### ISSUE TITLE
Redirect back to scenario page

### ISSUE THREAD

**Issue by mikalauskas** [cantino/huginn#1002]
it would be better to it redirects back to scenario page if i edit agent from its scenario page

**Comment by cantino** [comment]
That's a good idea, I'll take a look at it.

**Comment by cantino** [comment]
Should be fixed by #1003.  Mind testing?

**Comment by mikalauskas** [comment]
Yes! It works as should be :+1: 
also 'Back' button should work the same when you click on 'Show' or viewing events from agent details page, i think

**Comment by cantino** [comment]
Thanks for testing, @mikalauskas.  That's a good suggestion.  I just updated #1003, if you wouldn't mind hammering on it a bit.

**Comment by mikalauskas** [comment]
fix this too
https://github.com/cantino/huginn/blob/41f4d6e3395810d39e1262e3674f14e635f0f011/app/views/agents/_table.html.erb#L56
```
<%= link_to(agent.events_count || 0, agent_events_path(agent, return: (defined?(return_to) && return_to) || request.path)) %>
```
https://github.com/cantino/huginn/blob/agent_editing_returns/app/views/events/index.html.erb#L43
```
<%= link_to icon_tag('glyphicon-chevron-left') + ' Back'.html_safe, filtered_agent_return_link || agents_path, class: "btn btn-default" %>
```

**Comment by cantino** [comment]
Thanks, I updated it.

**Comment by level20peon** [comment]
Another place where the back button doesn't redirect properly:

Click on an Agents' "Actions" Menu -> "Show" -> "Events" -> "Back" leads back to the "Agents Overview" Page instead of the "Show" page.

Also:

Click on an Agents' "Actions" Menu -> "Show" -> "Actions" Menu -> "Edit agent" -> Save leads back to the "Agents Overview" Page instead of the "Show" page.

**Comment by cantino** [comment]
You mean the difference between "Summary" and "Details"?  I see what you mean, but I don't think it's worth the time to fix that particular issue right now.

**Comment by level20peon** [comment]
s/Show/Details/g
I was just referring to the name of the menu entry, but yes, that's what I mean. Maybe there are even yet other places where this occurs. I don't really understand why fixing the redirection back to the scenario page is more important than generally "fixing" the back-buttons, but I just added https://github.com/cantino/huginn/issues/1002#issuecomment-138565311 for the sake of completeness in this thread
