### ISSUE TITLE
DataOutputAgent : events_order don't work

### ISSUE THREAD

**Issue by yodaime08** [cantino/huginn#1005]
Hello,

I try to add an events_order to an DataOutputAgent 

{
  "secrets": [
    "classement20142015"
  ],
  "expected_receive_period_in_days": 2,
  "events_order": "[['{{Position}}', 'number', true]]",
  "template": {
    "title": "Classement Saison 2014/2015",
    "description": "Classement de ProA",
    "item": {
      "title": "{{Position}} - {{Equipe}}",
      "description": "J: {{Joue}} | G: {{Gagne}} - P: {{Perdu}}",
      "link": "{{Image}}",
    }
  }
}

But I have this error 

1 error prohibited this Agent from being saved:
events_order must be an array of arrays

I don't understand why. Can you give me the right syntax ?

**Comment by cantino** [comment]
@yodaime08, it should be 
```
"events_order": [["{{Position}}", string, true]]
```

I think

**Comment by yodaime08** [comment]
Same error 

{
  "secrets": [
    "classement20142015"
  ],
  "expected_receive_period_in_days": 2,
  "template": {
    "title": "Classement Saison 2014/2015",
    "description": "Classement de ProA",
    "item": {
      "title": "{{Position}} - {{Equipe}}",
      "description": "J: {{Joue}} | G: {{Gagne}} - P: {{Perdu}}",
      "link": "{{Image}}"
    }
  },
  "events_order": "[[\"{{Position}}\", \"string\", true]]"
}

**Comment by cantino** [comment]
I think you're putting it in as a string.  It needs to be an actual JSON array.

**Comment by yodaime08** [comment]
Sorry, I don't understand what you mean. {{Position}} need to be an array ?

**Comment by cantino** [comment]
No, the list of options needs to be in an array.  Like

```
  {
    "events_order": [
      ["{{Position}}", "string", true], 
    ]
  }
```

**Comment by yodaime08** [comment]
It works. Sorry for the misunderstanding
Thanks !

**Comment by cantino** [comment]
No problem, very glad it's working!  If this is fixed, feel free to close this issue.

**Comment by jspenney** [comment]
I have a similar problem. When I use just an expression for events_order in a data output agent, the sort works, but when I use an array, the tool changes the  expression
from this 
[{{date_published}}, "time", true]
to this
    }
  },
  "events_order": [
    "[\"{{date_published}}\", \"time\", true]"
  ]
}

any ideas why this is happening and how I can use the sort parameters

Thanks,
John


{
  "secrets": [
    "passblue_rss_02"
  ],
  "expected_receive_period_in_days": "5",
  "template": {
    "title": "Passblue RSS Feed",
    "description": "This is a feed of recent PassBlue posts, generated by Huginn",
    "item": {
      "title": "{{title}}",
      "link": "{{url}}",
      "author": "{{authors}}",
      "id": "{{id}}",
      "pubDate": "{{date_published}}",
      "description": "{{content}}"
    }
  },
  "events_order": [
    "{{date_published}}"
  ]
}
