### ISSUE TITLE
DeDuplicationAgent and DelayedJob workers issue

### ISSUE THREAD

**Issue by mikalauskas** [cantino/huginn#1006]
It looks like they emit the same event with id 3jarmn
one event come from agent#94
other one from agent#111
seems like they propagating at the same time and duplicate the same event

```
/var/log/huginn/jobs-1.log:Agent#95: Propagating new event as '3jarmn' is a new unique property.
```
```
/var/log/huginn/dj2-1.log:Agent#95: Propagating new event as '3jarmn' is a new unique property.
```
```
Your Events from uniq2
uniq2	~6h ago	{"id":"3jarmn",...	
uniq2	~6h ago	{"id":"3jarmn",...	
```

agent#95(uniq2) is deduplication agent
```
{
  "property": "{{id}}",
  "lookback": "0",
  "expected_update_period_in_days": "1"
}
```

also sorry for my english :(

**Comment by cantino** [comment]
Are you running two copies of threaded.rb simultaneously? It kind of looks like two are running when only one should be.

**Comment by mikalauskas** [comment]
I'm sure it's running only one bin/threaded.rb
just checked in htop

**Comment by cantino** [comment]
If somehow two copies of this Agent's check got queued, they could race and create two events.

@dsander or @knu, have you seen this before?

**Comment by mikalauskas** [comment]
yeah, I have multiple website agents with different sources which are sometimes have the same events

**Comment by cantino** [comment]
Wait, if you have multiple copies of the Agent, you'll definitely get repeating events.

**Comment by mikalauskas** [comment]
i mean 3 website and one deduplication like this
websiteagent1  websiteagent2  websiteagent3
                    \                |                 /
                       deduplicationagent

**Comment by virtadpt** [comment]
I'm seeing the same thing, too, with TwitterStreamAgent.  I've had to add a few more DeduplicationAgents to raise the S/N ratio.

**Comment by cantino** [comment]
That's concerning, we may have a bug then.  Any chance the remote system
takes a long time to respond... longer than the check period?  Basically,
I'm trying to think of any way that two simultaneous agent checks could
overlap with the same starting state. That would mean that they would both
see the new data, both think that it's new, and emit it.

**Comment by virtadpt** [comment]
My thinking is that it's the delayed job operators in a race condition but I can't prove it right now.  I'm not seeing any of Twitter's usual error messages in my logs, for what it's worth.

**Comment by dsander** [comment]
I guess a race condition would be possible with multiple delayed job workers because the`AgentReceiveJob` does not use a transaction. With just one threaded worker I don't see how this can happen.

**Comment by cantino** [comment]
I think he's running 1 threaded and one of the `bundle exec script/delayed_job -i 2 run` lines, so the lack of a transaction could be the problem if two copies of the `AgentReceiveJob` got enqueued by two different incoming events.  I didn't see how this was likely with `check`, but it does seem likely with `receive`.

@mikalauskas, would you mind editing `agent_receive_job.rb` to look like this and see if it helps?

```ruby
class AgentReceiveJob < ActiveJob::Base
  # Given an Agent id and an array of Event ids, load the Agent, call #receive on it with the Event objects, and then
  # save it with an updated `last_receive_at` timestamp.
  def perform(agent_id, event_ids)
    Agent.transaction do
      agent = Agent.find(agent_id)
      begin
        return if agent.unavailable?
        agent.receive(Event.where(:id => event_ids).order(:id))
        agent.last_receive_at = Time.now
        agent.save!
      rescue => e
        agent.error "Exception during receive. #{e.message}: #{e.backtrace.join("\n")}"
        raise
      end
    end
  end
end
```

**Comment by virtadpt** [comment]
Could ```ObjectSpace``` be useful here?

**Comment by cantino** [comment]
This transaction will likely help if the problem is duplicate runners.

**Comment by mikalauskas** [comment]
![image](https://cloud.githubusercontent.com/assets/2268118/11763650/559b8b16-a135-11e5-8ff4-d4b7607e93c2.png)

**Comment by cantino** [comment]
Sorry, what am I looking at?

**Comment by virtadpt** [comment]
It looks like the same event is being emitted by agent #14 through both a DelayedJob worker, and one of the threads in ThreadedWorker.  The weird thing is, they're about three minutes apart.

**Comment by cantino** [comment]
That's very odd.  Is that event ID the Huginn Event#id?

**Comment by mikalauskas** [comment]
#1432
