### ISSUE TITLE
GitHub not showing up under /services

### ISSUE THREAD

**Issue by deanishe** [cantino/huginn#1008]
I followed [the install instructions](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md) and everything seems to be running swimmingly except that there's no GitHub option under /services. I tried /auth/github manually, but that's a 404.

I've set `GITHUB_OAUTH_KEY` and `GITHUB_OAUTH_SECRET` in `.env`:

```bash
$ grep GITHUB_ .env
GITHUB_OAUTH_KEY=3a…
GITHUB_OAUTH_SECRET=6d…
```
and the settings appear to have been exported properly to `runit`:

```bash
$ ls /etc/service/huginn-web-1/env | grep GITHUB_
GITHUB_OAUTH_KEY
GITHUB_OAUTH_SECRET
$ ls /etc/service/huginn-jobs-1/env | grep GITHUB_
GITHUB_OAUTH_KEY
GITHUB_OAUTH_SECRET
```

I've checked that these files contain the correct values. I'm running the `production` environment and using revision f4b8e737.

Does anyone have any idea what might be going wrong?

**Comment by cantino** [comment]
Hey @deanishe, it looks to me that `gem 'omniauth-github'` is disabled in our Gemfile.  I'm not sure why, but try uncommenting it and running bundle locally, then updating your server.  If you need a hand, let me know.  If this fixes it, we'll figure out why it's defaulting to disabled right now.

**Comment by deanishe** [comment]
Hi @cantino, thanks for the fast response.

What does this bit mean exactly?

> running bundle locally, then updating your server

I don't have a local copy of huginn. It's only on my server.

**Comment by cantino** [comment]
Wait... I know why [this is commented out](https://github.com/cantino/huginn/blob/master/Gemfile#L44), we don't have a GitHubAgent yet: https://github.com/cantino/huginn/tree/master/app/models/agents  :) So someone would need to add that first.

**Comment by deanishe** [comment]
Well, that's a good a reason as any.

Thanks for your help!

**Comment by cantino** [comment]
I'll remove the config to prevent future confusion: https://github.com/cantino/huginn/pull/1013
