### ISSUE TITLE
Adding Service as a user

### ISSUE THREAD

**Issue by cescobarresi** [cantino/huginn#1009]
Hi, I've read many docs and issues regarding OAuth. The question is: a Huginn user can add a "generic" oauth Service from the UI or from cli?
For generic i mean not one of twitter, thirty seven, github, tumblr, dropbox nor wunderlist. I would like to connect to Spotify.

Is this possible or is necessary to do ruby coding?
Thanks
Francesco

**Comment by dsander** [comment]
Hi @cescobarresi,

I am afraid without an SpotifyAgent a Spotify service would not be working. However you can obtain a oauth_token from the [spotify web console](https://developer.spotify.com/web-api/console/get-album/) and use a WebsiteAgent to connect to the Spotify API. Here is an example accessing the albums endpoint (you need to replace the authorization with your auth_token):

```
{
  "expected_update_period_in_days": "2",
  "url": "https://api.spotify.com/v1/albums/4aawyAB9vmqN3uQ7FjRGTy?market=ES",
  "type": "json",
  "mode": "all",
  "extract": {
    "payload": {
      "path": "."
    }
  },
  "headers": {
    "Authorization": "Bearer token from the spotify web console"
  }
}
```

**Comment by cescobarresi** [comment]
Thank you @dsander for the quick answer.
The "problem" with this approach is that the token expires and I have to manually update it every X days.
Thanks.

**Comment by cantino** [comment]
Could we use a JavaScript Agent or a PostAgent to refresh it?

**Comment by cescobarresi** [comment]
I've studied a bit and it should be possible to keep the token up to date with a combination of available Agents. The question I could not answer is: 
can an Agent save data in to "credentials"?
or
can an Agent access data from another's "memory"?

**Comment by dsander** [comment]
I don't think that is possible at the moment, but we could allow the JavascriptAgent to update the credentials.

**Comment by cescobarresi** [comment]
That would be perfect!
Il 09/set/2015 16:28, "Dominik Sander" <notifications@github.com> ha
scritto:

**Comment by cantino** [comment]
It does seem reasonable to allow JavaScript agents to update Credentials, making Credentials a kind of shared memory.  Want to make a new Issue for this?

**Comment by cescobarresi** [comment]
An update for future reference:
Spotify API requires the access token to be updated every our. To do it with Agents (without programming a new service, which probably is the best way) is necessary to POST a request every 1h and save the result in a Credential.
#997 (which became 'add POST capabilities to WebAgent') will solve the POST part
#1025 solves part of the saving of the refreshed access token in a Credential

Will wait to see if #997 gets solved in some way and try again to setup refreshing of spotify access token.
Thanks.
