### ISSUE TITLE
What exactly does "propagate immediately" do in contrast to not using it?

### ISSUE THREAD

**Issue by level20peon** [cantino/huginn#1011]
I cannot find an elaborate answer anywhere in the wiki or issues.

**Comment by cantino** [comment]
Good question.  I've just added some documentation here: https://github.com/cantino/huginn/pull/1014

```
Normally, Huginn moves Events from source Agents to receiving Agents once
per minute. Checking this option will cause Events created by this Agent's sources
to be received immediately. This can use more CPU resources, but will decrease
the time between Event creation and being received by this Agent.
```

**Comment by virtadpt** [comment]
Beat me to it, Andrew.

The decrease in time between the creation of an event and the next agent in the network receiving it is considerable - on a decently provisioned system, three seconds at the outside.

**Comment by level20peon** [comment]
Alright, thanks guys!

**Comment by cantino** [comment]
No problem :)
