### ISSUE TITLE
RssAgent does not populate author and categories

### ISSUE THREAD

**Issue by apobekiaris** [cantino/huginn#1015]
I used it on http://feeds.feedburner.com/zerosharp but both author and categories do not have values

**Comment by cantino** [comment]
Hey @apobekiaris, welcome!  Would you mind seeing if #957 fixes this for you?

**Comment by apobekiaris** [comment]
thanks for the welcome! Excuse my newbie ignorance however #957 refers to
feednormalizer which i do not use. Furthermore the commit is dated Aug 3,
2015 and I got my docker image 3 days ago.

On Sun, Sep 6, 2015 at 12:34 AM, Andrew Cantino <notifications@github.com>
wrote:

> Hey @apobekiaris <https://github.com/apobekiaris>, welcome! Would you
> mind seeing if #957 <https://github.com/cantino/huginn/pull/957> fixes
> this for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cantino/huginn/issues/1015#issuecomment-137979683>.
>



-- 
Apostolis Bekiaris
Frameworks Technical Evangelist @ DevExpress
Blog @ http://apobekiaris.blogspot.com
Skype/twitter: tolisss

**Comment by cantino** [comment]
That pull request has not been merged yet, so you won't have it. We can see
if @knu is ready to merge it. That technology is replacing the innards of
what you're currently using in the RSSAgent.

**Comment by cantino** [comment]
Closing since #957 probably fixed it.
