### ISSUE TITLE
How to use the "headers" option of the WebsiteAgent?

### ISSUE THREAD

**Issue by level20peon** [cantino/huginn#1018]
This throws a `Options was assigned invalid JSON` at me:

    {
      "expected_update_period_in_days": "14",
      "url": "http://example.com",
      "type": "html",
      "mode": "on_change",
      "extract": {
        "content": {
          "css": "html",
          "index": "."
        }
      },
      "headers": {
        "accept-encoding" = "gzip, deflate, identity"
      }
    }

**Comment by cantino** [comment]
:, not =, in "accept-encoding" = "gzip, deflate, identity"

**Comment by level20peon** [comment]
Thanks, my bad.

However, I am experiencing a problem which drove me to try that headers option in the first place: `incorrect header check`.
After reading some threads of other projects they suggested (like this one for example: https://tickets.puppetlabs.com/si/jira.issueviews:issue-html/PUP-1680/PUP-1680.html) to explicitly set the header as a workaround.
This wasn't the case in my efforts.

    {
      "expected_update_period_in_days": "14",
      "url": "http://jobboerse.arbeitsagentur.de/vamJB/stellenangeboteFinden.html?execution=e1s1",
      "type": "html",
      "mode": "on_change",
      "extract": {
        "content": {
          "css": "html",
          "index": "."
        }
      },
      "headers" : {
        "accept-encoding" : "gzip; q=1.0, deflate; q=1.0; identity"
      }
    }

... or `"accept-encoding" : "gzip, deflate, identity"` result in an output like this one: http://pastebin.com/ALx0KWQ0

Any suggestions?

**Comment by cantino** [comment]
Odd, I'm not sure what that error means.  You could try `Accept-Encoding` (with capitals).  Headers are usually capitalized.

**Comment by level20peon** [comment]
Didn't make a difference. The only thing I can add for tracking this down is that this site worked when I used a previous huginn version (it was the one from July 30th). I definitely did use a ruby version < 2.0.0 there, but I can't remember which one it was exactly. So at some point along the road, something was implemented that broke the ability to fetch this site.

My best guess is that one of those two commits broke it:

#1: https://github.com/cantino/huginn/commit/0e06e8c25083c8e8ee94492c2698b6da1ec97d0f#diff-8b7db4d5cc4b8f6dc8feb7030baa2478
#2: https://github.com/cantino/huginn/commit/2caf45ab7dd1ddb454d3842e517d37f10e0fc35a#diff-8b7db4d5cc4b8f6dc8feb7030baa2478

... but I cannot test this right now, just seems to make sense at this point. Maybe I will find some time this week.

**Comment by level20peon** [comment]
ok, the culprit is the line `builder.use FaradayMiddleware::Gzip` inside `/app/concerns/web_request_concern.rb`. If I comment this out, the site is fetched just fine. Any idea how to proceed / fix this? Maybe implement a switch in the WebsiteAgent which allows this to be turned on/off?

**Comment by cantino** [comment]
@knu added that recently, he may have suggestions.

**Comment by cantino** [comment]
You could comment it out in the meantime.  It was supposed to be transparent, so you may have found a bug.

**Comment by knu** [comment]
Will look into this later.

**Comment by cantino** [comment]
@knu, I'm seeing this issue too.  I just got `Error when fetching url: incorrect header check
/Users/andrew/.rvm/gems/ruby-2.2.0@huginn/gems/faraday_middleware0.10.0/lib/faraday_middleware/gzip.rb:5`

**Comment by cantino** [comment]
URL was `http://jobboerse.arbeitsagentur.de/vamJB/stellenangeboteFinden.html?execution=e1s1&_arbeitszeitHeimarbeit.wert.value=on&_arbeitszeitNachtarbeit.wert.value=on&_arbeitszeitSchicht.wert.value=on&_arbeitszeitTeilzeitAbend.wert.value=on&_arbeitszeitTeilzeitFlexibel.wert.value=on&_arbeitszeitTeilzeitNachmittag.wert.value=on&_arbeitszeitTeilzeitSchicht.wert.value=on&_arbeitszeitTeilzeitVormittag.wert.value=on&_arbeitszeitVollzeit.wert.value=on&_arbeitszeitWochenende.wert.value=on&_behinderung.wert.value=on&_eventId_stellenangeboteSuchen%3Dnull%26request.parameter.jb.ankerhash.link.name%3Da358706291=Stellenangebote%20suchen&_keineAehnlicheBerufe.wert.value=on&allgemeineSuchkriterien.eingeklappt=false&arbeitsort.ort.wert=&arbeitsort.plz.wert=50677&arbeitsort.region.wert.wert=10&arbeitszeitVollzeit.wert.value=true&befristung.wert.wert=&beginnDerTatigkeit.wert=&berufe.wert=&betriebsgrosse.wert.wert=&fuhrungsverantwortung.wert.wert=&geringfugigeBeschaftigungMiniJob.wert.wert=2&jb.flow.event.hauptfunktion=_eventId_stellenangeboteSuchen&keineAehnlicheBerufe.wert.value=true&nurStellenMitFolgendenBegriffen.wert=betriebswirtschaftslehre&nurStellenOhneFolgendeBegriffe.wert=&stellenangeboteDerLetzten.wert.wert=2&suchbegriffebeziehung.wert.wert=2&umkreis.wert=50&weitereSuchkriterien.eingeklappt=false&o=1&jsessionid=123`

**Comment by knu** [comment]
The site (jobboerse.arbeitsagentur.de) might have broken support for the deflate encoding.

It responds to a request with `Accept-Encoding: deflate` with something un-inflate'able:
```
% curl -L -H 'Accept-Encoding: deflate' 'http://jobboerse.arbeitsagentur.de/vamJB/stellenangeboteFinden.html?execution=e1s1' | ruby -rzlib -e 'Zlib::Inflate.inflate($<.read)'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   423    0   423    0     0    623      0 --:--:-- --:--:-- --:--:--   622
100   451    0   451    0     0    463      0 --:--:-- --:--:-- --:--:--   463
100 11292    0 11292    0     0   8612      0 --:--:--  0:00:01 --:--:-- 2661k
-e:1:in `inflate': incorrect header check (Zlib::DataError)
        from -e:1:in `<main>'
```
The message `incorrect header check` is from zlib, so it's not ruby specific.
```
% curl -L -H 'Accept-Encoding: deflate' 'http://jobboerse.arbeitsagentur.de/vamJB/stellenangeboteFinden.html?execution=e1s1' | python -c 'import zlib,sys;print zlib.decompress(sys.stdin.read())'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   423    0   423    0     0    391      0 --:--:--  0:00:01 --:--:--   391
100   451    0   451    0     0    330      0 --:--:--  0:00:01 --:--:--     0
100 10623    0 10623    0     0   6278      0 --:--:--  0:00:01 --:--:--  6278
Traceback (most recent call last):
  File "<string>", line 1, in <module>
zlib.error: Error -3 while decompressing data: incorrect header check
```

**Comment by knu** [comment]
So, a workaround I can think of here is to exclude `deflate` from `Accept-Encoding`.  I've confirmed that fetching succeeds with either `"headers": { "accept-encoding": "identity" }` or `"headers": { "accept-encoding": "gzip,identity" }`.

**Comment by knu** [comment]
If there are many other sites with the problem with `deflate` encoding support, we could have a default Accept-Encoding value that does not have `deflate` in it.

**Comment by level20peon** [comment]
ok, so my test as described in https://github.com/cantino/huginn/issues/1018#issuecomment-138348998 would have worked if it didn't have `deflate` inside the request header.

Anyways, I don't think you should change the default as it obviously is that website's bad setup which leads to this error. I will use the accept-encoding option for this from now on.

If you don't have any further inquiries or suggestions, feel free to close this issue.

Thanks for the help!

**Comment by knu** [comment]
Oh wait, the `deflate` encoding might actually mean the DEFLATE format, and there obviously is a confusion here.
https://en.wikipedia.org/wiki/HTTP_compression#Problems_preventing_the_use_of_HTTP_compression

**Comment by knu** [comment]
We'd probably better avoid `deflate`, while gzip is more popular and should always be reliable.

**Comment by knu** [comment]
The said site returns a "raw" deflate stream while the Gzip middleware expects a "DEFLATE" zlib stream when the server says Content-Encoding is `deflate` (as defined in RFC).  Looks like major browsers support both, so we could request the Gzip middleware to do so.

**Comment by knu** [comment]
Rack::Deflater seems to produce a raw deflate stream too: https://github.com/rack/rack/blob/master/lib/rack/deflater.rb#L107-L108

**Comment by knu** [comment]
Just filed lostisland/faraday_middleware#119.

**Comment by level20peon** [comment]
nice catch!

**Comment by cantino** [comment]
Agreed we should remove Deflate for now I think.

**Comment by knu** [comment]
The above workaround should fix this issue, but it does not prevent the Gzip middleware from failing when the server, regardless of `Accept-Encoding`, returns a raw deflate stream with `Content-Encoding: deflate` anyway.

Let's see how it goes in lostisland/faraday_middleware#119.

**Comment by cantino** [comment]
Is this issue closable?
