### ISSUE TITLE
Atom authors event is a string with line breaks

### ISSUE THREAD

**Issue by sillygwailo** [cantino/huginn#1020]
When an Atom feed has the following for the author element in an item:
```
<author>
<name>Ford Prefect</name>
<uri>http://h2g2.com/</uri>
</author>
```

The event renders as:

```
  "authors": [
    "\n        Ford Prefect\n        http://h2g2.com//\n    "
  ],
```

Would it be possible to have the event look like this instead?

```
  "authors": [
  {
    "name": "Ford Prefect",
    "uri": "http://h2g2.com/"
  }],
```

**Comment by cantino** [comment]
I assume this is in the RSSAgent?

**Comment by sillygwailo** [comment]
Correct.



-- 
Richard Eriksson
justagwailo.com

**Comment by cantino** [comment]
Sounds like the RSSAgent doesn't understand nested values.  This would need to be added.  Does #957 perform any better?

**Comment by sillygwailo** [comment]
With the ```rss_agent-rss_parser``` branch, I get an event with:

```
  "authors": [
    "Ford Prefect"
  ],
```

which should fulfill my needs.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further!
