### ISSUE TITLE
Allow JavaScript agents to update Credentials

### ISSUE THREAD

**Issue by cescobarresi** [cantino/huginn#1022]
Allow JavaScript agents to update Credentials, making Credentials a kind of shared memory.
Maybe something like:

    this.credentials()
    this.credentials(name)
    this.credentials(nameToSet, valueToSet)

In this way the Credentials may be updated by an Agent and accessed be another Agent.
This could also help resolving issues like #1009

**Comment by cantino** [comment]
Good idea!
