### ISSUE TITLE
Add disable_ssl_verification option to the EmailAgent

### ISSUE THREAD

**Issue by level20peon** [cantino/huginn#1024]
I would like to request the option to accept faulty SSL certificates to the Email Agent, like it has been added to the `WebAgent` / `PostAgent` (and down the line to `app/concerns/web_request_concern.rb
`).

Right now I am using the workaround as found here: https://github.com/cantino/huginn/issues/810#issuecomment-97090083 (by adding `openssl_verify_mode: none` to the `config/smtp.yml` file) but I think this rather should be put into the Agents' configuration. What do you guys think?

**Comment by cantino** [comment]
Hey @level20peon, I don't think it's possible to do that per-message with ActionMailer.  What you could do is submit a PR that adds it as an environment variable to `config/smtp.yml`, similar to the other 7 lines that each environment has.  I'd suggest calling it `SMTP_OPENSSL_VERIFY_MODE`.  Would you be up for that?

**Comment by level20peon** [comment]
Just to be clear: Where would that variable be set? On a shell/script level?

**Comment by cantino** [comment]
Yes, I'd suggest adding it to `.env.example` and using it in `config/smtp.yml`.

**Comment by level20peon** [comment]
I wasn't able to create a pull request containing two files using the GIT webinterface, so here are two pull requests:
https://github.com/cantino/huginn/pull/1026
https://github.com/cantino/huginn/pull/1027

**Comment by cantino** [comment]
I fleshed this out in https://github.com/cantino/huginn/pull/1028
