### ISSUE TITLE
ASL Test scenario not creating any events

### ISSUE THREAD

**Issue by wasafiri** [cantino/huginn#1031]
@cantino I imported the "ASL Test" scenario you put together, and it is not creating any events. 

I also noticed a somewhat strange behavior that may or may not be related.

When I click Actions -> show for a ManualEventAgent, it shows that the event is simply {}. But if I click Actions -> Edit Event then it shows the event is 
{ "description": "american sign language" }.

**Comment by cantino** [comment]
When you view a ManualEventAgent, it gives you a UI to create events from it.  You can make one with the description you want and it should trigger.  It's not?

**Comment by wasafiri** [comment]
Does this help?
https://dl.dropboxusercontent.com/u/14456356/possible%20huginn%20bug.mov

**Comment by cantino** [comment]
Yes, very helpful!  I see the confusion.  The ManualEventAgent doesn't use it's options.  Instead, you use it to create one-off events by adding them in the "Manually Create Events" UI that you show at the beginning of the video.  If you put `{"description": "american sign language"}` in there and click "Submit", it should make an event that flows to your TriggerAgent for testing.

**Comment by wasafiri** [comment]
Ah! So the flow is different there. Might it make sense to remove the edit option from ManualEventAgents then, if options aren't used? The ManualEventAgent works the way you describe, however.

**Comment by cantino** [comment]
I just committed a textual clarification that will hopefully prevent future confusion: 5fa1824
