### ISSUE TITLE
error with dry running website agent

### ISSUE THREAD

**Issue by wasafiri** [cantino/huginn#1033]
Gist of error message:
https://gist.github.com/wasafiri/284fef33eb334ff008b7

Here's how I tried to parse it:
https://gist.github.com/wasafiri/27ef8ffeb40dec111f31

Looks like it has to do with uneven number of matches?

**Comment by level20peon** [comment]
https://github.com/cantino/huginn/blob/master/app/models/agents/website_agent.rb#L31

So yes, all of your patterns need to return the same number of results. I think it's not very elegant to parse the whole document (or json) for each element one wants to extract, so here's what I do (this is an example for a html document, but you might still adapt it to your json example):

1) Use the WebsiteAgent to extract the "master"-element which contains all of the sub-elements you want to extract
2) Use the EventFormattingAgent to split up those master-elements into the desired sub-elements via regex

**Comment by cantino** [comment]
Thanks @level20peon.  We do need to eventually figure something out for parsing nested structures.

**Comment by cantino** [comment]
Closing in favor of #990.
