### ISSUE TITLE
New agent: statsd

### ISSUE THREAD

**Issue by ssube** [cantino/huginn#1034]
I'm starting to use Huginn at work to integrate our dev/ops tools and would like to set up dashboards from the events we see. We're currently using datadog, which is backed by statsd for reporting and integration with applications. From reading up on the statsd gem, it looks like getting data from an application into statsd is very simple and could probably be set up with Huginn, allowing events to feed into metrics. The gem sends data to statsd, so it should work with any collection and dashboarding system, from Graphite to Datadog.

Would this feature be welcome in the project? I have little/no familiarity with Ruby or Huginn's codebase, but am more than willing to try and put a prototype together, if there is interest and I could get some feedback.

**Comment by virtadpt** [comment]
There is talk of adding a REST API to Huginn (tickets #626, #353), and on the back end there is a rudimentary API (poke around in the scenario, agent, and job sections.

I'm working on implementing something like this with collectd (https://collectd.org/) but, system-level stuff aside I haven't had any success with monitoring Huginn itself.  I think this has potential.

**Comment by cantino** [comment]
Hi @ssube, welcome!

I think an Agent that sends incoming Events to Statsd would be a really good contribution!

**Comment by ssube** [comment]
I'll start looking into this, now that we have a Huginn server running and puppetized.

**Comment by cantino** [comment]
Awesome, let us know if you have questions!

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further!
