### ISSUE TITLE
Website Agent Keep Events timer not working?

### ISSUE THREAD

**Issue by jonathanl01** [cantino/huginn#1035]
I have a Website Agent setup to check every hour and to keep events for 1 hour.  Once the previous payload/event's "Expires in" timer reaches the end, it reverses and just starts increasing in time.  Not sure if this is a bug or not.  I have tried setting the Website Agent mode to both "merge" and "all" and it still does it.

**Comment by dsander** [comment]
Hi @jonathanl01,

did you modify `EVENT_EXPIRATION_CHECK` in your `.env` file? Per default the expiration check just runs every 6 hours. When you set it to something like `15m` the events should be purged as expected.

**Comment by jonathanl01** [comment]
@dsander I did not know this, I'm just running a local instance on Docker to test it out and set the "Keep events" setting for the Website Agent to 1 hour. Thank you.
