### ISSUE TITLE
live demo system

### ISSUE THREAD

**Issue by Matthias84** [cantino/huginn#1037]
Hi,

while it's easy to use Docker to start with an local instance for some experiments, this might still prevent users from give it a try. So I suggest that someone keeps an public demo running, where users can explore the UI and agents and get an idea about this project :)

**Comment by cantino** [comment]
Hey @Matthias84.  Historically we've used self-hosting on Heroku for that.  Maintaining a demo system with many people's test Agents has sounded like a lot of work, so I don't think anyone has bitten it off yet.

**Comment by dsander** [comment]
[Docker](https://github.com/cantino/huginn/blob/master/doc/docker/install.md) is another good and easy option to test huginn, especially on OSX and Windows as [kitematic](https://kitematic.com/) recently got support for windows.

**Comment by Matthias84** [comment]
Sadly it's IMHO not true for an enterprise environment (Win, proxy, firewalls, ...) even I agree with @dsander that kitematic looks pretty nice :-)

I understand that it makes a lot of work to maintain demo instances, but on the other hand it might invite more people to learn what huginn does and how you can use it. If there is no manpower to run a live system, thats not an essential problem.

**Comment by cantino** [comment]
If you'd be open to running such a system, we'd gladly accept your support. :smile:

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further or build this!
