### ISSUE TITLE
Digital Ocean Huginn

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1038]
Is there a easy way to have Huginn running in Digital Ocean for a novice. Does anyone have a how to on this.

**Comment by signallhill** [comment]
I am following Installation from source guide in documents and I am stuck at this point

https://github.com/cantino/huginn/blob/5fa18248666308624afa75ad4e3a370e26a3ae24/doc/manual/installation.md#install-init-script

What do I need to do in Procfile

All steps before this is done with no issues. I am uncertain what I need to do here.

Edit the Procfile and choose one of the suggested versions for production 

sudo -u huginn -H editor Procfile

**Comment by cantino** [comment]
Hey @signallhill.  I think what @dsander meant here was for you to edit that file with an editor of your choice (`vim`, `nano`, `emacs`, `pico`, etc.).  Have you used one of these before?

**Comment by signallhill** [comment]
Sorry for the confusion. My question was "choose one of the suggested versions for production". Am I suppose to delete the "#" under the production section either for Threaded or Old Version?

I used vim like the guide says and I only know Pressing I does insert and ZZ to save and quit.

**Comment by virtadpt** [comment]
Use whatever text editor you're comfortable with.  If you're familiar with nano, use that.

**Comment by dsander** [comment]
@signallhill Yes exactly I would recomond this for a production installation:

```
###############################
#         DEVELOPMENT         #
###############################

# Procfile for development using the new threaded worker (scheduler, twitter stream and delayed job)
#web: bundle exec rails server -b0.0.0.0
#jobs: bundle exec rails runner bin/threaded.rb

# Old version with separate processes (use this if you have issues with the threaded version)
# web: bundle exec rails server
# schedule: bundle exec rails runner bin/schedule.rb
# twitter: bundle exec rails runner bin/twitter_stream.rb
# dj: bundle exec script/delayed_job run

###############################
#         PRODUCTION          #
###############################

# You need to copy or link config/unicorn.rb.example to config/unicorn.rb for both production versions.
# Have a look at the deployment guides, if you want to set up huginn on your server:
# https://github.com/cantino/huginn/doc

# Using the threaded worker (consumes less RAM but can run slower)
web: bundle exec unicorn -c config/unicorn.rb
jobs: bundle exec rails runner bin/threaded.rb

```

**Comment by signallhill** [comment]
@dsander Thanks. The instruction is very easy to follow, its just I am not familiar with all this. 

I have last couple of questions I am almost at end.
USING HTTPS section

Use the huginn-ssl Nginx example config instead of the huginn config:
    sudo cp deployment/nginx/huginn-ssl /etc/nginx/sites-available/huginn - DONE
    Update YOUR_SERVER_FQDN. - DigitOcean gives IP address can I use that or do i need to point a domain to the IP and update here?
    Update ssl_certificate and ssl_certificate_key. - What am I doing here/How do I do this

**Comment by dsander** [comment]
@signallhill If you do not own a domain which you can point to your DigitalOcean droplet IP **and** remove the default nginx config, the server_name can be anything, nginx will use the huginn "server" even if you just nagicate to `https://<your-DO-ip>`

Without a domain name you can not use a real certificate, if you are using a Ubuntu as base you can use a self-signed certificate which should be been created automatically by adding those to your huginn nginx config:

```
      ssl_certificate      /etc/ssl/certs/ssl-cert-snakeoil.pem;
      ssl_certificate_key  /etc/ssl/private/ssl-cert-snakeoil.key;
```

**Comment by signallhill** [comment]
I used Debian instead of Ubuntu. I have a domain I can point to the IP. In that case is the SSL certificate something I would buy and provide?

**Comment by dsander** [comment]
@signallhill Yes, the setup depends on the vendor you buy the ssl certificate from. Goggling for  `<vendor> ssl nginx` should give you instructions on how to set it up for almost all of them.

**Comment by signallhill** [comment]
@dsander THANK YOU 
All done. Just logged in to the new install of huginn.

The instruction was very easy to follow all I did was create a new droplet and just copy paste the commands in the console in the website. Never used DigitalOcean and dont know anything other than Windows. Amazing work.  Brilliant.

**Comment by cantino** [comment]
Awesome!

**Comment by dsander** [comment]
@signallhill Really glad the guide was helpful, thanks!

**Comment by signallhill** [comment]
@dsander I am trying to update huginn using the following instruction

https://github.com/cantino/huginn/blob/master/doc/manual/capistrano.md#deploy-updates-via-capistrano

I have Debian 8.1x64 with 1 GB ram

I did gem install capistrano - no problem

Set password sudo passwd huginn - no problem

Update .env for capistrano - no problem

Export Init script - no problem

when I do 

cap production deploy 

I get this 

LoanError: cannot load such file -- capistrano/bundler

![Uploading Untitled.png…]()

**Comment by mayailkour** [comment]
What do you think of adding Huginn to the [DigitalOcean Marketplace](https://marketplace.digitalocean.com/)?
