### ISSUE TITLE
How to export/import agents? or add/edit agents in CLI?

### ISSUE THREAD

**Issue by waldens** [cantino/huginn#1039]
1/ There are 50+ agents at my huginn in heroku, and now they want to move to VPS. Is there any other way to move these agents of huginn from heroku to Ubuntu, except for copy and paste json of every agent one by one, which is so slow? can they be export all at once, and then all import? (only agents, no need events)

2/ Is there any other way to add/edit agents except for http? SSH/CLI is much much more faster than HTTP in both network speed and operating ways. Sometimes editing agent and troubleshooting in browser is a little annoying: slow net speed, endless buttonsss and so many tabs in browser…can agents be add/edit by CLI/SSH or manipulating some files like?

thanks.

**Comment by dsander** [comment]
Hi @waldens,

heroku has documentation on how to [download database dumps](https://devcenter.heroku.com/articles/heroku-postgres-import-export). You could then import the database onto your VPS, the biggest problem is that we do not have a documented and tested way to run Huginn on PostgreSQL outside of heroku.
Working  on that is on my todo list and I hope to get to it on the weekend, until then a few pointers that might help:

* follow the manual installation guide but replace mysql with postgresql
* restore your heroku database to your local postgresql database
* export `ON_HEROKU=true` as an environment variable before running `bundle install`
* change the database configuration in `.env` to use the `postgresql` adapter

**Comment by dsander** [comment]
Sorry, kind of missed your main question. No, sadly there is no way to export all agents, if you have them grouped into scenarios you could export and import them.

**Comment by cantino** [comment]
I know @TildeWill was investigating this too.

**Comment by waldens** [comment]
Thanks @dsander ! Never noticed scenarios exist and what it is! It's exactly what I want, as you said, just group them all into scenarios and share. thanks! also thank you @cantino
