### ISSUE TITLE
DataOutputAgent : events_order don't work 

### ISSUE THREAD

**Issue by jspenney** [cantino/huginn#1041]
I have a similar problem to DataOutputAgent : events_order don't work #1005
https://github.com/cantino/huginn/issues/1005

 When I use just an expression for events_order in a data output agent, the sort works, but when I use the json array, the tool changes the expression
from this 
[{{date_published}}, "time", true]
to this
}
},
"events_order": [
"[\"{{date_published}}\", \"time\", true]"
]
}

any ideas why this is happening and how I can use the sort parameters

Thanks,
John

{
"secrets": [
"passblue_rss_02"
],
"expected_receive_period_in_days": "5",
"template": {
"title": "Passblue RSS Feed",
"description": "This is a feed of recent PassBlue posts, generated by Huginn",
"item": {
"title": "{{title}}",
"link": "{{url}}",
"author": "{{authors}}",
"id": "{{id}}",
"pubDate": "{{date_published}}",
"description": "{{content}}"
}
},
"events_order": [
"{{date_published}}"
]
}

**Comment by knu** [comment]
`[{{date_published}}, "time", true]` is not a valid JSON expression.  `["{{date_published}}", "time", true]` is.

**Comment by jspenney** [comment]
Akinori,
Thanks for your reply.
When I put ["{{date_published}}", "time", true] into the huginn tool to
edit the dataoutputagent, in gets turned to this and it doesnt work
propery. Any ideas of how to avoid this?
   }
  },
  "events_order": [
    "[\"{{date_published}}\", \"time\", true] "
  ]
}

**Comment by knu** [comment]
You seem to have happened to insert the expression as string.  Use the "[" button to create an array container and then put three elements `{{date_published}}`, `time`, and `true` in it. (Huginn treats `true` and `"true"` equally)
Alternatively, click on the toggle button and use the plain text area to put the expression as it is.

**Comment by jspenney** [comment]
Akinori,
I have got it to work. I needed two levels of brackets.
  },
  "events_order": [
    [
      "{{date_published}}",
      "string",
      "true"
    ]
  ]
}

Thanks for your help,
John

**Comment by knu** [comment]
Yes, that's how you do it! (except `"time"` misspelled as `"string"`, although it wouldn't be a problem unless the feed has many different timezones mixed)

**Comment by knu** [comment]
Now I feel like the doc and perhaps the UI should be improved.

**Comment by jspenney** [comment]
UI's can always be improved. I am a newbie at JSON so a few more real life agents would be helpful.
Thanks for your help!
