### ISSUE TITLE
Sending Mail Issue

### ISSUE THREAD

**Issue by jdragoo** [cantino/huginn#1042]
I have been running Huginn in development for a while and it works great.  I decided to setup a server in production now and all is working well there except that the email will not send.  I have double checked my credentials and have the exact setup in my development side and that works fine.  Is there another place other than the .env file that I need to configure in order to make email work by any chance?

**Comment by jdragoo** [comment]
I forgot to put the error in.  535-5.7.8 Username and Password not accepted. Learn more at is what is logged in production.log

**Comment by dsander** [comment]
Hi @jdragoo,

as far as I know copying the SMTP section of `.env` should be enough. I do not know if it is still a thing, but some email providers used "pop/imap before smtp" to 'authenticate' the email sending. That could explain your working local setup and it not working in production. Which email provider are you using? I use http://mandrillapp.com without any issues, their service is free for 12000 emails a month.

**Comment by jdragoo** [comment]
I have my own email server and in my logs I don’t seem to have any requests.  I’m thinking that my install is not even using my .env settings.

**Comment by dsander** [comment]
How did you install your production instance, did you use the [installation guide](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md)?

**Comment by jdragoo** [comment]
I did.  I followed it step by step.  I’m running through it again now just to make sure I didn’t miss anything.

**Comment by dsander** [comment]
That's odd your SMTP `.env` configuration should be exported to `/etc/service/huginn-web-1/env/SMTP_*` after you ran `rake production:export` it it's there huginn should use the configuration.

**Comment by jdragoo** [comment]
Well, I did miss a step in the installation guide.  I failed to export it after I make changes to .env.  I just did that and of course it works great.  Sorry for the troubles.

**Comment by dsander** [comment]
No worries, glad it works :smile:
