### ISSUE TITLE
Pass attachments to Slack

### ISSUE THREAD

**Issue by ssube** [cantino/huginn#1047]
The [Slack API accepts "attachments"](https://api.slack.com/docs/attachments), which are very helpful for pretty updates coming in from other tools. It looks like the Slack library used by Huginn [also has support for them](https://github.com/stevenosloan/slack-notifier#additional-parameters), but Huginn itself does not.

As far as I understand, it would mean changing [somewhere around this line](https://github.com/cantino/huginn/blob/master/app/models/agents/slack_agent.rb#L70) to detect whether `opts` has an attachment and pass it along. Is there a good way to do that without another surrounding `if` and four different calls to `ping`?

**Comment by cantino** [comment]
I don't know the Slack API, but it looks like we could build a hash above those lines and then configure it based on the Agent's options.  Want to give it a shot?

**Comment by ssube** [comment]
I've made a small change and created a pull for feedback. This may be wildly off base (my only Ruby experience is through Puppet), but seems to work. If there's any cleanup to do, I'll get on that asap.

**Comment by ssube** [comment]
The CI build is failing and I have no idea how to resolve that. From what I can tell, the hash keys are of the wrong type, so one of the relevant tests is failing. Converting the keys to strings didn't seem to help, so I'm not sure what is going on there.
