### ISSUE TITLE
Running Huginn in a Docker container

### ISSUE THREAD

**Issue by wasafiri** [cantino/huginn#1048]
Setting up Huginn via Docker.

Ran `docker pull cantino/huginn` then `docker pull postgres`.

Next, In the Docker instructions, this section shows how to link Huginn with the postgres container:

`docker run --rm --name huginn --link huginn_postgres:postgres -p 3000:3000 -e "HUGINN_DATABASE_USERNAME=huginn" -e "HUGINN_DATABASE_PASSWORD=pass@word" cantino/huginn`

Is huginn_postgres a constant variable or does it change based on individual setups?

I keep getting "Error response from daemon: Could not get container for huginn_postgres"

**Comment by cantino** [comment]
@dsander, do you know?

**Comment by dsander** [comment]
@cantino I have never tried to link the docker container to postgres, will check if and how it works.

@wasafiri Linking to a mysql database definitely works if you just want to try out huginn.

**Comment by dsander** [comment]
I now know that the docker container does not work with postgres, I hope to find a solution using #1040 on the weekend.

**Comment by deanputney** [comment]
In this case `huginn_postgres` is the name of the postgres container you're connecting to Huginn. You should first run the postgres container so it exists and the Huginn container can find it. Something like this:

    docker run -e POSTGRES_PASSWORD=mysecretpassword --name huginn_postgres -d postgres

You could name it anything and adjust accordingly.
