### ISSUE TITLE
WebsiteAgent: how to extract from event payload instead of url

### ISSUE THREAD

**Issue by mflau** [cantino/huginn#1050]
i am using (step1) website agent or rss agent to detect changes, (step2) website agent to fetch content and (step3) data output agent to generate rss. i have several simular sets of agents to generate fulltext rss.
i want to use a website agent to extract links and image from (step2) website agents.

in a website agent, i have to provide url to extract content
{
  "expected_update_period_in_days": "1",
  "url": "{{url}}",
  "type": "html",
  "mode": "merge",
  "extract": {
    "description": {
      "css": "div.article-body",
      "value": "."
    }
  }
}
how can i extract from source event payload content, such as decription, instead of fecch a file from event url.
or is there another agent that extract from event payload instead of url?

**Comment by cantino** [comment]
Hey @mflau, that's an interesting use-case.  I don't think that's possible at the moment besides using a formatting agent, which isn't a great way to parse HTML. This would be an interesting contribution if you'd like to work on it.

**Comment by mflau** [comment]
@cantino, i would be happy to work on it if i know ruby......

**Comment by cantino** [comment]
Ah, no worries.  I'm not sure if this should be a feature of the WebsiteAgent, or a new Agent, though.

**Comment by mikalauskas** [comment]
there is url_from_event but we can implement extract_from_event mode

**Comment by HyShai** [comment]
+1 would love this feature

**Comment by hunhejj** [comment]
+1 I was just looking for the same feature as I also have some usecases (want to extract an image url from the description with css rather than using regexp in a formatter). Looking forward for a "extract_from_event" mode!

**Comment by michal-polrolniczak** [comment]
+1 Thats something we could all use

**Comment by cantino** [comment]
Added a prototype of this in #1161 if someone wants to test it.

**Comment by cantino** [comment]
Would someone who :+1:'d this mind testing the feature?

**Comment by cantino** [comment]
@mflau, @mikalauskas, @HyShai, @hunhejj, or @bigretromike, would one of you mind testing this since you asked for the feature and I took the time to write it?

**Comment by HyShai** [comment]
I'm really sorry about this - I'm very excited to test it but I just haven't found any time recently. I plan on doing it over the holidays when my schedule will be more clear. 

I very much appreciate your hard work on this feature, and for Huginn in general!!

**Comment by cantino** [comment]
No worries, sorry for being grouchy :)

**Comment by HyShai** [comment]
Yeah, I know the feeling - work hard on something without feedback or appreciation. :(

**Comment by bigretromike** [comment]
@cantino I can test it, but I didnt touch my huginn since I added that tweet agent. 
Any sugestion how to update to your version from there ?
I dont mind checking it running 24/7 so i need info how to check it

**Comment by hunhejj** [comment]
Hey @cantino, sorry for not replying! As I mentioned in one of my [previous comments](https://github.com/cantino/huginn/issues/1127#issuecomment-153473233), I've already made a temporary working solution for myself and now I am a bit afraid that after applying your version I won't be able to switch back to mine again :s I am still confused with git.

**Comment by bigretromike** [comment]
Can you copy your working dir and backup it before doing this also git is
for versioning right ?
18 gru 2015 21:47 "hunhejj" <notifications@github.com> napisał(a):

**Comment by cantino** [comment]
I understand if switching to this branch is difficult in your setup and I don't want you to break something you depend on.  I'll check this out myself and get it merged soon.

**Comment by cantino** [comment]
Merged!  The new option is called `data_from_event` and uses a Liquid template to return data to be parsed.
