### ISSUE TITLE
CCS/Assets missing after a clean installation

### ISSUE THREAD

**Issue by qmaxquique** [cantino/huginn#1052]
**Hi there!**
I'm trying to develop a script to deploy Huginn at Terminal.com.
I was following the installation steps documented [here](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md) to create a script that automates the deployment.

Btw,this is the script that I'm writing, in case you want to see the steps that I followed: https://github.com/terminalcloud/apps/blob/master/huginn_installer.sh

**Everything seems to be just fine, but when I try to test the app, I get it completely unformatted.**

The browser console say this:
```
GET https://terminal39532-3000.terminal.com/assets/application-217f07c27970aab29070e0ef3564a0242db68b651934ce399e1a559bc7db8500.css 
(index):10 
GET https://terminal39532-3000.terminal.com/assets/application-1d50e510c33be250476689b997c80411a95686c74d2fb3d8cd61a0b9e084b42b.js 
(index):180 Uncaught ReferenceError: $ is not defined(anonymous function) @ (index):180
(index):61 
GET https://terminal39532-3000.terminal.com/assets/spinner-arrows-f4cfc5bc84f34fa882bc9125cd8730bb4ea4844c0ac6fd981bae2de9bb33aebc.gif 404 (Not Found)
(index):164 
GET https://terminal39532-3000.terminal.com/assets/odin-4aea0258f53748e9cc20b6ddd655824d8d1b26901015d43ad97c6d166bf88227.jpg 404 (Not Found)
```

Here is where the application might be running (you will be able to see the issue by yourself)
https://terminal39532-3000.terminal.com/

In order to speed up the debug process, I've created a shared Terminal here: https://terminal39532.terminal.com/

I will leave that machine open for a while, so you guys can snoop around.
Any help is appreciated! 

Thanks,
Enrique

**Comment by dsander** [comment]
Hi Enrique,

in the production environment rails per default expects the web server to deliver the static assets in `public/assets` to be served by the webserver, see the [example nginx configuration](https://github.com/cantino/huginn/blob/master/deployment/nginx/huginn#L62-L67). If that is not an option on Terminal.com you can set `RAILS_SERVE_STATIC_FILES` in the `.env` file to something (true,1, everything should work)

I modified the `.env` file on the Terminal you shared and it looks fine. That Terminal.com feature is **really** awesome, I like to debug issues this way :smile:

**Comment by qmaxquique** [comment]
I'm just starting with Huginn but I think you guys have a great application here.
Thank you, Dominik!

**Comment by dsander** [comment]
Glad you are liking Huginn!

We already have/had a [public snap](http://blog.terminal.com/huginn-on-terminal-com/) on Terminal.com but I think that version is outdated and does not work anymore, would you mind sharing yours once you have it working and update the wiki?

Terminal.com sounds like a great option to try Huginn for free now that Heroku changed their free plan.
