### ISSUE TITLE
Help filtering feeds

### ISSUE THREAD

**Issue by Pcsl** [cantino/huginn#1054]
Hi there,

I'm just a newbie that needs help to filter some RSS feeds after Yahoo! Pipes closure.
I'm following this tutorial: https://github.com/cantino/huginn/wiki/Generating-a-filtered-full-text-RSS-feed
However in the TriggerAgent I'm not sure about what are the available values for "path". I want to trigger only when the keywords "error" or "london" appears in the feed full text. What should it be the right value for path in this case?

I just feel I'm missing something to set it up everything in the right way because I can't find the documentation for everything I want to do. Anyway I think huginn is really powerful in the right hands.

Thank you for your hard work.

**Comment by cantino** [comment]
Welcome! You'll want to look at the format of the events coming into the
filter and then set path to the name of the key that has the text you care
about.  You'll want to use the regex filter type.

**Comment by Pcsl** [comment]
Thank you for your help. I got it to filter it right. However for some reason Feedly doesn't recognize the generated feed. I sent them a message to try to find out why it's not working with them.

I have another question if you don't mind, it's about the Twitter Stream Agent. Look at this filter for example:
test1 test3
It just matches tweets like "test1 test3 test5" but not "test1 test2 test3". How would be the right way to specify that I want to match both words but there can be other words between them?

**Comment by cantino** [comment]
I'm actually surprised, I thought that it would allow test1 test2 test3.

**Comment by Pcsl** [comment]
I'm still testing it. I would let you know if the matching from Twitter Stream Agent is working as you expected. 

One more question, I'm trying to add the expanded_url from Twitter Stream Agent as you can see in this code to the Data Output Agent as the link key.
```
"urls": [
        {
          "url": "http://t.co/MVRLtIr2u8",
          "expanded_url": "http://wp.me/p6yVwI-in",
          "display_url": "wp.me/p6yVwI-in",
          "indices": [
            45,
            67
          ]
        }
      ],
```

I tried using {{expanded_url}} and {urls.expanded_url}} but none of them worked.

By the way, this issue should have the tag "help-wanted" but didn't know how to add it...

**Comment by cantino** [comment]
Maybe something like `"{{ urls | map: 'expanded_url' | join: ',' }}"` would work?  You're dealing with an array of data here.

**Comment by Pcsl** [comment]
Thanks, I think it should work but it doesn't. 
I tried "link": "{{ urls | map: 'extended_url' | join: ',' }}" but it doesn't return anything...

**Comment by cantino** [comment]
`extended_url` or `expanded_url`?

**Comment by Pcsl** [comment]
Oh, sorry, I used
```
"link": "{{ urls | map: 'expanded_url' | join: ',' }}"
```
and it's not working :S

**Comment by cantino** [comment]
Ah, ok.  Mind sharing an example Scenario so I can take a look?

**Comment by Pcsl** [comment]
I first use the Twitter Stream Agent to filter tweets that contain the keyword #errorfare
```
{
  "filters": [
    "#errorfare",
  ],
  "expected_update_period_in_days": "50",
  "generate": "events"
}
```

Then using the Data Output Agent I try to create a RSS feed from that agent as source:

```
{
  "secrets": [
    "mykey"
  ],
  "expected_receive_period_in_days": "30",
  "template": {
    "title": "Error fare",
    "description": "Error fare tweet",
    "item": {
      "description": "{{text}}",
      "link": "{{ urls | map: 'expanded_url' | join: ',' }}",
      "pubDate": "{{created_at}}",
      "title": "{{text}}"
    }
  }
}
```

So the feed is generated and everything works as expected but the link field for the feed.

**Comment by cantino** [comment]
Looks like it'd be `entities.urls`, not `urls`.  Isn't it inside an `entities` hash?

**Comment by Pcsl** [comment]
Yeah, as usual I made a noob mistake. You were right. It's working now! Thank you very much for your help! This tool is really powerful, I am glad you share such an awesome tool like this one.

Thank you for your hard work!

**Comment by cantino** [comment]
No worries, it's an easy mistake to make.  I'm glad it's working!  Let us know what you build with Huginn :)
