### ISSUE TITLE
Huginn on Heroku: change from Sendgrid to own mailserver

### ISSUE THREAD

**Issue by MartinButter** [cantino/huginn#1061]
Hi there, I did deploy Huginn on Heroku, and took the sendgrid option just to test everything. Now, as I installed some agents and everything works fine, I want to get rid of Sendgrid and use my own mail server. But I couldn't find a .env file in the Huginn directory at Heroku where I could change the SMTP-details. Maybe I'm on the wrong track. Could someone tell me what to do?

**Comment by cantino** [comment]
Hey @MartinButter, welcome! You'll need to use the `heroku config` command on the console to change ENV settings in Heroku.  See the wiki for some more info about this, and please let me know if you run into any issues.

**Comment by MartinButter** [comment]
Thank you! Did'nt get that heroku config is a console command before. Now everything works fine! Huginn is really amazing and helps me a lot.

**Comment by cantino** [comment]
Awesome!
