### ISSUE TITLE
Javascript Question

### ISSUE THREAD

**Issue by Yamavu** [cantino/huginn#1064]
Hello There!

I thought of implementing a simple image downloader, that loads the data into a Canvas object and emits a base64 of the data. It this possible?

My response is: `JavaScript error: require is not defined` 
I thought V8 has a `Canvas` object and a public `require()`. 

Sorry if this question seems trivial, it's my first JS outside of a browser engine.

```javascript
Canvas = require('canvas');

function convertImgToBase64(url, callback, outputFormat){
	var img = new Canvas.Image();
	img.crossOrigin = 'Anonymous';
	img.onload = function(){
	    var canvas = new Canvas();
	    var ctx = canvas.getContext('2d');
		canvas.height = this.height;
		canvas.width = this.width;
	  	ctx.drawImage(this,0,0);
	  	var dataURL = canvas.toDataURL(outputFormat || 'image/png');
	  	callback(dataURL);
	  	canvas = null; 
	};
	img.src = url;
}

/*Agent.check = function() { ..... };*/

Agent.receive = function() {
  var events = this.incomingEvents();
  for(var i = 0; i < events.length; i++) {
    convertImgToBase64(events[i].payload.url, function(dataURL){
      this.createEvent({ 'data': dataURL });
    });
  }
}
```

**Comment by cantino** [comment]
Hey @Yamavu, welcome!  Huginn doesn't currently have a full node-style V8 environment, so `require` and the browser DOM (like Canvas) are not available.  It has the basic JS environment provided by [therubyracer](https://github.com/cowboyd/therubyracer).

**Comment by cantino** [comment]
If you'd like to try and add additional libraries to therubyracer environment, we'd be open to that.

**Comment by Yamavu** [comment]
Thanks @cantino for the warm welcome. This just looked like the easiest script to implement something like a "download file" agent, as suggested on other issues ( #809 ). I didn't really expect therubyracer to have a limited featureset, but just forwards everything to V8. 

I guess best solution for my case would be implementing the above agent in Ruby.

**Comment by Yamavu** [comment]
I researched a bit and stumbled upon #433 , which tackles a similar problem, but is over 1 year old by now. Not sure what's the status there.

I'd split the problem in 3, 
* **file aquirement**
 * Amazon S3 filesystem
 * Public HTTP(s) location
* **file memory**: How to store the files on the server for immediate retrieval
 * Location on disk (not available on heroku)
 * Serialization in Database
* **file forwarding in agents**: Now here's the more complex part, because many agents could make use of files. Upgrading the bracket syntax a bit could help there. I'm thinking about something like:  
 * `{{public_file|http://example.com/image.jpg|base64}}` (downloads a public file and prints the Base64 serialisation)
 * `{{local_file|/path/to/image.jpg|base64}}` (takes a local file and prints the Base64 serialisation)

However these ideas are raw and I still gotta think asbout them, but they should work, at least to some degree.

**Comment by virtadpt** [comment]
What about a local WebDAV server?  Maybe you could pass the file off to POST Agent to store it?

**Comment by cantino** [comment]
Your suggestion of using a Liquid command is interesting.  What is your final use-case here?

**Comment by cantino** [comment]
Closing since we haven't heard back.  Hope it's working for you!
