### ISSUE TITLE
Help retweeting

### ISSUE THREAD

**Issue by SmokE-PGF** [cantino/huginn#1065]
How do I retweet a tweet using the twitter agent?

**Comment by cantino** [comment]
Welcome @SmokE-PGF.  I don't think it's currently possible.  You could potentially try to add that to the TwitterUserAgent or TwitterPublishAgent if you'd like.

**Comment by SmokE-PGF** [comment]
Thanks @cantino 

I am fairly new to ruby I only just started glancing at ruby coding due to huginn so if there is anyone that have some expertise and free time please feel free to help out or if there are any good resources to look at for ruby coding. I will also be looking into it.

**Comment by cantino** [comment]
Would you envision this Agent as receiving events that contain tweet ids and then retweeting those?

**Comment by SmokE-PGF** [comment]
Yeah that would be easier route to go with

**Comment by SmokE-PGF** [comment]
Perhaps in conjunction with the aid of #1076 TwitterSearch agent to include tweet ids so that it can have a specific search term that gets retweeted

**Comment by cantino** [comment]
That seems like a reasonable addition.

**Comment by SmokE-PGF** [comment]
Wonder if this could be done like #1068 the favorite agent

**Comment by bigretromike** [comment]
yes, it only retrive the post the user you configure it with favored.

**Comment by Jngai** [comment]
@cantino I think you can close this ticket.
