### ISSUE TITLE
Modify .env after Docker install

### ISSUE THREAD

**Issue by cameradoppia** [cantino/huginn#1066]
Hi there,
i might be asking something silly, sorry but i'm a newbie :) 

Finally I was able to install the awesome Huginn via Docker on Centos7, i haven't set twitter oauth during installation so I have been trying to modify the .env without success. I can't find it using ssh access, i don't see the huginn user/folder... how do i achieve this goal?

Thanks in advance,
Dan

**Comment by cantino** [comment]
When using Docker, I believe all of the .env settings are set using ENV variables provided when you launch Docker.  Please see the environment variables section of https://hub.docker.com/r/cantino/huginn/ and let us know if you have any more questions.

**Comment by cantino** [comment]
Closing since we haven't heard back.  Hope it's working for you!
