### ISSUE TITLE
Bundle exec foreman starts terminated by SIGKILL

### ISSUE THREAD

**Issue by amarkhalid** [cantino/huginn#1067]
I've managed to setup Huginn up until executing foreman which fails with the following output. Please help I'm doing this on Windows 7 x64. Ran bundle a couple of times, cannot figure out what is going wrong.

C:\Users\User\huginn>bundle exec foreman start
Your Gemfile lists the gem pg (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of
 just one of them later.
15:27:05 web.1  | started with pid 8976
15:27:05 jobs.1 | started with pid 9096
15:27:52 jobs.1 | C:/Users/User/huginn/lib/agent_runner.rb:52:in `trap': unsuppo
rted signal SIGQUIT (ArgumentError)
15:27:52 jobs.1 |       from C:/Users/User/huginn/lib/agent_runner.rb:52:in `blo
ck in set_traps'
15:27:52 jobs.1 |       from C:/Users/User/huginn/lib/agent_runner.rb:51:in `eac
h'
15:27:52 jobs.1 |       from C:/Users/User/huginn/lib/agent_runner.rb:51:in `set
_traps'
15:27:52 jobs.1 |       from C:/Users/User/huginn/lib/agent_runner.rb:27:in `ini
tialize'
15:27:52 jobs.1 |       from bin/threaded.rb:5:in `new'
15:27:52 jobs.1 |       from bin/threaded.rb:5:in `<top (required)>'
15:27:52 jobs.1 |       from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.2.4/l
ib/rails/commands/runner.rb:60:in `load'
15:27:52 jobs.1 |       from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.2.4/l
ib/rails/commands/runner.rb:60:in `<top (required)>'
15:27:52 jobs.1 |       from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.2.4/l
ib/rails/commands/commands_tasks.rb:123:in `require'
15:27:52 jobs.1 |       from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.2.4/l
ib/rails/commands/commands_tasks.rb:123:in `require_command!'
15:27:52 jobs.1 |       from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.2.4/l
ib/rails/commands/commands_tasks.rb:90:in `runner'
15:27:52 jobs.1 |       from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.2.4/l
ib/rails/commands/commands_tasks.rb:39:in `run_command!'
15:27:52 jobs.1 |       from C:/Ruby21/lib/ruby/gems/2.1.0/gems/railties-4.2.4/l
ib/rails/commands.rb:17:in `<top (required)>'
15:27:52 jobs.1 |       from bin/rails:4:in `require'
15:27:52 jobs.1 |       from bin/rails:4:in `<main>'
15:27:52 jobs.1 | exited with code 1
15:27:52 system | sending SIGKILL to all processes
15:27:52 system | sending SIGKILL to web.1 at pid 8976
15:27:52 web.1  | exited with code 0

C:\Users\User\huginn>

**Comment by cantino** [comment]
Hey @amarkhalid, welcome! We recommend using VirtualBox on Windows for running Huginn.  Please see https://github.com/cantino/huginn/blob/master/doc/manual/requirements.md

**Comment by cantino** [comment]
Closing since we haven't heard back.  Hope it's working for you!
