### ISSUE TITLE
Can't figure out how to use DelayAgent

### ISSUE THREAD

**Issue by svermeulen** [cantino/huginn#1069]
I'm in a situation where I have an event occur, and I want to process that event but only 1 day after the event occurs.  So, DelayAgent seems like it would be perfect for this.  I would have DelayAgent observe the initial event, then wait a day before forwarding the event to another handler. 

However, after creating a DelayAgent I don't understand how to specify the delay?  I don't see a field for this.

**Comment by brianpetro** [comment]
After reading through the specs, it seems that this agent should re-emit *all* delayed events at a regularly scheduled interval(default is 12 hours).

I believe what you're looking for is to re-emit the event X hours after the event was received. I don't believe this result can be achieved with this agent alone, at this time.

**Comment by svermeulen** [comment]
Oh ok that makes sense.  I was reading the "Schedule" parameter to be when the delay agent ran, not when it fired the events again.  I will try setting it to 12 hours and see if that works.  Thanks!

**Comment by cantino** [comment]
You could also look at using a DelayAgent + a SchedulerAgent, if you need very fine-grained controls.  To emit an event after a specific amount of time *relative to when it was created* is a new concept, I think, and might require a JavaScriptAgent + a SchedulerAgent, or a modification and pull request for the DelayAgent.

**Comment by waldens** [comment]
There's also this need, need to emit an event ASAP, after 24h relative to when it was created.
For reference, I used 2 delay agents in series, the schedule is both 1d, which will ensure the final event is emitted, between 1 and 2 days later, relative to when it was created.
It's inaccurate and not elegant, but better than nothing...

**Comment by Aracon** [comment]
The issue with delaying events for some time is not solved at the moment, right?
Could you point the way, what to change in DelayAgent to reach this? I am new to Huginn, but I think this is very useful functionality.

**Comment by dsander** [comment]
@Aracon Do you want to delay events individually for a given time? I think you could introduce a `mode` to the `DelayAgent` which switches the behavior. If it is in the "`delay_by_fixed_duration`" mode iterate over the received events in `check` and only emit them if they are older then the configured duration.
