### ISSUE TITLE
Webhook Agent does not properly handle Liquid templating.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#1070]
Webhook Agent does not correctly substitute {% credential foo %} strings in its configuration.  The Agents' POST URLs are broken and unusable.  For example:
```
{
  "secret": "{% credential foo %}",
  "expected_receive_period_in_days": 365,
  "payload_path": "."
}
```
results in a POST URL of **https://huginn.example.com/users/1/web_requests/31337/%7B%25%20credential%20foo%25%7D**, which is incorrect.

**Comment by cantino** [comment]
Interesting.  Clearly that URL is wrong, but if you actually post to `https://huginn.example.com/users/1/web_requests/31337/VALUE_OF_CREDENTIAL_FOO`, does it work?  It looks like we do correctly do `interpolated['secret']`, so I'd expect it to.

**Comment by cantino** [comment]
Can I close this @virtadpt?

**Comment by ismail44** [comment]
This is also the case when using the PostAgent. LiquidTemplating placeholders are not being replaced with the appropriate options.

**Comment by cantino** [comment]
@ismail44 for which options?

**Comment by ismail44** [comment]
I honestly don't remember... this was a while ago... sorry.

**Comment by cantino** [comment]
No worries!

**Comment by xnaas** [comment]
Sorry to bump an incredibly old thread. You never got a reply from @virtadpt, but I can confirm that even though the URL is being displayed incorrectly, sending a POST request to the WebhookAgent with the secret key does indeed work. Anyway to get the aesthetic error resolved? 😃

**Comment by virtadpt** [comment]
Crap, I completely forgot about this.  I need to test it later today.
