### ISSUE TITLE
URL Query parameter support in webhook agent

### ISSUE THREAD

**Issue by deardooley** [cantino/huginn#1072]
Is there a way to get the URL Query parameters as well as the POST body when receiving a webhook? My use case is that I provide a custom URL to a 3rd party service. The URL has macros in the query string which are resolved at runtime. The resulting URL is sent a well-defined body in the POST. 

My current approach (with Zapier) is to inject a user email address into the query string when I register the webhook. I then pull out the email address and fields that I need and populate the recipient and content of an email template to send out. If I could use this approach in Huginn, I would only need to add a single a single email agent per email template (which is attractive given the number of users). I'm unclear about how to accomplish this in current webhook paradigm. Do you have any pointers?

**Comment by cantino** [comment]
Rails should merge any GET and POST params, so I'd expect you to be seeing both.  I take it that you're not?

**Comment by cantino** [comment]
Closing since we haven't heard back.  Hope it's working for you!
