### ISSUE TITLE
Is there a Swagger definition of the API?

### ISSUE THREAD

**Issue by deardooley** [cantino/huginn#1073]
Where can we find a swagger (or other) definition of the API behind huginn?

**Comment by dsander** [comment]
Hi @deardooley,

we currently have no documentation of the API, most (if not all) calls accept and return JSON but there is no central place where its documented. To properly support an API it would probably be best to expose it via a separated (versioned) URL prefix. I would be open for pull requests either documenting the current API or separating it from the "internal" application calls.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further!
