### ISSUE TITLE
Huginn using up way more database rows than events?

### ISSUE THREAD

**Issue by wasafiri** [cantino/huginn#1078]
Added up the total amt of events generated by all my agents -- 1557; however, my Postgres database on Heroku keeps having write access revoked due to exceeding the 10,000 row limit. Is there a reason why Huginn would be using 8,443+ more rows than there are events? 

I have all my agents set to keep events 2 days only.

Thanks for any feedback.

**Comment by cantino** [comment]
Hey @wasafiri, that's odd.  Idea 1: Heroku is lying.  Idea 2: we have a bug.  You could try running `heroku run rails console` and then do `Event.count` and see what you see.  Also do `Delayed::Job.count`, maybe you have a bunch of errored jobs?

**Comment by wasafiri** [comment]
Event.count = 1626
Delayed::Job.count = 19

So Heroku's lying?

**Comment by cantino** [comment]
You could also try `AgentLog.count`.  None of the other models in https://github.com/cantino/huginn/tree/master/app/models should be frequent.

**Comment by wasafiri** [comment]
Aha... AgentLog.count returns 8226. How can I go about reducing that?

**Comment by cantino** [comment]
Well, temporarily, it should be safe to run `AgentLog.delete_all` on that same console.  You should also set `AGENT_LOG_LENGTH` in your Heroku environment (`heroku config:set AGENT_LOG_LENGTH=20` or something) to something smaller than 100 (the default).  This is the number of logs lines kept per Agent.

**Comment by wasafiri** [comment]
Thanks. I had set AGENT_LOG_LENGTH as well as HUGINN_AGENT_LOG_LENGTH because both were found in a search. Now down to just over 5,000 rows after changing it to 50. Many thanks, and Heroku is happy as well. Might consider a lower default limit for Heroku installations because they're really strict about the 10,000 line limit and will revoke write access quickly if you go over that.

**Comment by cantino** [comment]
Glad it's working! I just added a note in fdd4673172906d0d14e1f1d79d7d7a963d7ce82c.
