### ISSUE TITLE
Highlevel system description

### ISSUE THREAD

**Issue by mez** [cantino/huginn#1080]
Hello all,

This is not really an issue, but a question.
I am looking for some docs to describe how huginn and the different moving pieces are working at a high level. I checked out the wiki and wasn't able to find a high level description or perhaps I missed it?!

Cool project and thank you!

**Comment by cantino** [comment]
Hey @mez, the README talks about the basic concepts of Agents and Events, but beyond that and [the instructions on adding an Agent](https://github.com/cantino/huginn/wiki/Creating-a-new-agent), I don't think we have anything formal.

**Comment by mez** [comment]
Hey @cantino, thanks for the response. I'll dig through the README again.

**Comment by cantino** [comment]
Sounds good, let us know if you have questions.  If you feel like beefing up our system documentation, that'd be great too! :smile:

**Comment by mez** [comment]
Reading through #60 and #293 is helping me understand the system concepts! :)
