### ISSUE TITLE
LDAP authentication support

### ISSUE THREAD

**Issue by ssube** [cantino/huginn#1081]
I'm deploying Huginn in an enterprise setting and would love to bind it against our domain. Right now, we've only got one person (me) with access to the server. It's possible to have everyone register, but we have a 3-month password policy that we like to enforce across our tools.

What library does Huginn use for the builtin authentication? Is this something with configurable backends that could easily be pointed at an LDAP/AD server? 

Since Huginn doesn't have groups, I don't think we'd need any crazy complicated support, just a simple bind to log a user in.

**Comment by cantino** [comment]
We use [Devise](https://github.com/plataformatec/devise), which likely has a plugin for LDAP support.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further!
