### ISSUE TITLE
How to structure agents

### ISSUE THREAD

**Issue by oroce** [cantino/huginn#1084]
In the last couple of days I was running an experiment with multiple agents where I did the following
1. pulling data from rss
2. posting to wordpress
3. share the wordpress post to tumblr
4. reblog the tumblr post to an another tumblr blog

Basically these are:
1. fetching and parsing rss (WebsiteAgent)
2. creating new post on a Wordpress (WordpressPublishAgent)
3. fetching post's metadata (title, link etc) based on the newly created post's id (from 2.) (WordpressPostFetchAgent)
4. posting the link from 3. to tumblr (TumblrPublishAgent)
5. fetching the metadata of the tumblr post (reblog_key) which we created in 4. (TumblrPostFetchAgent)
6. reblogging post from 5. (TumblrReblogAgent)

WebsiteAgent is the easy part, that works great.

WordpressPublishAgent (I haven't opened the pull request for this but I will, basically it works pretty similarly to TumblrPublishAgent) and TumblrPublishAgent are little bit trickier, since those do emit a new event everytime they run successfully but the emitted event only contains the `post_id` which is returned by the Tumblr API/Wordpress API (the post's body, such as title, link, tags, author, reblogging related info aren't returned). The main question is: should the TumblrPublishAgent and WordpressPublishAgent include the fetching of the newly created posts' metadata or should that live in a separate agent? Or maybe I should add that (the fetching) to the publish agents but it shouldn't happen by default (eg `options.fetch: true` should be set)?

Final question: should I add the reblogging functionality to TumblrPublishAgent or posting and reblogging should live separetely?

thanks

ps: right now the fetching is included in WordpressPublishAgent and TumblrPublishAgent, and I created a new agent, the TumblrReblogAgent (which is using the TumblrConcern)

**Comment by spaceghost69** [comment]
IMHO: from my experience building REST apis, WordpressPublishAgent should definitely include the fetching of the newly created posts' metadata.

One of the important side effects of a PUT/POST is the retrieval of the newly minted post ID for use in assigning subsequent processing such as assigning tags and uploading attachments.

On a side note, if you could export the scenario and agents publicly and share them with me I'd super appreciate it as I have some WordPress to automate.

**Comment by oroce** [comment]
@spaceghost69 I will add everything to this repo.

**Comment by spaceghost69** [comment]
@oroce your awesomes thx

**Comment by cantino** [comment]
I agree, I think the TumblrPublishAgent and WordpressPublishAgent should include the fetching of the newly created posts' metadata.

**Comment by cantino** [comment]
In order to avoid having too many Agents, it may make sense for the TumblrReblogAgent to be part of one of the other two if they're similar enough and it's just a `mode` switch.

**Comment by roxaloxa** [comment]
What is the status of the Wordpress agent? I was just about to get started on making one myself but figured I'd check here first.

**Comment by cantino** [comment]
I'm not aware of anyone making one.

**Comment by roxaloxa** [comment]
In the opening post here, @oroce mentioned making a WordpressPublishAgent, I was hoping he'd chime in on how that was going.

**Comment by cantino** [comment]
@oroce, do you still want this issue?

**Comment by oroce** [comment]
@cantino yes, actually the WordpressAgent's code is here: https://github.com/purposeindustries/huginn/tree/wordpress-agent (it has been there since december but I still haven't got time to write the tests:()

**Comment by cantino** [comment]
Let us know if you need a hand.

**Comment by oroce** [comment]
Thanks, I was just totally busy, but I really want to finish it and let everybody to use it.

**Comment by cantino** [comment]
I'm going to close this issue for now. Please don't hesitate to reopen if you're still working on this.
