### ISSUE TITLE
Installing huginn on ARM device

### ISSUE THREAD

**Issue by michal-polrolniczak** [cantino/huginn#1085]
Hello,

Im testing huginn on ARM device. It works without problems but when making:
```
 sudo -u huginn -H bundle exec rake assets:precompile RAILS_ENV=production
```
Im getting:
```
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/therubyracer-0.12.2/lib/v8/context.rb:99: [BUG] Segmentation fault at 0x228b54
ruby 2.2.3p173 (2015-08-18 revision 51636) [armv7l-linux-eabihf]
```

If I skip this part huginn works but there is no css/pictures on huginn page. It is throwing problem on therubyracer which I tracked to be problem on ARM devices (for ex. here https://github.com/gitlabhq/gitlabhq/issues/8809).

UPDATE:
This commande helped to overcome those errors

```
sed -ri '/therubyracer|libv8|ref/d' Gemfile{,.lock}
```

**Comment by dsander** [comment]
Hi @michal-polrolniczak,

that is odd, I tested the installation on a Scaleway server a few weeks ago. Which version of `libv8` and `therubyracer` were installed after you removed them from `Gemfile.lock`?

`bundle show` will give you a list of the gems and versions of your bundle.

**Comment by michal-polrolniczak** [comment]
if bundle show would output them then there are not there. so im missing them.

but when I try to install them:
```
apt-get install libv8-3.14.5                                                      :(
..
libv8-3.14.5 is already the newest version.
libv8-3.14.5 set to manually installed.
```
But I cannot find therubyracer

**Comment by dsander** [comment]
Try running `bundle show | grep rubyracer` in `/home/huginn/huginn`

**Comment by michal-polrolniczak** [comment]
There was something strange,
```gem install libv8``` throw error, but when I ```gem install therubyracer``` which use libv8 did install libv8... Now I was able to precompile assets but I still dont get any pictures on huginn.

In https://github.com/cantino/huginn/blob/master/doc/manual/installation.md it dose say 
```Visit YOUR_SERVER in your web browser for your first Huginn login```
but Im getting 502 Bad gateway there. but using MY_SERVER_ip:3000 (on port 3000 same as docker) i get almost black/white page without css/pics.

Any way to fix this ? Reboot didnt helped

**Comment by dsander** [comment]
Nginx listens on port 80, you should be able to access huginn via `http://SERVER_IP`

**Comment by dsander** [comment]
@michal-polrolniczak I did a fresh installation on scaleway with no issues:
```
$ uname -a
Linux scw-c29bf7 3.2.34-30 #17 SMP Mon Apr 13 15:53:45 UTC 2015 armv7l armv7l armv7l GNU/Linux
```
```
$ bundle show
....
  * therubyracer (0.12.2)
  * libv8 (3.16.14.7)
....
```

**Comment by michal-polrolniczak** [comment]
You are right. I did clean install again, but this time I did the step for ubuntu/debian. I wrongly assume that Debian base distro is Debian so I skiped the nodejs step. After that the problem with assets went away.

But still I got 502 Bad Gateway when entering in http://IP_ADDRESS_OF_HUGINN

Log say this:
```*1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 192.168.0.55, server: huginn.huginn, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html"```

Which is true, unicorn don't make socket file there. I try to search it the file is nowhere to be found. I readed somewhere else about similar problem and the solution was to put socket file in /var/sockets/ I will try that one also. 

Meanwhile if you got any ideas to fix that fell free to comment :+1:

**Comment by dsander** [comment]
Did you change the `Procfile` and uncomment [those two lines](https://github.com/cantino/huginn/blob/master/Procfile#L24-L25)? Also make sure to comment out the two active lines in the development section.

**Comment by michal-polrolniczak** [comment]
To be honest, I didn't when building, then after I did it uncomment two lines from production and comment out two in development envirement. 
Then I do:
```sudo rake production:export --trace``` (because it throw error)
But im getting this:
```
** Invoke production:export (first_time)
** Invoke production:check (first_time)
** Execute production:check
** Execute production:export
** Execute production:stop
Stopping huginn ...
ok: down: huginn-web-1: 96s, normally up
rake aborted!
'sv stop huginn-jobs-1' exited with a non-zero return value: timeout: run: huginn-jobs-1: (pid 2419) 2627s, want down, got TERM
/home/huginn/huginn/lib/tasks/production.rake:80:in `run'
/home/huginn/huginn/lib/tasks/production.rake:72:in `block (2 levels) in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:88:in `call'
/home/huginn/huginn/lib/tasks/production.rake:88:in `with_retries'
/home/huginn/huginn/lib/tasks/production.rake:71:in `block in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:70:in `each'
/home/huginn/huginn/lib/tasks/production.rake:70:in `run_sv'
/home/huginn/huginn/lib/tasks/production.rake:33:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/usr/local/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/usr/local/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/local/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/home/huginn/huginn/lib/tasks/production.rake:52:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/usr/local/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/usr/local/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/local/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/local/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/usr/local/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/usr/local/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/usr/local/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/usr/local/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/usr/local/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/usr/local/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/usr/local/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/local/bin/rake:33:in `<main>'
Tasks: TOP => production:export

```
and im not sure if the change are made - looking at trace it dose export settings.
and from what I see i dont see any ```unicorn``` in ```ps aux | grep unicorn``` (but im not sure if there should be any)

And using ```sv stop huginn-jobs-1``` give this info:
```timeout: run: huginn-jobs-1: (pid 2419) 2713s, want down, got TERM```

Everytime I try to export new Procfile I reboot after - to kill huginn-job and restart it for sure.

**Comment by michal-polrolniczak** [comment]
It's looks like export didnt work.
```sv force-stop huginn-jobs-1```
after that I killed then ```rake production:export```
and that did it for the unicorn
now the unicorn is starting and ```unicorn.socket``` is created.

Thanks you @dsander for helping resolve this issue! You gave alot of usefull tips!

**Comment by dsander** [comment]
Awesome, glad it works!
