### ISSUE TITLE
Optionally suppress WebHook 'Event Created' response message

### ISSUE THREAD

**Issue by amokan** [cantino/huginn#1087]
I have a Twilio integration I'm using that does a POST to a WebHook agent endpoint when receiving a text message. Everything works great, but it would be helpful to have the ability to suppress the 'Event Created' message with an optional config param on the WebHook agent to just send back the 201 response, but no text - because the text response causes Twilio to send a MMS reply back, which I do not want in this case.

I'm imagining something like an optional `"suppress_response_message": true` param on the agent to just return the 201 status if enabled here https://github.com/cantino/huginn/blob/master/app/models/agents/webhook_agent.rb#L56

I can put together a pull request if others think this would be a helpful option. I just wanted to raise the idea at this point. If there is a better way to handle my scenario, I'm open to other ideas as well.

**Comment by cantino** [comment]
That seems like a good addition, @amokan.  You could add an option to configure the `Event Created` message to be anything the user wants.  Would making it empty work for you?

**Comment by amokan** [comment]
I think the empty response would be great. I'll try to put together a PR later this week @cantino

**Comment by cantino** [comment]
Ok!

**Comment by cantino** [comment]
How's it going @amokan?

**Comment by cantino** [comment]
Never mind, I forgot we merged this!  Closing :)
