### ISSUE TITLE
Adding a new flight agent API 

### ISSUE THREAD

**Issue by Pcsl** [cantino/huginn#1088]
Adioso agent seems not be working anymore because Adioso API seems closed. I'm not skilled enough but I was thinking about some alternatives that could be useful to develop a new agent in case someone wants to try. I think the best one would be [QPX Express API](https://developers.google.com/qpx-express/v1/prereqs) from Google that powers Google Flights and ITA Matrix.

So if someone wants to give it a chance, just take this message as a suggestion.

**Comment by cantino** [comment]
I wonder if we should remove the Adioso Agent then?

**Comment by virtadpt** [comment]
Adioso is ignoring all e-mails, tweets, and DMs requesting login/passwords (or even questions to effect of "Hi, am I even allowed to have a login/password for your service?") and has been for five weeks.  I'm inclined to suggesting jettisoning it.

**Comment by cantino** [comment]
I'm concerned that if we remove it, it'll break anyone who's still using it when they update.  Do we know if the API is turned off, or just won't accept new signups?

**Comment by matk0** [comment]
I took up creating this agent based on QPX Express API. I will let you know once I have something tangible.

**Comment by Jngai** [comment]
@matk0 are you still tackling this? I am interested in this ticket.

**Comment by matk0** [comment]
Hi,
no I’m not anymore.

On 21 Feb 2016, at 23:58, Judy Ngai <notifications@github.com> wrote:

@matk0 <https://github.com/matk0> are you still tackling this? I am interested in this ticket.

**Comment by Jngai** [comment]
I will take a look into this ticket.

**Comment by Jngai** [comment]
I am going to put this on hold. I did some research and didn't think the doc is that robust. Google mixed with ruby and google api client is in alpha mode.

**Comment by Jngai** [comment]
I got the qpx express api to work so I am working on this now.

**Comment by Jngai** [comment]
#1367

**Comment by cantino** [comment]
@Jngai just contributed the GoogleFlightsAgent in #1367.  Thanks!  This should solve this issue.
