### ISSUE TITLE
json input from event to get parse

### ISSUE THREAD

**Issue by bigretromike** [cantino/huginn#1090]
Insted of making Agent for Pocket (getpocket) I was thinking to just parse outputs from api from other event using shellcommandagent.

I curently have a little :no_good: stop there. 
The JSON from query is like:
```
{"status":1,"complete":1,"list":{"123456789":{"item_id":"123456789","resolved_id":"123456789","given_url":"http:\/\/test.com","given_title":"name","favorite":"0","status":"0","time_added":"1434567339","time_updated":"1434562386","time_read":"0","time_favorited":"0","sort_id":0,"resolved_title":"name","resolved_url":"http:\/\/test.com","excerpt":"name","is_article":"0","is_index":"0","has_video":"0","has_image":"0","word_count":"117"}},"error":null,"search_meta":{"search_type":"normal"},"since":1445251010}
```

The problem is that I cannot get the ```123456789``` id out in any way to pass it to other agent.
I was trying to get this random ID out but I cannot find anyway to do it. I was trying with trigger Agent but the ID is inside block and not array so {{list[0].item_id}} and {{list.*.item_id}} dosn't work. I can limit the JSON to only contain one item, but I cannot find agent to do this. Im thinking of putting JSON from event into temporary file then regex it looking for ```item_id``` then take that file as input and delete it latter but that make it look more complicated than it should

I understand that the BEST method would be create Pocket Agent using pocket-ruby gem, but that is currently over me and I would love just to migrate my IFTTT to huginn completely :+1: 

I would love to setup every recipe from ifttt in Huginn and them I could start reserching more.

**Comment by cantino** [comment]
Hey @michal-polrolniczak, is that the exact Event data you see when you look at one of the events emitted by the ShellCommandAgent?  I'm wondering if maybe you're getting a string of JSON, not an actual JSON structure.

**Comment by michal-polrolniczak** [comment]
Payload is this:
```
{
  "command": "curl magic-url-here",
  "path": "/bin/",
  "exit_status": 0,
  "errors": "% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100  1117  100   954  100   163   1300    222 --:--:-- --:--:-- --:--:--  1633",
  "output": "{\"status\":1,\"complete\":1,\"list\":{\"123456789\":{\"item_id\":\"123456789\",\"resolved_id\":\"123456789\",\"given_url\":\"http:\\/\\/test.com\",\"given_title\":\"\test.com\",\"favorite\":\"0\",\"status\":\"0\",\"time_added\":\"1431517339\",\"time_updated\":\"1436762386\"}},\"error\":null,\"search_meta\":{\"search_type\":\"normal\"},\"since\":1445320114}"
}
```

This is the output

**Comment by cantino** [comment]
Yea, so what's going on here is that output is a string of JSON, so we can't easily parse it.  Perhaps the ShellCommandAgent should have an option to parse it's input as JSON before emitting an event?

**Comment by cantino** [comment]
I can take a look at adding this.

**Comment by cantino** [comment]
I think this should be possible now?  If not, please reopen!
