### ISSUE TITLE
Diagram disaster

### ISSUE THREAD

**Issue by mikalauskas** [cantino/huginn#1091]
Is there any alternative to the graphviz dot? Especially after integration of the Gap detector.

:scream::scream::scream:
![halp](http://i.imgur.com/16lmByb.jpg)

**Comment by cantino** [comment]
Wow.

Well, you can view subsets by putting Agents into Scenarios and then viewing the diagrams on those.

**Comment by knu** [comment]
There are some configuration options available in Graphviz.
I kind of like how my diagram is laid out by `statement 'graph', layout: 'neato', overlap: 'false'`.

**Comment by knu** [comment]
We might want to use the pure JavaScript dot renderer (https://github.com/mstefaniuk/graph-viz-d3-js) so we could apply layout option changes on the fly.
