### ISSUE TITLE
ShellCommandAgent timeout

### ISSUE THREAD

**Issue by michal-polrolniczak** [cantino/huginn#1093]
Im having few of somehow long shell scripts to complete, running them via agent end up with error in events:
```execution expired```
Is there way to setup Agent to wait (best would be infinity) or can we fork out script job outside agent so it will only trigger the start and the script will live it own life?

**Comment by level20peon** [comment]
I never used the ShellCommandAgent but can't you run it like `script.sh &` ?

Alternatively you can increase the "DELAYED_JOB_MAX_RUNTIME" in `.env`.

**Comment by michal-polrolniczak** [comment]
Im trying the ```DELAYED_JOB_MAX_RUNTIME``` 
I did forget about ```&``` but im triggering other scripts after the first one - but now Im thinking I could wrap that into one script that start the other one and start the wraped one with ```&``` so they will start one after another 

Thanks for the tip :+1: will definitly look into changing scripts

**Comment by michal-polrolniczak** [comment]
@level20peon sadly the trick with ```&``` dosn't work

**Comment by michal-polrolniczak** [comment]
@level20peon it did semiway.
I made my orginal script in exe.sh
I made script.sh ```exe.sh &```
and run ```script.sh``` from agent.

it looks like ShellCommandeAgent hook to script even if its started with ```&```

**Comment by level20peon** [comment]
try `nohup` then?

**Comment by michal-polrolniczak** [comment]
To be honest, i didnt know about ```nohup```, i could probably use ```screen``` also :+1: 
I will stick with wraping the main script with other one with ```&```
Im happy with result, and thanks again about both tips!

**Comment by michal-polrolniczak** [comment]
nope ```nohup``` in command line and inside script dont work the intended way

**Comment by cantino** [comment]
Setting DELAYED_JOB_MAX_RUNTIME in `.env` should be the solution.  What do you have it set to, and how long is your script taking?

**Comment by michal-polrolniczak** [comment]
its depend from the url input. It can take 1minut up to 30 or 45minuts - Im using ARM platform so scripts are executing longer.
I would love to fork out of ```Open3.popen3(command)``` but no matter what I do I end up with huginn waiting for finishing job or killing it with above error.

Probably I wont bypass this without editing agent rb file, right?

**Comment by K1773R** [comment]
just run it in screen -dm <insert command>

**Comment by cantino** [comment]
It's not clear to me if the system is killing the process, if popen3 is timing out, or if you're hitting your maximum delayed_job run time.

**Comment by michal-polrolniczak** [comment]
@K1773R ```-dm``` nor ```-dmS``` both get terminated after ```DELAYED_JOB_MAX_RUNTIME``` set time.

@cantino definitly get terminated to the ```DELAYED_JOB_MAX_RUNTIME``` 

But is there any way to jump out of this to bypass this ? because running time-consuming scripts make huginn stuck on them, and setting ```DELAYED_JOB_MAX_RUNTIME``` high in long run can also affect huginn.

I know that bypassing ```DELAYED_JOB_MAX_RUNTIME``` mechanism could potentialy be risky making a really CPU/time intense task just overflow huginn, but that is the same risk as using ShellCommandAgent

**Comment by cantino** [comment]
Well, you can increase `DELAYED_JOB_MAX_RUNTIME` and also run additional delayed_job workers.  Or make a separate process that POSTs to Huginn periodically.

**Comment by michal-polrolniczak** [comment]
```Or make a separate process that POSTs to Huginn periodically.``` could you elaborate this more?

addtional delayed_job that could work - I forgot about this because of recommandation to stick with 1 on ARM ;-)

**Comment by cantino** [comment]
You could use a cronjob or another program and have it POST to Huginn's WebhookAgent.

**Comment by michal-polrolniczak** [comment]
So currently it impossible to run out of ShellCommandAgent without blocking it.

**Comment by knu** [comment]
What about creating a ShellCommandAgent to fork a process which outputs to a file and generates a "cookie" file when done, and another to check for the cookie file and dump the output file (and remove the cookie file)?
