### ISSUE TITLE
## Set TWITTER_OAUTH_KEY and TWITTER_OAUTH_SECRET in your environment to use Twitter Agents.

### ISSUE THREAD

**Issue by level20peon** [cantino/huginn#1105]
The above is displayed every minute in the logs. I don't even have any twitter related agent configured / running.
I have yet to understand why Twitter is so important for Huginn it even assigns an own thread for it, even if no Twitter Agents are being used.

**Comment by cantino** [comment]
So you don't have any Twitter-related Agents at all?  This would be nice to fix.

**Comment by level20peon** [comment]
No I don't, I even moved Agents I don't use out of the `./app/models/agents/` directory, in order to shorten the scrollable list which I need when I create a new agent (yes, I know I can also enter a search term).

**Comment by cantino** [comment]
@dsander, I think you mentioned something about it printing that more often than it needed to in a different thread?

**Comment by dsander** [comment]
@cantino Right, totally forgot about that, added it to the list for the weekend :smile:

**Comment by cantino** [comment]
Let me know if I can help.
