### ISSUE TITLE
How to change agents on Heroku?

### ISSUE THREAD

**Issue by MartinButter** [cantino/huginn#1108]
Hi, I'm running Huginn on Heroku. I want to extract text from a pdf-file. Looking at the documentation of Hypdf I found the syntax for extracting pdf quite simular to extract pdf-info. So I changed the pdf_info_agent-file in app/models/agents and in spec/models/agents, replacing pdfinfo with pdftotext. I did a restart of Huginn. But when I run the agent, it still gives me the pdf-meta (this works perfect), but no extracted text, so my changes seem to be totally ignored. Did I miss a command to tell Huginn/Heroku to obey the changes?

Martin

**Comment by dsander** [comment]
Hi @MartinButter,

to have Heroku pick up your changes you need to commit them locally and then run `git push heroku master`or `git push heroku <branch>:master` if your local changes are not commited to the master branch.

**Comment by cantino** [comment]
Closing since we haven't heard back.  Hope it's working for you!
