### ISSUE TITLE
Twitter Service not showing

### ISSUE THREAD

**Issue by gbrindisi** [cantino/huginn#1111]
I've added twitter's keys as described [here] (https://github.com/cantino/huginn/wiki/Configuring-OAuth-applications), I've then restarted huginn but the twitter integration is not showing under the Services panel.

What should I check?

**Comment by signallhill** [comment]
If you manually installed Huginn then did you init script after updating API Key

sudo rake production:export

**Comment by gbrindisi** [comment]
I did but no luck!

    $ rake production:stop
    $ rake production:export
    $ rake production:start

**Comment by dsander** [comment]
Hi @gbrindisi, 

can you check if the env variables were exported successfully?

`ls /etc/service/huginn-web-1/env/TWITTER_OAUTH_*`should list two files.

**Comment by valo** [comment]
If you deploy using docker you need to set the env variables described in https://hub.docker.com/r/cantino/huginn/. For twitter these are

```
HUGINN_TWITTER_OAUTH_KEY
HUGINN_TWITTER_OAUTH_SECRET
```

**Comment by cantino** [comment]
Closing since we haven't heard back.  Hope it's working for you!
