### ISSUE TITLE
Cannot authenticate with Evernote in Service

### ISSUE THREAD

**Issue by MartinButter** [cantino/huginn#1115]
Running Huginn on Heroku I want to connect to Evernote to use the Evernote agent. I created a Evernote API Key and stored it with Heroku config:set as EVERNOTE_OAUTH_KEY and EVERNOTE_OAUTH_SECRET and set USE_EVERNOTE_SANDBOX=true. I also created an Dev accoung in Evernotes Sandbox. In Huginn's Services the button "Authenticate with Evernote" appears, but when I press the button I get only "We're sorry, but something went wrong.". Where can I find a log-file to check if "something" is with Huginn or if Evernote is rejecting the request?

**Comment by cantino** [comment]
Hey @MartinButter, it's possible that `heroku logs` may show you something.  Also make sure that `heroku config` shows the right keys, without quotes or anything.

**Comment by MartinButter** [comment]
Ok, I found something in heroku logs, but I don't really get the meaning:

OAuth::Unauthorized (401 Unauthorized):
config/initializers/silence_worker_status_logger.rb:5:in `call_with_silence_worker_status'

Does this just means that Evernote rejects the OAuth-attempt?

**Comment by cantino** [comment]
It may.  Did the `heroku config` output look right?  I don't use Evernote-- did it make you put a callback or redirect URL for your Huginn instance?  Maybe that's incorrect.

**Comment by cantino** [comment]
Closing since we haven't heard back.  Hope it's working for you!
