### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by calimou** [cantino/huginn#1121]
*Edited by cantino*

Add a simple user management system to Huginn.

[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=27825603)](https://www.bountysource.com/issues/27825603-users-management)

**Comment by cantino** [comment]
Hey @calimou.  We don't currently have a user management UI.  You could configure them in the Rails console, which is obviously not ideal.

**Comment by kirantpatil** [comment]
+1 for this feature.

**Comment by cantino** [comment]
I've added a bounty to this issue.

**Comment by dsander** [comment]
I will be working on that as part of my contract with www.kreuzwerker.de

Features we have planned:

* List users
* Create new users from the admin interface
* Edit existing users
* Make devise options configurable (lockable variables, confirmable durations, etc.)
* Manually de- and reactivate a user (should also stop the agents from running)

**Comment by albertsun** [comment]
One other feature request for something I think would be useful: the ability for admin users to directly make changes to a user's agents.

**Comment by cantino** [comment]
Awesome @dsander!

**Comment by dsander** [comment]
@albertsun That is a great idea, I might work on this after we have the initial version merged.

**Comment by Jngai** [comment]
@cantino @dsander It seems like the admin user management panel has already been done according to the merged pr referenced here. Is this ticket still open because of @albertsun request?

**Comment by albertsun** [comment]
That should really be moved into a separate issue.

**Comment by Jngai** [comment]
Then I guess this ticket should close then.

**Comment by cantino** [comment]
Yup, thanks to @dsander!
