### ISSUE TITLE
TwitterStreamAgent throwing errors

### ISSUE THREAD

**Issue by vincentriemer** [cantino/huginn#1122]
The agent seems to eventually recover but every few hours the agent stops creating events, does anyone have any ideas on how to fix this?

```
Agents::TwitterStreamAgent-15-ac082da107ea1750b88709e524f805138e765f63 Exception eventmachine not initialized: evma_connect_to_server:
/app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:673:in `connect_server'
/app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:673:in `bind_connect'
/app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:649:in `connect'
/app/vendor/bundle/ruby/2.1.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:62:in `connect'
/app/app/models/agents/twitter_stream_agent.rb:186:in `stream!'
/app/app/models/agents/twitter_stream_agent.rb:170:in `block in run'
/app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:170:in `call'
/app/vendor/bundle/ruby/2.1.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:170:in `run'
/app/app/models/agents/twitter_stream_agent.rb:169:in `run'
/app/app/concerns/long_runnable.rb:69:in `block in run!'
```

**Comment by cantino** [comment]
Wow, that's a new one for me.

Are you using Redis in any way?

/cc @dsander

**Comment by vincentriemer** [comment]
No I'm just running the docker container. Only real customization is that the huginn instance is running behind an HTTPS proxy.

**Comment by cantino** [comment]
This might be an interesting hint about an ongoing issue we've been seeing in the twitter stream.

**Comment by dsander** [comment]
How can this even happen? The complete backtrace is wrapped in a `EventMachine.run` block which does initialize eventmachine.

**Comment by cantino** [comment]
Maybe EventMachine's state is a Thread.local?

**Comment by dsander** [comment]
Pretty sure it is, the TwitterStreamAgent::Worker is running in it's own thread and starting `EM.run` inside it. Even if the active thread switches it does not change the execution order inside TwitterStreamAgent thread.

@vincentriemer Does the exception happen regularly?

**Comment by vincentriemer** [comment]
It seems to almost happen randomly, I'm currently in a good streak of it not happening. One thing I'm curious about it that I'm running Huginn and mysql in separate containers and in order to recover from some of these issues I've restarted the Huginn container, would this potentially create any weird state issues?

**Comment by dsander** [comment]
I don't think so, it is possible the database has some odd state when the huginn container crashes but that is unlikely. The same could happen outside of a docker container and we have not seen any bug reports about that.
The exception you posted looks like some kind of initialization error, what makes it even stranger is that it does not happen all the time

**Comment by vincentriemer** [comment]
I wish I could give you guys access of my running instance but unfortunately my current setup doesn't hide my secrets :/

**Comment by dsander** [comment]
It would be interesting to see how huginn behaves running outside of docker but against the same database and with the same configuration.

**Comment by cantino** [comment]
Has this continued @vincentriemer?

**Comment by vincentriemer** [comment]
It still happens intermittently but it has gotten better since I changed the interval from 30 mins to 1 hour. I think my biggest issue isn't that it the error occurs but that it doesn't recover from it. Whenever it happens I need to manually restart the docker container.

**Comment by cantino** [comment]
Very odd.  Maybe a race condition?  I've never seen it, but I don't use Docker.

**Comment by dsander** [comment]
I just migrated my main installation to the `cantino/huginn-single-process` docker image, curios if I will be getting the same error.

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you're still having this issue.
