### ISSUE TITLE
WebsiteAgent Question

### ISSUE THREAD

**Issue by brianpetro** [cantino/huginn#1126]
What is the purpose of this exception? https://github.com/cantino/huginn/search?utf8=%E2%9C%93&q=extract+MUST+have+the+same+number+of+matches+for+each+extractor&type=Code

I would like to extract multiple pieces of data from websites that may not consistently have each piece of data that I am trying to extract.

Is there a workaround? What problem is raising this error preventing?

Thanks (:

**Comment by cantino** [comment]
Hey @brianpetro, this would be a good thing for us to improve.  The basic idea is that we expect each matcher to have the same number of matches so that we can group them into events.  See #990.

**Comment by cantino** [comment]
Closing in favor of #990 and #1128.
