### ISSUE TITLE
Alternative to Gmail that works well with the Huginn Email Agent?

### ISSUE THREAD

**Issue by ppalme** [cantino/huginn#1130]
I am running huginn on terminal.com and I followed all their steps to allow the email agent access to gmail. No success. Is there an alternative email provider that works well with the huginn email agent?

**Comment by cantino** [comment]
Any should, but we've mostly tested with Gmail.  Have you tried contacting their support?

**Comment by dsander** [comment]
Hi @ppalme,

I am using [mandrill](http://mandrill.com/), but they recently changed their pricing policy. Other options would be http://www.mailgun.com and https://sendgrid.com, both have a free plan for up to 10k and 12k mails per month.

As far as I remember for gmail to work you need to set `EMAIL_FROM_ADDRESS` to your account address.

**Comment by knu** [comment]
In Gmail you can add alternative sender addresses in Settings-Accounts-Send Mail as.

**Comment by ppalme** [comment]
Much appreciate your comments and your help. Thank you.
