### ISSUE TITLE
Data Output Agent RSS feed not well formed?

### ISSUE THREAD

**Issue by ppalme** [cantino/huginn#1131]
I build the example based on Andrew's post: http://blog.andrewcantino.com/blog/2014/04/13/adding-rss-feeds-to-any-site-with-huginn/

When I use my created rss feed https://ppalme10-3000.terminal.com/users/1/web_requests/16/xkcdrss.xml
in a zapier rss trigger as a feed url I get the following error message:
not well-formed (invalid token): line 6, column 1645

When I run my feed url through w3org feed validator http://validator.w3.org/feed/
I get the following message:
It looks like this is a web page, not a feed. I looked for a feed associated with this page, but couldn't find one. Please enter the address of your feed to validate

Duke University uses huginn and their rss feed is just fine:
https://blogs.library.duke.edu/bitstreams/2015/09/04/a-welcoming-embrace-to-huginn-our-yahoo-pipes-replacement/

Not sure what is the difference?

**Comment by cantino** [comment]
When I view `https://ppalme10-3000.terminal.com/users/1/web_requests/16/xkcdrss.xml` I get an unauthorized error.  I think you need to have terminal.com allow non-authenticated viewers.

**Comment by ppalme** [comment]
Thank you Andrew

**Comment by cantino** [comment]
No problem!  Can I close this issue?

**Comment by ppalme** [comment]
For all those who use terminal.com for your huginn instance, I had to open the  port 3000 to allow non-authentic viewers for the RSS feed - for instruction see this: http://i.imgur.com/ZIN3wxp.gifv (provided by huginn support).

**Comment by cantino** [comment]
Would it be worth documenting this on the wiki?

**Comment by virtadpt** [comment]
Always.

**Comment by cantino** [comment]
@ppalme, would you mind adding / updating a terminal.com article?
