### ISSUE TITLE
Multiple Recipients for Email Agent

### ISSUE THREAD

**Issue by GregBigdata** [cantino/huginn#1133]
Hi, I'm trying to set up a multiple recipents with several email addresses.
But i'm always getting this error : 'when provided, 'recipients' should be an email address or an array of email addresses

could you provide me a correct json syntax ?

Many thanks in advance

When I'm trying that example, Im getting the error : ['bob@example.com', 'jane@example.com']

**Comment by cantino** [comment]
Are you doing an actual array, or an array in a string?  It may be easier to edit the raw JSON, or to use the structure editor and click the `[`.

**Comment by GregBigdata** [comment]
Ok, it works now. I can't explain why it was not working.
The good syntax is   recipients": [     "bob@example.com",     "jane@example.com"  ],...

**Comment by cantino** [comment]
Glad you got it!
