### ISSUE TITLE
Make fail fetching refetch, or the time interval longer?

### ISSUE THREAD

**Issue by waldens** [cantino/huginn#1135]
At some certain step using WebsiteAgent, due to the "high" concurrency(about 70+ events flood into this WebsiteAgent step), there are always some GET requests failed (whose host are the same). ,

Is there a way to make these fail fetching refetch? or make the fetching time interval longer like 5 seconds per request? Thanks!

![http://ww3.sinaimg.cn/large/d80a8e60gw1exsmer3yd0j20qp0frgtd.jpg](http://ww3.sinaimg.cn/large/d80a8e60gw1exsmer3yd0j20qp0frgtd.jpg)

**Comment by cantino** [comment]
Hey @waldens.

It seems like a good idea to add a rate limit / max requests per second to the WebsiteAgent.  Naïvely, this could be something like adding `sleep (options['request_delay'].presence || 0).to_f` after line 167.

**Comment by cantino** [comment]
Did you try that code @waldens?

**Comment by waldens** [comment]
@cantino Did new option about rate limit already added to WebsiteAgent? I didn't see Pull requests associated and realize that...will check and try later.

**Comment by cantino** [comment]
No, just the code I mentioned above.  It'd be a bigger build to add it generically, and this is the only request I've seen for it.

**Comment by waldens** [comment]
I didn't get the meaning at that time only need that one line code to try, and after that, another way was found to split events to several agents, so this problem isn't exist now. Thanks @cantino
