### ISSUE TITLE
help how to use javascript in credentials

### ISSUE THREAD

**Issue by bassodyssey** [cantino/huginn#1136]
Hello,

Love huginn but I have an issue, I'm sure it is not that difficult but i'm no dev and cannot find an example how to use javascript in credentials page.

I want to use the API of my internet provider router (http://dev.freebox.fr/sdk/os/login/) but I need to login and to do so I need to compute something with CryptoJS, I don't understand everything but I think I can figure it out if only I can get an example on how to use Javascript to get that token and return the value to a Post agent.

Please can someone help me or provide me an example, thanks guys.

**Comment by cantino** [comment]
I think this will be difficult with Huginn because we don't run a full JavaScript environment in the WebsiteAgent.  You'd need something like phantomjs or selenium, I think.

**Comment by bassodyssey** [comment]
Thanks for your answer @cantino. I tried many things and I find out that the API of my router doesn't allow cross domain, so I would be stuck anyway unless using some proxy. Finally I found a very simple way to achieve what I wanted to do using Data Output Agent as my router can read RSS. My head need some resting now :sleeping:

**Comment by cantino** [comment]
I'm glad you figured out a simple solution :)

Should we close this issue?

**Comment by bassodyssey** [comment]
Yes we do, thanks.
