### ISSUE TITLE
Reorder sortable table case insensitive 

### ISSUE THREAD

**Issue by HyShai** [cantino/huginn#1138]
Currently when reordering/sorting a SortableTable it is case sensitive - e.g. `Bar, Foo, foo, bar` instead of `Bar, bar, Foo, foo`. Perhaps calling `"LOWER(#{attribute})"` somewhere would fix this (I couldn't find the proper place to put that...)

**Comment by cantino** [comment]
Line 33 of sortable_table.rb is generated a structure like `{ :name => :asc }` that gets used in Arel scopes via `table_sort`, such as on line 9 of agents_controller.rb.  Perhaps it could be changed to `"LOWER(#{attribute}) #{direction}"`, but that's likely slow depending on the database being used.

**Comment by HyShai** [comment]
How much slower would it be? Is it a better idea to add a `:name_lower` column to the Agents table and then do the sort using that column (would require some refactoring of `sortable_table.rb`)

**Comment by cantino** [comment]
I'm not sure.  It's probably okay for Agents and Scenarios, but might be too slow for Events.

**Comment by HyShai** [comment]
Theoretically we wouldn't need `LOWER` for events because the only field that requires it (`name`) is generated by Huginn so they're all the same case (as opposed to Agents/Scenarios which are human generated).  Obviously in the current architecture there's no way to differentiate between tables (Agents/Scenarios vs Events) and attributes (name vs others).

**Comment by cantino** [comment]
If you'd like to try adding this, you could wire through a setting per column on whether or not it should downcase.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further or build this feature!
