### ISSUE TITLE
Mysql2::Error: MySQL server has gone away: ROLLBACK

### ISSUE THREAD

**Issue by pierrehegr** [cantino/huginn#1146]
Hi, 

I'm still using Huginn on my server, however, it's seem to me that I have an issue with Huginn and my MySQL database. Have you ever see this error message: 

>/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `query'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:334:in `exec_rollback_db_transaction'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:266:in `rollback_db_transaction'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `rollback_db_transaction'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:145:in `rollback'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:179:in `rollback_transaction'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:186:in `rescue in within_new_transaction'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:201:in `within_new_transaction'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.4/lib/active_record/transactions.rb:291:in `save!'
/usr/huginn/app/models/agent.rb:119:in `create_event'
/usr/huginn/app/concerns/dry_runnable.rb:75:in `create_event'
/usr/huginn/app/models/agents/rss_agent.rb:120:in `block in check_urls'
/usr/huginn/app/models/agents/rss_agent.rb:115:in `each'
/usr/huginn/app/models/agents/rss_agent.rb:115:in `with_index'
/usr/huginn/app/models/agents/rss_agent.rb:115:in `check_urls'
/usr/huginn/app/models/agents/rss_agent.rb:90:in `check'
/usr/huginn/app/jobs/agent_check_job.rb:7:in `perform'
/usr/local/lib/ruby/gems/2.1/gems/activejob-4.2.4/lib/active_job/execution.rb:32:in `block in perform_now'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/usr/local/lib/ruby/gems/2.1/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/usr/local/lib/ruby/gems/2.1/gems/activejob-4.2.4/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `instance_exec'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `block in simple'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `block in around'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/usr/local/lib/ruby/gems/2.1/gems/activejob-4.2.4/lib/active_job/logging.rb:23:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activejob-4.2.4/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/lib/ruby/gems/2.1/gems/activejob-4.2.4/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/usr/local/lib/ruby/gems/2.1/gems/activejob-4.2.4/lib/active_job/logging.rb:43:in `block in tag_logger'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'
/usr/local/lib/ruby/gems/2.1/gems/activejob-4.2.4/lib/active_job/logging.rb:43:in `tag_logger'
/usr/local/lib/ruby/gems/2.1/gems/activejob-4.2.4/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `instance_exec'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `block in simple'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `block in around'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
/usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/lib/ruby/gems/2.1/gems/activejob-4.2.4/lib/active_job/execution.rb:31:in `perform_now'
/usr/local/lib/ruby/gems/2.1/gems/activejob-4.2.4/lib/active_job/execution.rb:21:in `execute'
/usr/local/lib/ruby/gems/2.1/gems/activejob-4.2.4/lib/active_job/queue_adapters/delayed_job_adapter.rb:34:in `perform'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
/usr/local/lib/ruby/2.1/timeout.rb:90:in `block in timeout'
/usr/local/lib/ruby/2.1/timeout.rb: 100:in `call'
/usr/local/lib/ruby/2.1/timeout.rb: 100:in `timeout'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
/usr/local/lib/ruby/2.1/benchmark.rb:294:in `realtime'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
/usr/local/lib/ruby/2.1/benchmark.rb:294:in `realtime'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
/usr/huginn/lib/delayed_job_worker.rb:6:in `run'
/usr/huginn/app/concerns/long_runnable.rb:69:in `block in run!' 

Is there a misconfiguration of my database? 
Sincerely

**Comment by dsander** [comment]
Hi @pierrehegr, 

that sounds like your mysql server crashed or at least dropped the connection. Did you try to restart both mysql and huginn?

**Comment by pierrehegr** [comment]
Hi @dsander 

More drop the connection (because mysql is still running). I do restart Huginn and Mysql but without more luck

**Comment by signallhill** [comment]
@dsander I have a RSS agent that dumps 2k plus events each time it runs. I get the same error plus Delayed::Worker.max_run_time is only 240 seconds. 

Will increasing the max runtime too much have effect on huginn performance?

**Comment by cantino** [comment]
You can try increasing the max_run_time.

Huginn isn't really designed for this volume of data.

**Comment by dsander** [comment]
@pierrehegr Do you get the error right after starting huginn or after/while a specific agent runs?

**Comment by pierrehegr** [comment]
Well, this issue is often link with one of my agent (the biggest one). Others agents are ok

**Comment by cantino** [comment]
That sounds like it might be timing out. How many events does the agent
that you are linking have? How many agents do you have?

**Comment by pierrehegr** [comment]
For this agent, I have 30K events. And I have arround 30 agents

**Comment by cantino** [comment]
It's probably just taking too long to run, @pierrehegr.  Could you split it between a few Agents?

**Comment by pierrehegr** [comment]
Hi, I will try to see. I did the update of Huginn and it seems to be better
