### ISSUE TITLE
JabberAgent locks up, sends no events, backs up the job queue.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#1149]
(quoted from chat on gitter.im)

I'm running three DJ workers now, and got another lockup this morning - 3,301 pending jobs. Again, JabberAgent is at the top of the list.  bin/schedule.rb is still in memory and using 1.3% of the CPU it's sitting on.  If I just dump all the pending jobs, that doesn't fix it, I have to kill and restart Huginn to get it going again.

One unusual factoid associated with that: When I bounce Huginn, the number of jobs in the "to run" queue roughly doubles. The workflow is, stop Huginn, start it again, then dump all the pending jobs.

I disabled roughly 110 agents in the past two weeks to see if it was the number of running agents doing it; this does not appear to be the case.

I have five development.log files, one from each of the last four lockups. I've no idea what I'm looking for in there, though.

Now that Huginn has picked up again, the number of jobs is increasing at a rate of approximately 75 jobs every five seconds (if I'm interpreting the output correctly).
Up to 4,583 now and climbing.

Also, and I don't know if this means anything, the background process that's supposed to remove expired events from the database isn't. My database is over 60,000 stored events and climbing every day.  I wish I knew what was going on. If these lockups were consistent... whoa! Huginn just flatlined!  Hang on, let me paste the exception someplace.

http://pastebin.com/Qr9mYhQ3

The Rails server is running, bin/schedule.rb is running (ostensibly), bin/twitter_stream.rb is running, and script/delayed_job 0 and 1 (out of 0, 1, and 2) are running. script/delayed_job #2 is gone.  I've just saved development.log.5.  Trying to load Huginn shows a blank white page.

Restarting Huginn.

```
22:12:08 web.1 | started with pid 31207
22:12:08 schedule.1 | started with pid 31209
22:12:08 twitter.1 | started with pid 31211
22:12:08 dj0.1 | started with pid 31213
22:12:08 dj1.1 | started with pid 31217
22:12:08 dj2.1 | started with pid 31218
```

Looks like JabberAgent is hung up again - the icon's blue and it's stuck at the top of /jobs.  There is no red "Delete" button next to it, so I can't terminate it.

Yup, definitely. 28 minutes now.  (Well, it says 28 minutes.)

Wait, what's "Connect to receiver"?

**Comment by dsander** [comment]
Looks like this a know issue: https://github.com/xmpp4r/xmpp4r/issues/46 https://github.com/xmpp4r/xmpp4r/issues/28

Not sure if one can rescue a deadlock, but you can try to replace with `JabberAgent` deliver method with this and then check the agent log how often the exception happens:

```
    def deliver(text)
      client.send Jabber::Message::new(interpolated['jabber_receiver'], text).set_type(:chat)
    rescue Exception => e
      error("#{e.class} #{e.message}")
    end
```

**Comment by virtadpt** [comment]
Hmmmm.... I'll give this a try this afternoon and let you know what happens.

**Comment by virtadpt** [comment]
Done.  Monitoring now.

**Comment by virtadpt** [comment]
The Huginn lockup I ran into early this morning seems to have dumped a few exceptions into the development.log file.  It'll take me a little while to clean up the text so I can throw it on Pastebin.

**Comment by virtadpt** [comment]
http://pastebin.com/6j9MLiVD

**Comment by dsander** [comment]
I don't know if is related but with the amount of agents you are running I strongly suggest to migrate your setup to run in the production environment. I will definitely be faster and maybe even more stable. When you are running debian or ubuntu the manual installation guide should be straight forward. Copy over your `.env` file when you are done and huginn will run at least as stable as before.

**Comment by dsander** [comment]
`last_error = 'closed stream` Sounds like an issue with your XMPP server as well as the [exception](https://github.com/xmpp4r/xmpp4r/blob/v0.5.6/lib/xmpp4r/client.rb#L120) backtrace, did something change about the way you authenticate against the server?

**Comment by virtadpt** [comment]
No, I haven't reconfigured any instances of the JabberAgent, nor the copy of Prosody running on the same server.  The JabberAgents seem to run decently well most of the time, I get alerts from them from time to time during the day.

Could it be that I have multiple copies of JabberAgent all logging into the Prosody account, sending their messages, and then logging out?  Should I create multiple "service accounts" in prosody for each scenario?  Should I hook the agent networks that use JabberAgent as their means of output into a single JabberAgent for the scenario, and not a bunch of them?

**Comment by virtadpt** [comment]
I will give it another try, @dsander, and see if I can make it work this time.

**Comment by dsander** [comment]
> Could it be that I have multiple copies of JabberAgent all logging into the Prosody account, sending their messages, and then logging out?

That sounds like a very good point, when running multiple DJ workers your JabberAgent could be triggered multiple times and run in parallel which might cause the authentication problems.

**Comment by virtadpt** [comment]
Especially when taking into account that xmpp4r is multithreaded internally; I've had similar problems with other codebases.

It could also be a particular agent network of mine triggering this problem; I don't know what may or may not have changed in CronAgent, but I need to rework it so that it doesn't trigger as fast as it is.

**Comment by virtadpt** [comment]
@dsander To document the discussion in Gitter yesterday, I sat down with some of my co-workers yesterday morning and tried to migrate my environment over to the Production configuration.  The instructions failed at the ```sudo rake production:export``` step, we think because runit's scripts weren't finding the RVM environment.  We were able to get something very much like it running which operates noticeably faster.  However, this did not fix the issue with JabberAgent locking up DJ's or threads; just the opposite, in fact.  Huginn is now significantly less stable than it was before.

The patch you suggested for JabberAgent is not reporting any exceptions.  DJ's running Jabber agent do not print anything other than "Agent#186: Sending IM to <address> with event 900689".

One further thing - when a DJ runs a JabberAgent it stops functioning entirely until it's killed and restarted manually.  Watching the /jobs page after freshly starting up Huginn, one can see three jobs at a time run (and very quickly, at that).  Then a JabberAgent runs, and after that only two jobs at a time run.  Then one.  Then no more until they're killed and started again.  It's a pretty predictable downward slope that occurs inside of eight hours.  The Rails server, scheduler, and Twitter subprocesses do not seem to be affected.

**Comment by virtadpt** [comment]
One further point - I've created unique accounts in Prosody for the JabberAgents in each scenario on a 1:1 basis.  I think this rules out all of the JabberAgents all hitting a single XMPP account to send their events in short succession.

**Comment by virtadpt** [comment]
I've made one more configuration change - I enabled the legacyauth module in Prosody because it could be that xmpp4r either doesn't do SASL efficiently or at all, which might be part of the problem.  I've turned logging in Prosody all the way up so we can see the server-side of the agent interactions, also.

**Comment by virtadpt** [comment]
I have a better idea of what's going on right now.  I just correlated the frozen DJ's output with Prosody's debug logs, and what I see is JabberAgent negotiating a TLS session and authenticating successfully with SASL, logging into the XMPP server (the session is still online), but then the JabberAgent doesn't send its payload.  It does, however, send keepalives to keep the session active:
```
ov 21 19:54:07 c2sf8d040       debug   Received[c2s]: <iq id='EW9Uc-5292' type='get'>
Nov 21 19:55:09 c2sf8d040       debug   Received[c2s]: <iq id='EW9Uc-5293' type='get'>
Nov 21 19:56:21 c2sf8d040       debug   Received[c2s]: <iq id='EW9Uc-5294' type='get'>
```
Strangely, I just heard some XMPP messages hit my client; the output of the next DJ over shows the same instance of JabberAgent (agent 62) successfully send some events, and then the DJ ran a few more jobs immediately afterward.  This is weird.

**Comment by dsander** [comment]
> The instructions failed at the sudo rake production:export step, we think because runit's scripts weren't finding the RVM environment.

The documentation recommends not to use rvm or rbenv for a reason, it is nearly impossible to cover every possible configuration. I do not know what you did, I was able to migrate my rvm/capistrano setup to the manual installation guide by backing up the .env file, installing ruby globally (2.2.3 is not needed, any supported version never then 2.0 will work) and following the steps of the guide.

> just the opposite, in fact. Huginn is now significantly less stable than it was before.

I really doubt that is related to huginn running in the production environment. For example if you would be using runit the dying DJ workers would be restarted automatically. That does not solve the problem with the JabberAgent, but still would keep your huginn instance functioning.

I can not say much about the JabberAgent failing to communicate properly with your XMPP server because I just use it to receive events from a hipchat server. Maybe the issue needs to be upstreamed to xmpp4r?

**Comment by virtadpt** [comment]
That makes sense.

The DJ workers are not dying, they are locking up and have to be killed manually and restarted.  If they were just dying I could write a watchdog for them.  I think the DJs are just locking up faster in production mode than in development mode.

xmpp4r has not been maintained for nearly a year (commit 57e0488e199befde2244e637d39bbacf9d2fe26f was on 4 December 2014).

**Comment by cantino** [comment]
Are you getting deadlocks in the DB?

**Comment by virtadpt** [comment]
Not that I can tell - I was grepping for them in the logs but didn't see any.

**Comment by cantino** [comment]
So when you say they're locking up, the symptom you're seeing is that no jobs are getting handled, but the processes are still running?  What do the logs say during that time?

**Comment by virtadpt** [comment]
Yes to the first question, nothing to the second - the logs just stop updating.

**Comment by virtadpt** [comment]
Noticed the following this morning after restarting the threaded job runner: http://pastebin.com/ZGTgvFxa

**Comment by dsander** [comment]
I wonder how `@client` can become `nil` over the runtime, but the fix should be easy, you are using the `connect_to_receiver` option, right?

**Comment by virtadpt** [comment]
I am not using that option.  I am using JabberAgent to emit events over XMPP; there is nothing downstream of them in Huginn.

Should I be?  Are there semantics to the ```connect_to_receiver``` option that I'm not understanding (which is likely)?

**Comment by dsander** [comment]
When one of your jabber agents has the `connect_to_receiver` option set to true it will connect to the jabber server and emit an event for every XMPP message it receives. Without that I do not see how the code path your execution comes from is executed.

**Comment by virtadpt** [comment]
I have configured one of my JabberAgents to have that setting turned on as a test. We shall see what happens.

Why is this an optional setting now? I am not sure I follow the possible use cases.

**Comment by dsander** [comment]
Actually I just wanted to make sure you don't have the option enabled, because I don't think you need it. It is useful if you want to use the XMPP MUC room as a source of events, it does not send any message back.

**Comment by virtadpt** [comment]
In one of my scenarios, I have JabberAgent turned on and ```connect_to_receiver``` is set to ```true```.  It is deactivated in my other scenarios.  In the other scenarios it is set to ```false```.

**Comment by cantino** [comment]
Is this still happening @virtadpt?

**Comment by virtadpt** [comment]
I'll be honest with you, I don't know.  I deactivated all of my JabberAgents and set up BeeperAgents and that's been working for me.  I'll give it another try after I dig out from everything that snowed me in while I was on the road last week (probably this weekend) and let you know what I find.

**Comment by virtadpt** [comment]
We may as well close out this ticket.  Since I stopped using JabberAgent the problems stopped (I run into different kinds of problems these days) and nobody else has mentioned running into them.

**Comment by iecompattest** [comment]
:jhg kjfh


________________________________

**Comment by cantino** [comment]
:shrug: okay, works for me. I also don't use it.
