### ISSUE TITLE
Event Format Agent Help

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1151]
I am trying to filter out or replace emails and web address from event content and format it using event format agent. Help is appreciated.

{
  "instructions": {
    "message": "{{content}}",
    "subject": "{{title}}",
    "link": "{{url}}"
  },
  "matchers": [
    "{ {{content}} | replace: '*@*.*', {{url}} }"
  ],
  "mode": "clean"
}

**Comment by cantino** [comment]
I'm confused about what you're trying to do @signallhill.  Are you trying to output a message with replacements?

Something like this?

```
{
"instructions": {
"message": "{{content | replace: '@.*', url }}"
},
"mode": "clean"
}
```

**Comment by signallhill** [comment]
@cantino I have a Event that coming into into Event Formatting Agent looks like this

{
  "id": "829f845279611d7925146725317b868d",
  "date_published": "2014-09-11 01:30:00 -0700",
  "last_updated": "Thu, 11 Sep 2014 01:30:00 -0700",
  "url": "http://example.com/...",
  "urls": [ "http://example.com/..." ],
  "description": "Some description",
  "content": "Some content",
  "title": "Some title",
  "authors": [ ... ],
  "categories": [ ... ]
}

I am trying to format that event where the content is filtered by replacing all emails in the content with a the url of the above event.

**Comment by knu** [comment]
If `@.*` is intended to be a regular expression, use `regex_replace` instead.  See [this Wiki page](https://github.com/cantino/huginn/wiki/Formatting-Events-using-Liquid) for details.

**Comment by signallhill** [comment]
@knu thanks. I looked that up this morning and figured it out.

**Comment by cantino** [comment]
Nice.  Want to add it to https://github.com/cantino/huginn/wiki/Agent-configuration-examples ?

**Comment by signallhill** [comment]
Yes

**Comment by signallhill** [comment]
Done

**Comment by signallhill** [comment]
@cantino if a non-tech person had to be a huginn expert what would that person need to know on the technical side? I see ruby on rails, mysql, linux. But does the person need to be good at all of these?

**Comment by cantino** [comment]
Thanks!
