### ISSUE TITLE
Huginn Crash

### ISSUE THREAD

**Issue by kaogaau** [cantino/huginn#1155]
Hi,

I'm using Huginn on my PC server(Linux Mint RAM 32G 8 Core CPU ruby-2.2.2 rails 4.2.2), however, I write three test agents ,first send a post to the webhook URI ,then webhook get the post and create a events,then last test agents create a events if get the webhook events,I create 900 sets(3 agents = 1set)and run use two workers , when I run for a long time,gen the error message then huginn sersver stop.

The error message :
===============================================================================
22:33:16 jobs.1 | exited with code 0
22:33:16 system | sending SIGTERM to all processes
22:33:16 web.1  | [2015-11-12 22:33:16] FATAL SignalException: SIGTERM
22:33:16 web.1  | 	/home/austin/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:174:in `select'
22:33:16 web.1  | 	/home/austin/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:174:in `block in start'
22:33:16 web.1  | 	/home/austin/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:32:in `start'
22:33:16 web.1  | 	/home/austin/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:162:in `start'
22:33:16 web.1  | 	/home/austin/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/handler/webrick.rb:34:in `run'
22:33:16 web.1  | 	/home/austin/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
22:33:16 web.1  | 	/home/austin/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands/server.rb:80:in `start'
22:33:16 web.1  | 	/home/austin/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:80:in `block in server'
22:33:16 web.1  | 	/home/austin/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:75:in `tap'
22:33:16 web.1  | 	/home/austin/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:75:in `server'
22:33:16 web.1  | 	/home/austin/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
22:33:16 web.1  | 	/home/austin/.rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands.rb:17:in `<top (required)>'
22:33:16 web.1  | 	/home/austin/tool/huginn_3001/bin/rails:8:in `require'
22:33:16 web.1  | 	/home/austin/tool/huginn_3001/bin/rails:8:in `<top (required)>'
22:33:16 web.1  | 	/home/austin/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/client/rails.rb:28:in `load'
22:33:16 web.1  | 	/home/austin/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/client/rails.rb:28:in `call'
22:33:16 web.1  | 	/home/austin/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/client/command.rb:7:in `call'
22:33:16 web.1  | 	/home/austin/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/client.rb:26:in `run'
22:33:16 web.1  | 	/home/austin/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/bin/spring:48:in `<top (required)>'
22:33:16 web.1  | 	/home/austin/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/binstub.rb:11:in `load'
22:33:16 web.1  | 	/home/austin/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/binstub.rb:11:in `<top (required)>'
22:33:16 web.1  | 	/home/austin/tool/huginn_3001/bin/spring:13:in `require'
22:33:16 web.1  | 	/home/austin/tool/huginn_3001/bin/spring:13:in `<top (required)>'
22:33:16 web.1  | 	bin/rails:3:in `load'
22:33:16 web.1  | 	bin/rails:3:in `<main>'
22:33:16 web.1  | [2015-11-12 22:33:16] INFO  going to shutdown ...
22:33:16 web.1  | [2015-11-12 22:33:16] INFO  WEBrick::HTTPServer#start done.
22:33:16 web.1  | Exiting
22:33:16 web.1  | terminated by SIGTERM
22:33:16 dj2.1  | exited with code 0
===============================================================================
Has anyone get the same problem ?
Sincerely

**Comment by cantino** [comment]
SIGTERM means that a process asked Huginn to exit, I think.  Did it run out of RAM, or maybe you restarted the computer or used the process manager or something?

**Comment by cantino** [comment]
Closing since we haven't heard back.  Hope it's working for you!
