### ISSUE TITLE
Hello I need Help With WebsiteAgent 

### ISSUE THREAD

**Issue by ydaniels** [cantino/huginn#1157]
I am trying to scrape or generate rss for this website cosmopolitan.com/style-beauty/ by getting the title , a little text from the article and the image. I am pretty sure my css  are correct

my settings
```
{
 
            expected_update_period_in_days: 1
            url:  http://www.cosmopolitan.com/style-beauty/
            type: html
            mode: on_change
           extract:
             {
                  title:{
                        css:#landing-feed--story-title link link-txt
                         value: .//text()
                         }
             main-text:{
                 css: #abstract-text
                   value: .//text()
                             }
                    link:{
                          css: #landing-feed--story-title link link-txt
                 value: @href
                        }
                      image:
                           {
                                css: #swap-image lazy-loaded
                                value: @data-img320
                                }
}
}```


The problem is, if i run it brings out nothing

**Comment by cantino** [comment]
I assume that you have quotes around all of those values in the actual
settings?

When you use dry run, it finds nothing?

**Comment by signallhill** [comment]
@ydaniels is this what you are looking for?

{
  "expected_update_period_in_days": "2",
  "url": "http://www.cosmopolitan.com/style-beauty/",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "title": {
      "css": ".landing-feed--story-title",
      "value": ".//text()"
    },
    "main-text": {
      "css": ".abstract-text",
      "value": "@title"
    },
    "link": {
      "css": ".landing-feed--story-title",
      "value": "@href"
    },
    "image": {
      "css": ".story-image--link",
      "value": "@data-img320"
    }
  }
}

**Comment by signallhill** [comment]
@ydaniels use Cantino Selector Gadget to get the correct CSS

http://selectorgadget.com/

**Comment by cantino** [comment]
Can I close this issue?
