### ISSUE TITLE
Update Huginn on Heroku with Dropbox?

### ISSUE THREAD

**Issue by wootwoot1234** [cantino/huginn#1160]
I deployed Huginn on Heroku a while back (maybe a year ago) and I can't create agents anymore for some reason.  I figured it was time to update to the latest version and when I logged into Heroku I noticed that my app is connected to dropbox.  Can I update my installation using dropbox?  It looks like I have a copy of the huginn code on my computer in my dropbox folder.  

Will it work to update and commit the code in Dropbox following the update instructions?

https://github.com/cantino/huginn/blob/9c5847451b2f084f82796aff1243d01d410bc04a/doc/manual/update.md

**Comment by cantino** [comment]
You have to update heroku with git on the command line. Please see our wiki
or the heroku docs.

Unfortunately you can't host a Rails application in Dropbox.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further.
