### ISSUE TITLE
website agent xpath woes

### ISSUE THREAD

**Issue by ronajon** [cantino/huginn#1168]
i'm trying to use a website agent to get data from a site into RSS
title and description are working, but somehow i don't get a description and image into the list.

here's the site
http://www.marktplaats.nl/z/motoren/dnepr.html?query=dnepr+AND+ural&searchOnTitleAndDescription=true&categoryId=678&numberOfResultsPerPage=100

and this is my webagent

{
  "expected_update_period_in_days": "1",
  "url": "http://www.marktplaats.nl/z/motoren/dnepr.html?query=dnepr+AND+ural&searchOnTitleAndDescription=true&categoryId=678&numberOfResultsPerPage=100",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "title": {
      "xpath": "//*[@id=\"search-results\"]/section[2]/article",
      "value": "./div/div[1]/div[1]/h2/a/span/@title"
    },
    "link": {
      "xpath": "//*[@id=\"search-results\"]/section[2]/article",
      "value": "./div/div[1]/div[1]/h2/a/@href"
    },
    "description": {
      "xpath": "//*[@id=\"search-results\"]/section[2]/article",
      "value": "concat(\"descr.\",./div/div[1]/div[1]/a/span[1]/text(),./div/div[1]/div[1]/a/span[3]/text())"
    },
    "image": {
      "xpath": "//*[@id=\"search-results\"]/section[2]/article",
      "value": "concat(\"http:\",./figure/a/div/img/@src)"
    },
    "pubdate": {
      "xpath": "//*[@id=\"search-results\"]/section[2]/article",
      "value": "normalize-space(./div/div[2]/div[2][@class='date'])"
    }
  }
}

**Comment by cantino** [comment]
You could try using CSS and selectorgadget.com and see if you get better selectors?

**Comment by ronajon** [comment]
it's working with CSS 

{
  "expected_update_period_in_days": "1",
  "url": "http://www.marktplaats.nl/z/motoren/dnepr.html?query=dnepr+AND+ural&searchOnTitleAndDescription=true&categoryId=678&numberOfResultsPerPage=100",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "title": {
      "css": ".mp-listing-title",
      "value": ".//text()"
    },
    "link": {
      "css": ".heading a",
      "value": "@href"
    },
    "description": {
      "css": ".mp-listing-description",
      "value": ".//text()"
    },
    "image": {
      "css": ".listing-image img",
      "value": "concat(\"http:\",@src)"
    },
    "pubdate": {
      "css": ".date",
      "value": "normalize-space(.//text())"
    },
    "price": {
      "css": ".price-new",
      "value": "normalize-space(.//text())"
    }
  }
}

**Comment by cantino** [comment]
Great, I'm glad it's working!  Can I close this issue?

**Comment by ronajon** [comment]
yes it can be closed.
thx
