### ISSUE TITLE
Impossible to have access to Huginn (error 403 with Apache)

### ISSUE THREAD

**Issue by jschav88** [cantino/huginn#1170]
Hello, i have a little problem with Huginn installation.  I have installed Huginn on Ubuntu 14.04 (VirtualBox VM) following your tutorial. Once finished, it's impossible to have access to the application :

*Forbidden*
*You don't have permission to access / on this server.*

Apache log : 

    Cannot serve directory /home/huginn/huginn/public/: 
    No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, 
    and server-generated directory index forbidden by Options directive

Apache SSL/TLS configuration : 

    <IfModule mod_ssl.c>
        <VirtualHost _default_:443>
                ServerName www.domain.tld
                ServerAdmin xxx@yyy.tld
                DocumentRoot /home/huginn/huginn/public/
                ErrorLog ${APACHE_LOG_DIR}/error.log
                CustomLog ${APACHE_LOG_DIR}/access.log combined
                LogLevel warn
                SSLEngine on
                SSLCertificateFile /etc/PATH/certificat.crt
                SSLCertificateKeyFile /etc/PATH/cle.key
                SSLVerifyClient none
                #SSLVerifyDepth  10
                #SSLOptions +FakeBasicAuth +ExportCertData +StrictRequire
                <FilesMatch "\.(cgi|shtml|phtml|php)$">
                                SSLOptions +StdEnvVars
                </FilesMatch>
                <Directory /usr/lib/cgi-bin>
                                SSLOptions +StdEnvVars
                </Directory>
                BrowserMatch "MSIE [2-6]" \
                                nokeepalive ssl-unclean-shutdown \
                                downgrade-1.0 force-response-1.0
                BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

                RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
                RewriteRule ^/(.*)$ balancer://upstream%{REQUEST_URI} [P,QSA,L]

                <Proxy balancer://upstream>
                        BalancerMember http://127.0.0.1:3000
                </Proxy>

                ProxyRequests Off
                ProxyVia On
                ProxyPreserveHost On
                RequestHeader set X_FORWARDED_PROTO https
             	 <Proxy *>
                        Require all granted
                </Proxy>

                <Directory /home/huginn/huginn/public/>
                        Require all granted
                        AllowOverride all
                        Options -MultiViews
                </Directory>
        </VirtualHost>

Check : 

    /home/huginn/huginn# sudo rake production:start
    Startig huginn ...
    ok: run: huginn-web-1: (pid 26146) 152s
    ok: run: huginn-jobs-1: (pid 26149) 152s

    :/home/huginn/huginn# sudo rake production:check
    [  OK  ] Everything is fine

Did i miss something ? 

Thank you.

**Comment by dsander** [comment]
Hi @jschav88,

maybe the [wiki page about apache](https://github.com/cantino/huginn/wiki/Apache-Huginn-configuration) helps?

You also need to change `listen "#{wd}/tmp/sockets/unicorn.socket"`in config/unicorn.rb to `listen "127.0.0.1:3000"` (but that is unrelated to the 403 error you are getting.

**Comment by jschav88** [comment]
Thank you. 

i followed the wiki page about apache earlier. So i decided to reinstall from scratch and it works.

**Comment by dsander** [comment]
Great! :smile:
