### ISSUE TITLE
How to scrape data from a dynamic website that requires user interaction

### ISSUE THREAD

**Issue by cindyborg** [cantino/huginn#1171]
I just found Huginn and is learning how to use it.
I need to scrape data from a website with dynamic data. It requires user input first to get the rendered page with the data I want (ie. select an option from a drop down list, then click a button). 
Is there a way to achieve this through huginn agents only? ( I have looked at Website agent and webhook agent). Or do I have to write extra ruby code to simulate the user interactions and pass in the rendered page to an agent? If that's the case, how would I pass in the rendered page?

Thanks
Cindy

**Comment by cantino** [comment]
Welcome @cindyborg!

If you can create a web request with curl that does the action you want, it should be possible with Huginn.  (See the Chrome Developer Tools' network tab which you can right-click for a copy to curl option.)  Huginn can't interact with JavaScript, though, so it's not easy to script a behavior like clicking around on a site.

**Comment by cindyborg** [comment]
Thanks @cantino for the prompt response.
Unfortunately the user interactions are through client side JavaScript, it doesn't send any request to the server. 
I am looking at using Selenium Ruby APIs to simulate the user interactions to get the rendered html page first, then pass in the rendered page to a Huginn agent. Which agent can I use to pass in the rendered html page? I saw an example of using Webhook agent as an API with php, can I call the webhook/website agent as well through my Ruby project?

**Comment by cantino** [comment]
I think it would be reasonable to write a separate Ruby app that uses selenium (or phantomjs) to script the interface.  At that point, you'd need to decide if you get any benefit from Huginn beyond just adding behavior to this new app.  What is the problem that you're trying to solve?

**Comment by cindyborg** [comment]
Thanks @cantino.
We are trying to build a scraping tool that can scrape data from different websites either with static data or dynamic data. We would like to use Huginn agent as it gives us scheduling and monitoring options.
 
With one particular website I am building my prototype with, I found it requires user interaction before the data we interested in will be loaded. The user interaction is handled by JavaScript. 
I am considering the following two options with this case:
1. Try to get the rendered page through a separate Ruby app using selenium API as you mentioned and pass in to webhook agent. 
2. With this particular website, I found the data I am interested in have been loaded initially into the page source in the form of a Json string stored as a var for a JavaScript. I tried to parse the Json string through a couple of events using website agent.  Below is my snippet for the second website agent, the "Source" field is set to the first website agent, I have tried to use " "url_from_event": "{{url}}"  " as well, but it doesn't work and no error is logged. 
{
  "expected_update_period_in_days": "2",
  "url": "{{url}}",
  "type": "html",
  "mode": "merge",
  "extract": {
    "data2": {
      "xpath": "{{message}}"
    }
  }
}

**Comment by cantino** [comment]
Sometimes I've been able to watch the networking tab and infer a request route that it's using to load the data, then hit that directly in order to go around the selenium route (which can be a pain), other times I've had to use selenium because the ajax request formats that the site is using are too hard to figure out.  As someone who's done a lot of scraping, I also humbly recommend SelectorGadget for making extraction selectors. ;)

If you're trying to get JSON data embedded in a JS variable, you'll probably need to either use regular expressions to get the JSON string, then parse it.  This sounds easier in native Ruby with open-uri and regexp than in Huginn, to be honest.

**Comment by signallhill** [comment]
@cantino How is this done?

"If you can create a web request with curl that does the action you want, it should be possible with Huginn. (See the Chrome Developer Tools' network tab which you can right-click for a copy to curl option.)"

**Comment by cantino** [comment]
Using the website agent or the post agent.

**Comment by signallhill** [comment]
@cantino Please help with the post Agent. Below is response header from network tab in Chrome



GET /c/pagination?inputJSON=%7B%22startPage%22%3A30%2C%22articleId%22%3A%221adac%22%7D HTTP/1.1
Host: www.xyz.com
Connection: keep-alive
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
Referer: https://www.xyz.com/c/d
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: __uvt=; e18d5d532a99a.1445623125.5.1450122485.1449679512.a2400eb9-7418-4311-ac40-4993ed2b0e7b; spdiceses.b640=*

**Comment by signallhill** [comment]
@cantino Once the curl option is copied, is that used in url in website agent. Can you give an example if you have one.

**Comment by cantino** [comment]
It couldn't be used verbatim.  You'd need to tease apart the options and provide them to Huginn, for example `curl --data "param1=value1&param2=value2"` means it's POSTing two params.  You would use a PostAgent to make the request in this case.  Eventually the WebsiteAgent will probably also be able to make POSTs if someone adds that feature.

**Comment by signallhill** [comment]
Ok I will try.

**Comment by cantino** [comment]
Can I close this issue?
