### ISSUE TITLE
Need help with regexp (Event formatting Agent)

### ISSUE THREAD

**Issue by memorex258** [cantino/huginn#1172]
I tested the regex on Rubular http://rubular.com/r/LQqN0SnExv
but I do not know why I can not get the sale date to match.

Here is the string

"01/28/2016\t10:00:00 AM\tMagner"

Here is the json 

{
  "instructions": {
    "saledate": "{{saledate.1}}",
    "saletime": "{{saletime.1}}",
    "name": "{{name.1}}"
  },
  "matchers": [
    {
      "path": "{{text}}",
      "regexp": "saledate : (\\d*\\/\\d*\\/\\d*)",
      "to": "saledate"
    },
    {
      "path": "{{text}}",
      "regexp": "saletime : (\\d*:\\d*:\\d*..M)",
      "to": "saletime"
    },
    {
      "path": "{{text}}",
      "regexp": "name : ([a-zA-Z]*)",
      "to": "name"
    }
  ],
  "mode": "merge"
}

**Comment by cantino** [comment]
I think you may need two backslashes on the `\\d`s?

**Comment by memorex258** [comment]
not sure how i did that but thank you

**Comment by cantino** [comment]
No problem!
