### ISSUE TITLE
Web formatting - missing css styles?

### ISSUE THREAD

**Issue by tom130** [cantino/huginn#1177]
Hi guys,
I need your help. After manual installation on Debian 8 I am getting these outputs from SERVERIP:3000

![webformatting](https://cloud.githubusercontent.com/assets/1492611/11682700/caddbc04-9e66-11e5-929a-e8fb341ffa24.JPG)
I think i might have forgotten something in .env. Rake status and check are OK. But I think that page css style 
is missing. If i check css I get 
```
<!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <style type="text/css">
    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }
    div.dialog {
      width: 25em;
      padding: 0 4em;
      margin: 4em auto 0 auto;
      border: 1px solid #ccc;
      border-right-color: #999;
      border-bottom-color: #999;
    }
    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }
  </style>
</head>

<body>
  <!-- This file lives in public/404.html -->
  <div class="dialog">
    <h1>The page you were looking for doesn't exist.</h1>
    <p>You may have mistyped the address or the page may have moved.</p>
  </div>
</body>
</html>
```

Thank you for your help!

**Comment by dsander** [comment]
Hi @tom130,

when you are done with the manual installation guide the server should not be running on port 3000 but be proxied by nginx via port 80. After you start huginn and nginx, the instance should be accessigble via `http://<service_ip>`

**Comment by tom130** [comment]
Hi @dsander ,
so I started from clean OS install again :/. And I get 502 Bad Gateway. 
Let´s recapitulate, what I did:
* followed all commands instead of setting SSL
* changed in .env database credetials (and DATABASE_NAME=huginn_production) and uncommented RAILS_ENV=production
* uncommented in Procfile production
 web: bundle exec unicorn -c config/unicorn.rb
 jobs: bundle exec rails runner bin/threaded.rb
* of course reexported

and the output from sudo rake production:status is nothing, only development with that port slightly works (which causes the missing css)

Debugs:
/home/huginn/huginn/log/unicorn.log: No such file or directory
/home/huginn/huginn/log/production.log last info from migration
/home/huginn/huginn/log/*/current No such file or directory

Docker works, but I would like to use SSL certificate and IMHO safer manual installation

Should I try Wheezy?

**Comment by dsander** [comment]
You did start the instance with `sudo rake production:start` after reexporting, right?

The process you described read correct to me, not sure if if the leading spaces in front of ` web` and ` jobs` in your Procfile might be causing problems.

Jessi should work fine, at at least it did when I last tested the installation a few months ago.

**Comment by signallhill** [comment]
I had similar issue when I did HTTPS commands listed here
https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#using-https

I had to go back and re-enter FQDN in NGINX config which solved it.

**Comment by tom130** [comment]
Hi @signallhill,
Firstly I thought that nginx is causing this problem, but now I don`t have any Huginn instance running. So maybe I would focus on Ruby? 

@dsander thank you for your notes, I will definitely look into that spaces. And yes I started the instance :)

**Comment by tom130** [comment]
Ok, thank you @dsander . The problem was in spaces in Procfile.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further.
