### ISSUE TITLE
Build for Heroku fails

### ISSUE THREAD

**Issue by tomkofford** [cantino/huginn#1178]
I'm a noob at Heroku and ruby. I'm getting the following from both the readme button deploy and by running setup_heroku from my local environment. I'm on a mac, have huggin running fine locally. Not sure if this helps, but my local environment wouldn't work until I ran bundle update. Not sure if by doing that it updated something that wasn't planned for. My local .env file looks fine to me - I've also tried a copy of the template with no changes and I get the same error.Anyhow, any help is appreciated. Here's the error from setup_heroku (substituted "hex" for tmp directory name in a couple of spots):

> -----> Fetching set buildpack https://github.com/heroku/heroku-buildpack-multi.git... done
> -----> Multipack app detected
> =====> Downloading Buildpack: https://github.com/cantino/heroku-selectable-procfile.git
> =====> Detected Framework: Selectable Procfile
> -----> Using deployment/heroku/Procfile.heroku as Procfile
> =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-ruby.git
> =====> Detected Framework: Ruby
> -----> Compiling Ruby/Rails
> sh: 2: Syntax error: Unterminated quoted string
>  !
>  !     There was an error parsing your Gemfile, we cannot continue
>  !     Could not load huginn settings from .env file.
>  !     
>  !     Make sure to copy the .env.example to .env and change it to match your configuration.
>  !     
>  !     Capistrano 2 users: Make sure shared files are symlinked before bundle runs: before 'bundle:install', 'deploy:symlink_configs'
>  !     /tmp/build_hex/cantino-huginn-f49ef15/lib/gemfile_helper.rb:25:in `sanity_check': Could not load huginn settings from .env file. (RuntimeError)
>  !     /tmp/build_hex/cantino-huginn-f49ef15/lib/gemfile_helper.rb:13:in `load_dotenv'
>  !     /tmp/build_hex/cantino-huginn-f49ef15/Gemfile:8:in `eval_gemfile'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/dsl.rb:32:in `instance_eval'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/dsl.rb:32:in `eval_gemfile'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/dsl.rb:10:in `evaluate'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/definition.rb:25:in `build'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler.rb:155:in `definition'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/cli/check.rb:11:in `run'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/cli.rb:103:in `check'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/cli.rb:10:in `start'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/bin/bundle:20:in `block in <top (required)>'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/gems/bundler-1.9.7/bin/bundle:18:in `<top (required)>'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/bin/bundle:23:in `load'
>  !     /tmp/d20151210-216-1qt1b6m/bundler-1.9.7/bin/bundle:23:in `<main>'
>  !     There was an error in your Gemfile, and Bundler cannot continue.
>  !
>  !     Push rejected, failed to compile Multipack app

**Comment by cantino** [comment]
Hey @tomkofford, thanks for letting us know!  Indeed, when I tried the Heroku button just now it failed for me as well.

@dsander, this looks related to our recent Gemfile changes.

**Comment by dsander** [comment]
Darn, totally forgot about checking heroku, I'll look into it.

**Comment by dsander** [comment]
Hi @tomkofford, can you retry the deployment on heroku? It should be working now.

**Comment by tomkofford** [comment]
Tried from my local environment and it worked great now! Issue resolved. Thanks, gents!
