### ISSUE TITLE
Change HTTPS port from 443 to 8443 /

### ISSUE THREAD

**Issue by TheReal1604** [cantino/huginn#1180]
Hey Guys,

got a little problem in configuring the apache reverse proxy like in this wiki article:

https://github.com/cantino/huginn/wiki/Apache-Huginn-configuration

I got on the same machine an owncloud installation that is bound on port 443 so i want to use 8443 or a subdirectory.

Can anyone give a little tutorial on how to do this?

My virtualhost config for huginn looks like:

# Make sure mod_ssl, mod_rewrite, mod_headers, mod_proxy,
# mod_proxy_http and mod_proxy_balancer are enabled

<VirtualHost *:80>
    ServerName xxx.de
    RedirectPermanent / https://xxx.de/
</VirtualHost>
<VirtualHost *:8443>
    ServerName xxx.de
    DocumentRoot /var/www/huginn/

    RewriteEngine On

    RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
    RewriteRule ^/(.*)$ balancer://upstream%{REQUEST_URI} [P,QSA,L]

    <Proxy balancer://upstream>
        BalancerMember http://127.0.0.1:5000
    </Proxy>

    ProxyRequests Off
    ProxyVia On
    ProxyPreserveHost On
    RequestHeader set X_FORWARDED_PROTO https

     <Proxy *>
         Require all granted
    </Proxy>

    <Directory /var/www/huginn>
        Require all granted
        AllowOverride all
        Options -MultiViews
    </Directory>

    SSLEngine On
    SSLCertificateFile    /etc/apache2/ssl/xxxx.crt
    SSLCACertificateFile  /etc/apache2/ssl/xxx.ca.crt
    SSLCertificateKeyFile /etc/apache2/ssl/xxx.key
    # maybe not needed, need for example for startssl to point to a local
    # copy of http://www.startssl.com/certs/sub.class1.server.ca.pem
</VirtualHost>

At this point i get a "error connection closed / Site not available" in my browser.

Thanks!

Greez
TheReal

**Comment by TheReal1604** [comment]
Hey Guys,

now.. with the port 8443 in ports.conf it works.. Damn Sry for that.

But at this point, all css is missing. Anyone have an idea?

Thx.
Greez
TheReal

**Comment by cantino** [comment]
You probably have to compile assets.  Did you follow the installation guide?

**Comment by TheReal1604** [comment]
Hi Andrew,

i did not found the complete installation guide direct.. But I found it now.

Got several other problems with my installation, i decided to use the docker container to have less trouble :-). Did you have an clean uninstall guide? ;-)

Thx you can close the issue.

Greetz
TheReal

Am 17.12.2015 um 05:22 schrieb Andrew Cantino <notifications@github.com<mailto:notifications@github.com>>:


You probably have to compile assets. Did you follow the installation guide?

-

**Comment by cantino** [comment]
Glad it's working!
