### ISSUE TITLE
Parse Data from Website Agent

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1182]
I have website agent with following. On extract what should I do, I am trying to parse searchResults.

```
{
  "expected_update_period_in_days": "30",
  "url": [
    "https://www.xyz.com/page1"
    ],
  "type": "json",
  "mode": "on_change",
  "extract": {
    "title": {
      "path": "data-content.h[3].a.title"
    },
    "description": {
      "path": "data-content.h[3].shortdesc",
"url":{
      "path":"data-content.h[3].position.a.href"
    }
  },
  "headers": {
    "Cookie": "something"
}
}
```

Data looks like this

```
   "total":2,
   "pageCount":1,
   "count":30,
   "searchResults":"<div class='data-content'>
   <h3>
   <a title=\"Title 1" id=\"position0\" href=https://www.xyz.com/title1>title1<span class='status-indicator icon-preview-1 visited'><\/span><span class='status-indicator icon-star-1 saveaction' isSaved='false' id=\"158beaef777\"><\/span><\/a><\/h3>
   <div class='shortdesc'>short description<\/div><ul class='list-inline'><li>location1<\/li><li>date1<\/li><li class='easy'>Submit<\/li><\/ul'><\/div>
  <div class='data-content'>
  <h3>
  <a title=\"Title " id=\"position1\" href=https://www.xyz.com/title2>title2<span class='status-indicator icon-preview-1 visited'><\/span><span class='status-indicator icon-star-1 saveaction' isSaved='false' id=\"s514ce9e0ba4f\"><\/span><\/a><\/h3>
  <div class='shortdesc'>short description<\/div><ul class='list-inline'><li>location2<\/li><li>date2<\/li><li class='easy'>Submit<\/li><\/ul'><\/div>",
   "page":2
```

**Comment by cantino** [comment]
The easiest thing would be to send `searchResults` to a WebsiteAgent using the `event_data_path` feature provided in #1161.  Unfortunately, that's not in master yet.  I'll try to get it in soon.

**Comment by cantino** [comment]
#1161 has now been merged.

**Comment by signallhill** [comment]
@cantino Thank you. I updated but am I using it correct. 

{
  "expected_update_period_in_days": "30",
  "url": [
    "https://www.xyz.com/page1"
  ],
  "type": "json",
  "mode": "on_change",
  "extract": {
    "title": {
      "path": "data-content.h[3].a.title"
    },
    "description": {
      "path": "data-content.h[3].shortdesc"
    },
    "url": {
      "path": "data-content.h[3].position.a.href"
    }
  },
  "headers": {
    "Cookie": "something"
  },
  "data_from_event": "{{searchResults}}"
}

**Comment by signallhill** [comment]
Thank you I have updated and able to use it perfectly. 

Thank you again.
