### ISSUE TITLE
Twitter Oauth

### ISSUE THREAD

**Issue by upperhead** [cantino/huginn#1184]
Hi there, 

i need your help. I'm running huginn via terminal.com. I try to set up a twitter stream agent. I opend the .env file and completed it with my oauth token und secret. Then i restarted my terminal but huginn is not able to find the service. Where is my mistake? 

Thank you in advance
Stefan

**Comment by dsander** [comment]
Hi @upperhead,

by "huginn is not able to find the service" you mean that the "authenticate with twitter" button is not showing up in the services page?
If that is the case I guess the restart did not work properly, the button will be shown when the `TWITTER_OAUTH_KEY` and `TWITTER_OAUTH_SECRET` environment variables are present and twitter related gems in the Gemfile are available (which is the case per default).

**Comment by upperhead** [comment]
Hi Dominik, 

thx for your reply, Yes, you are right. There is no Authentication Button. I start my Terminal open then the .env File and fullfill Twitter_oauth_key and Twitter_oauth_secret. After that i restart my terminal session but with no effect. What went wrong? Do i have to start huginn separatly from my terminal?

Regards, 

Stefan

**Comment by dsander** [comment]
I have no experience with terminal.com myself, do you have a console open where `bundle exec foreman start` is running?

**Comment by upperhead** [comment]
Hi Dominik, 
after hours of testing i deleted my huginn snapshot and started from scratch with a ubuntu snapshot. After your install guide the rake production check says fine and nginx is running too. But now unfortunatly im running in a 502 Bad Gateway Error. The error HTML shows me Openresty instead of nginx. Is that correct? 

Greetings from Cologne!

Stefan

**Comment by upperhead** [comment]
Hi Dominik, 

the problem is solved. I think it was a problem with terminal.com. Now i use the snapshot again. With the snapshot a sudo rake production:export and start did the magic. Thanks for your help. 

Have a nice holiday!

Regards 

Stefan
