### ISSUE TITLE
Issue with CSS

### ISSUE THREAD

**Issue by cyberactive** [cantino/huginn#1185]
Im probably screwing up something simple but for the life of me I can not get simple css selectors to work with the following forum.

```
{
  "expected_update_period_in_days": "1",
  "url": "https://forums.servethehome.com/index.php?forums/processors-and-motherboards.18/",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "thread": {
      "css": ".titleText .title",
      "value": ".//text()"
    }
  }
}
```

Seems to work in selectorgadget and chrome developer tools.

**Comment by cantino** [comment]
Hey @cyberactive, this is an odd one.  I think that this site is giving Huginn different content than it gives the browser.  When I do a dry run with `"thread": { "css": "html", "value": "." }`, I don't see any occurrences of `titleText`.  You could try setting the `user_agent` to the one used by Chrome and see if it changes anything.

**Comment by cyberactive** [comment]
Yeah even setting the UA to chrome makes no difference. I even tested using
no script on Firefox to  see if that gets the same treatment as huginn. I
will investigate this more after the holiday.

**Comment by cantino** [comment]
Did you solve this @cyberactive?
