### ISSUE TITLE
Twitter Stream Agents - Filter & Language

### ISSUE THREAD

**Issue by upperhead** [cantino/huginn#1187]
Hi, 

thanks for a great piece of software, but i have some trouble with my twitter agents. I'm using the twitterstreamagent and twittersearchagent and only want to get german tweets which got retweeted:

{
  "filters": [
    #christmas
  ],
  "lang": "de",
  "retweeted": true, 
  "generate": "events",
  "expected_update_period_in_days": "2"
} 

But im getting results in english and not retweeted. Is there something i missed?

I wish you nice holidays!

Regards, 
Stefan

**Comment by cantino** [comment]
Hey @upperhead, welcome!  I don't think we support the `lang` option right now.  That probably wouldn't be too hard to add if you wanted to give it a try, but right now we don't pass that on to Twitter.

**Comment by upperhead** [comment]
Hi @cantino, thx for your reply. Could you please give me a hint how to add the properties to my agent? I found the ruby file for my agent, but adding lang, retweet_count etc. to opt is far to easy i think :).

**Comment by cantino** [comment]
You could try changing line 187 of twitter_stream_agent.rb to be

```ruby
          :path    => "/1/statuses/#{(filters && filters.length > 0) ? 'filter' : 'sample'}.json?track=#{filters.map {|f| CGI::escape(f) }.join(",")}&language=en,fr",
```

(for example)

if that works, we can wire it through from the Agent.  It wasn't obvious to me if the Twitter API accepts `language` on the filter endpoint.  It probably does?  https://dev.twitter.com/streaming/overview/request-parameters#track

**Comment by cantino** [comment]
Did you try that code @upperhead?
