### ISSUE TITLE
[Suggestion] Allow PushBullet Agent to push to multiple devices or channels

### ISSUE THREAD

**Issue by JamiePhonic** [cantino/huginn#1190]
I think the pushbullet agent should be modified to allow events to be pushed to all devices a user has (by not specifying a device to push to) or additionally to a channel (by specifying the channel tag).

**Comment by dsander** [comment]
@JamiePhonic This would not require a lot of changes, are you interested in doing it yourself? I would of course point you in the right direction and help along the way.

**Comment by JamiePhonic** [comment]
I would be willing to give it a go, however I've never used ruby, and I only know a bit of java and a good ammount of LUA and I'm not sure how to make it work around the first time you use it where it creates a device called huginn if you don't select a device.

Perhaps by creating a "device" called "All" and handling it that way?
I'll start on broadcasting to all devices, then if I can make that work, I'll take a crack at channels.

**Comment by dsander** [comment]
Great!

> Perhaps by adding a "device" to the list called "All" and handling it that way in code?

That sounds like the right direction. The [pushbullet API](https://docs.pushbullet.com/#create-push) states that when we do not specify a `device_iden` the push will be send to all registered devices. [This method](https://github.com/cantino/huginn/blob/master/app/models/agents/pushbullet_agent.rb#L102-L107) of the `PushbulletAgent` is responsible for returning the device list, which will then be shown in the `Device` configuration drop down. 

So my suggestion is to add a "Broadcast to all devices" dropdown value and then check if that value was selected in the [receive](https://github.com/cantino/huginn/blob/master/app/models/agents/pushbullet_agent.rb#L84) method. When that is the case setting the `device_iden` in the hash that is passed to the `request` method to `nil` should send the push to all devices.

**Comment by dsander** [comment]
@JamiePhonic Sorry, I spoke too soon, updated the references in my above comment ^^

**Comment by JamiePhonic** [comment]
Ok, i think im making sence of this, but correct me if im wrong.

`def devices` calls `request` passing `devices` as the method which makes a get request to `https://api.pushbullet.com/v2/devices` supplying the API key as authentication.
It recieves a JSON string and stores that in the `response` variable.
It then singles out the `devices` array and adds each device to a new array `d` if it has `pushable` set to `true`

`complete_device_id` then uses that new array `d`, to retrieve the device `nickname` which is shown on the page, and the `id` which is what the code actually uses to specify the device to push to.

Am it on the right lines (keeping in mind, ive never even seen ruby code until about 3 hours ago)

**Comment by dsander** [comment]
> complete_device_id then uses that new array d, to retrieve the device nickname which is shown on the page, and the id which is what the code actually uses to specify the device to push to.

Almost, `devices.map` iterates over the array returned by `devices`, assignes each entry of the array to `d` and replaces the entry with the return value of the block, `{text: d['nickname'], id: d['iden']}` in this case.

> With all that in mind, i assume i just need to insert a new item into the end of the d array with the nickname "All" or "Broadcast" or something similar and an id of "" or "nul"

Yes, but I think you need to set the id to something like `__all__` the name does not really matter als long as is unlikely to collide with any device that is really used be pushbullet. An empty string will have the [create_device](https://github.com/cantino/huginn/blob/master/app/models/agents/pushbullet_agent.rb#L109-L115) method create a new device. In `query_options` you can then check if `mo[:device_id]` is set to the "special" id and set `device_iden` to `nil` if it is the case.

**Comment by JamiePhonic** [comment]
Ok, i made some good progress today. i had to add a variable called `devList` to the `complete_device_id` function to store the result of the `devices.map` operation, and add the new `All Devices` entry to the top of the new array with `devList.unshift`

the modified function is now:
`def complete_device_id
      devList = devices.map! { |d| {text: d['nickname'], id: d['iden']} }
      devList.unshift({:text=>"All Devices", :id=>"__ALL__"})
    end`

**Comment by JamiePhonic** [comment]
Ok, so i noticed that the travis-ci build failed because apparently it was expecting `{:text=>"huginn", :id=>"12345"}`, but got `[{:text=>"All Devices", :id=>"__ALL__"}, {:text=>"huginn", :id=>"12345"}]` instead, probably because its getting what is essentialy a hard coded device that it isnt expecting at the top of the array. I'm guessing it tests the code by supplying it with a device called `huginn` with an ID of `12345`?

**Comment by JamiePhonic** [comment]
I'll mark this as closed for now. if i get round to working on implementing channels, ill make a new PR
