### ISSUE TITLE
docker loses data

### ISSUE THREAD

**Issue by gdomod** [cantino/huginn#1192]
if i stop (ctrl +c) the docker instance i lose all data
need i link a db ? or should be work as standalone ?

docker run -it -p 3000:3000 cantino/huginn

**Comment by dsander** [comment]
Hi @gdomod,

you do not need to link to a database container, giving it a name will not destroy container after you stopped it.

```
docker run -it -p 3000:3000 --name huginn cantino/huginn
# stop it
docker start huginn
# data should still be available
```
alternatively you can link to a database container and make sure the database stores the data in a docker volume (that will keep the data on the docker host and not inside of the container), both the [mysql](https://hub.docker.com/_/mysql/) and [postgresql](https://hub.docker.com/_/postgres/) docker containers have documented how do to this in their readmes.

**Comment by gdomod** [comment]
my fault, i am an idiot :+1:
