### ISSUE TITLE
Dynamically change url based on event

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1193]
I get payload like the following - note pageCount: 2
``
  "total":2,
   "pageCount":2,
   "count":30,
   "searchResults":"<div class='data-content'>
   <h3>
   <a title=\"Title 1" id=\"position0\" href=https://www.xyz.com/title1>title1<span class='status-indicator icon-preview-1 visited'><\/span><span class='status-indicator icon-star-1 saveaction' isSaved='false' id=\"158beaef777\"><\/span><\/a><\/h3>
   <div class='shortdesc'>short description<\/div><ul class='list-inline'><li>location1<\/li><li>date1<\/li><li class='easy'>Submit<\/li><\/ul'><\/div>
  <div class='data-content'>
  <h3>
  <a title=\"Title " id=\"position1\" href=https://www.xyz.com/title2>title2<span class='status-indicator icon-preview-1 visited'><\/span><span class='status-indicator icon-star-1 saveaction' isSaved='false' id=\"s514ce9e0ba4f\"><\/span><\/a><\/h3>
  <div class='shortdesc'>short description<\/div><ul class='list-inline'><li>location2<\/li><li>date2<\/li><li class='easy'>Submit<\/li><\/ul'><\/div>",
   "page":2
``
Url is following www.abc.xyz/page1 and www.abc.xyz/page2 

I could have more pages in other payload. Is it possible to update the url based on the pageCount and input it to the agent. 

For Ex - If pageCount is 2 then output URL www.abc.xyz/page1 and www.abc.xyz/page2  
For Ex - If pageCount is 3 then output URL www.abc.xyz/page1 and www.abc.xyz/page2 and www.abc.xyz/page3

**Comment by cantino** [comment]
You could likely do this with Liquid, or perhaps more easily with the JavaScriptAgent.

**Comment by signallhill** [comment]
I have never done JS before, am I on the right track?

Website agent is sending count from above into the JSAgent.

Agent.receive = function() {
  var events = this.incomingEvents();
  for(var i = 0; i < events.count; i++) {
    this.createEvent({ 'url': 'http://www.abc.xyz/page'events[i].count});
  }
}

**Comment by cantino** [comment]
This is the right idea.  It's `length`, not `count`, and string concatenation in JS is with `+`, so something like `this.createEvent({ 'url': 'http://www.abc.xyz/page' + events[i].length });`

Can you test this using the Dry Run feature?

**Comment by signallhill** [comment]
Im getting following 
"url": "http://www.abc.xyz/pageundefined"

The input coming is 
 "count": 2

**Comment by cantino** [comment]
Sorry, the second count would be on the payload.  Something like:

```javascript
Agent.receive = function() {
  var events = this.incomingEvents();
  for(var i = 0; i < events.length; i++) {
    this.createEvent({ 'url': 'http://www.abc.xyz/page' + events[i].payload.count });
  }
}
```

**Comment by signallhill** [comment]
im getting only 1
"url": "http://www.abc.xyz/page2"

Is events.length counting the number of payload.
example: 
"count":2,3,4 
then events.length = 3

in my case events.length = 1

If I do following I get error  - JavaScript error: Cannot read property 'count' of undefined

Agent.receive = function() {
  var events = this.incomingEvents();
  for(var i = 0; i < events.payload.count; i++) {
    this.createEvent({ 'url': 'http://www.abc.xyz/page' + events[i].payload.count });
  }
}

**Comment by cantino** [comment]
You definitely want `for(var i = 0; i < events.length; i++) {` since `events` is an Array.  I think that your Agent is receiving Events one at a time, so the length of the array is always 1.  That should be okay, though, if the Event's `count` property in its payload is present.  It sounds like that's always set to 2?

**Comment by signallhill** [comment]
Sorry for the confusion

JSAgent will only receive 1 event

"count":x

but the value of ``count`` will be different. so x above can be any number. I am trying to generate url based on x. 
I also tried this but get cannot read 'count' of undefined

Agent.receive = function() {
var events = this.incomingEvents();
var x = events.payload.count;
for(var i = 0; i < x; i++) {
this.createEvent({ 'url': 'http://www.abc.xyz/page' + x[i] });
}
}

**Comment by cantino** [comment]
```javascript
Agent.receive = function() {
  var events = this.incomingEvents();
  for(var i = 0; i < events.length; i++) {
    this.createEvent({ 'url': 'http://www.abc.xyz/page' + events[i].payload.count });
  }
}
```

is the correct code if the `count` value of your event is the thing you want.  `events.length` is unrelated, and is code to make sure we look at all events being received.

**Comment by signallhill** [comment]
I don't want ``count`` value in my event. 

I want the number of events to be the count value. so if ``count`` is 3 I want to JSAgent to give me

"url": "http://www.abc.xyz/page1"
"url": "http://www.abc.xyz/page2"
"url": "http://www.abc.xyz/page3"

if ``count`` value is 5 then

"url": "http://www.abc.xyz/page1"
"url": "http://www.abc.xyz/page2"
"url": "http://www.abc.xyz/page3"
"url": "http://www.abc.xyz/page4"
"url": "http://www.abc.xyz/page5"

**Comment by cantino** [comment]
Oh, I see.

```javascript
Agent.receive = function() {
  var events = this.incomingEvents();
  for(var i = 0; i < events.length; i++) {
    for(var j = 1; j < events[i].payload.count + 1; j++) {
      this.createEvent({ 'url': 'http://www.abc.xyz/page' + j });
    }
  }
}
```

**Comment by signallhill** [comment]
Thanks this works. 

Last question: On WEBSITE Agent

Is it possible to merge the ``url`` that is being scraped with the payload? so below would give event like this
Payload:
{
"count":2
"url":"abc.com"
}

Website agent:

``{
  "expected_update_period_in_days": "2",
  "url": "abc.com",
  "type": "json",
  "mode": "on_change",
  "extract": {
    "count": {
      "path": ".Count"
    }
  }
}``

**Comment by cantino** [comment]
Nice! A `mode` of `merge ` works, I think.

**Comment by signallhill** [comment]
merge only works if Website agent is getting event from another agent. 

The above one is the starting point of the chain.

**Comment by cantino** [comment]
Oh.  Can you use a formatting agent?
