### ISSUE TITLE
MySQL migrations cause a bigger diff than expected

### ISSUE THREAD

**Issue by TildeWill** [cantino/huginn#1195]
Whenever I run database migrations (such as to add a new table as was the case below) I get a diff in schema.rb that shows lines touched that I didn't expect to change. It looks like the diff is mostly the `collation` property not being dumped, I also see a `limit: 1` being removed for `boolean` columns
```diff
   create_table "services", force: :cascade do |t|
     t.integer  "user_id",       limit: 4,                     null: false
-    t.string   "provider",      limit: 255,                   null: false, collation: "utf8_general_ci"
-    t.string   "name",          limit: 255,                   null: false, collation: "utf8_general_ci"
-    t.text     "token",         limit: 65535,                 null: false, collation: "utf8_general_ci"
-    t.text     "secret",        limit: 65535,                              collation: "utf8_general_ci"
-    t.text     "refresh_token", limit: 65535,                              collation: "utf8_general_ci"
+    t.string   "provider",      limit: 255,                   null: false
+    t.string   "name",          limit: 255,                   null: false
+    t.text     "token",         limit: 65535,                 null: false
+    t.text     "secret",        limit: 65535
+    t.text     "refresh_token", limit: 65535
```

I've got a fairly modern version of MySQL running:
```
$ mysql --version
mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3
```
I suspect that the initializer `ar_mysql_column_charset.rb` isn't running during the migration so the generated `schema.rb` doesn't include the complete set of attributes. I don't feel like I have a good grasp of how it's supposed to work because it looks like there's a number of conditions that must be met. Wondering if I'm just missing something in my ENV.

**Comment by TildeWill** [comment]
Looks like `ActiveSupport.on_load :active_record do` in `ar_mysql_column_charset.rb` is being loaded too late in the life-cycle - that Rails/rake loading of `config/initializers` happens **after** ActiveSupport has loaded :disappointed: Not sure what to do about it because I'm hoping this works for other people.

**Comment by TildeWill** [comment]
Placing `require File.expand_path('../config/initializers/ar_mysql_column_charset', __FILE__)` at the top of the `Rakefile` does resolve the problem. Below is a passing* spec I wrote (needs MySQL to be the backing DB)

```ruby
require_relative '../../lib/ar_mysql_column_charset'
require 'rails_helper'
    
describe "monkey patches to ActiveRecord for MySQL charsets" do
  it "does the thing" do
    schema = dump_table_schema('users')
    expect(schema).to include('charset: "utf8mb4"')
    expect(schema).to include('limit: 1')
    expect(schema).to include('collation: "utf8_bin"')
  end
  
  def dump_table_schema(table, connection = ActiveRecord::Base.connection)
    old_ignore_tables = ActiveRecord::SchemaDumper.ignore_tables
    ActiveRecord::SchemaDumper.ignore_tables = connection.tables - [table]
    stream = StringIO.new
    ActiveRecord::SchemaDumper.dump(ActiveRecord::Base.connection, stream)
    stream.string
  ensure
    ActiveRecord::SchemaDumper.ignore_tables = old_ignore_tables
  end
end
```
*I'd like to be able to remove the first line and still have the spec pass

**Comment by dsander** [comment]
I wouldn't worry about the `db/schema.rb` too much, not sure if I am missing something but we don't use it at all. In all our guides/specs/docker container we use `db:migrate` and not `schema:load`. In my experience it is nearly impossible to have the schema.rb consistent for everyone. How the schema.rb looks depends on the database (postgresql or mysql) and even the version.

How I normally handle it is to commit the changes whenever I created a migration and just ignore the changes when I just ran the migrations.

**Comment by TildeWill** [comment]
Are those files offering any value then? Should they be removed?

**Comment by dsander** [comment]
The only benefit I know is that you can skip the migrations when you set up a new database an run `rake db:schema:load` to bring the database to the current state. Since migrating an empty is really fast I do not use that feature very much.
The noise the schema generates in commits is a bit annoying, but I would still keep it under version control.

**Comment by TildeWill** [comment]
Sorry, I was referring to `lib/ar_mysql_column_charset.rb`, `lib/ar_mysql_column_charset/main.rb`, `lib/tasks/ar_mysql_column_charset.rb`. The callback on line 3 of `lib/ar_mysql_column_charset.rb`, `ActiveSupport.on_load :active_record do` never gets fired because the file loads after ActiveRecord has loaded both in the case of the initializer and the rake task. 

Removing line 3, and the corresponding `end` seem to have the desired effect of loading the extension at the right time. I feel like either line 3 should be removed so that the files do something, or the whole set of files should be deleted from the project to avoid confusion. Thoughts? I'm happy to submit the pull request either way.

**Comment by dsander** [comment]
I think the files should be loaded, as far as I know they are supposed make mysql handle utf8 characters properly. @knu should know more about it.

Removing line 3 did not work for me, when I add `require File.expand_path('../../lib/ar_mysql_column_charset', __FILE__)` after `Bundler.require` in `config/application.rb` the callback is properly registered and called.

**Comment by cantino** [comment]
Those are indeed for MySQL extended utf8 support.

Should we add schema.rb to .gitignore?

**Comment by TildeWill** [comment]
I think excluding it from git makes a lot of sense. Multiple databases with differing schemas, this would convey that we don't expect the schema.rb to be a source of truth.

**Comment by TildeWill** [comment]
Submitted pull request (sorry for the commit spam) to remove schema.rb from git

**Comment by dsander** [comment]
I guess removing the `schema.rb` would not hurt. 

@TildeWill does the issue that the patches for MySQL are not loaded still exist?

**Comment by TildeWill** [comment]
*shrug* I guess the issue still exists. But I'm not sure it ever worked in the first place because so far I'm hearing that schema.rb doesn't matter. I don't know what test to write to know it's loaded correctly. Maybe in older versions of Rails the load order was different enough? I guess I'd need @knu to do a brain dump about the expectations of that code.

**Comment by cantino** [comment]
I believe it's for https://github.com/cantino/huginn/blob/master/db/migrate/20140813110107_set_charset_for_mysql.rb

**Comment by TildeWill** [comment]
Let's talk about what is supposed to happen here. In my reading through the wiki/issues/code history on Github, here's what I've garnered:
* Multiple databases are supported, namely MySQL and Postgres
* MySQL's utf8 encoding is not sufficient for supporting emoji which is important for things like Twitter integration
* In order to coax MySQL into a happy emoji state, additional `charset` and `collation` attributes need to be set on a specific set of text and string fields, but probably isn't needed for all text and string fields. This was handled in the migration  [20140813110107_set_charset_for_mysql.rb](https://github.com/cantino/huginn/blob/master/db/migrate/20140813110107_set_charset_for_mysql.rb) which needs the extension to ActiveRecord in order to set the charset and collation.
* `schema.rb` is not used by the app nor the setup instructions. Therefore it can be removed from the project since Postgres and MySQL will always generate different output when dumping the schema.

Does this sound right? Anything I've missed or got wrong?

**Comment by cantino** [comment]
@knu, would you mind checking if our understanding is correct?

**Comment by knu** [comment]
I don't think the diff is due to the callbacks not getting loaded.  I guess it is an accumulated set of changes by various contributors and committers.  I've always seen differences like you but just decided to pick relevant hunks when I commit, and ignored those differences.

**Comment by knu** [comment]
And yes, I think every point @TildeWill made is correct.

**Comment by cantino** [comment]
I think this is closable now that we merged in the `schema.rb` removal, right @TildeWill?

**Comment by TildeWill** [comment]
Correct, close away.

**Comment by cantino** [comment]
Thanks Will!
