### ISSUE TITLE
Namespace prefix media on content is not defined. 

### ISSUE THREAD

**Issue by eugenesvk** [cantino/huginn#1197]
I have a similar issue (https://github.com/cantino/huginn/issues/960) with **iTunes** style namespaces (e.g. `itunes:summary`).
I've tried adding `xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"` and created a PR for that (https://github.com/cantino/huginn/pull/1196), but your test routines all failed. Don't really understand what happened, so would you kindly check it out?

I've tried it on my **herokuapp** and it seems to be working, now I don't get error messages when I try to open the RSS XML output of the data output agent and instead have `<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0">` displayed as in a proper .
Or should it be a stub declaration like `xmlns:itunes="http://search.yahoo.com/mrss/"` instead of the real one?

**Comment by cantino** [comment]
Your PR looks good, I think.  We left a few comments on it.

**Comment by cantino** [comment]
Merged!
