### ISSUE TITLE
Browser Automation Sample

### ISSUE THREAD

**Issue by gdomod** [cantino/huginn#1199]
Hi there,

is there an solution for browser automation. i want to login in a bboard an parse some posts.
maybe with javascript agent, but can anybody give me a sample for js browser automation.

big thx

**Comment by dsander** [comment]
Hi,

browser automation is not possible at the moment, but if you have the session cookie you can use the `headers` option field of the `WebsiteAgent` to make authenticated requests to the site. It might also be possible to first make a POST request to the login and then grab the authentication headers from the generated event.

**Comment by signallhill** [comment]
@dsander how is this done.
"It might also be possible to first make a POST request to the login and then grab the authentication headers from the generated event."

**Comment by dsander** [comment]
Sorry I was mistaken, I thought this would be possible but the `PostAgent` does not propagate the data it received and the `WebsiteAgent` can not send POST requests.

**Comment by cantino** [comment]
At some point, I do think it would make sense for the WebsiteAgent to be able to POST, and for the PostAgent to emit any received data.

**Comment by virtadpt** [comment]
Playing around with both of them a little, I'm inclined to concur.  Being able to capture and propagate headers from PostAgent would be ideal for logging into a web service and capturing the authentication cookie.

**Comment by dsander** [comment]
Hm, not sure if we shouldn't merge both agents, it would be ideal to be able to do any kind of request (GET/POST/PATCH like in the PostAgent), set the expected response type (what the WebsiteAgent does) and optionally set encoding of the data (PostAgent does this) as well as emit/process the received data (WebsiteAgent again)

**Comment by cantino** [comment]
I agree.  I'll look into combining these.

**Comment by cantino** [comment]
Now that the PostAgent emits events parseable by the WebsiteAgent, I think this can be closed.  Please re-open to discuss further!
