### ISSUE TITLE
docker import export to other host - data lost

### ISSUE THREAD

**Issue by gdomod** [cantino/huginn#1200]
hi,

i try to export and import my docker container to other host. but the data are lost.
i also try to commit and save , than load the image. but no success.

can anybody explain me what i do wrong ?

**Comment by dsander** [comment]
Thats strange, I tried it myself and for some reason the when I `commit` the changes of the container to a new image the mysql database changes are not saved, the same happens when I use a linked mysql container. What should work is to either pass the huginn or the linked mysql container a volume and then move the volume data to the second server.

**Comment by gdomod** [comment]
i think the init script seed the database again. but i dont understand why.

**Comment by dsander** [comment]
It does recreate the database because the old one is not present when importing the container even though `commit` is supposed to store the changes.
On the other hand using a volume is the better solution anyways, because it allows you to update the container without losing the data.

**Comment by gdomod** [comment]
sounds good. can you send me the cmd line, doestn know the path that i linked to independently volume.

**Comment by dsander** [comment]
`docker run -it --name huginn-test -p 3000:3000 -v /local/path/to/the/data:/var/lib/mysql cantino/huginn` should do the trick, the same `-v` argument can be used when you start the separate mysql container. Keep in mind this will now work when using [boot2docker](https://github.com/docker-library/mysql/issues/44#issuecomment-73318805)

**Comment by cantino** [comment]
Did that work for you @gdomod?

**Comment by gdomod** [comment]
works thanks

**Comment by cantino** [comment]
Great!
