### ISSUE TITLE
Huginn failing with error "Asset was not declared to be precompiled in production"

### ISSUE THREAD

**Issue by Androoz** [cantino/huginn#1201]
Hi there!

I'm new to Huginn and Ruby, and trying to get it everything up and running. But almost at the finish line, I've run into a problem when trying to edit and/or add an agent. I immediately get a Rails error stating:

```
Sprockets::Rails::Helper::AssetNotPrecompiled in Agents#new
Showing /Users/MiniMe/Desktop/huginn/app/views/agents/_form.html.erb where line #1 raised:

Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( ace.js )` to `config/initializers/assets.rb` and restart your server

...
```
See also attached screen grab. 

I can't find any `config/initializers/assets.rb`and what I can see is `config.assets.precompile += %w( ace.js )`already stated in `config/environments/production.rb` together with the rest of javascripts?

I have precompiled the assets manually by running `RAILS_ENV=production bundle exec rake assets:precompile` with success but I still get the same error when running Huginn...

Can somebody please give me some ideas :) because I'm totally stuck... 

Regards,
Anders

![skarmavbild 2015-12-30 kl 21 46 54](https://cloud.githubusercontent.com/assets/16493514/12057387/db285b06-af40-11e5-9fdb-66a8d861679a.png)

**Comment by Androoz** [comment]
Hi again!

I solved it myself, and in retrospect I had the solution already as stated in the error message:
```
Add `Rails.application.config.assets.precompile += %w( ace.js )` to `config/initializers/assets.rb`
```
But `config/initializers/assets.rb` did not exist, so I had to create it and then add the following strings:
```
Rails.application.config.assets.precompile += %w( ace.js )
Rails.application.config.assets.precompile += %w( diagram.js )
Rails.application.config.assets.precompile += %w( graphing.js )
Rails.application.config.assets.precompile += %w( map_marker.js )
```
But I still don't understand why I needed to create assets.rb and add these strings? I couldn't find this in any documentation or tutorials, so why did I need to add this for my installation?

Thanks in advance :)

Regards,
Anders

**Comment by dsander** [comment]
Hi @Androoz,

the initializer should not be needed, additional static files are configured in [config/environments/production.rb](https://github.com/cantino/huginn/blob/master/config/environments/production.rb#L66), did you set the `RAILS_ENV` in your `.env` file?

**Comment by Androoz** [comment]
`RAILS_ENV` is commented out and not defined in my `.env` file. I defined it as "production" the other day and got the error to disappear but I reverted back because the stylesheets was not loading correctly. Should I define again and try to re-run `bundle exec rake assets:precompile`?

I'm also little confused about the difference between "production" and "development" deployments?

**Comment by dsander** [comment]
Yes, when you want to precompile the assets and run in the production environment `RAILS_ENV=production` should be enabled.

The environments change the way rails behaves, `development` is for development where you want to change the code and instantly see the changes, it includes code reloading and on the fly asset compilation. (make sure to delete the `public/assets` directory if you switch from production to development)
`production` is for deployments on servers, precompiling assets and caching classes (the code) improves the performance put also does not allow to apply changes without restarting the server and precompiling the assets again.

**Comment by Androoz** [comment]
Thanks @dsander! I will give `RAILS_ENV=production` another chance then :)

**Comment by cantino** [comment]
Did that work for you @Androoz?

**Comment by Androoz** [comment]
Sorry for late reply @cantino and @dsander. 

It did worked sort of, but I yet again got the CSS problem where the stylesheets won't load correctly. So I reverted back to my previous solution using a `config/initializers/assets.rb` file. After that I got Huginn to work and I haven't looked further into it.

**Comment by cantino** [comment]
Thanks for letting us know!  Please re-open if you have any issues.
