### ISSUE TITLE
Regex not working properly with colon (:) in trigger event

### ISSUE THREAD

**Issue by eugenesvk** [cantino/huginn#1202]
I have the following chain of agents to get only selected programs in a podcast:
RSS input (website agent) -> __Filter (trigger agent)__ -> RSS output (data output agent)

The filter removes some of the input by excluding `title` that has user-defined program names via `!regex`. However, it fails to filter out titles with colons `:`, for example __ProgramA : HostA__. For some reason I can filter out __HostA__, but cannot filter out __ProgramA__ or __ProgramA :__

So, this code doesn't work (`|` is a vertical bar)
`"type": "!regex",`
`      "value": ".*sometitle|ProgramA|ProgramA :|sometitle.*",`
`      "path": "title"`

But this one works (with __HostA__ following colon `:`, instead of __ProgramA__, preceding colon)
`"type": "!regex",`
`      "value": ".*sometitle|HostA|sometitle.*",`
`      "path": "title"`
 
From what I understand about Regex (and I used some online tools to check syntax), colon (`:`) is not special in any way and should be parsed as any other symbol.

Would you have any idea why the colon `:` breaks my filter? Is there some special escape thing I can use?
Thank you!

**Comment by cantino** [comment]
Hey @eugenesvk,

Could you give me an example of a full `title` that you'd like to return and another full `title` that you'd like to avoid?

**Comment by eugenesvk** [comment]
Full title I'd like to __avoid__ "News on TV : Host name". Host name can be different depending on a host, that's why I want to filter out "News on TV" regardless of who is hosting it, but now I have to filter out all the host names.
Full title I'd like to __keep__ "Soundtrack" or "Alone : Host name" (again, host names can be different)

**Comment by cantino** [comment]
I'd think that this would work.

```
"type": "!regex",
"value": "News on TV",
"path": "title"
```

**Comment by eugenesvk** [comment]
@cantino Unfortunately, it doesn't work - I've changed my filter and re-emitted the "News on TV : Host name" event again, it got through.
However, the weirdest part is that `news on` works as a filter! `news on TV` doesn't work, `news on TV :` doesn't work, `on TV` doesn't work. It's still suboptimal since there might be a program "News on something else" which I would miss with this filter, but it's an improvement over the current filter by host name since same host is more likely to be on a different program rather than a different program starting with "News on".
It's a very weird bug.

**Comment by cantino** [comment]
Maybe there's a non-breaking space instead of a normal space in this text?  Try `"News\\w+on\\w+TV"` perhaps?

**Comment by eugenesvk** [comment]
Ah, a very smart idea! That was it. The second space was causing the issue (although I've used capital `\\W` instead since capital `W` is any non-word character (lower-case `\\w` stands for any word character, so wasn't working).
Stupid podcast owners for passing stupid special characters instead of regular spaces and wasting our time.
Will use this trick for all future characters that resemble spaces :)
Thanks!

**Comment by cantino** [comment]
Glad it worked!
