### ISSUE TITLE
Should we unify the WebsiteAgent and PostAgent?

### ISSUE THREAD

**Issue by cantino** [cantino/huginn#1206]
There have been a couple of discussions and PRs about unifying the PostAgent and the WebsiteAgent (see discussion with @virtadpt and @dsander in #1199 and @Ishfal's #997, at least).  Basically, it's annoying that the PostAgent doesn't emit returned data as an Event, and it's annoying that the WebsiteAgent doesn't allow selection of a HTTP verb or POSTing of event data.

One solution is to do nothing: now that the WebsiteAgent has `data_from_event`, we could just recommend chaining PostAgent -> WebsiteAgent, letting the PostAgent own outbound communication and the WebsiteAgent own parsing.

Alternatively, we could add `method` (`get`, `put`, `post`, etc.), `outbound_content_type` (`json`, `xml`, `application/x-www-form-urlencoded`), and `outbound_content` (either a Liquid value to a hash in the incoming Event, or a hash of Liquid values) to the WebsiteAgent.  At this point, the PostAgent would be redundant, but perhaps worth keeping for it's simplicity.  It might be worth giving it the option to emit returned data too, for completeness.

Thoughts?

**Comment by dsander** [comment]
> One solution is to do nothing

I don't follow, how would we get the response data from the PostAgent to the WebsiteAgent without any changes?

If the PostAgent would emit the recieved data, would we also have access to the response status and the headers?

> PostAgent own outbound communication and the WebsiteAgent own parsing.

I like that idea, we could push that even further by renaming the PostAgent to RequestAgent and the WebsiteAgent to something like DataProcessingAgent which would allow us to clean up the responsibilities even more, but I am not sure if that would be possible without breaking existing installations.

Adding the ability to `POST`, `PUT`, etc to the WebsiteAgent sounds like the easiest solution but also would make the WebsiteAgent more complicated, it's already one of the most complicated agents we have.

**Comment by cantino** [comment]
Oops, you're right.  We'd need to at least allow the PostAgent to emit it's received data.

**Comment by flechaig** [comment]
I agree, the first thing is to allow PostAgent to emit data it received.

**Comment by cantino** [comment]
@flechaig, the PostAgent can emit Events now.
