### ISSUE TITLE
Website Agent : data_from_event not working when url_from_event present

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1207]
Im getting following error in website agent "No data was found in the Event payload using the template {{searchResults}}". If I put url instead of url_from_event it works fine.

Scenario: I have a website agent that gets url from event. The url from event gives out following data

   ``"total":2,
   "pageCount":1,
   "count":30,
   "searchResults":"<div class='data-content'>
   <h3>
   <a title=\"Title 1" id=\"position0\" href=https://www.xyz.com/title1>title1<span class='status-indicator icon-preview-1 visited'><\/span><span class='status-indicator icon-star-1 saveaction' isSaved='false' id=\"158beaef777\"><\/span><\/a><\/h3>
   <div class='shortdesc'>short description<\/div><ul class='list-inline'><li>location1<\/li><li>date1<\/li><li class='easy'>Submit<\/li><\/ul'><\/div>
  <div class='data-content'>
  <h3>
  <a title=\"Title " id=\"position1\" href=https://www.xyz.com/title2>title2<span class='status-indicator icon-preview-1 visited'><\/span><span class='status-indicator icon-star-1 saveaction' isSaved='false' id=\"s514ce9e0ba4f\"><\/span><\/a><\/h3>
  <div class='shortdesc'>short description<\/div><ul class='list-inline'><li>location2<\/li><li>date2<\/li><li class='easy'>Submit<\/li><\/ul'><\/div>",
   "page":2``

Here is the website agent code
{
  "expected_update_period_in_days": "30",
  "url_from_event": [
    "{{url}}"
    ],
  "type": "json",
  "mode": "on_change",
  "extract": {
    "title": {
      "path": "data-content.h[3].a.title"
    },
    "description": {
      "path": "data-content.h[3].shortdesc",
"url":{
      "path":"data-content.h[3].position.a.href"
    }
  },
  "headers": {
    "Cookie": "something"
},
  "data_from_event": "{{searchResults}}"
}

**Comment by dsander** [comment]
You are right, `url_from_event` and `data_from_event` [are exclusive](https://github.com/cantino/huginn/blob/master/app/models/agents/website_agent.rb#L334-L343) you can either use the data send to the WebsiteAgent or fetch a URL.

**Comment by signallhill** [comment]
Is #1205 related to this?

**Comment by cantino** [comment]
@signallhill, could you branch the event flow and use one Agent fetching with url_from_event to emit data, then a second using data_from_event to parse it?

**Comment by signallhill** [comment]
I apologize I was not aware data_from_event could be used exclusively to replace both the url option. I will use that. Thanks

**Comment by signallhill** [comment]
Works perfectly. Quadrupled the events huginn is processing.

**Comment by cantino** [comment]
Nice!
