### ISSUE TITLE
Looking for a Teacher / Trainer

### ISSUE THREAD

**Issue by ppalme** [cantino/huginn#1210]
Hi,
I have been working for a while with Huginn but now I am trying something complex with RSS.
So far I wasn't successful and now I have little time to experiment further.
Please let me know your rate and as well it would be good to see your example project with Huginn and RSS. Thank you.
Best regards,
Peter

**Comment by cantino** [comment]
Hey @ppalme, I've created a "contractor wanted" label for this.  I hope you can find someone to help!  If you have general questions, people are usually willing to answer them here as well.

**Comment by midwire** [comment]
Hey there @ppalme. I would be happy to dig into a specific question. If you are wanting one-on-one personal help I may be able to find some time. I'd rather not disclose rates and such here but feel free to send me an email at: c7bba866@opayq.com.

**Comment by ppalme** [comment]
Hi Andrew, thanks again for your help. Much appreciated. Best regards, Peter

On 8 January 2016 at 21:10, Andrew Cantino <notifications@github.com> wrote:

> Hey @ppalme <https://github.com/ppalme>, I've created a "contractor
> wanted" label for this. I hope you can find someone to help! If you have
> general questions, people are usually willing to answer them here as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cantino/huginn/issues/1210#issuecomment-170110476>.
>



-- 
Linkedin Profile: www.linkedin.com/in/peterpalme
Blog: http://ppalme.wordpress.com
