### ISSUE TITLE
User inputs

### ISSUE THREAD

**Issue by DreamFlasher** [cantino/huginn#1211]
I'm trying to migrate from Yahoo Pipes and would like to model the following: I want to stay up to date for some ebay searches. With Pipes I was able to construct a URL from user inputs (baseurl + string concatenation) and then retrieve the RSS feed at that URL. The advantage of this was that I could create another pipe that had several of these modules where I only needed to enter the search string/price etc. so I could easily modify what I was tracking. How would I model this in Huginn? Is there any way to call the RSS Agent and specify the URL param?

**Comment by cantino** [comment]
Hey @DreamFlasher.  Scenarios are sort of for this, but they're not variablized yet, so you can't really copy them for different cases.  You might be able to achieve some of this with either a JavaScriptAgent or creative use of Liquid formatting.

**Comment by DreamFlasher** [comment]
With Liquid Formatting you mean {{...}} markup? It would be cool if the RssAgent would support that. My current solution is a combination of Manual Agent: (new event with URL or parameters of URL) and 
Website Agent.

**Comment by cantino** [comment]
Yes, the `{{` syntax.  It looks like the `url` option of a RSSAgent should allow it, but since RSSAgents cannot receive Events right now, you're correct that there's no way to wire it.  Allowing them to receive Events, or switching to using a WebsiteAgent to parse the RSS, would be possible.

**Comment by DreamFlasher** [comment]
Yes, I am doing it with the WebsiteAgent succesfully, but I would prefer the RSS agent -- may I request as a feature that the RSS Agent can receive events? :)

**Comment by cantino** [comment]
It would be reasonable to add, yes.  Would you be interested in trying to make that change?

**Comment by DreamFlasher** [comment]
Oh yeah, why not! Can you give me some pointers where I can start?

**Comment by cantino** [comment]
Great! Do you have Huginn running locally on your computer?  If so, you'll just need to edit the rss_agent.rb and rss_agent_spec.rb files (in the app/models/agents and spec/models/agents directories).   If you don't have Huginn running locally, that'd be the first step.  See https://github.com/cantino/huginn#local-installation

**Comment by cantino** [comment]
Did that work @DreamFlasher?

**Comment by DreamFlasher** [comment]
@cantino Thank you for checking back. I had a look into the code but was demotivated by the complexity. I don't have any Ruby background and the templating/coding looked so complex that I deprioritized working on it. 
So no, unfortunately I won't work on that in the near future :(

**Comment by cantino** [comment]
Please re-open if you'd like to discuss further.
