### ISSUE TITLE
Extracting non-standard fields from RSS

### ISSUE THREAD

**Issue by wtluke** [cantino/huginn#1212]
Hi,

A few RSS feeds I'm working with have non-standard fields beneath <item>, e.g.:

`<dc.creator>`
`<enclosure url="http://uri.com">`

I'd like to parse these to a dataoutput agent but can't seem to grab them. I did try using a WebSite Agent and xpath, but it's beyond my capabilities! Is the RSS feed parser capable of this, or not?

Thanks

**Comment by cantino** [comment]
I think you'd want a WebsiteAgent with XPath or CSS.  You may need to change use_namespaces too, although I'd think the CSS "creator" or "enclosure" would work.

**Comment by cantino** [comment]
Did this work for you @wtluke?
