### ISSUE TITLE
Email Agent, awaiting retry -> recent failure

### ISSUE THREAD

**Issue by DreamFlasher** [cantino/huginn#1214]
I have an Rss Agent which succesfully creates events. I receive them with an Email Agent which also succesfully receives them ("Last event in"). Yet, I do not receive any emails, moreover all events related to this end in awaiting retry -> recent failure. I am running on Heroku.

**Comment by cantino** [comment]
Hey @DreamFlasher. Are any errors displayed in the email agent's log, or in the jobs list?

**Comment by DreamFlasher** [comment]
Unfortunately not @cantino. No errors on either. I am using the SMTP settings for gmail as specified in "Using your own mail server".

**Comment by cantino** [comment]
Where are you seeing "awaiting retry -> recent failure"?  Could you attach a screenshot?

**Comment by DreamFlasher** [comment]
Happy to do so:
![image](https://cloud.githubusercontent.com/assets/31695/12353964/e0800708-bb92-11e5-956a-70083a75e358.png)

The button right of it has the hint "17 jobs recent failures", unfortunately nothing happens when I click on the buttons.

**Comment by DreamFlasher** [comment]
Happy to do so:
![image](https://cloud.githubusercontent.com/assets/31695/12354001/27d25b10-bb93-11e5-94e3-c12708386e5c.png)
The button right of it has the hint "17 jobs recent failures", unfortunately nothing happens when I click on the buttons.

**Comment by DreamFlasher** [comment]
Happy to do so:

![image](https://cloud.githubusercontent.com/assets/31695/12354024/4e2ef070-bb93-11e5-8ce2-90af5800da09.png)

The button right of it has the hint "17 jobs recent failures", unfortunately nothing happens when I click on the buttons.

**Comment by cantino** [comment]
Clicking either of those should take you to /jobs.  It doesn't navigate you?  What happens if you go to /jobs directly?

**Comment by DreamFlasher** [comment]
Unfortunately, not! Neither on Ubuntu nor Windows, with non of Firefox/Chrome/Opera it navigates me to /jobs. When going to /jobs directly I get forwarded to the starting page. ("Welcome to Huginn!")

**Comment by cantino** [comment]
Interesting!  I think that means that you're not running as an admin user on Huginn.  Are you in a multi-user setup?  If not, how / where are you running it?

**Comment by DreamFlasher** [comment]
Ha, interesting, indeed! Didn't know that I wasn't an admin. I deployed it to Heroku, opened the app (huginn) page and it told me in order to register I need an invite code -- which I got from the config vars :D 
I managed to setup huginn with heroku toolbelt (not possible on Windows unfortunately), created an admin account with the same username and email as the user I created before -- and luckily I still have all my agents, plus admin rights.
With the error messages in /jobs I was able to set up SMTP succesfully (in gmail you need to deactivate secure login in the gmail settings).
Solved, thank you!

**Comment by cantino** [comment]
Great!
