### ISSUE TITLE
read and process response with postAgent

### ISSUE THREAD

**Issue by jamsheer-citrus** [cantino/huginn#1218]
Apart of my project requirement i need to read and process response with postAgent, how to do it ?
My use case as follows ,
I have a micro service which returns mail contents or SMS contents based on body parameters of a post REST call.I need to call this service from huginn and send its response as a mail by using mailAgent.How to do it ,Thanks in advance.

**Comment by cantino** [comment]
Hey @jamsheer-citrus.  That's not possible yet, but is likely coming soon.  See #1206.

**Comment by cantino** [comment]
This should be possible now! Please re-open to discuss further.
