### ISSUE TITLE
huginn on digitalocean coreOS

### ISSUE THREAD

**Issue by wasafiri** [cantino/huginn#1219]
on the digitalocean coreOS stable version (835.9.0) which is the lightest weight OS option digitalocean offers and comes with docker already set up:

after running `docker run -it -p 3000:3000 cantino/huginn`:

result:
`Bundled gems are installed into ./vendor/bundle.
2016-01-13 17:19:02,051 CRIT Set uid to user 0
2016-01-13 17:19:02,052 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2016-01-13 17:19:02,052 WARN Included extra file "/etc/supervisor/conf.d/bootstrap.conf" during parsing
2016-01-13 17:19:02,052 WARN Included extra file "/etc/supervisor/conf.d/foreman.conf" during parsing
2016-01-13 17:19:02,081 INFO RPC interface 'supervisor' initialized
2016-01-13 17:19:02,082 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-01-13 17:19:02,082 INFO supervisord started with pid 1
2016-01-13 17:19:03,086 INFO spawned: 'stdout' with pid 690
2016-01-13 17:19:03,092 INFO spawned: 'bootstrap' with pid 691
2016-01-13 17:19:03,119 INFO success: bootstrap entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2016-01-13 17:19:03,347 INFO exited: bootstrap (exit status 2; not expected)
2016-01-13 17:19:04,350 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bootstrap stdout | DATABASE_HOST=
bootstrap stdout | error: <class 'socket.error'>, [Errno 111] Connection refused: file: /usr/lib/python2.7/socket.py line: 224`

**Comment by wasafiri** [comment]
FWIW, same result with CoreOS 877.1.0 (beta)

**Comment by cantino** [comment]
@dsander, does your Docker upgrade fix this?

**Comment by dsander** [comment]
@cantino This looks like an issue with supervisord, so I guess the `dsander/huginn-single-process` image would work.

@wasafiri Do you have experience with coreOS? I am a bit confused because the same image id works perfectly fine on boot2docker and ubuntu. Does coreOS do anything special/different then "normal" distributions?

**Comment by wasafiri** [comment]
@dsander I haven't any experience with CoreOS, trying it because with Debian on DigitalOcean Huginn maxes out memory on a 512mb droplet almost right away. CoreOS, which is more lightweight, seems like a good candidate for getting Huginn running on a 512mb droplet. 

Gave the `dsander/huginn-single-process` image a try, I get this error with coreOS:

`Bundled gems are installed into ./vendor/bundle.
 #<Mysql2::Error: Can't connect to MySQL server on 'your-domain-here.com' (4)>
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8mb4", "reconnect"=>true, "database"=>"huginn_development", "pool"=>10, "username"=>"root", "password"=>"password", "host"=>"your-domain-here.com", "port"=>3306, "socket"=>"/tmp/mysql.sock", "strict"=>false}, {:charset=>"utf8mb4"}
(If you set the charset manually, make sure you have a matching collation)`

**Comment by dsander** [comment]
@wasafiri That is true, the 512mb RAM will be tight fit for Huginn, but it should work as long as you don't have too many agents.

The `huginn-single-process` image does not include mysql. Check out the [manual startup and linking](https://github.com/dsander/huginn/tree/docker/docker/single-process#usage) example, keep in mind the containers will not be deamonized, but you can add the `-d` flag to the docker run command (make sure to put it before the image name).
I would recommend docker-compose, but it looks like it's not installed on coreOS per default.

**Comment by wasafiri** [comment]
@dsander Unfortunately with 512mb it doesn't work at all -- it runs out of memory literally as the install process finishes, before any agents are set. 

I'll keep trying with huginn-single-process and will see if I can get docker-compose running on coreOS.

**Comment by wasafiri** [comment]
I was able to get docker-compose installed on coreOS but docker-compose up resulted in MySQL failing to initialize due to lack of memory. So, it seems 512mb doesn't work with coreOS, either.

For what it's worth, the only hurdle I had was needing to modify the docker-compose.yml as it seems dashes and underscores are disliked:

`Invalid service name "huginn_web" - only [a-zA-Z0-9] are allowed`

Modifying `huginn_web` and `huginn_threaded` to `huginnweb` and `huginnthreaded` got me past that error.

**Comment by dsander** [comment]
> Invalid service name "huginn_web" - only [a-zA-Z0-9] are allowed

Are you running docker-compose < 1.4? With 1.4 compose should support the underscore.

It did some local tests and the mysql container allocates a lot of memory by default:

```
CONTAINER                         CPU %               MEM USAGE / LIMIT  
singleprocess_huginn_threaded_1   0.13%               159.9 MB / 4.143 GB
singleprocess_huginn_web_1        0.00%               227.8 MB / 4.143 GB
singleprocess_mysql_1             0.06%               218 MB / 4.143 GB  
```

So it might be possible to run on coreOS when you restrict/tweak the memory usage for mysql but I don't think it will be fun, especially because huginn will need more RAM when you run a few agents.

**Comment by wasafiri** [comment]
@dsander i installed docker-compose 1.5.2.

Thanks for looking into memory usage -- seems 1GB is the practical minimum for me, as I have ~40 agents.
