### ISSUE TITLE
how to set recipient id to mail agent dynamically ?

### ISSUE THREAD

**Issue by muneesmajid** [cantino/huginn#1225]
I need to send a notification mail to different users  based on events ,Any possibility with huginn to do it .

**Comment by cantino** [comment]
Hey @muneesmajid, with PR #1227 that I just made, `recipients` option should allow Liquid formatting, so you could set it to `{{ email }}` (for example) to send email to the address in the incoming Event's `email` key.

**Comment by cantino** [comment]
Does that solve your question?

**Comment by jamsheer-citrus** [comment]
Tried same ,but not worked to me

**Comment by jamsheer-citrus** [comment]
Sorry ,it was due to my mistake ,my request body has unwanted spaces .Working fine now and thank you for this great job.

**Comment by cantino** [comment]
Great!

**Comment by jamsheer-citrus** [comment]
Is this feature available with  Email Digest Agent  ?

**Comment by cantino** [comment]
Yes, I believe so.

**Comment by jamsheer-thottathil** [comment]
ok fine ,Thank you @cantino
