### ISSUE TITLE
Google Calendar Publish Agent can 'stutter' on a perceived error and duplicate calendar entries

### ISSUE THREAD

**Issue by ohingardail** [cantino/huginn#1226]
The Google Calendar Publish Agent sometimes inserts calendar items correctly, but returns an error, resulting in multiple retries and multiple instances of the same event in the calendar.

For reasons I have yet to get to the bottom of, the Google Calendar Publish Agent randomly returns errors such as :

```
Exception during receive. getaddrinfo: Name or service not known: /usr/local/lib/ruby/2.2.0/net/http.rb:879:in `initialize'...
```
I assume this is some kind of transient internet error (I think getaddrinfo is a DNS problem) which might be at my end, or with my ISP.

And :

```
Exception during receive. execution expired (Delayed::Worker.max_run_time is only 600 seconds): /usr/local/lib/ruby/2.2.0/net/http.rb:879:in `initialize'...
```

I'm not sure what's causing this; as you can see I've increased DELAYED_JOB_MAX_RUNTIME to 600 secs. I'm also running 4 delayed job workers (increased from the default as an experiment to see if I can reduce instances of the problem) and I'm running on a 4Gb Ubuntu VM on a Fedora host. It could be that my Huginn set up is just not properly configured for the system I'm using.

However, weird transient issues are likely to happen when dealing with the internet (and most of the time the Google Calendar Publish Agent works just fine), so my real issue is how to make the Google Calendar Publish Agent 'sensible' to the fact that even though it perceives an error, the required task was actually done, or just not to try again even if it cannot perceive success.

I can desensitize my entire Huginn setup (I think - I'm only guessing really) by setting Delayed::Worker.max_attempts = 1 in config/initializers/delayed_job.rb, but this affects other agents which I don't mind retrying on failure. I can increase DELAYED_JOB_MAX_RUNTIME ever upwards, but I'm not sure if this would help (perhaps the unwanted retry would just happen later?).

One possibility might be to introduce an per-agent parameter, effectively saying that for *this* agent Delayed::Worker.max_attempts = 1, although the default would remain the same for other agents.

**Comment by cantino** [comment]
Hey @ohingardail.  These both seem likely to be networking issues.  I don't know the GoogleCalendarAgent well at all.  Perhaps @CloCkWeRX has some suggestions?  You could certainly add a `begin` ... `rescue` around line 97 of the agent to ignore errors, but sometimes you might want retries?

**Comment by ohingardail** [comment]
Thankyou @cantino . I look forward to a response; the unpredictable behaviour of the GoogleCalendarAgent is a bit of a nuisance. If you'd like, I can add a paragraph to the 'Companies and People Using Huginn' page as a sort of thanks for Huginn and all the effort you and your colleagues put into it.

**Comment by dsander** [comment]
@ohingardail The duplicated calendar events can happen when the agent processes multiple incoming events at once. If the first succeeds and the second fails the retried job will probably re-create the first event. Is that something that could happen in your setup?

You might be able to avoid this by setting the "Propagate immediately" option for the source agent of your google calendar publish agent.

**Comment by ohingardail** [comment]
Yes, that could happen on my setup. I'll set the source agents to "propogate immediately" and see if that helps. Thanks.

**Comment by ohingardail** [comment]
The proposed solution seems to address the problem; I still get the odd "getaddrinfo" error, but no duplicates. About 1% of events went missing somewhere but I am still investigating whether this is related to the Google Calendar Agent or not.

**Comment by cantino** [comment]
Maybe we should add a note in the `description` of this Agent recommending propagate immediately?

**Comment by dsander** [comment]
That might be an option, we could also change the way events are propagated for certain agents. We have some that benefit from bulk processing events at once (especially the ones that do not connect to external services), and some that should just process on event per job to avoid duplication caused by failed jobs. I am thinking about a `no_bulk_processing!` option for agents.

**Comment by cantino** [comment]
I think that makes sense.  I've thought about making everything propagate immediately, but have been concerned about what would happen if someone makes a loop of Agents.

**Comment by dsander** [comment]
Ok, I will work on that.
