### ISSUE TITLE
[Suggestion] allow Manual Event Generator to emit a stream of events

### ISSUE THREAD

**Issue by ohingardail** [cantino/huginn#1228]
As far as I can tell, the manual event generator can only emit one event at a time.

You put this in :
```
{
  "A": "1",
  "B": "2"
}
```
... and you get the same out.

This is usually fine for most unit testing, but I have already been tripped up by a fault (#1222, now fixed) where the receiving agent behaved differently with a stream of incoming events.

I tried something like this on the manual event generator :
```
[
{
  "A": "1",
  "B": "2"
},
{
  "C": "3",
  "D": "4"
}
]
```
... but what I got out was this : 
```
{
  "0": {
    "A": "1",
    "B": "2"
  },
  "1": {
    "C": "3",
    "D": "4"
  }
}
```
... which (I think) is still one event containing an array of hashes.

I can see why getting a single run of a single agent to produce multiple events could be awkward, but it would be useful! The best approach at the moment is to wire up a 'real' agent that emits 'real' events; this works, but it's sometimes easier to identify problems with the hand-crafted data that the manual event generator allows.

**Comment by cantino** [comment]
Hey @ohingardail.  I think this is a very reasonable idea.  Would you like to try making the change?

**Comment by ohingardail** [comment]
I'd like to be able to do this, but I don't think I'd know how. I'd be more than willing to test out the solution of anybody more competent at Ruby than me.

**Comment by cantino** [comment]
I'll take a look at adding it.
