### ISSUE TITLE
[Suggestion] Google Calendar agent doesn't support Liquid templating

### ISSUE THREAD

**Issue by ohingardail** [cantino/huginn#1229]
My Huginn set up aggregates events from local theatre, arts venues, community centres and such and stuffs them into a several Google Calendars (one for 'entertainment', 'community', 'education' etc) all of which are accessed using the same API key but different calendar IDs.

It would be awfully useful if the Google Calendar Agent could support Liquid templates, so, for instance, the following configuration would be legal (it isn't at the moment) :
```
{
  "expected_update_period_in_days": "30",
  "google": {
    "key_file": "/home/huginn/Huginn-abcdef.p12",
    "key_secret": "xxx",
    "service_account_email": "xxx@xxx.xxx.gserviceaccount.com"
  },
  "calendar_id": "{{ calId }}"
```
... so the value of {{ calID }} could be programmatically set upstream.

At the moment, the Google calendar agent complains about this thus : 
```
{
  "success": true,
  "published_calendar_event": {
    "error": {
      "errors": [
        {
          "domain": "global",
          "reason": "notFound",
          "message": "Not Found"
        }
      ],
      "code": 404,
      "message": "Not Found"
    }
  },
  "agent_id": nn,
  "event_id": nnnnn
}
```

... by which I'm guessing that {{ calID }} is either used literally or evaluated to nothing, neither of which are valid calendar IDs.

At the moment, a cumbersome workaround is to configure as many Google Calendar Agents as you have calendars, and prefix each with a trigger agent designed to filter *all* incoming events and only let through those that are applicable to its calendar.

It would also be quite neat if the other fields ("key_file", "key_secret", "service_account_email") could support {% credential USER_CREDENTIAL_NAME %} credentials so the relevant data could be stored centrally rather than in multiple agents.

As a broader point, how can I tell which agents support Liquid templating and which don't?

**Comment by cantino** [comment]
Hey @ohingardail. It looks like changing `options['calendar_id']` to `interpolated['calendar_id']` in the source code of google_calendar_publish_agent.rb would fix this.  Are you comfortable making that change to your instance of Huginn and seeing if it fixes the issue for you?  If it does, we can commit it for everyone.  Otherwise, I can make the change in a PR.

**Comment by ohingardail** [comment]
OK, I'll have a go at this.

**Comment by ohingardail** [comment]
I altered line 97 of app/models/agents/google_calendar_publish_agent.rb thus :
```
calendar_event = JSON.parse(calendar.publish_as(interpolated['calendar_id'], event.payload["message"]).response.body)
```
... re-exported Huginn, then created a Google Calendar agent thus :
```
{
  "expected_update_period_in_days": "30",
  "google": {
    "key_file": "/home/huginn/Huginn-abcdef.p12",
    "key_secret": "xxx",
    "service_account_email": "xxx@xxx.gserviceaccount.com"
  },
  "calendar_id": "{{cal_id}}"
}
```
(using real values rather than 'xxx'), and used the Manual event generator to pipe this value into it:
The Google Calendar Agent returned this error :

```
Exception during receive. 757: unexpected token at 'Not Found': /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
/home/huginn/huginn/app/models/agents/google_calendar_publish_agent.rb:97:in `block in receive'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/relation/delegation.rb:46:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/relation/delegation.rb:46:in `each'
/home/huginn/huginn/app/models/agents/google_calendar_publish_agent.rb:94:in `receive'
/home/huginn/huginn/app/jobs/agent_receive_job.rb:8:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/execution.rb:32:in `block in perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
:
:
... and so-on ...
```

**Comment by cantino** [comment]
That sure looks right to me.  You could add a new line above the JSON.parse line to output the interpolated value to sanity check it

either

```ruby
log "The value is: #{interpolated['calendar_id']}"
```

which will show up in the Agent's log view, or

```ruby
puts "The value is: #{interpolated['calendar_id']}"
```

which should show up in the UNIX console if you're running Huginn in a way where the console logs are easy to view.

**Comment by ohingardail** [comment]
I changed app/models/agents/google_calendar_publish_agent.rb as suggested, re-exported and re-tested :
```
log "The value is: #{interpolated['calendar_id']}"
calendar_event = JSON.parse(calendar.publish_as(options['calendar_id'], event.payload["message"]).response.body)
```
The agent emitted a log message:
```
The value is: 
```
that is, ```#{interpolated['calendar_id']}``` was evaluated to nothing.

**Comment by cantino** [comment]
Crap, sorry.  It needs the `event` too, I think.  Try

```ruby
log "The value is: #{interpolated(event)['calendar_id']}"
calendar_event = JSON.parse(calendar.publish_as(interpolated(event)['calendar_id'], event.payload["message"]).response.body)
```

**Comment by ohingardail** [comment]
With both lines, Email Agent log output looks like this:
```
The value is: xxx@group.calendar.google.com

Exception during receive. 757: unexpected token at 'Not Found': /home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
/home/huginn/huginn/app/models/agents/google_calendar_publish_agent.rb:98:in `block in receive'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/relation/delegation.rb:46:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/relation/delegation.rb:46:in `each'
/home/huginn/huginn/app/models/agents/google_calendar_publish_agent.rb:94:in `receive'
/home/huginn/huginn/app/jobs/agent_receive_job.rb:8:in `perform'
:
:
etc
```
... where xxx is the correct ID of he calendar.

**Comment by cantino** [comment]
Well, that makes me think that the Huginn code is working, assuming `xxx@group.calendar.google.com` is the correct calendar id.  You put `interpolated` in the two places like my example?

**Comment by ohingardail** [comment]
@cantino Aha! I see. I was still using the code you originally suggested: *changing options['calendar_id'] to interpolated['calendar_id']* and *log "The value is: #{interpolated['calendar_id']}"* but your latest comment includes an *(event)* reference I missed! If I use *interpolated(event)['calendar_id']* instead, the log out value is correct and calendar events gets correctly put into the right calendar. 
I experimented with {% credential xxx %} for key_file" and "service_account_email" as well, although this still seems not to work (I get an "Invalid keyfile or passphrase" log message).

**Comment by cantino** [comment]
I think you'll need to use "interpolated" for places key_file and
service_account_email are referenced instead of options too to support
those. Glad it's working! Are you interested in making a PR to contribute
the change to huginn?

**Comment by ohingardail** [comment]
I wouldn't be confident about adding a change to the git repository, if that's what you mean.

**Comment by cantino** [comment]
Well, ideally a pull request on GitHub with the changes and a spec showing
that they work. I'm also happy to make them since its small and you've
tested it.

**Comment by Chaosspeeder** [comment]
I assume the fix isn't online. I have a similar issue. The Google calendar publisher agent  doesn't support credentials.

**Comment by cantino** [comment]
I can make this change to Huginn shortly.

**Comment by cantino** [comment]
Mind testing #1257 @Chaosspeeder or @ohingardail?

**Comment by Chaosspeeder** [comment]
Thank you.  I will try  fix out your fix tonight (GMT) and give you a reply b

**Comment by cantino** [comment]
It won't support credentials yet. I can add that shortly.

**Comment by cantino** [comment]
I've added options['google']['key'], which can be the key itself or a Liquid credential reference.  I'm not setup to test this though.  Would you mind seeing if it works for you?
