### ISSUE TITLE
How to set env/config variables in Docker?

### ISSUE THREAD

**Issue by apopiak** [cantino/huginn#1230]
I saw the guide for integrating an OAuth app (https://github.com/cantino/huginn/wiki/Configuring-OAuth-applications#twitter) but I couldn't figure out how to set the oath tokens on a docker version of Huginn.
The link in the Twitter OAuth for docker just points to the generic [Docker page](https://hub.docker.com/r/cantino/huginn/) which doesn't contain any information on setting variables.
So you see I couldn't find the documentation.

**Comment by cantino** [comment]
I believe you need to set the HUGINN_TWITTER_OAUTH_KEY and HUGINN_TWITTER_OAUTH_SECRET environment variables when starting Docker.  (I think these are unprefixed in @dsander's new setup, but still start with HUGINN_ currently.)

**Comment by apopiak** [comment]
So it is not possible to change them for a running Huginn?

**Comment by dsander** [comment]
@apopiak As far as I know you can not change the environment variables for an existing docker container. When you are using a volume to persist the database you can `docker stop`, `rm` and change the environment variables in a new `docker run` command

**Comment by apopiak** [comment]
Ok, I suspected that after reading up on docker (not an expert there ;-) ), but it wasn't clear from the documentation.
