### ISSUE TITLE
{% line_break %} appears not to work in Email Agent because line break character is ignored in HTML emails

### ISSUE THREAD

**Issue by ohingardail** [cantino/huginn#1231]
An Email Agent configured like this:
```
{
  "subject": "{{ title }}",
  "expected_receive_period_in_days": "7",
  "recipients": "xx@isp.com",
  "body": "{{ description }} {% line_break %} {{ source_url }}"
}
```
... actually results an HTML email containing a line break character between {{ description }} and {{ source_url }}, which of course, is ignored when HTML is rendered, where a ```<br>``` is required instead.

I am unclear whether the Email Agent is creating the HTML email or something downstream, but if HTML output is mandated by the Email Agent then {% line_break %} doesn't actually put a line break in (or rather it puts in the wrong one, if you see what I mean). 

The workaround is to put a literal ```<br>``` in instead of {% line_break %}. 

This might be more of a documentation issue; https://github.com/cantino/huginn/wiki/Formatting-Events-using-Liquid might need updating to clarify that {% line_break %} won't do what a user might expect of it in Email Agent (and any other agent emitting HTML, if any).

**Comment by cantino** [comment]
You may be getting an HTML-formatted email.  Perhaps try `<br />&nbsp;<br />` instead of `{% line_break %}`?

**Comment by virtadpt** [comment]
Let me guess - you're sending messages to a Gmail account, @ohingardail?  Everything runs together?  I get the same thing.

@cantino I'll try that, too.

**Comment by cantino** [comment]
Please let me know what you see.

**Comment by ohingardail** [comment]
@virtadpt I've seen the effect in both hotmail and gmail. @cantino '<br>', or variations such as those you suggested, work fine. This might be a case of expectations management; I expected {% line_break %} to break a line, and it doesn't always; it puts in '\n' (I think) which is ignored in HTML rendering.

**Comment by cantino** [comment]
Right, it adds the line break character (\n), not HTML. Is there somewhere
that we should update our docs?

**Comment by ohingardail** [comment]
The only place I've seen {% line_break %} documented is here : https://github.com/cantino/huginn/wiki/Formatting-Events-using-Liquid#tags-added-by-huginn

**Comment by cantino** [comment]
Thanks!  I'll update the wiki to recommend `<br>` for emails.  Can we close this issue @ohingardail?

**Comment by ohingardail** [comment]
Yes, I think so.
