### ISSUE TITLE
Use Trigger Agent to filter calculated date?

### ISSUE THREAD

**Issue by tomkofford** [cantino/huginn#1234]
I have the following set up to scrape, filter, and publish a podcast:

1.  Website Agent to scrape original podcast feed. I extract the original published date as 'pubDate' here. A sample date looks like "Tue, 19 Jan 2016 17:59:18 +0000".
2.  Trigger Agent to filter against keywords. So far so good.
3.  De Duplication Agent that filters matches on the enclosure URL.
4.  Data Output Agent to provide the podcast feed.

Works great except that I need to limit my stored events (Heroku free plan). I don't want to keep events very long for duplicate checking, etc. I figure I can save events from the De Deplication Agent for a week or so and be fine. I'd like to limit the output of the Website Agent to events in the past week so prior events aren't duplicated.

I'd like to add something to the Trigger agent to limit events to the previous week. I can get the two dates in timestamp format to use `>=` logic like this:
Timestamp one week ago: `{{'now' | date: '%s' | minus : 604800}}`
Timestamp of sample above: `{{pubDate | date: '%s'}}`

It would be really easy to do `EventTime >= WeekAgo`, but I can't figure out how to pull this off in the Trigger Agent. It seems like whatever I put in 'path' will get evaluated to be the JSON path, not an actual value. And it seems that 'value' must be compared to field found at 'path' in the rules.

I also thought through adding it on the Website Agent (convert the date to timestamp), but that doesn't look possible either.

Must I have an Event Formatting agent before the Trigger agent and add a new value that's a conversation of pubDate to timestamp format? Just lazy and looking for a shortcut ;-). I'm fine using a formatting agent, but if there's a more concise way to do this that I'm overlooking, I'd love to know. 

Thanks!!

**Comment by tomkofford** [comment]
The Formatting Agent was quick and easy to setup. Everything seems to work correctly. I'm still curious if it's required in this instance.

**Comment by cantino** [comment]
Hey @tomkofford, welcome, and thanks for the clear description of your issue!

I think you'd analyzed it correctly-- as it stands, the TriggerAgent expects JSONPaths, not Liquid templating.  If you'd like to try and change this, it might be a nice improvement, but we'd need to be careful to migrate everyone's existing TriggerAgents.  (I think we could likely migrate existing paths to something like `{{ path }}`, so `hello.world` would be `{{ hello.world }}`, although not everything in JSONPath is supported in Liquid, so it might not be a perfect upgrade.  Worth thinking about.)  You could also consider adding a mode for TriggerAgents where the values are interpreted as values with Liquid, not as paths.

**Comment by ohingardail** [comment]
Does this mean that the trigger agent doesn't allow liquid templating for ```value``` either? This trigger agent config has the intention of only allowing through future events (although it doesn't work) :
```
{
  "expected_receive_period_in_days": "30",
  "keep_event": "true",
  "rules": [
    {
      "type": "field>=value",
      "value": "{{ 'now' | date: '%s' }}",
      "path": "unixDate"
    }
  ]
}
```
... where ```unixDate``` is configured upstream as something like ```{{ 'now' | date: '%s' | plus: 10000 }}``` (ie a future date).
If ```value``` has to be a literal, and *now* changes all the time, how would you filter for future events?

**Comment by cantino** [comment]
I'll need to look, but I'm pretty sure the value should work fine with
Liquid.

**Comment by tomkofford** [comment]
@ohingardail Yes, Liquid works fine for value. I'm using the following successfully:
```
"type": "field>=value",
"value": "{{'now' | date: '%s' | minus : 604800}}",
"path": "pubDateTimestamp"
```
My problem was that pubDate wasn't initially in unix timestamp format. I had to do that in a separate step in a different agent.

Since there isn't much (any that I saw) logging from the trigger agent, you may want to do something like this to make sure the values you are comparing are comparable (changed "type" so the event will be emitted and added message to see the values):
```
{
  "expected_receive_period_in_days": "30",
  "keep_event": "true",
  "rules": [
    {
      "type": "field!=value",
      "value": "{{ 'now' | date: '%s' }}",
      "path": "unixDate"
    }
  ],
"message": "vaue= {{'now' | date: '%s' }}; unixDate={{unixDate}}"
}

**Comment by ohingardail** [comment]
Aha! Its the manual event generator that isn't parsing Liquid templates, so it's no wonder that my test returns odd results. Should I log a separate issue about this?

**Comment by cantino** [comment]
Sure, it would be reasonable to add liquid parsing to the manual event
generator, although I think that would only be for testing?

**Comment by ohingardail** [comment]
Yes, only for testing, although I can see use cases where one might want to schedule a fixed event to be emitted in a production environment (a weekly post containing a link to a Google calendar showing next week's events, for example), but there are plenty of non-Huginn methods of doing that.

**Comment by cantino** [comment]
That's a good point, we don't really have an agent for periodically emitting a fixed event right now.  That's somewhat surprising, actually.

Are you interested in getting involved with coding in Huginn and trying to add that?

**Comment by ohingardail** [comment]
Perhaps one day, when I know enough about Ruby and Huginn to offer valuable help I could try, but that isn't now, I'm afraid.

**Comment by cantino** [comment]
I think for now we should leave this as-is: use an EventFormattingAgent to generate Liquid synthetic values, then filter on them with a TriggerAgent.  Does that work for you?

**Comment by cantino** [comment]
Closing since we haven't heard back.  Hope it's working for you!  Please re-open if you want to discuss further.
