### ISSUE TITLE
Why WebsiteAgent's url only recieve {{url}} value?

### ISSUE THREAD

**Issue by waldens** [cantino/huginn#1238]
WebsiteAgent's
```
{
  ...
  "url": "{{url}}",
  ...
}
```
no idea if I misunderstand:
If use {{url_article}} or whatever, although completely same url string, it's not working.
it's not a big problem, but will be more convenient if any {{...}} is allowed to use.

**Comment by cantino** [comment]
I'm sorry, could you clarify what you're trying to do?  (I think you may need to use `url_from_event`.)

**Comment by waldens** [comment]
Sorry for my broken English. And thanks cantino, `url_from_event` is indeed what I need. :smiley:  
I use `url` for several months and never knew `url_from_event`, such an idiot.

**Comment by cantino** [comment]
Glad it's working!
