### ISSUE TITLE
rake aborted!LoadError: cannot load such file -- google/api_client

### ISSUE THREAD

**Issue by santoshgistto** [cantino/huginn#1246]
rake aborted!
LoadError: cannot load such file -- google/api_client
/var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/home/santosh/Documents/rd/huginn-master/config/application.rb:5:in `<top (required)>'
/home/santosh/Documents/rd/huginn-master/Rakefile:5:in `<top (required)>

**Comment by cantino** [comment]
Have you run "bundle"? How are you running Huginn?

**Comment by santoshgistto** [comment]
ran the bundle
got the result
Bundle complete! 93 Gemfile dependencies, 211 gems now installed.
Bundled gems are installed into ./vendor/bundle.

huginn running local machine ubuntu14

**Comment by dsander** [comment]
Hi @santoshgistto 

running `bundle exec rake` should work then.

**Comment by santoshgistto** [comment]
@dsander  by running bundle exec rake 

getting :

/var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:289: warning: Insecure world writable dir /home/santosh/Documents/rd in PATH, mode 040777
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
rake aborted!
Rake::CommandLineOptionError: Unrecognized --trace option 'races'
/home/santosh/Documents/rd/huginn-master/vendor/bundle/gems/rake-10.5.0/lib/rake/application.rb:613:in `select_trace_output'
/home/santosh/Documents/rd/huginn-master/vendor/bundle/gems/rake-10.5.0/lib/rake/application.rb:567:in `block in standard_rake_options'
/usr/lib/ruby/2.2.0/optparse.rb:1427:in `call'
/usr/lib/ruby/2.2.0/optparse.rb:1427:in `block in parse_in_order'
/usr/lib/ruby/2.2.0/optparse.rb:1383:in `catch'
/usr/lib/ruby/2.2.0/optparse.rb:1383:in `parse_in_order'
/usr/lib/ruby/2.2.0/optparse.rb:1377:in `order!'
/usr/lib/ruby/2.2.0/optparse.rb:1469:in `permute!'
/usr/lib/ruby/2.2.0/optparse.rb:1491:in `parse!'
/usr/lib/ruby/2.2.0/optparse.rb:1480:in `parse'
/home/santosh/Documents/rd/huginn-master/vendor/bundle/gems/rake-10.5.0/lib/rake/application.rb:638:in `handle_options'
/home/santosh/Documents/rd/huginn-master/vendor/bundle/gems/rake-10.5.0/lib/rake/application.rb:86:in `block in init'
/home/santosh/Documents/rd/huginn-master/vendor/bundle/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/santosh/Documents/rd/huginn-master/vendor/bundle/gems/rake-10.5.0/lib/rake/application.rb:84:in `init'
/home/santosh/Documents/rd/huginn-master/vendor/bundle/gems/rake-10.5.0/lib/rake/application.rb:76:in `block in run'
/home/santosh/Documents/rd/huginn-master/vendor/bundle/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/santosh/Documents/rd/huginn-master/vendor/bundle/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/home/santosh/Documents/rd/huginn-master/vendor/bundle/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/home/santosh/Documents/rd/huginn-master/vendor/bundle/bin/rake:23:in `load'
/home/santosh/Documents/rd/huginn-master/vendor/bundle/bin/rake:23:in `<main>

**Comment by santoshgistto** [comment]
Hi @cantino & @dsander  thanks fixed the issue
changed
gem "google-api-client", require: 'google/api_client'
to
gem 'google-api-client', '~> 0.9.1'
i am not sure what is the issue am new to ruby

**Comment by cantino** [comment]
That's super weird, I have no idea why you had to make that change.

**Comment by santoshgistto** [comment]
[!] There was an error parsing `Gemfile`: Could not load huginn settings from .env file.. Bundler cannot continue.

 #  from /home/santosh/Documents/hgg/huginn/Gemfile:8
 #  -------------------------------------------
 #  require File.join(File.dirname(__FILE__), 'lib/gemfile_helper.rb')
 >  GemfileHelper.load_dotenv do |dotenv_dir|
 #    path dotenv_dir do
 #  -------------------------------------------
trying to deploy on heroku getting error while running bundle 
i need to copy of .env file ?

**Comment by cantino** [comment]
How are you deploying to Heroku?

**Comment by santoshgistto** [comment]
following the instructions provided the you 

https://github.com/cantino/huginn/blob/master/doc/heroku/install.md#instructions

**Comment by santoshgistto** [comment]
is am missing any thing?

**Comment by santoshgistto** [comment]
it was my mistake sorry for this.
i am new to awesome huginn :)

**Comment by cantino** [comment]
Glad you got it, and welcome!

**Comment by pjmorr** [comment]
I also received the 
```bash
LoadError: cannot load such file -- google/api_client
```
error today after doing git fetch && git merge upstream/master and changing Gemfile

```bash
44: -gem "google-api-client", require: 'google/api_client'
44: +gem 'google-api-client', '~> 0.9.1'
```
resolved my issue.

**Comment by dsander** [comment]
@pjmorr Did you maybe run `bundle update` by accident? The `google-api-client` gem version is locked in the [Gemfile.lock](https://github.com/cantino/huginn/blob/master/Gemfile.lock#L237) and should not be auto updated to a new version without manual changes. Even though we probably should lock it in the Gemfile as well.
