### ISSUE TITLE
RSS Feeds and TriggerAgent Help

### ISSUE THREAD

**Issue by xdirty** [cantino/huginn#1247]
im basically trying to filter out rss feeds.

This is my TriggerAgent

>{
  "expected_receive_period_in_days": "14",
  "keep_event": "true",
  "rules": [
    {
      "type": "regex",
      "value": "keyword1|keyword2|keyword3",
      "path": "url|description|title"
    }
  ]
}

I know the keywords should work since ive seen it other people do it but i could not find anything on having multiple paths like i have and im wondering if that will work. In order to search the title, description and url am i doing this right ?

Also if an rss im trying to filter is showing one of my keywords in it, why doesnt it show up right away, what im saying is the rss feed is showing that it has the keyword but it takes a while to retrieve the rss feed and filter for keywords, even though i have the refresh set at 5 min.

Just in case heres the rest of my agents

RssAgent
>{
  "expected_update_period_in_days": "1",
  "clean": "false",
  "url": "http://rssfeed.com/Rss.xml"
}

DataOutputAgent
>{
  "secrets": [
    "a-secret-key"
  ],
  "expected_receive_period_in_days": 1,
  "template": {
    "title": "sometitle",
    "description": "This is a feed was made by me,
    "item": {
      "title": "{{title}}",
      "description": "{{description}}",
      "link": "{{url}}"
    }
  }
}

**Comment by cantino** [comment]
Welcome @xdirty.  The `path` can only have on JSONPath in it, I believe.  I think you'd need multiple rules for multiple paths.

It could take longer than 5min because events don't propagate immediately by default and are instead propagated once every few minutes.  If  you check the "propagate immediately" checkbox, it might help a little.  You can also manually run the Agent.

**Comment by xdirty** [comment]
Cantino, first of all thank you for everything.

Im sorry, are you saying it can only have one path ? so different triggerAgent per path ?

**Comment by cantino** [comment]
You can have multiple rules in one trigger agent, like:

```
{
"expected_receive_period_in_days": "14",
"keep_event": "true",
"rules": [
{
"type": "regex",
"value": "keyword1|keyword2|keyword3",
"path": "url|description|title"
},
{
"type": "regex",
"value": "keyword1|keyword2|keyword3",
"path": "url|description|title"
},
{
"type": "regex",
"value": "keyword1|keyword2|keyword3",
"path": "url|description|title"
},
...
]
}
```

**Comment by xdirty** [comment]
Gotcha, now it all makes sense. 

THANK YOU!

**Comment by cantino** [comment]
No problem :)
