### ISSUE TITLE
Improvements to Twitter User Agent

### ISSUE THREAD

**Issue by vx28643** [cantino/huginn#1249]
Hi. I'd like Huginn to inform me about tweets from multiple Twitter accounts, and setting up a Twitter User Agent for each of them is rather clunky.

I am hoping for *either*:

* Added support in Twitter User Agent so it can follow multiple accounts.
* A new option in Twitter User Agent (or a new agent) that would simply inform me of any new tweets from any twitter accounts that are followed by the Twitter account I've linked to Huginn. 

The second would be preferable for me, as I could control who's tweets were picked up simply by following/unfollowing them in the linked Twitter account.

I'm not really in a position script this myself. So I'm wondering if something like this is on Huginn's horizon or if there is a way I can help see a feature like this added?

Thanks!

**Comment by cantino** [comment]
Hey @vx28643.  It looks likely that the TwitterStreamAgent could be modified to accept a list of usernames and to use the `follow` param. https://dev.twitter.com/streaming/reference/post/statuses/filter

I'll add `help-wanted` and hopefully someone will pick up this issue.

**Comment by Jngai** [comment]
@cantino @vx28643 Let me give this a try. Be back soon.

**Comment by Jngai** [comment]
@cantino The follow param is an "or" scenario and not an "and" one. So if filter is "harvard" and set to follow "me". I am getting tweets with harvard (filter) plus my own "harvard" related tweets. I am not sure if this answers what @vx28643 is looking for since its not only tweets by that user with those terms. It will be everything and will be quite messy. You will have to look for that particular tweet from that particular user from a jumble of events. Looks like setting up a twitter user agent for each user to follow is easier.

**Comment by vx28643** [comment]
Thank you @Jngai for looking at options.

What I want is a way to follow all tweets from multiple Twitter accounts, rather than setting up a Twitter User Agent for each of them.

So either of:

* a way to follow multiple Twitter accounts with a single Twitter User Agent (i.e. easily add/remove accounts by editing a single agent).
or 
* a way to tell Twitter User Agent to just follow **all** Twitter accounts that my twitter account is following (triggering when anyone tweets whom the account follows). This way I could control who's tweets trigger the agent simply by following them in Twitter, not even needing to log into Huginn to edit the agent.

The idea is to trigger when any of the accounts tweeted anything.
I did not plan to use any search words.
I think such an option would make the Twitter Agent much more valuable to Huginn users.

Hope this clarifies the intention & thanks again!

**Comment by Jngai** [comment]
@cantino The user agent is using `twitter.user_timeline` instance method to return 20 tweets from a user. There is actually a `home_timeline` method that 

> Returns the 20 most recent Tweets, including retweets if they exist, posted by the authenticating user and the users they follow.

This should answer the question. If it does would it be appropriate to modify the user agent and or create a new twitter agent?

**Comment by cantino** [comment]
It seems a bit silly to have multiple types of Twitter agents.  Do you think it makes sense to add this feature to your new `TwitterFavoritesAgent` and call it just the `TwitterTimelineAgent` or something?  Maybe it could select between modes?

**Comment by Jngai** [comment]
#1321 I added the option to twitter user agent. Turns out user_timeline-instance_method are nearly identical to home-timeline-instance method. It makes more sense to add this feature in user agent. Tested both locally and through spec. Description updated. There is a new pull request for this.

**Comment by cantino** [comment]
Awesome!

**Comment by vx28643** [comment]
Fantastic work @Jngai. I finally got the chance to update my install and try this. Following my own timeline appears to work well!

**Comment by Jngai** [comment]
@vx28643 I am very glad that you are using my work and that is working out for you.

**Comment by cantino** [comment]
:smile: :+1:
