### ISSUE TITLE
Trouble installing to rasberry Pi 2

### ISSUE THREAD

**Issue by xdirty** [cantino/huginn#1251]
Im trying to install on the latest raspberry pi 2 b and im getting this error. Keep in mind im a complete linux noob.

```
root@raspberrypi:/home/pi/huginn# bundle
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this
machine.
Could not load huginn settings from .env file.

Make sure to copy the .env.example to .env and change it to match your configuration.

Capistrano 2 users: Make sure shared files are symlinked before bundle runs: before 'bundle:install', 'deploy:symlink_configs'

[!] There was an error parsing `Gemfile`: Could not load huginn settings from .env file.. Bundler cannot continue.

 #  from /home/pi/huginn/Gemfile:8
 #  -------------------------------------------
 #  require File.join(File.dirname(__FILE__), 'lib/gemfile_helper.rb')
 >  GemfileHelper.load_dotenv do |dotenv_dir|
 #    path dotenv_dir do
 #  -------------------------------------------
root@raspberrypi:/home/pi/huginn#
```

**Comment by xdirty** [comment]
i installed ubuntu mate and removed everything and started all over, now im getting this error
rasp-pi@rasppi-desktop:~/huginn$ bundler
Could not load huginn settings from .env file.

Make sure to copy the .env.example to .env and change it to match your configuration.

Capistrano 2 users: Make sure shared files are symlinked before bundle runs: before 'bundle:install', 'deploy:symlink_configs'

[!] There was an error parsing `Gemfile`: Could not load huginn settings from .env file.. Bundler cannot continue.

 #  from /home/rasp-pi/huginn/Gemfile:8
 #  -------------------------------------------
 #  require File.join(File.dirname(__FILE__), 'lib/gemfile_helper.rb')
 >  GemfileHelper.load_dotenv do |dotenv_dir|
 #    path dotenv_dir do
 #  -------------------------------------------
rasp-pi@rasppi-desktop:~/huginn$

**Comment by cantino** [comment]
Did you follow the instructions in the readme?  It looks like you need to copy the .env.example file.

**Comment by xdirty** [comment]
I did finally copy it over, but i read it from the fedora guide but im on a debian based distro. the Novice-setup-guide didnt say anything about copying the .env file . Right now it looks like its still installing. Every guide ive read has been horrible for new linux users. the one that was half way decent was this one
http://clockwerx.blogspot.com/2014/06/introduction-to-huginn-owntracks-or-how.html

ive been trying to get this all day and still haven't.

**Comment by cantino** [comment]
I'm sorry to hear that, it sounds frustrating.  Did you see or follow or recommended guide at https://github.com/cantino/huginn/tree/master/doc ?

**Comment by xdirty** [comment]
How do i edit the .Env and then save the changes?

**Comment by xdirty** [comment]
Some how i figured out how to edit the .env file but now im getting this error 

> pi@raspberrypi:~/huginn $ bundle exec foreman start
00:46:42 web.1  | started with pid 1889
00:46:42 jobs.1 | started with pid 1891
00:48:05 web.1  | [2016-02-03 00:48:05] INFO  WEBrick 1.3.1
00:48:05 web.1  | [2016-02-03 00:48:05] INFO  ruby 2.1.5 (2014-11-13) [arm-linux-gnueabihf]
00:48:05 web.1  | [2016-02-03 00:48:05] INFO  WEBrick::HTTPServer#start: pid=1890 port=5000
00:48:05 jobs.1 | /var/lib/gems/2.1.0/gems/mysql2-0.3.16/lib/mysql2/client.rb:70:in `connect': Access denied for user 'root'@'localhost' (using password: NO) (Mysql2::Error)
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/mysql2-0.3.16/lib/mysql2/client.rb:70:in `initialize'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
00:48:05 jobs.1 | 	from /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
00:48:05 jobs.1 | 	from /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
00:48:05 jobs.1 | 	from /home/pi/huginn/lib/agent_runner.rb:61:in `with_connection'
00:48:05 jobs.1 | 	from /home/pi/huginn/lib/agent_runner.rb:93:in `block in load_workers'
00:48:05 jobs.1 | 	from /home/pi/huginn/lib/agent_runner.rb:89:in `each'
00:48:05 jobs.1 | 	from /home/pi/huginn/lib/agent_runner.rb:89:in `load_workers'
00:48:05 jobs.1 | 	from /home/pi/huginn/lib/agent_runner.rb:69:in `run_workers'
00:48:05 jobs.1 | 	from /home/pi/huginn/lib/agent_runner.rb:39:in `run'
00:48:05 jobs.1 | 	from bin/threaded.rb:13:in `<top (required)>'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/commands/runner.rb:60:in `load'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/commands/runner.rb:60:in `<top (required)>'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:123:in `require'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:90:in `runner'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
00:48:05 jobs.1 | 	from /var/lib/gems/2.1.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
00:48:05 jobs.1 | 	from bin/rails:4:in `require'
00:48:05 jobs.1 | 	from bin/rails:4:in `<main>'
00:48:06 jobs.1 | exited with code 1
00:48:06 system | sending SIGTERM to all processes
00:48:06 web.1  | terminated by SIGTERM
pi@raspberrypi:~/huginn $ 

>

**Comment by xdirty** [comment]
Ok so i changed the mysql password to blank since it seemed to cause problems, redid the database commands, everything looks like it works but when i go to localhost:3000, nothing shows

`pi@raspberrypi:~ $ cd huginn
pi@raspberrypi:~/huginn $ bundle exec foreman start
01:20:44 web.1  | started with pid 1952
01:20:44 jobs.1 | started with pid 1954
01:22:09 web.1  | [2016-02-03 01:22:09] INFO  WEBrick 1.3.1
01:22:09 web.1  | [2016-02-03 01:22:09] INFO  ruby 2.1.5 (2014-11-13) [arm-linux-gnueabihf]
01:22:09 web.1  | [2016-02-03 01:22:09] INFO  WEBrick::HTTPServer#start: pid=1953 port=5000
01:22:10 jobs.1 | Starting HuginnScheduler
01:22:17 jobs.1 | Starting DelayedJobWorker
01:23:10 jobs.1 | Queuing event propagation
01:23:10 jobs.1 | Queuing schedule for every_1m
01:24:10 jobs.1 | Queuing schedule for every_2m
01:24:10 jobs.1 | Queuing event propagation
01:24:10 jobs.1 | Queuing schedule for every_1m
01:25:10 jobs.1 | Queuing event propagation
01:25:10 jobs.1 | Queuing schedule for every_1m
01:26:10 jobs.1 | Queuing schedule for every_2m
01:26:10 jobs.1 | Queuing event propagation
01:26:10 jobs.1 | Queuing schedule for every_1m
01:27:10 jobs.1 | Queuing schedule for every_5m
01:27:11 jobs.1 | Queuing event propagation
01:27:11 jobs.1 | Queuing schedule for every_1m
01:28:10 jobs.1 | Queuing schedule for every_2m
01:28:11 jobs.1 | Queuing event propagation
01:28:11 jobs.1 | Queuing schedule for every_1m
01:29:11 jobs.1 | Queuing event propagation
01:29:11 jobs.1 | Queuing schedule for every_1m
`

**Comment by xdirty** [comment]
huginn is installed and appears to be working, now if someone could tell me why it works on port 5000 instead of 3000, i would be trully grateful

**Comment by cantino** [comment]
Is the `PORT` ENV variable set to 5000?

**Comment by xdirty** [comment]
Okay cantino, i will check the. Env file when i get home, you already pointed me in the right direction. 

I have another question, if i just x out the terminal to shut down huginn can that cause damage? Is there a proper way to shut off huginn? 

Another question which probably has nothing to do with huginn but do u know if mysql runs by it self on start up? Do i need  to do that manually?

**Comment by cantino** [comment]
MySQL likely runs on startup if you have it installed. Huginn won't unless
you put it in an appropriate run level or use foreman to generate an
upstart script.

Control-c in a terminal to stop Huginn. Closing the window may work, or it
may end up running in the background. It shouldn't cause any harm.

**Comment by xdirty** [comment]
Perfect!. Thank you so much for helping me. Andrew, could we leave this issue open for a while, im just sure something else will come up and id hate to spam here with new topics constantly

**Comment by cantino** [comment]
Definitely. You're welcome!

**Comment by xdirty** [comment]
Andrew, as i said in another thread im trying tox filter rss feeds and 
I made multiple rules to search different paths but it almost seems like the second rule searches the first rules results after it has been sorted. I need the trigger agent to give me back results for 3 different paths without them filtering eachother. It seems my results are being filtered 3 times and im only returning items that mean all three conditions for the 3 different paths. Basically it feels like im returning results that contain all 3 keywords as the title, description, url and if one of the paths does not contain the keyword it gets filtered. 
I need huginn to search and return 3 different paths for my keywords and return any results rather than all paths having to contain all the keywords simultaneously. 

Also, is there a limit of how many keywords i can use? 


> You can have multiple rules in one trigger agent, like:

{
"expected_receive_period_in_days": "14",
"keep_event": "true",
"rules": [
{
"type": "regex",
"value": "keyword1|keyword2|keyword3",
"path": "url"
},
{
"type": "regex",
"value": "keyword1|keyword2|keyword3",
"path": "description"
},
{
"type": "regex",
"value": "keyword1|keyword2|keyword3",
"path": "title"
},
...
]
}

**Comment by cantino** [comment]
Hi @xdirty. I think you're correct.  The docs say `By default, all rules must match for the Agent to trigger. You can switch this so that only one rule must match by setting must_match to 1`.  So it sounds like you're seeing correct behavior: all the rules are being ANDed together.  If you want to OR them, set must_match to 1.  Does that make sense?

**Comment by xdirty** [comment]
Makes sense but where do i access the setting ? .env file ?

**Comment by cantino** [comment]
That setting is in the individual agent options. So in this case, the
trigger agent.

**Comment by xdirty** [comment]
ok Andrew , i think i got everything working properly, even email is working.

A few more questions and then if you'd like you can close this thread

If i have a local installation, when i access huggin is it suppose to be on port 5000 ? my env clearly sais port 3000, but when i start huginn it assigns port 5000. 

Also, is there a place where i can get other peoples scenarios ? I would like to see how other people are using huginn but i couldnt find anything

**Comment by cantino** [comment]
If PORT is set when foreman starts, it should use that, otherwise the default in the Procfile should be 3000.

We're working on starting a directory of Scenarios (#390), but it doesn't exist yet.

Glad it's working!

**Comment by cantino** [comment]
Turns out the port thing is an issue: #1291.  Glad it's otherwise working.  Please re-open if you want to discuss further.
