### ISSUE TITLE
Feature request: per agent choice of Multipart-HTML OR Plain-Text emails

### ISSUE THREAD

**Issue by hcampan** [cantino/huginn#1256]
Hi team,

I have a feature request :

Could we have the choice (if not too difficult to implement) in Email Agents to what email type (HTML or Plain text) we can send. Would love to be able to choose.

Thanks

Hubert

**Comment by cantino** [comment]
That would be a nice improvement.

**Comment by Jngai** [comment]
I can look into this.

**Comment by Jngai** [comment]
#1325 I opened a pr for this and is currently waiting for feedback.

**Comment by cantino** [comment]
Thanks @Jngai! @hcampan, would you be able to test @Jngai's PR?

**Comment by hcampan** [comment]
Sure ! How do I proceed. Sorry for my lack of "how to" on this.

**Comment by Jngai** [comment]
@hcampan, update yourself with the newest version of huggin code

> Periodically run git fetch upstream and then git checkout master && git merge upstream/master to merge in the newest version of Huginn.

afterward try this

`git fetch origin pull/1325/head:emailtest`
then
`git checkout  emailtest`

The first command pulls my pr into a new branch locally in your machine. Then the second command switched your app to that version. I just tried this. 

Please don't push anything and delete emailtest branch after testing.

**Comment by hcampan** [comment]
Thanks @Jngai

I appreciate your explanation, but I do not have enough knowledge bricks to make it work. I installed Huginn with https://github.com/cantino/huginn/blob/5fa18248666308624afa75ad4e3a370e26a3ae24/doc/manual/installation.md#install-init-script

I suppose I have to get to home/huginn/huginn$ and type your commands, but it didn't work even using sudo. I also went to https://help.github.com/articles/fetching-a-remote/ to try and understand, but didn't.

  sudo git fetch upstream

› fatal: 'upstream' does not appear to be a git repository

My question may be so newbe-ish, sorry. Can you point me in the right direction ? I don't want to crash my well-working Huginn instance. 

Thanks

**Comment by Jngai** [comment]
@hcampan lets wait for @cantino to chime in and confirm.

**Comment by cantino** [comment]
Hey @hcampan.  There are general update [instructions here](https://github.com/cantino/huginn/blob/5fa18248666308624afa75ad4e3a370e26a3ae24/doc/manual/update.md), but those don't go into how to point at a fork.  It's probably not worth trying to manually test in your production setup.

Don't worry about it! I'll test this out soon and we'll get it merged.
