### ISSUE TITLE
Issue with install on ubuntu 14.04

### ISSUE THREAD

**Issue by the4ndy** [cantino/huginn#1261]
I have followed the instructions and when i run this command I get the following out put :disappointed: 

`/home/huginn/huginn$ sudo -u huginn -H bundle install --deployment --without development test`

```
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:98:in `[]': invalid byte sequence in US-ASCII (ArgumentError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:98:in `strip_leading_spaces'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:103:in `word_wrap'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:89:in `tell_me'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:34:in `error'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:20:in `rescue in with_friendly_errors'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'
```

**Comment by cantino** [comment]
That's odd.  I wonder which Gem has a bad gemspec?

**Comment by cantino** [comment]
Mind seeing if appending `--verbose` to the bundle command gives anything useful?

**Comment by the4ndy** [comment]
i added --verbose after install but before --deployment and got A LOT of output but the end was the same, the end portion is below along with some lines above it, if you would like the whole thing in a pastebin just let me know

```
Query List: ["celluloid-gems", "faraday-middleware", "form_data"]
Query Gemcutter Dependency Endpoint API: celluloid-gems,faraday-middleware,form_data
HTTP GET https://bundler.rubygems.org/api/v1/dependencies?gems=celluloid-gems%2Cfaraday-middleware%2Cform_data
HTTP 200 OK
Query List: []
Fetching dependency metadata from https://rubygems.org/
Query List: ["celluloid-gems", "form_data", "faraday-middleware"]
Query Gemcutter Dependency Endpoint API: celluloid-gems,form_data,faraday-middleware
HTTP GET https://bundler.rubygems.org/api/v1/dependencies?gems=celluloid-gems%2Cform_data%2Cfaraday-middleware
HTTP 200 OK
Query List: []
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:98:in `[]': invalid byte sequence in US-ASCII (ArgumentError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:98:in `strip_leading_spaces'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:103:in `word_wrap'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:89:in `tell_me'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:34:in `error'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:20:in `rescue in with_friendly_errors'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'
```

**Comment by cantino** [comment]
That's odd.  What OS are you on?

@knu, any ideas?

**Comment by the4ndy** [comment]
The machine is an Ubuntu 14.04 "Container". The hypervisor is Proxmox and i believe its an LXC (or as I am told, Linux Container). I am spinning up a full VM now to see if that solves my issues. It was smooth sailing until this point thought :confused:

**Comment by cantino** [comment]
See the `LANG` suggestion on this page: http://stackoverflow.com/questions/14839674/bundle-install-error-invalid-byte-sequence-in-us-ascii-argumenterror

Maybe that will help?

**Comment by the4ndy** [comment]
SUCCESS! You are a gentleman and a scholar. Thank you sir. I did as the first answer in that link suggested and exported the variables in the OS manually and im off to the races (well the next step at least). Thanks again.

Here is the solution in case anyone is looking.

"As a workaround you can set utf8 locale in your system:
```
export LANG="C.UTF-8"
export LC_ALL="C.UTF-8"

```

**Comment by the4ndy** [comment]
Also, since it says owner next to your name, it might be worth pointing out, that in the ".env" file the install instructions say that that file should look like this
```
DATABASE_NAME=huginn_production
DATABASE_POOL=20
```
However for me, I found mine to actually be:
```
DATABASE_NAME=huginn_development
DATABASE_POOL=10
```

Not sure if that is a mistake in that particular part or somewhere else in the puzzle, or perhaps more likely some error on my part (I am admittedly a novice). Just wanted to point it out

**Comment by cantino** [comment]
If you use huginn_development, you're running in development mode in the container, which is probably okay, but generally intended for when testing / developing Rails locally.  `production` mode is what you run on a server for any duration.  Our [docs](https://github.com/cantino/huginn/tree/master/doc) should take you through it if you plan to use Huginn long term.

**Comment by dsander** [comment]
@the4ndy The database name does not really matter, `huginn_development` is the default of the `.env.example`, the rails convention is to use `huginn_production` in a production environment (on a sever), but it does not make a difference. You might want to increase the `DATABASE_POOL`, it makes sure huginn can connect to the database when using more then a few agents.

I wonder if we should add a note about the encoding to the installation instructions, is there a way for me to test the installation using the same distruction and version you used?

**Comment by the4ndy** [comment]
i built the setup on an LXC with Proxmox as the Hypervisor. the Template for the LXC is the latest official build from ubuntu. I couldnt find any documentation to say where it came from but what i did find leads me to believe that the template for the container is provided by Ubuntu (or Canonical or whomever) and not something made by Proxmox or their community.
