### ISSUE TITLE
Issue with Dokku install

### ISSUE THREAD

**Issue by remigourdon** [cantino/huginn#1264]
Hello everyone,

I'd like to report a problem I have with a fresh install of dokku where I installed huginn following the [mini tutorial](https://github.com/cantino/huginn/wiki/Mini-Tutorial-for-installing-huginn-on-dokku).

At several steps (starting when I do the database migration) I receive this kind of message:
```
ssh -t root@dokku.me dokku run huginn bundle exec rake db:migrate         
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Migrating to DeviseCreateUsers (20120728210244)
== 20120728210244 DeviseCreateUsers: migrating ================================
-- create_table(:users)
   -> 0.0269s
-- add_index(:users, :email, {:unique=>true})
   -> 0.0068s
-- add_index(:users, :reset_password_token, {:unique=>true})
   -> 0.0067s
== 20120728210244 DeviseCreateUsers: migrated (0.0467s) =======================

Migrating to AddAdminToUsers (20120728215449)
== 20120728215449 AddAdminToUsers: migrating ==================================
...
```

But in the end it seems the migration is effective. Afterwards I receive the same message upon the next command:
```
ssh -t root@dokku.me dokku run huginn bundle exec rake db:seed   
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
```

And in the end after the restard I receive a 502 Bad Gateway when I try to access the webpage and again this message is prompted in the terminal:
```
ssh -t root@dokku.me dokku ps:restart huginn                  
-----> Releasing huginn (dokku/huginn:latest)...
-----> Deploying huginn (dokku/huginn:latest)...
-----> DOKKU_SCALE file found (/home/dokku/huginn/DOKKU_SCALE)
=====> web=1
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
=====> huginn container output:
       fatal: Not a git repository (or any of the parent directories): .git
       fatal: Not a git repository (or any of the parent directories): .git
       I, [2016-02-02T22:49:55.925251 #9]  INFO -- : Refreshing Gem list
       New threaded worker PID: 156
       fatal: Not a git repository (or any of the parent directories): .git
       fatal: Not a git repository (or any of the parent directories): .git
       fatal: Not a git repository (or any of the parent directories): .git
       fatal: Not a git repository (or any of the parent directories): .git
=====> end huginn container output
-----> Running post-deploy
-----> Found previous container(s) (63533d6da7d9) named huginn.web.1
=====> renaming container (63533d6da7d9) huginn.web.1 to huginn.web.1.1454453399
=====> renaming container (4af8ea7e9ecb) gloomy_hodgkin to huginn.web.1
-----> VHOST support disabled. Skipping domains setup
-----> Setting config vars
       NO_VHOST: 1
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Setting config vars
       DOKKU_APP_RESTORE: 1
-----> Shutting down old containers in 60 seconds
=====> 63533d6da7d91e4d7c6fd1d12e29a747a0b253687d3a7608b2232476713e9b0b
=====> Application deployed:
       http://dokku.me:32769 (container)
       http://dokku.me:27178 (nginx)
```

I already tried to reinstall the app and reinstall dokku entirely but I always end up with the same issues.

Would appreciate your help very much.

**Comment by cantino** [comment]
I believe @madflow wrote the tutorial.

**Comment by madflow** [comment]
I ignored the ```fatal: Not a git repository (or any of the parent directories): .git```- seems to [Bundler Bug](http://stackoverflow.com/questions/14199212/fatal-not-a-git-repository-or-any-of-the-parent-directories-git-on-every-ra). It worked anyway :S.

As I wrote in the tutorial - you will have to wait > 30 Seconds or so to wait for the workers / web process to boot _after the deployment_. If this does not help - what does ```dokku logs hugin``` tell you or - ``` dokku nginx:error-logs huginn```.

Disclaimer: I only tested this with VHOST support enabled in dokku. 

I have currently a workin huginn installation running on Digitalocean (Dokku Droplet) with just copy+pasting from the tutorial.

**Comment by remigourdon** [comment]
So, I reinstalled everything using a domain name and **enabling VHOST support** and I confirm that everything works properly, despite the recurring `fatal: Not a git repository (or any of the parent directories): .git`.

I run it now on a Digitalocean Dokku Droplet with 1 GB of RAM and everything looks like it runs smoothly.

Thanks for the help!
