### ISSUE TITLE
docker image unable to bundle

### ISSUE THREAD

**Issue by sky-chen** [cantino/huginn#1265]
```
sudo docker run -it -p 3000:3000 cantino/huginn

Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/gems/mysql2-0.3.16.gem)
An error occurred while installing mysql2 (0.3.16), and Bundler cannot continue.
Make sure that `gem install mysql2 -v '0.3.16'` succeeds before bundling.
```

I'm able to access *https://rubygems.org/gems/mysql2-0.3.16.gem* without any proxy, so it doesn't seem like a connection issue. Is it possible that this is due to openssl ? (maybe [related](https://github.com/rapid7/metasploit-framework/issues/5187))

**Comment by dsander** [comment]
Hi @sky-chen,

`Errno::ECONNRESET` sounds like a connection issue, does it fail with the same message every time you try to start the container?

**Comment by sky-chen** [comment]
Hmm, I realized that one of the redirect site from rubygems.org is blocked (I didn't noticed that because my auto proxy does that for me). Sorry for such a sloppy issue.
