### ISSUE TITLE
Custom subject line in EmailDigestAgent

### ISSUE THREAD

**Issue by bobbysteel** [cantino/huginn#1266]
Hi - I'm having issues trying to create custom subject lines in my emails.
My config is as follows:

`{
  "subject": "Alert: {{title}}",
  "headline": "Description: {{description}}",
  "expected_receive_period_in_days": "30",
  "recipients": "me@me.com"
}`

However this just leaves blanks where title and description would go.
The output from TriggerAgent to the EmailDigestAgent is as follows:
`{
  "id": "http://www.com/x.html",
  "date_published": "2016-02-01 01:49:22 +0000",
  "last_updated": "Mon, 01 Feb 2016 01:49:22 +0000",
  "url": "http://www.com/f.html",
  "urls": [
    "http://www.com/x.html"
  ],
  "description": "goes here",
  "content": "goes here",
  "title": "goes here",
  "authors": [
    "xxx"
  ],
  "categories": [
    "xxxxx"
  ],
  "message": "my message"
}`

The inputs seem correct, but the agent doesn't seem to be dynamically generating the subject and title as I'd expect. Any ideas what looks wrong here? Thanks!

**Comment by bobbysteel** [comment]
I figured this out. Given the Digest agent, it takes context outside the individual group subject line. So EmailAgent is better suited to this job, which does pass through subject properly.

**Comment by cantino** [comment]
Glad you figured it out.  Is there a change you'd recommend based on this?

**Comment by bobbysteel** [comment]
I think for me it's a matter of having/finding more examples. Your website was helpful but I'd love to see a list of links to more complex examples for me to learn from.

**Comment by cantino** [comment]
Would you mind adding your example to the wiki? There's a section for agent
configuration examples.

**Comment by bobbysteel** [comment]
Done

**Comment by cantino** [comment]
Thanks!
