### ISSUE TITLE
Is it possible to include custom fields for events?

### ISSUE THREAD

**Issue by International** [cantino/huginn#1267]
Hey guys, 

Thanks for this great tool. I've started to make use of it, especially the website agent. I have something like this:

```
  "extract": {
    "name": {
      "css": "[data-date=\"{{ 'now' | date: '%Y%m%d' }}\"] .title",
      "value": ".//text()"
    },
```

The events created by the web agent are sent to email digest, and when sending the email, I'd like to be able to set a custom mail title, something like: "Digest for airdates.tv". Is it possible to add a static field to the events created by the website agent? So each event would have something like:

```
[ { "name": "Friends", "source" : "airdates.tv"}, {"name": "Simpsons", "source":"airdates.tv"}]
```

This way I figured I could make use of the source field in the email digest agent. Or is there another way of customizing the name of the digest email, based on the source?

**Comment by signallhill** [comment]
Use Event Formatting agent to format events generated from Website agent then send them to Email Agent

**Comment by International** [comment]
Thank you!

**Comment by SwarShah** [comment]
I also stumbled upon this and I found that you can pass custom fields in the `template` object which then will get included in the event.

```
  "template": {
    "source" : "airdates.tv"
  }
```
