### ISSUE TITLE
Docker install docs are missing information

### ISSUE THREAD

**Issue by uri** [cantino/huginn#1268]
https://github.com/cantino/huginn/blob/master/doc/docker/install.md

In the *Configuration and linking to a database container* it states:

> Follow the instructions on the docker hub registry on how to configure Huginn using environment variables and linking the container to an external MySQL or PostgreSQL database.

Theres a link in there that points to https://hub.docker.com/r/cantino/huginn/ but the docker repository doesn't have any additional information on how to do any of these configurations.

Is this pointing to the right URL? Does the Docker repository need to be updated?

**Comment by dsander** [comment]
Hi @uri,

yes that is very annoying, as far as I know there is nothing we can do about it until https://github.com/docker/hub-feedback/issues/467 is fixed. I added some information about the problem ontop of the README in #1269

**Comment by dsander** [comment]
Docker fixed the issue.
