### ISSUE TITLE
Huggin on The Changelog!

### ISSUE THREAD

**Issue by jerodsanto** [cantino/huginn#1271]
Howdy from [The Changelog](https://changelog.com/)!

@cantino we'd love to have you on the show sometime soon. Feel free to send an email to editors@changelog.com to coordinate.

If you haven't heard of the show, The Changelog is a podcast published weekly that covers what's fresh and new in open source. You can listen to the show here https://changelog.com/podcast/ or here http://5by5.tv/changelog

Looking forward to hearing from you!

**Comment by cantino** [comment]
Thanks!  Sent you an email.
