### ISSUE TITLE
How to solve 502

### ISSUE THREAD

**Issue by restofworld** [cantino/huginn#1278]
502 Bad Gateway

nginx

How to solve this problem

**Comment by cantino** [comment]
It sounds like Huginn isn't running. How have you set it up?

**Comment by restofworld** [comment]
I have installed the huginn according to the manual, which was on AWS. But there are some steps that I don't know clearly.so, what I should do now?

**Comment by cantino** [comment]
You should see if it's running on the server by SSHing in and checking for the process in `top` or `htop`.  If it is running, perhaps nginx is misconfigured.  If it's not, then that's the problem and you'll need to start it.

Also, according to [the guide](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#ensure-your-huginn-instance-is-running), you can run `sudo rake production:status` to check the status.  What does that print out?

**Comment by restofworld** [comment]
I am a novice and my English is not very good, a lot of things do not understand, do you have any social tools WeChat, can I ask you?

**Comment by cantino** [comment]
Hey @restofworld, I don't have time tonight, but you can ask in our [Gitter room](https://gitter.im/cantino/huginn).

**Comment by restofworld** [comment]
run: huginn-jobs-1: (pid 3486) 5s; run: log: (pid 3279) 580s
run: huginn-web-1: (pid 3282) 581s; run: log: (pid 3281) 581s
run: huginn-dj2-1: (pid 3473) 36s; run: log: (pid 3283) 581s

**Comment by restofworld** [comment]
ok,thanks

**Comment by cantino** [comment]
That makes me think that the problem is that nginx is misconfigured.  If no one can help you in chat, I'll see if I can offer more suggestions soon.  Also, make sure that nginx is running and doesn't have any errors in its log.

**Comment by restofworld** [comment]
Thank you for your help, I have already solved the problem. But, I have another question here, I think is a problem of CSS, how should I solve it?

**Comment by restofworld** [comment]
This is my address ,you can have a look.
http://52.36.67.236:3000/

**Comment by cantino** [comment]
I think that you need to [compile assets](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#compile-assets).

**Comment by restofworld** [comment]
sudo -u huginn -H bundle exec rake assets:precompile RAILS_ENV=production
Doing this can solve a problem?

**Comment by cantino** [comment]
It may. Did it work for you?

**Comment by restofworld** [comment]
Sorry,im busying with other things these days.Thank you for your help,but it didn't work yet.

**Comment by dsander** [comment]
Hi @restofworld,

when you have time to give Huginn another try I recommend you start over and follow the [manual installation guide](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md) again. You mentioned that you tried to access via `http://52.36.67.236:3000/` which would explain nginx responding with 502s and the assets not being shown. Normally you would access huginn via port 80 and have unicorn listening on a unix socket and not port 3000.

Feel free to open the issue again if you issue happens again.

**Comment by restofworld** [comment]
Hello there,I tried again, the problem still exists. I do not know how to solve. I like huginn, I hope for your help.
http://52.37.1.247:3000/

**Comment by dsander** [comment]
Did you follow the manual installation guide? If you did did you maybe forget to make changes to the [`Procfile`](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#install-init-script)?

**Comment by restofworld** [comment]
I was done in accordance with guidelines,but i don't kown how to changje the procifle!

**Comment by dsander** [comment]
My guess is you are using the default Procfile, which would explain huginn listening to port 3000.

Open the Procfile:
`sudo -u huginn -H editor Procfile`
Comment out (disable) [these two lines](https://github.com/cantino/huginn/blob/master/Procfile#L6-L7)
Enable (remove the comment) from [these lines](https://github.com/cantino/huginn/blob/master/Procfile#L24-L25)

After that continue with the guide, "Export the init scripts" will be the next step.

**Comment by restofworld** [comment]
Wow!It work well now,thank you very much.You are a nice and very professional.

**Comment by cantino** [comment]
:)

**Comment by dsander** [comment]
Great, glad it works!
