### ISSUE TITLE
Pass on URL to the next agent from WebsiteAgent

### ISSUE THREAD

**Issue by prathyush** [cantino/huginn#1279]
I'm trying a scenario where RssAgent talks to WebsiteAgent and the data scraped and sent through a TriggerAgent and eventually to SlackAgent.

I did some digging around but couldn't figure out how the URL fed to WebsiteAgent (via url_for_event) can be passed along to the next agent in the workflow. Is there a way Huginn allows to do this ?

**Comment by cantino** [comment]
Hey @prathyush.  If you use a `mode` of `merge`, it should send on the original event with additional data added.

**Comment by prathyush** [comment]
@cantino That did the trick. Thanks!.

**Comment by cantino** [comment]
Great!
