### ISSUE TITLE
TriggerAgent: access the matched value in the message

### ISSUE THREAD

**Issue by benkulbertis** [cantino/huginn#1283]
I'm attempting to write a trigger agent with the following source:
`{
  "expected_receive_period_in_days": "1",
  "keep_event": "true",
  "rules": [
    {
      "type": "regex",
      "value": "6:00 PM|6:30 PM|7:00 PM|7:30 PM|8:00 PM|9:30 PM",
      "path": "body"
    }
  ],
  "message": "This time is now present! '{{ match }}'"
}`

Essentially, I want to only include what the regex matched in the message. Is there a way to do this? I've tried using something like:

`This time is now present! '{% regex_replace \"6:00 PM|6:30 PM|7:00 PM|7:30 PM|8:00 PM|9:30 PM\" in %}{{ body }}{% with %}{{ match }}{% endregex_replace %}'`

but I get the entire 'body' section, not just the matched part of it. This confirms that the desired string is found in the sourced event, but I can't find a way to get it alone in liquid format in the message field.

Any help is appreciated. Thank you!

**Comment by cantino** [comment]
I think you may need to use an EventFormattingAgent.  See the `matchers` section.

**Comment by benkulbertis** [comment]
Thanks! That works!

**Comment by cantino** [comment]
Great!

**Comment by jedis00** [comment]
Is there an example somewhere of how to do this?
