### ISSUE TITLE
Feature Idea/Request: Colors for Agents

### ISSUE THREAD

**Issue by metachris** [cantino/huginn#1284]
First off, thanks for this great piece of software!

What do you think about this feature idea/request: Ability to set colors for agents, in order to easier distinguish between/group different types.

**Comment by cantino** [comment]
Hey @metachris, cool idea.  Did you see that Scenarios offer coloring?  Does that work, or would you still want it on individual agents too?

**Comment by metachris** [comment]
Hi! I've played a bit with scenarios and think they do fit quite well. Thanks for responsing, and keep up the good work!

**Comment by cantino** [comment]
Glad to hear it! Let us know if you have any other questions.
