### ISSUE TITLE
Get an text when a new eBay item is listed for a specific search

### ISSUE THREAD

**Issue by Rizonline** [cantino/huginn#1285]
Hi,
I am looking to hire a developer to customize the Huginn script to achieve the following task for me in real time:

Send me a text message when a new eBay item is listed for a specific search item that is listed at a price which is blow my set max price. 

I tried using IFTTT for this and although it worked, it has 2 main issues that cannot be overcome with that system.
1. The results are usually 15-20 minutes (or more) late.
2. IFTTT as a monthly quota of 100 text messages.

We can integrate Twilio or any other suggested third party sms gateway service. Please contact me if interested.

Thanks!

**Comment by dsander** [comment]
Hi @Rizonline,
this sounds like an interesting problem so solve. I added the `contractor wanted` label. I hope that helps to find someone to help. Apart from the agent configuration I recommend reducing `DELAYED_JOB_SLEEP_DELAY` to something lower then 10 seconds to make huginn feel more "real time".

**Comment by Rizonline** [comment]
Hi @dsander,
Perhaps you can do it for me...are you available?
Thanks!

**Comment by gdomod** [comment]
Website agent for parsing ebay, you just need to add Email or Pushbullet agent
```
{
  "expected_update_period_in_days": "2",
  "url": "http://www.ebay.com/sch/i.html?_from=R40&_trksid=p2050601.m570.l1313.TR0.TRC0.H0.Xpraq+300.TRS0&_nkw=praq+300&_sacat=0",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "title": {
      "xpath": "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"vip\", \" \" ))]",
      "value": ".//text()"
    },
    "price": {
      "xpath": "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"prc\", \" \" ))]//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"bold\", \" \" ))]",
      "value": "translate(., translate(.,'0123456789,.',''), '')"
    },
    "url": {
      "xpath": "//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"prc\", \" \" ))]//*[contains(concat( \" \", @class, \" \" ), concat( \" \", \"bold\", \" \" ))]",
      "value": ".//@href"
    }
  }
}
```

**Comment by cantino** [comment]
Thanks @gdomod!
