### ISSUE TITLE
EmailAgent Error Handling

### ISSUE THREAD

**Issue by metachris** [cantino/huginn#1286]
I've just encountered this error where an outgoing email is rejected by the SMTP host due to an invalid sender, but I got no error message in the UI. 

`EmailAgent` should somehow notify users if an error is encountered sending the email.

**Comment by cantino** [comment]
Good idea.  Do you have the Rails logs from when this happened by any chance?

**Comment by jevanpipitone** [comment]
I have sent a pull request that should address this issue.

**Comment by cantino** [comment]
Fixed in #1335.  Please let us know if the fix doesn't work.
