### ISSUE TITLE
CORS issue ?

### ISSUE THREAD

**Issue by jamsheer-thottathil** [cantino/huginn#1295]
How to set CORS headers in  Webhook Agent  .I am facing CORS issue while connecting webhook agent with angular JS application .Any solution for this.

**Comment by dsander** [comment]
Hi @jamsheer-citrus,

the `WebsiteAgent` supports a `headers` key, you can provide any header key -> value pair you like.

**Comment by jamsheer-citrus** [comment]
I need to handle with  Webhook Agent

**Comment by dsander** [comment]
Sorry totally misread your issue. Setting headers for the `WebhookAgent` is not possible at the moment, I believe you should be able to set the `Access-Control-Allow-Origin: *` in your nginx or apache config to allow XHR connections form all domains.

**Comment by jamsheer-citrus** [comment]
@dsander  thank you for your response
