### ISSUE TITLE
NodeRed looks interesting

### ISSUE THREAD

**Issue by alias1** [cantino/huginn#1296]
* https://github.com/node-red/node-red
* http://flows.nodered.org/
* http://nodered.org/

**Comment by r04r** [comment]
This does look very interesting. I love the editor they have, it is very nice. Other than that, it feels unpolished but looks promising. Huginn has many more integrations by default, for example. And it doesn't look like NodeRed persists the state of agents, so they lose their 'memory' when the node-red process is restarted. This makes stuff like scraping websites and reporting changes hard.

I'm sure there's more, but it does look very interesting. And that editor is damn sexy.

**Comment by alias1** [comment]
Immediate issue I saw was no users at all, completely open to the world. The editor is so pretty but. How's it licenced..? ;) :p

Sent from Outlook Mobile




On Mon, Feb 15, 2016 at 10:03 AM -0800, "r04r" <notifications@github.com> wrote:












This does look very interesting. I love the editor they have, it is very nice. Other than that, it feels unpolished but looks promising. Huginn has many more integrations by default, for example. And it doesn't look like NodeRed persists the state of agents, so they lose their 'memory' when the node-red process is restarted. This makes stuff like scraping websites and reporting changes hard.



I'm sure there's more, but it does look very interesting. And that editor is damn sexy.

**Comment by r04r** [comment]
@alias1 There is no authentication by default but you can enable that in the settings. It has user support, and you can even plug in your own authentication backend. http://nodered.org/docs/security.html

**Comment by r04r** [comment]
After some playing with node-red I also wound up just writing a mini-module that uses MySQL as a super simple key-value store. It seems pretty nice now.

**Comment by alias1** [comment]
Added to https://github.com/cantino/huginn/wiki/Similar-or-Complimentary-to-Huginn
