### ISSUE TITLE
Email from address be a variable.

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1305]
Currently send from email is defined in .env

``# The address from which system emails will appear to be sent.
EMAIL_FROM_ADDRESS=from_address@mydomain.com

Can this be something that can be defined in email agent. So if a weather agent gives out a event that I am emailing from its email agent, the from email be weather@mydomain.com. If there is a price alert from website agent & trigger agent then have another email agent sending as price@mydomain.com.  

This would be possible if someone is using mandrill or sendgrid etc not when using gmail. 

Maybe either have .env able to accept multiple email from address that appears in email agent as drop down option

EMAIL_FROM_ADDRESS1=price@mydomain.com
EMAIL_FROM_ADDRESS2=weather@mydomain.com

**Comment by xdirty** [comment]
Not hijack this thread from signallhill, but i had a question about emails as well.
I want to change the email address the email appears to be from to the received. i change the settings from the .env file below but nothing happens.

``# The address from which system emails will appear to be sent.
EMAIL_FROM_ADDRESS=from_address@mydomain.com

**Comment by cantino** [comment]
Moving conversation to #1307.
