### ISSUE TITLE
Can't restart with existing MySQL data

### ISSUE THREAD

**Issue by csu** [cantino/huginn#1306]
I originally ran Huginn using:

    docker run --restart=always -v /data/huginn/mysql:/var/lib/mysql -d --env-file ~/huginn_env -p 3000:3000 cantino/huginn

I had to stop it recently. Upon running the above again, I get the following error from `docker log`:

    2016-02-18 06:04:21,346 CRIT Set uid to user 0
    2016-02-18 06:04:21,346 WARN Included extra file "/etc/supervisor/conf.d/bootstrap.conf" during parsing
    2016-02-18 06:04:21,346 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
    2016-02-18 06:04:21,346 WARN Included extra file "/etc/supervisor/conf.d/foreman.conf" during parsing
    2016-02-18 06:04:21,365 INFO RPC interface 'supervisor' initialized
    2016-02-18 06:04:21,365 CRIT Server 'unix_http_server' running without any HTTP authentication checking
    2016-02-18 06:04:21,365 INFO supervisord started with pid 1
    2016-02-18 06:04:22,368 INFO spawned: 'stdout' with pid 690
    2016-02-18 06:04:22,369 INFO spawned: 'bootstrap' with pid 691
    2016-02-18 06:04:22,377 INFO success: bootstrap entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
    2016-02-18 06:04:22,592 INFO spawned: 'mysqld' with pid 698
    2016-02-18 06:04:23,719 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
    2016-02-18 06:04:23,719 INFO success: mysqld entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
    bootstrap stdout | DATABASE_HOST=localhost
    bootstrap stdout | mysqld: available
    bootstrap stdout | mysqld: added process group
    bootstrap stdout | Starting mysql server...
    mysqld stderr | 160218 06:04:22 mysqld_safe Can't log to error log and syslog at the same time.  Remove all --log-error configuration options for --syslog to take effect.
    mysqld stdout | 160218 06:04:22 mysqld_safe Logging to '/var/log/mysql/error.log'.
    mysqld stdout | 160218 06:04:22 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
    bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | . bootstrap stdout | .2016-02-18 06:06:23,283 INFO exited: bootstrap (exit status 1; not expected)

(Note it ends with: `INFO exited: bootstrap (exit status 1; not expected)`)

Any ideas? I'm thinking it might be a permissions error with the MySQL database?

After a few tries, I also found the `DO_NOT_SEED` in the Docker README, so I tried adding that (I added `DO_NOT_SEED=DO_NOT_SEED` to the env file because the docs didn't really say what to set `DO_NOT_SEED` to besides just setting it to anything…). Still getting the same error.

**Comment by dsander** [comment]
Hi @csu,

when did you last pull the docker image? This might be related to #1243. I will try to have a look tonight if updating the image did not help.

**Comment by csu** [comment]
Hadn't pulled in maybe a week or so. Just pulled, restarted, and everything worked perfectly! Thanks, @dsander!
