### ISSUE TITLE
Email from address

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1307]
Currently send from email is defined in .env

``# The address from which system emails will appear to be sent.
EMAIL_FROM_ADDRESS=from_address@mydomain.com

Can this be something that can be defined in email agent. So if a weather agent gives out a event that I am emailing from its email agent, the from email be weather@mydomain.com. If there is a price alert from website agent & trigger agent then have another email agent sending as price@mydomain.com.

This would be possible if someone is using mandrill or sendgrid etc not when using gmail.

Maybe either have .env able to accept multiple email from address that appears in email agent as drop down option

EMAIL_FROM_ADDRESS1=price@mydomain.com
EMAIL_FROM_ADDRESS2=weather@mydomain.com

**Comment by virtadpt** [comment]
It would be handy, I'll admit.

(By the bye, why did you close the other ticket instead of reopening it?)

**Comment by signallhill** [comment]
I closed it by mistake. Was not sure if I opened it again it would get in line to be looked at again. I dont work in IT field and not familier with these systems. I learned Huginn by reading the instructions and posting here.

**Comment by cantino** [comment]
PR #1312 should allow this.
