### ISSUE TITLE
How to deploy Production mode on Mac

### ISSUE THREAD

**Issue by mdazmir** [cantino/huginn#1308]
I tried to run Huginn inside Docker but it's using too much memory and decided to run in natively on my Mac. I managed to install and run Huginn in development mode on my Mac Mini (OS X El Capitan) by following the instruction on this page: [Novice Setup Guide for Mac](https://github.com/cantino/huginn/wiki/Novice-Setup-Guide-for-Mac)

 To run in production mode, I tried to roughly follow this [guide](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md) but it seems that the source code contain a hardcoded path for the working directory pointing to /home/huginn/huginn.

Is it possible to run Huginn on production mode on Mac? And does production mode use less memory than development mode?

**Comment by dsander** [comment]
Hi @mdazmir,

I don't think running in production mode will reduce the RAM usage by a lot. You can try it by switching your local development to production like this:

Add these to your `.env` file:
```
RAILS_SERVE_STATIC_FILES=true
RAILS_ENV=production
```
Bundle to remove the unneeded `development` and `test` gems.
```
RAILS_ENV=production bundle install
```
Precompile the assets
```
bundle exec rake assets:precompile RAILS_ENV=production
```
then (re)start foreman.
