### ISSUE TITLE
I need more website agent html examples.

### ISSUE THREAD

**Issue by xdirty** [cantino/huginn#1309]
I have been trying to figure out how to extract data using the website agent, and i have successfully using json and xml but im still having trouble with regular html. The problem for has been no enough examples to study and not enough documentation. Does anyone know where i can view more examples on how to extract data from and html webpage and maybe some more documentation ?

**Comment by cantino** [comment]
I assume you've seen the ones on the wiki at https://github.com/cantino/huginn/wiki/Agent-configuration-examples?

**Comment by xdirty** [comment]
Yes that link helped me with json and xml. But there's barely any examples of extracting html

**Comment by cantino** [comment]
Do you have an example site you're trying to scrape?

**Comment by santoshgistto** [comment]
@cantino i have question how we can add the pagination to scrape the next page and for also reddit 
i am also trying to scrape website not succeeded here is the sample link http://simpleindianrecipes.com/

**Comment by xdirty** [comment]
Im trying to get the titles and links from http://newyork.backpage.com/buyselltrade/

Backpage has rss feeds but they update every few hours. I wanted to create my own website agent, extract all the titles then use a trigger agent to filter things im looking for .

I feel bad asking you for help again but i dont know where else to look. if theres anything guides or more examples on how to extract html with the webagent i would be glad to read it.

**Comment by cantino** [comment]
@xdirty, I recommend using SelectorGadget to come up with selectors.  For that page, according to SelectorGadget, `.cat a:nth-child(1)` would work for the links.

**Comment by cantino** [comment]
So something like this:

```
{
  "url": "http://newyork.backpage.com/buyselltrade/",
  "mode": "on_change",
  "type": "html",
  "expected_update_period_in_days": "10",
  "extract": {
    "title": {
      "css": ".cat a:nth-child(1)",
      "value": ".//text()"
    },
    "url": {
      "css": ".cat a:nth-child(1)",
      "value": "@href"
    }
  }
}
```

**Comment by cantino** [comment]
@santoshgistto, there was some discussion of this in #873

**Comment by xdirty** [comment]
Ok i downloaded selector gadget and i will play around with it. Thanks for the help

**Comment by xdirty** [comment]
Okay , i got everything working, SelectorGadget makes my life a lot easier. Another question. Is there a way that i can use the urls i have extracted with this agent and use them to visit and generate a description of each one ? Then combine them into one, that has title description and link ?

**Comment by cantino** [comment]
I think you could send them to a WebsiteAgent, extract the page title, and merge it into the incoming event, then combine them with a DataOutputAgent.

**Comment by gdomod** [comment]
`{
  "expected_update_period_in_days": "2",
  "url": "http://www.fussballgucken.info/fussball-alle-termine",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "date": {
      "xpath": "//*[contains(@class,\"time\")]",
      "value": "concat(../../preceding-sibling::*[contains(@class,\"date\")][1]//text(), \" \",.//text())"
    },
    "wettbewerb": {
      "xpath": "//*[contains(@title,\"Infos zu diesem Wettbewerb\")]",
      "value": ".//text()"
    },
    "match": {
      "xpath": "//*[contains(@class,\"matches\")]",
      "value": "concat(.//*[contains(@class,\"text-right\")][1]//text(),\" - \",.//*[contains(@class,\"text-left\")][1]//text())"
    },
    "screen": {
      "xpath": "//*[contains(@class,\"screen\")]",
      "value": ".//text()"
    }
  }
}`

OR

`{
  "expected_update_period_in_days": "2",
  "url": "IAMSORRYURL",
  "type": "text",
  "mode": "on_change",
  "extract": {
    "img": {
      "regexp": "^(?m).*?aditem-image.*?((data-imgsrc=\"(?<url>.+?)\")|(class=\"(?<url>.*?)\")).*?(?-m)$",
      "index": "url"
    },
    "title": {
      "regexp": "^(?m).*?aditem-main.*?<a.*?>(.+?)<\/a>.*?(?-m)$",
      "index": "1"
    },
    "url": {
      "regexp": "^(?m).*?aditem-main.*?<a.*?href=\"(.+?)\".*?(?-m)$",
      "index": "1"
    },
    "description": {
      "regexp": "^(?m).*?aditem-main.*?<p>(.+?)<\/p>.*?(?-m)$",
      "index": "1"
    }
  }
}`

**Comment by christopherdurr** [comment]
I think this issue should be closed, seems like it's been addressed

**Comment by cantino** [comment]
Agreed
