### ISSUE TITLE
HTTP Basic Auth 

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1313]
Is there a way to implement HTTP Basic Auth in huginn. 

I am following https://www.digitalocean.com/community/tutorials/how-to-set-up-http-authentication-with-nginx-on-ubuntu-12-10

But where should step 3 go? Or is it even possible to do?

**Comment by dsander** [comment]
This should work without problems, you can put the `auth_basic*` configuration directives inside the [server](https://github.com/cantino/huginn/blob/master/deployment/nginx/huginn#L23) block of your Huginn nginx configuration file.

**Comment by signallhill** [comment]
Thanks worked beautifully. Is there anyother methods to this that you recommend?? I read in that this is not the best way to do it. What else can do something similar but better??

**Comment by dsander** [comment]
I am using the same way when I want to have Basic Auth for one of my applications and do not know of a different solution.

**Comment by signallhill** [comment]
Great Thanks
