### ISSUE TITLE
What does this error message mean? 

### ISSUE THREAD

**Issue by xdirty** [cantino/huginn#1314]
I had found something had terminated my huginn and when i relaunched it i starting getting this error .	

> Broken pipe @ io_write - <STDOUT> /home/pi/huginn/app/models/agent_log.rb:18:in `write'

**Comment by xdirty** [comment]
>                         Broken pipe @ io_write - <STDOUT>
/home/pi/huginn/app/models/agent_log.rb:18:in `write'
/home/pi/huginn/app/models/agent_log.rb:18:in `puts'
/home/pi/huginn/app/models/agent_log.rb:18:in `puts'
/home/pi/huginn/app/models/agent_log.rb:18:in `log_for_agent'
/home/pi/huginn/app/models/agent.rb:212:in `log'
/home/pi/huginn/app/concerns/dry_runnable.rb:61:in `log'
/home/pi/huginn/app/models/agent.rb:216:in `error'
/home/pi/huginn/app/jobs/agent_check_job.rb:11:in `rescue in perform'
/home/pi/huginn/app/jobs/agent_check_job.rb:5:in `perform'
/usr/local/lib/ruby/gems/2.2.0/gems/activejob-4.2.5.1/lib/active_job/execution.rb:32:in `block in perform_now'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:117:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:117:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:343:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/usr/local/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/usr/local/lib/ruby/gems/2.2.0/gems/activejob-4.2.5.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:441:in `instance_exec'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:342:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:342:in `block in simple'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:497:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:497:in `block in around'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:343:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/usr/local/lib/ruby/gems/2.2.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:23:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/lib/ruby/gems/2.2.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/usr/local/lib/ruby/gems/2.2.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:43:in `block in tag_logger'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:68:in `tagged'
/usr/local/lib/ruby/gems/2.2.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:43:in `tag_logger'
/usr/local/lib/ruby/gems/2.2.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:441:in `instance_exec'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:342:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:342:in `block in simple'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:497:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:497:in `block in around'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
/usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/lib/ruby/gems/2.2.0/gems/activejob-4.2.5.1/lib/active_job/execution.rb:31:in `perform_now'
/usr/local/lib/ruby/gems/2.2.0/gems/activejob-4.2.5.1/lib/active_job/execution.rb:21:in `execute'
/usr/local/lib/ruby/gems/2.2.0/gems/activejob-4.2.5.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:34:in `perform'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/backend/base.rb:100:in `block in invoke_job'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/backend/base.rb:97:in `invoke_job'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:224:in `block (2 levels) in run'
/usr/local/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
/usr/local/lib/ruby/2.2.0/timeout.rb:98:in `call'
/usr/local/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:224:in `block in run'
/usr/local/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:223:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:300:in `block in reserve_and_run_one_job'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:300:in `reserve_and_run_one_job'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:207:in `block in work_off'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:206:in `times'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:206:in `work_off'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:169:in `block (4 levels) in start'
/usr/local/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:168:in `block (3 levels) in start'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:167:in `block (2 levels) in start'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:166:in `loop'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:166:in `block in start'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/plugins/clear_locks.rb:7:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `block in add'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/lib/ruby/gems/2.2.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:165:in `start'
/home/pi/huginn/lib/delayed_job_worker.rb:6:in `run'
/home/pi/huginn/app/concerns/long_runnable.rb:71:in `block in run!'

>

**Comment by dsander** [comment]
Hi @xdirty, 

how are you running Huginn? `broken pipe` looks like you redirect STDOUT so some process which closes the pipe.

**Comment by xdirty** [comment]
Im running hugginn on a raspberry pie with 1gb ram, on raspbian with one worker.  I had had ice weasel on and i think the raspberry pie ran out of ram and thay caused this. I restarted the pie and this issue seems to have gone away.  I could be wrong, im not sure what happened

**Comment by dsander** [comment]
That could be it, did runit automatically restart the process?

**Comment by xdirty** [comment]
Im sorry im not sure what you mean, im very new to linux and huginn. huggin stopped running completely if thats what you are asking.

**Comment by dsander** [comment]
I assumed you installed huginn using the [manual installation guide](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md), that would make runit manage the huginn processes and should automatically restart huginn when it died due to an error.

**Comment by xdirty** [comment]
oh i have a local installation so i cant even access huginn outsite of my network. it definitely doesn't restart it self.

**Comment by dsander** [comment]
I see, are you starting huginn with `foreman start`? As far as I know foreman does not automatically restart processes.

**Comment by cantino** [comment]
I'm going to close this since we haven't heard back.

**Comment by TLX1126** [comment]
Did you solve this problem？I also encountered this problem and I am a beginner
