### ISSUE TITLE
Integrate mailing list software with huginn.

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1317]
I recently looked into some mailing list managers like phplist,mailman, dadamail etc. And thought it would be really nice if something like that could be integrated with huginn. Or even be part of the installation of huginn.

**Comment by cantino** [comment]
What did you have in mind?

**Comment by signallhill** [comment]
I was just thinking since Huginn is all about getting information through agents and then getting alerts through emails. Right now its confined to either people who know what they are doing with all these different systems or someone who has lots of time and  to go through and learn. But that leaves behind people who are neither. 
So instead of having others get down and dirty with getting their own server and doing all that why not just give them the alerts. People who have Huginn may have friends, colleagues that may have good use of these information. But manually adding email address and deleting them will be time consuming and un-huggin like, also dont want to spam. So why not just integrate a mail list manager and let it take care of it. I didnt even know there were so many open and free out there.

I have seen some discussion on scenarios exchange. Maybe in the longterm do scenarios exchange and if there are some scenarios that you guys find will helpful to lots of people set it up as a service.

I have followed this project for a while and this is just amazing. I dont know the technical aspect of this but wanted to share.

**Comment by cantino** [comment]
It's an interesting idea @signallhill, thank you.  It would probably make the most sense if someone ran a separate mailing list system and then let people subscribe to Huginn scenarios that they ran.

**Comment by signallhill** [comment]
Yes. I saw that MailChimp able to do this. Sorry, I am learing myself all this things.
