### ISSUE TITLE
i cant access on browser

### ISSUE THREAD

**Issue by screamolic** [cantino/huginn#1318]
error nginx

**Comment by signallhill** [comment]
Try restarting your instance. It usully works for me.

**Comment by dsander** [comment]
@screamolic It would be nice if you could be more specific, if you used the manual installation guide we have a [troubleshooting](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#troubleshooting) section at the bottom of it.

**Comment by screamolic** [comment]
i will try again ..

**Comment by screamolic** [comment]
i got error

Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "reconnect"=>true, "database"=>"huginn_development", "pool"=>20, "username"=>"huginn", "password"=>"huginndb", "host"=>nil, "port"=>nil, "socket"=>"/var/run/mysqld/mysqld.sock", "strict"=>false}

**Comment by dsander** [comment]
When you created the database user like in the [database](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#4-database) section you need to change `DATABASE_NAME` in `.env` to `huginn_production`

**Comment by screamolic** [comment]
i miss that. thanks
