### ISSUE TITLE
Feature Code Agent

### ISSUE THREAD

**Issue by gdomod** [cantino/huginn#1320]
can we add a code agent ? please :)

I could well imagine, that we have a parameter for binaries 
ilke /usr/sbin/python

and the code block with the prgramm code
the return value could the agent response and must be return by code as json string

**Comment by dsander** [comment]
Did you have a look at the `ShellCommandAgent`? You can run any command you like with it.

**Comment by cantino** [comment]
See also the JavaScriptAgent.

**Comment by gdomod** [comment]
JavaScriptAgent has to few function (like xmlhttprequest)
and 
it would be nice i can edit online my scripts, with shellcommanderagent i need to upload the script and i use a docker container. its not so funny to edit

**Comment by cantino** [comment]
It would be interesting if we could extend our embedded JavaScript / CoffeeScript agent to be able to make web requests.

**Comment by Warloxx** [comment]
I just created an agent chain to create an OAuth token, and refresh it when expired, for the google API. I first tried the JS Agent but also noticed that things like xmlhttprequest are not supported. So I could get it done with PostAgent but I think it could be way more efficient with the JS Agent.

A bit unrelated, but the responses from the Post Agent are always provided as a string in the body field, even if the response header "Content-Type" says its "application/json". So I always need another JS Agent to convert the json string to an object I can index in other agents processing the data.

**Comment by cantino** [comment]
@Warloxx you can also use the website agent to parse the JSON string coming out of the PostAgent.  You're correct that it just emits its raw response body.

And I'd be supportive if you want to add xmlhttprequest support to the JavaScript agent.

**Comment by Warloxx** [comment]
I'll check out the website agent.

Unfortunately I have NO experience with Ruby or V8. So I probably won't attempt it. But you'll never now. Maybe I get bored one time and read up on ruby :)

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you'd like to discuss further.
