### ISSUE TITLE
NO css loading

### ISSUE THREAD

**Issue by somadona** [cantino/huginn#1324]
I have successfully installed Huginn but as image attached no css is loading although functions looks to be working.
![2016-02-29_3-32-02](https://cloud.githubusercontent.com/assets/17308512/13383633/1b7144d8-de95-11e5-9043-ba3c9b388254.jpg)

Can you please tell me what is wrong ?

**Comment by cantino** [comment]
You likely need to compile assets.  How did you install Huginn?  Via the https://github.com/cantino/huginn/blob/master/doc/manual/README.md guide?

**Comment by somadona** [comment]
Yes did exactly as in the guide above.

**Comment by somadona** [comment]
I have that messages while compiling ruby after command "make -j`nproc`"

Failed to configure -test-/win32/console. It will not be installed.
configuring -test-/win32/dln
Failed to configure -test-/win32/dln. It will not be installed.
Failed to configure -test-/win32/dln/empty. It will not be installed.
configuring -test-/win32/fd_setsize
Failed to configure -test-/win32/fd_setsize. It will not be installed.

**Comment by dsander** [comment]
This looks like you are running on windows? We only support *NIX operating systems for the manual installation guide. I recommend you have a look at [out docker images](https://github.com/cantino/huginn/tree/master/docker).

**Comment by somadona** [comment]
NO I have installed on Ubuntu 14

**Comment by dsander** [comment]
I see, you might have the same problem as described in [this issue](https://github.com/cantino/huginn/issues/1278#issuecomment-188136688).

**Comment by somadona** [comment]
@dsander Thank you your reference solution fixed it :)

**Comment by dsander** [comment]
Great, glad it works.

**Comment by cantino** [comment]
@somadona Do you have a suggestion on where we could add a warning to the docs to make this clearer?

**Comment by somadona** [comment]
@cantino Sure I recommend make the following change on here: 
https://github.com/cantino/huginn/blob/master/doc/manual/installation.md

Install Init Script
Huginn uses foreman to generate the init scripts based on a Procfile
Edit the Procfile and choose one of the suggested versions for production:
sudo -u huginn -H editor Procfile

To be:
Install Init Script
Huginn uses foreman to generate the init scripts based on a Procfile
Edit the Procfile and choose one of the suggested versions for production:
sudo -u huginn -H editor Procfile
Comment out (disable) these two lines
web: bundle exec rails server -p ${PORT-3000} -b ${IP-0.0.0.0}
jobs: bundle exec rails runner bin/threaded.rb

Enable (remove the comment) from these lines
# web: bundle exec unicorn -c config/unicorn.rb
# jobs: bundle exec rails runner bin/threaded.rb

**Comment by cantino** [comment]
Thanks @somadona, @dsander just made these changes.
