### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1327]
Trying to install new instance of Huginn with Ubuntu 14.04

when i get to here

sudo -u huginn -H bundle exec rake db:seed RAILS_ENV=production SEED_USERNAME=admin SEED_PASSWORD=yourpassword

get error 

user admin@example.com already exist. not seeding

If I move on and do all the steps. The website gives Bad Request error.

**Comment by cantino** [comment]
If you pull from master, I believe @dsander recently fixed this.

**Comment by dsander** [comment]
Bad request probably means that unicorn did not start. @signallhill Did you check the  [logs](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#troubleshooting)?

**Comment by signallhill** [comment]
I did the install again, making sure I follow all the instruction. I can see Huginn login page, but

sudo -u huginn -H bundle exec rake db:seed RAILS_ENV=production SEED_USERNAME=admin SEED_PASSWORD=yourpassword

Said user admin@example.com already exist. not seeding.

I cannot login to the admin page. I am guessing this command would pull the master according to the instruction.

sudo -u huginn -H git clone https://github.com/cantino/huginn.git -b master huginn

**Comment by dsander** [comment]
Did you already seed the database before without providing the changed SEED_PASSWORD? We changed the seed script to not change existing users, if admin@example.com already exists. Try logging in with "admin" and "password".

**Comment by signallhill** [comment]
I just followed the instruction. Copy Paste. 

Yes user: admin password: password worked.
