### ISSUE TITLE
Setup Gmail with Email Digest Agent

### ISSUE THREAD

**Issue by elvetemedve** [cantino/huginn#1328]
I would like to use my Gmail account to send notifications from Huginn. 
I followed the [documentation](https://github.com/cantino/huginn/blob/master/.env.example) to configure the Docker container. Running the email digest agent does not report an error, but I haven't got any email. I also checked the `/app/log/production.log` file inside the container, but it was empty.
What did I do wrong? Why there is no error?

**Comment by cantino** [comment]
Hi @elvetemedve.

Do you have any messages in the Agent logs in the UI?  I assume you configured the ENV variables for the email username and password, etc?

**Comment by dsander** [comment]
@elvetemedve You access the logs with `docker logs <container name>`

**Comment by elvetemedve** [comment]
Hi @cantino,
The only message I see is this: `Sending digest mail to ******@gmail.com with events [2]`.

Hi @dsander,
I triggered the agent and watched the logs. I guess these are the relevant lines:
```
foreman stdout | 08:44:31 jobs.1 | 2016-03-04T08:44:31+0000: [Worker(host:ea13ecddd52f pid:1149)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=2018) RUNNING
foreman stdout | 08:44:31 jobs.1 | [ActiveJob] [AgentCheckJob] [5d2f54f2-90b8-4e82-b548-bc44ea55ef54] Performing AgentCheckJob from DelayedJob(default) with arguments: 5
foreman stdout | 08:44:31 jobs.1 | [ActiveJob] [AgentCheckJob] [5d2f54f2-90b8-4e82-b548-bc44ea55ef54] Performed AgentCheckJob from DelayedJob(default) in 24.14ms
foreman stdout | 08:44:31 jobs.1 | 2016-03-04T08:44:31+0000: [Worker(host:ea13ecddd52f pid:1149)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=2018) COMPLETED after 0.0282
foreman stdout | 08:44:31 jobs.1 | 2016-03-04T08:44:31+0000: [Worker(host:ea13ecddd52f pid:1149)] 1 jobs processed at 23.8401 j/s, 0 failed
```
However I don't see any email or SMTP related info.

**Comment by dsander** [comment]
That does not look like the agent attempted to deliver a mail, did the Digest Agent have event in its memory queue?

**Comment by elvetemedve** [comment]
@dsander It seems to be empty at the moment. 

I made few screenshot of the configuration. See it here: https://drive.google.com/folderview?id=0B2tXOm0gFdwed0tDZFVSQ3ZqSTg&usp=sharing
Can you spot any problem?

**Comment by dsander** [comment]
The configuration looks correct, when you re-emit the event of the RainNotifier it should be added to the email digest agens memory again. Running the digest agent afterwards should send an email, or at least show an error in the docker logs.

**Comment by elvetemedve** [comment]
They key was **re-emitting** the event of the Rain Notifier. At the time the event was created, the SMTP setup was wrong. I amened it later, but only re-run the Email Digest agent which did not do anything, because of the empty memory queue. 

So it works perfectly. 
Thank you for helping me.

**Comment by dsander** [comment]
Glad we could help!

**Comment by soiqualang** [comment]
Hi @elvetemedve , I also used Docker to deploy Huginn, but I don't know how to load my huginn env to Docker. I use:
`docker run --restart=always -it -e DO_NOT_SEED=true --env-file /home/docker/huginn/env.huginn -p 3000:3000 huginn/huginn`

But I alway get error. Can you help me?
Thank you^^

**Comment by elvetemedve** [comment]
Hi @soiqualang,
I don't see any obvious error with your command. Just one tiny improvement you can do is move the **DO_NOT_SEED** variable into the environment file.
I can't SSH into my home server remotely at the moment, so I will check how I did that in the evening.

**Comment by soiqualang** [comment]
@elvetemedve , thanks for your replying.
When I run that command, I just got this:
![t2](https://user-images.githubusercontent.com/2648020/56721345-df2f6700-676e-11e9-8be7-33775d2b56a4.png)
I also removed **DO_NOT_SEED**, it've showed the same result.

Sorry to bother you so much.

**Comment by elvetemedve** [comment]
@soiqualang The source of the problem is shown around the middle: 
```
Access denied for user 'root'@'localhost'
```
Looks like your connection settings to the MySQL database is incorrect. Did you follow the [setup guide on Dockehub](https://hub.docker.com/r/huginn/huginn/)?

**Comment by elvetemedve** [comment]
@soiqualang I have created the bash command alias below to update/setup Huginn via Docker.
`alias update-huginn='sudo docker rm huginn; sudo docker pull huginn/huginn; sudo docker create -v /var/lib/huginn:/var/lib/mysql -p 3000:3000 --env-file="$HOME/huginn.env" --name=huginn huginn/huginn;'`
where `huginn.env` is based on the [sample file](https://github.com/huginn/huginn/blob/master/.env.example), but I removed the unused settings and added `DO_NOT_SEED=1` to the end of the file.

**Comment by dsander** [comment]
@elvetemedve Try removing the `DATABASE_PASSWORD=""` line your `.env` file. You might also need to delete your database volume to ensure the default password is used.
