### ISSUE TITLE
Monitoring Working Status of Agents

### ISSUE THREAD

**Issue by DreamFlasher** [cantino/huginn#1333]
I would like to get a notification if one of my agents is not working anymore. Is there an Agent which can create events if the status changes from Yes to No or an agent which can pull the information?

**Comment by dsander** [comment]
Hi @DreamFlasher,

we do not have an Agent for that at the moment, but it sounds like a good addition. Would you be interested in working on it?

**Comment by DreamFlasher** [comment]
Hi @dsander,

Well, of course I'd prefer if it already would exist :D so when I tried to extend the rss agent to support variables (don't know the right term) I realized that it requires considerable amount of time to get started with the Ruby templating you use for the agents... If there would be a tutorial on how to write your own agent that would make it easier to get started for new contributers.

**Comment by dsander** [comment]
We have a [wiki page](https://github.com/cantino/huginn/wiki/Creating-a-new-agent) that should explain the basics, does that help?

**Comment by DreamFlasher** [comment]
Nice! That's definitely helpful. How would I retrieve a list of all Agents from one agent? How do I access the info if they are working or not? Would I do that via a DB query?

**Comment by cantino** [comment]
From within an Agent, `user.agents` should be all of the owning User's Agents.  You could loop over them and call `working?` on each one.

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions or want to work on this change.
