### ISSUE TITLE
Agent cloning for Users...

### ISSUE THREAD

**Issue by nineralpha** [cantino/huginn#1339]
I have Huginn deployed on ubuntu on my laptop.. i want to clone all agents of admin user for every new user.... can anyone help me with the query???

**Comment by dsander** [comment]
Hi @nineralpha,

you could put all your agents into a scenario and export it. Then on every new you create import the scenario.

**Comment by nineralpha** [comment]
O yes.. Thanks man that may help. i am going to try it

**Comment by cantino** [comment]
I'm going to close this.  Please reopen if you have more questions!
