### ISSUE TITLE
Consider Treant for Agent Diagram

### ISSUE THREAD

**Issue by darrencauthon** [cantino/huginn#1341]
I was looking for a visualization tool and I came across Treant.  I'm not going to use it for what I need, but it reminded me of the Huginn agent visualization.  I've found that the more agents I have, the more I look at that tree tool.

Treant offers the same sort of tree visualization as Huginn has, but... it seems to have more options (hide/show, multiple buttons, etc) and might make it possible to add a bit more information to the diagram.  

I'm a little curious as to how well it might work.  If switching to a library is a definite "no" then I won't waste my time.  But if it's a "maybe" then I might through something together and see if it's a good fit.  

Thoughts?

![screenshot_030916_090552_am](https://cloud.githubusercontent.com/assets/148768/13639384/20db13de-e5d6-11e5-9230-5378b58bc57d.jpg)

**Comment by cantino** [comment]
Hey @darrencauthon.  Looks interesting.  I wonder if it's as flexible as our SVG output?  Also, can it handle loops?

**Comment by darrencauthon** [comment]
@cantino I'm not sure.  I think it might actually be more flexible, at least when it comes to using vertical space. 

I have 70-something agents now, and when I view my diagram it stretches far to the right.  I bet a library aware of horizontal space limits might be able to display them as discrete units of nodes, but sometimes down instead of right.

Looping... I'm not sure.  But I'll have to see how Huginn handles that today, I don't have looping agents. :smile:

Anyway, I'm curious, and you didn't yell **NO**, so I'll pop a pull request with some sort of general idea and see where it goes from there.

**Comment by elijah** [comment]
Has anybody looked into using something like graphviz to do the layout and
produce something reasonable?

--e

**Comment by darrencauthon** [comment]
@elijah I've never heard of that, do you have a small screenshot or something to compare?  Mayb ethat would be a better approach, if I were to go down this road.

**Comment by dsander** [comment]
@elijah Huginn currently uses graphviz when `USE_GRAPHVIZ_DOT` is [configured](https://github.com/cantino/huginn/blob/master/.env.example#L166-L169) in the `.env` file.

#1019 looks like an interesting approach to extend the current diagram.
