### ISSUE TITLE
Use multiple SMTP server.

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1346]
Is it possible to add the ability to choose from multiple SMTP servers in email agent? Either add it to the .env and choose in the agent or just enter in the agent to override default?

So low volume sends can be done through gmail which have daily limites.

Do high volume sends from email service.

**Comment by cantino** [comment]
At the moment, you'd have to update the .env file and restart.  This might be tricky to change dynamically.  Why?

**Comment by signallhill** [comment]
1. I am using regular email host smtp. It has limits like hourly send and daily send limits. Not always but sometimes those limits stop the emails in Huginn. I have couple of email agents that cause this. So instead of using all emails with another service wanted to see if using multiple smtp could be an option. 

2. There are also instances where the email host is down. Then doing SSH and then changing .env then restart, you have to be in front of laptop of desktop. **If that could be brought in the front end then it is brower accessible and can easily be done in a mobile phone. **

**Comment by dsander** [comment]
I think your best option would be a email service that does not have rate limits. http://www.mailgun.com lets you send 10000 mails for free every month. They do not seem to have a SLA, but it is a paid service i guess the uptime will be pretty good. Overcome downtime or connection issues you could setup [a local SMTP relay](https://community.rackspace.com/products/f/28/t/63).
Even if Huginn would let you configure the SMTP settings via the browser a restart would still be required to propagate the changed settings to the background workers.

**Comment by signallhill** [comment]
Ok I will do that. Thanks

**Comment by signallhill** [comment]
"Even if Huginn would let you configure the SMTP settings via the browser a restart would still be required to propagate the changed settings to the background workers"

Restarting can be done from the browser and/or apps of the service. I use digitalocean that I can restart from an mobile app. 

If I know the agents that need separate SMTP I would use that going forward.

**Comment by cantino** [comment]
I'd recommend using a reliable SMTP provider instead of trying to customize Huginn.

**Comment by signallhill** [comment]
Ok thanks
