### ISSUE TITLE
Help with update procedure

### ISSUE THREAD

**Issue by vx28643** [cantino/huginn#1349]
Hi,

I'm trying to follow your manual update procedure found [here](https://github.com/cantino/huginn/blob/master/doc/manual/update.md), however, I'm getting an error:
```
root@huginn:/home/huginn/huginn# sudo -u huginn -H git checkout -- db/schema.rb Procfile
error: pathspec 'db/schema.rb' did not match any file(s) known to git.
```
The update procedure worked for me in the past but if 'db/schema.rb' was removed or renamed then perhaps the update instructions also need updating.

What can I do about this and complete the update of my Huginn install?

Thanks for any assistance!

**Comment by dsander** [comment]
Hi @vx28643,

you are right, we removed `db/schema.rb` from git and forgot to update the instructions. I will do that tonight.

For now this command should work:
```
sudo -u huginn -H git checkout -- Procfile
```
Afterwards continue with the update like you did before.

**Comment by vx28643** [comment]
Thank you! That got me past the issue and I was able to update.

Just one note:

when I got to this part:
`sudo -u huginn -H bundle exec rake db:migrate RAILS_ENV=production`

I got this error:
```
Could not find activesupport-4.2.5.2 in any of the sources
Run `bundle install` to install missing gems.
```

so I did `bundle install` (as root) and got this warning:
```
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as
root will break this application for all non-root users on this machine.
```

I suppose I should have done: `sudo -u huginn bundle install` ?

Anyway, not sure if this `sudo -u huginn bundle install` is something that could/should be added to the update instructions or not, and if `sudo -u huginn bundle install` was correct.

Cheers.

**Comment by dsander** [comment]
Bundling is mentioned as the first step in [4. Install gems, migrate and precompile assets](https://github.com/cantino/huginn/blob/master/doc/manual/update.md#4-install-gems-migrate-and-precompile-assets), `sudo -u huginn bundle install` should work too but it will install gems that are not needed in production.

**Comment by vx28643** [comment]
Thanks for the clarification, and assistance. Closing the issue :)
