### ISSUE TITLE
Schedule: Every 30 Sec?

### ISSUE THREAD

**Issue by sonontse** [cantino/huginn#1353]
Is there any way to increase the schedule internals down to 30 seconds?  I have some webagents setup to pull data from an API (within the API's rate limit) and would like to pull it more frequently.  Thanks.

**Comment by dsander** [comment]
Hi @sonontse,

you can achieve that by using a `SchedulerAgent` which triggers your `WebsiteAgents` to run. When you need them to run more frequently then every 15 seconds you need to set `ENABLE_SECOND_PRECISION_SCHEDULE` to `true` in your `.env` file.

**Comment by sonontse** [comment]
Awesome! Works like a charm

**Comment by dsander** [comment]
Glad I could help :smile:
