### ISSUE TITLE
Javascript Agent does not respect timezone

### ISSUE THREAD

**Issue by elvetemedve** [cantino/huginn#1355]
When I set the "**TIMEZONE**" environment variable to a zone other than **the one set on the host**, GUI will reflect the changes, but when a `Date` object is created from a **Javascript Agent, it will use the time zone of the host** machine instead of the application.

Steps to reproduce the issue:

1. Set up a docker container following this guide https://github.com/cantino/huginn/blob/master/docker/multi-process/README.md and set the `TIMEZONE=Budapest` environment variable too. 
1. Start the application
1. Create a new Javascript Agent, give it a name like `test`, and put the following lines to the code field:

    ```javascript
    Agent.check = function() {
        var date = new Date();
        this.createEvent({ 'time': date.getHours() + ':' + date.getMinutes()  });
    };
    Agent.receive = function() { 
    };
    ```
1. Click on the **Dry Run** button twice.

You will get a time which is in **UTC**. The expected time should be in **UTC+1** (Europe/Budapest zone).

A quick workaround is to run `sudo dkpg-reconfigure tzdata` inside the Docker container and restart it after that.

**Comment by dsander** [comment]
Thanks for reporting the issue and pointing in the right direction @elvetemedve . It looks like setting the `TZ` environment variable has the same effect as configuring the timezone system wide. Would you mind testing the change I made in #1356?

**Comment by elvetemedve** [comment]
@dsander I've tested your changes and I can confirm that it works well. Well done. :+1:

**Comment by dsander** [comment]
@elvetemedve Thanks for verifying the fix works!
