### ISSUE TITLE
scheduler agent runs 1 hour later

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1357]
Since the daylight saving change, my scheduler agent runs 1 hour later. So 1pm runs 2pm

**Comment by signallhill** [comment]
Running in digitalocean Ubuntu 14. Ubuntu shows EST correct time, and .env also has Eastern time.

**Comment by dsander** [comment]
Does restarting your Huginn instance help? I could imagine that the scheduler did not pick up the DST time change.

**Comment by signallhill** [comment]
It still does that. I have restarted.

**Comment by dsander** [comment]
I did some tests. My scheduler is set up like this:
```
{
  "action": "run",
  "schedule": "0 7 * * *"
}
```
In `.env` I have `TIMEZONE="Eastern Time (US & Canada)"` and the scheduler seems to have run at the correct time: `2016-03-18 07:00:08 -0400`

Not sure if it is related but c48ff63e7a96260540f9399201cbd7a23d65c9fa might have fixed to issue you are having.

**Comment by signallhill** [comment]
I just changed the time on my scheduler. It must be something with my system.
