### ISSUE TITLE
Trigger Agent Rules 

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1358]
I have a trigger agent that has 2 rules out of which any one can match to trigger. It is possible to add a tag to know which one triggered. For example add line below path with tag_name and add_to.
tag_name: could be any thing
add_to: title or description or any other property

"must_match": "1",
  "rules": [
    {
      "type": "regex",
      "value": "something",
      "path": "title"
**      "tag_name":"Rule 1 triggered"
      "add_to":"title"**
    },
    {
      "type": "regex",
      "value": "something",
      "path": "description"
**      "tag_name":"Rule 2 triggered"
      "add_to":"title"**
    }

**Comment by cantino** [comment]
Hey @signallhill, I don't think that's possible right now.  That'd be an interesting addition.

**Comment by cantino** [comment]
I'm going to close this.  Please reopen if you have more questions!
