### ISSUE TITLE
An agent to query another agent's memory

### ISSUE THREAD

**Issue by roylez** [cantino/huginn#1365]
I am trying to do location query in slack like described in the following link with huginn.

http://labs.earthpeople.se/2016/02/my-family-uses-slack/

So far I can get MQTT agent to work, but it does not emit a new event when slack webhook triggers it because the message is already in memory.

Is there a way to query MQTT agent's memory?

**Comment by cantino** [comment]
It sounds like we'd need to extend the slack or MQTT Agent's abilities.  Is there an Event that the MQTT agent could emit that would enable this?

**Comment by roylez** [comment]
If given a certain MQTT topic, it would be nice if MQTT agent emits the last message received matching this topic or pattern. 

But I am a little worried if this would feed duplicated information into User Location Agent.

**Comment by cantino** [comment]
You'd need a way to filter it, or turn it on or off.

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.
