### ISSUE TITLE
Use event data in all options

### ISSUE THREAD

**Issue by thiagotalma** [cantino/huginn#1368]
It would be very useful to set options to the agent hash using event data (interpolate_options in all hash fields).

For example, in WebsiteAgente you can use the data of the event to set the url to be requested. Yet another parameter should be used, "url_from_event".

Why not allow that any parameter can receive event data?

**Comment by cantino** [comment]
Hey @thiagotalma, sorry, I'm not fully understanding.  Could you provide an example?

Maybe options support Liquid formatting, which can access Event data via something like `{{ event.field }}`.

**Comment by thiagotalma** [comment]
Sorry, my English is "by Google Translate."  :wink: 

It should be simpler I give a real example. I exported a scenario, see here: http://pastebin.com/dqBtSWnp

Three agents.
The first is a WebsiteAgente that generates an event as JSON.
```JSON
{
  "expected_update_period_in_days": "2",
  "url": "https://graph.facebook.com/v2.5/14888888888/leadgen_forms?fields=id,name,page{name,access_token}&access_token={% credential fb_token %}",
  "type": "json",
  "mode": "all",
  "extract": {
    "form": {
      "path": "data[*]"
    }
  }
}
```
Event:
```JSON
{
  "form": {
    "id": "88888888665112",
    "name": "My Form",
    "page": {
      "name": "Page Example",
      "id": "154888697488888"
    }
  }
}
```

The second is also a WebsiteAgent, which uses the received event data to construct the URL.
But I need to move to the next agent some event data received. Then create a new key `page` in the hash, which looks like this:
```JSON
{
  "expected_update_period_in_days": "2",
  "url_from_event": "https://graph.facebook.com/v2.5/{{form.id}}/leads?fields=id,form_id,created_time,field_data&access_token={% credential fb_token %}",
  "type": "json",
  "mode": "on_change",
  "extract": {
    "lead": {
      "path": "data[*]"
    }
  },
  "page": "{{event.page.name}}"
}
```


The third agent sends an email with the event data received, but also with the extra data sent by the agent of the hash.
```JSON
{
  "subject": "New data - {{agent.options.page}}",
  "expected_receive_period_in_days": "1",
  "body": "{{event.data}}"
}
```
But as the field `page` is not parsed, it always returns empty.

I'm sorry if I still can not explain well. Let me know that I try again.

Cheers!

**Comment by cantino** [comment]
I think I follow.  Could you add an EventFormattingAgent to generate the page key and then send it to your WebsiteAgent with a `mode` of `merge`?  If not, we may need to add templating into the WebsiteAgent, like the PostAgent does.

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.
