### ISSUE TITLE
Coveralls

### ISSUE THREAD

**Issue by cantino** [cantino/huginn#1375]
@knu or @dsander, did you turn this back on?  I didn't, as far as I know.  Do you like it?  I'm finding it a bit annoying.

**Comment by dsander** [comment]
I didn't, at first I was happy to get coverage reports again, but I agree it gets annoying. Don't they support sending the coverage report as a PR status?

**Comment by cantino** [comment]
Humm, not sure how it turned back on, but I just changed it to the following:

<img width="300" alt="screen shot 2016-03-27 at 2 44 00 pm" src="https://cloud.githubusercontent.com/assets/83835/14067992/680ff5a0-f42a-11e5-8b1b-c8ee14535ab8.png">

**Comment by cantino** [comment]
We'll see if we like this better.

**Comment by dsander** [comment]
Nice!

**Comment by thiagotalma** [comment]
Oh God! Thanks!!
That annoying feature!
