### ISSUE TITLE
failed on installing

### ISSUE THREAD

**Issue by screamolic** [cantino/huginn#1378]
much problem on installing.
1. update structure url git .
2. some gem can't download while using command bundle install.

**Comment by screamolic** [comment]
im using debian.

**Comment by cantino** [comment]
Hi @screamolic. Are you following our installation guide?

**Comment by screamolic** [comment]
yes. im following this.
https://gist.github.com/mjhea0/b6b58eefc38985380ff9

**Comment by screamolic** [comment]
does huginn support post to blogger ?

**Comment by screamolic** [comment]
i got another error with tutorial manual installation.

root@ubuntu-512mb-nyc3-01:/home/huginn/huginn# sudo bundle exec rake production:status
rake aborted!
Errno::ENOMEM: Cannot allocate memory - which
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'
/home/huginn/huginn/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'
/home/huginn/huginn/lib/tasks/production.rake:11:in `runit_installed'
/home/huginn/huginn/lib/tasks/production.rake:27:in `block (2 levels) in <top (required)>'
Tasks: TOP => production:status => production:check
(See full trace by running task with --trace)

**Comment by dsander** [comment]
Hi @screamolic, 

this error indicates that your server ran out of RAM. We [recommend](https://github.com/cantino/huginn/blob/master/doc/manual/requirements.md#memory) at least 512MB RAM plus the same amount of swap.

**Comment by screamolic** [comment]
thanks

**Comment by cantino** [comment]
I'm going to close this.  Please reopen if you have more questions!
