### ISSUE TITLE
Website Agent or else to monitor simple up/down website, help needed to configure

### ISSUE THREAD

**Issue by hcampan** [cantino/huginn#1379]
Hi all,

First, thanks to all of you who participate and to @cantino for the great job. Huginn is geting nicer and nicer. I also get progressively better at using it. Here is where I could use your help.

I've search and seen in previous post/issues a website health agent was a tought of idea. From what I know, it is not yet implemented. Or is it ?.

I found a way by using : 
"Shell Agent" (curl website) + "Change Detector Agent" (OK 200/or other) + "Email Agent" (to myself)

Is there a nicer/easier way to do that ? Using website agent may be. I saw something about liquid templating ("status: HTTP status as integer. (Almost always 200)") which seems to be usable but I don't understand how to.

Can someone point me to an example ? I'm sure someone must already be using this.

@cantino, may be that could go into the wiki ?

Thanks

Hubert

**Comment by cantino** [comment]
Hey @hcampan, would @darrencauthon's Http Status Agent (added in https://github.com/cantino/huginn/pull/1209) work for you?

**Comment by darrencauthon** [comment]
I use Huginn for this, set up the same way. A http status agent pointed at a URL I want to monitor, every five minutes. A change detector for the status, and alert to send to my phone. 

So if a site goes down, I get a notice, and when it comes back I get a second notice. 

It's working well. The only thing I want to change is to use a JavaScript agent to make it a little smarter. A couple times a week I might get a 200 => no response => 200, which I suspect is a fail with my server than the target. I'd like 200, no response, no response to throw. But it goes 200, 500, I want that message immediately. 

But anyway, the basic functionality can be had with Huginn, good luck!

**Comment by hcampan** [comment]
@cantino, thanks, yes it did. I updated Huginn (a first for me) to get it.

@darrencauthon, thank you for this agent ! A lot "cleaner" then "Shell Agent".

Pushing the concept a little :
From what I understand, we do have to create for each website a "ChangeDetectorAgent" as it isn't "thread aware" and cannot receive events from different "Http Status Agent"s. Would it be possible to save one step, zap the "ChangeDetectorAgent" and add in your "Http Status Agent" an "on_change_create_event" option?

**Comment by darrencauthon** [comment]
Hmmm... perhaps an option that said "Only fire an event on status change?"

Hmmm... I like the idea!

Darren Cauthon
darren@cauthon.com

**Comment by darrencauthon** [comment]
I can see two concrete changes to make to the Http Status Agent from this:

- [ ] Add an option to store the last result in memory, and only report a new event if the status changes. 

This will prevent the flood of events, requiring a change agent to alert for changes.

- [ ] Add an option to require the last 1-X changes to force an event change.  

Using this agent for a while, I've seen that it may have an occasional blip where the Huginn server fails to retrieve the page, resulting in a false error.  It might be a better monitoring agent if it required TWO fails before sending an alert.  I've also seen this behavior in professional monitoring services.

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.

**Comment by darrencauthon** [comment]
Closed because I think it's done. @hcampan you should be able to use this dedup feature in the latest huginn.

**Comment by tru2dagame** [comment]
@darrencauthon I've tried dedup agent. It seems I can't trigger a event after 1-x changes. Dedup seems to reduce duplication, can't trigger when duplicated.

**Comment by darrencauthon** [comment]
@tru2dagame What are you trying to do?

There is an option in the HttpStatus agent, changes_only, that might get you what you need?  With it set to true, the http status agent will fire an event only when the status code changes.

**Comment by tru2dagame** [comment]
Hi @darrencauthon, thanks for your reply.

Just want to do a simple healthcheck. `changes_only` isn't the exact option I want.

If the HttpStatusAgent has an option like the `retries` in docker, that would be perfect.
> https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by darrencauthon** [comment]
@tru2dagame I never went that far when I made it, as I didn't have a good idea in my head on how to present it in the documentation.  And I think there are some scenarios where this would not be a good fit, as a professional monitoring services have the luxury to be able to go green on 200 and red on !200.  For example, if a failing service keeps bouncing from 500 and 502, a service like pingdom will fail after 3 retries of anyting-but-200.  But http_status_agent just keeps track of the last status code response, so a new event won't get triggered unless the flucutating service can stay consistent on one code for 3 tries.

Maybe the agent could have been built more on the idea of 200 or not 200, but it wasn't and it's already been working this way for years.  But If retries was to be implemented, I like the way the docker documention shows it. The http_status_agent could have a "retries" option that defaults to 1, but allows someone to change it. 

Another way to implement this would be to turn changes_only to false, and then send all events to a javascript agent.  Program the javascript agent to pass the event from your http_status_agent after 3 successful 200 codes, or 3 non-200 codes.  If you're interested in that idea, I could help you with the javascript code.

**Comment by tru2dagame** [comment]
Hi @darrencauthon,

That would be perfect if you can show a workaround example.
Thanks so much.
