### ISSUE TITLE
Run scheduled agents

### ISSUE THREAD

**Issue by remino** [cantino/huginn#1385]
Hi,

I'm using Heroku's free plan to run an app with my own installation of Huginn. I've also set up a free account with uptimerobot to ping my server regularly, and that seems to work.

However, when listing my agents, I see they never run, even if they are schedule to run regularly (at, for example, every 2 hours).

Is there a particular URL I need to ping or a separate worker I need to start?

**Comment by cantino** [comment]
Unfortunately, Heroku's free plan doesn't really work with Huginn anymore because they only let you stay up for something like 18 hours a day.

**Comment by remino** [comment]
Okay, thanks for clearing that.

If I did upgrade my plan, how would I tell Huginn to run the scheduled agents regularly on its own?

**Comment by cantino** [comment]
It should just work on a paid plan.  If it doesn't, we have a bug to fix :)

**Comment by cantino** [comment]
I'm going to close this.  Please reopen if you have more questions!
