### ISSUE TITLE
sudo -u huginn -H git diff $OLD_VERSION..master .env.example

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1391]
When I use the above command to update Huginn it shows all these different changes to .env.
How do I accept the changes and move on to next step? Ubuntu Vim

**Comment by dsander** [comment]
You have to apply the changes manually, because `.env` is not checked into the reversion control system there is no way to apply the changes automatically (which is intentionally). For new options you can copy and paste them to your `.env` from `.env.example`.

**Comment by signallhill** [comment]
Thanks
