### ISSUE TITLE
Problem connecting to docker

### ISSUE THREAD

**Issue by Scinawa** [cantino/huginn#1392]
Hi,
I'm following the docker installation guide, but I cannot connect to my docker instance.

# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                    NAMES
4a8c3e7ee9d2        cantino/huginn      "/scripts/init"     40 minutes ago      Up 40 minutes       0.0.0.0:3000->3000/tcp   adoring_kalam

While 
docker ps -q | xargs docker inspect --format '{{ .Id }} - {{ .Name }} - {{ .NetworkSettings.IPAddress }}'
4a8c3e7ee9d2ac303edf83fbd2ebe9317bf365927749dd27bc7d7b9ee9c87e0f - /adoring_kalam - 172.17.0.2

I cannot connect to neither IP addresses (0.0.0.0 is my eth0 interface I suppose).
If I tcpdump the connection of the docker interface a see a RST packet from 172.17.0.2 :(

Any hints? I cannot login to the web screen. 
tnx

P.s. 
It might be helpful to know that I saw plenty of mysql errors in the docker's console, but these seems potentially innoquous..

mysqld stderr | 160330 00:00:57 mysqld_safe Can't log to error log and syslog at the same time.  Remove all --log-error configuration options for --syslog to take effect.
mysqld stdout | 160330 00:00:57 mysqld_safe Logging to '/var/log/mysql/error.log'.
mysqld stdout | 160330 00:00:57 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
2016-03-30 00:00:57,611 INFO exited: mysqld (exit status 0; expected)
mysqld stdout | 160330 00:00:57 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
2016-03-30 00:00:57,613 INFO spawned: 'mysqld' with pid 2622
2016-03-30 00:00:58,615 INFO success: mysqld entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by dsander** [comment]
Hi @Scinawa,

the output of `docker ps` looks good to me. When you are using Linux you should be able to access Huginn via `http://localhost:3000`, on OSX you would probably be using `docker-machine`, `docker-machine ls` should give you the IP of the docker host.

**Comment by Scinawa** [comment]
nope :|
`docker-machine ls` gave me an empty list..

Any Idea? I'm on a debian 8 and with not much docker experience

**Comment by dsander** [comment]
If you installed docker in debian Huginn should be reachable via localhost, did you try `http://localhost:3000`?

**Comment by Scinawa** [comment]
plenty of times :)

**Comment by dsander** [comment]
Sorry to hear that, i think it has to be an issue with your docker installation, did you follow the [installation guide](https://docs.docker.com/engine/installation/linux/debian/) and does the ["run a simple application" guide](https://docs.docker.com/engine/userguide/containers/usingdocker/) work for you?

**Comment by cantino** [comment]
I'm going to close this.  Please reopen if you have more questions!

**Comment by hillerliao** [comment]
I meet the similar problem.
