### ISSUE TITLE
Bundler::GemNotFound: Could not find rake-10.5.0 in any of the sources

### ISSUE THREAD

**Issue by virse** [cantino/huginn#1395]
Hey there,

I updated my Huginn-Production-Site. 

When I try to start Huginn via sudo rake production:start, I get the following error:

rake aborted!
Bundler::GemNotFound: Could not find rake-10.5.0 in any of the sources
/home/huginn/huginn/config/boot.rb:6:in `<top (required)>'
/home/huginn/huginn/config/application.rb:1:in `<top (required)>'
/home/huginn/huginn/Rakefile:5:in `<top (required)>'
LoadError: cannot load such file -- bundler/setup
/home/huginn/huginn/config/boot.rb:6:in `<top (required)>'
/home/huginn/huginn/config/application.rb:1:in `<top (required)>'
/home/huginn/huginn/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

and with sudo rake production:start --trace this error message

rake aborted!
Bundler::GemNotFound: Could not find rake-10.5.0 in any of the sources
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:92:in `block in materialize'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `map!'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `materialize'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:185:in `specs_for'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:174:in `requested_specs'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/environment.rb:18:in `requested_specs'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:13:in `setup'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/setup.rb:18:in `<top (required)>'
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/home/huginn/huginn/config/boot.rb:6:in `<top (required)>'
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/huginn/huginn/config/application.rb:1:in `<top (required)>'
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/huginn/huginn/Rakefile:5:in `<top (required)>'
/usr/local/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/usr/local/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/usr/local/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/usr/local/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/usr/local/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/usr/local/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/usr/local/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/local/bin/rake:33:in `<main>'
LoadError: cannot load such file -- bundler/setup
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/huginn/huginn/config/boot.rb:6:in `<top (required)>'
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/huginn/huginn/config/application.rb:1:in `<top (required)>'
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/huginn/huginn/Rakefile:5:in `<top (required)>'
/usr/local/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/usr/local/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/usr/local/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/usr/local/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/usr/local/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/usr/local/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/usr/local/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/local/bin/rake:33:in `<main>'

I already tried to find a solution via Google, but nothing I found solved my problem so far.

What can I do to bring Hugginn back to life ;o)

Thx in advance for any help

virse

**Comment by dsander** [comment]
Hi @virse,

have you tried `sudo bundle exec rake production:export`? I just updated my instance with the [update guide](https://github.com/cantino/huginn/blob/master/doc/manual/update.md) and had no problems.

**Comment by virse** [comment]
Hi dsander,

thx for your reply.

I also followed the update guide you mentioned and then the errors appeared.

When i try the `sudo bundle exec rake production:export`, I also see this on my console:

> sudo bundle exec rake production:export
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.5.0 in any of the sources (Bundler::GemNotFound)
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `map!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `materialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:185:in `specs_for'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:174:in `requested_specs'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/environment.rb:18:in `requested_specs'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:13:in `setup'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/setup.rb:18:in `<top (required)>'
	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

Any hint?

Thx a lot!

**Comment by dsander** [comment]
Hmm that is strange, can you try this?

```
sudo gem install rake
sudo bundle exec rake production:export
```

**Comment by virse** [comment]
Hi,

when i try `sudo gem install rake`, I get this:

> sudo gem install rake
ERROR:  Error installing rake:
	"rake" from rake conflicts with /usr/local/bin/rake

When I try `sudo gem uninstall rake` this:

> sudo gem uninstall rake
ERROR:  While executing gem ... (Gem::InstallError)
    gem "rake" cannot be uninstalled because it is a default gem

**Comment by virse** [comment]
I also tried `sudo gem update` but `rake` doesn't update:

ERROR:  Error installing rake:
	"rake" from rake conflicts with /usr/local/bin/rake
ERROR:  Error installing rdoc:
	"rdoc" from rdoc conflicts with /usr/local/bin/rdoc

and when I try another `sudo bundle exec rake production:export`, I get stil  this:

> sudo bundle exec rake production:export
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in `block in materialize': Could not find rake-10.5.0 in any of the sources (Bundler::GemNotFound)
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in `specs_for'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in `requested_specs'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'
	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

Any more thoughts on that? Thx a lot!

**Comment by virse** [comment]
So I managed to update rake and rdoc by simply rename the old version and do a `sudo gem install rake rdoc`, but still the same error when I try `sudo bundle exec rake production:export`:

> sudo bundle exec rake production:export
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in `block in materialize': Could not find rake-10.5.0 in any of the sources (Bundler::GemNotFound)
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in `specs_for'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in `requested_specs'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'

**Comment by virse** [comment]
Even if I
`> sudo gem install rake -v '10.5.0'
Successfully installed rake-10.5.0`

I still got the error mentioned above.

**Comment by dsander** [comment]
Can you check which version of rake is included in the bundle?
```
sudo bundle show | grep rake
```
If the version is not matching `10.5.0`, did you maybe miss running `sudo -u huginn -H bundle install --deployment --without development test`?

**Comment by virse** [comment]
Hey dsander, thx a lot for your time, but I was too fast.

I already removed ruby from my system and did a new installation of ruby as mentioned in the guide "Installation from source".

Unfortunately I have some problems with the ruby2.3.0-installation. Everything works fine til `sudo make install`.

It stops with this error message:

installing default gems:      /usr/local/lib/ruby/gems/2.3.0 (build_info, cache, doc, extensions, gems, specifications)
                              bigdecimal 1.2.8
                              io-console 0.4.5
                              json 1.8.3
                              psych 2.0.17
                              rdoc 4.2.1
installing bundle gems:       /usr/local/lib/ruby/gems/2.3.0 (build_info, cache, doc, extensions, gems, specifications)
                              rake 10.4.2
/tmp/ruby/ruby-2.3.0/lib/rubygems/installer.rb:227:in `check_executable_overwrite': no implicit conversion of nil into String (TypeError)
	from /tmp/ruby/ruby-2.3.0/lib/rubygems/installer.rb:468:in `block in generate_bin'
	from /tmp/ruby/ruby-2.3.0/lib/rubygems/installer.rb:455:in `each'
	from /tmp/ruby/ruby-2.3.0/lib/rubygems/installer.rb:455:in `generate_bin'
	from /tmp/ruby/ruby-2.3.0/lib/rubygems/installer.rb:295:in `install'
	from ./tool/rbinstall.rb:686:in `call'
	from ./tool/rbinstall.rb:686:in `block in <class:Installer>'
	from ./tool/rbinstall.rb:754:in `block (2 levels) in <main>'
	from /tmp/ruby/ruby-2.3.0/lib/rubygems/specification.rb:821:in `block in each_spec'
	from /tmp/ruby/ruby-2.3.0/lib/rubygems/specification.rb:743:in `block (2 levels) in each_gemspec'
	from /tmp/ruby/ruby-2.3.0/lib/rubygems/specification.rb:742:in `each'
	from /tmp/ruby/ruby-2.3.0/lib/rubygems/specification.rb:742:in `block in each_gemspec'
	from /tmp/ruby/ruby-2.3.0/lib/rubygems/specification.rb:741:in `each'
	from /tmp/ruby/ruby-2.3.0/lib/rubygems/specification.rb:741:in `each_gemspec'
	from /tmp/ruby/ruby-2.3.0/lib/rubygems/specification.rb:819:in `each_spec'
	from ./tool/rbinstall.rb:751:in `block in <main>'
	from ./tool/rbinstall.rb:801:in `block in <main>'
	from ./tool/rbinstall.rb:798:in `each'
	from ./tool/rbinstall.rb:798:in `<main>'
make: *** [do-install-nodoc] Error 1

Any thoughts on that?
Thx for your support!

**Comment by dsander** [comment]
That looks to be a [known issue](https://github.com/rubygems/rubygems/issues/1557) can you try installing ruby 2.2? Here is a link to the [installation guide](https://github.com/cantino/huginn/blob/fad4a44ec40ab5046bcb358331f2c28a81e15606/doc/manual/installation.md#2-ruby) with ruby 2.2

**Comment by virse** [comment]
Thx dsander!
I was able to finish the installation with ruby2.2.

but when i try to login, i get a

> We're sorry, but something went wrong.

the production log says me:

I, [2016-04-01T16:04:03.935530 #11992]  INFO -- : [1d093fe0-a0de-49d7-97a4-f771fd214998] Started GET "/" for 87.175.130.132 at 2016-04-01 16:04:03 +0200
I, [2016-04-01T16:04:03.971896 #11992]  INFO -- : [1d093fe0-a0de-49d7-97a4-f771fd214998] Processing by HomeController#index as HTML
I, [2016-04-01T16:04:04.025598 #11992]  INFO -- : [1d093fe0-a0de-49d7-97a4-f771fd214998]   Rendered home/_signed_out_index.html.erb (1.4ms)
I, [2016-04-01T16:04:04.025739 #11992]  INFO -- : [1d093fe0-a0de-49d7-97a4-f771fd214998]   Rendered home/index.html.erb within layouts/application (5.0ms)
I, [2016-04-01T16:04:04.042563 #11992]  INFO -- : [1d093fe0-a0de-49d7-97a4-f771fd214998]   Rendered layouts/_navigation.html.erb (3.0ms)
I, [2016-04-01T16:04:04.044165 #11992]  INFO -- : [1d093fe0-a0de-49d7-97a4-f771fd214998]   Rendered layouts/_messages.html.erb (0.6ms)
I, [2016-04-01T16:04:04.044622 #11992]  INFO -- : [1d093fe0-a0de-49d7-97a4-f771fd214998] Completed 200 OK in 72ms (Views: 55.9ms | ActiveRecord: 0.0ms)
I, [2016-04-01T16:04:07.954555 #11992]  INFO -- : [9d4173d9-63a3-4c2f-a5ca-559d127728bf] Started GET "/users/sign_in" for 87.175.130.132 at 2016-04-01 16:04:07 +0200
I, [2016-04-01T16:04:07.957434 #11992]  INFO -- : [9d4173d9-63a3-4c2f-a5ca-559d127728bf] Processing by Devise::SessionsController#new as HTML
I, [2016-04-01T16:04:08.100999 #11992]  INFO -- : [9d4173d9-63a3-4c2f-a5ca-559d127728bf]   Rendered devise/shared/_links.html.erb (42.8ms)
I, [2016-04-01T16:04:08.101126 #11992]  INFO -- : [9d4173d9-63a3-4c2f-a5ca-559d127728bf]   Rendered devise/sessions/new.html.erb within layouts/application (62.2ms)
I, [2016-04-01T16:04:08.102753 #11992]  INFO -- : [9d4173d9-63a3-4c2f-a5ca-559d127728bf]   Rendered layouts/_navigation.html.erb (0.7ms)
I, [2016-04-01T16:04:08.103020 #11992]  INFO -- : [9d4173d9-63a3-4c2f-a5ca-559d127728bf]   Rendered layouts/_messages.html.erb (0.1ms)
I, [2016-04-01T16:04:08.103350 #11992]  INFO -- : [9d4173d9-63a3-4c2f-a5ca-559d127728bf] Completed 200 OK in 146ms (Views: 79.4ms | ActiveRecord: 39.7ms)
I, [2016-04-01T16:04:19.609761 #11992]  INFO -- : [642f2f29-2479-4ce6-9cc5-41ce05fed1f9] Started POST "/users/sign_in" for 87.175.130.132 at 2016-04-01 16:04:19 +0200
I, [2016-04-01T16:04:19.611030 #11992]  INFO -- : [642f2f29-2479-4ce6-9cc5-41ce05fed1f9] Processing by Devise::SessionsController#create as HTML
I, [2016-04-01T16:04:19.611083 #11992]  INFO -- : [642f2f29-2479-4ce6-9cc5-41ce05fed1f9]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"pSlbHzeANx+EgughTwYANk8Ge+WuVCyEJ1+eDQtGwwyl0gsBI5qlsjtUKG7oW+OVNV9t6J2H1fFVcD6O659UDQ==", "user"=>{"login"=>"admin", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Log in"}
I, [2016-04-01T16:04:19.728898 #11992]  INFO -- : [642f2f29-2479-4ce6-9cc5-41ce05fed1f9] Completed 500 Internal Server Error in 118ms (ActiveRecord: 40.1ms)
F, [2016-04-01T16:04:19.729849 #11992] FATAL -- : [642f2f29-2479-4ce6-9cc5-41ce05fed1f9] 
NameError (undefined local variable or method `deactivated_at' for #<User:0x007ffada57ed60>):
  app/models/user.rb:47:in `active?'
  app/models/user.rb:65:in `active_for_authentication?'
  config/initializers/silence_worker_status_logger.rb:5:in `call_with_silence_worker_status'

**Comment by dsander** [comment]
That looks like you did not run the [database migrations](https://github.com/cantino/huginn/blob/master/doc/manual/update.md#4-install-gems-migrate-and-precompile-assets).

**Comment by virse** [comment]
That did the trick!

Thx a lot for your time and support!

Huginn is up and running.

Thx again!

**Comment by dsander** [comment]
Great! Glad your instance is working again :smile:
