### ISSUE TITLE
Getting this error message through email

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1396]
I keep getting this error message through email. This started about a week or so ago, also my scheduler agent did not adjust to the time change although server time is correct. Could this be related?

Subject: Cron <root@server> test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
Content-Type: text/plain; charset=ANSI_X3.4-1968
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <LOGNAME=root>
Message-Id: <ID@host.com>
Date: Thu, 31 Mar 2016 06:50:52 -0400

/etc/cron.daily/logrotate:
logrotate_script: 3: kill: No such process

error: error running last action script for /home/huginn/huginn/log/*.log
run-parts: /etc/cron.daily/logrotate exited with return code 1

**Comment by dsander** [comment]
The logrotate script tries to send a [signal](https://github.com/cantino/huginn/blob/master/deployment/logrotate/huginn#L17) to the unicorn process to make sure the server reopens the log file after rotation. It looks like the pid of the server changed without updating the PID file.
Did you try to restart Huginn?

**Comment by signallhill** [comment]
It's stop
