### ISSUE TITLE
Additional contents in email body 

### ISSUE THREAD

**Issue by jamsheer-thottathil** [cantino/huginn#1398]
I am working  'Email Digest Agent' and its working fine .But i am getting some additional contents with   email body like "web_request....".

Sample body 

test mail digest message 
web_request: {"message"=>"test mail digest message"} 

I need to remove web_request: {"message"=>"test mail digest message"} ,How to do it ?

**Comment by cantino** [comment]
Hey @jamsheer-thottathil.  If each incoming event has a `message` key, that should be what gets displayed.  What do your incoming events look like? Or do you have another Agent also sending to the email digest with a different format?

**Comment by jamsheer-thottathil** [comment]
Yes all my incoming payload has message key.I am passing dynamic message(mail content )  from client to mail agent to this.

**Comment by cantino** [comment]
I think I'd need to see a copy of the configuration options, or an exported Scenario with the Agents in it.

**Comment by jamsheer-thottathil** [comment]
My configuration like this

{
  "subject": "{{subject}}",
  "expected_receive_period_in_days": "1",
  "recipients": "user@example.com"
}

my input payload as follows and tried 2 times.I got mail in expected time  but mail does not have subject (here tried to set subject with payload input)   and also mail body has some additional contents ,what is the mistake happened in my side ?

paylaod

{
"message": "eaxmple content",
"subject":"example subject"
}

mail body

eaxmple content
subject: example subject 
web_request: {"message"=>"eaxmple content", "subject"=>"example subject"} 
eaxmple content
subject: example subject 
web_request: {"message"=>"eaxmple content", "subject"=>"example subject"} 

my expected out put
 
'example subject' as mail subject and mail body as follows

eaxmple content

eaxmple content

**Comment by jamsheer-thottathil** [comment]
Additional content removed using  Event Formatting Agent  .
