### ISSUE TITLE
Issues running on Raspberry Pi2

### ISSUE THREAD

**Issue by timlyo** [cantino/huginn#1400]
I'm trying to run Huginn on a Raspberry Pi 2 with Arch Linux Arm installed. 

When running with through Docker I'm getting:

`docker: Error response from daemon: Cannot start container 924014fc8fc09d543ff1dd30427bd8671daf89cba3931f764d0a0c697f42f846: [9] System error: exec format error.`

and when building from source I'm getting the following error when running `bundle`:

```
/home/tim/.gem/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:98:in `[]': invalid byte sequence in US-ASCII (ArgumentError)
	from /home/tim/.gem/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:98:in `strip_leading_spaces'
	from /home/tim/.gem/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:103:in `word_wrap'
	from /home/tim/.gem/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:89:in `tell_me'
	from /home/tim/.gem/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/ui/shell.rb:34:in `error'
	from /home/tim/.gem/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:20:in `rescue in with_friendly_errors'
	from /home/tim/.gem/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
	from /home/tim/.gem/ruby/2.3.0/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
	from /home/tim/.gem/ruby/2.3.0/bin/bundle:23:in `load'
	from /home/tim/.gem/ruby/2.3.0/bin/bundle:23:in `<main>'
```

I'm not very experienced with Docker or with Ruby, is Huginn supported on arm7, and if so can you tell me where I'm going wrong?

**Comment by dsander** [comment]
Hi @timlyo,

we currently do not have docker images that work on ARM. 

The problem during `bundle install` should be resolved by setting the locale to UTF-8:

```
export LANG="C.UTF-8"
export LC_ALL="C.UTF-8"
```

**Comment by timlyo** [comment]
Thanks for your answer. That seems to be working, but the process is taking a while. I'll come back and close this if it works.
