### ISSUE TITLE
WebsiteAgent is fail sometimes and don't have enough logs

### ISSUE THREAD

**Issue by waldens** [cantino/huginn#1401]
There's an agent who fails every now and then, and I checked logs whereas didn't get enough useful info to troubleshoot:

```
Message                                         When 
Extracting html at .mainMagContent dl dt a: []  5d ago 
Extracting html at .mainMagContent dl dt a: []  5d ago 
Fetching http://weekly.caixin.com/2016/cw697/  5d ago 
```

And everytime I re-emit the incoming event, it works again. So the only reason I can guess now is the website this agent fetches is down every now and then...but not sure.

So,
A. Is there a way to troubleshoot in detail what cause this problem?
B. If it's external reason to make Website Agent didn't get 200 OK when it runs by self, Any way to make this agent run again later automatically?

[This](http://216.189.52.26:3333/scenarios/29/export.json) is the scenarios if needed and the agent being talked here is '财新周刊 #2 抓取目录'. Thanks!

**Comment by cantino** [comment]
Hey @waldens.  I'm not sure.  I'd expect to see an error in the Agent's logs if the site couldn't be reached.  You could also look at the Rails logs (production.log, if you're running in production), but I would expect any error to be in the WebsiteAgent logs.

**Comment by waldens** [comment]
Thanks @cantino . I've looked at the [production.log and log/*/current](http://waldens.github.io/productionlog and current file.zip) but got no abnormal message associated. I fixed the schedule to 5pm and cancel the 'Propagate immediately' just now, in case that the first minute incoming event come in, the site still couldn't be reached until several hours later. Hope it gonna return back to normal...

**Comment by cantino** [comment]
It does sound like an external issue, but I'm surprised nothing's in the logs.  Do you see any failed delayed_jobs in the jobs interface at `/jobs`?

**Comment by waldens** [comment]
No any failed jobs. And just now, have tested out adding a delay agent to wait ＞12h(fairly enough I think) is still not working. New log:

```
Message 	                                     When 	
Extracting html at .mainMagContent dl dt a: [] 	~13h ago 	
Extracting html at .mainMagContent dl dt a: [] 	~13h ago 	
Fetching http://weekly.caixin.com/2016/cw698/ 	~13h ago 	
```
I'm really stuck here, and happy to provide VPS account if needed.

**Comment by cantino** [comment]
Are you sure that there is content that matches your selectors? Maybe
they're just not matching anything? The other idea I have is that the site
could be serving different content based on the User Agent. You could try
setting it to Firefox's.
