### ISSUE TITLE
How to extract only part of a href

### ISSUE THREAD

**Issue by somepaulo** [cantino/huginn#1403]
Hello community,

I am trying to scrape a search results page on a site. Given accurate parameters it displays results consistently unless a listing has been added or removed, but they don't very often. The problem is that every time the site is searched, the links to the actual listings on the results change dynamically, although the listings (with title and description stay the same). The links have a bunch of php variables, including tracking codes, and those change on every new search. So every time the Website Agent scrapes the page, it creates new events for the same listings only because the link has changed.

My question is how do I scrape only the main link to the listing, leaving all the variables behind? Essentially, I want the Agent to stop extracting a link just before the php ? symbol in it.
I have tried a configuration like this, but it didn't work:

<pre>
{
  "expected_update_period_in_days": "2",
  "url": [
    "http://www.example.com/page/1",
    "http://www.example.com/page/2"
  ],
  "type": "html",
  "mode": "on_change",
  "extract": {
    "link": {
      "css": ".title-link",
      "value": "{{ @href | regex_replace: '\\?(.*)', '' }}"
    },
    "title": {
      "css": ".title-text",
      "value": ".//text()"
    },
    "date": {
      "css": ".date-posted",
      "value": ".//text()"
    }
  }
}
</pre>

Is that a syntax flaw, or am I on the wrong path altogether?

Thank you!

**Comment by dsander** [comment]
Hi @somepaulo,

I don't think you can use liquid functions in the extraction process. I recommend you change the `WebsiteAgent` to always emit the events then use a `EventFormattingAgent` to modify the URL and then send the normalized event to a `ChangeDetectorAgent`. If the event contains multiple rows the only solution to modify the URL might be the `JavascriptAgent`.

**Comment by cantino** [comment]
I'm going to close this.  Please reopen if you have more questions!
