### ISSUE TITLE
DataOutput Agent Rss Issue With Feedly Android App

### ISSUE THREAD

**Issue by irfancharania** [cantino/huginn#1408]
When generating an RSS feed using the DataOutputAgent, [the iTunes compatible namespace attribute](https://github.com/cantino/huginn/blob/master/app/models/agents/data_output_agent.rb#L217) is causing display issues upon rotation on the Feedly android app [for a comic for example](https://github.com/cantino/huginn/wiki/Generating-a-filtered-full-text-RSS-feed).

Without the ``xmlns:media="http://search.yahoo.com/mrss/" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"`` there is no issue. 

Is it possible to have those attributes be optional?
As ``isPodcast: true`` with default ``false``?

**Comment by cantino** [comment]
:)
