### ISSUE TITLE
Interface Simplification

### ISSUE THREAD

**Issue by nineralpha** [cantino/huginn#1409]
Hey People i want to simplify interface for Email (Or simply say any made using Website) agent i.e. i want to make interface such that user only  enter "TO" email address,rest should either be hard coded inside agent code or value of this TO text field should be concatenated inside OPTION field
like
To_address:...............................................

option
To: To_address
From:abc@gmail.com
body: bla bla bla
Dont have idea how to do that

**Comment by dsander** [comment]
Hi @nineralpha,

to simplify the interface of the EmailAgent have a look at the [form_configurable](https://github.com/cantino/huginn/blob/master/app/concerns/form_configurable.rb) concern, as an example check out the [HipchatAgent](https://github.com/cantino/huginn/blob/master/app/models/agents/hipchat_agent.rb). I think what you need to to is remove the default options of the EmailAgent, just expose one form configurable field and replace the [interpolated values](https://github.com/cantino/huginn/blob/master/app/models/agents/email_agent.rb#L49-L55) with your hard coded ones.

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.
