### ISSUE TITLE
Dynamic 'from' address for mail agent

### ISSUE THREAD

**Issue by bhagyalakshmikk** [cantino/huginn#1410]
Hi,

I am working with mailAgent , I need to set different from address and subject based on my recipient.And it worked with subject by using liquid option ,but it had not worked for 'from' attribute ,Always I am getting from address as the attribute set in .env file.

**Comment by dsander** [comment]
Hi @bhagyalakshmikk,

I think that is a limitation of your email provider. Huginn will set the value you configure in the `from` field but some providers do not allow to "fake" the sender and always set it to your email address. A service like http://www.mailgun.com/ will allow you to configure the from address.

**Comment by cantino** [comment]
I'm going to close this.  Please reopen if you have more questions!
