### ISSUE TITLE
Enhanced schedule for digest agent

### ISSUE THREAD

**Issue by jamsheer-thottathil** [cantino/huginn#1416]
I need to schedule a digest agent with day  
  Example : Every Friday ,Every Saturday  etc  .  Is it possible ?Thanks in advance

**Comment by dsander** [comment]
Hi @jamsheer-thottathil,

you can use a `SchedulerAgent`, which is more flexible then the build in agent schedules, to trigger your EmailDigestAgent.

**Comment by jamsheer-thottathil** [comment]
Thank you@dsander Already tried with SchedulerAgent but its not worked.I configured never option for email digest agent and set exact time schedule in SchedulerAgent .is it right?

**Comment by brianpetro** [comment]
I've had some issues like this; the schedule doesn't handle restarts well when considering infrequently scheduled events. I was able to solve some of my issues by running the old Proc setup(not threaded); it separates the schedule process from the Web/worker processes. This way I can restart just the worker without affecting the schedule. This doesn't help if you push an update, though. 

Another possibility is make the agent run more frequently(hourly/daily) and setup a trigger/Javascript agent that only propagates the event if it meets your time constraint parameters.

**Comment by dsander** [comment]
@jamsheer-thottathil Yes, that is correct, did you also add the DigestAgent to the `control targets` of the SchedulerAgent?

**Comment by cantino** [comment]
I think @brianpetro's insight is correct, if you're restarting Huginn often.  Is that possible?

**Comment by dsander** [comment]
@cantino @brianpetro I think it depends, it is definitely true for the build in "every X" agent schedules. The SchedulerAgent on the other hand uses cronlines, and I don't think they will reset when Huginn is restarted.
