### ISSUE TITLE
Add Database cleaner ?

### ISSUE THREAD

**Issue by Jngai** [cantino/huginn#1421]
I have been doing lots of testing lately and noticed that I have to clear up the test environment pretty frequently. Would adding database cleaner to ensure that we have a clean state in the test env after every single rspec run be a good idea?

**Comment by dsander** [comment]
You needed to clean up the database due to a different migration state on different branches or because the fixtures left the database in a broken state?

**Comment by Jngai** [comment]
I am pretty sure its fixtures. Its not migration. So db cleaner rolls back the sql. I have been dumping the data in the test env.

**Comment by dsander** [comment]
Hmm that is odd, I never had any issues likes that with Huginn. We are using the `database_cleaner` gem in some projects that use capybara/poltergeist more to ensure the correct database state in between individual test cases.

**Comment by cantino** [comment]
I also have never had any issues.  Are you running code outside of `it` blocks in specs, or connecting the the RAILS_ENV=text rails console, or in some other way modifying the data in the test db outside of fixtures and specs?

**Comment by Jngai** [comment]
Yes I have been connecting into rails_env=test console. I will close this ticket.
