### ISSUE TITLE
new installation on Cloud 9 c9

### ISSUE THREAD

**Issue by isoftmaster** [cantino/huginn#1425]
Hi there
i am student and learning ruby and want to test **HUGINN** 
but i am unable to deploy it on cloud 9 server 
([https://c9.io/](https://c9.io/))
can someone please make a small but detail tutorial on 
how to install Huginn in Cloud 9
it will be very helpful for me

 **Solution** 
------------------------------------------------

1- Create a cloud 9 ( [c9.io](c9.io) ) rails workspace and enter the following command one by one:

```

git clone git://github.com/cantino/huginn.git
cd huginn/
cp .env.example .env
bundle
mysql-ctl start
bundle exec rake db:create
bundle exec rake db:migrate
bundle exec rake db:seed 

```

>  bundle exec rake db:seed <-- cannot download sample.
NOTE: The example 'SF Weather Agent' will not work until you edit it and put in a free API key from http://www.wunderground.com/weather/api/
See the Huginn Wiki for more Agent examples!  https://github.com/cantino/huginn/wiki

2- finally, you need to change the port number to $PORT and if still not work then change localhost to $IP in the following config file:
.env

3- And kick the app by entering:
````
bundle exec foreman start

````
now we see the login page. Good to go

![loginpage](https://cloud.githubusercontent.com/assets/7134947/14494462/07b2df86-019c-11e6-8bce-f3541920423c.jpg)

**Comment by isoftmaster** [comment]
@cantino bro can you help me cause i didn't find any installation guide for cloud 9

**Comment by dsander** [comment]
Hi @isoftmaster,

I have never used Cloud9, but how it looks like the setup required is probably similar to the [local installation](https://github.com/cantino/huginn#local-installation).

**Comment by isoftmaster** [comment]
@dsander thanks i did it
