### ISSUE TITLE
Can't connect to local MySQL server through socket

### ISSUE THREAD

**Issue by iLtc** [cantino/huginn#1436]
Hi,

I am trying to install Huginn on one server with MySQL on another server.

I have setted ```.env``` like this:

```
DATABASE_ADAPTER=mysql2
DATABASE_ENCODING=utf8mb4
DATABASE_RECONNECT=true
DATABASE_NAME=app_huginn
DATABASE_POOL=10
DATABASE_USERNAME=app_huginn
DATABASE_PASSWORD=******
DATABASE_HOST=mysql.***.net
#DATABASE_PORT=3306
#DATABASE_SOCKET=/tmp/mysql.sock

RAILS_ENV=production
```

And I also run ```bundle exec rake db:create```, ```bundle exec rake db:migrate```, and ```bundle exec rake db:seed``` successfully.

However, after I ```bundle exec foreman start``` and visited the website, it always showed "We're sorry, but something went wrong." And the ```production.log``` said 

```
Mysql2::Error (Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)):
  config/initializers/silence_worker_status_logger.rb:5:in `call_with_silence_worker_status'
```

I checked the installation instruction again and believed I had done all the steps.

Can someone help me?

Thanks,
Alan

**Comment by dsander** [comment]
Hi @iLtc,

it is odd that the database creation and migration worked but the webserver does not use the correct configuration. Did you run `sudo bundle exec rake production:export` after changing the settings in `.env`?
An other possibility is that the `DATABASE_PORT` needs to be set for rails to connect to `DATABASE_HOST` and not use the socket.

**Comment by iLtc** [comment]
Hi @dsander,

I set ```DATABASE_PORT``` and Huginn can run now! 

Thank you!

Best,
Alan

**Comment by dsander** [comment]
Great! Glad it works now.
