### ISSUE TITLE
Can't change base URI

### ISSUE THREAD

**Issue by neurolit** [cantino/huginn#1437]
Hi!

Thank you very much for this awesome tool! Huginn is really great.

I'd like to host Huginn on a server (through Apache or Nginx), and use _https://hostname/huginn-sub/_ instead of _https://hostname/_.

However I can't find a way to change the base URL of Huginn. Setting DOMAIN to _https://hostname/huginn-sub_ doesn't work, as all generated URL are absolute and begin with /.

Is there a way to achieve that?

**Comment by knu** [comment]
I think there are some (or many) places where Huginn is running at '/', especially in Ajax calls.
We'll need to fix them before we can mount Huginn anywhere except at a root.

**Comment by cantino** [comment]
Thanks @neurolit!  For now, could you use a subdomain?

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.

**Comment by Azimoth** [comment]
I believe, this is what causes [my problems here](https://github.com/huginn/huginn/issues/2040). Have you had time to make progress regarding changing the base URL?

**Comment by cantino** [comment]
I don't think supporting this is a priority at the moment. I'd recommend using a subdomain instead if you can't allocate a full domain.
