### ISSUE TITLE
Issue with bundle install

### ISSUE THREAD

**Issue by richwestcoast** [cantino/huginn#1438]
After running this command: 
sudo -u huginn -H bundle install --deployment --without development test

I get this error message: ([full log](http://pastebin.com/BQFkGyB8))

NoMethodError: undefined method `spec' for nil:NilClass

Did you mean?  inspect

An error occurred while installing delayed_job_active_record (4.1.0), and Bundler cannot continue.

Make sure that `gem install delayed_job_active_record -v '4.1.0'` succeeds before bundling.

**Comment by richwestcoast** [comment]
Fixed this issue by running gem update (doh)

**Comment by cantino** [comment]
Glad it's working for ya :)
