### ISSUE TITLE
Docker install fails 

### ISSUE THREAD

**Issue by kiliankoe** [cantino/huginn#1439]
Hi,

I'm unfortunately not even close to knowing my way around docker or a rails app, but wanted to start up huginn via docker on a machine of mine. I'm running into some issues though when trying to start it via `docker run -p 3000:3000 --name huginn cantino/huginn` or with varying flags. I always run into the following output:

```
foreman stderr | huginn_production already exists foreman stderr |
foreman stderr | + bundle exec rake db:seed
foreman stderr | + exec bundle exec foreman start
foreman stdout | 12:47:58 web.1  | started with pid 95
foreman stdout | 12:47:58 jobs.1 | started with pid 96
2016-04-18 12:48:44,565 CRIT reaped unknown pid 76)
foreman stdout | 12:49:19 web.1  | no ruby in PATH/CONFIG
foreman stdout | 12:49:47 web.1  | exited with code 137
foreman stdout | 12:49:47 system | sending SIGTERM to all processes
12:49:47        | Killed
12:49:47 jobs.1 | terminated by SIGTERM
2016-04-18 12:49:47,845 INFO exited: foreman (exit status 0; expected)
2016-04-18 12:49:54,409 CRIT reaped unknown pid 99)
```

Any help would be greatly appreciated. Thanks.

**Comment by dsander** [comment]
Hi @kiliankoe,

are you using the latest `cantino/huginn` image? I just tried `f09305c3c428` (the tag is `4140fa62f9ff2aeb32062c8ba7a861872439704a`) with docker 1.11.0 on OSX  and the container started without problems.

**Comment by kiliankoe** [comment]
The latest version (specified with the tag or without) seems to start just fine locally on OSX here as well, but I'm running into the problem with a freshly installed Ubuntu 14.04 with Docker 1.11.0 on DigitalOcean.

I'm guessing it's not really an issue with huginn, but I'm not sure what to look for. Simple demo apps work just fine with the installed docker on that machine.

**Comment by kiliankoe** [comment]
After trying it out again locally I see that I get the same output as above, but that's not where it ends. After seemingly having ended in those errors, it continues on to

```
foreman stdout | 19:42:17 jobs.1 | Starting HuginnScheduler
foreman stdout | 19:42:17 web.1  | [2016-04-18 12:42:17] INFO  WEBrick 1.3.1
foreman stdout | 19:42:17 web.1  | [2016-04-18 12:42:17] INFO  ruby 2.2.4 (2015-12-16) [x86_64-linux-gnu]
foreman stdout | 19:42:17 web.1  | [2016-04-18 12:42:17] INFO  WEBrick::HTTPServer#start: pid=486 port=3000
foreman stdout | 19:42:17 jobs.1 | Starting DelayedJobWorker
foreman stdout | 19:42:17 jobs.1 | 2016-04-18T12:42:17-0700: [Worker(host:4c49140ac18a pid:490)] Starting job worker
```

I've let it sit for close to an hour before. Not sure if this helps at all, just something I just noticed.

**Comment by cantino** [comment]
Hey @kiliankoe, how much RAM does your box have?

**Comment by kiliankoe** [comment]
I feel like an idiot for not having tried this... I tried again with a 1GB machine instead of just 512MB and everything seems to work just perfectly. Thanks for the hint! 😊
