### ISSUE TITLE
Unicorn Error

### ISSUE THREAD

**Issue by OliverGee** [cantino/huginn#1442]
Hi there,

I have followed the installation instructions [here](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md) to install on a Ubuntu based server over at DigitalOcean. I am new to nginx (familiar with apache) so a little lost.

I am getting the following error:

`2016/04/19 23:15:19 [crit] 979#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 81.149.45.127, server: IPCOMMENTEDOUT, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/hug$`

As noted in the installation instructions, I have CONFIRMED that my Procfile file is correct and that the unicorn config exists. I do not want to use Huginn on a domain, just the root server IP. Is this what is causing the issue?

**Comment by dsander** [comment]
Hi @OliverGee,

the issue you are noticing can have multiple causes. First check that the unicorn process is running `ps aux|grep unicorn`.  If it isn't run `sudo bundle exec rake production:export`
Next  ensure the unicorn socket file exists `sudo ls -al /home/huginn/huginn/tmp/sockets/unicorn.socket`. If it doesn't the unicorn configuration is not set up correctly.
Now we need to check if the socket is accessible by the `www-data` user nginx is using `sudo -u www-data ls -al /home/huginn/huginn/tmp/sockets/unicorn.socket`. If that does not work the permissions for the huginn home directory are set too tightly.

When everything looks good please post the output of the other log files [listed in the troubleshooting section](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#troubleshooting)

**Comment by OliverGee** [comment]
Hi @dsander 

Thanks for your swift response.

I ran into issues with the socket file. It throws a 'no such file or directory' error when running the command `sudo ls -al /home/huginn/huginn/tmp/sockets/unicorn.socket` so it seems we found the problem!

Should I reinstall?

**Comment by dsander** [comment]
Can you post the contents of the unicorn configuration? It should be in `/home/huginn/huginn/config/unicorn.rb`

**Comment by OliverGee** [comment]
```
wd = File.expand_path(File.join(File.dirname(__FILE__), '..'))

app_path = wd

worker_processes 1
preload_app true
timeout 180
listen "#{wd}/tmp/sockets/unicorn.socket"

working_directory app_path

rails_env = ENV['RAILS_ENV'] || 'production'

# Log everything to one file
stderr_path "log/unicorn.log"
stdout_path "log/unicorn.log"

# Set master PID location
pid "#{wd}/tmp/pids/unicorn.pid"

before_fork do |server, worker|
  ActiveRecord::Base.connection.disconnect!
  old_pid = "#{server.config[:pid]}.oldbin"
  if File.exist?(old_pid) && server.pid != old_pid
    begin
      Process.kill("QUIT", File.read(old_pid).to_i)
    rescue Errno::ENOENT, Errno::ESRCH
      # someone else did our job for us
    end
  end
end

after_fork do |server, worker|
  ActiveRecord::Base.establish_connection
end
```

**Comment by dsander** [comment]
Thanks, that looks perfectly fine. 

Can you run the following command and provide the output of `/home/huginn/huginn/log/unicorn.log` afterwards?
```
sudo bundle exec rake production:stop
sudo bundle exec rake production:export
sudo bundle exec rake production:start
```

**Comment by OliverGee** [comment]
Thanks for your help thus far.

I ran the commands you listed but there appears to be no log output. The only file in the log folder is production.log.

**Comment by dsander** [comment]
Ok, can you post your `Procfile`?

**Comment by OliverGee** [comment]
I'm sure it's going to be something simple I've buggered up!

```
# Old version with separate processes (use this if you have issues with the threaded version)
# web: bundle exec rails server
# schedule: bundle exec rails runner bin/schedule.rb
# twitter: bundle exec rails runner bin/twitter_stream.rb
# dj: bundle exec script/delayed_job run

###############################
#         PRODUCTION          #
###############################

# You need to copy or link config/unicorn.rb.example to config/unicorn.rb for both production versions.
# Have a look at the deployment guides, if you want to set up huginn on your server:
# https://github.com/cantino/huginn/doc

# Using the threaded worker (consumes less RAM but can run slower)
 web: bundle exec unicorn -c config/unicorn.rb
 jobs: bundle exec rails runner bin/threaded.rb

# Old version with separate processes (use this if you have issues with the threaded version)
# web: bundle exec unicorn -c config/unicorn.rb
# schedule: bundle exec rails runner bin/schedule.rb
# twitter: bundle exec rails runner bin/twitter_stream.rb
# dj: bundle exec script/delayed_job run

###############################
# Multiple DelayedJob workers #
###############################
# Per default Huginn can just run one agent at a time. Using a lot of agents or calling slow
# external services frequently might require more DelayedJob workers (an indicator for this is
# a backlog in your 'Job Management' page).
# Every uncommented line starts an additional DelayedJob worker. This works for development, production
# and for the threaded and separate worker processes. Keep in mind one worker needs about 300MB of RAM.
#
#dj2: bundle exec script/delayed_job -i 2 run
#dj3: bundle exec script/delayed_job -i 3 run
#dj4: bundle exec script/delayed_job -i 4 run
#dj5: bundle exec script/delayed_job -i 5 run
#dj6: bundle exec script/delayed_job -i 6 run
#dj7: bundle exec script/delayed_job -i 7 run
#dj8: bundle exec script/delayed_job -i 8 run
#dj9: bundle exec script/delayed_job -i 9 run
#dj10: bundle exec script/delayed_job -i 10 run
```

**Comment by dsander** [comment]
Hopefully it is, try removing the leading spaces in front of `web` and `jobs`.

**Comment by OliverGee** [comment]
Amazing. That was it! Thanks for all your help. I feel like an absolute moron :dancer:

**Comment by dsander** [comment]
Great, glad that fixed the issue!

**Comment by zytomorrow** [comment]
Hi,
I also make this mistake.And when I finished this code,
`sudo bundle exec rake production:stop`
`sudo bundle exec rake production:export`
`sudo bundle exec rake production:start`
the `/home/huginn/huginn/log/unicorn.log` has a so long output.

> I, [2017-11-26T09:17:42.436273 #13421]  INFO -- : Refreshing Gem list
bundler: failed to load command: unicorn (/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bin/unicorn)
NameError: uninitialized constant Rack::LiveReload
  /home/huginn/huginn/config/environments/development.rb:4:in `block in <top (required)>'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/railtie.rb:211:in `instance_eval'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/railtie.rb:211:in `configure'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/railtie.rb:173:in `configure'
  /home/huginn/huginn/config/environments/development.rb:3:in `<top (required)>'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/engine.rb:599:in `each'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/engine.rb:599:in `block in <class:Engine>'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/initializable.rb:30:in `instance_exec'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/initializable.rb:30:in `run'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/initializable.rb:59:in `block in run_initializers'
  /usr/local/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/initializable.rb:48:in `each'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/initializable.rb:48:in `tsort_each_child'
  /usr/local/lib/ruby/2.4.0/tsort.rb:415:in `call'
  /usr/local/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/lib/ruby/2.4.0/tsort.rb:347:in `each'
  /usr/local/lib/ruby/2.4.0/tsort.rb:347:in `call'
  /usr/local/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
  /usr/local/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/initializable.rb:58:in `run_initializers'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/application.rb:353:in `initialize!'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/railtie.rb:185:in `public_send'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/railtie.rb:185:in `method_missing'
  /home/huginn/huginn/config/environment.rb:5:in `<top (required)>'
  config.ru:4:in `require_relative'
  config.ru:4:in `block in <main>'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `eval'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `block in builder'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:752:in `build_app!'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:129:in `start'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/bin/unicorn:23:in `load'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/bin/unicorn:23:in `<top (required)>'
I, [2017-11-26T09:19:28.591143 #13493]  INFO -- : Refreshing Gem list
bundler: failed to load command: unicorn (/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bin/unicorn)
NameError: uninitialized constant Rack::LiveReload
  /home/huginn/huginn/config/environments/development.rb:4:in `block in <top (required)>'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/railtie.rb:211:in `instance_eval'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/railtie.rb:211:in `configure'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/railtie.rb:173:in `configure'
  /home/huginn/huginn/config/environments/development.rb:3:in `<top (required)>'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
  /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/engine.rb:599:in `each'
@
I don't know that's what cause it.Can you give me some advise?

**Comment by dsander** [comment]
@zytomorrow Check the [configure it](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#configure-it) section of the guide, I guess did you uncomment `RAILS_ENV=production` in the `.env` file.

**Comment by zytomorrow** [comment]
You're right!!! I ignore this step.Thanks for your help.Now I can do some interesting things.

**Comment by domainoverflow** [comment]
@dsander Thank you very much. The leading spaces in .env did it for me ( after many hours ... ) .. Thank You ! I'd suggest on huggin repo guide that it is mentioned somewhere: "leading spaces in .env can drive you to insanity" ... thank you again for sharing the solution.
