### ISSUE TITLE
Commander Agent not transmitting data from Rss Agent to Post Agent

### ISSUE THREAD

**Issue by kepford** [cantino/huginn#1443]
I'm a complete noob to Huginn, well about 24 hours in. Love it! Having one issue though. I'm attemping to wire up an event workflow that checks an RSS feed and then triggers a post to my Pinboard.in account.

<img src="https://dl.dropboxusercontent.com/s/a8ig1arxbdl6g3v/2016-04-20%20at%2012.14%20AM.png"  />

I'm wondering if I have something incorrect in my Post agent. I'm trying to pass the url and title from the RSS agent to the Post agent. Pinboard is not getting the url value so the post fails. I have confirmed that Huginn can create bookmarks when I hard code values in the Agent.

## RSS Agent

```
{
  "id": "829f845279611d7925146725317b868d",
  "date_published": "2014-09-11 01:30:00 -0700",
  "last_updated": "Thu, 11 Sep 2014 01:30:00 -0700",
  "url": "http://example.com/...",
  "urls": [ "http://example.com/..." ],
  "description": "Some description",
  "content": "Some content",
  "title": "Some title",
  "authors": [ ... ],
  "categories": [ ... ]
}
```

## Post agent

```
{
  "post_url": "https://api.pinboard.in/v1/posts/add?auth_token=user:token",
  "expected_receive_period_in_days": "1",
  "content_type": "text/xml",
  "method": "get",
  "payload": {
    "format": "json",
    "url": "url",
    "description": "title",
    "tags": "wd",
    "shared": "yes"
  },
  "headers": {},
  "emit_events": "true",
  "no_merge": "true"
}
```

What am I missing?

**Comment by dsander** [comment]
Hi @kepford,

glad you like Huginn! I think you do not need to `CommanderAgent` in the setup. Sending the event from the `RssAgent` to the `PostAgent` will trigger it automatically. Try using [Liquid interpolation](https://github.com/cantino/huginn/wiki/Formatting-Events-using-Liquid) in the `PostAgent` to use the fields of the incoming events.

```
{
  "post_url": "https://api.pinboard.in/v1/posts/add?auth_token=user:token",
  "expected_receive_period_in_days": "1",
  "content_type": "text/xml",
  "method": "get",
  "payload": {
    "format": "json",
    "url": "{{url}}",
    "description": "{{title}}",
    "tags": "wd",
    "shared": "yes"
  },
  "headers": {},
  "emit_events": "true",
  "no_merge": "true"
}
```

**Comment by kepford** [comment]
Ah! That makes sense now. And it worked. Thanks!

**Comment by dsander** [comment]
Great, have fun with Huginn! :smile:
