### ISSUE TITLE
Template/layout edits?

### ISSUE THREAD

**Issue by OliverGee** [cantino/huginn#1445]
Aside from the obvious CSS editing, where can i find the basic template structure for Huginn? I want to be able to alter the format of elements but can't for the life of me work out where it's sourcing it's basic html structure from.  I want to change fonts  (use Google Fonts), colours etc. but can't see where to edit header calls?

Also, is there a translation file somewhere to alter the language (for localised translation)?

**Comment by cantino** [comment]
This is a Rails application, so most of the HTML is in the app/views/ directory.  We don't have translation strings in place at the moment.

**Comment by OliverGee** [comment]
That is whay i concluded from looking at the structure, however editing any of those files yields mo results on the frontend?

**Comment by dsander** [comment]
I assume you are working on the production Huginn instance you set up? If that is the case you will need to restart the application after every edit with `sudo production:restart`, changes to javascript/css also require the assets to be [precompiled](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#compile-assets) before the restart. Making changes is easier in a [development setup](https://github.com/cantino/huginn#local-installation), if you do not want to install it locally the nitrous is a great option to get a development environment in the cloud.

**Comment by OliverGee** [comment]
Ah, that'll be it.

@dsander to my rescue once again. Thanks!

**Comment by OliverGee** [comment]
Just other quick questions:

- How would I call Google Fonts in the header?
- How does Huginn load image assets? I've tried adding relevant images to the /assets/images folder but they 404.

Thanks!

**Comment by dsander** [comment]
You should be able to add your google fonts to the header in the [application layout](https://github.com/cantino/huginn/blob/master/app/views/layouts/application.html.erb) just like you would in a HTML page. For the images I recommend reading the [rails asset pipeline guide](http://guides.rubyonrails.org/asset_pipeline.html), I forgot to mention adding images to `app/assets/ images/` also requires to precompile the assets in production. `<%= image_tag "image_in_app_assets_images.ext" %> ` should work to display a custom image.

**Comment by OliverGee** [comment]
Thanks @dsander.

I understand the code for including an image, and mine is correct I think:

`<%= link_to image_tag("logo.png", :class => 'img-responsive img-rounded', :border => 0, :alt => 'Logo alt text', :title => 'Logo title'), root_path, :class => 'navbar-brand' %>`

But that 404's. I'll read the article you linked and update later.

Thanks for all your help so far.

**Comment by dsander** [comment]
The code looks correct to me, did you precompile the assets afterwards and restarted Huginn?

**Comment by OliverGee** [comment]
Hi @dsander, apologies for the belated reply. I got it working.

I came to the realisation it would probably be easier to just implement an existing Bootstrap admin theme if i want to alter the layout. How hard would this be to do? I am completely unfamiliar with how rails applications work, but am knowledgeable as to how bootstrap works.

**Comment by dsander** [comment]
Hmm not sure, you can modify the [application.css.scss.erb](https://github.com/cantino/huginn/blob/master/app/assets/stylesheets/application.css.scss.erb) file and add the theme there or add a new css/scss file in the `app/assets/stylesheets/` directory.

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.
