### ISSUE TITLE
Is it Possible to have multiple Twitter account in one Huginn user account?

### ISSUE THREAD

**Issue by kepford** [cantino/huginn#1448]
Is it Possible to have multiple Twitter account in one Huginn user account?

**Comment by dsander** [comment]
Hi @kepford,

yes that is possible, you probably need to sign out of your current Twitter account before starting the authentication via the "Authenticate with Twitter" link a second time.

**Comment by kepford** [comment]
Ah, after reading https://github.com/cantino/huginn/wiki/Configuring-OAuth-applications I was thinking one had to create a Twitter Application for each account. Thanks @dsander
