### ISSUE TITLE
'Could not find rake-10.5.0 in any of the sources' when trying to Initialize Database

### ISSUE THREAD

**Issue by vivagonna** [cantino/huginn#1450]
Hi, I'm trying to install huginn on Debian Wheezy, everything went smoothly except when I tried to initialize database, it prompted up:

Could not find rake-10.5.0 in any of the sources
Run bundle install to install missing gems.

I tried `sudo gem install rake -v '10.5.0'` ,rake -v '10.5.0 installed successfully but it didn't work. Did anyone have the same question here? 

Thanks.

**Comment by cantino** [comment]
Did you `bundle`?

**Comment by vivagonna** [comment]
Thx cantino, I found I did miss something, when I `bundle`, it prompt

**Comment by vivagonna** [comment]
Thanks, cantino, I found I did miss something, when I run `bundle`, there was an error, "invalid byte sequence in US-ASCII (ArgumentError)" and I missed it out. I tried the solution in [this thread](http://stackoverflow.com/questions/17031651/invalid-byte-sequence-in-us-ascii-argument-error-when-i-run-rake-dbseed-in-ra) and `bundle` successfully. But I haven't gone through the whole process until now, so not sure this is the silver bullet to my problem, I will come back to update after I complete it. Thanks!

**Comment by vivagonna** [comment]
Hi, I managed to complete the install process and huginn finally ran.

run: huginn-jobs-1: (pid 11015) 1071s; down: log: 1s, normally up, want up
run: huginn-web-1: (pid 11012) 1071s; run: log: (pid 11091) 1066s

 I configure apache with [this example](https://github.com/cantino/huginn/wiki/Apache-Huginn-configuration), all needed mods enabled, https works fine and I can see Huginn's logo on the tab, but got 503 error. 

> Service Temporarily Unavailable
> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
> Apache/2.2.22 (Debian) Server at moli.teaink.com Port 443

I have no idea what't going wrong here. Could you help please? Thanks!

**Comment by dsander** [comment]
I think you need to change `listen "#{wd}/tmp/sockets/unicorn.socket"` in `config/unicorn.rb` to `listen "127.0.0.1:3000"` and restart Huginn afterwards.

**Comment by vivagonna** [comment]
Thank you so much sir! I just find your previous relpy about this error in anthor thread, it works. It is awesome! :+1:
