### ISSUE TITLE
Error parsing Gemfile

### ISSUE THREAD

**Issue by joeparis** [cantino/huginn#1451]
While setting up Huginn on a Digital Ocean Ubuntu 14.04 VM I keep running into the following error when running 

`sudo -u huginn -H bundle exec rake db:create RAILS_ENV=production`

```
[!] There was an error parsing `Gemfile`: Line "8af8e90eb6575a026da81afcbce08d7c97e86f391fabd4f1ff5bfa11f34d47177aa41067912375742cf119134de86b7e340b7e7053054a44122d48b5a10b18ea" doesn't match format. Bundler cannot continue.

 #  from /home/huginn/huginn/Gemfile:8
 #  -------------------------------------------
 #  require File.join(File.dirname(__FILE__), 'lib/gemfile_helper.rb')
 >  GemfileHelper.load_dotenv do |dotenv_dir|
 #    path dotenv_dir do
 #  -------------------------------------------
```

Any pointers would be appreciated.

**Comment by cantino** [comment]
What version of Bundler do you have?

**Comment by joeparis** [comment]
1.11.2

**Comment by dsander** [comment]
Hi @joeparis,

this might be caused by a line in your `.env` file search for the string `8af8e90eb6575a026da81afcbce08`. All lines need to match the format `VARIABLE_NAME=value`.

**Comment by joeparis** [comment]
@dsander Thank you! I accidentally removed `APP_SECRET_TOKEN=` when I put the app secret in the .env file. I feel really foolish. Thanks to both you and @cantino for your replies.

_smh_

**Comment by cantino** [comment]
Great!  Okay if I close this?

**Comment by joeparis** [comment]
Yes,  please do.  And thanks again!

**Comment by cantino** [comment]
No problem :)
