### ISSUE TITLE
Cloudflare Token

### ISSUE THREAD

**Issue by gdomod** [cantino/huginn#1452]
Hi,

i want to get a RSS Feed but its behind a cloudflare,
how can i parse the token or ignore the protection ?

http://www.mydealz.de/rss/deals/new

**Comment by dsander** [comment]
Hi @gdomod,

it looks like Cloudflare executes some Javascript code to redirect the browser. Huginn unfortunately does not support Javascript execution in the Website or PostAgent, so I think it is not possible to bypass the Cloudflare protection with Huginn.

**Comment by irfancharania** [comment]
I had kind of a [similar problem](https://github.com/cantino/huginn/issues/888). 
You could try knu's suggestion of using [PhantomJS Cloud](https://phantomjscloud.com/).
