### ISSUE TITLE
DelayedJob script vs. Rake task

### ISSUE THREAD

**Issue by TildeWill** [cantino/huginn#1453]
I'm in process of spinning up multiple instances on Heroku for Omniscope, and I was looking at the start command for the workers, [script/delayed_job.rb](https://github.com/dsander/huginn/blob/master/script/delayed_job). I didn't know if this file was offering something beyond the included rake task that comes with DelayedJob, [`rake jobs:work`](https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/tasks.rb)? 

As far as I can tell, the script is:
- initializing the environment, which the rake task also does, 
- then running the worker in the background (daemonize)

Running in the background is not something needed in my case where I'm deploying to Heroku. It also feels like it is not needed when starting the app with foreman. So my questions are:

1. Have I missed something and I should use `script/delayed_job.rb` to start my workers?
1. If I haven't missed something, is a pull request warranted to remove `script/delayed_job.rb`?

**Comment by dsander** [comment]
I think we can remove the script, daemonizing is not needed in any of the setups we support.

**Comment by TildeWill** [comment]
I'm looking at the Procfile, the section with dj2..dj10. There's no easy way to assign an instance number to the rake task version that I can see. I'm going to close this issue unless it's a hot issue for someone else.
