### ISSUE TITLE
More scheduler options to Email Digest Agent  or Digest Agent 

### ISSUE THREAD

**Issue by jamsheer-thottathil** [cantino/huginn#1457]
I am working with 'Email Digest Agent' and its  working fine.But now i need to provide more scheduler options as end user decision.Is there any way to generate dynamic scheduler or any third party tools to integrate with huginn  to achieve this.I already added  more customized time with scheduler agent but its does not meets my requirement 
Thanks in advance

**Comment by cantino** [comment]
Would a Scheduler Agent meet your needs?  It can trigger other agents at certain times.

**Comment by jamsheer-thottathil** [comment]
Already working with scheduler agent .but my requirement is that i need to set scheduling time dynamically (Eg:-through payload)

**Comment by dsander** [comment]
You could use a Commaner Agent to change the options of the Scheduler Agent, or if you want to trigger the agent externally using a WebhookAgent would probably be the easiest solution.

**Comment by brianpetro** [comment]
Create a Javascript agent that stores the incoming event ID and time in the
agent memory. The check function should check every minute (using existing
built-in scheduling) if the any times in the memory are less than the
current time. If there are, re-emit those events.

**Comment by jamsheer-thottathil** [comment]
@brianpetro  will you please give sample source of  java scriptAgent

**Comment by jamsheer-thottathil** [comment]
by mistake  i closed this.
@brianpetro will you please give sample source of java scriptAgent

**Comment by jamsheer-thottathil** [comment]
Please give sample configuration of java script agent to achieve this

**Comment by cantino** [comment]
You'll probably need to write it yourself, @jamsheer-thottathil.  As @brianpetro said, it'd be some code that stores the event IDs and time in the memory and compares to it.

**Comment by jamsheer-thottathil** [comment]
@brianpetro how to set schedule time using payload .Is it possible

**Comment by jamsheer-thottathil** [comment]
@brianpetro  tried it ,but not succeeded .I need to hold event by java script agent up to a  time which we given through payload .Is it possible ?
Thanks in advance

**Comment by brianpetro** [comment]
@jamsheer it's not possible directly. You must store that time in the
Javascript agent memory memory along with the incoming event ID. This logic
should exist in the `Agent.receive` function and utilize `this.memory()`.

In the `Agent.check` function; get the memory; check if any times contained
in the memory are less than the current time; if yes, emit the event using
the stored event ID.

Use the builtin scheduling method (drop down input) to schedule the agent
to every 1 minute. This will run `Agent.check` every one minute.

**Comment by jamsheer-thottathil** [comment]
@brianpetro  thank you for your reply

I have done this and emitted events by checking  the current time  as you said and its working fine,Now i need to remove particular  event from memory with event id ,Is it possible ?

**Comment by cantino** [comment]
@jamsheer-thottathil, are you trying to clear part of the memory from within the JavaScript code?

**Comment by jamsheer-thottathil** [comment]
@cantino  right , trying to clear memory with JavaScript  code.

**Comment by cantino** [comment]
Could you post the JavaScript code that you have now?

**Comment by jamsheer-thottathil** [comment]
@cantino  this is sample java script agent code which i am using to store and emit events.

Agent.check = function() {
  this.log('in check');
  
  var memory = this.memory();
  this.log(' length '+Object.keys(memory).length);
  
   for (var key in memory) {
    var time = this.memory(key) ;
    var d = new Date(); // for now
     var time2 = d.getHours()+':'+d.getMinutes()+':'+d.getSeconds();
	var timedif = compareTime(time,time2);
 
   
    if(timedif<0 && !isNaN(timedif)) {
      this.createEvent({ 'test': 'I got an event!', 'time':time });
     this.memory().delete(key);
      
    }
    
   }
   
  
};

Agent.receive = function() {
  var events = this.incomingEvents();
  for(var i = 0; i < events.length; i++) { 
    var p = events[i].payload.time;
    this.memory(events[i].id,p);
    
  }
  Agent.check();
  
}

function compareTime(time1, time2) {
   var s1 = 
       time1.split(":")[0] * 3600 + time1.split(":")[1] * 60 + time1.split(":")[2];
   var s2 = 
       time2.split(":")[0] * 3600 + time2.split(":")[1] * 60 + time1.split(":")[2];
   return (s1 - s2); // Gets difference in seconds
}

**Comment by cantino** [comment]
Ah, I see.  We don't appear to have a way to set the entire memory at once right now.  (We should add it!)


It'd probably be easier to store a hash in memory instead of using keys at the root.  So something like 

```javascript

var times = this.memory('times');

if (!times) {
  times = {};
}

// do your stuff
// to delete, do: delete times['key']

// store it back at the end
this.memory('times', times);
```

make sense?

**Comment by jamsheer-thottathil** [comment]
@cantino thank you for reply  .
