### ISSUE TITLE
Adding "domain" or "data type" as source in agent

### ISSUE THREAD

**Issue by beeksiwaais** [cantino/huginn#1458]
We have to connect manually agents together in "sources" fields when we define a agent. We could instead add a more abstract type of source "domain".

A domain "public transport" could be generated by any agent generating this data type. The agent issuer should comply with a definition set by the receiving agent. An agent could then use the agent "public_transport" or any other agent capable of providing information on public transport. The receiver becomes more abstract and we could add many new agent emitting a "domain" without having to edit agents that receive the event.

We can imagine agents that are dynamically activated by a receiving agent.

It just an idea and I think it could be a nice feature to Huginn.

**Comment by cantino** [comment]
Hey @beeksiwaais, I think this is an interesting idea.  We've talked about event schemas and namespaces in the past (like subscribing to `public_transit.*`).
