### ISSUE TITLE
"deleted" agents on background jobs panel

### ISSUE THREAD

**Issue by vivagonna** [cantino/huginn#1460]
Hi,

I've been playing around with huginn for a while, and it is great. It works well but I found it strange having some "deleted" agents listed on background jobs panel. They just show up every couple of minutes and then dispear. I took a [screenshot](https://drive.google.com/file/d/0B7ddmh7iiF1MVVNKa0tQckxhbzQ/view?usp=sharing), is there anything wrong with it? Thanks.

BR
Eason

**Comment by dsander** [comment]
Hi @vivagonna,

It's hard to tell which Agent is causing this, normally this should only happen right after deleting an Agent that runs on a schedule (but stop occurring at least after a restart of Huginn) or if you added and removed the code for an Agent.

Can you enter the following in a rails console the second the "deleted" agents pop up? (started with `rails c` in development or `sudo -u huginn -H bundle exec rails c RAILS_ENV=production` in production):
```
Delayed::Job.all
```
The interesting part is the `handler` attribute of the returned objects:
```
=> [#<Delayed::Backend::ActiveRecord::Job:0x007f8f1adb1388
  id: 34235,
  priority: 10,
  attempts: 0,
  handler:
   "--- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper\njob_data:\n  job_class: AgentCheckJob\n  job_id: 6c92a9ed-fec8-497f-8213-4b54c31aa066\n  queue_name: default\n  arguments:\n  - 100\n  locale: :en\n",
  last_error: nil,
--- snip ---
```

**Comment by vivagonna** [comment]
Hi, @dsander 

Thanks for you kind reply. I tried to open a rails console but got some error. I'be checked the three *.rb files but found nothing wrong. 

> root@vivagonna:/home/huginn/huginn# sudo -u huginn -H bundle exec rails c RAILS_ENV=production                          config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:
> 
>   * development - set it to false
>   * test - set it to false (unless you use a tool that preloads your test environment)
>   * production - set it to true
> 
> /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/connection_specification.rb:248:in `resolve_symbol_connection': 'RAILS_ENV=production' database is not configured. Available: ["development", "test", "production"] (ActiveRecord::AdapterNotSpecified)
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/connection_specification.rb:211:in `resolve_connection'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/connection_specification.rb:139:in `resolve'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/connection_specification.rb:169:in `spec'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_handling.rb:50:in `establish_connection'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/railtie.rb:120:in `block (2 levels) in <class:Railtie>'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/lazy_load_hooks.rb:27:in `each'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/railtie.rb:116:in `block in <class:Railtie>'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `instance_exec'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `run'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:55:in `block in run_initializers'
>         from /usr/local/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
>         from /usr/local/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
>         from /usr/local/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
>         from /usr/local/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
>         from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each'
>         from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `call'
>         from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
>         from /usr/local/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
>         from /usr/local/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:54:in `run_initializers'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/application.rb:352:in `initialize!'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `public_send'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `method_missing'
>         from /home/huginn/huginn/config/environment.rb:8:in `<top (required)>'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/application.rb:328:in `require_environment!'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:67:in `console'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
>         from /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
>         from bin/rails:8:in `require'
>         from bin/rails:8:in `<main>'

**Comment by dsander** [comment]
Sorry, my bad I got the command backwards `sudo -u huginn -H RAILS_ENV=production bundle exec rails c` should work.

In the rails console `pp Delayed::Job.all; nil` will produce a more readable output in production.

**Comment by vivagonna** [comment]
Hi,  @dsander 

Thank you very much. I think I've caught all them three this time, because I paused all my agents. They are here: 

> irb(main):017:0> pp Delayed::Job.all; nil
> [#<Delayed::Backend::ActiveRecord::Job:0x007f26d079f718
>   id: 588,
>   priority: 10,
>   attempts: 0,
>   handler:
>    "--- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper\njob_data:\n  job_class: AgentRunScheduleJob\n  job_id: 0cc8e2c7-2723-4853-85fe-24abf68f98b2\n  queue_name: default\n  arguments:\n  - every_2m\n  locale: :en\n",
>   last_error: nil,
>   run_at: Fri, 29 Apr 2016 22:11:45 HKT +08:00,
>   locked_at: nil,
>   failed_at: nil,
>   locked_by: nil,
>   queue: "default",
>   created_at: Fri, 29 Apr 2016 22:11:45 HKT +08:00,
>   updated_at: Fri, 29 Apr 2016 22:11:45 HKT +08:00>,
>  #<Delayed::Backend::ActiveRecord::Job:0x007f26d079f420
>   id: 589,
>   priority: 10,
>   attempts: 0,
>   handler:
>    "--- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper\njob_data:\n  job_class: AgentPropagateJob\n  job_id: 7fae1fad-970a-4a2d-9697-5eee6bb82c3c\n  queue_name: propagation\n  arguments: []\n  locale: :en\n",
>   last_error: nil,
>   run_at: Fri, 29 Apr 2016 22:11:45 HKT +08:00,
>   locked_at: nil,
>   failed_at: nil,
>   locked_by: nil,
>   queue: "propagation",
>   created_at: Fri, 29 Apr 2016 22:11:45 HKT +08:00,
>   updated_at: Fri, 29 Apr 2016 22:11:45 HKT +08:00>,
>  #<Delayed::Backend::ActiveRecord::Job:0x007f26d079f0b0
>   id: 590,
>   priority: 10,
>   attempts: 0,
>   handler:
>    "--- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper\njob_data:\n  job_class: AgentRunScheduleJob\n  job_id: 42dd31ef-8e8a-4db7-9310-3fc37fbd4a7f\n  queue_name: default\n  arguments:\n  - every_1m\n  locale: :en\n",
>   last_error: nil,
>   run_at: Fri, 29 Apr 2016 22:11:45 HKT +08:00,
>   locked_at: nil,
>   failed_at: nil,
>   locked_by: nil,
>   queue: "default",
>   created_at: Fri, 29 Apr 2016 22:11:45 HKT +08:00,
>   updated_at: Fri, 29 Apr 2016 22:11:45 HKT +08:00>]
> => nil

Looks like some kind of background processes, I think?

**Comment by dsander** [comment]
Yes, correct. Thanks a lot for helping to debug this! That is indeed a bug, a recent change broke the displaying of those jobs. They should at least be shows as "(internal)" like we did before. I will work on a fix for that.

**Comment by vivagonna** [comment]
Great! Thank you, @dsander .
