### ISSUE TITLE
twitter max_result

### ISSUE THREAD

**Issue by isoftmaster** [cantino/huginn#1463]
i am trying to get more then 100 result from twitter search API using NodeJs 
but not working 
if anyone can help please
its possible cause i tried in huginn twitter search agent (with max_result) and i got what i want 
but i want same thing in Node :(
i know this is irrelevant topic but you people can help me

**Comment by cantino** [comment]
Sorry @isoftmaster, I don't know NodeJS well.

**Comment by dsander** [comment]
@isoftmaster The twitter API is paginated, it returns at most 100 results per query, you can provide the [since_id](https://dev.twitter.com/rest/reference/get/search/tweets) parameter in successive requests to get more results.

**Comment by isoftmaster** [comment]
thank you @cantino and @dsander i am already doing it but that function is confusing i just want number of tweets but nested thing is complicated anyways appreciate your response and help
and i love your app huginn this issue is irrelevant if you want you can delete it
i don't mind

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.
