### ISSUE TITLE
Twitter Callback Issue

### ISSUE THREAD

**Issue by betacanis** [cantino/huginn#1465]
Could not find a valid mapping for path `/auth/twitter/callback`

Already set the

```
TWITTER_OAUTH_KEY=*****************fpUmY
TWITTER_OAUTH_SECRET=*********************************C69VZue
```

Server started with `bundle exec foreman start`

Stopped spring

Seeking assistance

Thanks

**Comment by dsander** [comment]
Hi @betacanis,

when are you getting the error and what is the log output, I am assuming you clicked on the "authenticate with twitter" link in the services page?

**Comment by isoftmaster** [comment]
hello @betacanis when you create app in Twitter dev website 
you have to define Call Back Url ( in my case i used my app url where i hosted my app - http://abc.heroku.com)

i hope your problem will be fixed
