### ISSUE TITLE
Make WebsiteAgent return changes, not complete content

### ISSUE THREAD

**Issue by KuenzelIT** [cantino/huginn#1470]
Hey,

I'd like to return only the changes of a Website and get them via an Email Agent. Is that possible?

I've seen the example with the RSS-feed, but that's not exactly what I need.

Thanks!

**Comment by dsander** [comment]
Hi, 

I don't think that is possible at the moment, building a `DiffAgent` which can work in different modes like `per row`, `HTML`, etc. might be useful for other use cases as well.

**Comment by KuenzelIT** [comment]
DiffAgent sounds good too.

But can't the WebsiteAgent just deliver the changes in his event, maybe with just a few changes?

**Comment by dsander** [comment]
Currently the WebsiteAgent can detect if the extracted values changed and only emit an event when they did. It does not operate on the HTML "level", buth rather uses XPath or CSS selectors to fetch the configured data, that's why I suggested a new Agent.

**Comment by KuenzelIT** [comment]
So it just does some kind of str_compare? I really have no clue how ruby and Huginn works, that's why I thought a little change to the WebsiteAgent would be the easiest way. 

Well yeah, something like returning the old content and the new content, and then doing the diff elsewhere sounds cleaner.

Since we are already at it: is there some way to include other scripting languages? I'm used to PHP and Javascript. Just thinking about something like Huginn Event calls PHP WebService (which e.g. does the Diff), which creates a Huginn event again with a web service?....

**Comment by dsander** [comment]
> So it just does some kind of str_compare? I really have no clue how ruby and Huginn works, that's why I thought a little change to the WebsiteAgent would be the easiest way.

Kind of, it compares the last event it emitted with the event it would emit in the current run, if they differ it emits a new event. Because the extraction is done before that, the comparison does not know anything about the underlying HTML, XML or JSON.

> Since we are already at it: is there some way to include other scripting languages? I'm used to PHP and Javascript. Just thinking about something like Huginn Event calls PHP WebService (which e.g. does the Diff), which creates a Huginn event again with a web service?....

PHP is not an option, but we have the `JavascriptAgent` which allows you to run custom javascript code, you could implement the HTML diffing in there. You could also use the `PostAgent` to send the HTML to an external service, and make the service call a `WebhookAgent` with the diff.

**Comment by KuenzelIT** [comment]
Thanks for your help! The JavascriptAgent is nice and I'm probably going to try that diffing.

Is there more information about the JavascriptAgent? Most of it is clear, but I don't get yet what the Agent.check() method is for.

About the diff: I assume I could use the WebAgent and get the html scheduled to the Javascript. There I can save the old html and always compare to the new one and extract the changes. Does that sound plausible?

**Comment by dsander** [comment]
> Is there more information about the JavascriptAgent? Most of it is clear, but I don't get yet what the Agent.check() method is for.

The `check` method is called when the Agent is run on a schedule or manually triggered to run, you probably do not need it for your use case.


> About the diff: I assume I could use the WebAgent and get the html scheduled to the Javascript. There I can save the old html and always compare to the new one and extract the changes. Does that sound plausible?

Yes exactly, use the memory to store the previous HTML and emit an event if you detect any changes.

**Comment by KuenzelIT** [comment]
Thanks a lot for your help!

I'm going to try it sometime and report back. :)
