### ISSUE TITLE
Use a credential in a liquid control flow tag?

### ISSUE THREAD

**Issue by hunhejj** [cantino/huginn#1472]
Hi,
if I wanted to check if the "description" field contains a certain keyword, I would use:
`"isInside": "{% if description contains "foo" %}yes{% else %}no{% endif %}"`
But what if the keyword is defined by a credential, e.g. in my_keyword? How can I use {%credential my_keyword %} instead of the string "foo" in the expression?

**Comment by brianpetro** [comment]
You could set `event.payload.foo` equal to the credential using an Event Formatting agent prior to this one. Then you could do `{% if description contains foo %}`

**Comment by hunhejj** [comment]
Yes, that's the way I am currently solving it, but it is not too nice to have an extra layer for this only. 
Wouldn't it be worth it to introduce some nicer concept?

**Comment by dsander** [comment]
@hunhejj I suppose you already tried `{% if description contains credential my_keyword %}` and  `{% if description contains credential(my_keyword) %}`?

**Comment by hunhejj** [comment]
None of them work currently, but yes, I was hoping for something like you proposed.

**Comment by dsander** [comment]
You could try to an open an issue on the liquid repository. I think the problem is that liquid does not allow arbitrary tags inside of a control flow tag.
