### ISSUE TITLE
pry-byebug instead of pry-rails?

### ISSUE THREAD

**Issue by International** [cantino/huginn#1475]
Hey guys, is there any reason not to include `pry-byebug` instead of `pry-rails` ( or perhaps along it ) in the Gemfile? Whenever I'm doing some debugging, I always do the change in the Gemfile, so that I would be able to step through the code.

**Comment by cantino** [comment]
I'd be fine with that if @dsander approves.

**Comment by dsander** [comment]
I have heard good things about `pry-byebug` while personally more used to `puts` debugging :smile:, but I dont object. If you we it, don't we want both?  `pry-byebug` for the debugger and `pry-rails` for have `pry` available in the rails console?

**Comment by International** [comment]
@dsander I tend to mix and match `puts` debugging with breakpoints :). I created a PR with `pry-byebug`

**Comment by dsander** [comment]
We now use both `pry-byebug` and `pyr-rails`, thanks @International
