### ISSUE TITLE
smtp config not beeing used

### ISSUE THREAD

**Issue by Warloxx** [cantino/huginn#1476]
I set up my email config in .env like this

```
SMTP_DOMAIN=gmail.com
SMTP_USER_NAME=redacted
SMTP_PASSWORD=redacted
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=465
SMTP_AUTHENTICATION=login
SMTP_ENABLE_STARTTLS_AUTO=true
```

yet it did not work.
After long research I found [this](https://github.com/cantino/huginn/issues/121#issuecomment-31589615) and I edited `config/initializers/action_mailer.rb` to this
```
# Read smtp config out of a config/smtp.yml file

smtp_config = YAML::load(ERB.new(File.read(Rails.root.join('config', 'smtp.yml'))).result)
p smtp_config
if smtp_config.keys.include? Rails.env
  ActionMailer::Base.smtp_settings = smtp_config[Rails.env].symbolize_keys
  p ActionMailer::Base.smtp_settings
end
```

Both printouts did not include any of the settings I made in `.env` and also did not just consist of the defaults set int `smtp.yaml`. I can remember that for the domain it always said something like `your-domain.com`. That value was neither set in `.env` nor in `smtp.yml`, so where did it come from? I did a quick search with `grep` but could not find any file with that string.

Sadly I can not print the log since I removed the `log/job-1/current` while debugging this and now it won't create a new one, so no way to reproduce this ATM. I someone can tell me how I get my logs back (production.log still works) I will print the results I got.

My current workaround is to set the smtp config within `config/initializers/action_mailer.rb` directly like this:
```
# Read smtp config out of a config/smtp.yml file

smtp_config = YAML::load(ERB.new(File.read(Rails.root.join('config', 'smtp.yml'))).result)
#p smtp_config
if smtp_config.keys.include? Rails.env
  ActionMailer::Base.smtp_settings = smtp_config[Rails.env].symbolize_keys
#  p ActionMailer::Base.smtp_settings
end
ActionMailer::Base.smtp_settings = {
  address: 'smtp.gmail.com',
  port: 587,
  domain: 'gmail.com',
  authentication: 'plain',
  enable_starttls_auto: true,
  user_name: 'redacted',
  password: 'redacted'
}
```

**Comment by dsander** [comment]
Hi @Warloxx,

sorry to hear you are having trouble to get it working. How did you install Huginn? The `.env` file changes will only be picked up after a restart (and running `bundle exec sudo production:export` before that in case you are used the manual installation guide).

**Comment by Warloxx** [comment]
I used [these instructions](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md)  to setup huginn.
I did restart but I did not run `bundle exec sudo production:export`, AFAIK it is not explicitly stated that that is necessary if you change the `.env` file so changes are being picked up. Maybe add that to the instructions. I will try to run `bundle exec sudo production:export` and report back if that works.

**Comment by Warloxx** [comment]
Running `bundle exec sudo production:export` did now pickup the changes and it works. 

Just saw on the update instruction it also states to run `bundle exec sudo production:export` as the last step. But since I did a fresh install and just added the stmp config after install I never knew you had to run it again. I guess its unintuitive (at least for me), maybe a note in the instructions would be nice.

**Comment by dsander** [comment]
Glad it is working now. Exporting the configuration is listed as the last test of the [init script installation](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#install-init-script), do you have recommendations how we can make that clearer?

**Comment by Warloxx** [comment]
I guess I must have totally missed that note during installation. Since I was just changing the `.env` file I just looked at the _Configure it_ section for reference. An extra note under the _Configure it_ section might help. The only bad thing is, during first install the note will reference something the user has not read yet.

> **Note:** You have to re-export (see [Install Init Script](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#install-init-script)) the init script every time you change the configuration in `.env` or your `Procfile`!

**Comment by dsander** [comment]
@Warloxx Thanks, that makes sense. I added the note in #1485
