### ISSUE TITLE
Is there any interest in having a poltergeist agent?

### ISSUE THREAD

**Issue by International** [cantino/huginn#1479]
As I'm sure everyone who ever used a website agent could attest, it kind of sucks not to be able to get to some data, because it's generated by javascript. On a [branch of mine](https://github.com/International/huginn/tree/poltergeist_agent), I've created a basic poltergeist agent. Basically, I'm planning a vacation in a few months, and I use it to check flight prices :). The way I'm using it right now, is that the poltergeist agent requests the page, then creates an event with an output key after it's been processed by poltergeist. I have a website agent which receives the poltergeist agent, and then it can process the info with other huginn agents. Based on your feedback, we could potentially expand from there. At this point, it's kind of crude, but it gets the job done ( for me ). What do you guys think?

**Comment by elijah** [comment]
This sounds awesome - can you talk out the memory requirements and such
that would be required to use the agent productively?  [poltergeist loads a
headless webkit, right?]

best,

--e

**Comment by irfancharania** [comment]
I've run into the [same problem before](https://github.com/cantino/huginn/issues/888). I ended up using [PhantomJs Cloud](https://phantomjscloud.com). (Running Phantom on a Heroku instance wasn't as reliable). I just added the [wiki entry](https://github.com/cantino/huginn/wiki/Browser-Emulation-Using-PhantomJS-Cloud) today.

A built-in agent to solve this would be fantastic

**Comment by elijah** [comment]
I like that phantomjscloud has a free plan.  500 pages/day is plenty to do
a lot of useful work.  Nice tip!

--e

**Comment by International** [comment]
@elijah @irfancharania haven't checked (yet) the memory requirements for phantomjs. It might be that a small heroku dyno is not enough for it and for huginn.

**Comment by dsander** [comment]
@International I think that is great idea, but we should probably document the implications well. In my experience PhantomJS can be really slow, never checked the memory requirements though.

**Comment by International** [comment]
@dsander can't say I'm much of a fan as well, since I kind of have mixed feelings about poltergeist, but it should be easier to setup than a webdriver agent. Plus, poltergeist is already a test dependency for huginn :)

**Comment by cantino** [comment]
@irfancharania, did you make an agent for phantomjscloud?

**Comment by irfancharania** [comment]
Yep. I submitted a pull request.
So far it's been working for me. It's good to have options

**Comment by International** [comment]
Not sure how the version that uses phantomcloud is working, but I've been experiencing problems with my implementation. In the beginning, it seemed to work pretty good. Lately, i'm experiencing non-stop timeout errors from the poltergeist lib. Is this something other ppl have experienced as well?

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.
