### ISSUE TITLE
Error on website agent 

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1480]
I am getting this error on a website I'm fetching. What does this mean? 

```'Error when fetching url: Failed: #<Faraday::Response:0x007f7c3d8c5788 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:get @body="" @url=#<URI::HTTP http://www.something.com> @request=#<Faraday::RequestOptions (empty)> @request_headers={"User-Agent"=>"Huginn - https://github.com/cantino/huginn", "Accept-Encoding"=>"gzip,deflate"} @ssl=#<Faraday::SSLOptions verify=true> @response_headers={} @status=0>>'```

>

**Comment by dsander** [comment]
Looks like the server responded with an empty response  and the HTTP status code `0` which is invalid, due to that the request is logged as failed. You should be able to accept the status code by adding it to the `http_success_codes` option (which needs to be an array).

**Comment by signallhill** [comment]
I added [200, 0] status codes. It works but no data is extracted. I can see it in the browser. 

[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Fetching http://www.something.com
[00:00:00] INFO -- : Extracting html at #table .title a: []
[00:00:00] INFO -- : Extracting html at #table .title: []
[00:00:00] INFO -- : Extracting html at #table .a: []
[00:00:00] INFO -- : Extracting html at .div: []
[00:00:00] INFO -- : Extracting html at #table .ls: []
[00:00:00] INFO -- : Dry Run finished

**Comment by signallhill** [comment]
The domain is pointing to the website through CNAME. It looks like there is something going on with CNAME where the browser sees the website but huginn does not. I am going to go directly to the website address directly instead of the domain to get the data.

Is this a huginn issue or just the CNAME issue?

**Comment by dsander** [comment]
Do you get a response using curl (`curl -Lv http://google.com`) and if you disable javascript in the browser?

**Comment by signallhill** [comment]
when I do curl I get

* Rebuilt URL to: http://www.something.com/
* Hostname was NOT found in DNS cache
*   Trying 18X.XX.XXX.XXX...
* Connected to www.something.com (18X.XX.XXX.XXX) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.something.com
> Accept: */*
>
< HTTP/1.1 200 OK
* Server Something is not blacklisted
< Server: Something
< Date: Sat, 07 May 2016 15:08:27 GMT
< Connection: keep-alive
< X-Frame-Options: ALLOWALL
< Content-Type: text/html; charset=utf-8
there there is HTML and ends with
* Connection #0 to host www.something.com left intact

If I disable javascript I can see the website in the browser.

**Comment by International** [comment]
@signallhill what happens if you change the user agent?

**Comment by signallhill** [comment]
I have 2 website agent scraping same page.

1 has following as header 

"User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36",

The second one has no header. 

And both don't work.

**Comment by dsander** [comment]
Hmm you can try to set the headers to be identical to the ones that curl sends. Another test would be to check if the server still responds properly when you force curl to use HTTP 1.0: `curl --http1.0 -Lv`

**Comment by signallhill** [comment]
It started work again by itself. I think whatever was going on with the CNAME got fixed.
