### ISSUE TITLE
Trigger with !regex

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1481]
I have a trigger agent with 2 condition out of which 1 match is good. I think the value in the second is the problem.

    {
      "type": "!regex",
      "value": "something|somethingelse",
      "path": "title"
    }
    {
      "type": "!regex",
      "value": "\1 criteria\|\2 criteria\",
      "path": "description"
    }

This is the error I get

 too short escape sequence: /\1 criteria\|\2 criteria\/i

**Comment by dsander** [comment]
If you try to match `\1 criteria\` the slashes need to be escaped `\\1 criteria\\|\\2 criteria\\`.

**Comment by signallhill** [comment]
Thanks
