### ISSUE TITLE
TwitterStreamAgent doesn't generate any events (anymore)

### ISSUE THREAD

**Issue by xabgesagtx** [cantino/huginn#1490]
I've issues getting the TwitterStreamAgent to work or keep it working. For several days it worked perfectly but now it doesn't generate any events anymore. The check is running but no events are created. I don't understand why and I cannot find any error messages. I tried to reauthenticate with twitter but that didn't change anything.

The huginn application runs in production and I started it with this command. `sudo bundle exec rake production:start`

The configuration of the agent.
```
{
  "filters": [
    "raspberrypi",
    "cubieboard",
    "huginn open source"
  ],
  "expected_update_period_in_days": "2",
  "generate": "counts"
}
```

All other agents are working fine and are creating events as expected.

I've found this in `log/jobs-1/current`, what made me worry a little bit
```
Restarting Agents::TwitterStreamAgent-9-f54cd3d03e1cd38e5269238e87f2b75fab01f648
--> Restarting Agents::TwitterStreamAgent-9-f54cd3d03e1cd38e5269238e87f2b75fab01f648 at 2016-05-08 22:21:35 +0200 <--
Restarting Agents::TwitterStreamAgent-9-f54cd3d03e1cd38e5269238e87f2b75fab01f648
--> Restarting Agents::TwitterStreamAgent-9-f54cd3d03e1cd38e5269238e87f2b75fab01f648 at 2016-05-08 22:21:55 +0200 <--
Restarting Agents::TwitterStreamAgent-9-f54cd3d03e1cd38e5269238e87f2b75fab01f648
Queuing schedule for every_5m
Killing Agents::TwitterStreamAgent-9-f54cd3d03e1cd38e5269238e87f2b75fab01f648
Queuing event propagation
...
Queuing event propagation
Queuing schedule for every_1m
Stopping AgentRunner...
```

Is there any way how I could get to the bottom of this? Other log levels, specific log files, common mistakes I could check.

**Comment by dsander** [comment]
Hi @xabgesagtx,

it looks like the twitter stream API does have an outage [at the moment](https://dev.twitter.com/overview/status), that would explain the continuous restarts of the `TwitterStreamAgent`s.  `Stopping AgentRunner...` only is triggered when the background processor received a UNIX signal to stop, did you manually kill it?
You should get your instance back up by running `sudo bundle exec rake production:restart` in `/home/huginn/huginn`.

**Comment by xabgesagtx** [comment]
Wow. This is a really long outage. I guess this explains the problem.

I only stopped and started huginn with the bundle commands. I was just confused that after starting huginn "Stopping AgentRunnner..." was the last line in the log

**Comment by xabgesagtx** [comment]
On the other hand, I may have been a little to quick to close the ticket. [Retiring the old API](https://twittercommunity.com/t/retiring-old-v1-streaming-api-endpoints-on-march-31st-2016/60351) could be an explaination as well. The status page seems to be [broken](https://twitter.com/andypiper/status/729287075497922562) too

[The code of the agent](https://github.com/cantino/huginn/blob/master/app/models/agents/twitter_stream_agent.rb) seems to use the API version v1.

**Comment by dsander** [comment]
Oh, you are right we totally missed that. Let's hope the fix is as easy as changing the URL.

**Comment by dsander** [comment]
@xabgesagtx Thanks for digging into this! I was wondering about the long "downtime" but did not think about API deprecations. The latest master build should work again.

**Comment by xabgesagtx** [comment]
Yeah, it works. Thanks for fixing it, @dsander!
