### ISSUE TITLE
RSS Agent max_events_per_run

### ISSUE THREAD

**Issue by vx28643** [cantino/huginn#1491]
Setting **max_events_per_run** in the RSS Agent seems to count events that have already been seen, preventing new events from being created.

For example, if there are two or more previously unseen entries in an RSS feed, "max_events_per_run": "2" should always mean at least 2 new events are created. But apparently it counts older entries that have already been seen, preventing the new events from being created.

The code seems to be [here] (https://github.com/cantino/huginn/blob/master/app/models/agents/rss_agent.rb#L118), 

`unless max_events && max_events > 0 && index >= max_events`

perhaps that should be:

`unless max_events && max_events > 0 && created_event_count >= max_events`

Though I would prefer someone with more experience look at it to be sure. I noticed it after experiencing problems trying to use max_events_per_run.

Thanks!

**Comment by dsander** [comment]
I don't know the `RssAgent` well, but your new version of the condition makes sense to me, @knu might know more about the Agent.

**Comment by irfancharania** [comment]
Not all feeds are ordered in descending order. I believe if you set ordering by date (as in example on right), then your max_events per run will work as expected.

**Comment by vx28643** [comment]
I was able to solve my problem by setting the order as described in the examples on the right. I still think it should not count entries that have already been seen, however it seems less critical as setting the order does solve it. Thanks all for your help!
