### ISSUE TITLE
Trigger Agent throws a "	undefined method `<<' for nil:NilClass" error

### ISSUE THREAD

**Issue by gyaoshi** [cantino/huginn#1493]
**the code is**
 {
  "expected_receive_period_in_days": "2",
  "keep_event": "false",
  "rules": [
    {
      "type": "field>=value",
      "value": "4.0",
      "path": "{{magnitude}}"
    }
  ],
  "message": {{magnitude}} earthquake"
} 

**also tried to use regex, come out the same error:**
  "rules": [
    {
      "type": "regex",
      "value": "[4,5,6,7,8,9].*",
      "path": "{{magnitude}}"
    }

And I have a another trigger Agent work fine. 

``         undefined method `<<' for nil:NilClass
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/jsonpath-0.5.7/lib/jsonpath.rb:53:in `initialize'
/home/huginn/huginn/lib/utils.rb:71:in `new'
/home/huginn/huginn/lib/utils.rb:71:in `values_at'
/home/huginn/huginn/lib/utils.rb:60:in `value_at'
/home/huginn/huginn/app/models/agents/trigger_agent.rb:74:in `block (2 levels) in receive'
/home/huginn/huginn/app/models/agents/trigger_agent.rb:73:in `map'
/home/huginn/huginn/app/models/agents/trigger_agent.rb:73:in `block in receive'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/relation/delegation.rb:46:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/relation/delegation.rb:46:in `each'
/home/huginn/huginn/app/models/agents/trigger_agent.rb:69:in `receive'
/home/huginn/huginn/app/jobs/agent_receive_job.rb:8:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/execution.rb:32:in `block in perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:441:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:342:in `block in simple'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:497:in `block in around'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:43:in `block in tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:43:in `tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:441:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:342:in `block in simple'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:497:in `block in around'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/execution.rb:31:in `perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/execution.rb:21:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.5.2/lib/active_job/queue_adapters/delayed_job_adapter.rb:34:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/backend/base.rb:100:in `block in invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/backend/base.rb:97:in `invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:224:in `block (2 levels) in run'
/usr/local/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/local/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:224:in `block in run'
/usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:223:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:300:in `block in reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:300:in `reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:207:in `block in work_off'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:206:in `times'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:206:in `work_off'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:169:in `block (4 levels) in start'
/usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:168:in `block (3 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:167:in `block (2 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:166:in `loop'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:166:in `block in start'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `block in add'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:165:in `start'
/home/huginn/huginn/lib/delayed_job_worker.rb:6:in `run'
/home/huginn/huginn/app/concerns/long_runnable.rb:71:in `block in run!'``

**Comment by dsander** [comment]
Hi @gyaoshi,

the `TriggerAgent` expects the values in `path` to be a JSONPath, try using `$.magnitude` instead of `{{magnitude}}`.
