### ISSUE TITLE
Error scraping json using WebsiteAgent "Error when fetching url: Cannot use ?(...) unless eval is enabled"

### ISSUE THREAD

**Issue by bleakstew** [cantino/huginn#1494]
I am attempting to filter incoming json entries using the filter feature of JSONPath similar to one of the examples on the Goessner website. However, it looks to me like this feature has not been enabled in the Huginn implementation of JSONPath. Am I missing something?

My WebsiteAgent looks like this:

```
{
  "expected_update_period_in_days": "2",
  "url": [
    "http://sciencepatrol.storenvy.com/products.json"
  ],
  "type": "json",
  "mode": "on_change",
  "extract": {
    "data": {
      "path": "$[*].variants[0].variant[?(@.status = 'active')]"
    }
  }
}


```
And I get the following error during a dry run:
ERROR -- : Error when fetching url: Cannot use ?(...) unless eval is enabled

Is my JSONPath syntax wrong, or are the filters not available?

Thanks

**Comment by International** [comment]
I think this refers to the section in your .env file:

```
# Allow JSONPath eval expresions. i.e., $..price[?(@ < 20)]
# You should not allow this on a shared Huginn box because it is not secure.
ALLOW_JSONPATH_EVAL=false

```

Setting it to true should do the trick.

**Comment by bleakstew** [comment]
That worked. I deployed to Heroku, so I set the variable in the dashboard instead. Thanks!
