### ISSUE TITLE
Newbie question: Environment variables when using docker

### ISSUE THREAD

**Issue by mostar** [cantino/huginn#1495]
Hi,

How can I change the environment variables file ".env.example" and reload huginn when running:
`docker run -it -p 3000:3000 cantino/huginn`

**Comment by dsander** [comment]
Hi @mostar,

you can pass environment variables using the `-e` flag: `docker run -it -e TIMEZONE="Berlin" -e ANOTHER="variable" -p 3000:3000 cantino/huginn`

An other option is to use [docker-compose](https://docs.docker.com/compose/) with [one](https://github.com/cantino/huginn/blob/master/docker/single-process/docker-compose.yml) of our [example configurations](https://github.com/cantino/huginn/blob/master/docker/multi-process/docker-compose.yml).
