### ISSUE TITLE
Why can't I see recent failures / retries?

### ISSUE THREAD

**Issue by bobbysteel** [cantino/huginn#1498]
The grey pills at the top of the screen seem to be clickable but when I click I can't see what's failed, or clear them. Googling it seems like there was an issue in the past w/ a non admin user seeing them, but I'm running as admin and can't see them.

Regardless, how can I even clear the failed jobs? I don't see where they're stored to clear them out in any easy way, or where in MySQL they're even stored.

Thanks

**Comment by dsander** [comment]
Hey,

do you see the "Job Management" link in the "Account" dropdown? If that is not the case your user is not an admin. The only was to grant a non-admin user admin rights is via the database or rails console:

```
# rails c

user = User.find_by_username("username")
user.admin = true
user.save!
```

**Comment by bobbysteel** [comment]
Ah perfect. I found the database flag and set it properly now and it works great. Should I update the wiki to include that in the setup instructions? Seems like it's a worthwhile thing.

**Comment by dsander** [comment]
Great! Which wiki page do you refer to? I think all installation guides should include `rake db:seed` which automatically creates the first user as an admin.

**Comment by bobbysteel** [comment]
Weird - I followed the directions and didn't get my user created as admin. I suppose it's possible I missed that one command but everything else works flawlessly. Odd.

**Comment by dsander** [comment]
Which directions did you follow? It also possible that one of the guides does not include the database seeding instruction.

**Comment by bobbysteel** [comment]
Honestly don't recall now - it was like 3-4 months ago. I agree the directions now include that rake command. Perhaps I just missed it before.

**Comment by dsander** [comment]
I see, we probably will never know :) Can we close this issue?
