### ISSUE TITLE
Error when fetching url: 784: unexpected token 

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1499]
I am trying to retrieve a JSON url and get the above error. 

The data looks like this in the browser and I am trying to extract "list". I get this error even when I sent data_from_event to {{Result}}

{"Result":

    {
        "ticket":{"arg":"list_posts","pid":"gwt","t":"1463155156","uid":"","h":"2f9","elapsed":"1.559743","msg":""},"request":{"arg":"list_posts","api":"","save":"0","keywords":"","featured":"","pid":"gwt","h":"220",POST_TYPE},"**list**":[{"POST_DATE":"2016-05-13","POST_SUBJECT":"","POST_DES":"<br><b>something","POST_ID":"101","POST_DATE":"05/13/16"},{"POST_DATE":"2016-05-13","POST_SUBJECT":"","POST_DES":"<br><b>something","POST_ID":"102","POST_DATE":"05/13/16"}]

The error I get is 

Error when fetching url: 784: unexpected token at '{"Result":
{
        "ticket":{"arg":"list_posts","pid":"gwt","t":"1463155269","uid":"","h":"678","elapsed":"1.066382","msg":"Ticket Mismatch!"},"request":{"proximity":"","arg":"list_posts","api":"","save":"0","keywords":"","featured":"","pid":"gwt","h":"220",POST_TYPE},
}
}

**Comment by dsander** [comment]
I am not sure which Agents you are using, but the data you posted is not valid JSON, try it in a JSON validator: http://jsonlint.com/
