### ISSUE TITLE
.env loading

### ISSUE THREAD

**Issue by TildeWill** [cantino/huginn#1500]
I was curious about the history of the GemfileHelper.load_dotenv. Right now it's giving me headaches because when I run tests, the RAILS_ENV isn't defined and .env.development gets loaded, then spec_helper.rb runs which defines RAILS_ENV to 'test'. 

It seems like we'd be able to use the pre-loader that comes with doenv-rails per their README:
#### Note on load order

dotenv is initialized in your Rails app during the `before_configuration` callback, which is fired when the `Application` constant is defined in `config/application.rb` with `class Application < Rails::Application`. If you need it to be initialized sooner, you can manually call `Dotenv::Railtie.load`.

```ruby
# config/application.rb
Bundler.require(*Rails.groups)

Dotenv::Railtie.load

HOSTNAME = ENV['HOSTNAME']
```

If you use gems that require environment variables to be set before they are loaded, then list `dotenv-rails` in the `Gemfile` before those other gems and require `dotenv/rails-now`.

```ruby
gem 'dotenv-rails', :require => 'dotenv/rails-now'
gem 'gem-that-requires-env-variables'
```

**Comment by dsander** [comment]
`gem 'dotenv-rails', :require => 'dotenv/rails-now'` looks interesting I am not sure if I just missed it when we added the GemfileHelper or it didn't work for our needs. Did you try to swap out `GemfileHelper.load_dotenv` with the example from their README?

**Comment by TildeWill** [comment]
`rails-now` may not have existed until recently. I was more asking about the history of the heroku and CI checks. Could we live without those?

**Comment by TildeWill** [comment]
I did some short experimentation. `rails-now` does not load the environment variables in time for the rest of the Gemfile, so in my case `bundle` exploded when trying to install mysql2 because I don't have MySQL installed on my machine.

**Comment by dsander** [comment]
Darn, it would have been great to be able to remove the vendored gems. I think we can not remove the CI and Heroku checks, in those two environments it is ok to not have a `.env` file installed. About the tests I generally add new `.env` defaults on which the tests depend on to `env.test` to ensure the local tests work even when I change the value in `.env`.
