### ISSUE TITLE
docker image: can't load when overlayfs is selected

### ISSUE THREAD

**Issue by thypon** [cantino/huginn#1502]
https://github.com/docker/docker/issues/12080

overlayfs doesn't support unix sockets used by supervisord: a simple solution could be to mount the unix socket under /dev/shm

**Comment by dsander** [comment]
Thanks for reporting the issue, I read in the docker issue that it only should happen when hardlinks are used? I am pretty sure we do not do that in our docker image.

**Comment by thypon** [comment]
Actually it affects the huginn docker image. I tried with/without overlayfs having different outcome.
