### ISSUE TITLE
Performance optimization of huginn 

### ISSUE THREAD

**Issue by jamsheer-thottathil** [cantino/huginn#1507]
Thank you for this nice  work  HUGINN.

I am using lot of huginn's agents in  my project as it helpful to meet my  requirements.Now it seems slow by executing multiple agents simultaneously .Is there any documentation available with minimum configuration need to install huginn and also how to do horizontal scaling with huginn .

**Comment by cantino** [comment]
Hi @jamsheer-thottathil. Slow in the UI, or slow working through Agent updates?

**Comment by jamsheer-thottathil** [comment]
UI is too slow and some time agent update also seems slow.

**Comment by cantino** [comment]
How many Agents do you have?

**Comment by jamsheer-thottathil** [comment]
@cantino  thank you for your replay .i have more than 50 agents for different purpose

**Comment by cantino** [comment]
What sort of server are you running it on?

**Comment by jamsheer-thottathil** [comment]
We are using Ubuntu 16.04 LTS with 4GB RAM and 2CPUs on Digital Ocean

**Comment by cantino** [comment]
That seems sufficient for 50 agents. Which actions specifically are feeling
slow?

**Comment by jamsheer-thottathil** [comment]
@cantino 

https://github.com/cantino/huginn/issues/1457

I applied event scheduling with java script agent as explained above link.

**Comment by razakpm** [comment]
@cantino is it possible horizontal scaling with huginn

**Comment by cantino** [comment]
You can add more workers and scale up the database, yes.

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you're still having issues.
