### ISSUE TITLE
google/api_client issue

### ISSUE THREAD

**Issue by mogorman** [cantino/huginn#1508]
I am not sure if this is something weird about my box or huginn.  i am trying to build a package for my distribution.  when i run bundle it succeeds and gets te gem for google_api_client. but wen i try to run the rake command it errors there.  just commenting  out the instance in the gemfile lets me go further.  i am running ruby  ruby 2.3.0p0 (2015-12-25) [x86_64-linux]

$ bundle exec rake db:create RAILS_ENV=production 
rake aborted!
LoadError: cannot load such file -- google/api_client

**Comment by cantino** [comment]
See https://github.com/cantino/huginn/issues/1246, maybe you need to copy the `.env` file?

**Comment by mogorman** [comment]
no, but the other suggestion solved my issue. changing the api/client line to the current version you are using 

gem "google-api-client",  '~> 0.9.6'

also I had to comment out 
gem 'string-scrub'    # for ruby <2.1
as i was running on 2.3.0
and for some reason had to upgrade json
gem 'json', '~> 1.8.3'

also i needed 
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

as well.

**Comment by mogorman** [comment]
also i got it running on nixos.  so that is awesome.  should be fully packaged this weekend
