### ISSUE TITLE
Cannot auth with twitter

### ISSUE THREAD

**Issue by joehua87** [cantino/huginn#1511]
My docker run command
```shell
docker run 	-d  --name huginn -p 3000:3000 \
			-v /var/www/huginn/data:/var/lib/mysql \
			-e TWITTER_OAUTH_KEY=<API KEY> \
			-e TWITTER_OAUTH_SECRET=<API SECRET>"\
			cantino/huginn
```
I've try with HUGINN_ prefix or not
I've seen the Auth with Twitter Link got 500 error when navigate to it
I've check the /app/log/production.log in docker but got nothing

**Comment by dsander** [comment]
Hey @joehua87,

are you accessing your huginn instance via the same base url you used for the creation of the Twitter application?

When you are using `http://localhost:3000/auth/twitter/callback` you also need to access huginn via `http://localhost:3000`

You can access the docker logs via `docker logs -f <container name>`, to get a list of running containers use `docker ps`

**Comment by joehua87** [comment]
@dsander My mistake, thank you for your kinda response ❤️

**Comment by dsander** [comment]
Glad that it's working now 😄
