### ISSUE TITLE
Incorrect (?) Trigger Agent behaviour for negative comparison

### ISSUE THREAD

**Issue by andrey-yantsen** [cantino/huginn#1512]
Maybe Travel Agent should parse rule `{"type": "field!=value", "value": [1,2], "path": "p"}` as `p != 1 and p != 2`, instead of `p != 1 or p != 2`? Same for `!regex`. Because in current behaviour value `1` will pass the rule. Yep, it's `by design` (and it's possible to make a workaround by creating one `!=` rule for each required value), but it's still quite strange behaviour, imho.

Or, at least, will be great if you just add an error (with an example of doing the thing in proper way) when adding `!` rule with array as value.

**Comment by cantino** [comment]
Changing this might (perhaps unlikely) break people's existing installations.  Maybe you could add a warning or update the Markdown in the sidebar?

**Comment by andrey-yantsen** [comment]
Yep, I'll make a PR in next 2 weeks, right now I'm quite busy :(
I just wanted to know what do you think about this — is it really an issue, or we should keep it as it is.
