### ISSUE TITLE
RegExp Help

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1513]
I am using Event Formatting Agent (EFA) trying to use the Matchers as shown in the example but not able to do it.

Payload coming into EFA

title: text text1 at text2 text3 (text4 text5, text6 text7)

Matchers:[
{
path:{{title}}
regex: \A(?<string1>[...](...) \sat\s | \Z(?<string2> \\((...), text6 text7\\)
to: title_new
}

Looking for Output

title_new.string1: text text1
title_new.string2: text4 text5

**Comment by cantino** [comment]
something like `(.*?) at .*? \((.*?), ` maybe?
