### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by nakouzia** [cantino/huginn#1515]
after following this page to install Huginn https://github.com/cantino/huginn/blob/master/doc/manual/installation.md
...
All goes smoothly until this step "Install Gems" and stuck here... with the following error
>> bundle install -j4

Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Could not locate Gemfile or .bundle/ directory

any help with the installation please...

**Comment by mogorman** [comment]
can you dump your log?  if i had to guess it might have been caught on mysql or pgsql dependency or the libcurl one.

**Comment by nakouzia** [comment]
Where I can find the log file?..

**Comment by mogorman** [comment]
what appears on your console at the end of bundle install

**Comment by nakouzia** [comment]
![moon-shot-01](https://cloud.githubusercontent.com/assets/7265885/15451232/157390a6-1fc0-11e6-8c9d-485d579d51b3.jpg)
![steps](https://cloud.githubusercontent.com/assets/7265885/15451238/707edf0a-1fc0-11e6-8a4d-e9f9458d162a.jpg)

**Comment by mogorman** [comment]
what happens if you run 
bundler package --path vendor/cache --no-install

not as root

**Comment by dsander** [comment]
Hi @nakouzia,

you are in the home directory of the root user, but the commands need to be executed in the directory where the huginn source is checked out. Also please use the command as they are provided in the guide, try doing this:

```
cd /home/huginn/huginn
sudo -u huginn -H bundle install --deployment --without development test
```

**Comment by nakouzia** [comment]
Stuck here can't complete...
***********************************************************
```
root@moon:/home/huginn/huginn# sudo -u huginn -H bundle install -j4 --deployment --without development test
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/ui/shell.rb:99:in `[]': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/ui/shell.rb:99:in `strip_leading_spaces'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/ui/shell.rb:104:in `word_wrap'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/ui/shell.rb:90:in `tell_me'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/ui/shell.rb:35:in `error'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/friendly_errors.rb:21:in `log_error'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/friendly_errors.rb:100:in `rescue in with_friendly_errors'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/exe/bundle:19:in `<top (required)>'
        from /usr/local/bin/bundle:23:in `load'
        from /usr/local/bin/bundle:23:in `<main>'
```
---------------------------------------------------------------------

if I try to skip and go to nect command which is 
Initialize Database

# Create the database
`sudo -u huginn -H bundle exec rake db:create RAILS_ENV=production`

I got this error:


```
Could not find rake-10.5.0 in any of the sources
Run `bundle install` to install missing gems.
```
****************************************************************************************

**Comment by mogorman** [comment]
in your Gemfil can you add 
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
at the top?

I was having same issue with ascii and that solved it for me

**Comment by nakouzia** [comment]
Thanks Sir... Works perfectly...

**Comment by dsander** [comment]
Thanks for helping @mogorman!

@mogorman @nakouzia May I ask which distribution and image (maybe of which cloud provider) you used as a base to install Huginn? I think cause for the problem you noticed is that the system locate is not set to UTF-8.

**Comment by mogorman** [comment]
i am using nixos on my laptop.  I have had other issues with ascii vs utf-8 all solved in prs i have open.  not sure why ruby is trying to use ascii
```
[mog@toadman 04:29:20 ~]
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by nakouzia** [comment]
I am using online VPS Linux Ubuntu 14.04.4 LTS 30GB SSD and 6GB RAM...
