### ISSUE TITLE
Netflix Scumblr

### ISSUE THREAD

**Issue by alias1** [cantino/huginn#1522]
Just came across this, haven't had a play yet, but could be some things in it that are useful.

https://github.com/Netflix/Scumblr

**Comment by cantino** [comment]
Interesting!  https://github.com/Netflix/Workflowable looks interesting too.

**Comment by alias1** [comment]
I'm wondering whether a wiki page would be a good idea to keep track of all these 'not quite huginn related but could be quite useful in combination' things.

**Comment by cantino** [comment]
Sure, feel free :)

**Comment by alias1** [comment]
Done :)

https://github.com/cantino/huginn/wiki/Similar-or-Complimentary-to-Huginn

Will trawl back through old issues and find some of the others I've posted.

**Comment by virtadpt** [comment]
\o/
