### ISSUE TITLE
Instagram agent / OAuth 2.0 questions

### ISSUE THREAD

**Issue by bleakstew** [cantino/huginn#1525]
IFTTT is removing support for pulling favorites from Instagram, I believe due to new rate limits on API calls. This breaks the workflow I use the most. I like to capture images I favorite on Instagram into Google Drive as an image reference library for art projects.

1. Is anyone currently working on an Instagram agent that would support pulling photos favorited by an authenticated user (not the user's photos other people have favorited)?

If not...

2. Instagram uses OAuth 2.0. Is this version of Oauth currently supported by Huginn?

3. Does it seem likely that the Twitter favorites agent would be a good model for implementing an Instagram favorites agent? [Instagram API Documentation](https://www.instagram.com/developer/authentication/)

Thanks!!

**Comment by cantino** [comment]
Hey @bleakstew. I don't know of an Instagram agent right now, but I suspect it wouldn't be hard for someone to build.  Yes, Huginn has good OAuth 2.0 support through omniauth.

**Comment by bleakstew** [comment]
Thanks. Well I'm going to leave this open a few more days in case someone
else wants to chime in. I have a bit of a learning curve ahead of me to
code my own agent. My background is Perl rather than Ruby. And I am still
learning how to use git. However, it seems like an excellent chance for me
to build some new skills!

**Comment by cantino** [comment]
Let us know if you start building it and have questions :smile:

**Comment by bleakstew** [comment]
Going to take a stab at this.
