### ISSUE TITLE
Allow setting entire memory at once in JavaScriptAgent

### ISSUE THREAD

**Issue by cantino** [cantino/huginn#1527]
We don't appear to have a way to set the entire memory at once right now.  Maybe we should add `setMemory`, or some way for the `memory` helper to set the entire memory?

**Comment by dsander** [comment]
Makes sense, I don't see any downsides.

**Comment by Enfop** [comment]
I like the addition. Not sure if there is a any convention for the javascript memory functions but i think it would be nice if the helpers could be streamlined. 

Like setMemory(key), getMemory(key) and deleteMemory(key) ( like @knu mentioned in #1543 ) for a key/value pair and setMemory(obj), getMemory() and deleteMemory() for the entire memory. 

This approach would split the memory helper in a get and set and i'm not sure if this is wanted.

**Comment by cantino** [comment]
@Enfop, I think that's a good idea.  If you'd like to work on it, your help would be appreciated.  We need to maintain backwards compatibility, though.

**Comment by cantino** [comment]
This has been merged.
