### ISSUE TITLE
Manually adding attributes to send to the next agent

### ISSUE THREAD

**Issue by ryanwhetstone** [cantino/huginn#1529]
New here, just heard of Huginn on a recent Changelog podcast.  Thanks for all the effort to make this awesome!
I have been playing with this and have the following scenario for watching a craigslist listing page.
https://gist.github.com/ryanwhetstone/30f72a6bdc0555e04c7965cb821943bd
Quick idea of what I am doing.
1. Watch https://cincinnati.craigslist.org/search/cto?query=truck&min_price=7000&auto_cylinders=5 for changes.  When there is a new listing, get the url to the listing detail page and pass this to another website agent.
2. Go to the detail page and extract the details of the listing (title, price, description and an image)
3. Pass the details to a formatting agent.
4. email the new listings.

Sweet, very cool, this works awesome!

The issue I came across is that in the 2nd WebsiteAgent ("Single Craigslist Listing"), I couldn't figure out how to add the url attribute to the event that was then sent to the formatting agent.  I had to add 
"url": {
    "css": "#qrcode",
    "value": "@data-location"
}
to "re-extract" the url.  But this seemed strange to me considering it was available in the incoming agent with the "url" attribute.

So, my question is... Is there a way to manually set an attribute on the event being created?

Thanks!

**Comment by dsander** [comment]
Hi @ryanwhetstone,

glad you like Huginn 😄 You can set `mode` to `merge` which will include the received event data in the emitted event, the downside is that it is not possible to use `merge` and `on_change` at the same time.

I think there currently isn't a better approach then yours. It would be nice to have a general option to merge the received event into the generated data of the Agent.

**Comment by ryanwhetstone** [comment]
Thanks  @dsander, I wasn't sure how to use the merge mode.  This makes sense.  I think I could use it for the second agent, because I don't care about the on_change part in that case, just the initial one.  I will see if I can get it working with the merge mode.
I agree, though, it would be nice to either merge or just set attributes manually.
Thanks again!

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.

**Comment by blackberryoctopus** [comment]
@ryanwhetstone 
Are you still running your CL truck search agent? 
If yes, what query frequency are you using with your agent?

**Comment by ryanwhetstone** [comment]
I'm not currently running it, but I had it going once every 12 hours.

**Comment by ryanwhetstone** [comment]
Did you try using this scenario?  I feel like I had to change it some to get it working recently.  Like maybe the html on the page changed.  Let me know if you need me to re export the scenario.  I do have similar searches working right now and would be happy to share this with you.

**Comment by 917huB** [comment]
@ryanwhetstone I'm new to Huggin and would like to see your current scenarios to help learn from, could you update if you have a moment please?
