### ISSUE TITLE
DryRunnable::Wrapper has been removed Error

### ISSUE THREAD

**Issue by ismail44** [cantino/huginn#1531]
Seeing a weird error every once in a while that says:

`A copy of DryRunnable::Wrapper has been removed from the module tree but is still active!: /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:479:inload_missing_constant'`

No real rhyme or reason... but, a restart makes it go away.

Adding this Issue per @cantino via Gitter.

**Comment by dsander** [comment]
Hi @ismail44,

does this cause any exceptions or prevent any of the Huginn functions from working? I guess you are running in the development environment and the warning is caused by the rails trying to reload the code during which that module/class can not be unloaded properly.

**Comment by ismail44** [comment]
Yes... it stops the entire engine from running... and yes we are still in development mode... I guess that makes sense... I'll switch to production mode for a bit and see if the problem recreates.
