### ISSUE TITLE
Resque Instructions

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1532]
Can anyone provide instructions on how to setup resque with huginn. On AWS w/ Ubuntu

Here is the wiki.
https://github.com/cantino/huginn/wiki/Resque-Setup

I am unable to get is working.

**Comment by dsander** [comment]
You can try my WP branch of #1433, installing redis, setting `BACKGROUND_JOB_PROCESSOR=resque` in `.env` and following the instructions for the `Procfile` should be enough, but I did not test it in production and can not promise when and even if we merge it.
