### ISSUE TITLE
WebsiteAgent Issue

### ISSUE THREAD

**Issue by lloydpick** [cantino/huginn#1539]
Hi,

I'm trying to extract some JSON information from Instagram, it should be pretty straight forward. I can get the correct data through cURL, but no matter what options I try through Huginn I always get a 501.

`curl 'https://www.instagram.com/explore/locations/40971/?__a=1' -H 'referer: https://www.instagram.com'`

You'll get a large JSON hash returned to you. If you remove the referer header, then it'll start 501'ing. But when I try to replicate this with...

```
{
  "expected_update_period_in_days": "30",
  "url": "https://www.instagram.com/explore/locations/40971/?__a=1",
  "type": "json",
  "mode": "on_change",
  "extract": {},
  "headers": {
    "referer": "https://www.instagram.com"
  }
}
```

I get...

```
[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Fetching https://www.instagram.com/explore/locations/40971/?__a=1
[00:00:00] ERROR -- : Error when fetching url: Failed: #<Faraday::Response:0x007f9cb815dae0 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:get @body="" @url=#<URI::HTTPS https://www.instagram.com/explore/locations/40971/?__a=1> @request=#<Faraday::RequestOptions (empty)> @request_headers={"referer"=>"https://www.instagram.com", "User-Agent"=>"Huginn - https://github.com/cantino/huginn", "Accept-Encoding"=>"gzip,deflate"} @ssl=#<Faraday::SSLOptions verify=true> @response_headers={"Strict-Transport-Security"=>"max-age=86400", "Content-Language"=>"en", "Expires"=>"Sat, 01 Jan 2000 00:00:00 GMT", "Vary"=>"Accept-Language, Cookie", "Pragma"=>"no-cache", "Cache-Control"=>"private, no-cache, no-store, must-revalidate", "Date"=>"Wed, 08 Jun 2016 00:02:01 GMT", "Content-Type"=>"text/html; charset=utf-8", "Set-Cookie"=>"mid=V1dgeQAEAAH4IsyggmmXo7iI8q4X; expires=Tue, 03-Jun-2036 00:02:01 GMT; Max-Age=630720000; Path=/", "Connection"=>"keep-alive", "Content-Length"=>"0"} @status=501>>
```

I've tried changing the user agent, turning off ssl verification, you name it. I think I'm missing something obvious. Ideas?

**Comment by cantino** [comment]
You may want to try setting a user-agent header too?

**Comment by lloydpick** [comment]
Yeah, even tried to make it exactly match what cURL was sending, but no luck. Changed it to match my browser as well, same outcome, 501.

```
{
  "expected_update_period_in_days": "30",
  "url": "https://www.instagram.com/explore/locations/40971/?__a=1",
  "type": "json",
  "mode": "on_change",
  "extract": {},
  "headers": {
    "referer": "https://www.instagram.com"
  },
  "user_agent": "curl/7.43.0"
}
```

**Comment by lloydpick** [comment]
Ok, I just tested this locally with master, and it seemed to work fine. So I'm a bit lost, my production huginn is hosted with omniscope, maybe something about their setup.

**Comment by dsander** [comment]
Maybe instagram is blocking Heroku IP ranges? /cc @TildeWill

**Comment by omniscopeio** [comment]
Hi @lloydpick, sorry you're having trouble. I'll recreate your set up and check the logs later on today.

**Comment by TildeWill** [comment]
Yep, seems to be something specific to Heroku or the way we've (Omniscope) set up Huginn on Heroku. Taking omniscopeio/huginn/tree/master and running it locally produces a successful response from Instagram using the Website Agent. I'll keep digging.

**Comment by TildeWill** [comment]
It's pretty strange. URLs like this one for #regentstreet work from anywhere: https://www.instagram.com/explore/tags/regentstreet/?__a=1
But the supplied one for /explore/locations/40971/?__a=1 has problems only when coming from Heroku, producing the 501 described above

**Comment by TildeWill** [comment]
I can also log into Heroku using `heroku run bash` and run cURL with the following output:
```bash
~ $ curl -i "https://www.instagram.com/explore/locations/40971/?__a=1"
HTTP/1.1 501 NOT IMPLEMENTED
Strict-Transport-Security: max-age=86400
Content-Language: en
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Vary: Accept-Language, Cookie
Pragma: no-cache
Cache-Control: private, no-cache, no-store, must-revalidate
Date: Sat, 11 Jun 2016 18:08:24 GMT
Content-Type: text/html; charset=utf-8
Set-Cookie: mid=V1xTmAAEAAFC6xhW-askJBFiNqyh; expires=Fri, 06-Jun-2036 18:08:24 GMT; Max-Age=630720000; Path=/
Connection: keep-alive
Content-Length: 0

```
So there's most certainly a problem between Heroku and Instagram for this subset of endpoints - I'd encourage you to ping Instagram with a support ticket.

**Comment by lloydpick** [comment]
Yeah I imagine so, usually though if you provide the right referer it works. (As this is how the website works when you browse there).

I'll have to try and replicate this request this through the API instead, although it seems that it quite strict to get enough access to poll the equivalent. Thanks for all the investigation work people have done!
