### ISSUE TITLE
rake db:migrate issue during Heroku setup

### ISSUE THREAD

**Issue by fabiogiglietto** [cantino/huginn#1542]
Hi :)
I keep getting this error while executing setup_heroku.

```
Running database migrations...
Running rake db:migrate on lit-shelf-10639... starting, run.7902
Running rake db:migrate on lit-shelf-10639... connecting, run.7902
Running rake db:migrate on lit-shelf-10639... up, run.7902
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

I've tried on two different Linux machines but the result is the same. The very first time I've launched the script it also asked me to create an account. The result is that my deployment is up but I can't login (see https://lit-shelf-10639.herokuapp.com/users/sign_up).

Thank you in advance for your help. This is a very promising application and I'd love to use it for a project I've in mind.

Best regards, Fabio Giglietto

**Comment by dsander** [comment]
Hi @fabiogiglietto,

the `fatal: ...` message is coming from bundler, even though it sure looks like an error it normally does not cause any problems. If the user creation did not work you can either run it again manually:
```
heroku run rake db:seed SEED_EMAIL=mail@example.com SEED_USERNAME=username SEED_PASSWORD=password
```
or create the user with the randomly set invitation token:
```
heroku config:get INVITATION_CODE
```

**Comment by fabiogiglietto** [comment]
Thanks. It worked! Best, Fabio

**Comment by cantino** [comment]
Awesome, glad it worked! Okay if we close this issue?

**Comment by fabiogiglietto** [comment]
Yep

Il mar 14 giu 2016, 7:05 AM Andrew Cantino <notifications@github.com> ha
scritto:
