### ISSUE TITLE
Can Website Agent retrieve URL to a second page with unique content for use in an RSS feed?

### ISSUE THREAD

**Issue by krdurquh** [cantino/huginn#1546]
Hey guys, 
Sorry if this question has already been asked before (I did a quick look and didn't find anything). 

I'm trying to build an RSS feed (like in the blog post example) for a webcomic which has a second unique "hidden comic" attached to each original comic.  The main page of the original comic always has a link to the page that has the second "hidden comic",  
I haven't been able to figure out how to get my RSS feed to display a link to the hidden comic. 

The website is www.amazingsuperpowers.com
On each comic, there is a "translucent question mark" icon in the upper right corner of the comic panel which you click to reach the hidden comic. 
The closest I've come is using the CSS selector to identify "#question img" as the path for said "translucent question mark" icon, but of course this only provides a PNG image of the question mark icon itself, and not a URL link to the content that lies beyond it. 

Any help would be appreciated.  I'll keep experimenting in the meanwhile. 
Thanks!

**Comment by dsander** [comment]
Hi @krdurquh,

this options should get you the link the the hidden comic:

```
{
  "expected_update_period_in_days": "2",
  "url": "http://www.amazingsuperpowers.com/2015/02/trailers/",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": "#question a",
      "value": "@href"
    }
  }
}
```
I think you will need at least three WebsiteAgents, one for the normal comic image and one for the URL of the hidden one which then feeds into the third WebsiteAgent to exact the comic from the hidden URL.

**Comment by krdurquh** [comment]
thanks @dsander ! I didn't know about "href".  That's going in my toolkit. 
If you don't mind, I have a couple of follow-up questions, : 

1) Why did you use "#question a"  instead of  "#question img" ?   (CSS selector seems to suggest that #question img would be more appropriate).  
I tried both out - your way works, my way doesn't.  I just don't understand why my way doesn't work too. 


2) For this "third website agent" that brings everything together, I haven't come up with a way to get everything to play nicely. 
Should I be using a DataOutputAgent to extract the hidden-comic website URL? 


Here's a sample payload from the one you already helped me with: 
{
  "hiddencomic": "http://www.amazingsuperpowers.com/hc/05122016/",
}
How do I use that to combine the linked hidden comic with my other agents? 

My thought was I should use one of the website agents as a SOURCE, and then try to extract the URL from the event coming from the SOURCE agent.   So I tried something like this: 

{
  "expected_update_period_in_days": "2",
  "url_from_event": "{{ url }}",
  "type": "html",
  "mode": "on_change",

But that came up blank. 


I also tried treating it like a JSON output (which i figured was just a long-shot anyways): 

{
  "expected_update_period_in_days": "2",
  "url_from_event": "{{ url }}",
  "type": "json",
  "mode": "on_change",
  "extract": {
    "url": {
      "path": "$.hiddencomic"
    }
  }
}


That came up blank as well. 

Anyways, you can probably tell I'm pretty confused. 
I'd be really grateful if you could point me in the right direction. 
Thanks again!

**Comment by dsander** [comment]
> 1) Why did you use "#question a" instead of "#question img" ? (CSS selector seems to suggest that #question img would be more appropriate).

The link to the comic is in the `href` attribute of the `a` tag, the img selector would only get you the image "inside" of the link.

I would use a second WebsiteAgent to extract the image from the hidden URL:

`WebsiteAgent A` extracts image from main page and sends the event to a `DataOutputAgent`
`WebsiteAgent B` extracts the link to the hidden page and sends the URL it to `WebsiteAgent C`
`WebsiteAgent C` extracts the image from the hidden page and sends the event to the `DataOutputAgent`

When the link is inside `hiddencomic` you try using ` "url_from_event": "{{ hiddencomic }}"`.

**Comment by krdurquh** [comment]
thanks! I really appreciate it!
