### ISSUE TITLE
Possible issue with ~16777215 byte payloads (probably minor)

### ISSUE THREAD

**Issue by Alex-Ikanow** [cantino/huginn#155]
(See #141) When the event payload gets written into the delayed job handler, there is some preamble/postamble added. This could cause the handler to be >16MB and it will be truncated, causing delayed_job to error when it tries to parse the handler.

One thing that should definitely be done is wrap the delayed job handler parser in a try/catch routine so it doesn't kill the entire system (see #141)

Not sure why I didn't do that for #141 actually, I probably just forgot when I didn't immediately see the parser code. @cantino is that something easy you can sneak in there? (or give me a quick navigational pointer to where it lives, if it's not obvious)

You could potentially also truncate the payload, but you'd probably want to do it by lopping off the entirety of the previous JSON object, or you'll get corrupt JSON kicking about, which probably isn't ideal either.

**Comment by cantino** [comment]
Haven't seen this in a long time.
