### ISSUE TITLE
Webhook Agent should be able to respond with request parameters

### ISSUE THREAD

**Issue by fabiogiglietto** [cantino/huginn#1554]
Hi again,
I was planning to experiment with Facebook Messenger Bots but got stuck in the process of callback verification. Basically Facebook sends a GET request to the the callback url with a numeric hub.challenge parameter and expects to get the value of the parameter in response.

I've already configured the Webhook Agent to accept GET requests.

Is it possible to configure the Webhook Agent response parameter to output the value of the hub.challenge GET parameter?

**Comment by dsander** [comment]
Hey!

I don't think that is possible, you can configure the WebhookAgents `response` option but it is not possible to change the response option dynamically during the Webhook request. The hub.challenge is changed for every request?

**Comment by fabiogiglietto** [comment]
Unfortunately it is changed for every request...

**Comment by cantino** [comment]
With a small change, it might be possible.  We return `interpolated['response']`, so if we added a `request` Liquid helper, you could set `response` to `{{ request['hub.challenge'] }}`. This isn't possible now, but is a good feature request!

**Comment by fabiogiglietto** [comment]
That would be great!

**Comment by cantino** [comment]
This should be fixed now by #1682.

**Comment by cybrpimp** [comment]
Started  a new thead for how to implement that new feature.

[User Webhook Agent to return Response to Dropbox Webhook Verification · Issue #3021 · huginn/huginn](https://github.com/huginn/huginn/issues/3021)
