### ISSUE TITLE
Issue with Regex

### ISSUE THREAD

**Issue by Pcsl** [cantino/huginn#1556]
As time goes by I'm more in love with this project. It lets me to automate so many things... Thank you for all the hard work!

Anyway now I'm having a problem with regex rules. I want the TriggerAgent to result an event when the word Spain or Madrid are found in the content AND when the word travel appears in text. That is working fine using this code. 

>  {
>       "type": "regex",
>       "value": "Spain|Madrid",
>       "path": "content"
>     },
>     {
>       "type": "regex",
>       "value": "travel",
>       "path": "content"
>     }

However, how could I make the event to trigger when it finds the word "travel" not just in text but also when that word appears only on the title? The problem is that this isn't triggered when the word "trave" appears only in the title...
Any idea?

**Comment by albertsun** [comment]
Here's one way you could do it.

Create a second TriggerAgent configured to detect just when the word "travel" is in the title. Then create a DeDepulicationAgent that accepts results from both TriggerAgents and de-deduplicates based on their URL. Then change any downstream agents to take output from the DeDepucliationAgent instead of the original TriggerAgent.

**Comment by cantino** [comment]
@Pcsl, can you set `path` to `title`, or is that not a field in your events?

**Comment by Pcsl** [comment]
@cantino I could but the problem is that I want it to check both the content and the title and trigger if any of them contains the word "travel". But I can not find any way to use an "OR" operator in regex.

If there isn't an easy way I will probably try to do what albertsun said.

**Comment by cantino** [comment]
Since you can't say path = `content|title`, it might not be possible right now?

**Comment by Pcsl** [comment]
Thanks then I will close it!
