### ISSUE TITLE
E-mail Subject in body

### ISSUE THREAD

**Issue by ancientz** [cantino/huginn#1558]
Hi!

Not sure why this happens, my e-mail body comes with the HTML I set, but also come with the subject defined on the top, see screenshot attached.

<img width="1023" alt="wtf" src="https://cloud.githubusercontent.com/assets/6853961/16283201/42aa9772-38a2-11e6-89b8-7f5a91d7e665.PNG">

My current EmailAgent config is:
{
  "subject": "Status Report - Neture",
  "expected_receive_period_in_days": "1",
  "recipients": [
    "XXXXX",
    "XXXXX"
  ],
  "content_type": "text/html",
  "body": "THE HTML",
  "headline": "",
  "some_text": ""
}

I would like to show only the body html to the user, without the subject. I would the current behavior is not right?

**Comment by dsander** [comment]
Hi @ancientz,

you want the email to have an empty subject? This is not possible you could set it to something like `.`, but how would the recipient of the email know what it's about?

**Comment by ancientz** [comment]
@dsander Oh no, the problem is not the subject of the email, its the fact that the subject is being printed on the body of the e-mail, in the middle of the HTML, right after the body tag:

<body>
Status Report - Neture
..... rest of HTML

It's quite strange, I think it might have something to do with the headline, but I set it to empty and the subject text is still being printed on the email body.

**Comment by dsander** [comment]
Ah, ic that looks indeed like its coming from the headline, it is included in the email even when the `headline` option is set to an empty string? I don't understand how it is happening, but if it is the case i would consider it a bug.

**Comment by ancientz** [comment]
Yeah, the EmailAgent config is like this:
{
"subject": "Status Report - Neture",
"expected_receive_period_in_days": "1",
"recipients": [
"XXXXX",
"XXXXX"
],
"content_type": "text/html",
"body": "THE HTML",
"headline": "",
"some_text": ""
}

Where headline is empty, and some_text too, and It still shows.

**Comment by cantino** [comment]
@ancientz, I think I have a fix here #1559:   Would you mind testing and seeing if it fixes your issue?

**Comment by ancientz** [comment]
Thanks @cantino , I'll be testing this morning.

**Comment by ancientz** [comment]
Hi @cantino , not sure If you've seen my message on the pull request, I tested the fix but I did not work, even tried with headline set as empty ("") and without it, same result, the headline is still displaying.

**Comment by cantino** [comment]
Could you post an exported Scenario with your Agent so I can debug?

**Comment by ancientz** [comment]
@cantino Hi, I'm attaching the exported JSON, however I redacted the client name and some info with XXXX.
[client.zip](https://github.com/cantino/huginn/files/334822/client.zip)

**Comment by cantino** [comment]
Thanks @ancientz.  I think I understand what's happening.  Huginn uses [this template](https://github.com/cantino/huginn/blob/master/app/views/system_mailer/send_message.html.erb) when rendering your HTML email, and it already includes the header and body for the HTML.  The text you're seeing is from your `<title>` tag.  Can you remove the HTML tags from your body content?

**Comment by ancientz** [comment]
@cantino Oh! You sir, are very right, the title tag was the problem. Thank you! :)
Should I close this issue or should we treat the title tag?

**Comment by cantino** [comment]
I think we can close this.  I may add a comment to the description indicating that the `body` will be wrapped with an HTML template, and so it shouldn't contain the HTML or BODY tags itself.  Glad it's working!
