### ISSUE TITLE
Regex on URL from Google News

### ISSUE THREAD

**Issue by Avalanchaa** [cantino/huginn#1562]
Need some help from the community, I dont know how to use Regex.

I have an RSSAgent that pulls google news from RSS and brings links in the following format:
`<link>
http://news.google.com/news/url?sa=t&amp;fd=R&amp;ct2=us&amp;usg=AFQjCNFvchZyGNkXRBnsZ8WdSfUKbw&amp;clid=c3a7d30bb8a4878e06b8898331&amp;cid=527798794224&amp;ei=WE1uVSL3AH_qYyIBw&amp;url=https://www.apparelnews.net/news/2016/jun/23/importers-brace-new-disruptions-worldwide-ports/
</link>` 

I am using a DataOutputAgent and want to clean the URL to get the following result (without the initial reference and tags from google news)
`<link>
https://www.apparelnews.net/news/2016/jun/23/importers-brace-new-disruptions-worldwide-ports/
</link>`

 my current code on DataOutputAgent looks like this:
```
{
  "secrets": [
    "secretkey"
  ],
  "expected_receive_period_in_days": "1",
  "template": {
    "title": "RSS feed",
    "description": "feed description",
    "item": {
      "description": "{{description | strip_html}}",
      "link": "{{url}}",
    }
  }
}
```

How do I include a regex to clean the url?

**Comment by Avalanchaa** [comment]
By reading the documentation for a websiteAgent, I could use substring-after function.
It will need to extract the text after 

`url=`

my code looks like this:
```
{
  "url": "https://news.google.com/news?cf=all&hl=en&pz=1&ned=us&q=inditex+supply+chain&output=rss",
  "mode": "on_change",
  "type": "xml",
  "extract": {
    "title": {
      "css": "item title",
      "value": ".//text()"
    },
    "link": {
      "css": "item link",
      "value": ".//text()"
    },
```

Can anyone suggest how to include substring-after on the code?

**Comment by cantino** [comment]
Could you give an example of the content that contains `url=`?

**Comment by irfancharania** [comment]
I did up a quick EventFormattingAgent to get you the output you're after:

```json
{
  "instructions": {
    "message": "{{link | regex_replace: '.*url=', ''}}"
  },
  "mode": "merge"
}
```

`message` will contain the actual url minus the google text

**Comment by Avalanchaa** [comment]
Thanks @irfancharania and @cantino , works!

For the ones who would like to know the scenario, I am taking an RSS from Google News i.e. 
[https://news.google.com/news?cf=all&hl=en&pz=1&ned=us&topic=w&output=rss](url)

Google News RSS feed shows urls with  i.e.
`<link>http://news.google.com/news/url?sa=t&fd=R&ct2=us&usg=AFQjCNGp7Iw8_USPHfZuIgE4SNu0TMxKLQ&clid=c3a7d30bb8a4878e06b80cf16b898331&cid=52779143302835&ei=PDd0V4SsG9HWhQGi3KPgDQ&url=http://www.wsj.com/articles/wreckage-black-box-data-point-to-fire-aboard-egyptair-flight-804-1467231659</link>`

with the code from @irfancharania on EventFormattingAgent you can get a clean url i.e.
`<link>http://www.wsj.com/articles/wreckage-black-box-data-point-to-fire-aboard-egyptair-flight-804-1467231659</link>`

**Comment by Avalanchaa** [comment]
@irfancharania can you help me with this regex? I found Google Alerts more useful, but shows URL in between two codes:

Example:

href="https://www.google.com/url?rct=j&sa=t&url=http://www.oann.com/uks-hammond-brexit-path-might-be-clearer-later-this-year/&ct=ga&cd=CAIyGjM3ZGYxNjI5NzU3YTg0MjI6Y29tOmVuOlVT&usg=AFQjCNGY3EeRskCUop5c2qtmzg2f01z5qA
`
real url starts at "url=" and ends before "&ct=" , how to use replace_regex?

**Comment by irfancharania** [comment]
You could just do it simply as a regex replace followed by another regex replace

`{{link | regex_replace: '.*url=', '' | regex_replace: '&ct=.*', ''}}`

(haven't tested this but should work)

**Comment by Avalanchaa** [comment]
Works!

Just for the records, using RSSAgent with a [Google Alerts](https://www.google.com/alerts#) with feed format, url output is as per below

`https://www.google.com/url?rct=j&amp;sa=t&amp;url=http://www.avenuemail.in/jamshedpur/dcs-attend-training-biometric-machines-supply-chain-management/96065/&amp;ct=ga&amp;cd=CAIyGmZmMTI3NzI3YjhjNzlhNzE6Y29tOmVuOlVT&amp;usg=AFQjCNGaf59Y7prCnIVZv8Cwsn57e68MBw`

With an Event Formatting Agent and using the following code it extracts the real url:
`"link": "{{url | regex_replace: '&amp;ct.*', '' | regex_replace: '.*url=', '' }}",`

end result:

`http://www.avenuemail.in/jamshedpur/dcs-attend-training-biometric-machines-supply-chain-management/96065/`

**Comment by cantino** [comment]
Nice!

**Comment by Davelohan** [comment]
Thanks for this. As a novice of Huginn perhaps you can tell me more about how to output the new cleaned up data as an RSS?

**Comment by irfancharania** [comment]
Use the DataOutputAgent

You should look at the [wiki](https://github.com/cantino/huginn/wiki) for examples -- like [this one](https://github.com/cantino/huginn/wiki/Generating-a-filtered-full-text-RSS-feed)
