### ISSUE TITLE
string-scrub issue?

### ISSUE THREAD

**Issue by wasafiri** [cantino/huginn#1565]
Might need a newer version of string-scrub? Has anyone run into this problem before?

    Using twitter-stream 0.1.15 from git://github.com/cantino/twitter-stream.git (at huginn@f7e7edb)
    An error occurred while installing string-scrub (0.1.1), and Bundler cannot continue.
    Make sure that `gem install string-scrub -v '0.1.1'` succeeds before bundling.
    bahar@pine64pro:/home/huginn/huginn$ gem install string-scrub -v '0.1.1'
    ERROR:  Error installing string-scrub:
	    string-scrub requires Ruby version < 2.1, >= 1.9.3.

**Comment by cantino** [comment]
I'm surprised you're seeing string-scrub 0.1.1, the Gemfile.lock has `string-scrub (0.0.5)`.  Did you `bundle update` by mistake?

**Comment by knu** [comment]
Aside from the problem, we should probably drop support for ruby 2.0 (eol), and maybe 2.1 by the time we start looking to adopt Rails 5.

**Comment by forpython** [comment]
@cantino 
I run into the same problem. I delete the gemfile.lock file accidentally and I ran` bundle install`, after which I ran into the problem

**Comment by cantino** [comment]
Yes, in that case you'd need to use git to restore the deleted Gemfile, and run `bundle`.

**Comment by wasafiri** [comment]
I did bundle update in this case.

**Comment by cantino** [comment]
You should never run `bundle update`, only `bundle install` or `bundle update <specific gem>`.
