### ISSUE TITLE
escape special characters in xpath (WebAgent)

### ISSUE THREAD

**Issue by TheReal1604** [cantino/huginn#1566]
Hey @cantino,

got a little problem with an webagent, i have a rss feed with special xml tags <lvb:addinfo> and <lvb:title>....

Then I use this character ":" in my xpath of the webagent, it outputs an error that this variable could not be found. On an online xpath tester, its working. 

Error: [00:00:00] ERROR -- : Error when fetching url: Undefined namespace prefix: /rss/channel/item/lvb:add_info/lvb:title/text()

You can get the xml code here:
http://v.lvb.de/feed/rss-aktuelles/0,0,output,rdf

And my xpath string is:
`/rss/channel/item/lvb:add_info/lvb:title/text()`

How i can escape the ":" ?

Thank you in advance!

Greetings
TheReal

Edit: Tested my xpath command with this online tool: http://www.freeformatter.com/xpath-tester.html

**Comment by cantino** [comment]
I think the website agent, by default, ignores namespaces, so you could probably omit the `lvb:` parts.  There's an option to turn this off.

**Comment by TheReal1604** [comment]
you mean that this xpath string do the trick:

/rss/channel/item/add_info/title/text())

?

Thats not working for me. :(

**Comment by cantino** [comment]
No problem, glad it's working!  Feel free to re-open if something else comes up.
