### ISSUE TITLE
TwitterUserAgent fails to generate events or log entries

### ISSUE THREAD

**Issue by bleakstew** [cantino/huginn#1568]
I am having trouble with TwitterUserAgent. I believe I am successfully authenticated with Twitter because I have both TwitterSteamAgent and TwitterFavorites running successfully. I have just created a TwitterUserAgent with the default options.

```
{
  "username": "tectonic",
  "include_retweets": "true",
  "exclude_replies": "false",
  "expected_update_period_in_days": "2",
  "choose_home_time_line": "false"
}
```
The agent does not generate events, and there are no messages at all in the agent log.

Any suggestions what I should try next?

**Comment by cantino** [comment]
Hey @bleakstew. What update schedule have you set?

**Comment by bleakstew** [comment]
@cantino 5 min intervals. I should also say that my deployment is on Heroku and that I merged updates from the main branch (if that's the right term) about a month ago.

**Comment by cantino** [comment]
It's working for me with 

```json
{
  "username": "tectonic",
  "include_retweets": "true",
  "expected_update_period_in_days": "2"
}
```

you linked it to an authenticated Twitter Service?

**Comment by bleakstew** [comment]
I dropped and recreated my agent, and now it seems to work. I'm really not sure what I was doing wrong before. Sorry to bother and thanks for the response.

**Comment by cantino** [comment]
No problem, glad it's working!
