### ISSUE TITLE
Heroku Git Push

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1571]
When doing git push heroku master after changing gemfile I get following error. bundle install runs successfully but git push does not. I am running Ubuntu locally.

remote: -----> Fetching set buildpack https://github.com/heroku/heroku-buildpack-multi.git... done
remote: -----> Multipack app detected
remote: =====> Downloading Buildpack: https://github.com/cantino/heroku-selectable-procfile.git
remote: =====> Detected Framework: Selectable Procfile
remote: -----> Using deployment/heroku/Procfile.heroku as Procfile
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-ruby.git
remote: =====> Detected Framework: Ruby
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.3.1
remote: -----> Installing dependencies using bundler 1.12.5
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        You are trying to install in deployment mode after changing
remote:        your Gemfile. Run `bundle install` elsewhere and add the
remote:        updated Gemfile.lock to version control.
remote:        You have added to the Gemfile:
remote:        * redis
remote:        * resque
remote:        * resque-web
remote:        * resque-pool
remote:        Bundler Output: You are trying to install in deployment mode after changing
remote:        your Gemfile. Run `bundle install` elsewhere and add the
remote:        updated Gemfile.lock to version control.
remote:        
remote:        You have added to the Gemfile:
remote:        * redis
remote:        * resque
remote:        * resque-web
remote:        * resque-pool
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Multipack app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to Huginn.
remote: 
To https://git.heroku.com/Huginn.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/Huginn.git'

**Comment by cantino** [comment]
Have you committed your updated Gemfile.lock?

**Comment by signallhill** [comment]
Steps im doing
1. Make changes to gemfile
2. bundle install - success
3. git add .
4. git commit -m "commit"
5. git push heroku master 

But keep getting that message.

**Comment by cantino** [comment]
So you're committing the updated Gemfile.lock?  Take a look at git log / git show <your commit> and make sure both the Gemfile and Gemfile.lock were committed.

**Comment by cantino** [comment]
Because: `You are trying to install in deployment mode after changing your Gemfile. Run bundle install elsewhere and add the updated Gemfile.lock to version control.`

**Comment by cantino** [comment]
Did that fix it?

**Comment by signallhill** [comment]
Problem was Windows OS. Switching to Ubuntu worked.
