### ISSUE TITLE
A request and a problem experienced during install

### ISSUE THREAD

**Issue by StakFallT** [cantino/huginn#1575]
I REALLY wish Huginn had two things:

1) Support for MongoDB

2) More Linux distros supported. I'm trying to get Huginn installed on OpenSUSE, and unfortunately, it's just been absolutely miserable. One part is in the documentation. It says:
"_Copy .env.example to .env (cp .env.example .env) and edit .env, at least updating the APP_SECRET_TOKEN variable._"

You get the SECRET_TOKEN by running "rake secret" according to the .env file. However, when you do that, you get:

"git://github.com/wunderlist/omniauth-wunderlist.git (at d0910d0@d0910d0) is not yet checked out. Run `bundle install` first._"

if you run run bundle install, you get:
error: cannot open .git/FETCH_HEAD: Permission denied

Retrying git fetch --force --quiet --tags "/home/StakFallT/.bundle/cache/git/faraday_middleware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b" due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags "/home/StakFallT/.bundle/cache/git/faraday_middleware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b"` in directory /usr/lib64/ruby/gems/2.1.0/bundler/gems/faraday_middleware-c5836ae55857 has failed.
If this error persists you could try removing the cache directory '/home/StakFallT/.bundle/cache/git/faraday_middleware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b'
error: cannot open .git/FETCH_HEAD: Permission denied

Retrying git fetch --force --quiet --tags "/home/StakFallT/.bundle/cache/git/faraday_middleware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b" due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags "/home/StakFallT/.bundle/cache/git/faraday_middleware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b"` in directory /usr/lib64/ruby/gems/2.1.0/bundler/gems/faraday_middleware-c5836ae55857 has failed.
If this error persists you could try removing the cache directory '/home/StakFallT/.bundle/cache/git/faraday_middleware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b'
error: cannot open .git/FETCH_HEAD: Permission denied

Retrying git fetch --force --quiet --tags "/home/StakFallT/.bundle/cache/git/faraday_middleware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b" due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags "/home/StakFallT/.bundle/cache/git/faraday_middleware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b"` in directory /usr/lib64/ruby/gems/2.1.0/bundler/gems/faraday_middleware-c5836ae55857 has failed.
If this error persists you could try removing the cache directory '/home/StakFallT/.bundle/cache/git/faraday_middleware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b'
error: cannot open .git/FETCH_HEAD: Permission denied

Git error: command `git fetch --force --quiet --tags "/home/StakFallT/.bundle/cache/git/faraday_middleware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b"` in directory
/usr/lib64/ruby/gems/2.1.0/bundler/gems/faraday_middleware-c5836ae55857 has failed.
If this error persists you could try removing the cache directory '/home/StakFallT/.bundle/cache/git/faraday_middleware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b'

and yeah, I dumped the .bundle directory. I've even tried just removing the specific directory it mentioned (/home/StakFallT/.bundle/cache/git/faraday_middleware-c881d4de2a647f87ad56e89f17bf2b22bf19b28b) and that's a no go.  At this point I don't know whether it's a distro issue or a huginn issue. I even tried redownloading it. I also own the directory and have rwx permissions on it for the owner and group. I'm kinda lost.

**Comment by virtadpt** [comment]
How did you install Ruby?

Did you do the checkout and other stuff as the root user, with sudo, or as yourself (i.e., an unprivileged user)?

**Comment by StakFallT** [comment]
I think they may have come preinstalled or were installed due to requirements of other packages. But they would have come from my distro's repo using zypper or Yast.

**Comment by virtadpt** [comment]
Try using [RVM](https://rvm.io/) to install a more up-to-date copy of Ruby in your home directory, make sure it comes before the system-wide Ruby (or uninstall it entirely), and use that to install Huginn.  That's what quite a few of us do, myself included.

**Comment by StakFallT** [comment]
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux-gnu] isn't new enough?

**Comment by StakFallT** [comment]
ok I think I may finally have it working. Here's the steps so far (for anyone else that's having difficulty)
goto https://rvm.io
find the section that says:
Cut Rubies with ease!

Install RVM:
and use the two commands they provide in a terminal window. At the time for me it was:
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

and

\curl -sSL https://get.rvm.io | bash -s stable

then install the latest ruby version (for me at this time is 2.3.1) by doing:
rvm install 2.3.1

then do:
rvm use 2.3.1 --default
You may get a warning/error about this but that's fine for now
next do this:

then confirm by doing:
rvm list

you should see something like:
rvm rubies
=* ruby-2.3.1 [ x86_64 ]
# => - current
# =* - current && default
#  * - default

the ruby-2.3.1 part was in bright green

if at any point you receive this error:
RVM is not a function, selecting rubies with 'rvm use ...' will not work.
You need to change your terminal emulator preferences to allow login shell.
Sometimes it is required to use `/bin/bash --login` as the command.
Please visit https://rvm.io/integration/gnome-terminal/ for an example.

do this:
source ~/.rvm/scripts/rvm

This will cause rvm to become a function in the instance. This will most likely not be permanent. You can follow:
http://stackoverflow.com/questions/9336596/rvm-installation-not-working-rvm-is-not-a-function
for instructions on making it permanent.


then do:
gem install bundler

now you should be able to go back into your huginn directory and do:
bundle

I'm certain there's a much cleaner way to do this and perhaps one with less warning/errors. So if it can be improved please do so and maybe should we should look at getting this inserted into the documentation. The documentation is pretty light. It follows more along the lines of: install this here and use that -- for example:
"_Step 2 - Install ruby and gem

Install ruby (2+ recommended but 1.9.3 should work) and gem. You can either download them and compile manually or install via your OS' package manager (e.g. homebrew for Mac OS X or apt for Ubuntu). We recommend using rvm or rbenv. You will also need MySQL or Postgres, both of which can also be installed via your package manager._"

**Comment by virtadpt** [comment]
Using RVM to install Ruby is pretty much the most stable way of doing it because very few distros are up to date insofar as their packaged Ruby environments are concerned (lots of gems just aren't compatible).

Try updating [the wiki page](https://github.com/cantino/huginn/wiki/Novice-setup-guide) with your comment on this ticket - the syntax is pretty straightforward.

**Comment by StakFallT** [comment]
Well I wouldn't mind putting that info in the wiki, but I'm sure the process can be refined a bit better. I also had to pop open new terminal windows for certain things to take affect so I could continue with the process. I don't want to put incomplete info in it. Unless you think that would be ok and the community would just refine it as time goes on?

**Comment by cantino** [comment]
Or maybe make a new page for installing rvm on OpenSUSE, and link it from the novice guide?

**Comment by StakFallT** [comment]
Good idea! I'll do just that soon as I get a chance (when I get to work later and things are slow). I always feel good when I can contribute something back! Glad to help out :)

If I get motivated I may clone one of my OpenSUSE VM's that haven't had it installed and do it again from scratch documenting each step. My OpenSUSE VM's are NON-Leap since I had created them before Leap 42.1 (I think it was .1) was put out, my 2nd job's main computer IS OpenSUSE Leap though so I might also do one for LEAP as well. By then I should have it down pretty pat.


_On a side note: would still LOVE to see MongoDB support :/ But I imagine it would be brutal making the feature since the DB code is pretty deep in the core of source huh?_

**Comment by StakFallT** [comment]
Just an short update: OpenSUSE 13.2 install writeup for wiki page is coming along NICELY, I DEFINITELY will need to fix it up a bit. One thing I realize now that I CANNOT believe I didn't do was screenshots!!! :(

Anyhow, it's taking a really long time, I'm detailing out as much as I can. I'm really hoping the community can help make it better but once it's up, it should be a good launchpad to build on.

**Comment by cantino** [comment]
Hey @StakFallT.  Appreciated!  Yes, Mongo support would be a large undertaking :)

**Comment by StakFallT** [comment]
My pleasure.

Just finished completing the steps and documenting it. Now to get it in a wiki and start formatting it.

**Comment by StakFallT** [comment]
It's up:

https://github.com/cantino/huginn/wiki/OpenSUSE-13.2---From-distro-install-to-installed-Huginn

It's also linked in the Novice guide.

**Comment by cantino** [comment]
Thanks @StakFallT!

**Comment by StakFallT** [comment]
My pleasure

Sorry the formatting is pretty crappy. I kind've feel like the particular wiki engine used on GitHub isn't exactly the most robust.

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.
