### ISSUE TITLE
How to get twitter count of URL using TwitterSearchAgent

### ISSUE THREAD

**Issue by Avalanchaa** [cantino/huginn#1580]
Help wanted.

I am building and RSS aggregator and would like to know the popularity on twitter by counting the number of tweets for links using TwitterSearchAgent which receives links from a DataOutputAgent.

The first step is to test TwitterSearchAgent can count tweets. I am having below code without results

```
{
  "search": "http://www.bbc.com/news/uk-36742691",
  "expected_update_period_in_days": "2"
}
```

The output I expect is a merge from previous RSS invoirmation plus a "count" field with a numerical value for each link.
Does someone knows if this is possible or if I am doing something wrong?  - if not possible, any similar way to know if URLs are popular and rate them?

**Comment by dsander** [comment]
Hi @Avalanchaa,

try setting the `starting_at` option of the agent like so:

```
{
  "search": "http://www.bbc.com/news/uk-36742691",
  "expected_update_period_in_days": "2",
  "starting_at": "Mon Jun 02 00:38:12 +0000 2014"
}
```

This will output an event for every tweet that includes the search term, I think that you'd need a `JavascriptAgent` to do the counting. If you are only interested in live tweets the `TwitterStreamAgent` with `generate=counts` could be a better option.

**Comment by Avalanchaa** [comment]
Is there any way to include the date as "last 7 days" or an easy format like "YYYYmmdd"?

On the output:
As I would like TwitterSearchAgent to receive "search:" terms from RSS feed and output the count for each search term in RSS format (with a merge), I am afraid that I will need to take a look at another option. Or do you think this is possible with Huginn?

**Comment by dsander** [comment]
I think it would require a complex scenario of multiple Agents, but it should be doable. You can use a `JavaScriptAgent` to generate the timestamp `new Date((new Date()) - (24 * 7 * 3600 * 1000))`. Then send the string to a `CommanderAgent` which reconfigures the `TwitterSearchAgent` and use a second `CommanerAgent` to run the twitter search. Counting and aggregating the results would require another `JavaScriptAgent`. The trickiest part is probably to run the search for every item you received in the incoming RSS.

**Comment by Avalanchaa** [comment]
Thanks @dsander , I found how it should be done:
-Get search tweets [https://dev.twitter.com/rest/reference/get/search/tweets](url)
-From the result, count retweets and favourites from all feeds resulted

This could be an slight modification of TwitterSearchAgent, all results must come into a single item and output the sum of all retweets and favourites. I will leave the issue here in case somebody else is interested on so we can collaborate.

**Comment by dsander** [comment]
If we modify the TwitterSearchAgent to emit an array of all tweets, I wonder if the counting could be done by liquid. You would like to get a sum of all retweet and favourite counts for tweets of the search, right?

**Comment by Avalanchaa** [comment]
Yes, with dev.twitter parameters on GET/Search (with value count =  100, which is the max - default is 15), count must be:

number of items + sum of each item `retweet_count` value + sum of each item `favorite_count` value

**Comment by Avalanchaa** [comment]
Closing the issue.
