### ISSUE TITLE
Can't run db:migrate -- Due to special characters in the password

### ISSUE THREAD

**Issue by Skarlso** [cantino/huginn#1584]
Hi everyone. 

After setting everything up, and trying to run db:migrate, I'm getting this error:

```
Psych::SyntaxError: (<unknown>): did not find expected tag URI while parsing a tag at line 8 column 13
<omitted>/huginn/huginn/config/initializers/action_mailer.rb:3:in `<top (required)>'
```

I followed it back to the point where it's trying to parse the smtp.yml config file, for which it fails on this line: 

```
password: <%= ENV['SMTP_PASSWORD'] || "" %>
```

I'm seeing here that it's trying to get it from ENV, so I tried sourcing the .env file, even though no documentation said I should, so... I'm lost at this point at what might be wrong. I have my .env SMTP_PASSWORD setup correctly as well. 

Though I'll have another concern that I'm using MFA with gmail and I have no idea how that will work with email sending. But that's another problem for later.

*EDIT*: So, I found out that if I leave it with data like, asdf@gmail.com and password is also asdf than it migrates fine. Which leads me to believe that there is some escape problem that happens when a password has special characters? And I was right. 

You need to escape special character in the PASSWORD!! That's a bug. :)

**Comment by dsander** [comment]
Hi @Skarlso,

does it work as well when you put the password in double quote?

**Comment by Skarlso** [comment]
Hi @dsander.

Nope, it did not. I did try that. Double quote didn't save the day. :/

**Comment by dsander** [comment]
I tried a bunch of special characters, but was not able to trigger the exception you got. Do you know which character is causing the issue?

**Comment by Skarlso** [comment]
Exclamation mark.

**Comment by virtadpt** [comment]
MFA is set up... did you set up an application password in your Gmail account?

**Comment by dsander** [comment]
@Skarlso Thanks, with a leading exclamation mark I was able to reproduce the problem.

@cantino Do you know if there is a reason why we still have the `smtp.yml` and `database.yml`? At the moment we parse the config out of the `.env` file, then write them to an `.yml.erb` template and parse the generated YAML. As I see it we could directly use the config in `ENV` to configure both the database and ActionMailer and skip the YAML serialization.

**Comment by cantino** [comment]
@dsander I can't think of any good reason, no.

**Comment by Skarlso** [comment]
@dsander Yeah, sorry, I forgot to say that it's leading mark. :/ Well done, for finding it. :)

**Comment by dsander** [comment]
@Skarlso This should be fixed now, do you mind testing if it works without escaping the exclamation mark?

**Comment by Skarlso** [comment]
Sure, I'm going to try this today. Thanks!

**Comment by Skarlso** [comment]
Hey, 

Yep, verified that it works. Thanks!

Gegrely.

**Comment by dsander** [comment]
Thanks for verifying!
