### ISSUE TITLE
How to pull web pages using non UTF-8 character set?

### ISSUE THREAD

**Issue by vivagonna** [cantino/huginn#1588]
I'm trying to pull some web pages with website agent but get stuck at an error:
`ERROR -- : Error when fetching url: invalid byte sequence in US-ASCII`
I have tried almost every possible header configuration but it still doesn't work. I realized that the page is not using UTF-8 character set. In the html there is such a line indicating that it is encoded in "gbk" character set. (It is a page with Chinese charaters.)
`<meta http-equiv="Content-Type" content="text/html; charset=gbk" />`
Just wondering is it possible to decode html in gbk instead of UTF-8 in website agent?
Thanks.

**Comment by dsander** [comment]
I think the problem is that your system does not have `LANG` or `LC_ALL` set to `utf-8`, you can check that with running `locale`. To change the default locale settings edit `/etc/default/locale` to this:
```
LANG="en_US.UTF-8"
```
run `sudo locale-gen` afterwards, open a new shell and verify the `locale` is now UTF-8. When you restart Huginn it should work with unicode characters.

**Comment by vivagonna** [comment]
Thank you very much dsander. But I think I didn't descript my situation clearly enough. My system environment is "en_US.UTF-8" all the way, so it is with MySQL. And it have no problem for Huginn to handle UTF-8 web pages (either with English or Chinese characters). However, the web page I mentioned above is not UTF-8. Instead, the html header shows it is "gbk", an out-of-date character set for Chinese. Just guess that the problem is website agent expected an UTF-8 page but received a page it couldn't decode. But I'm not sure. I tried setting the Website agent's header "force_encoding" to "UTF-8" or "gbk", but it didn't work. I also tried pulling the page with `curl `command and found the Chinese characters in html are garbled in my terminal, while other UTF-8 page with Chinese can display correctly. 

And, I followed your suggestion to make sure the setting is correct before I tried again, but the error was still there.

**Comment by dsander** [comment]
Ah, sorry I misread that. Can you try to replace [this line](https://github.com/cantino/huginn/blob/master/app/concerns/web_request_concern.rb#L50) with:
```
body.encode!(Encoding::UTF_8, encoding, undef: :replace, replace: '?')
```

restart Huginn and rerun the WebsiteAgent with `force_encoding` set?

**Comment by vivagonna** [comment]
Hi, thanks. I think that is a good ides. But I'm sorry to say that it doesn't work. The good news is: I tried to append `iconv -f gbk -t utf-8` command to `curl` in shell and managed to get the html displayed correctly. That means, I can circumvent this problem by using the ShellCommand Agent to curl the page and pass the output to the WebsiteAgent. 

Another finding during the tests is, that even I switched the whole environment to "GBK", the html was still garbled in terminal (Even worse, not only Chinese characters but also English characters became garbled). Anyway, it is very strange.

**Comment by cantino** [comment]
Hi @vivagonna, could you share what URL you're trying to fetch, or the JSON options of the Agent that was erroring?

**Comment by vivagonna** [comment]
Hello Cantino! Sure, here it is: `https://s.2.taobao.com/list/list.htm?st_edtime=1&q=%B2%A9%CA%C0+%B5%E7%C6%F0%D7%D3&ist=0 ` which is a second-hand exchange platform : )

**Comment by vivagonna** [comment]
Thanks a lot! The patch fixed this issue perfectly! I'm gonna close this issue. :+1:

**Comment by brianpetro** [comment]
Just pulled the latest updates and I'm not sure why this code is giving me this error `uninitialized constant Faraday::Encoding::BINARY`

**Comment by cantino** [comment]
Which line is erroring for you?
