### ISSUE TITLE
Rate limit exceeded  in agent Twitter Favorites 

### ISSUE THREAD

**Issue by alejandrohn** [cantino/huginn#1594]
Hello, i am building an agent Twitter Favorites, i'm create a service with my account of twitter  everything OK but  in the Twitter Favorites i want to fallow VHMok 

{
  "username": "VHMok",
  "number": "5",
  "history": "5",
  "expected_update_period_in_days": "2",
  "starting_at": "Tue Jul 19 20:59:00 -04:00 2016"
}

response error:  Rate limit exceeded

Rate limit exceeded
/home/rails/.rvm/gems/ruby-2.2.2@huginn/gems/twitter-5.14.0/lib/twitter/rest/response/raise_error.rb:15:in `on_complete'
/home/rails/.rvm/gems/ruby-2.2.2@huginn/gems/faraday-0.9.1/lib/faraday/response.rb:9:in`block in call'
/home/rails/.rvm/gems/ruby-2.2.2@huginn/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
/home/rails/.rvm/gems/ruby-2.2.2@huginn/gems/faraday-0.9.1/lib/faraday/response.rb:8:in`call'
....

**Comment by cantino** [comment]
This means you're using the Twitter API too quickly.  You'll need to slow down the rate of actions you perform.

**Comment by alejandrohn** [comment]
Thanks, it was that

change Schedule to Schedule: Every 1h
