### ISSUE TITLE
Can't get huginn to redirect to right domain

### ISSUE THREAD

**Issue by erikthorselius** [cantino/huginn#1599]
I'm using the docker image on my own server but I after a login or logout huginn will redirect to http://huginn instead of https://huginn.mydomain.com. In the logs i can see `Jul 22 21:41:27 marv.mydomain.com docker[20331]: foreman stdout | 19:41:24 web.1  | [c60d1a97-8d70-4eaa-b5f0-33c462660b0d] Redirected to http://huginn/users/sign_in`

I can see that the values looks right if I run docker exec and look with `env`. I tried both HUGINN_DOMAIN=huginn.mydomain.com
DOMAIN=huginn.mydomain.com

but huginn is still redirecting to the wrong adress. Other things as mail and db works fine setting via env. 

The image I'm using is: cantino/huginn:latest. How to I make huginn to redirect to the right domain?

**Comment by dsander** [comment]
Hi @erikthorselius 

have you tried settings `FORCE_SSL=true` when you create the container? I have not tried it myself but that might work. I am using nginx to do the SSL termination with a server block that redirects all requests to the SSL endpoint:
```
server {
  listen 80;
  server_name huginn.mydomain.com;
  server_tokens off;
  ## root doesn't have to be a valid path since we are redirecting
  root /nowhere;
  rewrite ^ https://$server_name$request_uri permanent;
}
```

**Comment by erikthorselius** [comment]
Hi, I tried the FORCE_SSL=true and it got worse. Now i'm redirected to from https://huginn.mydomain.com -> https://huginn every request. 

I also have a nginx infront that terminates ssl but I'm using the proxy_pass.

```
server {
  listen 443 ssl;

  server_name huginn.mydomain.com;

  include conf.d/locations/*.conf;

  location / {
    auth_request /oauth2/auth;
    error_page 401 = /oauth2/start?rd=/huginn;
    proxy_pass  http://huginn;
    proxy_redirect     off;
  }
}
```

**Comment by albertsun** [comment]
I wonder if there's some escaping problem in setting the environmental variable where everything after the `huginn.` is getting cut off?

How are you running the docker image?

**Comment by erikthorselius** [comment]
My docker command from my service file is:`ExecStart=/usr/bin/docker run --rm -p 3001:3000 --env-file="/home/huginn/huginn.env" --name ${CONTAINER} ${IMAGE}`

All other environment variables looks good. Huginn picks up db and mail settings.

**Comment by erikthorselius** [comment]
I peaked inside the container and the .env file is missing the HUGINN_DOMAIN env variable. I see it when running `env`. And it is in the input envfile.

```
core@host /home/huginn $ docker exec -it huginn bash
root@4c87a3b06241:/app# cat .env|grep DOMAIN
DOMAIN=huginn.mydomain.com
SMTP_DOMAIN=mydomain.com
root@4c87a3b06241:/app# env |grep DOMAIN
SMTP_DOMAIN=mydomain.com
DOMAIN=mydomain.com
HUGINN_DOMAIN=huginn.mydomain.com
root@4c87a3b06241:/app# exit
core@host /home/huginn $ cat huginn.env |grep DOMAIN
HUGINN_DOMAIN=huginn.mydomain.com
DOMAIN=huginn.mydomain.com
SMTP_DOMAIN=mydomain.com
core@host /home/huginn $
```

**Comment by erikthorselius** [comment]
Sorry, I see now that none of the variables are prefixed

**Comment by dsander** [comment]
Yes the "rewriting" from HUGINN_* to * is expected, we are doing that to be backwards compatible with a old version of the docker image.

Your redirection errors are really odd, I removed my http->https redirection in nginx, set `FORCE_SSL=true` and I can log into Huginn without issues. Maybe setting additional proxy header options will help, this is my SSL server block:
```
server {
  server_name huginn.mydomain.com;

  listen 443 ssl;
  ssl_certificate /etc/nginx/ssl/cert.pem;
  ssl_certificate_key /etc/nginx/ssl/cert.key;

  ssl_ciphers 'ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4';

  ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
  ssl_session_cache  builtin:1000  shared:SSL:10m;

  ## Enable OCSP stapling to reduce the overhead and latency of running SSL.
  ## Replace with your ssl_trusted_certificate. For more info see:
  ## - https://medium.com/devops-programming/4445f4862461
  ## - https://www.ruby-forum.com/topic/4419319
  ssl_stapling on;
  ssl_stapling_verify on;
  ssl_trusted_certificate /etc/nginx/ssl/stapling.trusted.crt;
  resolver 8.8.8.8 8.8.4.4 208.67.222.222 208.67.222.220 valid=300s;
  resolver_timeout 10s;

  ssl_prefer_server_ciphers   on;
  ## [Optional] Generate a stronger DHE parameter (recommended):
  ssl_dhparam /etc/nginx/ssl/dhparam.pem;

  add_header Strict-Transport-Security max-age=63072000;
  add_header X-Frame-Options DENY;
  add_header X-Content-Type-Options nosniff;

  gzip on;

  access_log /var/log/nginx/huginn_access.log combined;
  error_log  /var/log/nginx/huginn_error.log;

  rewrite_log on;

  # use the application's 500.html page
  error_page 500 502 503 504 /500.html;

  # allow clients to upload large files (if necessary)
  client_max_body_size 4G;

  location / {
    proxy_pass        http://localhost:3000;
    proxy_redirect    off;

    proxy_set_header  Host                $http_host;
    proxy_set_header  X-Real-IP           $remote_addr;
    proxy_set_header  X-Forwarded-Ssl     on;
    proxy_set_header  X-Forwarded-For     $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto   $scheme;
    proxy_set_header  X-Frame-Options     SAMEORIGIN;

    client_max_body_size        100m;
    client_body_buffer_size     128k;

    proxy_buffer_size           4k;
    proxy_buffers               4 32k;
    proxy_busy_buffers_size     64k;
    proxy_temp_file_write_size  64k;
  }
}

``

**Comment by erikthorselius** [comment]
The extra headers in location block works as a charm! Thanks for all the help!
