### ISSUE TITLE
heroku run rake db:migrate → fatal: Not a git repository (or any parent up to mount point /app)

### ISSUE THREAD

**Issue by DreamFlasher** [cantino/huginn#1601]
I try to update my huginn installation. I use the same repo I used for deploying, git fetch, merge, push works successfully. 
`heroku run rake db:migrate`
yields:
`fatal: Not a git repository (or any parent up to mount point /app)`
`Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).`

**Comment by dsander** [comment]
The `fatal` messages are coming from rubygems that are not set up properly, even though it says fatal it does not matter. When you did not get any other messages your database was already up to date and Huginn should be running without issues.

**Comment by DreamFlasher** [comment]
I didn't get any other error messages and huginn also runs smoothly -- `fatal` sounded pretty bad, if it's not a problem I'll close the issue :) Thank you!
