### ISSUE TITLE
Post Agent headers can't take in event data?

### ISSUE THREAD

**Issue by WangQiru** [cantino/huginn#1603]
In Post Agent, **Payload** field is able to load data from source, **Headers** isn't.

For example:

```
"headers": {

 "time": "{{time}}"

 }
```

Where {{time}} is a string.

![](https://s6.postimg.org/lrj3im82p/image.png)

Time field in **headers** can't take in any data.

However it works if I change it to this:

```
"headers": {

 "time": "2016-01-01"

 }
```

![](https://s6.postimg.org/r5hvq5xsx/image.png)

Which defeats my purpose... 

Any workaround?

**Comment by cantino** [comment]
Hey @WangQiru.  I think you found a bug-- we don't interpolate the outgoing Headers with the incoming event.  #1606 should fix it.  Would you mind testing?

**Comment by WangQiru** [comment]
#1606 works now. @cantino
