### ISSUE TITLE
Can't send mail : end of file reached /usr/lib/r..... `read_nonblock'

### ISSUE THREAD

**Issue by kornflex** [cantino/huginn#1604]
Hi,

I'm using Huginn in docker with Gmail account to send mails.

I'm trying to use huginn like this : RSS feed to email.

With the email trigger, I have this error :  	end of file reached /usr/lib/ruby/2.2.0/net/protocol.rb:153:in `read_nonblock'

My password had special caracters, so I used quote : same thing.
I changed it with no special caracters : same thing.

I changed the email agent to send basic email : 

{
  "subject": "You have a notification!",
  "headline": "Your notification:",
  "expected_receive_period_in_days": "2"
}

Same thing.

Do you have any ideas ?
Thanks

**Comment by cantino** [comment]
Are you sure you have the email server and port configured correctly in your environment settings? This could happen if the mail server isn't responding.

See this thread from a different project: https://github.com/sameersbn/docker-gitlab/issues/170

**Comment by kornflex** [comment]
I'm think yes because I had an other error with gmail plain / 587. I had to change for login / 465
![mail](https://cloud.githubusercontent.com/assets/5457493/17101464/021bd38c-5275-11e6-89ad-d397316f0f13.png)

**Comment by cantino** [comment]
It looks like 587 is the correct one.  http://serverfault.com/questions/395359/is-the-legacy-smtp-client-submit-port-456-or-465-what-is-the-history-of-thi

**Comment by kornflex** [comment]
Hi,

Thank you ! 
This is my config : 
Same as the picture but with 587 port.


And accept less secure apps : 
https://www.google.com/settings/security/lesssecureapps
