### ISSUE TITLE
RSS Feed to Wordpress Post : howto add tags and categories

### ISSUE THREAD

**Issue by kornflex** [cantino/huginn#1609]
Hi,

I'm using some RSS Feeds to publish in my personnal wordpress blog using email.

It's easy : 
**Create a RSS agent with this :** 
{
  "expected_update_period_in_days": "5",
  "clean": "false",
  "url": "http://www.domain.com/feed"
}

**And an Email agent :** 
{
  "subject": "{{title}}",
  "expected_receive_period_in_days": "2",
  "body": "{{description}}<br><br>Source de l'article : {{url}} [category vehicule][tags {{categories | join: ', '}}][status publish]"
}

It's working, each RSS Feed add multiple tags and I take them but I need to add a static one.
So I tried to edit my RSS agent and configure it like this : 

{
  "expected_update_period_in_days": "5",
  "clean": "false",
  "url": "http://www.domain.com/feed",
  **"WPTags": "StaticOne"**
}

And edit Email agent : 
{
  "subject": "{{title}}",
  "expected_receive_period_in_days": "2",
  "body": "{{description}}<br><br>Source de l'article : {{url}} [category vehicule][tags **{{WPTags}},**{{categories | join: ', '}}][status publish]"
}

It doesn't work. How to get the value ?

Thank you

**Comment by dsander** [comment]
Hi @kornflex,

I assume you want to use one EmailAgent with multiple RssAgents? You put a `EventFormattingAgent` between them with `mode` set to `merge` and put the static value in `instructions`.

**Comment by kornflex** [comment]
Yes.  I want to use only one email agent because it is always the same except two parameters ! It will be easier for me to manage. 

I will try this agent. I tried with a websiteagent like the howto to make rss for a websiteagent which doesnt have. 

Thanks

**Comment by kornflex** [comment]
Thank you for the tip, it's working great !

**Comment by dsander** [comment]
Awesome!
