### ISSUE TITLE
SMTP.yml - new SMTP problems

### ISSUE THREAD

**Issue by bobbysteel** [cantino/huginn#1611]
I did my periodic update for the first time in a month or so yesterday and SMTP has now broken for me. I see a commit in the recent commits as removing smtp.yml, but I had all my config in the .env anyways. Any ideas why a plain localhost SMTP server is now not authenticating despite having set type as "plain"?

**Comment by bobbysteel** [comment]
Hm, after a bunch of playing around it seems the .env variables aren't being accepted. In my config I needed to disable TLS for example and only editing the config/initializers/action_mailer.rb settings actually seem to work in the changes. Did that last commit from @dsander somehow override the .env variables?

**Comment by cantino** [comment]
Hey @bobbysteel, that certainly wasn't the intention. Are other .env settings being loaded for other parts of Huginn?

**Comment by bobbysteel** [comment]
Everything else seems to be fine with the other .env variables. Database access is good as usual. It's just ignoring the old .env settings it seems. I can try and troubleshoot it some more but was wondering if anyone else was seeing this. I haven't done a line by line test to see if it's ignoring everything but at least some of the paramaters like autostart TLS didn't seem to be honored in the .env but in the main.rb file though.

**Comment by dsander** [comment]
@bobbysteel That is odd, I did not have issue with the smtp configuration after updating, is `enable_starttls_auto` the only setting that is not set correctly?

**Comment by bobbysteel** [comment]
Unfortunately, I wasn't able to test granularly to determine if it was just one setting. My server stopped sending emails entirely with a unable to authenticate error (despite being set to "plain" as auth type). At various points I just switched both files, but it did seem that the "plain" and "starttls" were both ignored in the .env but respected in the main.rb file. Presumably all other .env settings are fine as database etc are still working great.

**Comment by dsander** [comment]
@bobbysteel Thanks, I see. We probably have to wait if we get more issue reports, I don't see how the changes would cause issues, but nothing is impossible :)
