### ISSUE TITLE
UserLocationAgent - Google Maps API requires API key

### ISSUE THREAD

**Issue by saesh** [cantino/huginn#1612]
Hi, I just checked out the UserLocationAgent and the map is not working without an Google Maps API Key. I think it is standard now, that every JavaScript application uses an API Key.

The view should insert a configured key in the `javascript_inlude_tag`:

`<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=[GOOGLE_MAPS_KEY]" %>`

**Comment by cantino** [comment]
Good find @saesh.  Would you be interested in making a PR to add this?  If not, that's fine too. I'll note it as a bug.

**Comment by saesh** [comment]
Sure, I'll give it a go.

**Comment by cantino** [comment]
Awesome! Please let us know if we can help.
