### ISSUE TITLE
depency on tumblr gem for creating a new agent?

### ISSUE THREAD

**Issue by RMHogervorst** [cantino/huginn#1614]
Hi all, I managed to make huginn run on my raspberry pi2, however I commented out things I wouldn't use such as the tumblr gem.
It does run, but when I want to create new agent I recieve an error: 

LoadError at /agents/new
cannot load such file -- tumblr_client
it furthermore shows a live shell and application frames and other things I don't understand.

Do I really need the tumblr gem? from

**Comment by knu** [comment]
Hi, did you run `bundle` and then restarted the processes after modifying Gemfile?

**Comment by RMHogervorst** [comment]
yes I did, however I also changed some other things, I will let you know when it works again.  But this comfirms that I need the tumblr things right?

**Comment by cantino** [comment]
Hey @RMHogervorst. You should be able to comment out `tumblr_client` and `omniauth-tumblr` in your Gemfile, run `bundle`, and Huginn should work (except that you can't use the tumblr Agent then).

**Comment by cantino** [comment]
Would you mind giving #1615 a try?

**Comment by RMHogervorst** [comment]
I'm on it, I made the mistake to sudo bundle install. I'm still dealing
with the permission problems after that.

Op 3 aug. 2016 16:50 schreef "Andrew Cantino" <notifications@github.com>:

**Comment by dsander** [comment]
@RMHogervorst `sudo chown -R huginn:huginn /home/huginn` or removing `/home/huginn/huginn/vendor/bundle` might help.

**Comment by RMHogervorst** [comment]
yes, this fixed the problem. I now can enter the new agent screen. Thanks! :+1:

**Comment by cantino** [comment]
I've merged the PR.  Thanks for letting us know!
