### ISSUE TITLE
IMAP Folder Agent is not working properly

### ISSUE THREAD

**Issue by Noyalcitrus** [cantino/huginn#1616]
Hai, I am using the IMAP Folder Agent and monitoring the mails receiving on specified mail address, and its working fine for 20 to 25 days or more after some days I can't able to monitor the mail the log showing like(Connecting to imap.gmail.com via SSL,Selecting the folder: INBOX,0 new mails) . When I create a new Imap Folder Agent with same mail address that will be working fine and I can able to monitor the mail but on the same time the old IMAP Folder Agent is not working its logging (Connecting to imap.gmail.com via SSL,Selecting the folder: INBOX,0 new mails)

**Comment by cantino** [comment]
Hmm, that's odd.  Would you be able to share the memory from the Agent? You can see it at the bottom when viewing the agent.  @knu might have an idea here.

**Comment by Noyalcitrus** [comment]
{
  "notified": [
    "CAPTP29hVoJMx-hyD_J6V+ibo-ghgmPp3mJe7FuXfhaasDmuuTA@mail.gmail.com",
    "CAPTP29gnuZeobuFNU3gNsz5nU8wOgT68tzyqVcx-R61MCPeFMA@mail.gmail.com",
    "CAPTP29gSCfUhRfX4q-jqhcTRM1Q4j24oLb5s=anCtOsg=m13-A@mail.gmail.com",
    "CAPTP29iZAjjCP0vOP8OpYQBvfDXD6eVY2eEYyWTwbwDo3-tzqg@mail.gmail.com",
    "CAPTP29jG6yWA26rLQN5X=7ND+hvLm01K3CmFSKcabDx7nprsbw@mail.gmail.com",
    "CAPTP29gvBKdkK2p63x=NupN17DZaaXWVVVpMRA31WCrhjdORRQ@mail.gmail.com",
    "CAPTP29iyBNY7oFsFAMn1BGeX5_oEWej-uyaF7HbXyQskUOVmYQ@mail.gmail.com",
    "CAPTP29gstO6z4vybD7jT9Dn+vxUTN0uZc_dM8TESBXiD8p2T8g@mail.gmail.com",
    "CAPTP29jhyFruO6u7ggAQWoPzeXFA_X-bJHNfd-ff8GMxx-3tgA@mail.gmail.com",
    "CAPTP29j=6J93tas4WK_WzUm+hPLREyauuGcBuCbqchaL2=hW4Q@mail.gmail.com",
    "CAPTP29ienVRb_a=fHTcrtdSbLPowaFnrkDUnrB4eOHfY8n-8ag@mail.gmail.com",
    "CAPTP29j7ymOekPeqPdFgPmok-zQkqe1fiT0w+qdVmJqkB5WEFQ@mail.gmail.com",
    "CAPTP29hdCMgsvsy0uREKm9HvKhDCLvH-uDNEGXO3zgx_gqQkCg@mail.gmail.com",
    "CAPTP29js4jzK_LUgrhEZxymd8-+DvMkrzqfx_FaKfVg4Xosp3g@mail.gmail.com",
    "CAPTP29iGR7ivDK3Hhn28v45n7MknOUm+8E8VnQVeY-bsyUnMSQ@mail.gmail.com",
    "CAPTP29iV21e7iDcdnn4t+U_y_Jn2TWPVCCd2_5LUrAsB9LgwaQ@mail.gmail.com",
    "CAPTP29jYT7B-45S6FxCo5iQOK326QsLSb6Gk45arxQW+qH4eEw@mail.gmail.com",
    "CAPTP29iCcLF4jArkjTBkcW95FSK425Aw3p-jbxrTuT1DJf_=+w@mail.gmail.com",
    "CAPTP29hCYm-c7D3+GQ_v_u_KW-h+OvCvREKTmpnjge1RDjp-WA@mail.gmail.com",
    "CAPTP29hhUeNOiXR4gEEGAOougA5j9OPMovepuzaVEfHFDVGBBA@mail.gmail.com",
    "CAPTP29iLyHtNo2WeTsYe6HNUkXRKMb7NbHM5HtU0JOrDnyLEmQ@mail.gmail.com",
    "CAPTP29jJ3czViaTspGhgJ+Cg4QEi1h73-B8cMxseGKQABxvQ0w@mail.gmail.com",
    "CAPTP29geD0L=VERM69pmePTFKjOdoeFvoVGRMaX+-QhGvfkgwA@mail.gmail.com",
    "CAPTP29hhj=Gs-uNdGdB7nwEbJXcm_k8ZCypVxwNLc2o+CKxq9w@mail.gmail.com",
    "CAPTP29hVYeq3hooetcEt23TiQzU93c3GPQpDaQZj-SnLFPBVhw@mail.gmail.com",
    "CAPTP29hxNfxJjjDkofn2ogAk7d5+EkQsJ9_4zYmiLDqh+=8=1Q@mail.gmail.com",
    "CAPTP29gRSQhLMZRk_b1u9CJSgHOATad1mnRBD+E1CSY=5_i8Mw@mail.gmail.com",
    "CAPTP29ic2JuDe0ti=vhvtL2-2tr+xxFNgFkBJLz=m7qinJDnqA@mail.gmail.com",
    "CAPTP29jtj8U0z-sbW_CW+yvk1_v6gD0W1pQCgfPmFLQ5O_5=zQ@mail.gmail.com",
    "CAPTP29h2LhOb3oKcy=iYAzgjKbJvWXWB3AqqmVfPEoBFmCnFzw@mail.gmail.com",
    "CAPTP29izOcUQUE50XHt3ZphN-BQfDyHWiqzLzxy1CYb3rpGHuw@mail.gmail.com",
    "CAPTP29h28EjUbQ4afiucU5DE6ZvgDha9-242m=jb0aJN20amLg@mail.gmail.com",
    "CAPTP29hfYa8v079O5wmijtH9-JNWVskWCN2xmSCMn_EpMyJQZQ@mail.gmail.com",
    "CAPTP29i_rDnjOXzuYZtzYig_X8n7UPuM6BpLovShhFXG1rM_uA@mail.gmail.com",
    "CAPTP29jOuehrK2MgYrXwxqF1X0mQRimCwK33E+Zf3HxenutDyg@mail.gmail.com",
    "CAPTP29ghryrskXT7=pyHfwA9GM5nMh2obv6_H4bHgaakuOr4gA@mail.gmail.com",
    "CAPTP29gjhyiKj-xw1D9nJb1oc=Jh=cPjzKr8hTOZbJLh8mvwaA@mail.gmail.com",
    "CAPTP29grYNQvXW2Uv3+o=WughVAfS+5LkR5XB9RC0eNt-xfnug@mail.gmail.com",
    "CAPTP29hQdMPPN_wnVuifjgb6nJX1xWCdk4BhvB42YiJ=JjpyWg@mail.gmail.com",
    "CAPTP29iMvU2L9uoD9dFRhbrjFT8+nqBqTuvyY3q9F9UhjUgj7w@mail.gmail.com",
    "CAPTP29hW1G0E0y_DauhacH=8ic5gjhUo3ysAvoxq1-+KVFoRww@mail.gmail.com",
    "CAPTP29hgs_MUwK+G4=TN1P=bSC8pFdPcMFsXJ+pSnZRZt6a6Ag@mail.gmail.com",
    "CAPTP29i0fBAwc5w0ohMQ=frV6jC92HvP8sJ4fw5QM-Gcfk6jkA@mail.gmail.com",
    "CAPTP29h5s0N2s3UOcphrZjaYQTZfkKEwYManF7VLswp+g2AOCw@mail.gmail.com",
    "CAPTP29j38XEQhSfL3jq2TtOzruMXjC=XLvgiWWvf5Nw+NFoGhw@mail.gmail.com",
    "CAPTP29ikfrz4KtOB795E25O0wOYFN-9RA3frSkXKuJ2YxWoO+A@mail.gmail.com",
    "CAPTP29jVxwdZ8i30ORjJWPmZgFY3w3NU_bKwvNM0HOcJccOryA@mail.gmail.com",
    "CAPTP29ieKBYBxipPCNJ7T_u3jM29WYXD_RrdEC=FxmQDYE2BwA@mail.gmail.com",
    "CAPTP29i1JPDdEeoSWp_xHM3Gk7Aoo=OZm40uYxoy+SAxyOWsvA@mail.gmail.com",
    "CAPTP29hnSrCPxGy1eELVbYBmNNekPBdn4kNxeOTAnZNwjDpSeQ@mail.gmail.com",
    "CAPTP29gr-D-aBvbMELkLN97wXniW1Dz=ZijuKXma_-F7AYdh=w@mail.gmail.com",
    "CAPTP29h+mKVSvME2__NHSBLdmCbYKCUNhc7=ZFtAxf-T9nZUFA@mail.gmail.com",
    "CAPTP29gYi4G6-QOua=j6W13ik2CKpCZzeT2rbS_8o4wUK=WQ6g@mail.gmail.com",
    "CAPTP29hpZR5eS=eskV79Sde+E37OQRi4GgW91YfFPzo10XOmVQ@mail.gmail.com",
    "CAPTP29gfcr6hiKqJWehhx6KLqgSeWMRo3w6sNWUaEu+kmFNBjw@mail.gmail.com",
    "CAPTP29hj6sSGe4pvO_a+HcxkGRpD9-1+Xzz=n11cmVzp37p+7w@mail.gmail.com",
    "CAPTP29igwzLxAk+aQPuwn8BcY7skJ3FowZ+zs8XNOLzrqWGmKw@mail.gmail.com",
    "CAPTP29iGd1cg1zn_UkYw92Dv3mG+svW_67f4bASRkKKJOwTNgQ@mail.gmail.com",
    "CAPTP29gJMRdO6eqHZmg-unMj0W6ndJww9onou0F5AjkLS+DLzQ@mail.gmail.com",
    "CAPTP29gNATMcQz-Uir=0cYpaMEMq_LdZBJeBw9oxGauCsBkqTA@mail.gmail.com",
    "CAPTP29i2sUjUZtzSKgfGwcJPmVLAZdVVywBNP3qWg_Ur3wD9RQ@mail.gmail.com",
    "CAPTP29hBC1cj0VnEmvx67q4kwsK1tX83sw01=mLfHdDXu=pfKA@mail.gmail.com",
    "CAPTP29jGVcGur+ZjXR9PjpWUDj4eQwNxA1hf+hWQKS50um6SVA@mail.gmail.com",
    "CAPTP29i9fcwxOW5S06tX-kMV5QCNp=mxEEZDYfXs7N1u56mupA@mail.gmail.com",
    "CAPTP29jHJKgpuwD50KYNtxZHdKHj_Cnj54HMGoQmB8YwQgk9Zg@mail.gmail.com",
    "CAPTP29gemMDH5-ZMdDKELtdrN2ptE7rjN4oCXgSNyc0huUmGtA@mail.gmail.com",
    "CAPTP29gJ7BDj7fjLzvkr9DJ_64HMG_AdvUrtWN2EtkMdhFaomQ@mail.gmail.com",
    "CAPTP29jgZf6_a51NZmmdhAn40i=J=-V5-r1S288r8N+FLBfJVw@mail.gmail.com",
    "CAPTP29iHvz2ja=pBTtJRcPab=W6yY54Nq6UzfkAB=Mvp2NM0gg@mail.gmail.com",
    "CAPTP29hRt-8tX-2XyFjLUCTPkeY=ejGgRSPN8R9YvLUN+TU4LA@mail.gmail.com",
    "CAPTP29hpZ5KUkWrge3d8xqdhKNJhCrwAXuwZv=OsrptmhZjOLg@mail.gmail.com",
    "CAPTP29jkzDkFi-HqSACh_FCoqjjhCwaDSGnsH4jPVinizmhgXA@mail.gmail.com",
    "CAPTP29giKpm0mK5y_Dy0SCK+QHaQqnYkKmuw6H4Rx_JssnOX9Q@mail.gmail.com",
    "CAPTP29i5SYQ2NXjtiH=TCUYEuV6ORNwY+f5uJa9=oquBndhwNQ@mail.gmail.com",
    "CAPTP29jRhpP4g5Rk+owCTRaAYU3eR9H8HGZUjiGXEhoaDNHE0Q@mail.gmail.com",
    "CAPTP29jgTJ5LGO3w1P28gBDJtVftp5haRB7s8Vg6c=OUy9-Qzg@mail.gmail.com",
    "CAPTP29iah_Cdb_V-E+2SWZtD77MjGzG3cdLsRUGvcrfpLWNTqA@mail.gmail.com",
    "CAPTP29ghoDk6SnMRM_s2m-x1cLM3ZD+mZzTkt6qBFtjWQAFfPA@mail.gmail.com",
    "CAPTP29gEoAuADb7LzfiH_P59sbtx5vhWAJCV=54USHKUiZTMyw@mail.gmail.com",
    "CAPTP29j4t2iQmarhpen1Hhq5iY9j3VJ=ey9ZKjZ0=J5r71fmwA@mail.gmail.com",
    "CAPTP29i+pEv05uu-S_89B6e68jU5VC-_W2BeO61QMPCaNE1F1g@mail.gmail.com",
    "CAPTP29h=CS0uBkLYBC5v1fzLBOGyeY29=QDVvaB5ZqmC16AWMw@mail.gmail.com",
    "CAPTP29h5H42Fzcn2ovQpOiCLCOp32uQayQeAocftxvjNVBYNZw@mail.gmail.com",
    "CAPTP29jK2yOZ-21SqVb3NhH7W8LeBuhsw=LQMBCZNNcBtSxUww@mail.gmail.com",
    "CAPTP29h0qhUTcJNDj7Z=irhBO3C-iF5FCXp5bDt3w5J8NKV85Q@mail.gmail.com",
    "CAPTP29i+onMw3OvGxtLA-g03RMXa5omJRqn7pMfpw5USCa3LmA@mail.gmail.com",
    "CAPTP29i8=ooGaLctXGrDaii-Lt2X_GJqfMqyETHdLQybye+KSw@mail.gmail.com",
    "CAPTP29j=ZW43zU4CBdiGqsm9geKQZg1V4-h1WHJYqPUW0RrNkg@mail.gmail.com",
    "CAPTP29iBnwqPy5D0NkQNYiPOOphM_D-qSjQ30bUusp_8oAc8mg@mail.gmail.com",
    "CAPTP29ipn5t=YSQkjO+Bpb2rAyNWCb-2kbuNnHPksWzpO3gemg@mail.gmail.com",
    "CAPTP29hUEVL+AxbUfYfFt4ATshhYSt=TbWXASgEtb=dw9pQRwA@mail.gmail.com",
    "CAPTP29jOUfUiyx3mWa6c1ku5CamUkt+PGu3zWDghBcUTDptPZA@mail.gmail.com",
    "CAPTP29iv+qWOUN-+LJ+QZcpGCNT8B_LAh_d7MdjjQUeRg==7oA@mail.gmail.com",
    "CAPTP29gPzfW=MtXFTNe8j8a-xK9YvU+=cE5CG+pJ3n73-aQGUQ@mail.gmail.com",
    "CAPTP29gqQ+D5cNC-kAoQ0pZOY+sWSEWjqYnx4MPQpgBW6eQVQQ@mail.gmail.com",
    "CAPTP29hdUPUecHDkVD87de61X+h2P-=dVC=C+Te8=ifzMXY+aw@mail.gmail.com",
    "CAPTP29j46ygXuEWAVsBBkRjfTp4mf+bh786511g7Xt=XYhi6NA@mail.gmail.com",
    "CA+--th7tAczbOhH3d+V0KRU-Eu6TyubXCbfahuc16zUJee-YgA@mail.gmail.com",
    "CA+--th4LF_GyGTvyXXP9FrcRD1BtsvAZ=dFQL4gK0E-UhB7jgg@mail.gmail.com",
    "193CF60E223F419D93AFB62FD2B227FA@Bhagyalakshmi",
    "291198206.3059606.1470175618451.JavaMail.app@lva1-app2768.prod.linkedin.com"
  ],
  "lastseen": {
    "1": 1177
  }
}

**Comment by Noyalcitrus** [comment]
This is memory from the Agent

**Comment by Noyalcitrus** [comment]
after clear the memory , no notifications are coming

**Comment by cantino** [comment]
If you clear the memory, it should be identical to making a new ImapAgent.  Are there any differences in how they're configured?
