### ISSUE TITLE
examples of trigger agent with type: field >value ?

### ISSUE THREAD

**Issue by RMHogervorst** [cantino/huginn#1617]
I am having some trouble with the trigger agent.
What I want is to create a message when the temperature is above 21 degrees celsius.
I cannot find examples of the type field >= value triggers online. 

This is what I have:

```
{
"expected_recieve_period_in_days": "2",
"message" : "Today blablabla {{high.celsius}}",
"rules" :  
[
{ "path": "high.celsius",
 "value": "21",
"type" : "field>=value"
}
]
}
```

Error message: 
expected_recieve_period_in_days, messag, and rules, with a type, value and path for every rule are required.

**Comment by RMHogervorst** [comment]
When I started with a clean example in stead of the rain notifier example it worked out fine. Although I still would like more examples of all sorts of agents. 
```
{
  "expected_receive_period_in_days": "2",
  "keep_event": "false",
  "rules": [
    {
      "type": "field>=value",
      "value": "21",
      "path": "high.celsius"
    }
  ],
  "message": "Vandaag rokjesdag! temperaturen tussen de {{low.celsius}} en {{high.celsius}} graden."
}

```

**Comment by knu** [comment]
There was a typo in `expected_recieve_period_in_days`: `ie` -> `ei`
