### ISSUE TITLE
Huginn failed to restart after installed node and systemd

### ISSUE THREAD

**Issue by Vin-c-wong** [cantino/huginn#1618]
Hello.
I tried to use systemd on the same Debian server with Huginn. After installation Huginn failed to start:
```
/home/huginn/huginn# sudo bundle exec rake production:start
Startig huginn ...
rake aborted!
'sv start huginn-jobs-1' exited with a non-zero return value: fail: huginn-jobs-1: runsv not running
/home/huginn/huginn/lib/tasks/production.rake:85:in `run'
/home/huginn/huginn/lib/tasks/production.rake:77:in `block (2 levels) in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:93:in `with_retries'
/home/huginn/huginn/lib/tasks/production.rake:76:in `block in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:75:in `each'
/home/huginn/huginn/lib/tasks/production.rake:75:in `run_sv'
/home/huginn/huginn/lib/tasks/production.rake:38:in `block (2 levels) in <top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => production:start
(See full trace by running task with --trace)
```

Thanks a lot.

**Comment by dsander** [comment]
Hi,

it looks like runit is not running anymore, check the contents of `/etc` if its still initialized: `grep -irn runsv /etc/`, on ubuntu trusty it's started in `/etc/init/runsvdir.conf`, for some debian versions it should be in `/etc/inittab`.
You can also try to start it manually with `sudo runsvdir-start`.

**Comment by Vin-c-wong** [comment]
Thanks. 
Created a simple systemd service point to the /usr/sbin/runsvdir-start which solved the problem
`[Unit]
Description=runsvdirstart 
[Service]
ExecStart=/usr/sbin/runsvdir-start
Restart=always`
