### ISSUE TITLE
Add volume to Docker containers

### ISSUE THREAD

**Issue by saesh** [cantino/huginn#1619]
I would like to add a docker volume to the Docker containers to provision files used by some agents, e. g. certificates for the MQTT agent. These files would then also be persistent if the container is updated. The path for the volume would be `/opt/huginn`.

This makes it easier for users with a Docker setup to provide said files without having to create a new `Dockerfile` from an existing one just to add a volume.

Any suggestions?

**Comment by dsander** [comment]
Hi @saesh,

have you tried specifying the volume with `-v /opt/huginn:/opt/huginn` when starting the Huginn container?

**Comment by saesh** [comment]
Hey @dsander, right, that would be an option. I totally forgot that you don't need to specify the volume in the `Dockerfile` for the command line argument to work. I don't think a change to the `Dockerfile` is necessary then, and will close this issue.
