### ISSUE TITLE
Multiple email addresses for email agent 

### ISSUE THREAD

**Issue by wasafiri** [cantino/huginn#1621]
An array is required to send to multiple email addresses per the instructions provided in the EmailDigestAgent:

```
'when provided, 'recipients' should be an email address or an array of email addresses
```

However, this array is not recognized:
```
["bob@example.com", "jill@example.com"]
```

This is also not recognized:
```
['bob@example.com', 'jill@example.com']
```

This isn't recognized either:
```
%w(bob@example.com jill@example.com)
```

Any ideas?

**Comment by cantino** [comment]
Hey @wasafiri, did you make a JSON array in the JSON editor?  `key: ["email1", "email2"]`  Or you can press the `[` icon on the line.

**Comment by wasafiri** [comment]
Using the JSON editor made it work.
