### ISSUE TITLE
EmailDigestAgent memory too big

### ISSUE THREAD

**Issue by TildeWill** [cantino/huginn#1623]
I'm running into an issue where it looks like one of my users has constructed an `EmailDigestAgent` that has a huge value for the `memory` field. So big that I can't select it from my database, and it locks up the worker when it tries to load the agent. 

I want to migrate the database to limit the size of the `memory` field - what's a reasonable size for normal use?

**Comment by TildeWill** [comment]
Thinking through it more, I think I want to limit the number of source events. The EmailDigestAgent was being fed events from a TwitterStreamAgent which totaled 40,276 new events.

**Comment by dsander** [comment]
I think your first thought was correct, the `EmailDigestAgent` is storing the events it received in its memory. Can you fetch the agent memory via a database console?

The problem I see with limiting the memory field is that it will probably break Agents once the serialized memory is truncated. Maybe we can add a configurable limit to the digest agent?

**Comment by cantino** [comment]
Or maybe a `.env` configurable limit on the maximum memory size or maximum number of historical events an Agent can see? Also, the EmailDigestAgent could be edited to look at `.received_events` instead of storing them in `memory`.

**Comment by TildeWill** [comment]
It was ~76MB of payload in `memory`. I like @cantino's suggestion that "EmailDigestAgent could be edited to look at `.received_events`" and then for Omniscope I'll build out tiers that allow increasing numbers of events with the cap being something that my dynos can handle. Thanks!

**Comment by dsander** [comment]
Wow that is really a lot of data.

> Also, the EmailDigestAgent could be edited to look at .received_events instead of storing them in memory.

Generally it would be a nice optimization, even though then the event count would be limited by the env variable and `Keep events` of the emitting agent.
