### ISSUE TITLE
How to pass through "title" through TriggerAgent to EmailAgent

### ISSUE THREAD

**Issue by bobbysteel** [cantino/huginn#1625]
My input to the TriggerAgent contains parameters such as "title". However the TriggerAgent seems to only output a "message" and nothing else parametrized is passed through. Am I missing something how to get this out of a TriggerAgent event?
Thanks

**Comment by brianpetro** [comment]
Set `keep_event` to `true`

**Comment by bobbysteel** [comment]
In the TriggerAgent? That's set already yes.

**Comment by bobbysteel** [comment]
In my EmailAgent it seems to be getting the full event data but is not using it

  "subject": "My alert: {{title}}",
  "headline": "Thread: {{description}}",
  "expected_receive_period_in_days": "30",
  "recipients": "myemail"

The output is blank where title and description would go.

**Comment by bobbysteel** [comment]
Ack nevermind. Realized the digest agent wouldn't handle this properly and I should use a plain EmailAgent instead. Sorry!
