### ISSUE TITLE
Configure links between agents automatically

### ISSUE THREAD

**Issue by pedrocaseiro** [cantino/huginn#1626]
Suggestion, when creating a new agent some of the text boxes would already be filled, including the ones that link agents (sources and receivers for instance)

**Comment by dsander** [comment]
Hi @pedrocaseiro,

Huginn Agents can be linked in any way, I do not see how that could be done automatically. Do you have a special use case in mind?

**Comment by pedrocaseiro** [comment]
Hello,

Yes I do. I'm currently working on integrating Buddi (https://www.buddi.co.uk/) with Huginn. It consists in 3 agents, the one who connects to the Buddi API to get new notifications, the parser, who parses events that come from the first agent, and the last one that connects to my API so I can get notifications for each created event.

The people who are using them (the buddis) are elders that live at care homes. The people who are creating new agent's for each Buddi are carers, not me, that's why it would be good for me to have a "auto linking". Off course I can write a good Agent description to guide them, but anyway, it would be much better to simplify the most.

**Comment by dsander** [comment]
I see that looks very cool! Have you looked at the `Scenarios` page? A Scenario is a group of preconfigured Agents which comes with a description and can be exported to a JSON file for easy sharing.

**Comment by pedrocaseiro** [comment]
Yeah, but that doesn't solve the problem. Imagine 50 new elders start using Buddi. Someone is gonna need to create 50 new agents and give them the proper default options plus the linking to another agents. A scenario doesn't do that :/

**Comment by dsander** [comment]
A scenario does exactly that, it stores the Agent connections and their configuration at the time it's exported. When importing a Scenario it reuses Agents, so currently it is not possible to force the creation of new Agents when the Scenario is imported multiple times for the same user. Is that the issue?

**Comment by pedrocaseiro** [comment]
So what you're saying is that a save a Buddi Agent in a Scenario with the linking already done, so everytime a carer needs to create a new buddi agent they'll just import the Scenario and change de default_options?

**Comment by dsander** [comment]
Kind of, it will work for the first import of the scenario, if the same user imports the same scenario multiple times Huginn will not create new Agents but try to update (modify) the previously imported ones.
When you modify the Scenario or the Agents `guid` in the JSON (I am not sure if all of them need to change) Huginn will create new Agents when reimporting the changed JSON.
The best option I currently see is to use an external service/script (or a chain of Huginn Agents) which modifies the JSON, maybe also updates the Agent name with the elderly's, and then use that scenario file to create the Agents.

**Comment by pedrocaseiro** [comment]
Yeah, that's a solution, but it's too much work for the carers to do it. In fact, it is even more work for them than just having a nice description to guide them when creating a new agent.

If I manage to get some spare time I'll try to find a solution and PR it.

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions or want to do a PR.
