### ISSUE TITLE
 TypeError in Home#index 

### ISSUE THREAD

**Issue by pierrehegr** [cantino/huginn#1627]
Hi, in my up to date Huginn install, I have this error message when I go to the URL: 

`Showing /usr/huginn/app/views/layouts/application.html.erb where line #9 raised:

couldn't digest ActiveSupport::StringInquirer

    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
Rails.root: /usr/huginn
Application Trace | Framework Trace | Full Trace

app/views/layouts/application.html.erb:9:in `_app_views_layouts_application_html_erb__60447276267061146_17250810140'
config/initializers/silence_worker_status_logger.rb:5:in `call_with_silence_worker_status'
`
But the app is working, is just the web interface

Sincerely

**Comment by dsander** [comment]
Hi @pierrehegr,

do you want to run Huginn in the `production` environment on a server or in `development` locally? 

For production you probably need to change set `RAILS_ENV=production` in `.env`, for development try deleting the precompiled assets with `rm -rf tmp/cache/assets/`.

**Comment by pierrehegr** [comment]
@dsander I'm running in a development locally. I will try to delete the precompiled assets

**Comment by pierrehegr** [comment]
`rm -rf tmp/cache/assets/` was the solution. Thank a lot

**Comment by dsander** [comment]
Awesome :)
