### ISSUE TITLE
Scheduling Mechanism should allow intervals between specific time ranges

### ISSUE THREAD

**Issue by sriramsv** [cantino/huginn#1629]
The scheduling mechanism in the agents currently only support time to be either at intervals or specific times.

However, there is no way we can schedule an agent like "Check weather every 10minutes between 8am-10am".

Hence requesting that feature to be added.

**Comment by dsander** [comment]
Hi @sriramsv,

I think we will not add that to the default Agent schedules, the option would get too complex. However you can do that by using a `SchedulerAgent` to run your Agent. It accepts cron lines so you could configure it with `*/10 8-10 * * *` and set the `action` to `run` targeting the agent you want to run.

**Comment by sriramsv** [comment]
@dsander ah... I din quite realise that..
Thank you! Closing issue.
