### ISSUE TITLE
bin/setup_heroku doesnt work.

### ISSUE THREAD

**Issue by mboveiri** [cantino/huginn#1635]
Hi.
I deploy huginn from the readme to Heroku and to setup my admin user and password, follow this steps : 

![heoku](https://cloud.githubusercontent.com/assets/4364319/17664745/7f7dfab6-630b-11e6-8765-187af215cf37.png)

but on last step when i type : `bin/setup_heroku` on command prompt

i got :

 `'bin' is not recognized as an internal or external command,
operable program or batch file.`

i already installed : `Heroku Toolbelt` and `Rails Installer` from [http://railsinstaller.org/en](url)

any help.?

Thank you.

**Comment by cantino** [comment]
We don't support Windows directly.  Please use a virtualization tool like VirtualBox to run this on Linux.

**Comment by dsander** [comment]
[Bash on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about) could work, but I have not tried it myself.

**Comment by mboveiri** [comment]
> Bash on Windows could work, but I have not tried it myself. 

Yes, from "Windows 10" windows support `Bash`, anyway got this error after `bin/setup_heroku`

```
C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in require': cannot load such file -- active_support/core_ext/object/blank (LoadError)
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in require'
        from C:/myhuginnx/lib/setup_tools.rb:5:in <top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in require'
        from bin/setup_heroku:2:in <main>'
```
any help.?

**Comment by dsander** [comment]
That does not look like your are running the bash on windows from microsoft, as far as I know that should run native linux binaries, you seem to be running a windows binary of ruby. I can't really help because I do not use windows myself.

**Comment by mboveiri** [comment]
> That does not look like your are running the bash on windows from microsoft, as far as I know that should run native linux binaries, you seem to be running a windows binary of ruby. I can't really help because I do not use windows myself.

Yes, actually i'm on windwos 8.1 and doesn't access to Windows 10.
Thanks.

**Comment by mboveiri** [comment]
> That does not look like your are running the bash on windows from microsoft, as far as I know that should run native linux binaries, you seem to be running a windows binary of ruby. I can't really help because I do not use windows myself.

same on `Linux mint` Virtual-ed in `vobx ` : 

![VBOX](http://i.imgur.com/baKJajd.png)

**Comment by cantino** [comment]
Have you `bundle`d?

**Comment by mboveiri** [comment]
> Have you bundled?

yes,of course; i think that error cause some packs doesn't installed by `bundle`, or `Ruby-DevKit `needed.?

**Comment by cantino** [comment]
Hmm, does `bundle exec bin/setup_heroku` act any differently?

**Comment by mboveiri** [comment]
> Hmm, does bundle exec bin/setup_heroku act any differently?

got : `bundler: not executable: bin/setup_heroku`

**Comment by cantino** [comment]
Odd... you could try `bundle exec ruby bin/setup_heroku`

**Comment by mboveiri** [comment]
> Odd... you could try bundle exec ruby bin/setup_heroku

Thanks for the command, got : 
```
Could not find activesupport-4.2.7.1 in any of the sources
Run `bundle install` to install missing gems.
```
But before ran your command i manually installing : `ruby-railties` & `ruby-rspec-core` & `ruby-spring` with `sudo apt install`

and finally `bin/setup_heroku` work successfully.

Thanks.

**Comment by cantino** [comment]
Odd that you had to, but I'm glad it worked!

**Comment by alvarodemig** [comment]
Hello @mboveiri !!

Could you deploy Huginn on Heroku using win10?

Thanks!

**Comment by cantino** [comment]
@alvarodemig We recommend using VirtualBox to test or deploy Huginn if you're on Windows.
