### ISSUE TITLE
Huginn won't open after resetting the database

### ISSUE THREAD

**Issue by Faberman** [cantino/huginn#1636]
Hello.
I have a lot of agents and the number of rows have exceeded the free plan capacity. So, I've decided to clean all the events via 'Reset Database' command instead of manual deleting them.  Now I can access the main page, but it's impossible to sign in because of an error: 'We're sorry, but something went wrong'.

The question is can it be fixed? And I shouldn't use this option to clean the events, right?

**Comment by cantino** [comment]
Is this on Heroku?  If you dropped the database, without backups, you'll need to connect to the `heroku console` and create a new user (see the [code here](https://github.com/cantino/huginn/blob/master/db/seeds/seeder.rb)), or use the seed file, similar to https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#initialize-database

**Comment by Faberman** [comment]
It's on Heroku, yes. Sorry, forgot to mention. I've just create a new user and everything is fine. Thank you!
All agents are gone though. I'm really screwed up. Well, one should not forget about backups.

**Comment by cantino** [comment]
That sucks :(

You should definitely check out https://devcenter.heroku.com/articles/heroku-postgres-backups and see if it may have been enabled.
