### ISSUE TITLE
Keeping Events for Less time

### ISSUE THREAD

**Issue by sriramsv** [cantino/huginn#1637]
I was wondering if we can change the keep event interval for smaller amounts of time like 1 min, 2mins so that events don't get accumulated all together

**Comment by cantino** [comment]
Huginn isn't designed for high-throughput systems.  If you're getting enough events in 1-2 minutes, I suspect you may want to consider a different system?

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.
