### ISSUE TITLE
date function

### ISSUE THREAD

**Issue by level20peon** [cantino/huginn#1638]
I need to pass a date to a website agent in order to build a dynamic URL. For this I need to provide the current date and the date in 7 days like so "2016-08-16/2016-08-23". I built a workaround to create the current day with a dummy website agent and an event formatting agent using "{{ created_at | date:\"%Y-%m-%d" }}" but I cannot do a date calculation (i.e. add 7 days) this way. I simply need the string "2016-08-16/2016-08-23" in a website agent url, how would you propose to accomplish that? I don't care if it's created by the event formatting agent, the javascript agent or anything else, as long as it stays huginn internal (I don't want to calculate the date string on an external server and them pull it into the huginn system with a website agent).

**Comment by Enfop** [comment]
With this liquid
``
"{{'now' | date: '%Y-%m-%d'}}/{{'now' | date: '%s' | plus : 604800 | date: '%Y-%m-%d'}}"
``
i get "2016-08-16/2016-08-23".  I hope it helps.


credits to 
http://stackoverflow.com/questions/21056965/date-math-manipulation-in-liquid-template-filter

didn't even know that something like this is possible in liquid :smile:

**Comment by level20peon** [comment]
Perfect - thank you!
