### ISSUE TITLE
WebsiteAgent having trouble loading the correct webpage 

### ISSUE THREAD

**Issue by krdurquh** [cantino/huginn#1639]
I'm trying to pull off event listings from a webpage.  The "events" homepage is always today's current date, but there is a clickable calendar on the page that can send you to a different date. 
So what i want to do is create a website agent for each specific day in the future I'm interested in.  Here's an example: 

the homepage URL is this --> https://nowtoronto.com/search/event/community-events/
using the calendar --> https://nowtoronto.com/search/event/community-events/#search_date=2016-10-28

So this is what I'm working with the website agent: 

{
  "expected_update_period_in_days": "2",
  "url": "https://nowtoronto.com/search/event/community-events/#search_date=2016-10-28",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "title": {
      "css": ".event_result",
      "value": ".//text()"
    }
  }
}

The problem is when I run the agent, it will always pull events from TODAY'S day  (eg. it will search for october 28 (as in the above example), but will only return events from today). 

I wonder if it's some sort of problem with the website. 
I recently noticed that If I paste the example link into my browser, sometimes the WRONG DAY will load. 
Eg.  I'll enter this into the URL: https://nowtoronto.com/search/event/community-events/#search_date=2016-10-28
But once the page has finished loading, the URL bar will read this: 
https://nowtoronto.com/search/event/community-events/#search_date=2016-10-27

Has anyone had this sort of trouble before?  Is this particular website just one I should give up on? 
Any help would be appreciated.  Thanks guys.

**Comment by cantino** [comment]
Given the `#` in the URL, I suspect this is a client-side web application, which Huginn may not be able to deal with. It'd be good to figure out if there are unique URLs you can fetch, or if the page is making a JSON request that you could co-opt.  Perhaps you can try using the Chrome inspector and looking at the network requests being made?

**Comment by krdurquh** [comment]
Thanks for the reply! 

When I use the chrome inspector, I inspect the different selectable "days on the calendar", 
each one has a href = #. 
eg.  
eg.   <a class="ui-state-default" href="#">25</a>
eg. 2: <a class="ui-state-default" href="#">26</a>

I presume that's a bad thing, since other proper links on the page have fully fleshed out href addresses. 
Those other "fully fleshed out" hrefs are the ones that I'm looking for, obviously, but I can't access them without clicking on these "calendar days", unless I wait for the day itself to change. 

Regarding your other comments, I've used the chrome inspector and gone looking for JSON requests and at the network request information, but I don't understand the significance of everything I'm looking at.  
I obviously don't expect you to educate me on this stuff, so I'm going to abandon this webpage for the time being until I understand it a little better. 
Thanks for your time though.

**Comment by irfancharania** [comment]
What Andrew means is in your Chrome inspector, check out the network tab
![capture](https://cloud.githubusercontent.com/assets/3255038/17719033/6f0f659a-63cc-11e6-95a7-9e9345926fa8.PNG)

In there, you'll see a request being made to 
https://nowtoronto.com/api/search/event/community-events/get_search_results?search_value=&categories=&search_date=2016-10-28&page=1

You can try to parse the results from those calls and see where that gets you

Also, this site is tremendously helpful: https://developer.chrome.com/devtools

**Comment by krdurquh** [comment]
thanks! I'll take a look through these in the next few days. 
appreciate it!

**Comment by irfancharania** [comment]
You might also want to check out [this](https://github.com/cantino/huginn/issues/1638) to give you some ideas!

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.
