### ISSUE TITLE
Accessing all the values an agent's memory had

### ISSUE THREAD

**Issue by pedrocaseiro** [cantino/huginn#1640]
Is it possible to access all the values that an agent's memory had?

What I'm doing right now is pushing the new information to a hash inside the memory array so I can have access to all the values the memory had, but it isn't the optimal solution.

Any other way to do this? I guess I could be doing this with a db, but if I could do it just with the agent's memory that would be great.

**Comment by cantino** [comment]
What's the underlying problem you're trying to solve?

**Comment by pedrocaseiro** [comment]
It's a private integration I'm working on, where I receive a list of clients and create then in my platform if they were non existent, or remove them if they were deleted from the list but they're on the platform. Every element of that list has an ID associated that I need to always have access, so I know if I had already synced them with the platform before or not.

**Comment by cantino** [comment]
Could your memory contain `client_ids` and `deleted_client_ids` arrays?

**Comment by pedrocaseiro** [comment]
Yeah. One approach I was thinking was having a Array of Hashes, i.e. memory -> [{user_id: id, platform_id: plat_id, flag: flag}] where flag indicates if it is created or not in the platform.

**Comment by cantino** [comment]
Seems reasonable as long as it won't get too large.

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.
