### ISSUE TITLE
CURL

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1641]
If I have something like the below is it possible to get the data from Huginn?

curl --include --request GET "https://example.dyio.com/df/api/34rgfd/latest.json?auth=3ewdsfgre34rfa"

Can someone guide me if it is.

**Comment by K1773R** [comment]
You'd want to use the WebsiteAgent

**Comment by cantino** [comment]
Yes, WebsiteAgent or PostAgent with method GET.

**Comment by signallhill** [comment]
Ok Post Agent like this but Result 
{
  "post_url": "https://example.dyio.com/df/api/34rgfd/latest.json?auth=3ewdsfgre34rfa",
  "expected_receive_period_in_days": "1",
  "content_type": "json",
  "method": "get",
  "payload": {
    "title": "{{title}}"
  },
  "headers": {},
  "emit_events": "true",
  "no_merge": "false"
}

Result

[
  {
    "body": "null",
    "headers": {
      "Content-Length": "4",
      "Content-Type": "application/json; charset=utf-8",
      "Access-Control-Allow-Origin": "*",
      "Cache-Control": "no-cache",
      "Strict-Transport-Security": "max-age=31556926; includeSubDomains; preload"
    },
    "status": 200
  }
]

**Comment by vivagonna** [comment]
What do you want from that url? It seems there is nothing on it. In fact, it redirected me to its home page automatically.

**Comment by signallhill** [comment]
Thats an example url not the actual one.  I am trying to figure out what needs to be done in the website or post agent to pull data from the url.

**Comment by cantino** [comment]
That page gave me an SSL error.  You're getting a body of `null`, either due to that or because the page is empty.
