### ISSUE TITLE
HTML Data in XML

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1642]
I have an xml url that sends HTML data. I able to pick the html data and send it out to the website agent. but once it reaches the website agent i cannot extract what I want. The payload looks like this

Basically want Title 1 Within h2 and description from this data within sumMob.

{
  "expected_update_period_in_days": "5",
  "data_from_event": "{{data}}",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "title": {
      "css": "h2"
      "path":".//text()"
    },
    "des": {
      "css": "sumMob"
      "path":".//text()"
    }
  }
}

Payload

  "data": "`<htmlData>&lt;div class=\"items\"&gt;&lt;a name=\"gg\"&gt;&lt;!--placeholder--&gt;&lt;/a&gt;&lt;div class=\"C1\"&gt;&lt;div onclk=\"Grid;\" class=\"item\"&gt;&lt;div class=\"Info\"&gt;&lt;!--content spacer--&gt;&lt;h2&gt;Title1&lt;/h2&gt;&lt;p class=\"sumMob\"&gt;Description  &lt;/p&gt;&lt;div class=\"postType\"&gt;&lt;span class=\"label\"&gt;Post Type:&lt;/span&gt;&lt;span&gt;Daily&lt;/span&gt;&lt;/div&gt;&lt;div class=\"location\"&gt;&lt;span class=\"label\"&gt;Location:&lt;/span&gt;&lt;span class=\"cityState\"&gt;city,state&lt;/span&gt;&lt;/div&gt;&lt;div class=\"posted\"&gt;&lt;span class=\"label\"&gt;Date Posted:&lt;/span&gt;&lt;span class=\"date\"&gt;Dec 19, 2015&lt;/span&gt;&lt;span class=\"daysApart\"&gt;365 days ago\n      &lt;/span&gt;&lt;/div&gt;&lt;div class=\"industry\"&gt;&lt;span class=\"label\"&gt;type:&lt;/span&gt;&lt;span&gt;ss&lt;/span&gt;&lt;/div&gt;&lt;p class=\"sumDesk\"&gt;Description  &lt;/p&gt;&lt;/div&gt;&lt;div class=\"buttons\"&gt;&lt;!--content spacer--&gt;&lt;span class=\"toDesc\"&gt;&lt;a " href=\"/link.htm\"&gt;Full Descn&lt;/a&gt;&lt;/span&gt;&lt;!--placeholder--&gt;&lt;/a&gt;&lt;div class=\"C1\"&gt;&lt;div onclk=\"Grid;\" class=\"item\"&gt;&lt;div class=\"Info\"&gt;&lt;!--content spacer--&gt;&lt;h2&gt;Title1&lt;/h2&gt;&lt;p class=\"sumMob\"&gt;Description  &lt;/p&gt;&lt;div class=\"postType\"&gt;&lt;span class=\"label\"&gt;Post Type:&lt;/span&gt;&lt;span&gt;Daily&lt;/span&gt;&lt;/div&gt;&lt;div class=\"location\"&gt;&lt;span class=\"label\"&gt;Location:&lt;/span&gt;&lt;span class=\"cityState\"&gt;city,state&lt;/span&gt;&lt;/div&gt;&lt;div class=\"posted\"&gt;&lt;span class=\"label\"&gt;Date Posted:&lt;/span&gt;&lt;span class=\"date\"&gt;Dec 19, 2015&lt;/span&gt;&lt;span class=\"daysApart\"&gt;365 days ago\n      &lt;/span&gt;&lt;/div&gt;&lt;div class=\"industry\"&gt;&lt;span class=\"label\"&gt;type:&lt;/span&gt;&lt;span&gt;ss&lt;/span&gt;&lt;/div&gt;&lt;p class=\"sumDes\"&gt;Description  &lt;/p&gt;&lt;/div&gt;&lt;div class=\"buttons\"&gt;&lt;!--content spacer--&gt;&lt;span class=\"toDesc\"&gt;&lt;a " href=\"/link.htm\"&gt;Full Descn&lt;/a&gt;&lt;/span&gt;&lt;/div<\/htmlData>`"

**Comment by cantino** [comment]
It looks like it's all HTML escaped.  You'll need to `unescape` it in Liquid, I think.

**Comment by signallhill** [comment]
Worked thank you.
