### ISSUE TITLE
Graphviz support badge

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1643]
Is it possible to show a badge or an icon on agents that has propagate immediately set to true in view diagram mode?

**Comment by cantino** [comment]
That's a good idea. Or maybe a different line styling.

**Comment by signallhill** [comment]
Also, is it possible include a button Show only Orphan Agents (shows agents that are not linked to any other agents) like the one that says Hide Disabled Agents. Please consider too.

**Comment by knu** [comment]
I believe the `propagate_immediately?` attribute already [affects the line styling](https://github.com/cantino/huginn/blob/master/app/helpers/dot_helper.rb#L154).

**Comment by knu** [comment]
...Where a dashed arrow indicates events will be propagated periodically, and a filled arrow indicates events will be propagated immediately.

**Comment by signallhill** [comment]
@knu I have propagate immediately unchecked agents with both dotted and solid lines and vice versa?

**Comment by signallhill** [comment]
@knu looking at my diagram one logic I am seeing for the dotted vs solid is control. If an agent controls another agent then a dotted line links them. For example scheduler agent controlling other agents or website agent sending payload to a event formatting agent. these have dotted on mine

For website agent that send payload to trigger agent which may or may not process that data based on a trigger is not controlled by website agent and has a solid line connecting them. these have solids on mine

Does the second line have to do anything with this? Its a guess, I don't know what language this is.

 'style: ('dashed' unless receiver.propagate_immediately?),
label: (" #{agent.control_action}s " if agent.can_control_other_agents?),'

**Comment by cantino** [comment]
It looks like it is dashed unless propagate_immediately is set.
