### ISSUE TITLE
Website Agent css selector or xpath copied from Chrome not working

### ISSUE THREAD

**Issue by budric** [cantino/huginn#1646]
Hi,
I'm trying to scrape some values from an HTML site, I used Chrome Dev mode to get to the element and copied CSS selector as well as xpath but unfortunately neither works and result value is empty.  I downloaded the page with wget and the data I want is in the document, it's not a dynamically loaded JavaScript site.

Am I doing something wrong (the URL comes from RSSAgent)?

```
{
  "expected_update_period_in_days": "2",
  "url_from_event": "{{ url }}",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "price1": {
      "css": "#itemdetails > div.col-2 > table > tbody > tr:nth-child(2) > td > div > span > strong",
      "value": ".//text()"
    },
    "price2": {
      "xpath": "//*[@id=\"itemdetails\"]/div[2]/table/tbody/tr[2]/td/div/span/strong",
      "value": "normalize-space(.//text())"
    }
  }
}
```

Dry run with URL:
```
[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Fetching http://www.kijiji.ca/v-hand-tool/oshawa-durham-region/bullseye-auto-levelling-laser-studfinder-b-d-used-once/1192950858
[00:00:00] INFO -- : Extracting html at #itemdetails > div.col-2 > table > tbody > tr:nth-child(2) > td > div > span > strong: []
[00:00:00] INFO -- : Extracting html at //*[@id="itemdetails"]/div[2]/table/tbody/tr[2]/td/div/span/strong: []
[00:00:00] INFO -- : Dry Run finished
```

**Comment by dsander** [comment]
Hi @budric,

your selector looks correct, not sure what the issue is, does this selector work `#itemdetails span[itemprop=price] strong`?

**Comment by cantino** [comment]
Maybe the site is detecting user agents?  You could try setting one for Firefox.

**Comment by budric** [comment]
@dsander that selector works.  But other similar selectors like "#itemdetails > div.col-2 > table > tbody > tr:nth-child(5) > td" don't seem to work.  Not sure how to further debug this issue.

@cantino user agent doesn't appear to be the issue in this case.

Thank you.

**Comment by dsander** [comment]
Maybe the `nth-child` pseudo selector is causing problems, I am not sure if the Agent supports those. You can check out http://selectorgadget.com/ it will most likely give you simpler selectors.

**Comment by cantino** [comment]
Nokogiri should definitely support nth-child.  There was this issue, but we're on 1.6.8 now. https://github.com/sparklemotion/nokogiri/issues/829

**Comment by knu** [comment]
Just a wild guess, but what if you changed `table > tbody > tr...` to `table > tr...` or `table tr...`?  Some browsers automatically insert a `tbody` container element around `tr` elements in a DOM tree, even if it does not exist in the original HTML while Nokogiri (libxml2) does not do that.  The first thing you should check out is the original HTML document.

**Comment by budric** [comment]
@knu yes that actually works and appears to be the problem.  Thanks!   So from now on I'll remove tbody from selectors.

As a side note:
I've tried SelectorGadget as the first tool for this, however the selectors are too simple/broad for this case.  For example for the price element the selector it generated was just `strong`.  But in my view if anything else is ever formatted in bold on the page it would be mistaken for the price.

Firefox in dev mode generated this selector `.ad-attributes > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(2) > div:nth-child(1) > span:nth-child(1) > strong:nth-child(1)`  which I can't get to work, whereas Chrome generates this `#itemdetails > div.col-2 > table > tbody > tr:nth-child(2) > td > div > span > strong` which I can get working by removing tbody.

**Comment by cantino** [comment]
@budric With selectorgadget, did you tell it that it was too general by clicking on one of he incorrect matches?

**Comment by budric** [comment]
It's the only <strong> tag on the sample page (or any Ad page I've encountered so far).  So there is nothing else in green to un-select with SelectorGadget.  But it just doesn't sit right with me to leave my search criteria for the "price" field is "any text that's bold" - even though it works for pretty much every page I've opened from that site.

**Comment by cantino** [comment]
Gotcha. That makes sense.
