### ISSUE TITLE
Retrieve .env for deployed heroku app

### ISSUE THREAD

**Issue by DreamFlasher** [cantino/huginn#1648]
I deployed to heroku a while ago, and now I don't have the folder with my .env anymore. I just checked out from heroku again with ```heroku git:clone -a appname``` again -- but the .env file is missing. If I would now to a pull and push to heroku I'd assume to break my app. How can I restore the .env?

**Comment by cantino** [comment]
On Heroku, everything is set as an environment variable.  You can see these with `heroku config`, and could copy them into a copy of .env.example if you want.

**Comment by DreamFlasher** [comment]
Ah perfect, thanks a lot! ```heroku config -s > .env```
