### ISSUE TITLE
DB not cleaning up at midnight

### ISSUE THREAD

**Issue by DreamFlasher** [cantino/huginn#1649]
I received a mail from heroku that I am over the 10000 limit for my database. I have one agent which creates many events (1k per day), I set it to keep events for one week. Nevertheless old entries weren't deleted within the last 24 hours. What can I do to get it below the limit again?

**Comment by cantino** [comment]
Is this on a Heroku paid or free plan?  It's possible on the free plan the cleanup isn't happening because the app is offline much of the time?

**Comment by DreamFlasher** [comment]
It's on the free plan, but the free plan was changed so actually the description with the downtime is not necessary anymore: https://www.heroku.com/pricing -- I am just running the app all the time, because I have only one app.

**Comment by dsander** [comment]
I don't think `SCHEDULER_EXPIRATION_CHECK` is used anywhere. You might need to set `EVENT_EXPIRATION_CHECK` to `1h`, per default the check is done only every `6h`. Also the expiration date for events is set when the event is created, did you modify the `Keep event` option of the Agent recently?

**Comment by DreamFlasher** [comment]
I used it because it was referred to in this issue: https://github.com/cantino/huginn/issues/765 (https://github.com/cantino/huginn/commit/7d047a3a4764add2b32b963730bdfab88e15ee45)

I set the Keep event option of the Agent after I got the notification that my limit is reached -- that's interesting that the expiration date is set when the event is created, because well, do I now have any chance at all to get rid of the events in that agent? (I'm fine to just trash all of them)

**Comment by cantino** [comment]
That does seem like a bug-- we should backfill the expiration when it's changed / set.

**Comment by cantino** [comment]
You can go into the UI and delete all events made by the agent from the dropdown on the Agent's show page.

**Comment by dsander** [comment]
I overlooked the [after_save filter](https://github.com/cantino/huginn/blob/master/app/models/agent.rb#L149), the Event expiration date is updated after `keep_events_for` is changed.

@DreamFlasher Is it possible that the Agent created more events in the last week then usual? You can check the Events creations dates in the `Agent -> Events` page.

**Comment by DreamFlasher** [comment]
The agent didn't create more event than usual, also the Agents -> Events page is not helpful in answering this question, because getting an overview of multiple thousand events is not what the page is built for. 
I deleted all the events for the agent and continue observing what is happening, I've set the retention to 1 day, so I should be able to observe the deletion of events.

**Comment by DreamFlasher** [comment]
This night the events were reduced, so I am closing the issue.

**Comment by cantino** [comment]
Glad it's working
