### ISSUE TITLE
Liquid Templating Help

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1650]
I need to delete or replace with blank, data before and after two pattern. I want nothing before and after the regex pattern. How can that be achieved??

**Comment by cantino** [comment]
You'll want a pattern that matches everything and remembers a piece in the middle, then replaces everything with the piece in the middle.  For example: `{{ foobar | regex_replace: '\A.*?(something).*?\z', '\1' }}`

**Comment by signallhill** [comment]
So there is nothing like 'regex_replace_before' and 'regex_replace_after'. Ok will give it a shot.

**Comment by signallhill** [comment]
I used the following. enclosed the beginning patter with <h4> and ending with </h4>

and then selected h4 to be scraped. Works when I do dry run but not when the agent is run, dont know why.


{
  "expected_update_period_in_days": "2",
  "data_from_event": "{{body | regex_replace:'pattern1','<h4>' | regex_replace:'pattern2','</h4>'}}",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "h4": {
      "css": "h4",
      "value": ".//text()"
    }
  }
}

**Comment by cantino** [comment]
Does the incoming event definitely have a `body` field?

**Comment by signallhill** [comment]
Yes, post agent basically is sending the whole page HTML to website agent. When I do dry run it shows the correct data within <h4>. But when I run the post agent it sends out the body to website agent but does not see <h4>. Is this a bug or am I doing something wrong?

**Comment by cantino** [comment]
Can you show an example event coming from the post agent?

**Comment by signallhill** [comment]
Post agent runs and send out the below event. It goes to website agent and nothing happens. If I manually go to the website agent and do Dry-Run it works.


Here the event coming in from post agent

`{
 "body": "<script>\n                        jQuery(document).ready(function(){\n                            var search_results = buildResults({\"count\":2,\"error\":false,\"data\":[{\"description\":\"description details.\",\"state\":\"KP\",\"city\":\"city1\",\"title\":\"Tilte 1\"},{\"description\":\description detail.\",\"state\":\"KP\",\"city\":\"ciy2\",\"title\":\"title\"}],\"message\":\"\",\"searchVars\":{\"keywords\":\"\",\"officeId\":\"0\",\"reqType\":[\"1\"],\"industry\":\"1\"}}",
  "headers": {
    "Server": "nginx",
    "Date": "Mon, 29 Aug 2016 14:21:10 GMT",
    "Content-Type": "text/html; charset=UTF-8",
    "Transfer-Encoding": "chunked",
    "Connection": "keep-alive",
    "X-Pingback": "https://www.somewebsite.com/wp/xmlrpc.php",
    "Link": "<https://www.somewebsite.com/wp-json/>; rel=\"https://api.w.org/\", <https://www.somewebsite.com/>; rel=shortlink"
  },
  "status": 200
}`

Here is the website agent trying to get the data but does not work

`{
  "expected_update_period_in_days": "2",
  "data_from_event": "{{ body | regex_replace:'\<script\>\\n+\s*+jQuery\(document\).ready\(function\(\)\{+\\n+\s*+var\s*+search_results\s*+\s*+=\s*+buildResults\(\{\"count\":[0-9]*+,\"error\":false,\"data\":\[','<h4>' | regex_replace:'\]\,\"message\":\"\",\"searchVars\"..','</h4>' }}",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "h4": {
      "css": "h4",
      "value": "normalize-space(.)"
    }
   }
  }
}`


Here is the website agent event when I do **Dry-Run**

`<h4> {\"description\":\"description details.\",\"state\":\"KP\",\"city\":\"city1\",\"title\":\"Tilte 1\"},{\"description\":\description detail.\",\"state\":\"KP\",\"city\":\"ciy2\",\"title\":\"title\"} </h4>`

**Comment by cantino** [comment]
I wonder if it has to do with escaping the regexes? I don't see why it would, though, just a suspicion. It'd be helpful if you could simplify the regex as much as possible and see if you can isolate which part is working in dryrun, but not on the real event. You can always test by going to one of the events and `Re-emit`ing it.

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.
