### ISSUE TITLE
Using the container behind a proxy

### ISSUE THREAD

**Issue by tomasdelvechio** [cantino/huginn#1652]
Hi, I trying to use [the container with Huginn installed](https://hub.docker.com/r/cantino/huginn/). But in my organization we work behind a proxy.

I try to launch the container and provide the proxy settings in the enviroment to container:

```
$ docker run -it -p 3000:3000 -e "http_proxy=http://my-proxy-url.org.ar:8080" -e "https_proxy=http://my-proxy-url.org.ar:8080" -e "HTTP_PROXY=http://my-proxy-url.org.ar:8080" -e "HTTPS_PROXY=http://my-proxy-url.org.ar:8080" cantino/huginn
Fetching source index from https://rubygems.org/
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Could not fetch specs from https://rubygems.org/
```

What is the script/scripts I must refactor to support proxy? If I get a list of this, I do a PR with that options supported.

**Comment by dsander** [comment]
Hi @tomasdelvechio,

I think the problem is not the configuration you used but ruby not working with your proxy server, when I start the container with your options I get exactly the same output.

**Comment by tomasdelvechio** [comment]
Hi @dsander, my mistake, I had to configure the dns of my organization too. The container works fine behind the proxy using the parameters.
