### ISSUE TITLE
Support Pushjet, push notification service

### ISSUE THREAD

**Issue by wjdp** [cantino/huginn#1653]
See https://pushjet.io/, very open alternative to pushbullet. Service is currently alpha but looks very promising.

API: http://docs.pushjet.io/
GH: https://github.com/Pushjet

**Comment by dsander** [comment]
Hi @wjdp,

their API looks straight forward, a PostAgent with these options should be able to send events to Pushjet:

```
{
  "post_url": "https://api.pushjet.io/message",
  "expected_receive_period_in_days": "1",
  "content_type": "json",
  "method": "post",
  "payload": {
    "message": "Hello from Huginn: {{message}}",
    "secret": "d2d1820d56b862a6f5b1a69a7af730fa"
  },
  "emit_events": "false",
  "no_merge": "false"
}
```

**Comment by wjdp** [comment]
@dsander Cheers, will have a try
