### ISSUE TITLE
RSS-media multiple params

### ISSUE THREAD

**Issue by nata-lee** [cantino/huginn#1654]
Hello!

I'm trying to generate an RSS-media feed with multiple media:thumbnails but it is impossible. Also it is related to media:comments, media:embed and a lot of others.
RSS-media reference http://www.rssboard.org/media-rss#media-thumbnails
This issue is similar to #1361

**Comment by nata-lee** [comment]
I found a workaround, I moved thumbnails to RSS item description.

**Comment by dsander** [comment]
Hi, yes cause for the problem you are describing in the same as in #1361, our XML serializer does not support using the same tag multiple times.

**Comment by dsander** [comment]
I am closing this issue. Please feel free to reopen if you need further assistance!
