### ISSUE TITLE
[help-wanted] Email Agent liquid formatting not working

### ISSUE THREAD

**Issue by cawilliamson** [cantino/huginn#1656]
This is likely just me missing something but I have a task which pulls information from a JSON file (a reddit search returning a json file.)

I then pass three values through to the email agent:

title, url, created

I use the title and url values as is but I am trying to format the created value to a human readable date (from epoch.) Everything looks like it should work but when the email arrives it contains:

Created: 1433082180.0

(I notice a decimal point is added but it is certainly not outputting the formatting I would expect from the code below:

`{
  "subject": "New reddit post",
  "expected_receive_period_in_days": "64",
  "type": "text/html",
  "body": "Title: {{ title }}<br>URL: {{ url }}<br>Created: {{ created | date:\"%H:%M on %d/%m/%Y\" }}"
}`

Any help would be greatly appreciated!

**Comment by dsander** [comment]
Hi @cawilliamson,

that is odd, I tested your configuration with a `EventFormattingAgent` and the liquid formatting seems to work there:

```
# agent options:
{
  "instructions": {
    "message": "Title: {{ title }}<br>URL: {{ url }}<br>Created: {{ created | date:\"%H:%M on %d/%m/%Y\" }}"
  },
  "matchers": [],
  "mode": "clean"
}
# dry run event
{
  "title": "hello",
  "url": "url",
  "created": "1433082180"
}
# output
[
  {
    "message": "Title: hello<br>URL: url<br>Created: 16:23 on 31/05/2015"
  }
]
```

Can you confirm your `body` string works in a `EventFormattingAgent`?

**Comment by cawilliamson** [comment]
@dsander The formatting does work on a EventFormattingAgent but the final email still does not come in the formatted type.

Essentially the dry run output shows the output email correctly but when it is sent it reverts to the epoch timestamp (with .0 at the end)

**Comment by cawilliamson** [comment]
@dsander 

I have had another look at this and have added a event formatting agent before the email send step. With this in place I still see the same issue strangely.

The message line is:
"message": "Title {{ title }}<br>URL: {{ url }}<br>Created: {{ created | date:\"%H:%M on %d/%m/%Y\" }}"

Strangely I still get the same decimal point result: 1433082180.0

I'm not too sure where I should be looking now. I am new to Huginn so it's entirely possible I'm doing something silly here but I just can't figure it out. The dry run results show the correct formatting but running the task from the start properly results in this weird decimal place epoch timestamp. Seems very odd.

Thanks a lot for your assistance so far! It's greatly appreciated. :)

**Comment by cawilliamson** [comment]
I did make an additional change by Changing {{ title }} to {{ title | replace: 'foo', 'bar' }} and that *did* work so it looks like liquid formatting is working to some degree - just strangely it isn't working on the date field.

I'm wondering if this is because the date is a float perhaps? Maybe if I tried removing the '.0' it may work...

**Comment by cawilliamson** [comment]
Ok so I found a workaround:

{{ created | replace '.0', '' | date \"%H:%M on %d/%m/%Y\" }}

It seems the decimal point was causing the problems and with that removed the date formatting works properly. There is likely a more elegant way to remove the decimal point but this does seem to work for now.

Seems odd that the date formatting wasn't able to deal with the .0 though - it *does* render properly in the dry run ' preview output mode but when it comes to actually sending the value off to another agent it sends the unformatted text. Very strange.

Probably worth looking in to.

**Comment by cawilliamson** [comment]
I just had another look in to this and there is actually a much more elegant solution:

`{{ created | round | date \"%H:%M on %d/%m/%Y\" }}`

I'm completely happy with this as a solution - my only comment to make on that is - why does this work in the results pane on a dry run but not on the actual email being sent or value being stored? Very strange.

**Comment by dsander** [comment]
I see, I thought you meant the decimal was added by the `EmailAgent` seems you are right and the `date` filter requires the input to be a "integer". When I dry run with `1433082180.0` I am getting `1433082180.0` in the message as well.

**Comment by cantino** [comment]
Did you get this figured out?

**Comment by dsander** [comment]
I am closing this issue. Please feel free to reopen if you need further assistance!
