### ISSUE TITLE
503 5.5.1 Error: authentication not enabled when I'm running a local SMTP server.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#1657]
I have Postfix installed on my Huginn server, and it is configured to only send outbound mail from applications running on the server (alongside several other pieces of software).  After updating last night I started getting failed jobs with the following error message:

503 5.5.1 Error: authentication not enabled

The relevant configuration settings in huginn/.env, which I have not edited (confirmed with the output of AIDE):

```
SMTP_DOMAIN=my.huginn.server.com
SMTP_USER_NAME=
SMTP_PASSWORD=
SMTP_SERVER=localhost
SMTP_PORT=25
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=false
```

Did something change in Huginn that prevents it from using the local SMTP server without authentication?

**Comment by cantino** [comment]
Hey @virtadpt. The only thing that comes to mind is #1595. You could try editing [lines 7 and 8](https://github.com/dsander/huginn/blob/c4d3c5795d67c15c796bc03c955bec6212b50785/config/initializers/action_mailer.rb#L7) of action_mailer.rb to be `ENV['SMTP_USER_NAME'],` and `ENV['SMTP_PASSWORD']` (remove the `|| ""`).  It's possible that you need `nil`, not empty string, to be sent to the mail server?

**Comment by virtadpt** [comment]
Thanks, let me give that a try...

**Comment by virtadpt** [comment]
No dice.  Let me try 'nil'.

**Comment by virtadpt** [comment]
'nil' didn't work, either.

Hypothetically speaking, what would happen if `authentication: ENV['SMTP_AUTHENTICATION'] || "plain",` was set to 'nil'?

**Comment by virtadpt** [comment]
Per the answer here (https://stackoverflow.com/questions/26093514/rails-actionmailer-send-email-without-authentication) I had to comment out (not set to 'nil' - that continued to throw the same error) the authentication, user_name, and password lines to get outbound SMTP working again.

Perhaps it should be possible to set the appropriate lines in huginn/.env to nothing (e.g., "SMTP_AUTHENTICATION=") to disable that particular facet of SMTP transmission... or would ActionMailer not permit that by design?

**Comment by cantino** [comment]
Interesting.  Does the following work if you set `SMTP_AUTHENTICATION` to `none`?

```
authentication: ENV['SMTP_AUTHENTICATION'] == 'none' ? nil : (ENV['SMTP_AUTHENTICATION'] || "plain")
```

and

```
user_name: ENV['SMTP_USER_NAME'].presence,
password: ENV['SMTP_PASSWORD'].presence,
```

work?

If it doesn't, then I think you're correct, and the existence of the key, independent of it's value is what's causing authentication.  In that case, we should do:

```ruby
ActionMailer::Base.smtp_settings = {}.tap do |settings|
  settings.merge! {
    address: ENV['SMTP_SERVER'] || "smtp.gmail.com",
    port: ENV['SMTP_PORT'] || 587,
    domain: ENV['SMTP_DOMAIN'],
    enable_starttls_auto: ENV['SMTP_ENABLE_STARTTLS_AUTO'] == 'true',
    openssl_verify_mode: ENV['SMTP_OPENSSL_VERIFY_MODE'].presence,
    ca_path: ENV['SMTP_OPENSSL_CA_PATH'].presence,
    ca_file: ENV['SMTP_OPENSSL_CA_FILE'].presence
  }
  if ENV['SMTP_AUTHENTICATION'] != 'none'
    settings.merge! {
      authentication: ENV['SMTP_AUTHENTICATION'].presence || "plain",
      user_name: ENV['SMTP_USER_NAME'].presence,
      password: ENV['SMTP_PASSWORD'].presence,
    }
  end
}
```

**Comment by virtadpt** [comment]
I'm trying it right now.  I'l keep an eye on things, and if I keep getting e-mail in the next hour or two, that might be the fix.

**Comment by dsander** [comment]
@virtadpt I used your .env settings and compared the old and the new ActionMailer SMTP configuration and think the first change Andrew proposed should have worked:
```
# New:
{:address=>"localhost",
 :port=>"25",
 :domain=>"my.huginn.server.com",
 :authentication=>"plain",
 :enable_starttls_auto=>false,
 :user_name=>"",
 :password=>"",
 :openssl_verify_mode=>nil,
 :ca_path=>nil,
 :ca_file=>nil}
# Old
{:address=>"localhost",
 :port=>25,
 :domain=>"my.huginn.server.com",
 :authentication=>"plain",
 :enable_starttls_auto=>false,
 :user_name=>nil,
 :password=>nil,
 :openssl_verify_mode=>nil,
 :ca_path=>nil,
 :ca_file=>nil}
```

I think it should work to change `config/initializers/action_mailer.rb` to:

```
ActionMailer::Base.smtp_settings = {
  address: ENV['SMTP_SERVER'] || "smtp.gmail.com",
  port: ENV['SMTP_PORT'] || 587,
  domain: ENV['SMTP_DOMAIN'],
  authentication: ENV['SMTP_AUTHENTICATION'] || "plain",
  enable_starttls_auto: ENV['SMTP_ENABLE_STARTTLS_AUTO'] == 'true',
  user_name: ENV['SMTP_USER_NAME'].presence,
  password: ENV['SMTP_PASSWORD'].presence,
  openssl_verify_mode: ENV['SMTP_OPENSSL_VERIFY_MODE'].presence,
  ca_path: ENV['SMTP_OPENSSL_CA_PATH'].presence,
  ca_file: ENV['SMTP_OPENSSL_CA_FILE'].presence
}
```

**Comment by virtadpt** [comment]
@cantino Just tried the changes you suggested - no soap, no outbound SMTP.

@dsander Just set things up the way you suggested with `SMTP_AUTHENTICATION=` in huginn/.env.  Let's see what happens.

**Comment by virtadpt** [comment]
Nope.  No dice.

**Comment by cantino** [comment]
So the change @dsander suggested seems to have fixed it, @virtadpt?

**Comment by virtadpt** [comment]
That seems to have fixed it.  Note that in the .env file SMTP_USERNAME, SMTP_PASSWORD, and SMTP_AUTHENTICATION must have nothing after the equals sign for it to work, putting something like nil or false won't work.  It'll be a minor edit to the comments of huginn/.env.example.

**Comment by bobbysteel** [comment]
Strangely after moving to docker but keeping all my old configuration in getting this error. Postfix is configured the same and the docker network is bridged properly but no matter how I configure it huginn is making an AUTH request to postfix putting u this same error. any other ideas why this might affect from docker?

**Comment by dsander** [comment]
How did you configure the network bridge? I am surprised that the docker container can reach the docker host by using `127.0.0.1`.

**Comment by bobbysteel** [comment]
Host mode and -h 127.0.0.1
I needed this as my MySQL runs native on the server . Works fine and when I
exec into the image i can reach postfix just fine

**Comment by bobbysteel** [comment]
The docker commands are 
```
 --net=host -h 127.0.0.1 -p 127.0.0.1:3000:3000 
```
I dump all my ENV variables into a Dockerfile and rebuild an image. Easier for me to automate this way vs 20+ env variables in my run command.

The container is interfacing fine with postfix but it always seems to send an AUTH request.
Separately, I also can't send via Gmail either as it gives me an end of file error when I use the same SSL config as several other apps on this PC :/

**Comment by bobbysteel** [comment]
FWIW, I seem to have fixed this by finding that pull from earlier this year to specify SMTP_AUTHENTICATION=none as an env variable. This seems to have been overlooked in docs so I'll note this elsewhere in the wiki.

**Comment by dsander** [comment]
> The docker commands are
> 
>  --net=host -h 127.0.0.1 -p 127.0.0.1:3000:3000

Cool I did not know this was possible.



> I dump all my ENV variables into a Dockerfile and rebuild an image. Easier for me to automate this way vs 20+ env variables in my run command.

Interesting, you can also use the `docker run --env-file` to pass in variables from an external `.env` file.

> This seems to have been overlooked in docs so I'll note this elsewhere in the wiki.

Thank you! We are not very good when it comes to documenting stuff 😊
