### ISSUE TITLE
[help-wanted] Fetching Google Calendar events (from Birthday calendar)

### ISSUE THREAD

**Issue by cawilliamson** [cantino/huginn#1658]
So a task I'm trying to move over from Zapier -> Huginn is a trigger based on calendar events.

I know there is a way to *write* google calendar events but I actually want to:

- Read a calendar event from the Birthday calendar Google provides
- Use the persons name in that event to perform a google contacts search for them
- Determine the address from the step above
- Email this information to myself so that I have an email stating:

Name: John Doe
Birthday Date: 01/01/2001
Address:
123 Balamory Road
London
LN1 1NL

That's what I'm looking to achieve (and what I currently achieve using Zapier) but I'm struggling on where to start on the Google Calendar side of things. The best I can think of at the moment is to use the Javascript agent but I'm putting this out there to see if there is something I've overlooked.

Thanks!

**Comment by dsander** [comment]
Google has an [API](https://developers.google.com/google-apps/calendar/v3/reference/) for the Calendar Events, and it should be possible to query it using a `PostAgent` when the correct `oAuth` authentication headers are used. The filtering of the Events would most likely involve a `JavascriptAgent`.

**Comment by cawilliamson** [comment]
Any advice on how to configure the oauth Google authentication step?

Since Huginn doesn't have built in support (that I'm aware of) for Google Calender API nor Google oauth in any way - I'm confused as to where to start in terms of getting my oauth credentials approved for access to my Google account to allow this to happen?

Thanks!

**Comment by dsander** [comment]
@cawilliamson Were you able to figure it out? Most oAuth providers have a sandbox in which you can generate the auth token manually which then can be passed as a header in the PostAgent. Those specs might work: https://developers.google.com/identity/protocols/OAuth2ForDevices

**Comment by dereitz** [comment]
Please share if you solved this.  Thanks!
