### ISSUE TITLE
View diagram : Too many agent to display

### ISSUE THREAD

**Issue by kornflex** [cantino/huginn#1664]
Hello,

I have transfer Huginn from docker to my production serveur ( without docker ) and now, when I want to show the diagram, I have this error : 
"Too many agent to display, please check unused agents "

How can I fix this ?

**Comment by dsander** [comment]
Hi @kornflex,

that is a limitation of the Google Chart API. You can use graphviz to render the Agent graphs. First check if it is installed on your server: `which dot` should return a path, if it doesn't on ubuntu and debian the package is called `graphviz`.
Configure Huginn to use graphviz by activating the `USE_GRAPHVIZ_DOT` setting in `.env`, export the configuration (if you used the manual installation guide) and restart Huginn.

**Comment by kornflex** [comment]
Thank you ! It's working fine !

**Comment by dsander** [comment]
Great! :)

**Comment by MingShyanWei** [comment]
I provide another method.



```ruby
diff --git a/app/helpers/dot_helper.rb b/app/helpers/dot_helper.rb
index db83a42..98d9e71 100755
--- a/app/helpers/dot_helper.rb
+++ b/app/helpers/dot_helper.rb
@@ -8,15 +8,17 @@ module DotHelper
         } rescue false)
       decorate_svg(svg, agents).html_safe
     else
-      uriquery = URI.encode_www_form(cht: 'gv', chl: agents_dot(agents))
-      #Get query maximum length should be under 2048 bytes with including "chart?" of google chart request url
-      if uriquery.length > 2042*3
-        "Too many agent to display, please check unused agents"
-      else
-        tag('img', src: URI('https://chart.googleapis.com/chart').tap { |uri|
-              uri.query = uriquery
-           })
-      end
+
+      url = URI("https://chart.googleapis.com/chart")
+      http = Net::HTTP.new(url.host, url.port)
+      http.use_ssl = true
+      http.verify_mode = OpenSSL::SSL::VERIFY_NONE
+
+      request = Net::HTTP::Post.new(url)
+      request.body = URI.encode_www_form(cht: 'gv', chl: agents_dot(agents))
+      response = http.request(request)
+      tag('img', src: 'data:image/jpg;base64,'+Base64.encode64(response.read_body))
+
     end
   end

```

**Comment by MingShyanWei** [comment]
@cantino  
Yes.  the Google Chart API supports HTTP POST for chart requests up to 16K long. (*1)
And, Embed Base64-Encoded Images Inline In HTML <img> tag.

(*1) https://developers.google.com/chart/image/docs/post_requests

:)

**Comment by cantino** [comment]
Awesome! Would you be interested in sending us a pull request for this?

**Comment by MingShyanWei** [comment]
Sure. I'll do it later.
:)
