### ISSUE TITLE
How to replace linefeed characters?

### ISSUE THREAD

**Issue by Kaboomki** [cantino/huginn#1677]
Hi this seems to be a simple one, nevertheless I am trying to figure it out since yesterday with no sucess:

1. Website Agent grabs me a list of values X from some li elements on a website. The resulting payload is separated by linefeed characters: `Value A\nValue B\nValue C\n`

2. Event Formatting Agent should replace line feed with comma. I used 
`{{X | replace: '\n',','}}`

3. A Dry Run gives me the results as expected:
`Value A,Value B,Value C,`

4. Surprisingly the events produced still contain the original line feeds
`Value A\nValue B\nValue C\n`

5. Filters like "strip_newlines" work a expected, but I am loosing all of my separators. I ve also tried to change the string with regex_replace with the same result.

Any ideas?

Thank you very much.

**Comment by dsander** [comment]
Hi @Kaboomki,

that is interesting it looks like the `\n` is escaped differently when its stored in the database. Can you try to add one or two more backslashes?

**Comment by Kaboomki** [comment]
Thanks. Using '\\n' or '\\\n with the replace filter didn't help. I was able to do the desired replacement using:
`{{X | newline_to_br | strip_newlines | replace:'<br />',','}}`

However, the payload:
`<br />Value A<br /><br />Value B<br />`
is displayed:
`\\nValue A\\n\\nValue B\\n`
in the Dry Run preview. Is this intended?

**Comment by dsander** [comment]
Hmm no that looks odd, I will have to look into that. The output is correct when the Agent is not dry running?

**Comment by dsander** [comment]
@Kaboomki I think I tracked down the issue, the problem is that we do not handle new line characters properly when dry running Agents. #1715  should fix that.

Can you try do use this instruction in the `EventFormattingAgent`? `{{data | newline_to_br | strip_newlines | replace: '<br />', ','}}` working with newlines in liquid is a bit bulky :)

**Comment by Kaboomki** [comment]
Thanks! I can confirm that this workaround works. See my comment above. :-)
