### ISSUE TITLE
Twitter Agent Error

### ISSUE THREAD

**Issue by cvdsouza** [cantino/huginn#1685]
Here is the sequence of what I've done so far : 
1. Added a Twitter Service and authenticated. 
2. Added a Twitter Service Agent 
           When I click save , I get the following error : 

"2 errors prohibited this Agent from being saved:
Service can't be blank

Twitter consumer_key, consumer_secret, oauth_token, and oauth_token_secret are required to authenticate with the Twitter API. You can provide these as options to this Agent, or as Credentials with the same names, but starting with 'twitter_'.v"

I then went into the production.log file to check if there were any errors : 

[2016-09-14T17:56:45.823271 #4487]  INFO -- : [e489e543-6dc8-4cab-a1b8-6ed330840c61] Processing by AgentsController#create as HTML
I, [2016-09-14T17:56:45.823723 #4487]  INFO -- : [e489e543-6dc8-4cab-a1b8-6ed330840c61]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"MHIDxAMBBuX6a+jh8TAhW2TT9qN5vQtJVG26+mQ9aJWxJRGdnucRRMv2qMrjVM4k83c1RkZrScUOKiNN1PjT0g==", "return"=>"", "agent"=>{"type"=>"Agents::TwitterStreamAgent", "name"=>"phish", "service_id"=>"4", "schedule"=>"every_30m", "control_target_ids"=>[""], "keep_events_for"=>"0", "source_ids"=>[""], "propagate_immediately"=>"0", "receiver_ids"=>[""], "scenario_ids"=>["", "1"], "options"=>"{\r\n  \"filters\": [\r\n    \"Company\",\r\n    \"Comp\"\r\n  ],\r\n  \"expected_update_period_in_days\": \"2\",\r\n  \"generate\": \"events\"\r\n}"}, "commit"=>"Save"}
I, [2016-09-14T17:56:46.855120 #4487]  INFO -- : [e489e543-6dc8-4cab-a1b8-6ed330840c61]   Rendered agents/_oauth_dropdown.html.erb (4.5ms)
I, [2016-09-14T17:56:46.886066 #4487]  INFO -- : [e489e543-6dc8-4cab-a1b8-6ed330840c61]   Rendered agents/_options.erb (0.9ms)
I, [2016-09-14T17:56:46.887395 #4487]  INFO -- : [e489e543-6dc8-4cab-a1b8-6ed330840c61]   Rendered agents/_form.html.erb (1002.5ms)
I, [2016-09-14T17:56:46.888062 #4487]  INFO -- : [e489e543-6dc8-4cab-a1b8-6ed330840c61]   Rendered agents/new.html.erb within layouts/application (1004.9ms)
I, [2016-09-14T17:56:46.894924 #4487]  INFO -- : [e489e543-6dc8-4cab-a1b8-6ed330840c61]   Rendered layouts/_navigation.html.erb (4.9ms)
I, [2016-09-14T17:56:46.895857 #4487]  INFO -- : [e489e543-6dc8-4cab-a1b8-6ed330840c61]   Rendered layouts/_messages.html.erb (0.2ms)
I, [2016-09-14T17:56:46.896244 #4487]  INFO -- : [e489e543-6dc8-4cab-a1b8-6ed330840c61]   Rendered application/_upgrade_warning.html.erb (0.1ms)
I, [2016-09-14T17:56:46.903096 #4487]  INFO -- : [e489e543-6dc8-4cab-a1b8-6ed330840c61] Completed 200 OK in 1079ms (Views: 1018.6ms | ActiveRecord: 5.1ms)
I, [2016-09-14T17:56:47.758373 #4487]  INFO -- : [c1dd64fc-406a-4340-addc-c0a323090763] Started GET "/agents/type_details?type=Agents%3A%3ATwitterStreamAgent" for 72.88.205.66 at 2016-09-14 17:56:47 -0700
I, [2016-09-14T17:56:47.761243 #4487]  INFO -- : [c1dd64fc-406a-4340-addc-c0a323090763] Processing by AgentsController#type_details as JSON
I, [2016-09-14T17:56:47.761584 #4487]  INFO -- : [c1dd64fc-406a-4340-addc-c0a323090763]   Parameters: {"type"=>"Agents::TwitterStreamAgent"}
I, [2016-09-14T17:56:47.776003 #4487]  INFO -- : [c1dd64fc-406a-4340-addc-c0a323090763]   Rendered agents/_oauth_dropdown.html.erb (3.8ms)
I, [2016-09-14T17:56:47.777680 #4487]  INFO -- : [c1dd64fc-406a-4340-addc-c0a323090763]   Rendered agents/_options.erb (0.8ms)
I, [2016-09-14T17:56:47.780104 #4487]  INFO -- : [c1dd64fc-406a-4340-addc-c0a323090763] Completed 200 OK in 18ms (Views: 1.6ms | ActiveRecord: 0.7ms)

I cannot pin point any error here. 

Was wondering what I'm doing wrong here. Attaching screenshot. 

![image](https://cloud.githubusercontent.com/assets/1090828/18534995/7b7a59ee-7abe-11e6-9a3e-eebd9287f4da.png)

**Comment by dsander** [comment]
Hi @cvdsouza,

thanks for reporting the issue, it should be fixed on master now.
