### ISSUE TITLE
feature request: display current time somewhere in the app

### ISSUE THREAD

**Issue by mogorman** [cantino/huginn#1687]
If you are in wrong timezone it might be confusing to find out when events will actually fire. also if there is a clock skew between you and host might be annoying too

**Comment by WangQiru** [comment]
I don't think it's an issue, Huginn uses server time.
Just go to terminal `date` or `date --help` and make sure you set your server time zone correctly?

**Comment by mogorman** [comment]
if im a user and not the maintainer I wouldnt be able to check that.  it seems like something that could fit in the header and be fairly useful

**Comment by cantino** [comment]
You could add a simple info / about page to the menu maybe?

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions or want to implement this change.
