### ISSUE TITLE
Twitter Stream Agent Error

### ISSUE THREAD

**Issue by cvdsouza** [cantino/huginn#1689]
Hi, Apologies for raising multiple issue consecutively. 

I'm attempting to get a handle on the twitter usage with Huginn for a demo to colleagues. 

Here are the steps I followed : 

- Create a new Agent : Twitter Stream Agent
- Add in Twitter Stream Agent details 

Details: 
Type: Twitter Stream Agent

Schedule: Every 1h

Last checked: 4m ago

Keep events: 1 day

Last event created: never

Events created: 0

Service: Twitter - 07james1

Event receivers: None

Working: No

Options: 
{
  "filters": [
    "Company",
    "comp"
  ],
  "expected_update_period_in_days": "1",
  "generate": "events"
}

I run the agent - 

Error from Logs : 

Agents::TwitterStreamAgent-22-a0e5e62347f57419c5ff8aab4ab456da99520775 Exception Broken pipe @ io_write - <STDERR>:
/home/huginn/huginn/app/models/agents/twitter_stream_agent.rb:200:in `write'
/home/huginn/huginn/app/models/agents/twitter_stream_agent.rb:200:in `puts'
/home/huginn/huginn/app/models/agents/twitter_stream_agent.rb:200:in `block in stream!'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:287:in `receive_error'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:216:in `handle_headers_complete'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:128:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:128:in `<<'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/twitter-stream-f7e7edb0bae0/lib/twitter/json_stream.rb:128:in `receive_data'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'

I'm not sure how to debug this log. I have Huginn set up as production 

I use : 
cd /home/huginn/huginn && sudo bundle exec rake production:start and cd /home/huginn/huginn && sudo bundle exec rake production:stop to start and stop Huginn.

and 
sudo service nginx restart 
for the Nginx server. 

Would you be able to give me some advice on what I'm doing wrong here? 

Appreciate the help. 

Thanks, 
Clinton 

 PS : Also Tried the below from previous issue posts I read
bundle exec foreman start

Got the following: 

22:33:15 web.1  | started with pid 17971
22:33:15 jobs.1 | started with pid 17973
22:33:16 web.1  | exited with code 1
22:33:16 system | sending SIGTERM to all processes
22:33:16 jobs.1 | terminated by SIGTERM

**Comment by dsander** [comment]
`Exception Broken pipe` looks like the process can not write to STDOUT, did you get the output from `logs/job-1/current`?

If you followed the manual installation guide doing `sudo bundle exec rake production:start` is the correct command, `foreman start` is only used directly in development.

You can try to reexport the services by running `sudo bundle exec rake production:export`

**Comment by cvdsouza** [comment]
Thank you very much . sudo bundle exec rake production:export worked. Getting streams now. 

Thanks once again.

**Comment by dsander** [comment]
Awesome! Glad it's working now 😄
