### ISSUE TITLE
How to use Huginn to post job to selected job board upon creating a job post on my job board?

### ISSUE THREAD

**Issue by AfolabiOlaoluwa** [cantino/huginn#1693]
Upon creating a job post on my job board, I want an agent that post the same job post to a number of selected free job boards.

**Comment by cantino** [comment]
That sounds somewhat complex, but if they all have APIs, you should be able to do it with PostAgents and WebsiteAgents.

**Comment by AfolabiOlaoluwa** [comment]
Thank you. I will see how I can. It's a task I have never tried.

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.
