### ISSUE TITLE
HTML body is not working perfectly for Email Agent

### ISSUE THREAD

**Issue by Noyalcitrus** [cantino/huginn#1696]
Hai,
	While sending a mail using Email Agent, HTML body is not working perfectly
	ie. All the tags are working(h1,<h2,table etc...) But when I use any styles like 'bgcolor' or 'align' or any other styles are not supporting 

My body : 
`<html><body><h1>welcome</h1><h1>welcome</h1><table border=\"1\"><tr bgcolor=\"red\"><th>Name</th><th>Age</th></tr><tr align=\"center\"><td>noyal</td><td>20</td></tr><tr><td>jamsheer</td><td>38</td></tr></table></body></html>`

and also tried without html and body tag

`<h1>welcome</h1><h1>welcome</h1><table border=\"1\"><tr bgcolor=\"red\"><th>Name</th><th>Age</th></tr><tr align=\"center\"><td>noyal</td><td>20</td></tr><tr><td>jamsheer</td><td>38</td></tr></table>`

**Comment by cantino** [comment]
Hey @Noyalcitrus.  Have you tried `style="background-color: red;"`?

**Comment by Noyalcitrus** [comment]
I tried with 
`<html><body><h1>welcome</h1><h2 style=\"background-color: red;\">welcome</h2><table border=\"1\"><tr style=\"background-color: blue;\"><th>Name</th><th>Age</th></tr><tr><td>noyal</td><td>20</td></tr><tr><td>jamsheer</td><td>38</td></tr></table></body></html>`

and without html and body tag

But no change ..... same problem

**Comment by blackalegator** [comment]
Escaping double quotes is quite tricky, I suggest you use \x22 instead of \"

**Comment by Noyalcitrus** [comment]
cool, Thanks 
 Its working Perfectly

**Comment by cantino** [comment]
Thanks for checking! #1712 will add this to master.
