### ISSUE TITLE
Not able to create twitter user agent

### ISSUE THREAD

**Issue by TheReal1604** [cantino/huginn#1697]
Hey Guys,

my huginn instance is running with docker and i am able to authenticate against twitter. (Setting env parameters via docker-compose like the description in the wiki: https://github.com/cantino/huginn/wiki/Configuring-OAuth-applications)

After that, i am unable to create an twitter user agent, the service is already enabled under "services".

![2016-09-20 09_55_23-huginn](https://cloud.githubusercontent.com/assets/5877910/18662028/b2e80bde-7f18-11e6-9666-864eece4ce39.jpg)

Irritating, Service is filled.. but he says "service can´t be blank".. Anyone have an idea?

Thank you!

Edit: I also tried to save the oauth key and so on via the credentials tab, no success.

**Comment by dsander** [comment]
Hey @TheReal1604,

we fixed that issue a few days ago, can you try it with the latest docker image?

**Comment by TheReal1604** [comment]
@dsander Thanks for the info! The actual docker-image is working like a charm.
