### ISSUE TITLE
ForecastIO is now The Dark Sky

### ISSUE THREAD

**Issue by Warloxx** [cantino/huginn#1700]
[The Forecast API is now The Dark Sky API](http://status.darksky.net/2016/09/20/forecast-api-is-now-dark-sky-api.html)

So the API URL for the Weather agent should be updated from `https://api.forecast.io/` to `https://api.darksky.net/`.

They say the old one should still work, but I guess that is not guaranteed forever.

**Comment by cantino** [comment]
Hey @Warloxx, thanks! Would you be interested in sending in a PR?  (If not, I'm happy to do it.)

**Comment by Warloxx** [comment]
I found out that the weather agent uses the external library https://github.com/darkskyapp/forecast-ruby to get to the forcast.io data. This library has already been patched with the new API endpoint as of Version 2.0.1.
So this is already solved by externals.

The only thing that remains is that the name "forcast io" will still remain in the instructions of the agent. Should this be changed? I might dabble in creating a PR for that.

**Comment by cantino** [comment]
It sounds like then we'd need to `bundle update forcast-ruby` and edit the text in the instructions.

**Comment by Warloxx** [comment]
That should not be necessary. The descriptions I meant should all be in the weather agent Ruby file. It just calls upon the library to get the data as far as I understand.

**Comment by cantino** [comment]
Well, if you want Huginn to use the newer version of the forcast-ruby gem that has the new API endpoint, we'd need to bundle update it.

**Comment by cantino** [comment]
Hey @Warloxx, would you mind testing #1722?
