### ISSUE TITLE
cannot connect to url

### ISSUE THREAD

**Issue by vanucci** [cantino/huginn#1702]
Hello i have googled and gone over my file edits several times. I'm new at this. 

I have installed everything via the manual installation on ubuntu 14

i edited the env file to have the server ip on it, but kept the port 3000 the same. 

Yet when i go to the ip=port, i get nothing at all. problem loading page.
Where could i have gone wrong ?

`:/home/huginn/huginn# sudo bundle exec rake production:status
run: huginn-jobs-1: (pid 18304) 9s; run: log: (pid 17761) 171s
run: huginn-web-1: (pid 18302) 10s; run: log: (pid 17763) 171s
`

**Comment by dsander** [comment]
Hi @vanucci,

if you followed the guide include the nginx configuration you should be able to access Huginn by only using the IP or domain name of your server: `http://<your-ip>`. Port 3000 is usually used in development setups, `DOMAIN` in `.env` should also be your ip or domain name without a port.
When you can not access Huginn please paste the output of the log file listed in the [troubleshooting](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#troubleshooting) section.

**Comment by vanucci** [comment]
I'm starting from scratch again. Thanks for your input also.
