### ISSUE TITLE
cannot create tables

### ISSUE THREAD

**Issue by vanucci** [cantino/huginn#1703]
Hello 

I started a fresh install and when i try to run this command 
`sudo -u huginn -H bundle exec rake db:create RAILS_ENV=production`

I get this output error 

`Mysql2::Error: Access denied for user 'huginn'@'localhost' to database 'huginn_d                                                                                                             evelopment': CREATE DATABASE`huginn_development`DEFAULT CHARACTER SET`utf8`
/usr/local/lib/ruby/gems/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in`_q                                                                                                             uery'
/usr/local/lib/ruby/gems/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `bl                                                                                                             ock in query'
/usr/local/lib/ruby/gems/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in`ha                                                                                                             ndle_interrupt'
/usr/local/lib/ruby/gems/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `qu                                                                                                             ery'
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/conne                                                                                                             ction_adapters/abstract_mysql_adapter.rb:309:in`block in execute'
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/conne                                                                                                             ction_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/not                                                                                                             ifications/instrumenter.rb:20:in`instrument'
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/conne                                                                                                             ction_adapters/abstract_adapter.rb:478:in `log'
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/conne                                                                                                             ction_adapters/abstract_mysql_adapter.rb:309:in`execute'
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/conne                                                                                                             ction_adapters/mysql2_adapter.rb:231:in `execute'
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/conne                                                                                                             ction_adapters/abstract_mysql_adapter.rb:379:in`create_database'
/home/huginn/huginn/lib/ar_mysql_column_charset/main.rb:72:in `create_database'
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks                                                                                                             /mysql_database_tasks.rb:16:in`create'
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks                                                                                                             /database_tasks.rb:93:in `create'
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks                                                                                                             /database_tasks.rb:107:in`block in create_current'
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks                                                                                                             /database_tasks.rb:276:in `block in each_current_configuration'
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks                                                                                                             /database_tasks.rb:275:in`each'
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks                                                                                                             /database_tasks.rb:275:in `each_current_configuration'
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks                                                                                                             /database_tasks.rb:106:in`create_current'
/usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railt                                                                                                             ies/databases.rake:17:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in`block i                                                                                                             n execute'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in`execute                                                                                                             '
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block i                                                                                                             n invoke_with_call_chain'
/usr/local/lib/ruby/2.3.0/monitor.rb:214:in`mon_synchronize'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_                                                                                                             with_call_chain'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in`                                                                                                             invoke_task'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in`                                                                                                             each'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in`                                                                                                             run_with_threads'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in`b                                                                                                             lock in run'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in`r                                                                                                             un'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>                                                                                                             '
/usr/local/bin/rake:23:in`load'
/usr/local/bin/rake:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in`load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:74:in                                                                                                              `kernel_load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli/exec.rb:27:in`run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:332:in `ex                                                                                                             ec'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/t                                                                                                             hor/command.rb:27:in`run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/t                                                                                                             hor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/t                                                                                                             hor.rb:359:in`dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:20:in `dis                                                                                                             patch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/vendor/thor/lib/t                                                                                                             hor/base.rb:440:in`start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/cli.rb:11:in `sta                                                                                                             rt'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/exe/bundle:34:in`block in <t                                                                                                             op (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/friendly_errors.r                                                                                                             b:100:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/exe/bundle:26:in`<top (requi                                                                                                             red)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in`<main>'
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8mb4", "recon                                                                                                             nect"=>true, "database"=>"huginn_development", "pool"=>10, "username"=>"huginn",                                                                                                              "password"=>"***", "host"=>nil, "port"=>nil, "socket"=>"/var/run/mysqld/                                                                                                             mysqld.sock", "strict"=>false}
rake aborted!
Mysql2::Error: Access denied for user 'huginn'@'localhost' to database 'huginn_d                                                                                                             evelopment'
/home/huginn/huginn/lib/ar_mysql_column_charset.rb:7:in `block in establish_conn                                                                                                             ection'
/home/huginn/huginn/lib/ar_mysql_column_charset.rb:6:in`tap'
/home/huginn/huginn/lib/ar_mysql_column_charset.rb:6:in `establish_connection'
/usr/local/bin/bundle:23:in`load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
`

the `.env` file have the correct database details. 

i removed the " around password also and that didnt change anything. As far as im aware, the setup is right ?

**Comment by vanucci** [comment]
oh, i see a space in database name

**Comment by vanucci** [comment]
ok, like a true noob i forgot/didnt know that i had to uncomment the db ips etc. which i have done now and i get this error 

`#<Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)>
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "reconnect"=>true, "database"=>"huginn_development", "pool"=>10, "username"=>"huginn", "password"=>"***", "host"=>"localhost", "port"=>3306, "socket"=>"/tmp/mysql.sock", "strict"=>false}, {:charset=>"utf8", :collation=>"utf8_unicode_ci"}
(If you set the charset manually, make sure you have a matching collation)
rake aborted!
Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
/home/huginn/huginn/lib/ar_mysql_column_charset.rb:7:in `block in establish_connection'
/home/huginn/huginn/lib/ar_mysql_column_charset.rb:6:in `tap'
/home/huginn/huginn/lib/ar_mysql_column_charset.rb:6:in `establish_connection'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
`

**Comment by dsander** [comment]
Try removing this line from your `.env` file:

```
DATABASE_SOCKET=/tmp/mysql.sock
```
The lines in the examples starting with a `#` are commented out.

**Comment by vanucci** [comment]
hello, thankls for the reply. I tried this but get the same error as above.

**Comment by dsander** [comment]
Then the mysql user and password you set up in [step 4](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#4-database) probably does not match the `DATABASE_USERNAME` and `DATABASE_PASSWORD`. An other possibility is that you named the database `huginn_production` but use `DATABASE_NAME=huginn_development` in `.env`

Can you connect to the database from the console?
```
sudo -u huginn -H mysql -u huginn -p -D huginn_production
```
Is the command if you are using the default `huginn` username and `huginn_production` as the database name.

**Comment by cantino** [comment]
I'm going to close this issue. Please reopen if you have further questions.
