### ISSUE TITLE
Scenario Share Space

### ISSUE THREAD

**Issue by JamiePhonic** [cantino/huginn#1706]
In leu of the fact the we still dont have a dedicated place to share our scenarios #390 , i thought it might be a good idea to create a thread for them in the mean time.

Format should ideally be a paragraph or 2 explaining what the scenario does and a link to either a github repo or pastebin.

Ill start with this one i cobbeled together to scrape a list of TV shows and their UK air dates from www.geektown.co.uk/uk-air-dates **once every 7 days**, filter them for the shows we care about (listed in the scenario description) and only those that have dates, format them nicely, concatinate them into one event and emit that to wherever you like (default is pushbullet)

Beware this scenario is only of use to people in the UK, though it could be adapted to use other sources.
Feel free to modify it for your own purposes or suggest alterations to streamline it or add functionality.

http://pastebin.com/RRcK3EEz

~~TODO: find a way to invert the sort order of the list. the current setup will have the TV shows airing furthest from the current date at the top, i.e. the dates are sorted in decending order. Best i can tell is because when the digest agent recieves an event, it adds it to the top of the list rather than the bottom.~~
Fixed! It was as easy as adding `reverse` to the digest agent's liquid template. Who'da thought!
I've updated the code on pastebin

**Comment by cantino** [comment]
Nice!

**Comment by JamiePhonic** [comment]
After searching through the other issue posts, i found this scenario created by @McGriddle (#384) which scrapes `http://www.reddit.com/r/GameDeals` to provide notifications on Gamedeals for things like free games and pricing errors. By default, this scenario uses PushOver to send its notifications:

http://pastebin.com/jts6rHyK

I also found this collection of scenarios by @virtadpt from #390.
His Github page explains what they do, so go and check them out!

https://github.com/virtadpt/exocortex-agents

**Comment by cantino** [comment]
There are also [some on the wiki](https://github.com/cantino/huginn/wiki/Agent-configuration-examples)

**Comment by JamiePhonic** [comment]
Forgot about this 😜 
Closed by issue #1774
