### ISSUE TITLE
Including the url in the event sent by WebsiteAgent

### ISSUE THREAD

**Issue by mskog** [cantino/huginn#1710]
**Scenario**
I want to watch for changes for a bunch of sites and then when they change I want to post the url to a Slack channel.

Everything works just fine except that I can't seem to figure out a way to have the event from a WebsiteAgent contain the url it is using. Can this be done?

**Comment by cantino** [comment]
You could set `mode` to `merge` and set `url_from_event` to `{{ url }}` in the WebsiteAgent, then make an EventFormattingAgent pass `url` into the WebsiteAgent. It'll come out the other side because of the `merge`.

**Comment by bobbysteel** [comment]
Alternatively, if you can find the URL on the page itself somewhere, you can just extract that as part of the process. For example:

`{
  "expected_update_period_in_days": "90",
  "url": "https://www.amazon.co.uk/HP-Original-C9732A-Laserjet-Cartridge/dp/B000077CF5/",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "body_text": {
      "xpath": "//*[@id=\"priceblock_ourprice\"]",
      "value": "substring-after(.,\"£\")"
    },
    "url": {
      "xpath": "//link[@rel='canonical']/@href",
      "value": ".//text()"
    }
  }
}`

**Comment by bobbysteel** [comment]
@cantino do you think it'd make sense to output the input url (checking that the url is not set otherwise in the extraction)? Seems like it would be a useful feature w/o breaking backward compatibility. It's v useful for my various checks as some pages don't have the URL anywhere in the Xpath and otherwise an EventFormattingAgent seems needlessly complex (I'd have to create one for each WebsiteAgent which would be a pain)
Thanks

**Comment by cantino** [comment]
@bobbysteel, that seems reasonable, but what if a user has an extraction key called `url` already?

**Comment by bobbysteel** [comment]
Logically I guess just only fill if there's no existing key by that name?
Sort of like a default value?

**Comment by cantino** [comment]
You could try adding that if you like and send a PR. It seems reasonable, although maybe it should be an option like `include_url` or something?

**Comment by bobbysteel** [comment]
Happy to try although I'm warning you you're gonna get some seriously bad
code :)

**Comment by bobbysteel** [comment]
Strangely, looking at the code this seems to be already in there, just in a kind of buggy way. In line 341 you see 
`          result[name] = output[name][index]
          if name.to_s == 'url' && url.present?
            result[name] = (url + Utils.normalize_uri(result[name])).to_s
          end
        end`

So to test, if you include a valid extract key/value as 'url' it automatically returns the url. This should probably be changed to add an include_url option then just use that option here to do that.

**Comment by bobbysteel** [comment]
I've added a PR https://github.com/cantino/huginn/pull/1748

**Comment by cantino** [comment]
I believe this has been fixed.
