### ISSUE TITLE
backup for huginn

### ISSUE THREAD

**Issue by krdurquh** [cantino/huginn#1711]
I've read over much of the documentation and studied the example_backup.rb file, and i have a few questions. 

1) 
"
(#) In your crontab do something like:
(#) 0 0,12 * * * /bin/bash -l -c "RAILS_ENV=production backup perform -t huginn_backup --config_file /home/you/huginn_backup.rb" 2>&1 >> /home/you/huginn_backup_log.txt
"

In my terminal window, would i just type: 
"crontab -e"
and then add the above line?   Is it that simple? That's a one-time only thing? 

2) 
Also, I've never purchased a domain to host huginn, so can I safely delete these from the backup.rb file:
    database.host               = "your-database-host"
    database.port               = "your-database-port"
    database.socket             = "your-database-socket"

    mail.domain               = "example.com"
    mail.user_name            = 'you@example.com'
? 

3) Lastly, 
For SSL encryption, there are instructions that say: 

"
(#) In backups.password on your server:
(#) some password
"

I'm not sure how to make a file with a ".password" extension. 
If i make a file called "backups.password.rtf", and then include this in the file: 

encrypt_with OpenSSL do |encryption|
    encryption.password_file = "/home/you/backups.password.rtf"
    encryption.base64        = true
    encryption.salt          = true
  end

Would that work? 

Thanks for any help!

**Comment by cantino** [comment]
Well, you'd need to make sure you have the correct version of the backup gem installed. I'd actually suggest just taking database dumps instead of using the backup.rb config if you haven't worked with it or cron before.

**Comment by krdurquh** [comment]
haha thanks, fair enough. 
done.
