### ISSUE TITLE
Combine Similar Payloads

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1714]
Hi,

How can I take a list of payloads with similar data for example

Payload 1
{
"Name" : "Name1"
}
Payload 2
{
"Name" : "Name2"
}
Payload 3
{
"Name" : "Name2"
}

Then use an agent to combine them into one?

Payload New
{
"Name" : "Name1, Name2, Name3"
}

**Comment by dsander** [comment]
Hey,

a `DigestAgent` should be able to do that, change `message` in the default "message" option to `Name` and you should get the desired result. If you need more flexibility there is the `JavascriptAgent`.

**Comment by signallhill** [comment]
on DigestAgent is this how to do it? Its not working

{{ events | map: 'Name' | join: ',' }}

**Comment by dsander** [comment]
Did you send the events to the digest agent before you ran it? The events
it received should show up in the digest agents memory.

**Comment by signallhill** [comment]
@dsander Yes its working, I edited the last comment.

How about events from 2 different agents? How would I do that? 

So 
Payload 1/Agent 1
{
Name: "Name1, Name2, Name3"
}

Paload 1/ Agent 2
{
Address:"Address1, Address2, Address3"
}

Output

Payload1/Agent3
{
Name: "Name1, Name2, Name3",
 Address:"Address1, Address2, Address3"
}

**Comment by dsander** [comment]
I think that would require a JavaScriptAgent because the digest agent only
has one output attribute

**Comment by signallhill** [comment]
I don't know JS. Here is my shot in the dark. 

Agent.receive = function() {
  var events = this.incomingEvents();
  for(var i = 0; i < events.length; i++) {
      this.createEvent({ 'Name': '{{Name}}','Address':'{{Address}}' });
    }
}

**Comment by signallhill** [comment]
Its not working how can it be done?

**Comment by cantino** [comment]
This isn't tested, but should be close:

```js
Agent.receive = function() {
    var merged_event = this.memory('merged_event') || {};
    this.incomingEvents().forEach(function(event) {
        Object.keys(event).forEach(function(key) {
          merged_event[key] = event[key];
        });
    });
    this.memory('merged_event', merged_event);
};
Agent.check = function() {
    var merged_event = this.memory('merged_event');
    this.createEvent(merged_event);
    this.memory('merged_event', {});
};
```

**Comment by signallhill** [comment]
Thank you.

**Comment by cantino** [comment]
If it worked for you, mind posting it on the wiki?

**Comment by signallhill** [comment]
Sure
