### ISSUE TITLE
PushoverAgent will not override event hash's keys

### ISSUE THREAD

**Issue by dgw** [cantino/huginn#1718]
PushoverAgent uses the event payload's `url`/`title`/`message` no matter what, if they exist. There is NO WAY to override any of these if the sending agent specifies them in the event.

It took me some time to figure out that this was why I couldn't override the data sent in RssAgent events, but now that I have I looked at the code for PushoverAgent—it's using the event data first, so if those keys exist it never checks its own config.

Expected behavior would be using the configured values from its own hash, then falling back to the event's if its own are not defined.

**Comment by knu** [comment]
One way to fix this may be make the agent always use the ones in options, which are defaulted to `{{ url }}`, `{{ title }}`, and `{{ message }}`.

**Comment by dgw** [comment]
This might be simple enough for me to hack on myself, if Huginn doesn't mind me editing agents while it's running. Can I just edit the agent's `.rb` file and re-emit an event to test, or would testing be more involved than that?

**Comment by knu** [comment]
Or you could create an EventFormattingAgent to put between the source agents and the pushover agent.

**Comment by knu** [comment]
@dgw Mind giving the above PR a try?

**Comment by dgw** [comment]
@knu Params are being overridden as expected with that PR checked out. Thanks!
