### ISSUE TITLE
how to use Website Scraper to pull from "itunes:summary" field?

### ISSUE THREAD

**Issue by willenglishiv** [cantino/huginn#1721]
Or more succinctly:

```
{
  "expected_update_period_in_days": "2",
  "url": "<itunes podcast feed>",
  "type": "xml",
  "mode": "on_change",
  "extract": {
    "itunes_image": {
      "css": "item itunes:image",
      "value": "@href"
    },
    "itunes_subtitle": {
      "css": "item itunes:subtitle",
      "value": ".//text()"
    }
  },
  "events_order": [
    [
      "{{_index_}}",
      "number",
      true
    ]
  ]
}
```

This does not retrieve any items.  I'm guessing it's because of the itunes namespace.

**Comment by cantino** [comment]
By default it drops namespaces, I think, but you could change this.  Does "item subtitle" work?

**Comment by willenglishiv** [comment]
actually, I ended up using xpath from another example, and also learned quickly that you have to have even item numbers when scraping so. . there's that.

Item Closed.  Mission Complete.
