### ISSUE TITLE
Trouble Installing To Raspberry Pi 3

### ISSUE THREAD

**Issue by acronomic** [cantino/huginn#1726]
Hi,  

  I'm very excited about working with Huginn and bought a Rpi 3 to run it on.  However, I'm having a bit of trouble bundling some of the gems.  I followed a number of guides, and at the moment, gem install gets stuck on unf_ext.

`Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory: /tmp/bundler20161007-16062-unp7l7unf_ext-0.0.7.1/gems/unf_ext-0.0.7.1/ext/unf_ext
/usr/bin/ruby2.3 -r ./siteconf20161007-16062-wdgukt.rb extconf.rb`

When I try: sudo gem install unf_ext -v '0.0.7.1' I get the following error:

`current directory: /tmp/bundler20161007-16062-unp7l7unf_ext-0.0.7.1/gems/unf_ext-0.0.7.1/ext/unf_ext
make "DESTDIR="
compiling unf.cc
In file included from unf/normalizer.hh:10:0,
             from unf.cc:1:

unf/table.hh:13539:25: error: narrowing conversion of ‘-27’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
  -77, -39,-124, -39,-123};`

The above is followed by a very long list of err: narrowing conversion of ## from int to char inside {} [-Wnarrowing] errors

I am compiling with gcc: 6.1.1 20160802 (Raspbian 6.1.1-11+rpi1)

I'm a beginner with all of this, so any help would be greatly appreciated. Thanks.

**Comment by dsander** [comment]
Hi @acronomic,

did you follow the [manual installation guide](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md)? I installed Huginn to my Raspberry Pi 3 a few weeks ago and just updated it to the latest version without issues.

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

# uname -a
Linux raspberrypi 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux
```

**Comment by acronomic** [comment]
Hi @dsander,

  Thanks for the response.  I successfully installed huginn to one of my Rpi's, but was having trouble running the server locally, so I tried to install on another SD card, using the quick instructions for running in development mode.  I updated Ruby to 2.3.0 as well as upgrade the operating system: `Linux raspberrypi 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux` , which is likely why it is not working.

  I am now revisiting my prior project (the one I setup according tot he manuall installation guide) to try to figure out how to deploy locally.  Can I run it in production mode off the raspberry pi?  Or do I have to bundle it in development mode?  Will both modes allow me to to run off localhost:3000?

Do I still want to comment out these lines:
web: bundle exec rails server -p ${PORT-3000} -b ${IP-0.0.0.0}
jobs: bundle exec rails runner bin/threaded.rb

And enable the others?

And should all db:migrates be done in RAILS_ENV=production mode?

And should my nginx YOUR_SERVER_FQDN, be localhost?

Thanks.

**Comment by dsander** [comment]
I am not sure what you are trying to do with the Huginn installation on the Raspberry. Maybe the wording we are using is a bit confusing. By "Local" installation we mean a development installation which is used to make changes to the Huginn source code (add or modify Agents for example).

"Production" (which the manual installation guide does) means a installation which runs on a server (or your Raspberry) and is intended to only "use" Huginn. Even though your Rapsberry is "local" I am assuming you would like to run Huginn in production.

Generally you should follow all steps in the manual installation guide and not mix it with any of the "local" or "quick setup" guides.



> Do I still want to comment out these lines:
> web: bundle exec rails server -p ${PORT-3000} -b ${IP-0.0.0.0}
> jobs: bundle exec rails runner bin/threaded.rb

Yes, comment out these and use [those](https://github.com/cantino/huginn/blob/master/Procfile#L24-L25).


> And should all db:migrates be done in RAILS_ENV=production mode?

Yes use the command from the guide:

```
# Create the database
sudo -u huginn -H bundle exec rake db:create RAILS_ENV=production

# Migrate to the latest version
sudo -u huginn -H bundle exec rake db:migrate RAILS_ENV=production

# Create admin user and example agents using the default admin/password login
sudo -u huginn -H bundle exec rake db:seed RAILS_ENV=production SEED_USERNAME=admin SEED_PASSWORD=password
```


> And should my nginx YOUR_SERVER_FQDN, be localhost?

If you only installed Huginn on the Raspberry you do not have do modify the nginx configuration file, only make sure to delete the default config: `sudo rm /etc/nginx/sites-enabled/default`

You can access Huginn with the IP of your Rapsberry or the hostname (if your router has a local DNS server): `http://<raspberry-ip>`

**Comment by acronomic** [comment]
Thank you for clarifying.  This is the first time I am hosting a server so the setup is a bit confusing. I followed your directions, and am going to explore why I am having trouble, but just two more quick question.

1.  For the .env files, should I be leave the DOMAIN NAME: localhost:3000 and PORT:3000 or should I switch these settings to the rpi's ip? Nginx says that it is running successfully, but I am getting a 502 bad gateway error.  I suppose that means its running, but it is misconfigured.

2.  When I run `sudo bundle exec rake production:status` should I see a response? At the moment I am not receiving any message. (Just the command prompt returns)

**Comment by dsander** [comment]
Using the IP for `DOMAIN` should be fine. To be honest I don't know off the top of my head where that setting is used :)

Did you run `sudo bundle exec rake production:export` after modifying the `Procfile`?

**Comment by acronomic** [comment]
Hi,  

  I was having such problems getting the server up, I decided to try a fresh install, but am having a few problems. 

1.  I followed the manual instructions to compile ruby 2.3.1 and uninstall all prior versions of ruby.  The system wouldn't detect it the newly compiled version (2.3.1), so I moved it from the /tmp/ruby folder to /bin.  My system seems to find it now, and I was able to follow all the steps up to 
`sudo -u huginn -H bundle install --deployment --without development test`

where I get the error

`Git error: command `git fetch --force --quiet --tags "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/cache/bundler/git/kaminari-c1443b2ed1fb966de1732843115af93c356a7818"` in directory
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/kaminari-abbf93d55720 has failed.
If this error persists you could try removing the cache directory '/home/huginn/huginn/vendor/bundle/ruby/2.3.0/cache/bundler/git/kaminari-c1443b2ed1fb966de1732843115af93c356a7818'`

I have tried to remove this cache file, but now I get this error

`Git error: command `git clone 'git://github.com/amatsuda/kaminari.git' "/home/huginn/huginn/vendor/bundle/ruby/2.3.0/cache/bundler/git/kaminari-c1443b2ed1fb966de1732843115af93c356a7818" --bare --no-hardlinks --quiet` in directory
/home/huginn/huginn has failed.`


2.  Each time I try to get my rake secret, (I have tried rake secret / bundle exec rake secret / sudo bundle exec rake secret), I receive the following error message:

`[!] There was an error parsing `Gemfile`: Permission denied @ rb_sysopen - /home/huginn/huginn/.env. Bundler cannot continue.  

 #  from /home/huginn/huginn/Gemfile:12
 #  -------------------------------------------
 #  require File.join(File.dirname(__FILE__), 'lib/gemfile_helper.rb')
 >  GemfileHelper.load_dotenv do |dotenv_dir|
 #    path dotenv_dir do
 #  -------------------------------------------`

I have tried to upgrade and update but to no avail.    Here's the spec's I'm on:

Linux raspberrypi 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux
ruby 2.3.1p112 (2016-04-26 revision 54768) [armv7l-linux-eabihf]
Bundler version 1.13.3

Thank you.

**Comment by dsander** [comment]
The last error looks like there is a permission error while reading the `.env` file. 

Try
```
sudo chown -R huginn:huginn /home/huginn
```
And rerun bundle install.

**Comment by acronomic** [comment]
Great.  I believe I'm one step away, everything seems to be installed, the server seems to be running, but, when I visit the rpi's IP, I am getting this message: 

RuntimeError at /
Missing `secret_key_base` for 'production' environment, set this value in `config/secrets.yml`

Ruby	/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb: in validate_secret_key_config!, line 513
Web	GET 192.168.1.23/

I believe this is because I didn't type in the rake secret code in the .env.  I tried again to run rake secret and bundle exec rake secret, but I am getting this message:

[!] There was an error parsing `Gemfile`: Permission denied @ rb_sysopen - /home/huginn/huginn/.env. Bundler cannot continue.

 #  from /home/huginn/huginn/Gemfile:12
 #  -------------------------------------------
 #  require File.join(File.dirname(__FILE__), 'lib/gemfile_helper.rb')
 >  GemfileHelper.load_dotenv do |dotenv_dir|
 #    path dotenv_dir do
 #  -------------------------------------------

**Comment by acronomic** [comment]
Thank you.  Everything is working now.

**Comment by dsander** [comment]
Awesome, glad it works!

**Comment by acronomic** [comment]
One more issue I'm having:  When I visit the server (rpi's IP), the page seems to lack any css formatting, and all the image links are broken.  I tried precompiling again, and I made sure, that my nginx config file has:

`server_name 192.168.1.20`;
The root in this nginx file is:   root /home/huginn/huginn/public;

But seems like the server can't find the assets folder.  Inside public/assets, these files are there:
`
ace-4e193d62772eb46b3e33b90c99811375c038d990970594e9e60621da58816f94.js
ace-4e193d62772eb46b3e33b90c99811375c038d990970594e9e60621da58816f94.js.gz
diagram-072c739e4bef92087fecac9a4e641837e6a3dcfd05ebc778a7ac4f5404ad911b.js
diagram-072c739e4bef92087fecac9a4e641837e6a3dcfd05ebc778a7ac4f5404ad911b.js.gz
graphing-360e28afaff0bf480b668387aae8e0dff375d0643c5835a6cc1c792ae5b1d1a8.js
graphing-360e28afaff0bf480b668387aae8e0dff375d0643c5835a6cc1c792ae5b1d1a8.js.gz
map_marker-ef508669b3c04b7afea8043caba6ac252b05752b8c2e01eb1bca1dd483db7aef.js
map_marker-ef508669b3c04b7afea8043caba6ac252b05752b8c2e01eb1bca1dd483db7aef.js.gz
odin-4aea0258f53748e9cc20b6ddd655824d8d1b26901015d43ad97c6d166bf88227.jpg
select2-d6b5d8d83dbc18fb8d77c8761d331cd9e5123c9684950bab0406e98a24ac5ae8.png
select2-spinner-f6ecff617ec2ba7f559e6f535cad9b70a3f91120737535dab4d4548a6c83576c.gif
select2x2-6fe28d687dc0ed4d96016238c608ba1e7198c9c9accfa0b360b78018b9fb9bc2.png
spinner-arrows-f4cfc5bc84f34fa882bc9125cd8730bb4ea4844c0ac6fd981bae2de9bb33aebc.gif
`

But still even after restarting I can't seem to see the page as its suppose to be displayed.

**Comment by cantino** [comment]
There's a step in the guide about compiling assets. Did you do that step when you deployed?

**Comment by acronomic** [comment]
Yep,  and I just tried it again:
`sudo -u huginn -H bundle exec rake assets:precompile RAILS_ENV=production`

And also exported, and restarted the nginx server
`sudo bundle exec rake production:export`

but no luck.

**Comment by dsander** [comment]
Can you check the nginx logs that are mentioned in the [troubleshooting](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#troubleshooting) section?

It might be a permission issue, try `cd /home/huginn/huginn/; sudo chmod -R u+rwX,go-w,go+rx log/ tmp/` to fix it.

**Comment by acronomic** [comment]
Hmm.  Tried the code you listed.  Css/ Images still are broken.  Here's what I have in my logs:

errors from /var/log/nginx/huginn_error.log:
`
2016/10/12 12:04:29 [error] 1519#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.1.15, server: 192.168.1.23, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "192.168.1.23"
2016/10/12 12:04:29 [error] 1519#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.1.15, server: 192.168.1.23, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "192.168.1.23"`

Inside my unicorn log:
`
192.168.1.15 - - [12/Oct/2016:03:33:01 -0700] "GET / HTTP/1.0" 200 - 0.3117
192.168.1.15 - - [12/Oct/2016:03:33:01 -0700] "GET /404 HTTP/1.0" 404 728 0.0114
192.168.1.15 - - [12/Oct/2016:03:33:01 -0700] "GET /404 HTTP/1.0" 404 728 0.0087
192.168.1.15 - - [12/Oct/2016:03:33:01 -0700] "GET /404 HTTP/1.0" 404 728 0.0087
I, [2016-10-12T04:07:58.377759 #467]  INFO -- : reaped #<Process::Status: pid 1348 exit 0> worker=0
I, [2016-10-12T04:07:58.378299 #467]  INFO -- : master complete
I, [2016-10-12T11:08:11.117002 #463]  INFO -- : Refreshing Gem list
I, [2016-10-12T05:00:19.937677 #463]  INFO -- : unlinking existing socket=/home/huginn/huginn/tmp/sockets/unicorn.socket
I, [2016-10-12T05:00:19.939004 #463]  INFO -- : listening on addr=/home/huginn/huginn/tmp/sockets/unicorn.socket fd=11
I, [2016-10-12T05:00:19.976138 #463]  INFO -- : master process ready
I, [2016-10-12T05:00:19.990944 #1355]  INFO -- : worker=0 ready
I, [2016-10-12T05:04:17.231265 #463]  INFO -- : reaped #<Process::Status: pid 1355 exit 0> worker=0
I, [2016-10-12T05:04:17.231598 #463]  INFO -- : master complete
I, [2016-10-12T12:04:24.440705 #1471]  INFO -- : Refreshing Gem list
I, [2016-10-12T05:04:43.619108 #1471]  INFO -- : unlinking existing socket=/home/huginn/huginn/tmp/sockets/unicorn.socket
I, [2016-10-12T05:04:43.619857 #1471]  INFO -- : listening on addr=/home/huginn/huginn/tmp/sockets/unicorn.socket fd=11
I, [2016-10-12T05:04:43.656959 #1471]  INFO -- : master process ready
I, [2016-10-12T05:04:43.671122 #1546]  INFO -- : worker=0 ready
192.168.1.15 - - [12/Oct/2016:05:05:23 -0700] "GET / HTTP/1.0" 200 - 0.3041
192.168.1.15 - - [12/Oct/2016:05:05:23 -0700] "GET /404 HTTP/1.0" 404 728 0.0109
192.168.1.15 - - [12/Oct/2016:05:05:23 -0700] "GET /404 HTTP/1.0" 404 728 0.0090
192.168.1.15 - - [12/Oct/2016:05:05:23 -0700] "GET /404 HTTP/1.0" 404 728 0.0087
192.168.1.15 - - [12/Oct/2016:05:42:19 -0700] "GET / HTTP/1.0" 200 - 0.0414
192.168.1.15 - - [12/Oct/2016:05:42:19 -0700] "GET /404 HTTP/1.0" 404 728 0.0156
192.168.1.15 - - [12/Oct/2016:05:42:19 -0700] "GET /404 HTTP/1.0" 404 728 0.0150
192.168.1.15 - - [12/Oct/2016:05:42:19 -0700] "GET /404 HTTP/1.0" 404 728 0.0156
`

I made sure that I had the following uncommented in my Procfile:
`
web: bundle exec unicorn -c config/unicorn.rb
jobs: bundle exec rails runner bin/threaded.rb`

**Comment by dsander** [comment]
Thats odd, did you use the example nginx configuration without modifications except for possibly the `server_name`?

Please paste the last entries from the nginx access log `/var/log/nginx/huginn_access.log`

**Comment by acronomic** [comment]
Here's my access from today:
`
192.168.1.15 - - [12/Oct/2016:10:33:01 +0000] "GET / HTTP/1.1" 200 1450 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.15 - - [12/Oct/2016:10:33:01 +0000] "GET /stylesheets/application.css HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.15 - - [12/Oct/2016:10:33:01 +0000] "GET /javascripts/application.js HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.15 - - [12/Oct/2016:10:33:01 +0000] "GET /images/odin.jpg HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
192.168.1.15 - - [12/Oct/2016:12:04:29 +0000] "GET / HTTP/1.1" 502 568 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:12:05:23 +0000] "GET / HTTP/1.1" 200 1453 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:12:05:23 +0000] "GET /stylesheets/application.css HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:12:05:23 +0000] "GET /javascripts/application.js HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:12:05:23 +0000] "GET /images/odin.jpg HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:12:05:23 +0000] "GET /android-chrome-192x192.png HTTP/1.1" 304 0 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:12:05:23 +0000] "GET /android-chrome-48x48.png HTTP/1.1" 304 0 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:12:42:19 +0000] "GET / HTTP/1.1" 200 1450 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:12:42:19 +0000] "GET /stylesheets/application.css HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:12:42:19 +0000] "GET /javascripts/application.js HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:12:42:19 +0000] "GET /images/odin.jpg HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:13:35:06 +0000] "GET / HTTP/1.1" 502 568 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:13:35:09 +0000] "GET / HTTP/1.1" 502 568 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:13:35:12 +0000] "GET / HTTP/1.1" 502 568 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:13:37:53 +0000] "GET / HTTP/1.1" 200 1450 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:13:37:53 +0000] "GET /stylesheets/application.css HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:13:37:53 +0000] "GET /javascripts/application.js HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:13:37:53 +0000] "GET /images/odin.jpg HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:13:49:47 +0000] "GET / HTTP/1.1" 200 1451 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:13:49:47 +0000] "GET /stylesheets/application.css HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:13:49:47 +0000] "GET /javascripts/application.js HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [12/Oct/2016:13:49:47 +0000] "GET /images/odin.jpg HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"`

Nginx conf (nothing but server_name changed):`
server {
  listen 0.0.0.0:80 default_server;
  listen [::]:80 ipv6only=on default_server;
  server_name 192.168.1.23; ## Replace this with something like huginn.example.com
  server_tokens off; ## Don't show the nginx version number, a security best practice
  root /home/huginn/huginn/public;

  ## Increase this if you want to upload large attachments
  client_max_body_size 20m;

  ## Individual nginx logs for this Huginn vhost
  access_log  /var/log/nginx/huginn_access.log;
  error_log   /var/log/nginx/huginn_error.log;

  location / {
    ## Serve static files from defined root folder.
    ## @huginn is a named location for the upstream fallback, see below.
    try_files $uri $uri/index.html $uri.html @huginn;
 }`

**Comment by dsander** [comment]
Ah! Those requests look like their are coming from a development configuration. Check your `.env` and ensure `RAILS_ENV=production` is enabled. After re-exporting and restarting Huginn you should see the images and stylesheets.

**Comment by acronomic** [comment]
Hi, attaching my .env lines here.  I tried exporting `sudo bundle exec rake production:export` and restarting 'sudo service nginx restart` `sudo bundle exec rake production:start`

both using DOMAIN:localhost, and using DOMAIN:193.168.1.23, as you can see below.  RAILS_ENV=production is enabled.   Could there be some other configuration somewhere that needs to be adjusted for production?
`
# This is the domain where your Huginn instance will be running. The default should work
# for development, but it needs to be changed to your Huginn domain when you deploy to a
# production environment (e.g., yourdomain.com, possibly including a port).
#DOMAIN=localhost:3000
#PORT=3000
DOMAIN=192.168.1.23

# Optionally set an asset host
# ASSET_HOST=http://assets.example.com

############################
#      Database Setup      #
############################

DATABASE_ADAPTER=mysql2
DATABASE_ENCODING=utf8
DATABASE_RECONNECT=true
DATABASE_NAME=huginn_production
DATABASE_POOL=20
DATABASE_USERNAME=huginn
DATABASE_PASSWORD=#######
#DATABASE_HOST=your-domain-here.com
#DATABASE_PORT=3306
#DATABASE_SOCKET=/tmp/mysql.sock

# MySQL only: If you are running a MySQL server >=5.5.3, you should
# set DATABASE_ENCODING to utf8mb4 instead of utf8 so that the
# database can hold 4-byte UTF-8 characters like emoji.
DATABASE_ENCODING=utf8mb4

# ==== Additional required production settings ====

# Configure Rails environment.  This should only be needed in production and may cause errors in development.
RAILS_ENV=production

# Should Rails force all requests to use SSL?
FORCE_SSL=false
`

**Comment by dsander** [comment]
I don't think so, request from a production instance include a hash after the file name like this:
```
31.16.225.128 - - [12/Oct/2016:13:55:31 -0400] "GET /assets/application-65997864ab9844be9c6355f69e0785ee69f779012de3d9a062522523b08190cc.css
```

Is it possible multiple application servers are running? `ps aux|grep "unicorn master"` should only return one process.

`cat /etc/service/huginn-web-1/env/RAILS_ENV` should return `production`. If both are true try rebooting the Raspberry.

**Comment by acronomic** [comment]
I am seeing two results from ps aux:
`huginn    2399  2.3  9.7 126220 92424 ?        Sl   17:52   0:19 unicorn master -c config/unicorn.rb
pi        2564  0.0  0.2   4276  1944 pts/0    S+   18:05   0:00 grep --color=auto unicorn master`

`cat /etc/service/huginn-web-1/env/RAILS_ENV` is returning production

**Comment by dsander** [comment]
And you are still getting the same request in the nginx access log?

**Comment by acronomic** [comment]
They seem a bit different.  

`192.168.1.15 - - [13/Oct/2016:10:33:36 +0000] "GET /images/odin.jpg HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [13/Oct/2016:10:33:36 +0000] "GET /images/spinner-arrows.gif HTTP/1.1" 404 446 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [13/Oct/2016:10:33:40 +0000] "GET /agents HTTP/1.1" 200 5235 "http://192.168.1.23/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [13/Oct/2016:10:33:40 +0000] "GET /javascripts/application.js HTTP/1.1" 404 446 "http://192.168.1.23/agents" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [13/Oct/2016:10:33:40 +0000] "GET /stylesheets/application.css HTTP/1.1" 404 446 "http://192.168.1.23/agents" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [13/Oct/2016:10:33:40 +0000] "GET /images/spinner-arrows.gif HTTP/1.1" 404 446 "http://192.168.1.23/agents" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [13/Oct/2016:10:33:57 +0000] "GET /agents/14?return=%2Fagents HTTP/1.1" 200 3934 "http://192.168.1.23/agents" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [13/Oct/2016:10:33:57 +0000] "GET /javascripts/application.js HTTP/1.1" 404 446 "http://192.168.1.23/agents/14?return=%2Fagents" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [13/Oct/2016:10:33:57 +0000] "GET /stylesheets/application.css HTTP/1.1" 404 446 "http://192.168.1.23/agents/14?return=%2Fagents" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
192.168.1.15 - - [13/Oct/2016:10:33:57 +0000] "GET /images/spinner-arrows.gif HTTP/1.1" 404 446 "http://192.168.1.23/agents/14?return=%2Fagents" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"`

No longer the hash after the file name.  But still I am not seeing any of the images or css formatting.

**Comment by dsander** [comment]
The problem is that the requested files do not have the hash in their names. 

Sorry, I am running out of ideas, your configuration looks correct to be but since the hash is missing the application server seems not to be running in production mode.

What does `cd /home/huginn/huginn && sudo -u huginn -H bundle exec rails runner "puts ENV['RAILS_ENV']"` output?

**Comment by acronomic** [comment]
Running that command outputs production.

I can try to reinstall from scratch.  Maybe it is something to do with upgrading the Rpi?  I noticed that your linux install is a bit older.  The only step that I did out of order, was input the rake secret in the .env file after bundling and then re-export.   Could that have anything to do with it?

**Comment by dsander** [comment]
I am not sure, I will also reinstall my Raspberry with the current image and check if I am getting the same problem you are having.

**Comment by dsander** [comment]
I reinstalled my Raspberry and everything looks good to me. During the asset precompilation libv8 segfaulted, but switching to a a slightly older Huginn version resolved the problem: `sudo -u huginn -H git checkout 8efe50ad9901f821bdbc78d6c8a4e2897e890eeb`

**Comment by acronomic** [comment]
Tried a fresh install, but I am encountering the same issue.  Also access logs still have no hash in their http requests.  I tried running this git command, now do I have to rebundle in this head state?  Not very familiar with git.

**Comment by dsander** [comment]
It depends which version you were running previously, to be safe run [step 4](https://github.com/cantino/huginn/blob/master/doc/manual/update.md#4-install-gems-migrate-and-precompile-assets) and [step 7](https://github.com/cantino/huginn/blob/master/doc/manual/update.md#7-export-init-script-and-start-huginn) of the upgrade guide.

Does it help if you clear the browser cache?

What is the output of that command? `curl -s http://localhost |grep script` (depending of the way you configured Nginx you might need to replace `localhost` with the IP of your Raspberry)

**Comment by acronomic** [comment]
This worked.  Thank you so much for all your help.

**Comment by dsander** [comment]
Nice! :)
