### ISSUE TITLE
Json and payload_path

### ISSUE THREAD

**Issue by nachiarg** [cantino/huginn#1732]
I'm having issues building a webhook agent for the following Json from a Kerberos installation . I don't know how to create just one event for it because the payload_path ="." Or $.web_request creates several events.

Could anyone give me a hand?

{
  "regionCoordinates": [
    388,
    308,
    535,
    599
  ],
  "numberOfChanges": 4442,
  "incoming": 1,
  "outgoing": 0,
  "timestamp": "1476391523",
  "microseconds": "6-438745",
  "token": 736,
  "pathToImage": "1476391523_6-438745_frontdoor_388-308-535-599_4442_736.jpg",
  "instanceName": "frontdoor",
  "web_request": {
    "regionCoordinates": [
      388,
      308,
      535,
      599
    ],
    "numberOfChanges": 4442,
    "incoming": 1,
    "outgoing": 0,
    "timestamp": "1476391523",
    "microseconds": "6-438745",
    "token": 736,
    "pathToImage": "1476391523_6-438745_frontdoor_388-308-535-599_4442_736.jpg",
    "instanceName": "frontdoor"
  }
}

**Comment by dsander** [comment]
Hi @nachiarg,

`payload_path: "."` should be working, are you sure Huginn isn't receiving more then one request? If it keeps being an issue you could use a `DeDuplicationAgent` to filter out the duplicates.

**Comment by nachiarg** [comment]
Ive manage to correctly configure a DeDuplicationAgent but I want to clean up the original agent

![image](https://cloud.githubusercontent.com/assets/21292817/19395251/0dee9892-9213-11e6-9d55-8faf75ac91e4.png)

**Comment by nachiarg** [comment]
For example if I want to send as a payload only the token.  I would think it should go like this



> {
>   "secret": "kerberos",
>   "expected_receive_period_in_days": 1,
>   "response": "Event Created",
>   "code": "201",
>   "payload_path": "$..token"
> 
>  }
> 


Original JSON

> {

> "regionCoordinates": [
> 388,
> 308,
> 535,
> 599
> ],
> "numberOfChanges": 4442,
> "incoming": 1,
> "outgoing": 0,
> "timestamp": "1476391523",
> "microseconds": "6-438745",
> "token": 736,
> "pathToImage": "1476391523_6-438745_frontdoor_388-308-535-599_4442_736.jpg",
> "instanceName": "frontdoor",
> "web_request": {
> "regionCoordinates": [
> 388,
> 308,
> 535,
> 599
> ],
> "numberOfChanges": 4442,
> "incoming": 1,
> "outgoing": 0,
> "timestamp": "1476391523",
> "microseconds": "6-438745",
> "token": 736,
> "pathToImage": "1476391523_6-438745_frontdoor_388-308-535-599_4442_736.jpg",
> "instanceName": "frontdoor"
> }
> }

**Comment by dsander** [comment]
When you followed the manual installation guide the request logs should be in `/home/huginn/huginn/log/production.log`, sites like http://requestb.in/ let you inspect the raw data that is send.

When the JSON payload is an array the WebHookAgent will emit an Event per array entry, would that explain the amount of events you are seeing?

**Comment by nachiarg** [comment]
Solved, Kerberos was expecting a 200 , not a 201, so it was looping.

Thanks!

**Comment by dsander** [comment]
Great 😄
