### ISSUE TITLE
Is it possible to ass parameters by URL?

### ISSUE THREAD

**Issue by aborruso** [cantino/huginn#1737]
Dear all,
imagine that I have built an RSS feed starting from a page that does not have it.

I would like to use a filter - all the feed items that contain the world "dog" - and apply this filter calling the rss huginn URL. Something like http://myhuginnsite/myfeed?filter=dog

Is it possible?

Thank you

**Comment by dsander** [comment]
Hi @aborruso,

that is not possible at the moment (and would probably be tricky to implement), but you can use `TriggerAgent`s to filter the events before they go into your `DataOutputAgent` and have a feed for every filter.
