### ISSUE TITLE
Add title of RSS source to events emitted by RSS Agent?

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#1738]
Would it be a fairly straightforward operation to add the title of the blog, website, or other source of an RSS feed to the events emitted by RSS Agent?  It would simplify agent networks where the blog's title would be referenced later in the output.

**Comment by knu** [comment]
Did you try the `include_feed_info` option?

**Comment by nogre** [comment]
I add fields to my RSS agent with the desired information. Then pass the output of the RSS agent to a formatting agent, which has access to the RSS agent's configuration options, and the formatter adds/ modifies the desired fields to the general payload. Then I use the output of the formatting agent. 

For example, my RSS agents have an extra field which I call 'pname' for the 'proper name' of that website. This normally would be lost as it is part of the RSS agent configuration. However, the formatting agent copies all the regular info from the RSS agent and adds a field 'pname: {{agent.options.pname}}' . So whatever the RSS payload is used for later on has the official title easily accessible as part of the payload.

**Comment by cantino** [comment]
Did this work for you @virtadpt?

**Comment by dsander** [comment]
I am closing this issue. Please feel free to reopen if you need further assistance!
