### ISSUE TITLE
Delayed Reaction Agent (Scheduling Events in the Future)

### ISSUE THREAD

**Issue by qedi-r** [cantino/huginn#174]
I'm currently implementing a Weatherunderground Astronomy agent, so that I can trigger things based on sundown/sunrise, so I was wondering what is the best way to schedule events for some time in the future.

If say I knew that sundown was going to be at 6:04 pm, how could I schedule my agent from creating an event then?

**Comment by virtadpt** [comment]
I've just found that I have a use case for this as well: Say an every happens, and I want to trigger another agent two minutes after it happens. And maybe another agent five minutes after that if they're chained (or in parallel and just happen to act like they are). Maybe it consumes the event it's or in received, maybe it emits its item payload as an event. It would certainly save a lot of shell script hackery with --delay=<seconds> if nothing else.

**Comment by cantino** [comment]
This seems like a pretty simple agent to add.

**Comment by cantino** [comment]
We have a DelayAgent now.
