### ISSUE TITLE
Functionality Design of the Deduplication Agent

### ISSUE THREAD

**Issue by level20peon** [cantino/huginn#1740]
I would like to know how the Deduplication Agent handles its task. Let's say I have three Agents:

WebSiteAgent -> Deduplication Agent -> DataOutput Agent

And let's say the WebSiteAgent has its Option "Keep events" set to "1 day". The WebSiteAgent will create 10 events per day. The Deduplication Agent has its Loopback option set to 1000.

Will the Deduplication agent output the same (duplicate) events at day two (and so forth), because the original events from the WebSiteAgent don't exist any longer, or will it still work correctly (as in filter out the duplicates) because the hash of the new events at day two (and so forth) will match the hash of the original events?

I am asking because I get lots of duplicates every day and I am wondering if the issue originates from the fact that I am not storing original events very long once they have been processed. I checked out GIT on July 12th for the last time, but I couldn't see any commits from then which involved the Deduplication Agent, so I guess I'm up to date concerning this specific functionality.

**Comment by dsander** [comment]
The `DeDuplicationAgent` stores CRC32 hashes of the received events (or the `property`depending on how it's options) in the Agent memory, so it does not require the original events to still be present.
Are you using the whole Event for the de-duplication?

**Comment by level20peon** [comment]
No I am using one property, for example the link when I am converting web input data to RSS feeds. The conversion works just fine, in case you wonder - as a mere human I can see that the links match exactly (also there are no extra spaces or anything). I have had this problem for quite a while now and hoped that it was fixed by [this](https://github.com/cantino/huginn/pull/1432) update. Don't get me wrong, I am not getting 10% duplicates, I just notice this behaviour once in a while so I learned to live with it. But it's not very pretty, since I generate hundreds of RSS items per day, and even in this huge number, I notice duplicates. And according to your description, this behaviour shouldn't occur at all.

**Comment by dsander** [comment]
In theory it could happen due to has collisions, but with the frequency you are describing it seems unlikely. If you change the `lookback` amount, does it change the amount of duplicates you are getting?

To debug the issue we would need some sample data to reproduce the issue, could you share your scenario or gather the Events of your WebsiteAgent for a few days so we can replay the DeDuplicationAgent invocations?

**Comment by level20peon** [comment]
I chose all loopback amounts to match a real world loopback likelyhood (per incoming stream) and then multiplied this times 10. That means that if a stream would put out 1000 items per month and even only 100 of them would be unique I set the loopback to be 10000.

I will compile a list during the next days, when I find the deduplication to be inacurate again.

**Comment by level20peon** [comment]
ok, I got an example... the original event still existed, so that's definitely not the issue here. Website Agent:

    {
      "expected_update_period_in_days": "14",
      "url": "https://www.amazon.de/s?lo=clothing&rh=n:1981351031,p_n_feature_six_browse-bin:3707438031|3707437031,p_n_size_browse-vebin:2136439031&sort=date-desc-rank",
      "type": "html",
      "mode": "on_change",
      "extract": {
        "content": {
          "css": "ul#s-results-list-atf li.s-result-item",
          "value": "./node()"
        }
      }
    }

DeDuplication Agent:

    {
      "property": "{{link}}",
      "lookback": "10000",
      "expected_update_period_in_days": "1"
    }

Payload 1 (5 hours ago):

    {
      "content": "<div class=\"s-item-container\">\n<div class=\"a-row sx-badge-region\"><\/div>\n<div class=\"a-row a-spacing-base\"><div aria-hidden=\"true\" class=\"a-column a-span12 a-text-center s-position-relative\">\n<span class=\"a-declarative\" data-action=\"sx-card-deck\" data-sx-card-deck='{\"cardGroupId\":\"rot-B01KP5C3WC\",\"imageRotations\":[2]}' id=\"rot-B01KP5C3WC\"><div class=\"a-row a-gesture a-gesture-horizontal\"><a class=\"a-link-normal a-text-normal\" href=\"https://www.amazon.de/Pepe-Jeans-Herren-Pullover-blau/dp/B01KP5C3WC/ref=sr_1_1/251-4032746-4434912?s=apparel&amp;ie=UTF8&amp;qid=1476752403&amp;sr=1-1&amp;psc=1\"><div class=\"s-card s-card-group-rot-B01KP5C3WC s-active\">\n                    <img src=\"https://images-eu.ssl-images-amazon.com/images/I/514jzYavzgL._AC_UL260_SR200,260_.jpg\" srcset=\"https://images-eu.ssl-images-amazon.com/images/I/514jzYavzgL._AC_UL260_SR200,260_.jpg 1x, https://images-eu.ssl-images-amazon.com/images/I/514jzYavzgL._AC_UL390_SR300,390_QL65_.jpg 1.5x, https://images-eu.ssl-images-amazon.com/images/I/514jzYavzgL._AC_UL500_SR385,500_QL65_.jpg 1.9230x\" width=\"200\" height=\"260\" alt=\"Pepe Jeans Herren Pullover\" class=\"s-access-image cfMarker\" onload=\"viewCompleteImageLoaded(this, new Date().getTime(), 60, false);\" data-search-image-load data-csm-markers=\"af,cf\">\n<\/div>\n            <div class=\"s-card s-card-group-rot-B01KP5C3WC s-hidden\">\n                    <div data-search-image-load data-search-image-source=\"https://images-eu.ssl-images-amazon.com/images/I/61hXVL5nD6L._AC_UL260_SR200,260_.jpg\" data-search-image-source-set=\"https://images-eu.ssl-images-amazon.com/images/I/61hXVL5nD6L._AC_UL260_SR200,260_.jpg 1x, https://images-eu.ssl-images-amazon.com/images/I/61hXVL5nD6L._AC_UL390_SR300,390_QL65_.jpg 1.5x, https://images-eu.ssl-images-amazon.com/images/I/61hXVL5nD6L._AC_UL520_SR400,520_QL65_.jpg 2x, https://images-eu.ssl-images-amazon.com/images/I/61hXVL5nD6L._AC_UL650_SR500,650_QL65_.jpg 2.5000x\" data-search-image-width=\"200\" data-search-image-height=\"260\" data-search-image-alt=\"Pepe Jeans Herren Pullover\" class=\"data-search-image-stub\" style=\"width: 200px; height: 260px\"><\/div>\n<\/div>\n            <\/a><\/div><\/span><div class=\"a-section a-spacing-none a-text-center\"><div class=\"a-icon-row a-spacing-top-small\">\n<span class=\"a-declarative\" data-action=\"sx-card-deck-indicator\" data-sx-card-deck-indicator='{\"cardGroupId\":\"rot-B01KP5C3WC\",\"cardIndex\":0}'><span class=\"s-indicator-target\">\n                <i class=\"s-card-indicator s-indicator s-card-group-rot-B01KP5C3WC s-active\"><\/i>\n            <\/span>\n        <\/span><span class=\"a-declarative\" data-action=\"sx-card-deck-indicator\" data-sx-card-deck-indicator='{\"cardGroupId\":\"rot-B01KP5C3WC\",\"cardIndex\":1}'><span class=\"s-indicator-target\">\n                <i class=\"s-card-indicator s-indicator s-card-group-rot-B01KP5C3WC\"><\/i>\n            <\/span>\n        <\/span>\n<\/div><\/div>\n<\/div><\/div>\n<div class=\"a-row a-spacing-none\">\n<div class=\"a-row a-spacing-mini\"><a class=\"a-link-normal s-access-detail-page  a-text-normal\" title=\"Pepe Jeans Herren Pullover\" href=\"https://www.amazon.de/Pepe-Jeans-Herren-Pullover-blau/dp/B01KP5C3WC/ref=sr_1_1/251-4032746-4434912?s=apparel&amp;ie=UTF8&amp;qid=1476752403&amp;sr=1-1&amp;psc=1\"><h2 data-attribute=\"Pepe Jeans Herren Pullover\" data-max-rows=\"0\" data-truncate-by-character=\"false\" class=\"a-size-base a-color-null s-inline  s-access-title  a-text-normal\">Pepe Jeans Herren Pullover<\/h2><\/a><\/div>\n<div class=\"a-row a-spacing-none\"><a class=\"a-link-normal a-text-normal\" href=\"https://www.amazon.de/Pepe-Jeans-Herren-Pullover-blau/dp/B01KP5C3WC/ref=sr_1_1/251-4032746-4434912?s=apparel&amp;ie=UTF8&amp;qid=1476752403&amp;sr=1-1&amp;psc=1\"><span class=\"a-size-base a-color-price s-price a-text-bold\">EUR 80,00 - EUR 90,00<\/span><\/a><\/div>\n<\/div>\n<\/div>"
    }

Event 1 created by the DeDuplication Agent (after running it through an EventFormatting Agent):
    {
      "title": "Pepe Jeans Herren Pullover",
      "description": "80,00€<br /><img src=\"https://images-eu.ssl-images-amazon.com/images/I/514jzYavzgL._AC_UL260_SR200,260_.jpg\" />",
      "link": "https://www.amazon.de/Pepe-Jeans-Herren-Pullover-blau/dp/B01KP5C3WC"
    }

Payload 2 (2 hours ago):
    {
      "content": "<div class=\"s-item-container\">\n<div class=\"a-row sx-badge-region\"><\/div>\n<div class=\"a-row a-spacing-base\"><div aria-hidden=\"true\" class=\"a-column a-span12 a-text-center s-position-relative\">\n<span class=\"a-declarative\" data-action=\"sx-card-deck\" data-sx-card-deck='{\"cardGroupId\":\"rot-B01KP5C3WC\",\"imageRotations\":[2]}' id=\"rot-B01KP5C3WC\"><div class=\"a-row a-gesture a-gesture-horizontal\"><a class=\"a-link-normal a-text-normal\" href=\"https://www.amazon.de/Pepe-Jeans-Herren-Pullover-blau/dp/B01KP5C3WC/ref=sr_1_2/252-5891998-3905524?s=apparel&amp;ie=UTF8&amp;qid=1476763204&amp;sr=1-2&amp;psc=1\"><div class=\"s-card s-card-group-rot-B01KP5C3WC s-active\">\n                    <img src=\"https://images-eu.ssl-images-amazon.com/images/I/514jzYavzgL._AC_UL260_SR200,260_.jpg\" srcset=\"https://images-eu.ssl-images-amazon.com/images/I/514jzYavzgL._AC_UL260_SR200,260_.jpg 1x, https://images-eu.ssl-images-amazon.com/images/I/514jzYavzgL._AC_UL390_SR300,390_QL65_.jpg 1.5x, https://images-eu.ssl-images-amazon.com/images/I/514jzYavzgL._AC_UL500_SR385,500_QL65_.jpg 1.9230x\" width=\"200\" height=\"260\" alt=\"Pepe Jeans Herren Pullover\" class=\"s-access-image cfMarker\" onload=\"viewCompleteImageLoaded(this, new Date().getTime(), 60, false);\" data-search-image-load data-csm-markers=\"af,cf\">\n<\/div>\n            <div class=\"s-card s-card-group-rot-B01KP5C3WC s-hidden\">\n                    <div data-search-image-load data-search-image-source=\"https://images-eu.ssl-images-amazon.com/images/I/61hXVL5nD6L._AC_UL260_SR200,260_.jpg\" data-search-image-source-set=\"https://images-eu.ssl-images-amazon.com/images/I/61hXVL5nD6L._AC_UL260_SR200,260_.jpg 1x, https://images-eu.ssl-images-amazon.com/images/I/61hXVL5nD6L._AC_UL390_SR300,390_QL65_.jpg 1.5x, https://images-eu.ssl-images-amazon.com/images/I/61hXVL5nD6L._AC_UL520_SR400,520_QL65_.jpg 2x, https://images-eu.ssl-images-amazon.com/images/I/61hXVL5nD6L._AC_UL650_SR500,650_QL65_.jpg 2.5000x\" data-search-image-width=\"200\" data-search-image-height=\"260\" data-search-image-alt=\"Pepe Jeans Herren Pullover\" class=\"data-search-image-stub\" style=\"width: 200px; height: 260px\"><\/div>\n<\/div>\n            <\/a><\/div><\/span><div class=\"a-section a-spacing-none a-text-center\"><div class=\"a-icon-row a-spacing-top-small\">\n<span class=\"a-declarative\" data-action=\"sx-card-deck-indicator\" data-sx-card-deck-indicator='{\"cardGroupId\":\"rot-B01KP5C3WC\",\"cardIndex\":0}'><span class=\"s-indicator-target\">\n                <i class=\"s-card-indicator s-indicator s-card-group-rot-B01KP5C3WC s-active\"><\/i>\n            <\/span>\n        <\/span><span class=\"a-declarative\" data-action=\"sx-card-deck-indicator\" data-sx-card-deck-indicator='{\"cardGroupId\":\"rot-B01KP5C3WC\",\"cardIndex\":1}'><span class=\"s-indicator-target\">\n                <i class=\"s-card-indicator s-indicator s-card-group-rot-B01KP5C3WC\"><\/i>\n            <\/span>\n        <\/span>\n<\/div><\/div>\n<\/div><\/div>\n<div class=\"a-row a-spacing-none\">\n<div class=\"a-row a-spacing-mini\"><a class=\"a-link-normal s-access-detail-page  a-text-normal\" title=\"Pepe Jeans Herren Pullover\" href=\"https://www.amazon.de/Pepe-Jeans-Herren-Pullover-blau/dp/B01KP5C3WC/ref=sr_1_2/252-5891998-3905524?s=apparel&amp;ie=UTF8&amp;qid=1476763204&amp;sr=1-2&amp;psc=1\"><h2 data-attribute=\"Pepe Jeans Herren Pullover\" data-max-rows=\"0\" data-truncate-by-character=\"false\" class=\"a-size-base a-color-null s-inline  s-access-title  a-text-normal\">Pepe Jeans Herren Pullover<\/h2><\/a><\/div>\n<div class=\"a-row a-spacing-none\"><a class=\"a-link-normal a-text-normal\" href=\"https://www.amazon.de/Pepe-Jeans-Herren-Pullover-blau/dp/B01KP5C3WC/ref=sr_1_2/252-5891998-3905524?s=apparel&amp;ie=UTF8&amp;qid=1476763204&amp;sr=1-2&amp;psc=1\"><span class=\"a-size-base a-color-price s-price a-text-bold\">EUR 80,00 - EUR 90,00<\/span><\/a><\/div>\n<\/div>\n<\/div>"
    }

Event 2 created by the DeDuplication Agent (after running it through an EventFormatting Agent):
    {
      "title": "Pepe Jeans Herren Pullover",
      "description": "80,00€<br /><img src=\"https://images-eu.ssl-images-amazon.com/images/I/514jzYavzgL._AC_UL260_SR200,260_.jpg\" />",
      "link": "https://www.amazon.de/Pepe-Jeans-Herren-Pullover-blau/dp/B01KP5C3WC"
    }

**Comment by dsander** [comment]
How do the incoming events of the DeDuplicationAgent looks like? I am asking because the link in `content` has some postfixes that are different in the two payloads.

**Comment by level20peon** [comment]
The events look the same as the ones being emmited by the DeDuplication Agent... here are the two events generated by the EventFormatting Agent I mentioned, which then ran into the DeDuplication Agent and were both emitted:

Payload 1 (5 hours ago):

    {
      "title": "Pepe Jeans Herren Pullover",
      "description": "80,00€<br /><img src=\"https://images-eu.ssl-images-amazon.com/images/I/514jzYavzgL._AC_UL260_SR200,260_.jpg\" />",
      "link": "https://www.amazon.de/Pepe-Jeans-Herren-Pullover-blau/dp/B01KP5C3WC"
    }

Payload 2 (2 hours ago):

    {
      "title": "Pepe Jeans Herren Pullover",
      "description": "80,00€<br /><img src=\"https://images-eu.ssl-images-amazon.com/images/I/514jzYavzgL._AC_UL260_SR200,260_.jpg\" />",
      "link": "https://www.amazon.de/Pepe-Jeans-Herren-Pullover-blau/dp/B01KP5C3WC"
    }

**Comment by dsander** [comment]
I see, generally those payload work properly. Are you running multiple delayed_job worker or just one?

**Comment by level20peon** [comment]
Multiple (2 total), but I thought this issue was fixed with [this](https://github.com/cantino/huginn/pull/1432) update I mentioned earlier. Apparently it's still an issue.

**Comment by dsander** [comment]
If it's related to multiple workers it is a slightly different issue, do you have the DeDuplicationAgent set to `propagate_immediately`? If that's the case check if unsetting it reduces the duplicates your are getting.

**Comment by level20peon** [comment]
Yes I do have it set to propagate immediately. Should I only set the DeDuplicationAgent to not propagate immediately, or also any Agent which passes data to that DeDuplicationAgent?

**Comment by level20peon** [comment]
Also: why does the immediate propagation influence duplicate finding, if the events that are duplicates are hours apart?

**Comment by dsander** [comment]
Only for the DeDuplicationAgent for now. What I am thinking is that the Agent is run simultaneously in both your workers and thus not properly updating the memory:

```
worker1: DeDup starts and gets the current memory
worker2: starts and gets the current memory
worker1: does it's work adds a property to the seen properties
worker1: Agent is done and the updated memory is written to the database
worker2: finishes and overrides the changes the Agent of worker1 did
```

**Comment by level20peon** [comment]
This scenario is realistic if the duplicate events are created within a few seconds (maybe minutes), but it makes no sense if the duplicate events are created three hours apart. Every memory/database update should have happened ages before it could become a race condition, or am I wrong?

**Comment by dsander** [comment]
No if that scenario is happening the Agent can "forget" any event. Imagine `worker2` handling your `5h ago` event (which never is registered in the seen properties because `worker1` overrides them). When the `2h ago` is handled the Agent thinks it is new and emits it again.

**Comment by level20peon** [comment]
Why is that event not registered in the seen properties? Doesn't it write the hash of the event it saw into the db and the other worker reads that list of hashes before deciding on the new event being a duplicate or not? Why would that change if the "propagate_immediately" option is unchecked?

**Comment by dsander** [comment]
> Doesn't it write the hash of the event it saw into the db and the other worker reads that list of hashes before deciding on the new event being a duplicate or not?

Yes, normally it works like this. What I think might happen is a classic race condition. Both workers run the Agent at the same time, which means they get the memory from the database and both write it back with their own changes (not knowing about what the other worker did). The Agent that finished last thereby overrides the changes of the other one that finished milliseconds before.

Disabling `propagate_immediately` has the effect that the Agent only runs once per minute and processes all events of the last minute. That means the race condition I  am describing can not happen anymore and thus you should not get any duplicates anymore.

**Comment by level20peon** [comment]
So bottomline, "propagate_immediately" has nothing to do with my problem, where events occur hours apart.

**Comment by dsander** [comment]
If my theory is correct it does, like I said it does not matter when the event is received. When the race condition happens the DeDuplication does not register the processed event in the memory. When it receives the same event later it is not considered a duplicate because the `property` is not in the memory.

You don't have to believe me, but please try unsetting `propagate_immediately` for a few days and check if you are getting less or maybe even no duplicates.

**Comment by level20peon** [comment]
I think I understand now - the race condition appears because both workers "synchronize" their memory at the same time, which has nothing to do with database entries.
I will test if disabling immediate propagation will fix this.
Nonetheless a followup question, in the case I understand correctly now: if "propagate_immediately" isn't checked, aren't the workers' memories synchronized every minute at the same time (rather than at random times during one minute), which would lead to a race condition in the first place?

**Comment by dsander** [comment]
I don't hope so, when `propagate_immediately` is disable all events the Agent received in the previous minute will be processed in one job (processed by one worker). 
With it enabled every event creates one job which can result in the Agent being run in parallel when using multiple workers.

**Comment by level20peon** [comment]
ok, I understand... testing is underway.

**Comment by level20peon** [comment]
I think two months without duplicates are a good measure. So, I consider this resolved - thanks for your help!

**Comment by cantino** [comment]
:+1:

**Comment by malagebidi** [comment]
The same situation happened to me when running two workers, it's probably 20 percent chance to get a duplicate one, now I'm trying to disable `propagate_immediately` to test around.

**Comment by dsander** [comment]
That sounds like the same issue as https://github.com/huginn/huginn/issues/2389
