### ISSUE TITLE
Insert date or timestamp in file name

### ISSUE THREAD

**Issue by nachiarg** [cantino/huginn#1745]
Im trying to use de FTP agent to save events from each day. I want to add a timestamp to the file name (timestamp+filename.csv) to avoid rewriting every time the same file.

My flow is:

![image](https://cloud.githubusercontent.com/assets/21292817/19601779/100275f4-9781-11e6-82dc-96e3f3843065.png)

Kerberos Delayer hold the spools for a day and then sends them to CSV parser (Kerberos - Agregador en CSV para FTP ) and then FTP agent saves the file. I want a different file for each day.

Ftp config is: 

"{
  "mode": "write",
  "expected_update_period_in_days": "1",
  "url": "ftp://user:*password*@***.com.**/",
  "force_encoding": "",
  "filename": "kerberos.csv",
  "data": "{{ data }}"
}"

**Comment by knu** [comment]
If each received event contains a timestamp in say, `created_at`, and you want to use it, then try setting the `filename` option to something like `{{ created_at | date: '%FT%T' }}_kerberos.csv`. (See [this document](http://shopify.github.io/liquid/filters/date/) for the time format)
If you want to use the time when the FtpsiteAgent is run, then try `{{ 'now' | date: '%FT%T' }}_kerberos.csv` instead.  The value `'now'` is a special key to get the current time.

I'll add the tips about how to get the current time formatted to [our Wiki page](https://github.com/cantino/huginn/wiki/Formatting-Events-using-Liquid) later.

**Comment by cantino** [comment]
Good tip, thanks @knu! I'm going to close this @nachiarg.  Feel free to post a new issue if you have other questions. :)

**Comment by knu** [comment]
The special word `'now'` was not documented in the latest document, so I've submitted a PR and got it merged: https://shopify.github.io/liquid/filters/date/

**Comment by cantino** [comment]
Nice
