### ISSUE TITLE
SMTP Settings

### ISSUE THREAD

**Issue by nata-lee** [cantino/huginn#1747]
Hello!

I'd like to change email settings to localhost smtp server, but I don't know, how.
I changed smtp settings in the `.env` file and run
```
bundle exec rake production:stop
bundle exec rake production:export
```
no use. 
I updated huginn with instructions
`https://github.com/cantino/huginn/blob/master/doc/manual/update.md`
but settings didn't change.
I also tryed to change `config/initializers/action_mailer.rb` with the same result. Huginn always try to send emails via gmail (it was default setting), I can check it with tcpdump.

I'm sorry, I'm not good at ruby, so I have no idea what else to do. I need to change settings to localhost. I changed `SEND_EMAIL_IN_DEVELOPMENT=true` And also I run huginn in production.

Please help me.

**Comment by dsander** [comment]
Hey!

If you installed Huginn using the manual installation guide the steps you did should have changed the SMTP config. 
When you run `bundle exec rake production:stop` is Huginn really not accessible anymore?

If that is the case restart Huginn with `bundle exec rake production:export`, wait for a minute for the services to start and paste the output of `sudo ps aux|grep huginn`.

**Comment by nata-lee** [comment]
Thank you very much! I missed that huginn was still running. 
Now settings are applied!
