### ISSUE TITLE
Telegram Agent needs file extension when uploading photo

### ISSUE THREAD

**Issue by dan-sullivan** [cantino/huginn#1749]
If your try to send a photo using a URL, the filename needs to end with the file extension (jpg, png etc) or the telegram API will reject it. If your URL has a query string, for instance, the temporary file created will be named "foo.bar?baz=true" and the Telegram API will reject it with the following message:

```
{"ok"=>false, "error_code"=>400, "description"=>"Photo has unsupported extension. Use one of .jpg, .jpeg, .gif, .png, .tif or .bmp"}
```

I've not tested but I suppose this will be the case for videos and other files.

I'm not a Ruby dev but can put some time into resolving this. Would appreciate some guidance on approach though. I thought of using ruby-filemagic to detect the filetype and append the correct extension.

**Comment by cantino** [comment]
This sounds like it may be a bug on the telegram side?

**Comment by dan-sullivan** [comment]
While I agree Telegram have been shortsighted and should be checking a MIME type header, they are verifying the filetype through its filename extension by design.

This has come about from trying to use phantomjscloud to send screenshots. This API call responds with an image.

```https://phantomjscloud.com/api/browser/v2/a-demo-key-with-low-quota-per-ip-address/?request={url:%22http://www.highcharts.com/demo/pie-donut%22,renderType:%22jpg%22}```

The Telegram Agent creates a temporary file from the using this URL as a base.

```file = Tempfile.new [File.basename(url), File.extname(url)]```

However this wont always be enough to work with the Telegram API, as the phantomjscloud example shows.

**Comment by cantino** [comment]
So `File.basename(url)` isn't handling the `?request` portion of the URL correctly, is that right? You could parse the URL first to drop the query, then apply `basename` (in the Ruby code), or condition on the basename matching one of `/\.(gif|jpe?g|png)$/i`, and set it to some default if it doesn't.

**Comment by cantino** [comment]
Were you able to figure this out @dan-sullivan?

**Comment by dsander** [comment]
I am closing this issue. Please feel free to reopen if you need further assistance!
