### ISSUE TITLE
How to get CDATA from RSS feed

### ISSUE THREAD

**Issue by Avalanchaa** [cantino/huginn#1752]
I have an RSS feed agent which gets a `<descripiton>` lable with some CDATA.

How do I extract the real url from `[FULL-ARTICLE-URI] `?

`"description": "[SOURCE]FreshPlaza[/SOURCE]\n[FULL-ARTICLE-URI]http://www.bbcnews.com/article/165592/[/FULL-ARTICLE-URI]"`

**Comment by knu** [comment]
You can create an EventFormattingAgent setting the RssAgent as a source, then make it extract the desired part from `description` and add a new key.

Try setting the following JSON to `options`:
```json
{
  "mode": "merge",
  "matchers": [
    {
      "path": "{{ description )}}",
      "regexp": "\\[FULL-ARTICLE-URI\\](?<content>\\S+?)\\[/FULL-ARTICLE-URI\\]",
      "to": "match"
    }
  ],
  "instructions": {
    "article_url": "{{ match.content }}"
  }
}
```

**Comment by Avalanchaa** [comment]
Works wonderful. Thanks @knu

**Comment by knu** [comment]
Great to hear that!
