### ISSUE TITLE
Issues with Regex

### ISSUE THREAD

**Issue by Avalanchaa** [cantino/huginn#1755]
I am having this issue with Regex on Event Formating Agent. How to get the last 10 digits from url?

`"sort": "{{url | regexp: '\\d*(\\d{10})'}}"`

I know the regular expression works, but its not working on Event Formating Agent.

**Comment by knu** [comment]
I don't think there's such a filter called `regexp`.  Use the `matchers` option or the `regex_replace`/`regex_replace_first` filters documented [here](https://github.com/cantino/huginn/wiki/Formatting-Events-using-Liquid).

**Comment by Avalanchaa** [comment]
You are right, I had to use regex_replace and select all unwanted characters. This worked (although, maybe there is a better way to select the last 10 digits). Thanks @knu 

`"sort": "{{url | regex_replace: '^(.*).-',''}}"`
