### ISSUE TITLE
How to get date from string?

### ISSUE THREAD

**Issue by Avalanchaa** [cantino/huginn#1759]
Can somebody give me a hand on how to get a date from an Event Formatting Agent which contains:

"date": "Iano Kang, (Aug 3, 2016)"

I need to extract the date in any format usable for an RSS.

**Comment by dsander** [comment]
Hi @Avalanchaa,

that should be possible with the date filter: `{{ date | date: "%F"}}`. The [liquid documentation](https://help.shopify.com/themes/liquid/filters/additional-filters#date) has a few formatting examples.

**Comment by Avalanchaa** [comment]
Works well! Thanks for the guidance @dsander !  closing the issue.
