### ISSUE TITLE
Oauth for users (not for developers)

### ISSUE THREAD

**Issue by dadaista** [cantino/huginn#176]
Hi, congrats for the project. Sorry if  i start pointing an issue but I think it can improve a lot the usability. In a use case where one maintaner share the server with many people, for agents based on twitter (or any other oauth provider) it should be possible for the maintaner to register a new app on twitter (one service) but for the other users to authenticate oauth client side (having the twitter login/password opened and then redirected to huginn). Sorry, maybe you have already this in the roadmap, I didn't find among the issues.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further!
