### ISSUE TITLE
Reverse Proxy 

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#1761]
On the data output agent the following is written. What is reverse proxy and how is it done?

push_hubs - Set to a list of PubSubHubbub endpoints you want to publish an update to every time this agent receives an event. (default: none) Popular hubs include Superfeedr and Google. Note that publishing updates will make your feed URL known to the public, **_## so if you want to keep it secret, set up a reverse proxy to serve your feed via a safe URL and specify it in template.self_**

**Comment by cantino** [comment]
You could use nginx to proxy-pass to Huginn, but add a secret or basic auth I think.

**Comment by signallhill** [comment]
After reading on nginx reverse proxy I have some questions.

- So to reverse proxy DataOutputAgent can I just update the current Huginn configuration file in /etc/nginx/sites-available/  with additional location? or do I have to put another config file in sites-available and them reverse proxy it?

- Also will this proxy pass work where there is basic http auth enabled?

**Comment by cantino** [comment]
I don't know the detail for Nginx. It'd be the same as proxy passing from Nginx to any web server.
