### ISSUE TITLE
Does anybody know what happened to beeper.io?

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#1762]
For the past two weeks or so, BeeperAgents have been stuck in retry loops, finally failing, and piling up in the "failed jobs" list, sometimes to the tune of a couple of hundred.

The beeper.io website and api.beeper.io service have been unresponsive for the same period of time, though the domain records still exist and hostnames resolve.

Did they suddenly go out of business?  If so, this agent is pretty much dead and should be removed from the codebase.  Finding something to replace it (or building it - I'll admit I've been considering looking into building a personal push notification daemon) is also an option.

**Comment by bobbysteel** [comment]
Seems like they just abruptly killed it. The parent company Azati still has their website up but no mention of Beeper. There seem to be plenty of options like Pushover, Pushbullet, etc.

**Comment by virtadpt** [comment]
I spent last night rewriting everything to use Pushover.

By the way, while [pushd](https://github.com/rs/pushd) seems like a good solution (and it's fairly straightforward to use) there don't seem to be any generic or universal push notification clients for Android out there.

**Comment by cantino** [comment]
Should we remove the Beeper Agent?

**Comment by bobbysteel** [comment]
Seems sensible @cantino

**Comment by virtadpt** [comment]
I think that would be a good idea - the service is gone so there's no sense in keeping dead code laying around.

**Comment by cantino** [comment]
Removed it.
