### ISSUE TITLE
"no implicit conversion of URI::HTTPS into String" Error

### ISSUE THREAD

**Issue by waldens** [cantino/huginn#1765]
Scenarios as below. I got 'Error when handling event data: no implicit conversion of URI::HTTPS into String' message in second agent ([whole log](http://notepad.pw/c1wigfv2) ). I google it, but nothing useful found, only know it seems ruby relevent. Is there anything I can do to fix it? Thanks.

1 Rss Agent 
```json
{   
  "expected_update_period_in_days": "16",
  "clean": "false",
  "url": "http://vdaily.iu.vc/weekly.xml"
}
```
2 Website Agent
```json
{   
  "expected_update_period_in_days": "20",
  "data_from_event": "{{content}}",
  "type": "html",
  "mode": "merge",
  "extract": {
    "url": {
      "css": "a",
      "value": "@href"
    },
    "title": {
      "css": "a",
      "value": "./node()"
    }
  }
}
```

**Comment by knu** [comment]
This looks like a bug in WebsiteAgent where `handle_event_data()` is passing a non-URI object to `handle_data()`.  Seems it has existed since when the `data_from_event` option was introduced.  I'll come up with a fix shortly.

**Comment by knu** [comment]
I'll merge the above PR later, but in the meantime you can try it out and see it fixes your problem.

**Comment by knu** [comment]
@waldens With the fix merged, would you try it again with the latest master?

**Comment by waldens** [comment]
Tried, works like a charm! Thanks @knu !

**Comment by knu** [comment]
Great!  Thanks for the confirmation.
