### ISSUE TITLE
Error when trying to install via `bundle install`

### ISSUE THREAD

**Issue by Fogest** [cantino/huginn#1785]
I am getting the following error when running the command from the install instructions(`sudo -u huginn -H bundle install --deployment --without development test`):

```
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
/var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/dsl.rb:544:in `parse_line_number_from_description': invalid byte sequence in US-ASCII (ArgumentError)
        from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/dsl.rb:510:in `to_s'
        from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:16:in `to_s'
        from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:16:in `message'
        from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:16:in `log_error'
        from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:102:in `rescue in with_friendly_errors'
        from /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
        from /var/lib/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
```

Many solutions keep saying to use some `export` command or to add an if statement and change the encoding in the gemfile. I seem to be unable to get the `export` part working, presumably because huginn as per the setup is not really running with a bash shell? 

Does anyone know of a fix? Here is a related Stackoverflow answer: http://stackoverflow.com/a/17031697/1044984

I am running Ubuntu 14.04.

**Comment by Fogest** [comment]
I just added the following to my Gemfile and it is now working:

```
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
```

**Comment by cantino** [comment]
That's odd that you needed that.  What is `LANG` set to in your environment? https://docs.ruby-lang.org/en/2.1.0/Encoding.html#class-Encoding-label-External+encoding

**Comment by Fogest** [comment]
@cantino Here is what it is:
```
irb(main):001:0> ENV["LANG"]
=> nil
irb(main):002:0> Encoding.default_external
=> #<Encoding:US-ASCII>
```

I will note that I never actually changed it to do this, this is just how it was when I got it on Ubuntu 14.04.

**Comment by cantino** [comment]
I think LANG should be UTF8 or en_US.UTF-8? Maybe something is wrong with your setup?
