### ISSUE TITLE
Problems with session: changing password ends up in HTTP 500 error page

### ISSUE THREAD

**Issue by elvetemedve** [cantino/huginn#1788]
On **/users/edit** page when I try to change the password for the currently logged in user, I get an HTTP 500 error page.

Relevant part of the log looks like:

> 11:42:37 web.1  | [b6c1a083-8819-44e3-abf4-4505bf060d56] Started PUT "/users" for 172.17.0.1 at 2016-11-12 12:42:37 +0100
> 11:42:37 web.1  | [b6c1a083-8819-44e3-abf4-4505bf060d56] Processing by Users::RegistrationsController#update as HTML
> 11:42:37 web.1  | [b6c1a083-8819-44e3-abf4-4505bf060d56]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"1Ai3W0aT4r2kkKw8BPbRMDWuzKOl/wSGxQdqKMRs97kR6L//BYGEw4VTn6EKUfDQZWnbOQRAQiDEkakVMbfiDg==", "user"=>{"current_password"=>"[FILTERED]", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Update"}
> foreman stdout | 11:42:37 web.1  | [b6c1a083-8819-44e3-abf4-4505bf060d56] Can't verify CSRF token authenticity.
> 11:42:37 web.1  | [b6c1a083-8819-44e3-abf4-4505bf060d56] Completed 500 Internal Server Error in 8ms (ActiveRecord: 0.0ms)
> 11:42:37 web.1  | [b6c1a083-8819-44e3-abf4-4505bf060d56]   
> 11:42:37 web.1  | [b6c1a083-8819-44e3-abf4-4505bf060d56] NoMethodError (undefined method `to_key' for nil:NilClass):
> 11:42:37 web.1  | [b6c1a083-8819-44e3-abf4-4505bf060d56]   
> 11:42:37 web.1  | [b6c1a083-8819-44e3-abf4-4505bf060d56] config/initializers/silence_worker_status_logger.rb:3:in `call'

**Comment by elvetemedve** [comment]
I also cannot log out.

> 11:59:19 web.1  | [a8574739-b48b-4ed8-ac15-bb8bb28d8000] Started DELETE "/users/sign_out" for 172.17.0.1 at 2016-11-12 12:59:06 +0100
> 11:59:19 web.1  | [a8574739-b48b-4ed8-ac15-bb8bb28d8000] Processing by Devise::SessionsController#destroy as HTML
> 11:59:19 web.1  | [a8574739-b48b-4ed8-ac15-bb8bb28d8000]   Parameters: {"authenticity_token"=>"SyihixZ/VPvyxZtonJ/T+Z7IpJjgthepCciKEarrpAeOyKkvVW0yhdMGqPWSOPIZzg+zAkEJUQ8IXkksXzCxsA=="}
> 11:59:19 web.1  | [a8574739-b48b-4ed8-ac15-bb8bb28d8000] Can't verify CSRF token authenticity.

**Comment by elvetemedve** [comment]
I think the key is **Can't verify CSRF token authenticity.** message. Something is wrong with session storage. 
Any idea what to check out?

**Comment by cantino** [comment]
That's odd @elvetemedve. I just tried it locally and was able to change a password and log out. Did you change anything about the cookies in your browser, or your Huginn session storage?

**Comment by elvetemedve** [comment]
Thanks for the feedback.
I updated the Docker application image (the multi-process one) to the latest version. I didn't do anything else.
I tried to view the application in a private browser tab, but it did not let me in at login.
The database might have damaged. I'll check MySQL.

**Comment by elvetemedve** [comment]
Database looks good.

As I see Rails stores [session data on the client side in a cookie](https://github.com/cantino/huginn/blob/master/config/initializers/session_store.rb). So I checked out other browsers and I found that only **Chromium** and **Google Chrome 54.0.2840** has this issue. For example login works well with Firefox and Opera.
I think Chome has different cookie handling, that's why Rails cannot decode session data and therefore could not find the CSRF token in the session storage.

**Comment by dsander** [comment]
It seems to be working fine for me on OSX with Chrome 54.0.2840.87, which OS are you using @elvetemedve?

**Comment by elvetemedve** [comment]
@dsander I'm on Arch Linux.

**Comment by cantino** [comment]
I don't think we changed our session storage on the Rails upgrade. Did you try clearing your cookies?

**Comment by elvetemedve** [comment]
I tried to log in with both Firefox and Chrome. In case of Firefox it was successful, but for Chrome I got back the login page. 

I have captured the raw TCP/HTTP stream between the browser and the server.
I noticed from the dumps that the repose to the login **POST** request is a **302 redirect**, but the application _did not send_ the **_rails_session** cookie in case of Chrome. So Chrome will open the redirect location sending back the old session cookie (starting with _SHBC_) which explains why the login page will be shown.

[Firefox_tcp_dump.log.txt](https://github.com/cantino/huginn/files/587974/Firefox_tcp_dump.log.txt)
[GoogleChrome_tcp_dump.log.txt](https://github.com/cantino/huginn/files/587975/GoogleChrome_tcp_dump.log.txt)

**Comment by elvetemedve** [comment]
@cantino **_rails_session** is the only stored cookie, but removing it does not help. (Actually it's removed automatically when I close the browser tab, since it's a session cookie.)

**Comment by cantino** [comment]
I assume you haven't changed cookies_serializer.rb in any way, right?

It looks like you're being redirected away from HTTPS.  Are you setup with HTTPS?  If not, make sure that `FORCE_SSL` is `false` and that there is not `https` in any url in your configuration.

**Comment by elvetemedve** [comment]
Yes, I haven't touched that.

Actually I prefer to use HTTPS. I have Nginx in front of the Huginn application which is configured to redirect all HTTP requests to HTTPS with a 301 permanent redirect.
`FORCE_SSL` is set to `false` now. If I turn it to `true`, then the page redirects in a loop. I'll check Nginx config.

**Comment by elvetemedve** [comment]
When SSL is forced and I have a Nginx config like
```
location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
```
then Nginx terminates the SSL connection and opens a new HTTP connection to Huginn which tries to force SSL by redirecting the page to HTTPS.

If I update Nginx config to proxy requests as HTTPS like
```
location / {
        proxy_pass https://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
```
then I get this error from the Nginx:
`140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol`
That probably means the socket listening on port 3000 can't handle SSL. I would expect another port open for SSL, but only MySQL has an open socket. See below:

> root@b1b67917edc2:/app# netstat -ln
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State      
> tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN     
> tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN     
> Active UNIX domain sockets (only servers)
> Proto RefCnt Flags       Type       State         I-Node   Path
> unix  2      [ ACC ]     STREAM     LISTENING     504929   /var/run/mysqld/mysqld.sock
> unix  2      [ ACC ]     STREAM     LISTENING     503764   /dev/shm/supervisor.sock.1

Best would be to leave `FORCE_SSL` off and the application should use relative URL in redirect header.
Do you have any suggestion?

**Comment by cantino** [comment]
You'll definitely need `proxy_set_header X-Forwarded-Proto $scheme;` too.

**Comment by virtadpt** [comment]
To the best of my knowledge, the Rails server as used by Huginn isn't SSL/TLS capable.  Leave the proxy_pass directive set to http://127.0.0.1:3000/ and make sure that the "web:" directive in huginn/Procfile has 127.0.0.1 in it.  Alternatively, when running the Rails server make sure that '-b 127.0.0.1' is passed to the evocation of bundle.  Let Nginx do the heavy lifting, including TLS termination.

**Comment by elvetemedve** [comment]
It looks like switching between HTTP and HTTPS was the source of the problem.
Using SSL termination in Nginx and adding the `X-Forwarded-Proto` header fixed the session issue.
Thank you guys for your help.

I've created a wiki page for a [sample Nginx config](https://github.com/cantino/huginn/wiki/Nginx-reverse-proxy-configuration) if someone else want to set it up like that.

**Comment by dsander** [comment]
We also have a nginx SSL enabled configuration in the [repository](https://github.com/cantino/huginn/blob/master/deployment/nginx/huginn-ssl). Not sure if all `set_proxy_options` are needed but it has been working well for me for many apps.

**Comment by elvetemedve** [comment]
Hmm. I should have checked that before.
Thanks for pointing it out. I have few things organised into separate config files, like custom error pages or list of allowed ciphers, but there could be other useful options missing from my setup.

**Comment by cantino** [comment]
Is the new wiki page more-or-less the same as the page in the repo?

**Comment by elvetemedve** [comment]
I would say the two are quite different.
I created it specifically for the Docker distribution, while the one in the repo assumes the application is available locally (that's why assets are served from public directory or proxy is connected via unix socket etc.).

**Comment by cantino** [comment]
Makes sense. Would you mind linking to the repo one too?

**Comment by elvetemedve** [comment]
I wanted to suggest the same.
I've updated the wiki page.

**Comment by cantino** [comment]
Thanks!

**Comment by dsander** [comment]
Great, thank you @elvetemedve!
