### ISSUE TITLE
agent description use table format

### ISSUE THREAD

**Issue by tsaohucn** [cantino/huginn#1795]
I want to write agent's description by table format, it should no problem because huginn use kramdown gem. But i can't do it. My format is in the below. What happen?
```
|-----------------+------------+-----------------+----------------|
| Default aligned |Left aligned| Center aligned  | Right aligned  |
|-----------------|:-----------|:---------------:|---------------:|
| First body part |Second cell | Third cell      | fourth cell    |
| Second line     |foo         | **strong**      | baz            |
| Third line      |quux        | baz             | bar            |
|-----------------+------------+-----------------+----------------|
| Second body     |            |                 |                |
| 2 line          |            |                 |                |
|=================+============+=================+================|
| Footer row      |            |                 |                |
|-----------------+------------+-----------------+----------------|
```

**Comment by knu** [comment]
The kramdown gem is locked at 1.3 which is a bit old, but even that version should support the table syntax.  Did you put blank lines around the table?

**Comment by kaogaau** [comment]
I got this view in the huginn, its gird line can't show. lol

<img width="501" alt="2016-11-16 1 42 08" src="https://cloud.githubusercontent.com/assets/6713879/20336067/7a9f4064-ac02-11e6-8712-8f0297f68f89.png">

**Comment by kaogaau** [comment]
I find the reason, the kramdown gem parse the table syntax to pure html tag and have no css, so its show no gird line, I change the syntax and add bootstrap css style in the below, and its work. But that's so weird, because I thought the table tag default has gird line even there's no css style.

\<table class ="table">
...
\</table>

**Comment by cantino** [comment]
It's probably inheriting default Bootstrap CSS.  Do you want to make a PR to change this?

**Comment by kaogaau** [comment]
OK, give me few days, I make a PR to change this^^

**Comment by cantino** [comment]
Hey @tsaohucn, is this still something you want to work on?

**Comment by tsaohucn** [comment]
oh, sorry I am too busy that I forgot this. I make it tonight.

**Comment by tsaohucn** [comment]
Hey @cantino, I have make the PR #1883, thanks^^

**Comment by cantino** [comment]
Thanks!
