### ISSUE TITLE
MySQL Connection leak : "could not obtain a connection from the pool"

### ISSUE THREAD

**Issue by flechaig** [cantino/huginn#1796]
Hi everyone,
There is a connection leak when using two docker containers, one for Huginn and one for its database MySQL. After a few days up, Huginn stops running jobs because it can't get a connection from the database pool.
The error is : 
`all pooled connections were in use`
as shown below.

`job:
|  Rufus::Scheduler::EveryJob "1h" {:tag=>"HuginnScheduler"}
|error:
|  47334774641320
|  ActiveRecord::ConnectionTimeoutError
|  could not obtain a connection from the pool within 5.000 seconds (waited 5.001 seconds); all pooled connections were in use
|    /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:202:in 'block in wait_poll'
|    /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in 'loop'
|    /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in 'wait_poll'
|    /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:154:in 'internal_poll'
|    /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:278:in 'internal_poll'
|    /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in 'block in poll'
|    /usr/lib/ruby/2.3.0/monitor.rb:214:in 'mon_synchronize'
|    /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:158:in 'synchronize'
|    /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:148:in 'poll'
|    /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:709:in 'acquire_connection'
|    /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:501:in 'checkout'
|    /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in 'connection'
|    /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:395:in 'with_connection'
|    /app/lib/huginn_scheduler.rb:191:in 'block in with_mutex'
|    /app/lib/huginn_scheduler.rb:190:in 'synchronize'
|    /app/lib/huginn_scheduler.rb:190:in 'with_mutex'
|    /app/lib/huginn_scheduler.rb:150:in 'run_schedule'
|    /app/lib/huginn_scheduler.rb:121:in 'block (2 levels) in setup'
|    /app/vendor/bundle/ruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:234:in 'do_call'
|    /app/vendor/bundle/ruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:258:in 'do_trigger'
|    /app/vendor/bundle/ruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:300:in 'block (3 levels) in start_work_thread'
|    /app/vendor/bundle/ruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:303:in 'block (2 levels) in start_work_thread'
|    /app/vendor/bundle/ruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:289:in 'loop'
|    /app/vendor/bundle/ruby/2.3.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:289:in 'block in start_work_thread'`

I think some connections are not put back in the pool as they should be, or maybe they are not closed properly.
Can anyone help ?
Thanks a lot

**Comment by cantino** [comment]
What is your pool size set to?

**Comment by dsander** [comment]
I hope we don't have a connection leak, but think that is unlikely as we did not have any issue with it for some time. Like Andrew mentioned our default connection pool size is pretty low, I suggest setting `DATABASE_POOL` to 20 or 30.

@cantino Do you think we should increase the default pool size? I think we hit the connection limit as soon as one uses a couple of twitter stream or longrunnable agents.

**Comment by cantino** [comment]
Yes, I think we should.  I just checked and mine is set to 20.

**Comment by flechaig** [comment]
Mine is at the default value (10 I think).
Do you mean I need more connections as the number of agents grow ?
