### ISSUE TITLE
RSS Agent: 'invalid byte sequence in UTF-8'

### ISSUE THREAD

**Issue by DreamFlasher** [cantino/huginn#1797]
When using the RSS Agent on this feed: http://www.teltarif.de/feed/h/blackberry/20.rss2

I get the following error:
```Failed to fetch http://www.teltarif.de/feed/h/blackberry/20.rss2 with message 'undefined method `entries' for nil:NilClass': ["/app/app/models/agents/rss_agent.rb:143:in `feed_to_events'", ... "/app/lib/delayed_job_worker.rb:6:in `run'", "/app/app/concerns/long_runnable.rb:71:in `block in run!'"]```

Other feeds in the same RSS Agent work smoothly.

**Comment by dsander** [comment]
Can you try to update Huginn to the latest version? I think @knu fixed that error recently.

**Comment by DreamFlasher** [comment]
I updated and now get the following error ```Failed to fetch http://www.teltarif.de/feed/h/blackberry/20.rss2 with message 'invalid byte sequence in UTF-8'```

**Comment by DreamFlasher** [comment]
So this particular RSS feed has problems with the encoding (unfortunately many rss feeds fail on that). When I set `"force_encoding": "UTF-8"` then I get the error `invalid byte sequence in UTF-8`, not setting it or setting it to "force_encoding": "ISO8859-1" yields wrong characters. So the RSS is in UTF-8 but somehow there are problems in it.

**Comment by dsander** [comment]
Are you using a debian based distribution? Try setting `LANG` in `/etc/default/locale` to ensure rubys default encoding is UTF-8.
```
LANG="en_US.UTF-8"
```
Maybe generating the locales is also required:
```
locale-gen en_US.UTF-8
update-locale LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8
```
You then need to open a new shell and restart Huginn.

**Comment by DreamFlasher** [comment]
I'm running it on heroku, LANG is set as you requested. I would expect that heroku has the locales?
I think problems in the rss need to be handled like this: http://stackoverflow.com/a/18454435

**Comment by dsander** [comment]
You are right, when I use `force_encoding` I am getting the same result. It looks like their server is setting the encoding to `ISO8859-1` where as the data is actually encoded in `UTF-8`. I am not sure why our `force_encoding` code is not properly converting the data.

**Comment by dsander** [comment]
I did some more digging but still don't completely understand why we are having this issue.

* The RSS feed is really encoded in `ISO-8859-1` which matches the content-type header
* When I download the feed using wget `file -I` also reports the correct encoding, however displaying the umlauts with `cat` or `less` fails (maybe it does not convert the encoding to UTF-8?!?)
* The german umlauts are encoded properly: `0xFC` for `ü` etc.
* Huginn processes the data correctly when I disable our [custom encoding handling](https://github.com/cantino/huginn/blob/master/app/concerns/web_request_concern.rb#L35-L52)
* Trying to bypass our encoding handling with `force_encoding: ASCII-8BIT` fails with `"\xE4" from ASCII-8BIT to UTF-8'`

@knu Do we need an option to bypass our encoding handling or can we fix it in a different way?

**Comment by knu** [comment]
I made some investigation and now I see what's going on inside of RssAgent.  Feedjira receives a UTF-8 encoded XML document, but its underlying SAX parser ignores the encoding and performs ISO-8859-1 to UTF-8 conversion as soon as it finds the XML declaration with `encoding="ISO-8859-1`.  So, the resulted document is double-decoded from ISO-8859-1.

I'm currently looking for a way to tell the SAX parser to respect the string encoding.

**Comment by knu** [comment]
Looks like you need to pass to libxml2 a parser option called `XML_PARSE_IGNORE_ENC`, but there is currently no way to do that in Nokogiri.  I guess removing the encoding attribute is the best way to achieve what we need.

**Comment by dsander** [comment]
Wow that is some sneaky stuff, nice find!

**Comment by DreamFlasher** [comment]
I updated to the latest version but still get the same error `Failed to fetch http://www.teltarif.de/feed/h/blackberry/20.rss2 with message 'invalid byte sequence in UTF-8'`

**Comment by dsander** [comment]
@DreamFlasher Have you tried it without `force_encoding`? The sites encoding was actually correct, the problem was that we encoded it twice which causes the issues.

**Comment by DreamFlasher** [comment]
Without `force_encoding` it works -- but then I have the problem that in the email digest the encoding is wrong. That's the reason I wanted to have the `force_encoding` in the first place -- I wanted all output to be converted to utf-8 so that it's correctly displayed in the emails.

**Comment by knu** [comment]
You mean it didn't work with `force_encoding`?  It should, just as confirmed in 7ac6916.

If you specified "UTF-8" as the value, then that's why it didn't work.  The RSS is encoded in ISO-8859-1, so you must specify "ISO-8859-1", if you had to.

**Comment by DreamFlasher** [comment]
If I set force_encoding to utf-8, then I get the error. If I set it to iso or don't set it then I get broken umlauts in the email report.

**Comment by dsander** [comment]
Are the umlauts also broken in the Huginn Events? If they look good there it might be an encoding problem in the email.

**Comment by DreamFlasher** [comment]
Tested with a new rss feed from teltarif, and just let it email to me: Works. I can't explain the wrongly encoded email I got, but it looks as it works now. Thank you!
