### ISSUE TITLE
Parse html content from a JSON object

### ISSUE THREAD

**Issue by cyanglee** [cantino/huginn#1799]
Hi, I am new to Huginn and wonder if someone could point me a direction regarding parsing html from a json object.

Here is what I want to achieve:

1. Fetch from a url containing a json object through a WebSite agent (**done**)
2. Select a specific key from the returned json object (**done**)
```
{
  "expected_update_period_in_days": "2",
  "url": "some-url",
  "type": "json",
  "mode": "on_change",
  "extract": {
    "main": {
      "path": "{{ main }}"
    }
  }
}
```
3. The value from the "main" key contains a messy html that looks like:
```
\r\n<div class=\"shList  \" >\r\n    <ul class=\"shInfo\"   >\r\n        <li class=\"info\">\r\n            <div class=\"left\" data-bind=\"4633055\" data-img-length=\"5\">\r\n
```
4. I've created another agent as a receiver that does the following:
```
{
  "expected_update_period_in_days": "2",
  "data_from_event": "{{ main }}",
  "mode": "merge",
  "extract": {
    "title": {
      "xpath": "//p[@class='title']",
      "value": "string(.)"
    }
  }
}
```
There's probably something wrong with the way I do it, so I got nothing from the agent above. 

Any suggestion is appreciated. Thanks!

**Comment by dsander** [comment]
Hi @cyanglee,

the options you are using look correct to me, are you sure the HTML includes the tag and class you are searching for?

**Comment by cyanglee** [comment]
Hi @dsander,

Thanks for the reply. I didn't paste the whole content in my first, but I am confident that the tag and class are there. I wonder if the xpath query is affected by the newline characters (\r\n). Is there any way that I can do some initial content cleaning through either liquid or JsonPath before sending the content to the second website agent? Thanks!

**Comment by dsander** [comment]
I don't think the newlines will cause problems, but you could use a `EventFormattingAgent` with the liquid [`regex_replace`](https://github.com/cantino/huginn/wiki/Formatting-Events-using-Liquid#filters-added-by-huginn) filter to get rid of them.

I used your options of the second website agent and passed it this event in a dry-run, which worked like expected:
```
{
  "main": "<h1>hi</h1><p class=\"title\">Hello</p>"
}
```

Did you try to use an Event of the first WebsiteAgent and pass it in a dry-run of the second?

**Comment by cyanglee** [comment]
Hi @dsander, it turns out that the returned object is actually a json formatted and returned as a html. It's a poor design but I was able to use xpath to filter the values I need after I realized that. Thanks for the help. I will go ahead to close this issue.

**Comment by dsander** [comment]
Nice, glad you figured out a solution :)

**Comment by cantino** [comment]
Are there docs that we should update about this?

**Comment by cyanglee** [comment]
@cantino As someone new to Huginn, during the process of setting up agents, especially website agents, I found the Liquid filters very helpful. If a link to [Formatting Events using Liquid](https://github.com/cantino/huginn/wiki/Formatting-Events-using-Liquid) or some basic examples regarding how to use them could be added to the doc section on the right hand side of the agent, it would be a nice plus.

**Comment by cantino** [comment]
Just the WebsiteAgent, or other ones too?

**Comment by cyanglee** [comment]
@cantino I think for all the agents where the results can be handled by Liquid would be helpful, e.g. json event formatter etc. Thanks!

**Comment by cantino** [comment]
Done in 81f6ee5.
