### ISSUE TITLE
Switching translator to Google

### ISSUE THREAD

**Issue by joenas** [cantino/huginn#1800]
Hey there and thanks for an awesome app! 

I noticed this when trying to use the `TranslatorAgent`: 

> DataMarket and Data Services are being retired and will stop accepting new orders after 12/31/2016. Existing subscriptions will be retired and cancelled starting 3/31/2017. Please reach out to your service provider for options if you want to continue service.

Any plans on switching service, to for example [Google Translate](https://developers.google.com/api-client-library/ruby/start/get_started)? If I find some spare time, I might start implementing it if there's interest. 

Also, the current Agent doesn't work... 😄 

```
no implicit conversion of nil into String
/app/app/models/agents/translation_agent.rb:44:in `+'
/app/app/models/agents/translation_agent.rb:44:in `translate'
```

which seems to be because `access_token` is `nil`.
I was gonna create an issue about that but since it's being retired anyways I figure no point.

**Comment by cantino** [comment]
I don't personally use it, but it'd be nice if it worked. We'd gladly accept a PR to fix it.

**Comment by Maroo-b** [comment]
I'll try to submit a PR to migrate to google Translator.

**Comment by Maroo-b** [comment]
@cantino it seems that google translate is a paid service ( [source](https://cloud.google.com/translate/faq) )

For free services it seems Yandex the most promising, do you suggest another service to integrate ?

**Comment by cantino** [comment]
Probably the best solution would be to support multiple translation backends. Would you be interested in working on that?

**Comment by Maroo-b** [comment]
Absolutely, I suggest that we start by implementing an alternative to the existent solution, it seems that [Microsoft Translator](https://www.microsoft.com/en-us/translator/) is the upgrade for the current implemented solution. (I need to do more checks )
Afterward we can add other backends based on users feedback.

**Comment by joenas** [comment]
I actually have a working implementation of Google Translate, I just haven't gotten around to write specs...

**Comment by cantino** [comment]
It'd be great to get both Google and Microsoft in one Agent. @joenas, maybe you can contribute yours and @Maroo-b can add to it?

**Comment by Maroo-b** [comment]
@cantino that would be interesting I'll wait for @joenas PR.

**Comment by joenas** [comment]
PR submitted!

**Comment by Maroo-b** [comment]
should this issue be closed ?

**Comment by joenas** [comment]
It depends on whether you want to use it for Microsoft/Yandex/whatever too or not I guess?

**Comment by Maroo-b** [comment]
@joenas thank you for the feedback,
I don't use the translator Agent but if there is a need for another translate API I can submit a PR otherwise I'll check other issues :)

**Comment by joenas** [comment]
Then I think we should close and move on :D

**Comment by cantino** [comment]
Agreed! Thanks.
