### ISSUE TITLE
"Creating scope :failed. Overriding existing method"

### ISSUE THREAD

**Issue by cantino** [cantino/huginn#1806]
When starting the docker image, I noticed this error:

```
foreman stdout | Creating scope :failed. Overriding existing method Delayed::Backend::ActiveRecord::Job.failed.
```

It seems like our definition of `scope :failed, -> { where("failed_at IS NOT NULL") }` in initializers/delayed_job.rb is clobbering a DJ built-in method. (Perhaps the `failed` callback?)

I wonder if this was a Rails 5 change?

**Comment by dsander** [comment]
That is odd, I am seeing the same message with both docker images, but can not reproduce it outside of docker (even when running in production). Furthermore there only seems to be an `failed` instance method defined for [Delayed::Backend::Base](https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/backend/base.rb#L59). The [scope](http://api.rubyonrails.org/classes/ActiveRecord/Scoping/Named/ClassMethods.html#method-i-scope) docs claim to also define an instance method, but that is not the case:
```
Delayed::Job.pending.new.pending
NoMethodError: undefined method `pending' for #<Delayed::Backend::ActiveRecord::Job:0x007fd0d0b8ff08>
```
Even though I don't think the warning does effect the functionality we could rename the scope to `failed_jobs`

**Comment by cantino** [comment]
Odd. It also doesn't seem to be breaking anything. Is there any eager_loading / caching difference about how we run in Docker vs outside it?
