### ISSUE TITLE
failed to load command: unicorn

### ISSUE THREAD

**Issue by aqui4tman** [cantino/huginn#1807]
I tried to use the manual install steps on Debian.
I was receiving 502 bad gateway with the following in nginx log:
_connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream_

# cat log/unicorn.log

_I, [2016-11-20T11:45:46.555346 #31387]  INFO -- : Refreshing Gem list
bundler: failed to load command: unicorn (/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/unicorn)
NameError: uninitialized constant Rack::LiveReload
  /home/huginn/huginn/config/environments/development.rb:4:in `block in <top (required)>'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:209:in `instance_eval'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:209:in `configure'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:181:in `configure'
  /home/huginn/huginn/config/environments/development.rb:3:in `<top (required)>'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:599:in `each'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:599:in `block in <class:Engine>'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/local/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:44:in `each'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:44:in `tsort_each_child'
  /usr/local/lib/ruby/2.3.0/tsort.rb:415:in `call'
  /usr/local/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each'
  /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `call'
  /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  /usr/local/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:193:in `public_send'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:193:in `method_missing'
  /home/huginn/huginn/config/environment.rb:5:in `<top (required)>'
  config.ru:4:in `require_relative'
  config.ru:4:in `block in <main>'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `eval'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `block in builder'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:752:in `build_app!'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:129:in `start'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
  /home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'_

# And my Procfile

_web: bundle exec unicorn -c config/unicorn.rb
jobs: bundle exec rails runner bin/threaded.rb_

# my unicorn.rb

_wd = File.expand_path(File.join(File.dirname(__FILE__), '..'))
app_path = wd
worker_processes 2
preload_app true
timeout 180
listen "#{wd}/tmp/sockets/unicorn.socket"
working_directory app_path
rails_env = ENV['RAILS_ENV'] || 'production'
stderr_path "log/unicorn.log"
stdout_path "log/unicorn.log"
pid "#{wd}/tmp/pids/unicorn.pid"
before_fork do |server, worker|
  ActiveRecord::Base.connection.disconnect!
  old_pid = "#{server.config[:pid]}.oldbin"
  if File.exist?(old_pid) && server.pid != old_pid
    begin
      Process.kill("QUIT", File.read(old_pid).to_i)
    rescue Errno::ENOENT, Errno::ESRCH
      # someone else did our job for us
    end
  end
end
after_fork do |server, worker|
  ActiveRecord::Base.establish_connection
end_

### 
Why?
Any pointers are appreciated!

**Comment by dsander** [comment]
Hi @aqui4tman,

did you uncomment the `RAILS_ENV=production` setting in `.env`? If that wasn't the you need to reexport the services with `sudo bundle exec rake production:export` after enabling the setting.

**Comment by aqui4tman** [comment]
I reexport the services with _sudo bundle exec rake production:export_ after enabling the setting.
but ,
_root@xxx:/home/huginn/huginn# sudo bundle exec rake production:export
Stopping huginn ...
ok: down: huginn-web-1: 119s, normally up
rake aborted!
'sv stop huginn-jobs-1' exited with a non-zero return value: timeout: run: huginn-jobs-1: (pid 21166) 184s, want down, got TERM
/home/huginn/huginn/lib/tasks/production.rake:85:in `run'
/home/huginn/huginn/lib/tasks/production.rake:77:in `block (2 levels) in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:93:in `with_retries'
/home/huginn/huginn/lib/tasks/production.rake:76:in `block in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:75:in `each'
/home/huginn/huginn/lib/tasks/production.rake:75:in `run_sv'
/home/huginn/huginn/lib/tasks/production.rake:33:in `block (2 levels) in <top (required)>'
/home/huginn/huginn/lib/tasks/production.rake:57:in `block (2 levels) in <top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => production:export
(See full trace by running task with --trace)_

and,
_root@xxx:/home/huginn/huginn# cat log/jobs-1/current 
bundler: failed to load command: rails (/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/rails)_

**Comment by dsander** [comment]
Maybe Huginn did not start properly, try stopping it multiple times until you do not get an exception with `sudo bundle exec rake production:stop`, and then start it again `sudo bundle exec rake production:start`.

Does you server match the [hardware requirements](https://github.com/cantino/huginn/blob/master/doc/manual/requirements.md#hardware-requirements)?

**Comment by aqui4tman** [comment]
it works!
Thank you!
