### ISSUE TITLE
JSONParseAgent

### ISSUE THREAD

**Issue by bshort** [cantino/huginn#1810]
So I have a working agent that emits this: 

```
{
	"name": "TQQQ",
	"percentage": "+1.68%",
	"price": "125.20"
}
```

I'd like to detect whether the "percentage" field is down by more than 2%. I tried creating a TriggerAgent that looks like:
```
{
  "expected_receive_period_in_days": "2",
  "keep_event": "false",
  "rules": [
    {
      "type": "field<=value",
      "value": "-2",
      "path": "percentage"
    }
  ],
  "message": "Looks like your pattern matched in '{{value}}'!"
}
```

But this doesn't work. I'm guessing it's because of the "%" character. So I created a JSONParseAgent that looks like this to try and  filter it out:

```
{
  "data": "{{ percentage | replace: '%', ''  }}",
  "data_key": "percent"
}
```

I get an error that looks like: 

> Could not parse JSON: JSON::ParserError '784: unexpected token at '+1.68%''

Am I specifying my JSONParseAgent properly? Is there a better way to do this?

Is there a way to filter out the "%" sign in the WebsiteAgent?

Thanks,
-Brian

**Comment by bobbysteel** [comment]
Weird, I tried this w/ your above code and it worked as expected for me even with the % (although you can't use value in your message.

`
[
  {
    "message": "Looks like your pattern matched in ''!"
  }
]
`

**Comment by cantino** [comment]
Should data_key be percentage, not percent?

**Comment by dsander** [comment]
@bobbysteel The JSONParse Agent is used to parsed a JSON string that is fetched from a Website (or a different source), even though Events in Huginn are stored in JSON they are passed to the Agent as an Object. Now that I have written it I totally understand how that can be confusing :)

Try using a EventFormattingAgent instead of the JSONParseAgent and use those options:
```
{
  "instructions": {
    "integer": "{{ percentage | replace: '%', ''  }}"
  },
  "mode": "merge"
}
```

**Comment by dsander** [comment]
I am closing this issue. Please feel free to reopen if you need further assistance!
