### ISSUE TITLE
Unescaping in new Template feature in WebsiteAgent

### ISSUE THREAD

**Issue by bobbysteel** [cantino/huginn#1812]
The templating work that @knu did is awesome. However I'm having an issue passing Arrays through to be parsed as JSON. Without using the template option this works fine. With templates, the Array is quotation mark escaped and nothing I do can seem to make it readable by my next agent, a Javascript agent.
Without using template, just extract:
`
  "last_investors": [
      {
        "id": 1727,
        "name": "Bessemer Venture Partners"
      },
      {
        "id": 2588,
        "name": "Mangrove Capital Partners"
      },
      {
        "id": 30228,
        "name": "Primary Venture Partners"
      },
      {
        "id": 33629,
        "name": "Lerer Hippeau"
      },
      {
        "id": 73867,
        "name": "Comcast Ventures"
      }
    ],
`
With using template and in this case just passing through "last_investors": "{{last_investors | json}}" from the extract:
`
    "last_investors": "[{\"id\":1727,\"name\":\"Bessemer Venture Partners\"},{\"id\":2588,\"name\":\"Mangrove Capital Partners\"},{\"id\":30228,\"name\":\"Primary Venture Partners\"},{\"id\":33629,\"name\":\"Lerer Hippeau\"},{\"id\":73867,\"name\":\"Comcast Ventures\"}]",
`
Any ideas how to fix and just pass straight through (or some undocumented unescape command)? Thanks.

**Comment by knu** [comment]
I guess you could use the `as_object` filter that was added recently.

**Comment by bobbysteel** [comment]
Ah works flawlessly. I had hoped it was something very small like this. Thanks @knu !
