### ISSUE TITLE
Monitoring Github

### ISSUE THREAD

**Issue by mirkathaha** [cantino/huginn#1814]
Hi there,

Is there anyone here that managed to setup agent to find sensitive information lingering in publicly available files on GitHub? Something like [Gitrob](https://github.com/michenriksen/gitrob)?

Thanks!

**Comment by cantino** [comment]
I'm not aware of something like this. Maybe consider Google BigQuery on the [GitHub Data Set](https://cloud.google.com/bigquery/public-data/github)?
