### ISSUE TITLE
(Semi) Auto-Updating Huginn

### ISSUE THREAD

**Issue by JamiePhonic** [cantino/huginn#1815]
Just wondering if anyone has found a way to automatically update huginn, either using a script or through other means?
I attempted to get capistrano working but the wiki entry for it is short and somewhat ambiguous in that im not sure whether i should install capistrano on my local machine and configure it to push TO my huginn server, or whether it should be installed ON the huginn server itself... or both?

for now ive setteled on just bundeling the manual update commands into a bash script to automate most of the process, but it still has to be called manually to do updates.

any thoughts?

**Comment by cantino** [comment]
You'd install Capistrano on your local machine. This is what I use, but many other users (such as @dsander) have moved to Docker.  I don't know if anyone automatically updates, though, as opposed to running a script (Capistrano, Docker, etc.) to do the update.

**Comment by JamiePhonic** [comment]
no not fully automated, i'd still want a command to initiate the update.

i've looked at docker but i dont have the time to learn its subtleties. im currently running huginn in and LXD container just now. the main blocker for docker for me at the moment is figuring out how to configure its networking. currently i have the LXD container bridged to my lan so i can route it through a reverse proxy and also use an external mysql server without any complexities.

i know there's probably a much better way do that and i know that docker containers can be bridged to your lan, i just dont have the time to look up and implement it because im so busy just now...

anyway, ramble over, thanks for clarifying that 👍

**Comment by dsander** [comment]
When using docker-compose updating it pretty easy, `docker-compose pull && docker-compose up -d` does it all 😄 Accessing a public interface of the host from inside the docker container should be no problem, but I am not sure what is required to access private or interface behind the LXC bridge.

**Comment by JamiePhonic** [comment]
might need to clear up some abiguity there...

my setup is thus:
```
Host: Windows server 2016 running Hyper-V
|__Ubuntu 16.4 VM with LXD installed
     |__LXD container running huginn
     |__LXD container running Node-Red
```
the windows server is on my lan directly attached, ubuntu server is also directly attached because of how Hyper-V works (it creates a virtual switch and dedicates a NIC to it, so all VM's also appear direcly attached and will get an IP from my router via DHCP
the LXD containers are then briged through the adaper in ubuntu so they also get an ip address from my router via DHCP.

in the above instance, docker would replace LXD entierly, or at least run alongside it.

to simplify, if i had ubuntu running on physical hardware, then i'd want any docker images to be bridged to eth0 so they appear as hosts on my network.

**Comment by cantino** [comment]
I admit I don't know Docker well either. It'd be nice to see a compose setup that uses best practices like a separate, persistent database. Do we have a good example of a recommended production setup?

**Comment by JamiePhonic** [comment]
i use a seperate database server because i already had it running for other things and setting up a second one just for huginn seemed like a waste of server resources to me.

i'd probably say the for locally hosted production systems, using docker with a seperate database server would be best, but im no security expert so thats essentually just my 2c

**Comment by JamiePhonic** [comment]
Wrote a short script to automate a majority of the update process.
Will investigate using docker at some point in the future.
