### ISSUE TITLE
Create custom schedulles

### ISSUE THREAD

**Issue by vicenteampliffy** [cantino/huginn#1818]
Is there a way to create custom schedulles?
I was looking to launch agents in a more fine-grained schedulle: in slots of quarters of an hour.
I understand I need to change here: https://github.com/cantino/huginn/blob/8a14a57e00716c12d060a036240cbfda789ab010/app/models/agent.rb
The following line:
SCHEDULES = %w[every_1m every_2m every_5m every_10m every_30m every_1h every_2h every_5h every_12h every_1d every_2d every_7d
                 midnight 1am 2am 3am 4am 5am 6am 7am 8am 9am 10am 11am noon 1pm 2pm 3pm 4pm 5pm 6pm 7pm 8pm 9pm 10pm 11pm never]

But I don't know which is the right syntaxis (sorry, I'm not proficient yet with ruby nor the code base)

Also it would be great to specify maybe a day of the week in order to just launch agents on Sundays for example, or on Mondays.

Best,
Vicente

**Comment by dsander** [comment]
Hi @vicenteampliffy,

you can use a `SchedulerAgent` which allows to run Agents based on a cronline, with the [extensions specific to the gem we are using](https://github.com/jmettraux/rufus-scheduler#first-monday-last-sunday-et-al) it is possible to run an Agent on specific days of the week:  `* * * * mon`

**Comment by vicenteampliffy** [comment]
Hi @dsander ,

That's exactly what I needed! Thanks! I'm closing this issue.
