### ISSUE TITLE
Huginn twitter agents

### ISSUE THREAD

**Issue by neethkrish** [cantino/huginn#1820]
Hi,
 I am new to huginn twitter agents .  Can some one please help me in finding out how to create a twitter agent that retrieves tweets that have been tweeted by  a particular user and under a particular hashtag . 

Thanks in advance..

**Comment by virtadpt** [comment]
To follow a a particular account, use the Twitter User Agent.  You'd set it up something like this:
`{
  "username": "ap",
  "include_retweets": "true",
  "expected_update_period_in_days": "7"
}`
You could then feed the output of that agent into a Trigger Agent that monitors for particular words, which would match hashtags as well.  Here's an example of one such agent:
`
{
  "expected_receive_period_in_days": "365",
  "keep_event": "false",
  "rules": [
    {
      "type": "regex",
      "value": [
        "occupy",
        "North Korea",
        "cyber"
      ],
      "path": "$.text"
    }
  ],
  "message": "@ap tweeted an article at {{created_at}} {{time_zone}} referencing {{value}}: {{text}}"
}`
You can then do whatever you want with the output events from the Trigger Agent, like e-mail them to yourself, or post them to your own Twitter account, or something like that.

**Comment by virtadpt** [comment]
If you want to check out some more complex agent networks, check this out: https://github.com/virtadpt/exocortex-agents

**Comment by neethkrish** [comment]
Thanks @virtadpt . This was exactly what i was looking for . Thanks a lot for the reply .

Could you please tell me what does the parameter  "expected_update_period_in_days" actually means . I read the descriptions but  did not get a clear idea about the same . 
 
Thanks.

**Comment by cantino** [comment]
It tells Huginn how often you think this Agent will receive an event or do some work. If more time passes than this, the Agent will show up in your list as "not working" so that you can investigate if something is wrong. It's just for your convenience.

**Comment by neethkrish** [comment]
Alright.. Thanks a lot :-)

**Comment by neethkrish** [comment]
Just one more clarification to be made, so is it like we can give any larger values for it..like may be a 400 or even larger..

Thanks.

**Comment by virtadpt** [comment]
I usually give expected_update_period_in_days a much larger value, like 3650.  Ten years doesn't seem to impact it adversely.

**Comment by cantino** [comment]
Then it'll just never reported as not "working". Up to you

**Comment by neethkrish** [comment]
Thanks..

**Comment by atomobianco** [comment]
Hi @virtadpt thanks your comments helped me as well. 
How did you get that that info? By reading some similar example (can you point me there?) or by looking at the code of Trigger agent?
