### ISSUE TITLE
br tag changed into carriage return

### ISSUE THREAD

**Issue by luismanson** [cantino/huginn#1821]
Hello, im using the website agent to fetch a site and get a mail with changes, which come with carriage returns in it ( **\n\n** ). Upon further inspection the issue comes from the website agent. since the source HTML has BR tags and the logs show \n

i extract the code with:
```
  "content": {
      "xpath": "//ul[contains(@class, 'accordion')][*]/li[contains(@class, 'accordion-navigation')][*]/div[contains(@id, 'show')]/p[contains(@class, 'chlog-p')]",
      "value": "string(.)"
    }```

**Comment by dsander** [comment]
Hi @luismanson,

I think the spring `string` function replaces tags with line breaks, `./node()` will return the raw inner HTML.

**Comment by luismanson** [comment]
thanks @dsander that did it!
