### ISSUE TITLE
The line wrap symbole \n become \\n

### ISSUE THREAD

**Issue by kaogaau** [cantino/huginn#1822]
I enter the string \n in the agent's option input box, but when I checkout to Toggle View, I find it
actually enter the "\\n", it cause some error for line, wechat...etc message application's agent, it's a bug or it's correct behavior that we decide to change the encode?

**Comment by cantino** [comment]
Hey @kaogaau, try using `{{ line_break }}`. (See https://github.com/cantino/huginn/wiki/Formatting-Events-using-Liquid#tags-added-by-huginn)

**Comment by kaogaau** [comment]
That's right, thanks for your help
