### ISSUE TITLE
Missing CSS styles - Please help a novice!

### ISSUE THREAD

**Issue by LeonLuchs** [cantino/huginn#1823]
Hello,
I've successfully installed Huginn on Ubuntu Server 14.04.5 on Odroid XU4 following the installation guide but no css is loading. I already checked previous solved and similar problems but didn't find a solution. Do you have one? Thank you!

production.log shows no error message

huginn_error.log shows only "old" errors / no error messages in new logins / javascript and stylesheets folder doesn't exist:

> 2016/12/04 16:08:20 [error] 1622#0: *109 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "192.168.178.27"
2016/12/04 16:08:21 [error] 1622#0: *109 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "192.168.178.27"
2016/12/04 16:08:21 [error] 1622#0: *109 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "192.168.178.27"
2016/12/04 16:08:22 [error] 1622#0: *109 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "192.168.178.27"
2016/12/04 16:08:22 [error] 1622#0: *109 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "192.168.178.27"
2016/12/04 16:08:23 [error] 1622#0: *109 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "192.168.178.27"
2016/12/04 16:08:23 [error] 1622#0: *109 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "192.168.178.27"
2016/12/04 16:08:27 [error] 1622#0: *109 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "192.168.178.27"
2016/12/04 16:08:27 [error] 1622#0: *109 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "192.168.178.27"
2016/12/04 16:08:28 [error] 1622#0: *109 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "192.168.178.27"
2016/12/04 16:08:28 [error] 1622#0: *109 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "192.168.178.27"
2016/12/04 16:08:30 [error] 1622#0: *109 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "192.168.178.27"
2016/12/04 16:08:30 [error] 1622#0: *109 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "192.168.178.27"
2016/12/04 16:09:28 [error] 979#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "192.168.178.27"
2016/12/04 16:09:28 [error] 979#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "192.168.178.27"
2016/12/04 16:09:29 [error] 979#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "192.168.178.27"
2016/12/04 16:09:29 [error] 979#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "192.168.178.27"
2016/12/04 16:09:29 [error] 979#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "192.168.178.27"
2016/12/04 16:09:29 [error] 979#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "192.168.178.27"
2016/12/04 16:32:54 [error] 974#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "192.168.178.27"
2016/12/04 16:32:54 [error] 974#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "192.168.178.27"
2016/12/04 16:32:55 [error] 974#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "192.168.178.27"
2016/12/04 16:32:55 [error] 974#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "192.168.178.27"
2016/12/04 16:32:56 [error] 974#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "192.168.178.27"
2016/12/04 16:32:56 [error] 974#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "192.168.178.27"
2016/12/04 16:32:56 [error] 974#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "192.168.178.27"
2016/12/04 16:32:56 [error] 974#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "192.168.178.27"
2016/12/04 16:57:45 [error] 1535#0: *77 open() "/home/huginn/huginn/public/stylesheets/application.css" failed (2: No such file or directory), client: 192.168.178.25, server: _, request: "GET /stylesheets/application.css HTTP/1.1", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/04 16:57:45 [error] 1535#0: *79 open() "/home/huginn/huginn/public/javascripts/application.js" failed (2: No such file or directory), client: 192.168.178.25, server: _, request: "GET /javascripts/application.js HTTP/1.1", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/04 16:57:46 [error] 1535#0: *77 open() "/home/huginn/huginn/public/stylesheets/application.css" failed (2: No such file or directory), client: 192.168.178.25, server: _, request: "GET /stylesheets/application.css HTTP/1.1", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/04 16:57:46 [error] 1535#0: *79 open() "/home/huginn/huginn/public/javascripts/application.js" failed (2: No such file or directory), client: 192.168.178.25, server: _, request: "GET /javascripts/application.js HTTP/1.1", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/04 16:57:52 [error] 1535#0: *77 open() "/home/huginn/huginn/public/stylesheets/application.css" failed (2: No such file or directory), client: 192.168.178.25, server: _, request: "GET /stylesheets/application.css HTTP/1.1", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/04 16:57:52 [error] 1535#0: *79 open() "/home/huginn/huginn/public/javascripts/application.js" failed (2: No such file or directory), client: 192.168.178.25, server: _, request: "GET /javascripts/application.js HTTP/1.1", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/04 16:57:54 [error] 1535#0: *77 open() "/home/huginn/huginn/public/stylesheets/application.css" failed (2: No such file or directory), client: 192.168.178.25, server: _, request: "GET /stylesheets/application.css HTTP/1.1", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/04 16:57:54 [error] 1535#0: *79 open() "/home/huginn/huginn/public/javascripts/application.js" failed (2: No such file or directory), client: 192.168.178.25, server: _, request: "GET /javascripts/application.js HTTP/1.1", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/04 16:57:55 [error] 1535#0: *77 open() "/home/huginn/huginn/public/stylesheets/application.css" failed (2: No such file or directory), client: 192.168.178.25, server: _, request: "GET /stylesheets/application.css HTTP/1.1", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/04 16:57:55 [error] 1535#0: *79 open() "/home/huginn/huginn/public/javascripts/application.js" failed (2: No such file or directory), client: 192.168.178.25, server: _, request: "GET /javascripts/application.js HTTP/1.1", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/04 16:57:55 [error] 1535#0: *77 open() "/home/huginn/huginn/public/stylesheets/application.css" failed (2: No such file or directory), client: 192.168.178.25, server: _, request: "GET /stylesheets/application.css HTTP/1.1", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/04 16:57:55 [error] 1535#0: *79 open() "/home/huginn/huginn/public/javascripts/application.js" failed (2: No such file or directory), client: 192.168.178.25, server: _, request: "GET /javascripts/application.js HTTP/1.1", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/04 16:57:56 [error] 1535#0: *77 open() "/home/huginn/huginn/public/stylesheets/application.css" failed (2: No such file or directory), client: 192.168.178.25, server: _, request: "GET /stylesheets/application.css HTTP/1.1", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/04 16:57:56 [error] 1535#0: *77 open() "/home/huginn/huginn/public/javascripts/application.js" failed (2: No such file or directory), client: 192.168.178.25, server: _, request: "GET /javascripts/application.js HTTP/1.1", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/04 17:00:03 [error] 1547#0: *94 open() "/home/huginn/huginn/public/stylesheets/application.css" failed (2: No such file or directory), client: 192.168.178.25, server: _, request: "GET /stylesheets/application.css HTTP/1.1", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/04 17:00:03 [error] 1547#0: *96 open() "/home/huginn/huginn/public/javascripts/application.js" failed (2: No such file or directory), client: 192.168.178.25, server: _, request: "GET /javascripts/application.js HTTP/1.1", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/11 14:46:07 [error] 983#0: *29 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET /images/odin.jpg HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/images/odin.jpg", host: "192.168.178.27", referrer: "http://192.168.178.27/"
2016/12/11 14:46:07 [error] 983#0: *29 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (111: Connection refused) while connecting to upstream, client: 192.168.178.25, server: _, request: "GET /images/odin.jpg HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "192.168.178.27", referrer: "http://192.168.178.27/"

unicorn.log:
> I, [2016-12-11T06:17:26.767098 #854]  INFO -- : unlinking existing >socket=/home/huginn/huginn/tmp/sockets/unicorn.socket
>I, [2016-12-11T06:17:26.768053 #854]  INFO -- : listening on >addr=/home/huginn/huginn/tmp/sockets/unicorn.socket fd=10
>I, [2016-12-11T06:17:26.804459 #854]  INFO -- : master process ready
>I, [2016-12-11T06:17:26.805185 #1259]  INFO -- : worker=0 ready
>I, [2016-12-11T06:17:26.815160 #1262]  INFO -- : worker=1 ready
>192.168.178.25 - - [11/Dec/2016:06:19:47 -0800] "GET / HTTP/1.0" 200 - 0.3206
>192.168.178.25 - - [11/Dec/2016:06:19:47 -0800] "GET /404 HTTP/1.0" 404 728 0.0117
>192.168.178.25 - - [11/Dec/2016:06:19:47 -0800] "GET /404 HTTP/1.0" 404 728 0.1299
>192.168.178.25 - - [11/Dec/2016:06:19:47 -0800] "GET /404 HTTP/1.0" 404 728 0.0075
>::1 - - [11/Dec/2016:06:35:36 -0800] "GET / HTTP/1.0" 200 - 0.2105
>192.168.178.27 - - [11/Dec/2016:06:36:16 -0800] "GET / HTTP/1.0" 200 - 0.0705
>I, [2016-12-11T06:36:55.309063 #854]  INFO -- : reaped #<Process::Status: pid 1259 exit 0> >worker=0
>I, [2016-12-11T06:36:55.309555 #854]  INFO -- : reaped #<Process::Status: pid 1262 exit 0> >worker=1
>I, [2016-12-11T06:36:55.309843 #854]  INFO -- : master complete
>I, [2016-12-11T14:37:28.134655 #846]  INFO -- : Refreshing Gem list
>I, [2016-12-11T06:37:44.013404 #846]  INFO -- : unlinking existing >socket=/home/huginn/huginn/tmp/sockets/unicorn.socket
>I, [2016-12-11T06:37:44.014387 #846]  INFO -- : listening on addr=/home/huginn/huginn/tmp/sockets/unicorn.socket fd=10
I, [2016-12-11T06:37:44.050347 #846]  INFO -- : master process ready
I, [2016-12-11T06:37:44.051583 #1256]  INFO -- : worker=0 ready
I, [2016-12-11T06:37:44.058420 #1259]  INFO -- : worker=1 ready
192.168.178.25 - - [11/Dec/2016:06:38:03 -0800] "GET / HTTP/1.0" 200 - 0.2337
192.168.178.25 - - [11/Dec/2016:06:38:04 -0800] "GET /404 HTTP/1.0" 404 728 0.0134
192.168.178.25 - - [11/Dec/2016:06:38:04 -0800] "GET /404 HTTP/1.0" 404 728 0.1027
192.168.178.25 - - [11/Dec/2016:06:38:04 -0800] "GET /404 HTTP/1.0" 404 728 0.0061
192.168.178.25 - - [11/Dec/2016:06:38:06 -0800] "GET / HTTP/1.0" 200 - 0.1550
192.168.178.25 - - [11/Dec/2016:06:38:06 -0800] "GET /404 HTTP/1.0" 404 728 0.0052
192.168.178.25 - - [11/Dec/2016:06:38:06 -0800] "GET /404 HTTP/1.0" 404 728 0.0111
192.168.178.25 - - [11/Dec/2016:06:38:06 -0800] "GET /404 HTTP/1.0" 404 728 0.0053
192.168.178.25 - - [11/Dec/2016:06:38:07 -0800] "GET / HTTP/1.0" 200 - 0.0260
192.168.178.25 - - [11/Dec/2016:06:38:07 -0800] "GET /404 HTTP/1.0" 404 728 0.0106
192.168.178.25 - - [11/Dec/2016:06:38:07 -0800] "GET /404 HTTP/1.0" 404 728 0.0112
192.168.178.25 - - [11/Dec/2016:06:38:07 -0800] "GET /404 HTTP/1.0" 404 728 0.0106
192.168.178.25 - - [11/Dec/2016:06:38:07 -0800] "GET / HTTP/1.0" 200 - 0.0292
192.168.178.25 - - [11/Dec/2016:06:38:07 -0800] "GET /404 HTTP/1.0" 404 728 0.0109
192.168.178.25 - - [11/Dec/2016:06:38:07 -0800] "GET /404 HTTP/1.0" 404 728 0.0101
192.168.178.25 - - [11/Dec/2016:06:38:07 -0800] "GET /404 HTTP/1.0" 404 728 0.0096
192.168.178.25 - - [11/Dec/2016:06:38:07 -0800] "GET / HTTP/1.0" 200 - 0.0298
192.168.178.25 - - [11/Dec/2016:06:38:07 -0800] "GET /404 HTTP/1.0" 404 728 0.0097
192.168.178.25 - - [11/Dec/2016:06:38:07 -0800] "GET /404 HTTP/1.0" 404 728 0.0098
192.168.178.25 - - [11/Dec/2016:06:38:07 -0800] "GET /404 HTTP/1.0" 404 728 0.0102
192.168.178.25 - - [11/Dec/2016:06:38:07 -0800] "GET / HTTP/1.0" 200 - 0.0246
192.168.178.25 - - [11/Dec/2016:06:38:07 -0800] "GET /404 HTTP/1.0" 404 728 0.0097
192.168.178.25 - - [11/Dec/2016:06:38:07 -0800] "GET /404 HTTP/1.0" 404 728 0.0108
192.168.178.25 - - [11/Dec/2016:06:38:07 -0800] "GET /404 HTTP/1.0" 404 728 0.0098
::1 - - [11/Dec/2016:06:38:17 -0800] "GET / HTTP/1.0" 200 - 0.0955
I, [2016-12-11T06:40:35.359306 #846]  INFO -- : reaped #<Process::Status: pid 1256 exit 0> worker=0
I, [2016-12-11T06:40:35.360073 #846]  INFO -- : reaped #<Process::Status: pid 1259 exit 0> worker=1
I, [2016-12-11T06:40:35.360521 #846]  INFO -- : master complete
I, [2016-12-11T14:45:59.898997 #1818]  INFO -- : Refreshing Gem list
I, [2016-12-11T06:46:15.216072 #1818]  INFO -- : unlinking existing socket=/home/huginn/huginn/tmp/sockets/unicorn.socket
I, [2016-12-11T06:46:15.216913 #1818]  INFO -- : listening on addr=/home/huginn/huginn/tmp/sockets/unicorn.socket fd=10
I, [2016-12-11T06:46:15.262614 #1818]  INFO -- : master process ready
I, [2016-12-11T06:46:15.264497 #1868]  INFO -- : worker=0 ready
I, [2016-12-11T06:46:15.272777 #1871]  INFO -- : worker=1 ready
192.168.178.25 - - [11/Dec/2016:06:46:21 -0800] "GET / HTTP/1.0" 200 - 0.2417
192.168.178.25 - - [11/Dec/2016:06:46:21 -0800] "GET /404 HTTP/1.0" 404 728 0.0442
192.168.178.25 - - [11/Dec/2016:06:46:21 -0800] "GET /404 HTTP/1.0" 404 728 0.1427
192.168.178.25 - - [11/Dec/2016:06:46:21 -0800] "GET /404 HTTP/1.0" 404 728 0.0074
I, [2016-12-11T06:51:26.787318 #1818]  INFO -- : reaped #<Process::Status: pid 1868 exit 0> worker=0
I, [2016-12-11T06:51:26.787712 #1818]  INFO -- : reaped #<Process::Status: pid 1871 exit 0> worker=1
I, [2016-12-11T06:51:26.787978 #1818]  INFO -- : master complete
I, [2016-12-11T14:51:57.852015 #846]  INFO -- : Refreshing Gem list
I, [2016-12-11T06:52:14.618950 #846]  INFO -- : unlinking existing socket=/home/huginn/huginn/tmp/sockets/unicorn.socket
I, [2016-12-11T06:52:14.619932 #846]  INFO -- : listening on addr=/home/huginn/huginn/tmp/sockets/unicorn.socket fd=10
I, [2016-12-11T06:52:14.656339 #846]  INFO -- : master process ready
I, [2016-12-11T06:52:14.657304 #1252]  INFO -- : worker=0 ready
I, [2016-12-11T06:52:14.664298 #1255]  INFO -- : worker=1 ready
192.168.178.25 - - [11/Dec/2016:06:52:57 -0800] "GET / HTTP/1.0" 200 - 0.2668
192.168.178.25 - - [11/Dec/2016:06:52:57 -0800] "GET /404 HTTP/1.0" 404 728 0.0107
192.168.178.25 - - [11/Dec/2016:06:52:57 -0800] "GET /404 HTTP/1.0" 404 728 0.1553
192.168.178.25 - - [11/Dec/2016:06:52:57 -0800] "GET /404 HTTP/1.0" 404 728 0.0106

*.env:
>APP_SECRET_TOKEN=....
>DOMAIN=localhost:80
>PORT=80

>DATABASE_ADAPTER=mysql2
>DATABASE_ENCODING=utf8mb4
>DATABASE_RECONNECT=true
>DATABASE_NAME=huginn_production
>DATABASE_POOL=20
>DATABASE_USERNAME=huginn
>DATABASE_PASSWORD="...."

>RAILS_ENV=production

>FORCE_SSL=false

>INVITATION_CODE=try-huginn

>SKIP_INVITATION_CODE=false

>REQUIRE_CONFIRMED_EMAIL=false

>ALLOW_UNCONFIRMED_ACCESS_FOR=2.days

>CONFIRM_WITHIN=3.days

>MIN_PASSWORD_LENGTH=8

>RESET_PASSWORD_WITHIN=6.hours
>MAX_FAILED_LOGIN_ATTEMPTS login attempts. Set to 'none' to allow unlimited failed login attempts.
>LOCK_STRATEGY=failed_attempts

>MAX_FAILED_LOGIN_ATTEMPTS=10

>UNLOCK_STRATEGY=both

>LOCK_STRATEGY is 'failed_attempts'
>UNLOCK_AFTER=1.hour

>REMEMBER_FOR=4.weeks

>IMPORT_DEFAULT_SCENARIO_FOR_ALL_USERS=true

>AGENT_LOG_LENGTH=200
>FARADAY_HTTP_BACKEND=typhoeus

>DEFAULT_HTTP_USER_AGENT="Huginn - https://github.com/cantino/huginn"

>ALLOW_JSONPATH_EVAL=false

>ENABLE_INSECURE_AGENTS=false

>ENABLE_SECOND_PRECISION_SCHEDULE=false

>SCHEDULER_FREQUENCY=0.3

>EVENT_EXPIRATION_CHECK=6h

>TIMEZONE="Pacific Time (US & Canada)"

>FAILED_JOBS_TO_KEEP=100

>DELAYED_JOB_MAX_RUNTIME=2

>DELAYED_JOB_SLEEP_DELAY=10

Procfile:
>#PRODUCTION
>web: bundle exec unicorn -c config/unicorn.rb
>jobs: bundle exec rails runner bin/threaded.rb

/etc/nginx/sites-enabled/huginn:
> ## Huginn
>upstream huginn {
>  server unix:/home/huginn/huginn/tmp/sockets/unicorn.socket fail_timeout=0;
>}

>server {
> listen 80 default; #default_server;
>  listen [::]:80 ipv6only=on; ## default_server;
>  server_name _; ##YOUR_SERVER_FQDN;  ## Replace this with something like huginn.example.com
>  server_tokens off; ## Don't show the nginx version number, a security best practice
>  root /home/huginn/huginn/public;

 > client_max_body_size 20m;

>  access_log  /var/log/nginx/huginn_access.log;
>  error_log   /var/log/nginx/huginn_error.log;

 > location / {
  >  try_files $uri $uri/index.html $uri.html @huginn;
>     }

>  location @huginn {
 >   proxy_read_timeout      300;
  >  proxy_connect_timeout   300;
  >  proxy_redirect          off;

>    proxy_set_header    Host                $http_host;
  >  proxy_set_header    X-Real-IP           $remote_addr;
   > proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
   > proxy_set_header    X-Forwarded-Proto   $scheme;
  >  proxy_set_header    X-Frame-Options     SAMEORIGIN;

>    proxy_pass http://huginn;
 > }

  > location ~ ^/(assets)/ {
  >  root /home/huginn/huginn/public;
  >  gzip_static on; # to serve pre-gzipped version
  >  expires max;
  >  add_header Cache-Control public;
>  }

>  error_page 502 /502.html;
>}

**Comment by dsander** [comment]
Hi @LeonLuchs,

it looks like the application is not running in the production envrionment, please check your `.env` file and make sure there is no leading space in the `RAILS_ENV=production` line. If you made a change you need to re-export the configuration with `sudo bundle exec rake production:export`.

**Comment by LeonLuchs** [comment]
Hi @dsander,

Thank you. I've checked the .env file (no leading space, everything seems to be fine) and re-exported it but unfortunately it didn't work. So I did a reinstall of the system to check if something went wrong during installation. No warning or error. But the missing css still remains. What else can I do to fix the problem?

**Comment by dsander** [comment]
That is odd, do you still get the same error messages in the nginx `huginn_error.log` as before?
I assume the asset precompilation (`sudo -u huginn -H bundle exec rake assets:precompile RAILS_ENV=production`) ran without errors?

**Comment by LeonLuchs** [comment]
Hi @dsander,

`huginn_error.log` shows no error. But there is an error message in the asset precompilation: `/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/therubyracer-0.12.2/lib/v8/function.rb:13: [BUG] Segmentation fault at 0x22be30
ruby 2.3.1p112 (2016-04-26 revision 54768) [armv7l-linux-eabihf]`. Does it mean that the error appeared during the ruby-installation? And how to solve this problem?

**Comment by dsander** [comment]
It's either a bug in the `therubyracer` gem or (more likely) in libv8 on this system. You can try to force rails to use nodejs for the asset precompilation: `sudo -u huginn -H bundle exec rake assets:precompile RAILS_ENV=production EXECJS_RUNTIME=Node`

**Comment by LeonLuchs** [comment]
Thank you, @dsander! It works after reboot.
