### ISSUE TITLE
Insert data from payload into post url

### ISSUE THREAD

**Issue by Ubun1** [cantino/huginn#1824]
hi! is it possible to insert data from payload into url in post agent?
I have a webhook agent, wich is resieve event from gitlab, this event has something like this in its payload:
```json
{
  "object_kind": "merge_request",
  "user": {
    "name": "Administrator",
    "...":"..."
  },
  "object_attributes": {
    "id": 99,
    "...":"..."
  }
}
```
and then i want to send post request via post agent to url:
 .../branches?branch_name=`object_attributes.id`&ref=master

How can i insert data from json payload into post request?

**Comment by dsander** [comment]
Hi @Ubun1,

if you are sending the event of the WebhookAgent to your PostAgent you can access the data using liquid: `branches?branch_name={{object_attributes.id}}&ref=master`
