### ISSUE TITLE
Generate Github Pages

### ISSUE THREAD

**Issue by NonaSuomy** [cantino/huginn#1826]
I would like to generate GitHub Pages (Jekyll Markdown) to "_posts" folder from random social services (twitter, meetup, facebook, etc) APIs. The only way I could think of doesn't seem very good in my head, which would be to

Grab the social service JSON API with Website Agent => Liquid Agent the markdown => Local File Agent to a local git folder => Shell Command Agent to a git commit.

**Edit:** This has been changed to Grab the social service JSON API with Website Agent => Liquid Agent the markdown => Shell Command Agent Curl Liquid agent to a local git folder, send file with a git commit. (Still not ideal.)

Is there any way to do this without dumping to local storage?

If not, can you help me understand, how to get the process working below (Seems I have the first and fourth step working just not 2 & 3 not sure how to trigger 4 yet?

**Edit:** This is working now, via [267889618](https://github.com/cantino/huginn/issues/1826#issuecomment-267889618) removed 3rd step and replaced it with a curl in Shell Command Agent.

First Step, Website Agent (Working) (would have to fill in your own <SIGID> & <SIG> or use other data:

https://secure.meetup.com/meetup_api/console/?path=/:urlname/events

```
MeetUpAPI Details

Type: Website Agent
Schedule: Every 12h
Last checked: 37m ago
Keep events: Forever
Last event created: 37m ago
Last received event: never
Events created: 2
Event sources: None
Propagate immediately: No
Event receivers: JekyllFormatting, MarkdownDump, GitCommit, and JekyllFormatting2
Working: Yes
Options:
{
  "expected_update_period_in_days": 2,
  "url": "https://api.meetup.com/<YOURMEETUP>/events?photo-host=public&page=1&sig_id=<SIGID>&fields=plain_text_description&sig=<SIG>",
  "type": "json",
  "mode": "on_change",
  "extract": {
    "Name": {
      "path": "$.[0].name"
    },
    "Description": {
      "path": "$.[0].plain_text_description"
    },
    "Link": {
      "path": "$.[0].link"
    },
    "Time": {
      "path": "$.[0].time"
    },
    "Created": {
      "path": "$.[0].created"
    },
    "Location": {
      "path": "$.[0].venue.name"
    }
  }
}
```
Second Step, Liquid Agent (not working (or I don't understand how to use it)... doesn't grab any values from website agent):

But it shows data in the lower right box:

```
Agents::WebsiteAgent

Events will have the following fields:

{
  "Name": "...",
  "Description": "...",
  "Link": "...",
  "Created": "...",
  "Time": "...",
  "Location": "..."
}
```

So I assume it can see the data it just doesn't use it for some reason.

```
JekyllFormatting Details

Type: Liquid Output Agent
Last received event: never
Event sources: MeetUpAPI
Propagate immediately: No
Working: No
Options:
{
  "secret": "jekyllformatting",
  "expected_receive_period_in_days": "2",
  "content": "---\r\nlayout: post\r\ntitle: {{Name}}\r\n---\r\n\r\nLocation: {{Location}} @ {{Time}}\r\n\r\ntext/x-markdown\r\n\r\n{{Description}}\r\n\r\n{{Link}}\r\n\r\nContact us if you have a skill you would like to demo.\r\n\r\n{% raw %}\r\n![_config.yml]({{ site.baseurl }}/images/jekyll-logo.png)\r\n{% endraw %}",
  "mime_type": "text/x-markdown",
  "mode": "Last event in",
  "event_limit": ""
}
```

Output

```
---
layout: post
title: !
---
 
Location:
Date: Wed Dec 31 19:00:00 1969
 
 
 
 
Contact us if you have a skill you would like to demo.
 
 
![_config.yml]({{ site.baseurl }}/images/jekyll-logo.png)
```

Third Step, File Output Agent:

Warning: This type of Agent can read and write any file the user that runs the Huginn server has access to and is currently enabled. Only enable this Agent if you trust everyone using your Huginn installation. You can enable this Agent in your .env file by setting ENABLE_INSECURE_AGENTS to true.

This doesn't seem to output any files (not really sure how it works).

```
MarkdownDump Details

Type: Local File Agent
Schedule: Every 1h
Last checked: ~1h ago
Keep events: Forever
Last event created: never
Last received event: never
Events created: 0
Event sources: MeetUpAPI
Propagate immediately: No
Event receivers: None
Working: No
Options:
{
  "mode": "write",
  "watch": "false",
  "path": "/home/<username>/website/<websitename>.github.io/_posts/test.md",
  "append_radio": "true",
  "append": "true",
  "data": "'---'$'\\nlayout: post'$'\\ntitle: {{Name}}!'$'\\n---'$'\\n'$'\\nLocation: {{Location}}'$'\\nDate: {{ Time |divided_by: 1000 |date: \"%c\" }}'$'\\n{{Description}}'$'\\n'$'\\n{{Link}}'$'\\n'$'\\nContact us if you have a skill you would like to demo.'$'\\n'$'\\n{% raw %}'$'\\n![_config.yml]({{ site.baseurl }}/images/jekyll-logo.png)'$'\\n{% endraw %}'"
}
```

Fourth Step, Shell Command Agent (Seems like it's working):

```
Agents::WebsiteAgent

Events will have the following fields:

{
  "Name": "...",
  "Description": "...",
  "Link": "...",
  "Created": "...",
  "Time": "...",
  "Location": "..."
}
```

```
GitCommit Details

Type: Shell Command Agent
Schedule: Never
Last checked: 8m ago
Keep events: Forever
Last event created: 8m ago
Last received event: 16m ago
Events created: 2
Event sources: MeetUpAPI
Propagate immediately: No
Event receivers: None
Working: Yes
Options:
{
  "path": "/home/<username>/website/<websitename>.github.io/_posts/",
  "command": "echo '---'$'\\nlayout: post'$'\\ntitle: {{Name}}!'$'\\n---'$'\\n'$'\\nLocation: {{Location}}'$'\\nDate: {{ Time |divided_by: 1000 |date: \"%c\" }}'$'\\n{{Description}}'$'\\n'$'\\n{{Link}}'$'\\n'$'\\nContact us if you have a skill you would like to demo.'$'\\n'$'\\n{% raw %}'$'\\n![_config.yml]({{ site.baseurl }}/images/jekyll-logo.png)'$'\\n{% endraw %}' > {{ Created |divided_by: 1000 |date: \"%Y-%m-%d\" }}-Meetup.md && git add . && git commit -m 'Update Feed' && git push origin master",
  "suppress_on_failure": false,
  "suppress_on_empty_output": false,
  "expected_update_period_in_days": 1
}
```
This echo is working when I manually select the data in the dry run box, I get a properly formated file with the data in it, but not sure how you get it to select the data in the normal run. It just dumps a formatted text file with no data: 1969-12-31-Meetup.md . The reason this is not working could be the reason why the Liquid Agent Doesn't work either. I must be missing something.

**Edit:** This seems to work fine when you run the prior Website Agent, grabs the right date on the file but not when you manually run the Shell Agent, it gets the date above, yet the file contents are correct.

**Comment by cantino** [comment]
Are events being created by the WebsiteAgent and they look correct when you view them?

**Comment by NonaSuomy** [comment]
```
Your Events
Source	Created	Payload	
GitCommit	~17h ago	{"command":"echo '---'$'\\nlayout: post'$'\\ntitle: !'$'\\n---'$'\\n'$'\\nLocation: '$'\\n	ShowRe-emitDelete
GitCommit	~17h ago	{"command":"echo '---'$'\\nlayout: post'$'\\ntitle: All about Mini_sumo Robots!'$'\\n---'$	ShowRe-emitDelete
MeetUpAPI	~17h ago	{"Name":"All about Mini_sumo Robots","Description":"All About Mini-sumo Robots\n\nWe're go	ShowRe-emitDelete
MeetUpAPI	~21h ago	{"Name":"All about Mini_sumo Robots","Description":"All About Mini-sumo Robots\n\nWe're go	ShowRe-emitDelete
```
MeetUpAPI is website agent I see the data there, the GitCommit first one was the dry run I'm guessing and then the one with no data was the regular forced run.

**Comment by NonaSuomy** [comment]
I had to do this in the Liquid Agent 

```Date: {% raw %}{{ {% endraw %}{{Time}} {% raw %}| divided_by: 1000 | date: "%c" }}{% endraw %}```

Which then Jekyll formats the Epoch time it got from Huginn. Which still doesn't help for the file naming, not sure what to attempt for a hack around with that to work, because RUN is not working  for me or I don't understand how to use it properly.

**Comment by LondonMakersCommunity** [comment]
Here is a scenario export, just to note you can't use liquid credential tags in path :(

 "path": "/home/{% credential luser %}/website/{% credential grepo %}.github.io/_tests/",

(It doesn't actually let you save that, I just manual modified it to that after exporting the scenario.)

```
{
  "schema_version": 1,
  "name": "MeetUps",
  "description": "Grabs content from MeetUps API then messages the data into liquid markdown for posting it to a GitHub Pages site.",
  "source_url": false,
  "guid": "432064f93e674f1c4e16a9334c3a7518",
  "tag_fg_color": "#ffffff",
  "tag_bg_color": "#5bc0de",
  "icon": "calendar",
  "exported_at": "2016-12-19T06:00:36Z",
  "agents": [
    {
      "type": "Agents::LiquidOutputAgent",
      "name": "JekyllFormatting",
      "disabled": false,
      "guid": "2bde6ef936b34f036e72321e0940e4e8",
      "options": {
        "secret": "meetup",
        "expected_receive_period_in_days": "2",
        "content": "---\r\nlayout: post\r\ntitle: {{Name}}!\r\n---\r\n\r\n{% raw %}{{ {% endraw %}{{Created}} {% raw %}| divided_by: 1000 | date: \"%Y-%m-%d\" }}-Meetup.md{% endraw %}\r\n\r\nLocation: {{Location}}\r\n\r\nDate: {% raw %}{{ {% endraw %}{{Time}} {% raw %}| divided_by: 1000 | date: \"%c\" }}{% endraw %}\r\n\r\n\r\n{{Description}}\r\n \r\n[Come check it out @ the MeetUp!]({{Link}})\r\n \r\nContact us on the Live Chat above or Social feeds below if you have a skills or project builds you would like to demo at any of the meetups.\r\n \r\n{% raw %}\r\n![_config.yml]({{ site.baseurl }}/images/jekyll-logo.png)\r\n{% endraw %}",
        "mime_type": "text/x-markdown",
        "mode": "Last event in",
        "event_limit": ""
      },
      "propagate_immediately": false
    },
    {
      "type": "Agents::WebsiteAgent",
      "name": "MeetUpAPI",
      "disabled": false,
      "guid": "62e184a596ae56de188643414d1833f0",
      "options": {
        "expected_update_period_in_days": 2,
        "url": "https://api.meetup.com/{% credential meetupid %}/events?photo-host=public&page=1&sig_id={% credential meetupsigid %}&fields=plain_text_description&sig={% credential meetupsig %}",
        "type": "json",
        "mode": "on_change",
        "extract": {
          "Name": {
            "path": "$.[0].name"
          },
          "Description": {
            "path": "$.[0].plain_text_description"
          },
          "Link": {
            "path": "$.[0].link"
          },
          "Created": {
            "path": "$.[0].created"
          },
          "Time": {
            "path": "$.[0].time"
          },
          "Location": {
            "path": "$.[0].venue.name"
          }
        }
      },
      "schedule": "every_12h",
      "keep_events_for": 0,
      "propagate_immediately": false
    },
    {
      "type": "Agents::ShellCommandAgent",
      "name": "GitCommit (2)",
      "disabled": false,
      "guid": "65050ebac7203e16b924a35d9ca70629",
      "options": {
        "path": "/home/{% credential luser %}/website/{% credential grepo %}.github.io/_tests/",
        "command": "curl -o {{ Created |divided_by: 1000 |date: \"%Y-%m-%d\" }}-Meetup.md http://localhost:3000/users/1/web_requests/9/meetup.md && git add . && git commit -m 'Update Feed' && git push origin master",
        "suppress_on_failure": false,
        "suppress_on_empty_output": false,
        "expected_update_period_in_days": 1
      },
      "schedule": "never",
      "keep_events_for": 0,
      "propagate_immediately": false
    }
  ],
  "links": [
    {
      "source": 1,
      "receiver": 0
    },
    {
      "source": 1,
      "receiver": 2
    }
  ],
  "control_links": [

  ]
}
```

**Comment by NonaSuomy** [comment]
Here is a scenario export, just to note you can't use liquid credential tags in path :(

"path": "/home/{% credential luser %}/website/{% credential grepo %}.github.io/_tests/",
Anyway to fix this?

(It doesn't actually let you save that, I just manual modified it to that after exporting the scenario.)

meetups.json

{
  "schema_version": 1,
  "name": "MeetUps",
  "description": "Grabs content from MeetUps API then messages the data into liquid markdown for posting it to a GitHub Pages site.",
  "source_url": false,
  "guid": "432064f93e674f1c4e16a9334c3a7518",
  "tag_fg_color": "#ffffff",
  "tag_bg_color": "#5bc0de",
  "icon": "calendar",
  "exported_at": "2016-12-19T06:00:36Z",
  "agents": [
    {
      "type": "Agents::LiquidOutputAgent",
      "name": "JekyllFormatting",
      "disabled": false,
      "guid": "2bde6ef936b34f036e72321e0940e4e8",
      "options": {
        "secret": "meetup",
        "expected_receive_period_in_days": "2",
        "content": "---\r\nlayout: post\r\ntitle: {{Name}}!\r\n---\r\n\r\n{% raw %}{{ {% endraw %}{{Created}} {% raw %}| divided_by: 1000 | date: \"%Y-%m-%d\" }}-Meetup.md{% endraw %}\r\n\r\nLocation: {{Location}}\r\n\r\nDate: {% raw %}{{ {% endraw %}{{Time}} {% raw %}| divided_by: 1000 | date: \"%c\" }}{% endraw %}\r\n\r\n\r\n{{Description}}\r\n \r\n[Come check it out @ the MeetUp!]({{Link}})\r\n \r\nContact us on the Live Chat above or Social feeds below if you have a skills or project builds you would like to demo at any of the meetups.\r\n \r\n{% raw %}\r\n![_config.yml]({{ site.baseurl }}/images/jekyll-logo.png)\r\n{% endraw %}",
        "mime_type": "text/x-markdown",
        "mode": "Last event in",
        "event_limit": ""
      },
      "propagate_immediately": false
    },
    {
      "type": "Agents::WebsiteAgent",
      "name": "MeetUpAPI",
      "disabled": false,
      "guid": "62e184a596ae56de188643414d1833f0",
      "options": {
        "expected_update_period_in_days": 2,
        "url": "https://api.meetup.com/{% credential meetupid %}/events?photo-host=public&page=1&sig_id={% credential meetupsigid %}&fields=plain_text_description&sig={% credential meetupsig %}",
        "type": "json",
        "mode": "on_change",
        "extract": {
          "Name": {
            "path": "$.[0].name"
          },
          "Description": {
            "path": "$.[0].plain_text_description"
          },
          "Link": {
            "path": "$.[0].link"
          },
          "Created": {
            "path": "$.[0].created"
          },
          "Time": {
            "path": "$.[0].time"
          },
          "Location": {
            "path": "$.[0].venue.name"
          }
        }
      },
      "schedule": "every_12h",
      "keep_events_for": 0,
      "propagate_immediately": false
    },
    {
      "type": "Agents::ShellCommandAgent",
      "name": "GitCommit (2)",
      "disabled": false,
      "guid": "65050ebac7203e16b924a35d9ca70629",
      "options": {
        "path": "/home/{% credential luser %}/website/{% credential grepo %}.github.io/_tests/",
        "command": "curl -o {{ Created |divided_by: 1000 |date: \"%Y-%m-%d\" }}-Meetup.md http://localhost:3000/users/1/web_requests/9/meetup.md && git add . && git commit -m 'Update Feed' && git push origin master",
        "suppress_on_failure": false,
        "suppress_on_empty_output": false,
        "expected_update_period_in_days": 1
      },
      "schedule": "never",
      "keep_events_for": 0,
      "propagate_immediately": false
    }
  ],
  "links": [
    {
      "source": 1,
      "receiver": 0
    },
    {
      "source": 1,
      "receiver": 2
    }
  ],
  "control_links": [

  ]
}

**Comment by cantino** [comment]
* It looks like `path` in the ShellCommandAgent needs to be a real path on disk at the time the options are saved, which is before Liquid interpolation. (It'd probably work if you changed line 71 of the shell_command_agent.rb to `unless File.directory?(interpolated['path'])`)  Want to make a PR for that?
* It looks like the LiquidOutputAgent should support interpolation on the secret.
* I don't know why you needed that raw / endraw stuff. Maybe it's not converting Time to a number correctly? Does `Time | plus: 0 | divided_by: 1000 | date: "%c"` work any better?

**Comment by NonaSuomy** [comment]
@cantino thanks for your further guidance I will check out those items, the main current issue that I was seeking help on was that it doesn't seem to pass the values from the events to the other agents when I use the liquid tags from the other events during a "RUN", but they seem to work during a "DRY RUN" when you select the data from the list shown above. Passing values from Website Agent => Liquid Agent on a RUN I get null data so when the {{ time }} tries to convert it just gives back the start of the epoch because it never received any data from the RUN events. Which then effects the file naming in the command agent because it has no data to convert and just puts the start of the epoch in the file name.

I tried to change other options like on_change to all and another value to true, but seems it still bombs out with sending empty data.

This scenario takes a message from meetups and then posts it to the Gitter Activity Feed on the right.
```
{
  "schema_version": 1,
  "name": "GitterWebhookActivityFeed",
  "description": "Grab Meetups data post to Gitter Activity Feed with Gitter Custom Webhook.",
  "source_url": false,
  "guid": "f72783d4f83fd66cabf36dda82400484",
  "tag_fg_color": "#ffffff",
  "tag_bg_color": "#5bc0de",
  "icon": "bullhorn",
  "exported_at": "2016-12-19T23:15:43Z",
  "agents": [
    {
      "type": "Agents::PostAgent",
      "name": "GitterWebhook",
      "disabled": false,
      "guid": "4471913264de0956c9f80ee71cc4cc37",
      "options": {
        "post_url": "https://webhooks.gitter.im/e/{% credential gitterwebhook %}",
        "expected_receive_period_in_days": "1",
        "content_type": "json",
        "method": "post",
        "payload": {
          "message": "Trigger Automated Event test 2 with data: {{ Name }}"
        },
        "headers": {
        },
        "emit_events": "false",
        "no_merge": "true"
      },
      "schedule": "never",
      "keep_events_for": 0,
      "propagate_immediately": false
    },
    {
      "type": "Agents::WebsiteAgent",
      "name": "MeetUpAPI",
      "disabled": false,
      "guid": "6e0ec05697a9e89ccc34813fd23948fc",
      "options": {
        "expected_update_period_in_days": "2",
        "url": "https://api.meetup.com/{% credential meetupid %}/events?photo-host=public&sig_id={% credential meetupsigid %}&fields=plain_text_description&sig={% credential meetupsig %}",
        "type": "json",
        "mode": "all",
        "extract": {
          "Name": {
            "path": "$.[0].name"
          },
          "Description": {
            "path": "$.[0].plain_text_description"
          },
          "Link": {
            "path": "$.[0].link"
          },
          "Created": {
            "path": "$.[0].created"
          },
          "Time": {
            "path": "$.[0].time"
          },
          "Location": {
            "path": "$.[0].venue.name"
          }
        }
      },
      "schedule": "every_12h",
      "keep_events_for": 0,
      "propagate_immediately": false
    }
  ],
  "links": [
    {
      "source": 1,
      "receiver": 0
    }
  ],
  "control_links": [

  ]
}
```

Pushing RUN on the website agent seems sometimes it works, pushing DRY RUN on the Post Agent I can't seem to figure this out if there is a difference.

This is what it shows in Gitter Activity:

```
18:10
Trigger Automated Event test 2 with data: <= RUN
17:55
Trigger Automated Event test 2 with data: All about Mini_sumo Robots <= RUN?
17:53
Trigger Automated Event test 2 with data:
17:50
Trigger Automated Event test 2 with data:
17:48
Trigger Automated Event test 2 with data:
17:43
Trigger Automated Event test 2 with data: All about Mini_sumo Robots
17:41
Trigger Automated Event test 2 with data: All about Mini_sumo Robots
17:40
Trigger Automated Event test 2 with data: All about Mini_sumo Robots
17:37
Trigger Automated Event test 2 with data: All about Mini_sumo Robots 
17:36
Trigger Automated Event test 2 with data: <= RUN
17:34
Trigger Automated Event test 2 with data: <= RUN
17:34
Trigger Automated Event test 2 with data: All about Mini_sumo Robots <== Dry Run
17:32
Trigger Automated Event test 2 with data: <== Second test trying to add data from website agent RUN (data missing)
17:29
Trigger Automated Event test! <== first test from Huginn.
00:12
markdown is fun, test activity post! <== first test from cURL.
```

It's supposed to grab data: {{ Name }} from website agent but randomly seems like it grabs nothing.

Which happens in the cases posted above.

**Comment by cantino** [comment]
Can you show me one of the events from the WebsiteAgent?

**Comment by nogre** [comment]
I basically do what you outline above. Huginn gets a bunch of data from websites and then I use that output to create a Jekyll site via shell script. My workflow looks like this: Huginn gets data and outputs liquid formatted data. Then I `wget` to save that output and `cat` to concatenate the static parts of the website with the Huginn dynamic bits. I also do whatever time math I need to in shell scripts and splice it into the files. The finished files are then put into the Jekyll folders and the site is built.

**Comment by NonaSuomy** [comment]
@cantino [1826#issuecomment-267238642](https://github.com/cantino/huginn/issues/1826#issuecomment-267238642)

**Comment by NonaSuomy** [comment]
@nogre  Thanks for some input on how you go about it.  I was looking for a way that would not require local storage. This is what I am currently doing: [1826#issuecomment-267889618](https://github.com/cantino/huginn/issues/1826#issuecomment-267889618) Basically 

WebsiteAgent ▶️ LiquidOutputAgent ▶️ ShellCommandAgent ▶️ 

```
"path": "/home/username/website/usersite.github.io/_posts/",
        
"command": 

"curl -o {{ Created |divided_by: 1000 |date: \"%Y-%m-%d\" }}-Meetup.md http://localhost:3000/users/1/web_requests/9/meetup.md 

&& git add . 

&& git commit -m 'Update Feed' 

&& git push origin master",

        "suppress_on_failure": false,
        "suppress_on_empty_output": false,
```

I was hoping there was some Excalibur comprehension on the GitHub API where you could commit the data direct to the GitHub repo without downloading to the local drive so you wouldn't have to cache the entire git repo of the GitHub Pages site locally.

**Comment by cantino** [comment]
@NonaSuomy Could you show me the full JSON from one of the website agent events and one of the command agent ones?

**Comment by cantino** [comment]
Hi @NonaSuomy, is it okay if we close out this issue?

**Comment by NonaSuomy** [comment]
@cantino Still looking for the original question answer, a method to not have to locally store the git clone of the website on the server, even though the rest of the conversation did help with many other things. Just to note I was finally able to test this change out [1826#issuecomment-268033214](https://github.com/cantino/huginn/issues/1826#issuecomment-268033214) and it worked properly, thank you for that. The [PR 1911](https://github.com/cantino/huginn/pull/1911) has been requested.

**Comment by cantino** [comment]
It might be possible via the GitHub API (I'm not sure).

**Comment by dsander** [comment]
@NonaSuomy The repository contents API should do that, but i have not played with it: https://developer.github.com/v3/repos/contents/

**Comment by christopherdurr** [comment]
I think this issue should be closed

**Comment by cantino** [comment]
Yea, it's time. Please re-open if you have further questions!
