### ISSUE TITLE
Post agent not posting to a particular url.

### ISSUE THREAD

**Issue by neethkrish** [cantino/huginn#1827]
Hi,

I have created a post agent to post response to particular url , which receives events from a twitter streams agent via an event formatting agent . The post agent returns the following payload response , each time it receives the event .

{
  "body": "\t\n\n\n",
  "headers": {
    "Server": "nginx",
    "Date": "Tue, 13 Dec 2016 08:41:12 GMT",
    "Content-Type": "application/json; charset=UTF-8",
    "Transfer-Encoding": "chunked",
    "Connection": "keep-alive",
    "Vary": "Accept-Encoding",
    "Set-Cookie": "PHPSESSID=doer0u5cmr5me4k5dj67lp61r2; path=/; secure; HttpOnly, mc_session_ids[default]=0500c27301855d60652937afd23c30bbf41a7963; expires=Tue, 13-Dec-2016 08:46:12 GMT; Max-Age=300; path=/; secure; httponly, mc_session_ids[multi][0]=a3eed28e45d6b05f813b23f5771ac9958741a0a5; expires=Tue, 13-Dec-2016 08:46:12 GMT; Max-Age=300; path=/, mc_session_ids[multi][1]=3a0af0cb726166b7274773def40d27991b641d59; expires=Tue, 13-Dec-2016 08:46:12 GMT; Max-Age=300; path=/, mc_session_ids[multi][2]=0f23962d06545a33bae10545b2359ff2ce1ae029; expires=Tue, 13-Dec-2016 08:46:12 GMT; Max-Age=300; path=/, mc_session_ids[multi][3]=e53c55742639dff43c4c07e142373c310d9adcf0; expires=Tue, 13-Dec-2016 08:46:12 GMT; Max-Age=300; path=/, mc_session_ids[multi][4]=c8b54d84a309ef4b759d87458d1eccc825dbfc74; expires=Tue, 13-Dec-2016 08:46:12 GMT; Max-Age=300; path=/",
    "Expires": "Thu, 19 Nov 1981 08:52:00 GMT",
    "Cache-Control": "no-store, no-cache, must-revalidate, post-check=0, pre-check=0",
    "Pragma": "no-cache",
    "Access-Control-Allow-Origin": "",
    "Access-Control-Allow-Methods": "POST, GET, OPTIONS, PUT, DELETE",
    "Access-Control-Allow-Credentials": "true",
    "X-Content-Type-Options": "nosniff, nosniff",
    "Access-Control-Expose-Headers": "X-WP-Total, X-WP-TotalPages",
    "Access-Control-Allow-Headers": "Authorization, Content-Type",
    "X-Xss-Protection": "1; mode=block",
    "Content-Length": 4
  },
  "status": 200
}

And there is no response in the resource end i.e after posting to the url . I am not getting any clue regarding the issue . Any suggestions ? 

Thanks in advance..

**Comment by dsander** [comment]
Hi @neethkrish,

is the PostAgent sending the data you are expecting? http://requestb.in/ is a great service to verify the request is correct.
What should be the response of the website your are POSTing to?

**Comment by neethkrish** [comment]
Thanks.. i got it right..a mistake from my part..
