### ISSUE TITLE
Issue in adding services authentication for using one of the twitter agents

### ISSUE THREAD

**Issue by neethkrish** [cantino/huginn#1829]
Hi,
I have created a twitter streams agent and also authentication with the twitter services was also successfully completed . I could see the "authenticate with twitter" button and twitter service name listed in the services tab and of huginn in my local machine.

But the problem is am not able to achieve the same in live environment . Have followed the same procedures but cannot see the "authenticate with twitter" button in the huginn service tab  . Any guesses why ?
 
Thanks..

**Comment by dsander** [comment]
Hi,

if the twitter service is not listed the `TWITTER_OAUTH_KEY` and `TWITTER_OAUTH_SECRET` settings are not set in the `.env` (or environment config for docker). Did you re-export the Huginn init scripts after modifying the configuration?

**Comment by neethkrish** [comment]
Hi @dsander ,
Thanks a lot .. I got it correct now . The problem was as per the instructions given, after authenticating i restarted huginn . But after exporting it works fine .

Thanks..
