### ISSUE TITLE
Stop autostart

### ISSUE THREAD

**Issue by justinkruit** [cantino/huginn#1830]
Hey,

I'm a bit new to this all. I've installed the deployment setup successfully, and got it all up and running. But how can I set it so it won't start up together with my PI every time? As this won't be something I'll need all the time, so I rather have it set that I need to enter a command to start it, instead of entering a command to stop it again.

**Comment by dsander** [comment]
Hey @justinkruit,

that depends on the linux distribution, I think Raspbian is based on Debian 7, so `systemctl disable runit.service` should disable runit which is used to start Huginn.

**Comment by justinkruit** [comment]
@dsander Yup, that did the trick, thank you!

**Comment by justinkruit** [comment]
Uhm.. Now that I tried to start it again, it gave some errors about runsv not running. Is there a way I can just start Huginn again with a command, without the need to enable and disable the service every time when needed?

**Comment by dsander** [comment]
Did you try `systemctl start runit.service`? That should start runit which then starts Huginn processes you configured in your Procfile.

**Comment by cantino** [comment]
Hi @justinkruit, is it okay if we close out this issue?

**Comment by justinkruit** [comment]
@cantino yeah sure, no problem.
