### ISSUE TITLE
Combine two feeds on matching items

### ISSUE THREAD

**Issue by level20peon** [cantino/huginn#1831]
Is it possible to combine two (or more) feeds which might differ in items (identified by URL for example) and only keep the items which are present in both feeds?

Use case: Having a finite amount of filters available which can be passed via URL in order to receive some results back, I need to use two URLs in order to send all filters I need. Only items which are returned from both WebsiteAgents should be processed further.

**Comment by dsander** [comment]
That should be some kind of `UnionAgent` which does the opposite of the `DeDuplicationAgent`, right? I think that is currently only possible with a `JavascriptAgent`.

**Comment by level20peon** [comment]
If it's possible via JavascriptAgent I would appreciate a potential workaround you have in mind. For example:
1) use two WebsiteAgents, each with their own search parameters
2) use two EventFormattingAgents, in order to (for example) create / extract unique URLs / IDs
3) use two separate DeDuplicationAgents
4) use one / two JavascriptAgent (? -> please help)

**Comment by dsander** [comment]
I think it should be one `JavascriptAgent` which receives the events from the `DeDuplicationAgent` and stores them in two different memory keys based on the source `WebsiteAgent` (you could use the `EventFormattingAgent` to add the key to the events). When the `JavascriptAgent` is checked, iterate over the events and re-emit those which are present in both memory keys and clear the memory.

**Comment by level20peon** [comment]
How do I accomplish the JavascriptAgent to wait for the input from both streams?

**Comment by level20peon** [comment]
Maybe WebsiteAgent (2) -> EventFormattingAgent (2) -> DeduplicationAgent (2) ==> DigestAgent (1) -> JavaScriptAgent (1) ?

**Comment by level20peon** [comment]
I'm having trouble using the JavaScriptAgent. I know how to write Javascript but am unsure about how to use the methods implemented in this very framework. As a first test, I tried to just output the events my JavaScriptAgent receives via DryRun. Unfortunately, nothing is returned. Here's my DryRun test:

    Agent.receive = function() {
    	var events = Agent.incomingEvents();
        for(var i=0;i<events.length;i++){
            Agent.createEvent(events[i].payload);
        }
    };

It doesn't matter if I use "Agent" or "this" inside the function. It also doesn't matter if I use "payload" or any actual key I use inside my payloads. The DryRun always returns no result at all.

**Comment by level20peon** [comment]
I have serious issues using the JavaScript Agent. Is there an overview with a few examples? I do quite well with Javascript but I don't really get the methods used in this framework (or better yet: I don't get the reqeuired workflow).

**Comment by cantino** [comment]
I think you'd need an agent that collected incoming events and stored them in memory, deduplicated them, then emitted them after a certain amount of time passed, right?

**Comment by dsander** [comment]
@level20peon The example `receive` function should be a good starting point, either manually create an event in the dry run modal or connect the JavascriptAgent to the source Agent and select a event the source previously emitted. By adding `this.memory('agent1', events[i].payload)` to the for loop you should be able to add received event to the memory.

**Comment by level20peon** [comment]
ok, but one question still remains: do I need the DigestAgent in order to collect events from both sources first? How else can the JavascriptAgent determine which events have to be combined?

**Comment by dsander** [comment]
> Maybe WebsiteAgent (2) -> EventFormattingAgent (2) -> DeduplicationAgent (2) ==> DigestAgent (1) -> JavaScriptAgent (1) ?

I think that sounds like the easiest solution, you can use the two `EventformattingAgent`s to add a key to the event which determines if it came from the first or second `WebsiteAgent`

**Comment by level20peon** [comment]
ok, I got a workflow like this now:
![workflow](https://cloud.githubusercontent.com/assets/14050847/21380000/4f3ed7de-c752-11e6-82d5-f20d926a1275.png)

I am using a JavascriptAgent like this now (simplified for two streams, "trigger" is my stream identifier):

    Agent.receive = function() {
    	var events = this.incomingEvents();
    	for(var i = 0; i < events[0].payload.events.length; i++) {
    		for(var j = 0; j < events[0].payload.events.length; j++) {
    			if (
    			events[0].payload.events[i].trigger == '1' &&
    			events[0].payload.events[j].trigger == '2' &&
    			events[0].payload.events[i].link == events[0].payload.events[j].link
    			) {
    				this.createEvent({
    					'title': events[0].payload.events[i].title,
    					'description': events[0].payload.events[i].description,
    					'link': events[0].payload.events[i].link
    				});
    			}
    		}
    	}
    };

It seems to work as intended. What I would like to know, however, is if huginn schedules Agents which are further on top of such workflow before agents which are further down the line, if they got the same execution interval set. So in this example: are the WebsiteAgents always run before the DigestAgent if all Agents are set for a 1h interval?

**Comment by level20peon** [comment]
@cantino You are correct. However, I don't know if this Use Case is that popular, so I'm just fine using the JavascriptAgent here.

**Comment by dsander** [comment]
> It seems to work as intended. What I would like to know, however, is if huginn schedules Agents which are further on top of such workflow before agents which are further down the line, if they got the same execution interval set. So in this example: are the WebsiteAgents always run before the DigestAgent if all Agents are set for a 1h interval?

There are no guarantees which Agent is run first, we could control the order in which Agents are enqueued to run in DelayedJob, but when using two or more workers DJ itself executes the jobs randomly. You can use two ScheduleAgents to run those Agents at specific minutes of every hour.

**Comment by level20peon** [comment]
Is that by design or could / should that be changed, i.e. prioritize a workflow according to the Agent's position "in the line" ?
I wouldn't want to create a separate ScheduleAgent for potentially each and every other Agent I use.

**Comment by dsander** [comment]
We can't, even if we enqueue the jobs in a specific order they will be executed randomly by the background job processing system.

**Comment by level20peon** [comment]
@Avalanchaa Thanks for the input but I don't want to simply combine multiple feeds, instead I want to combine items which are present in ALL source feeds.

@dsander Ok, seems logical. Well I just set my WebsiteAgents to emmit events no matter if the source changed or not, so the probability for them to all get emmitted before they are combined at least a few times a day is high enough for me.
