### ISSUE TITLE
RSS agent fails to fetch feed

### ISSUE THREAD

**Issue by irfancharania** [cantino/huginn#1832]
I've updated my Huginn instance to cb2b906 and I noticed it's failing to fetch certain feeds (e.g. [this one](http://showrss.info/user/81009.rss?magnets=true&namespaces=false&name=clean&quality=null&re=no))

The log shows [this](http://pastebin.com/raw/WX0UFENc) message.

In an older instance, this feed works just fine

**Comment by cantino** [comment]
How long does the request take if you do it on the command line with `curl` or `wget`? I assume not >120 seconds, right?

**Comment by irfancharania** [comment]
Very quick: 0.106

`curl -o /dev/null -s -w %{time_total}  "http://showrss.info/u1009.rss?magnets=true&namespaces=false&name=clean&quality=null&re=no"`

**Comment by knu** [comment]
I think the problem is the regex pattern that causes excessive backtracking when the XML document is large.  Please try out the latest master!

**Comment by irfancharania** [comment]
I can confirm that fixed it. Thanks!

**Comment by cantino** [comment]
Woah, good catch.
