### ISSUE TITLE
git clone failed

### ISSUE THREAD

**Issue by jiey2016** [cantino/huginn#1834]
some of the important files cant be copied into the local environment .
I use cloud9ide to git clone your huginn but just missing all the files named with "." such as ".env.example " why is that?

**Comment by cantino** [comment]
I think you or your IDE is doing something like `*.*` which doesn't match dot files. This doesn't sound like a problem with Huginn.

**Comment by jiey2016** [comment]
indeed I have solved this problem thank you!

**Comment by cantino** [comment]
Glad to hear it!
