### ISSUE TITLE
Json format issue while sending event from TwitterStreamAgent to any agent

### ISSUE THREAD

**Issue by Noyalcitrus** [cantino/huginn#1835]
I am using TwitterStreamAgent and TwitterUserAgent, and while send the Event from  TwitterStreamAgent to any other agent Eg: EventFormattingAgent which expects the 'urls' key and I am getting the value of this is in the form of string. Actual value of the key is a JSON array and my expectation is it should be in JSON format 
Please help me in it.
Incoming Events from  TwitterStreamAgent is bellow 
`{
  "created_at": "Wed Dec 21 09:35:26 +0000 2016",
  "id": 811505348116934657,
  "id_str": "811505348116934657",
  "text": "#ffff https://t.co/709ZXHnO2Q https://t.co/WT9q3xFYSr https://t.co/TKclXJIVjI",
  "truncated": false,
  "entities": {
    "hashtags": [
      {
        "text": "ffff",
        "indices": [
          0,
          5
        ]
      }
    ],
    "symbols": [
    ],
    "user_mentions": [
    ],
    "urls": [
      {
        "url": "https://t.co/709ZXHnO2Q",
        "expanded_url": "https://www.facebook.com/",
        "display_url": "facebook.com",
        "indices": [
          6,
          29
        ]
      },
      {
        "url": "https://t.co/WT9q3xFYSr",
        "expanded_url": "https://www.linkedin.com/",
        "display_url": "linkedin.com",
        "indices": [
          30,
          53
        ]
      },
      {
        "url": "https://t.co/TKclXJIVjI",
        "expanded_url": "http://www.gmail.com/",
        "display_url": "gmail.com",
        "indices": [
          54,
          77
        ]
      }
    ]
  },
  "source": "<a href=\"http://twitter.com\" rel=\"nofollow\">Twitter Web Client<\/a>",
  "in_reply_to_status_id": null,
..........
}`

I am trying to accesses the key '**urls**' in EventsFornatter agent But I am getting the result is like this

`'{"url"=>"https://t.co/709ZXHnO2Q", "expanded_url"=>"https://www.facebook.com/", "display_url"=>"facebook.com", "indices"=>[6, 29]}{"url"=>"https://t.co/WT9q3xFYSr", "expanded_url"=>"https://www.linkedin.com/", "display_url"=>"linkedin.com", "indices"=>[30, 53]}{"url"=>"https://t.co/TKclXJIVjI", "expanded_url"=>"http://www.gmail.com/", "display_url"=>"gmail.com", "indices"=>[54, 77]}''`

I need this value as in the correct JSON format and any possible solution for this ???

**Comment by Noyalcitrus** [comment]
> hjhgj

**Comment by Noyalcitrus** [comment]
[hgjghj](url)

**Comment by Noyalcitrus** [comment]
`[ghjhgjghjjjjjjjjj](url)`

**Comment by dsander** [comment]
Yes try using `{{urls | as_object}}`, that will include the urls as array in the emitted event.

**Comment by Noyalcitrus** [comment]
@dsander Thanks , Its working fine

**Comment by gelinger777** [comment]
@NoyalThomas  what is your json setup? Can you share it for the data and id field?
