### ISSUE TITLE
retweet using Twitter Action Agent

### ISSUE THREAD

**Issue by Noyalcitrus** [cantino/huginn#1837]
Can u help me how to re-tweet(re-posted to another user)  using Twitter Action Agent 
I tried with twitter action agent and getting error as 'Read-only application cannot POST'
`{
  "expected_receive_period_in_days": "2",
  "favorite": "false",
  "retweet": "true",
  "emit_error_events": "false"
}` 
I set retweet as true and I am using TwitterStreamAgent and Twitter user agent as the source

I tried with Twitter Publish Agent and I am getting the error as 'Read-only application cannot POST' and i reffed `(How to get successful payload tweets in twitter publishing agent? #630)` and I am using TwitterStreamAgent as the source

Publish Agent
`{
  "expected_update_period_in_days": "1",
  "message": "{{text}}"
}`

and I am getting error 

`{
  "success": false,
  "error": "Read-only application cannot POST.",
  "failed_tweet": "#test welcome",
  "agent_id": 82,
  "event_id": 21100
}` 

is it possible to mention the username in this agent ????

OR any agent is available for this problem

**Comment by dsander** [comment]
That sounds like your Twitter OAuth application only has read access, you can change that here: https://apps.twitter.com/. You probably need to reauthenticate Huginn afterwards.

**Comment by cantino** [comment]
Hey @Noyalcitrus, okay if we close this issue?

**Comment by dsander** [comment]
I am closing this issue. Please feel free to reopen if you need further assistance!
