### ISSUE TITLE
How to change one value based on value of another?

### ISSUE THREAD

**Issue by tomkofford** [cantino/huginn#1838]
I need to know how to adjust one value based on another value.

I have a great podcast feed that filters out all the stuff I don't want using Huginn. It works with the following agents:
Website Agent which scrapes an existing podcast and feeds
Event Formatting Agent which extracts a timestamp and feeds
Trigger Agent which filters out a bunch of episodes and also limits feeds to a certain time (compared to timestamp from previous agent) and  feeds 
De Duplication Agent which feeds
Data Output Agent which outputs the podcast feed.

The problem is that recently the source podcast has changed its publishing practice a bit, and broken out a single day by "Hour 1", "Hour 2", etc. This would be fine except that they also consistently timestamp the episodes incorrectly. So it appears to my podcast player that "Hour 3" come before "Hour 1" and it plays them in that order. If I play in reverse order, that's fine for a single day, but not when there are multiple days. I want to listen to them in order. The timestamps are all within minutes of each other for a single day.

So, I'd like to do something in the formatting agent like (pseudo here, no idea how to do an "if then"):
```
if {title} contains "Hour 1"
   "instructions": {
        "pubDate": "{{pubDate - 30 minutes}}"
    }
else if {title} contains "Hour 2"
    "instructions": {
         "pubDate": "{{pubDate - 15 minutes}}"
     }
end if
```

Any help is appreciated!!

**Comment by cantino** [comment]
Hey @tomkofford. You could certainly do this with the JavaScriptAgent. That might be the easiest option.

**Comment by Enfop** [comment]
hey @tomkofford 

you could try to do the if-else inside the pubDate value string with liquid. Something like this   
```
{
  "instructions": {
    "pubDate": "{% if title contains 'Hour 1'%} {{ 'now'| date: '%b %d, %Y %I:%M %p'  }} {% elsif title contains 'Hour 2' %} {{'now' | date: '%s' | minus : 1800 | date: '%b %d, %Y %I:%M %p' }} {% endif %}"
  },
  "mode": "clean"
}
```
Time calculations in liquid are a bit ugly  :smile:.  
https://ecommerce.shopify.com/c/ecommerce-design/t/simple-date-math-manipulation-help-needed-for-liquid-280610 and 
http://stackoverflow.com/questions/21056965/date-math-manipulation-in-liquid-template-filter 
might help for this.

Sry for the long code block but i think json doesn't like linebreaks.

**Comment by tomkofford** [comment]
Thanks! Both suggestions work. I went with the if-else statement in liquid to avoid another agent. I'm not sure why I just didn't try it to begin with - it looks so obvious now. Here's what I ended up with in my formatting agent that takes care of this:

```
{
  "instructions": {
    "pubDate": "{% if title contains 'Hour 1' %}{{ pubDate | date: '%s' | minus : 1800 | date: '%a, %d %b %Y %H:%M:%S %z'  }} {% elsif title contains 'Hour 2' %}{{ pubDate | date: '%s' | minus : 900 | date: '%a, %d %b %Y %H:%M:%S %z' }} {% endif %}"
  },
  "matchers": [],
  "mode": "merge"
}
```
