### ISSUE TITLE
one key deploy for heroku is failed

### ISSUE THREAD

**Issue by jiey2016** [cantino/huginn#1839]
https://github.com/cantino/huginn/blob/fca06d6ec2a4ccfaa02e44f664a577ce4893e050/README.md#heroku
it seems that the one key deploy for heroku is no longer working anymore could you fix it? @cantino

**Comment by cantino** [comment]
Could you clarify @jiey2016? I just pressed the "Deploy to Heroku" button on the README and it worked for me.

**Comment by ramdaffe** [comment]
I'm experiencing the same thing just now, bundler fails at fetching tumblr_client repo.

**Comment by dsander** [comment]
@ramdaffe I just ran the deployment and it worked, "failed to fetch" are almost always random errors where the connection from Heroku to Github times out. If that happens just try it again :)

**Comment by jiey2016** [comment]
@cantino It seems that the function is turning normal maybe just like @ramdaffe said the connection is unstable,anyway problem sloved thank you guys

**Comment by cantino** [comment]
Let us know if you have any questions!
