### ISSUE TITLE
Daily Schedulers not working

### ISSUE THREAD

**Issue by nogre** [cantino/huginn#1840]
I'm trying to fire off a Javascript Agent every other day. However, I can't seem to get it to automatically trigger using the "Every 1day" or "Every 2 day" schedulers. For instance I'll have the agent set to trigger every day and then I'll see that it said "last check 4 days ago". This is confirmed by using the agent's memory to store last execution time.

As a workaround I'm triggering the agent at 1pm and then doing some javascript time math to make the important code only execute every other day.

**Comment by dsander** [comment]
Just to clarify the schedules which are running on a fixed time every day work, but "every X days" doesn't?

**Comment by nogre** [comment]
@dsander That is correct. Schedulers that are like every 1 minute or at 1pm daily are working for me, but not the Every 1day.

**Comment by dsander** [comment]
That sounds odd, is it possible that your Huginn background worker is restarted frequently? At the moment the every X schedules are counted from the startup of the background process (either `bin/threaded.rb` or `bin/scheduler.rb`). To run every day the process needs to run at least 24 hours.

**Comment by cantino** [comment]
I started a test agent on my setup with a 1d schedule to make sure I'm seeing it work. Will take a couple days to know for sure.

**Comment by nogre** [comment]
@cantino Thanks. I appreciate it.
@dsander I'll take a look.

**Comment by cantino** [comment]
My daily schedule does seem to be working:

<img width="859" alt="screen shot 2017-01-03 at 7 56 21 am" src="https://cloud.githubusercontent.com/assets/83835/21608400/3d8e7aa2-d18a-11e6-9485-3c2a7bf8da81.png">

**Comment by nogre** [comment]
@cantino Thanks for taking a look. I must have something strange on my end I haven't figured out yet.
