### ISSUE TITLE
Issues with the most recent docker image

### ISSUE THREAD

**Issue by mattbarron** [cantino/huginn#1845]
Is anyone else having issues with the most recent docker image on [https://hub.docker.com/r/cantino/huginn/](https://hub.docker.com/r/cantino/huginn/)? I am trying to initialize with docker compose and it is constantly restarting with an error of "/app/.env: line 10: app: command not found."

**Comment by dsander** [comment]
Hi @mattbarron,

that sounds like some kind of problem with one of the ENV variable, can you post the full backtrace?
Starting the image without additional variables works without issues for me, does the same compose config work with older tags of the image?

**Comment by mattbarron** [comment]
I am not adding any more variables than was provided in the example yaml. Here is my config:
# This needs at least compose 1.6.0
version: '2'

services:
  mysqldata:
    image: mysql:5.7
    command: /bin/true

  mysql:
    image: mysql:5.7
    volumes_from:
      - mysqldata
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: huginn
      MYSQL_USER: huginn
      MYSQL_PASSWORD: password2

  huginn:
    build:
      context: /home/myuser/gitclones/huginn/
      dockerfile: docker/multi-process/Dockerfile
    restart: always
    environment:
      HUGINN_DATABASE_NAME: huginn
      HUGINN_DATABASE_USERNAME: root
      HUGINN_DATABASE_PASSWORD: password1
      INTENTIONALLY_SLEEP: 10
      #DATABASE_INITIAL_CONNECT_MAX_RETRIES: 5
      PORT: 3000
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
    ports:
      - 3000:3000
    links:
      - mysql


I also tried just using "image: cantino/huginn" instead of building and got a similar error, "/app/.env: line 10: CHANGES.md: command not found."

**Comment by dsander** [comment]
That is really odd, can you apply those changes https://github.com/dsander/huginn/commit/9e5563d062aa4ea8020b7e59988c258f57efbef8#diff-1cdaa6855a98ab789edc9dc54f27e7e7 to the multi-process init script and rebuild the image?
It should then output the contents of the `.env` file.

**Comment by mattbarron** [comment]
I just did a bash shell into the huginn image created by docker compose, to get the .env contents, with these commands:
docker commit huginncontainerid mysnapshot
docker run -t -i mysnapshot /bin/bash

Here is my .env file with passwords removed:
APP_SECRET_TOKEN=REPLACE_ME_NOW!
DOMAIN=localhost:3000
PORT=3000
DATABASE_ADAPTER=mysql2
DATABASE_ENCODING=utf8mb4
DATABASE_RECONNECT=true
DATABASE_NAME=huginn
DATABASE_POOL=20
DATABASE_USERNAME=root
DATABASE_PASSWORD=password1
DATABASE_HOST=mysql
DATABASE_PORT=3306
DATABASE_SOCKET=/tmp/mysql.sock
DATABASE_ENCODING=utf8mb4
FORCE_SSL=false
INVITATION_CODE=try-huginn
SKIP_INVITATION_CODE=false
REQUIRE_CONFIRMED_EMAIL=false
ALLOW_UNCONFIRMED_ACCESS_FOR=2.days
CONFIRM_WITHIN=3.days
MIN_PASSWORD_LENGTH=8
RESET_PASSWORD_WITHIN=6.hours
LOCK_STRATEGY=failed_attempts
MAX_FAILED_LOGIN_ATTEMPTS=10
UNLOCK_STRATEGY=both
UNLOCK_AFTER=1.hour
REMEMBER_FOR=4.weeks
IMPORT_DEFAULT_SCENARIO_FOR_ALL_USERS=true
SMTP_DOMAIN=your-domain-here.com
SMTP_USER_NAME=you@gmail.com
SMTP_PASSWORD=somepassword
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
SEND_EMAIL_IN_DEVELOPMENT=false
EMAIL_FROM_ADDRESS=from_address@gmail.com
AGENT_LOG_LENGTH=200
TWITTER_OAUTH_KEY=
TWITTER_OAUTH_SECRET=
THIRTY_SEVEN_SIGNALS_OAUTH_KEY=
THIRTY_SEVEN_SIGNALS_OAUTH_SECRET=
GITHUB_OAUTH_KEY=
GITHUB_OAUTH_SECRET=
TUMBLR_OAUTH_KEY=
TUMBLR_OAUTH_SECRET=
DROPBOX_OAUTH_KEY=
DROPBOX_OAUTH_SECRET=
WUNDERLIST_OAUTH_KEY=
WUNDERLIST_OAUTH_SECRET=
EVERNOTE_OAUTH_KEY=
EVERNOTE_OAUTH_SECRET=
USE_EVERNOTE_SANDBOX=true
AWS_ACCESS_KEY_ID="your aws access key id"
AWS_ACCESS_KEY="your aws access key"
AWS_SANDBOX=false
FARADAY_HTTP_BACKEND=typhoeus
DEFAULT_HTTP_USER_AGENT="Huginn - https://github.com/cantino/huginn"
ALLOW_JSONPATH_EVAL=false
ENABLE_INSECURE_AGENTS=false
ENABLE_SECOND_PRECISION_SCHEDULE=false
SCHEDULER_FREQUENCY=0.3
EVENT_EXPIRATION_CHECK=6h
USE_GRAPHVIZ_DOT=dot
DIAGRAM_DEFAULT_LAYOUT=dot
TIMEZONE="Pacific Time (US & Canada)"
FAILED_JOBS_TO_KEEP=100
DELAYED_JOB_MAX_RUNTIME=2
DELAYED_JOB_SLEEP_DELAY=10
CAPISTRANO_DEPLOY_SERVER=
CAPISTRANO_DEPLOY_USER=
CAPISTRANO_DEPLOY_REPO_URL=
ASSET_HOST=
DEFAULT_SCENARIO_FILE=
RAILS_SERVE_STATIC_FILES=
SEED_EMAIL=
SEED_PASSWORD=
SEED_USERNAME=
SMTP_OPENSSL_CA_FILE=
SMTP_OPENSSL_CA_PATH=
SMTP_OPENSSL_VERIFY_MODE=
RAILS_ENV=production
START_MYSQL=
RAILS_LOG_TO_STDOUT=true
RAILS_SERVE_STATIC_FILES=true

**Comment by mattbarron** [comment]
I removed all the containers and started at ground zero. Got things working, thanks for the help.
