### ISSUE TITLE
need help about websiteagent and multi event

### ISSUE THREAD

**Issue by singler-rss** [cantino/huginn#1849]
i am use huginn to creat full rss , it works well .but still need help.

for example：

use website agent grabs a webpage's photo .the webpage have "pic1","pic2","pic3".....,

the events created by websiteagent looks that

event1:
title:"abc"
content:"pic1"

event2:
title:"abc"
content："pic2"

event2:
title:"abc"
content："pic3"

............

but i am really want this

event
title"abc"
content:"pic1,pic2,pic3"

what shall i do ? please help .

**Comment by dsander** [comment]
Hi @singler-rss,

I think the easiest solution would be a `DigestAgent` to concatenate the `content` values and runs on the same schedule as your `WebsiteAgent`. 

@knu @cantino I wonder if we should give the `WebsiteAgent` an option to emit all extracted matches in one event?

**Comment by singler-rss** [comment]
hi @dsander 
thank‘s for help
digestagent may be solution.
and i  like u idea .

**Comment by cantino** [comment]
Hey @singler-rss, okay if we close this issue?

**Comment by singler-rss** [comment]
yes . please close this issue .
there are 2 ways solve my question.
1  use  .//@src
2  use Event Formatting Agent modify event .

**Comment by cantino** [comment]
Sounds good!
