### ISSUE TITLE
Using huginn with vagrant: some setup problems

### ISSUE THREAD

**Issue by aborruso** [cantino/huginn#1850]
Hi,
I have installed all using [this guide](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md).

I'm using nginx, but I have changed the default port to 82.

```
  listen 0.0.0.0:82 default_server;
  listen [::]:82 ipv6only=on default_server;
```
If I run `sudo nginx -t` I have

    nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
    nginx: configuration file /etc/nginx/nginx.conf test is successful

If I run  `sudo bundle exec rake production:status`, I have:

    run: huginn-jobs-1: (pid 14664) 5s; run: log: (pid 934) 2131s
    run: huginn-web-1: (pid 14695) 0s; run: log: (pid 931) 2131s

Then in my vagrant conf file I have added this row:

    config.vm.network "forwarded_port", guest: 3000, host: 3000

But If I open localhost:3000 in my browser I have a gray page with `ERR_SOCKET_NOT_CONNECTED`.

I think it's a stupid error of mine, but I do not know what.

Thank you

**Comment by dsander** [comment]
Hi @aborruso,

nginx is used as proxy in front of the Huginn application server. Try exposing the guest port 82 from your VM.

**Comment by cantino** [comment]
Hey @aborruso, okay if we close this issue?

**Comment by alias1** [comment]
Closing for now, can reopen if required.
