### ISSUE TITLE
source install instruction suggestions:

### ISSUE THREAD

**Issue by djdavetrouble** [cantino/huginn#1851]
asks you to curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash - 
before curl is installed in the next step. Either move down or add an install curl step above this.

also says to

mysql> GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, LOCK TABLES ON `huginn_production`.* TO 'huginn'@'localhost';

before the database is created. I had to 'CREATE DATABASE huginn_production' before this would work.

**Comment by dsander** [comment]
Hi @djdavetrouble,

which Debian 7 version/image are you using as the base for the installation? I tested Wheezy on multiple hosting providers and never had the problems you describe.

**Comment by djdavetrouble** [comment]
Actually I was using lubuntu and switched to the recommended version of ubuntu, it worked fine. The instructions do ask you to use curl before it is installed, though.
