### ISSUE TITLE
Different form in user credentials insertion and edition

### ISSUE THREAD

**Issue by Phyks** [cantino/huginn#1856]
Hi,

The form when inserting a new user credential in database is a normal `textarea`, as expected:
<img width="1216" alt="capture d ecran 2017-01-03 a 16 27 49" src="https://cloud.githubusercontent.com/assets/3856586/21615335/5c56106e-d1dd-11e6-8603-29fe37c3403f.png">

However, when editing the inserted user credential, the form is a "code" form, with line numbers, whatever its type (whereas such a form could be expected for a "JavaScript" credential, but not for a plaintext one).

<img width="1056" alt="capture d ecran 2017-01-03 a 16 27 55" src="https://cloud.githubusercontent.com/assets/3856586/21615336/5c91a20a-d1dd-11e6-9ef9-7425712ec216.png">

**Comment by cantino** [comment]
Hey @Phyks. I hadn't realized it wasn't using the rich editor for the creation form too. The original intention was to allow you to write snippets of code and such to be used in multiple agents, but now that the JavaScriptAgent has the editor inline, it's less needed. Maybe we should remove it from Credentials, where it kind of doesn't make any sense to be.

**Comment by cantino** [comment]
I was contemplating removing the rich editor and the modes from the credential form. I wish I knew if people use it there at all to write JS or larger text blobs. I'd also be open to just removing the text mode. What about it was bothering you?

**Comment by cantino** [comment]
What about the text mode was bothering you?

**Comment by cantino** [comment]
Hey @Phyks, okay if I close this, or were there more issues with the text mode?

**Comment by Phyks** [comment]
I think it is all right by now, sorry for the late reply :/
