### ISSUE TITLE
Scenario icon not selected on edit page

### ISSUE THREAD

**Issue by camilstaps** [cantino/huginn#1857]
On the page to edit a scenario, the correct icon is not selected automatically, so the top one (Gear) is always selected. Thus, when you save it and don't pay attention to this, the original icon will be changed to Gear. This can be solved pretty easily I suppose by adding a `selected="selected"` in the right place, but I don't know this code base.

**Comment by dsander** [comment]
Fixed by #1861. Thanks for reporting the issue @camilstaps

**Comment by camilstaps** [comment]
Cheers :)
