### ISSUE TITLE
Setting up Huginn with Apache 2.4 ( Ubuntu 14.04)

### ISSUE THREAD

**Issue by cvdsouza** [cantino/huginn#1858]
Hi, 

So I've set up Huginn with nginx in my dev environment and it works perfect. I'm trying to set it up with Apache since my prod server hosts Apache 2.4. 

I'm hitting the following error : 

[Tue Jan 03 21:45:40.664587 2017] [core:notice] [pid 15115:tid 140673495578496] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 03 21:45:46.275446 2017] [proxy:error] [pid 15119:tid 140673265170176] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:3000 (127.0.0.1) failed
[Tue Jan 03 21:45:46.275636 2017] [proxy:error] [pid 15119:tid 140673265170176] AH00959: ap_proxy_connect_backend disabling worker for (127.0.0.1) for 60s
[Tue Jan 03 21:45:46.275669 2017] [proxy_http:error] [pid 15119:tid 140673265170176] [client 100.8.68.30:54427] AH01114: HTTP: failed to make connection to backend: 127.0.0.1

I've followed the instructions listed here : https://github.com/cantino/huginn/wiki/Apache-Huginn-configuration ( Including changing the <Proxy *> and <Directory> setting for Apache 2.4. 

Huginn itself is up and running, I've checked with : sudo bundle exec rake production:status
 
Any suggestion on how I could fix this problem?

**Comment by cvdsouza** [comment]
Ah I see this issue was fixed : https://github.com/cantino/huginn/issues/1170
May be add this to the wiki : change listen "#{wd}/tmp/sockets/unicorn.socket"in config/unicorn.rb to listen "127.0.0.1:3000" 

Just a suggestion.

**Comment by dsander** [comment]
Hi @cvdsouza,

yes you are right that information is missing in the Wiki page, would you be willing to make the change?

**Comment by cvdsouza** [comment]
Hi @dsander , 
I've added it into the wiki.

**Comment by dsander** [comment]
Thank you!
