### ISSUE TITLE
Get current date in liquid template

### ISSUE THREAD

**Issue by camilstaps** [cantino/huginn#1859]
I have a PostAgent scheduled at 6am every day which is used to make an API request to some service. Part of the request should be the current month as a number (January is 1) and the current year. The API allows other values of course, but I'm only interested in the current date.

Is there any way I can use liquid templating to get these numbers? Or am I going about this the wrong way and should I be looking for some other solution?

**Comment by knu** [comment]
Take a look at the comments and links in #1745.  Hope they'll give you some hints!

**Comment by camilstaps** [comment]
Thanks a lot! I now use `{{ 'now' | date: "%-m" }}` for the month and `{{ 'now' | date: "%Y" }}` for the year.

**Comment by cantino** [comment]
Nice :) @knu, did this get documented on our wiki?

**Comment by knu** [comment]
@cantino Done!
