### ISSUE TITLE
Use WebSiteAgent  generate rss not work

### ISSUE THREAD

**Issue by ISX** [cantino/huginn#1862]
I need help, I want to generate rss, but not work.
**The json is**
{
  "expected_update_period_in_days": "2",
  "url": "http://m.ruguoapp.com/topics/5739ae0e662839120080ad97",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "title": {
      "css": ".content",
      "value": "normalize-space(.)"
    }
  }
}
**This website sourccode is** 
![image](https://cloud.githubusercontent.com/assets/4536178/21741174/38d82cec-d509-11e6-9b75-9647c68974af.png)

I guess the reason is about javascript is asynchronous，How can i do？

**Comment by cantino** [comment]
If it's actually because content is being rendered by JavaScript, you could try [PhantomJs Cloud](https://github.com/cantino/huginn/wiki/Browser-Emulation-Using-PhantomJs-Cloud).

**Comment by ISX** [comment]
thanks，it help me a lot

**Comment by cantino** [comment]
Great! Please let us know if you have other questions.
