### ISSUE TITLE
Issue with scheduler on latest build (commit b8765fb)

### ISSUE THREAD

**Issue by JamiePhonic** [cantino/huginn#1863]
Small issue on the latest build (Commit b8765fb)

It seems the scheduler times changed from the build i was using and "every 7 days" is no longer availale, so i had to change a couple of agents and figured that "every monday" would be close enough, however when i try to save the agents, i get an error that "Schedule is not a valid schedule"

the other options work fine though.

(Note: My .ENV file has the timezone set to "Edinburgh" since i live in scotland)

**Comment by cantino** [comment]
Thanks @JamiePhonic, being unable to save with the Monday schedule is definitely a bug.
