### ISSUE TITLE
Scheduling in digest agent

### ISSUE THREAD

**Issue by Noyalcitrus** [cantino/huginn#1869]
I am working with ' Digest Agent' and its working fine.But now i need to provide more scheduler options as end user decision.Is there any way to generate dynamic scheduler.I tried with more customized time with scheduler agent but my requirement is to set scheduling time dynamically (through payload),
And I achieved this trough javascript agent and Is there any possible solution for this with out the help of javascript agent

**Comment by dsander** [comment]
I believe you can use a `CommanderAgent` to configure the options of the `SchedulerAgent`.

**Comment by dsander** [comment]
I am closing this issue. Please feel free to reopen if you need further assistance!
