### ISSUE TITLE
RSS Data Output Agent in Feedly

### ISSUE THREAD

**Issue by razmauser** [cantino/huginn#1870]
I made some RSS Out Feeds and I try to contribute these feeds on feedly. 
But I always get an "error 404". Here is my example:

Anyone here with Data Output Agent working in Feedly?

{
  "secrets": [
    "itunes"
  ],
  "expected_receive_period_in_days": 2,
  "template": {
    "title": "iTunes RSS Out",
    "description": "iTunes RSS Out",
    "item": {
      "title": "{{title}}",
      "description": "Secret hovertext: {{hovertext}}",
      "link": "{{url}}"
    }
  },
  "ns_media": "true"
}

**Comment by cantino** [comment]
You get a 404 when you go to the URL on your Huginn instance?

**Comment by razmauser** [comment]
No. When I subscribe any of my Rss Feeds in Feedly there is always Error 404.
This is one example Feed. Do I have to use any user credentials or anything else?

http://v22017014190443188.ultrasrv.de:32768/users/2/web_requests/26/itunes.xml

**Comment by dsander** [comment]
I can not connect to the server, are you some kind of vpn to access your Huginn instance?

**Comment by razmauser** [comment]
Sorry. Server was down. 
Not the link should work.

**Comment by dsander** [comment]
I am getting the same result with your feed, however adding one from my Huginn installation works. The only difference I see is the port you are using, can you try to switch to port 80?

**Comment by razmauser** [comment]
Thanks. That works. So Feedly needs port 80.

**Comment by dsander** [comment]
Great! Feel free to reopen the issue if you need additional help.

**Comment by poonjh** [comment]
I get the same issue as @razmauser ,  add feed to feedly , no articles, and try to follow and get 404 error code.   I test in digg reader, there's no issue.     I change the port to 80, still the same.

Anything else you change to make it work in feedly ? @razmauser    Big Thanks.


Here's my feed:

 http://14.1.98.98/users/1/web_requests/22/tikehui.xml

{
  "secrets": [
    "tikehui"
  ],
  "expected_receive_period_in_days": "2",
  "template": {
    "title": "Tikehui RSS",
    "description": "This is a feed of recent Tikehui",
    "item": {
      "title": "{{title}}",
      "link": "{{url}}",
      "description": "{{Description}}",
      "guid": "{{url}}"
    },
    "link": "http://14.1.98.98/",
    "icon": "http://tikehui.com/addons/theme/_stastic/image/logo.png"
  },
  "ns_media": "true"
}

**Comment by ldexterldesign** [comment]
👋 https://github.com/huginn/huginn/issues/2905
