### ISSUE TITLE
Javascript Agent doesn't respect TZ variable on Heroku

### ISSUE THREAD

**Issue by Faberman** [cantino/huginn#1871]
I set TZ in Settings > Config Variables, but it doesn't have any effect.
This simple code snippet returns UTC time.
```
Agent.check = function() {
    var date = new Date();
    this.createEvent({ 'time': date });
};
```
Am I missing something?

**Comment by dsander** [comment]
Hi @Faberman,

we are overriding the `TZ` environment variable with the value of `TIMEZONE`, setting that variable should make the `JavascriptAgent` respect the timezone. You can find all available configuration values in [`.env.example`](https://github.com/cantino/huginn/blob/master/.env.example)

**Comment by Faberman** [comment]
Thank you, @dsander! Yes, this solved the problem.
