### ISSUE TITLE
Scenario Import - Twitter OAuth Fails

### ISSUE THREAD

**Issue by lloydpick** [cantino/huginn#1875]
Hi,

Having to move away from Omniscope as they're shutting down, and moving to my own Huginn installation. I'm trying to import my scenarios, by exporting and importing, however, whenever I import one which has any Twitter service integration it throws an error and semi-breaks the import.

    Errors when saving 'EU Twitter Post': Service can't be blank and Twitter consumer_key, consumer_secret, oauth_token, and oauth_token_secret are required to authenticate with the Twitter API. You can provide these as options to this Agent, or as Credentials with the same names, but starting with 'twitter_'.

Even though I have correctly setup the Twitter service and provide it an account to use from the dropdown.

I can't ever get it to import those Twitter agents, however the other problem is that then suddenly all associations between agents are lost. So the other agents import, but have no source or receivers anymore, and the only way to fix it is to do it by hand. Not end of the world, but frustrating.

I'm using the latest version of the Docker image.

**Comment by dsander** [comment]
Hi @lloydpick,

thanks for reporting the issue, do you mind testing if the PR fixes the problem?

Those two images have the fix build in:
```
huginnbuilder/huginn-single-process:pr-1877
huginnbuilder/huginn:pr-1877
```
