### ISSUE TITLE
Help creating a translated RSS feed via Translate Agent

### ISSUE THREAD

**Issue by keshav13** [cantino/huginn#1879]
Can anyone guide through creating a project I'm working a to translate RSS feed from a Chinese source to English using Translate API.

So far I've been able to achieve this:

**Created a Test RSS Agent:**

**Config:**
```
{
  "expected_update_period_in_days": "1",
  "clean": "false",
  "url": "https://www.anzhuo.cn/feed"
}
```

**Created a Test Website Agent:**

**Event source:** Test RSS Agent
**Config:**
```
{
  "expected_update_period_in_days": "2",
  "url": "{{url}}",
  "type": "html",
  "mode": "on_change",
  "title": "{{title}}",
  "extract": {
    "content": {
      "css": ".poDtl__tle",
      "value": "normalize-space(.)"
    }
  }
}
```

**Created a Test Translate Agent**

**Event source:** Test Website Agent
**Config:**
```
{
  "client_id": "###",
  "client_secret": "###",
  "to": "en",
  "expected_receive_period_in_days": 1,
  "content": {
    "content": "{{content}}"
  }
}
```

Now how do you create a RSS feed back from the last Test Translate Agent to finally get a translated rss feed of the website. Please help.

**Comment by dsander** [comment]
Hi @keshav13,

you should be able to feed the Event from your `TranslateAgent` to a `DataOutputAgent`. Use `{{content}}` as the item description and it should generate a RSS feed with the translated content.

**Comment by cantino** [comment]
I think you need to use the `data_from_event` option for the WebsiteAgent to tell it which HTML event field coming out of the RSSAgent you'd like to parse. Take a look at one of the events created by the RSSAgent and provide the path to that field in `data_from_event`, like `{{ description }}`.

**Comment by dsander** [comment]
I am closing this issue. Please feel free to reopen if you need further assistance!
