### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by 3PO** [cantino/huginn#1880]
Hi,

i have installed huginn, but cannot connect to it.

This is the issue from starting huginn:
https://bpaste.net/show/55a0dbd337a5

When i want to connect to huginn, i get this issue:

![2017-01-21_165328](https://cloud.githubusercontent.com/assets/945108/22175691/6619ef0a-dffa-11e6-8024-5aea0d983ea0.png)

Here ist the Log:
https://bpaste.net/show/513ba75e84b3

Where is my fault?

**Comment by dsander** [comment]
Hi @3PO,

I have never seen this error before, can you try to use a a different `PORT` in your `.env` file?

**Comment by 3PO** [comment]
Hi,

i changed the PORT in the .env file to:

``DOMAIN=localhost:5000

PORT=5000``

**Comment by dsander** [comment]
Are you using some kind of port forwarding? This line looks like the request is not coming from localhost:
```
Cannot render console from 192.168.177.45! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
```
Please also check if a process is listening on port 35729: `netstat -tulpn | grep 35729`

**Comment by 3PO** [comment]
> [...] Please also check if a process is listening on port 35729:  netstat -tulpn | grep 35729 

No issue:  

```
server01 ~ # netstat -tulpn | grep 35729
server01 ~ #
```

**Comment by dsander** [comment]
You don't use port forwarding to access Huginn?

If you do not plan to make changes to Huginn yourself I recommend following the [manual installation guide](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md)

**Comment by 3PO** [comment]
>You don't use port forwarding to access Huginn?

No, at the moment only local. Maybe later, if it's working, i'll use portforwarding.

I do not plan to make changes to Huginn myself, but i don't use Debian/Ubuntu, so i cannot use the "manual installation guide" one by one.

**Comment by dsander** [comment]
I see, you might be able to work around the issue by switching `RAILS_ENV` to `production` in your .env file. If that works the assets need to be compiled manually:
```
bundle exec rake assets:precompile RAILS_ENV=production
```

**Comment by 3PO** [comment]
The "production" mode seems working:

```
server01 huginn # foreman start
10:29:54 web.1  | started with pid 16500
10:29:54 jobs.1 | started with pid 16501
10:29:59 web.1  | [2017-01-25 01:29:59] INFO  WEBrick 1.3.1
10:29:59 web.1  | [2017-01-25 01:29:59] INFO  ruby 2.2.6 (2016-11-15) [x86_64-linux]
10:29:59 web.1  | [2017-01-25 01:29:59] INFO  WEBrick::HTTPServer#start: pid=16500 port=5000


```

![2017-01-25_103259](https://cloud.githubusercontent.com/assets/945108/22284996/1b611cfc-e2ea-11e6-8bb3-5bbdeac9d095.png)

**Comment by dsander** [comment]
Nice! Can we close the issue?

**Comment by 3PO** [comment]
It is working, but i cannot see any pictures.
But this can be a setup problem.

The "connect problem" is solved, therefor we can close this issue.

**Comment by dsander** [comment]
Did you precompile the assets and restart the server afterwards?

**Comment by dsander** [comment]
Forgot that `RAILS_SERVE_STATIC_FILES=true` needs to be set in your `.env` config as well.

**Comment by 3PO** [comment]
After addig `RAILS_SERVE_STATIC_FILES=true` in `.env`, it ist working now with Pictures.

![2017-01-30_132956](https://cloud.githubusercontent.com/assets/945108/22423183/adad69b2-e6f0-11e6-925b-084eb748d634.png)


Thanks!! :)
