### ISSUE TITLE
Gem Parsing Error

### ISSUE THREAD

**Issue by BasharAG** [cantino/huginn#1886]
I keep getting an error when running
>sudo -u huginn -H bundle install --deployment --without development test

The error is:
[!] There was an error parsing `Gemfile`: Line " RAILS_ENV=production" doesn't match format. Bundler cannot continue.

>from /home/huginn/huginn/Gemfile:9
>-------------------------------------------
>require File.join(File.dirname(__FILE__), 'lib/gemfile_helper.rb')
> GemfileHelper.load_dotenv do |dotenv_dir|
>path dotenv_dir do

What do I need to do to avoid this error? I am very new to programming

**Comment by cantino** [comment]
Hey @BasharAG, that's odd. What version of ruby and bundler are you using?

**Comment by dsander** [comment]
@BasharAG Please check your `.env` file for leading spaces and remove them if there are any.

**Comment by dsander** [comment]
I am closing this issue. Please feel free to reopen if you need further assistance!
