### ISSUE TITLE
setup_heroku fails on Windows/MSYS terminal

### ISSUE THREAD

**Issue by jmn** [cantino/huginn#1887]
Some notes from running `bin/setup_heroku` in MINGW64 GIt bash terminal on Windows
- First off,  I had to `gem install activesupport`
- Windows `heroku` client stores auth credentials in ~/_netrc so had to login in windows cmd and then in terminal, `cp ~/_netrc ~/.netrc`

After this the script ran fine all the way up until:
```
And what username would you like to login as? foo
Finally, what password would you like to use? C:/users/foo/git/huginnz/lib/setup_tools.rb:77:in `noecho': Bad file descriptor (Errno::EBADF)
        from C:/users/jmn/git/huginnz/lib/setup_tools.rb:77:in `ask'
        from C:/users/jmn/git/huginnz/lib/setup_tools.rb:83:in `nag'
        from bin/setup_heroku:138:in `<main>'

```
[Related](https://github.com/cantino/huginn/issues/489)

**Comment by dsander** [comment]
Hi @jmn,

you can try to remove `, noecho: true` from [bin/setup_tools.rb](https://github.com/cantino/huginn/blob/master/bin/setup_heroku#L138), but I can not guarantee that it will work. We generally recommend using a linux VM to set up heroku.

**Comment by dsander** [comment]
I am closing this issue. Please feel free to reopen if you need further assistance!
