### ISSUE TITLE
WebsiteAgent runs slowly, sometimes even blocked completely

### ISSUE THREAD

**Issue by waldens** [cantino/huginn#1888]
A WebsiteAgent (code below) runs slowly so frequently, as log said, `Error when fetching url: execution expired (Delayed::Worker.max_run_time is only 120 seconds) `.

Sometimes it's even blocked completely, resulting in a large backlog of jobs, as [this screenshot](https://ooo.0o0.ooo/2017/01/30/588f08a12afc6.png) showed. I have to restart huginn manually to stop it.

Already checked `bundle exec rake production:check`, `huginn_error.log`, `unicorn.log`, `production.log`, all seems fine, no helpful clues. 
Only when `sudo bundle exec rake production:stop`, it shows:
```
Stopping huginn ...
ok: down: huginn-web-1: 0s, normally up
rake aborted!
'sv stop huginn-jobs-1' exited with a non-zero return value: timeout: run: huginn-jobs-1: (pid 16246) 7690867s, want down, got TERM
/home/huginn/huginn/lib/tasks/production.rake:85:in `run'
/home/huginn/huginn/lib/tasks/production.rake:77:in `block (2 levels) in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:93:in `with_retries'
/home/huginn/huginn/lib/tasks/production.rake:76:in `block in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:75:in `each'
/home/huginn/huginn/lib/tasks/production.rake:75:in `run_sv'
/home/huginn/huginn/lib/tasks/production.rake:33:in `block (2 levels) in <top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => production:stop
(See full trace by running task with --trace)
```

Is there any ways to fix this? thanks

---
The WebsiteAgent:
```json
{
  "expected_update_period_in_days": "20",
  "url": [
    "http://s.video.qq.com/get_playsource?id=3581&plat=2&type=4&data_type=3&video_type=10&year=2017&otype=json&callback=j",
    "http://s.video.qq.com/get_playsource?id=45196&plat=2&type=4&data_type=3&video_type=10&year=2017&otype=json&callback=j",
    "http://s.video.qq.com/get_playsource?id=54222&plat=2&type=4&data_type=3&video_type=10&year=2017&otype=json&callback=j"
  ],
  "type": "text",
  "mode": "on_change",
  "extract": {
    "jsondata": {
      "regexp": "^j\\((.*)\\)",
      "index": "1"
    }
  }
}
```

**Comment by dsander** [comment]
Hi @waldens,

this might be related to #1567. Does your server has enough memory to switch to the [separate background processes](https://github.com/cantino/huginn/blob/master/Procfile#L27-L31)?

DelayedJob uses `Timeout` to monitor the run time of jobs and that is not thread safe. I am suspecting that - in some cases - the exception `Timeout` raises messages with one of our threads in the threaded background process and thus preventing it from working properly.

**Comment by waldens** [comment]
Oh, I haven't searched out #1567. Seems the same problem.
I'll try separate background processes, and reply the addition info/log in that issue if it's stuck again.
Thanks @dsander .
