### ISSUE TITLE
Starting huginn with OpenRC?

### ISSUE THREAD

**Issue by 3PO** [cantino/huginn#1891]
Hi,

is there a possibility to run huginn via OpenRC?

**Comment by cantino** [comment]
I'm sure it's possible since it's just a normal Rails app, but I don't think it's something we've tried.

**Comment by 3PO** [comment]
I dont know if this is the best way, but i solved it on my Gentoo Linux as follow:

I've installed huginn in to "/opt/huginn".

I created a 3 little files to fire up Huginn:

**/opt/huginn/run_huginn.sh**

    #!/bin/bash
    
    source /etc/conf.d/huginn
    
    cd $HUGINN_DIR
    exec $RUBY $RAILS >> $LOGFILE 2>&1


**/etc/conf.d/huginn**

    # Config file for /etc/init.d/huginn
    
    HUGINN_DIR="/opt/huginn"
    source $HUGINN_DIR/.env
    
    PIDFILE="/run/huginn.pid"
    RUBY="/usr/bin/ruby22"
    RAILS="bin/rails server -p $PORT -b 0.0.0.0"
    LOGFILE="/log/huginn.log"
    HUGINN_RUN="$HUGINN_DIR/run_huginn.sh"

**/etc/init.d/huginn**

    #!/sbin/openrc-run
    
    
    depend() {
            need net
    }
    
    
    start() {
            ebegin "Starting Huginn Server"
            start-stop-daemon --start -m -p $PIDFILE --quiet -b --exec $HUGINN_RUN
            eend $?
    }
    
    
    stop() {
            ebegin "Stopping Huginn Server"
            start-stop-daemon --stop -p $PIDFILE --quiet --exec $HUGINN_RUN
            eend $?
    }

Now i can fire up and shutdown Huginn via:

    /etc/init.d/huginn start
and

    /etc/init.d/huginn stop

**Comment by dsander** [comment]
You also need a script for the background processes (`bin/threaded.rb`).

It looks like gentoo also has a package for runit, since you already have all the system package dependencies installed the manual installation guide should also work on gentoo.

**Comment by 3PO** [comment]
>You also need a script for the background processes ( bin/threaded.rb ). ...

Thanks!

I changed the files as follow and it seems working:

**/opt/huginn/run_huginn.sh**

    #!/bin/bash
    
    source /etc/conf.d/huginn
    
    cd $HUGINN_DIR
    bundle exec rails runner bin/threaded.rb &
    exec $RUBY $RAILS >> $LOGFILE 2>&1

**/etc/init.d/huginn**

    #!/sbin/openrc-run
    
    
    depend() {
    	need net
    }
    
    
    start() {
    	ebegin "Starting Huginn Server"
    	start-stop-daemon --start -m -p $PIDFILE --quiet -b --exec $HUGINN_RUN
    	eend $?
    }
    
    
    stop() {
    	ebegin "Stopping Huginn Server"
    	start-stop-daemon --stop -p $PIDFILE --quiet --exec $HUGINN_RUN
    	ps aux |grep "bin/threaded.rb" |grep -v grep |awk '{print $2 }' | while read i ; do kill $i; done
    	eend $?
    }

**Comment by alias1** [comment]
@3PO I'm going to close this, but it would be awesome if you were able to copy your steps over to the wiki or similar, in case it helps others in future!
