### ISSUE TITLE
Stripping tabs?

### ISSUE THREAD

**Issue by bobbysteel** [cantino/huginn#1893]
Using the normal liquid formatting remove and replace functions doesn't perform as expected in removing tabs. My data source has many /t characters. However using remove: "/t" and the same replace with '' both fail to remove the tabs. Any idea how to work around? There seems to be slight differences in how the liquid formatting works vs what I've found online - for example camelcase does not work here but it's listed in the link as valid... 
Thanks!

**Comment by cantino** [comment]
It should be `\t`, not `/t`. You also may need to double escape it, so `\\t`. Maybe that's the problem?

**Comment by bobbysteel** [comment]
Sorry yeah typo. Meant \t.
Do you mean double escape with single quotes or double? Think I tried both
combinations but can double check in am (flying next 8 hours)

**Comment by cantino** [comment]
Double / triple escaping the backslash may help, but it could also be something else. You may have found a bug.

**Comment by bobbysteel** [comment]
just retried it with `"\\t"`, `'\\t'`, `"\t"`, `'\t'` and none work - dry run returns this:
` "top_line": "Memphis,\t\t\t\t\t\t\t\t\t            \t\t\t            \tTN,\t\t\t            \t\t\t            \t\t\t            \tUnited States\t\t\t            \t\t          \t\t\t          \t\t          \t\t\t\t\t\t\t\t\t\t\t        \t\t\t\t        01/31/2017\t\t\t\t `

**Comment by bobbysteel** [comment]
just tried `"\\\t"` and `'\\\t'` and they also don't work. :(

**Comment by cantino** [comment]
Could you post an agent example or scenario for us to play with?

**Comment by bobbysteel** [comment]
` {
  "instructions": {
    "headline": "{{headline.text | strip_html | strip | remove: \"/\t\" }}",
    "error_status": "{{status.text | strip_html | strip | remove: \"/\t\" }}",
    "top_line": "{{top_line.text | strip_html | strip | remove: \"/\t\" }}",
    "url": "{{url}}"
  },
  "matchers": [
    {
      "path": "{{ body_text  | strip_newlines | strip}}",
      "regexp": "\\<p class=\"error\"\\>(?<text>.*?)\\<",
      "to": "status"
    },
    {
      "path": "{{ body_text  | strip_newlines | strip}}",
      "regexp": "id=\"tt_spStatus\"\\>(?<text>.*?)\\<",
      "to": "headline"
    },
    {
      "path": "{{ body_text  | strip_newlines | strip}}",
      "regexp": "<tr class=\"odd\"\\>(?<text>.*?)\\<.?tr\\>",
      "to": "top_line"
    }
  ],
  "mode": "clean"
} `
 That's the agent. For sample data to dry run, you can try any old rubbish...
`{
  "body_text": "What's This?</a></li>\r\\n\\t\\t\\t</ul>\r\\n\\t\\t</div>\r\\n\\t\\t\r\\n\\t\\t<div class=\"secBody\">\r\\n\\t\\t\\t\r\\n\\t\\t\\t\r\\n\\t\\t\\t\r\\n\r\\n\\t\\t\\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"dataTable\">\r\\n\\t\\t\\t\\t<tr>\r\\n\\t        \\t\\t<th>Location</th>\r\\n\\t        \\t\\t<th>Date</th>\r\\n\\t        \\t\\t<th>Local Time</th>\r\\n\\t        \\t\\t<th class=\"full\">Activity</th>\r\\n\\t           \\t</tr>\r\\n\\t           \\t\r\\n\\t           \\t\r\\n\r\\n\\t\\t       \\t\r\\n\\t\\t       \\t<tr class=\"odd\">\r\\n\\t\\t          \\t<td class=\"nowrap\">\r\\n\\t\\t          \\t\r\\n\\t\\t            \\t\r\\n\\t\\t              \\t\\tNashville,\r\\n\\t\\t\\t\\t\\t\\t\r\\n\r\\n\\t\\t\\t            \r\\n\\t\\t\\t            \\tTN,\r\\n\\t\\t\\t            \r\\n\r\\n\\t\\t\\t            \r\\n\\t\\t\\t            \\tUnited States\r\\n\\t\\t\\t            \r\\n\\t\\t          \\t\r\\n\\t\\t          \\t</td>\r\\n\r\\n\r\\n\\t          \\t\\t\r\\n\\t\\t\\t\\t\\t<td class=\"nowrap\">\r\\n\\t\\t\\t\\t        \r\\n\\t\\t\\t\\t        02/01/2017\r\\n\\t\\t\\t\\t        \r\\n\\t\\t\\t        </td>\r\\n\r\\n\\t          \\t\\t\r\\n\\t\\t          \\t<td class=\"nowrap\">\r\\n\\t          \\t\\t\r\\n\\t            \\t\\t3:51 A.M.\r\\n\\t          \\t\\t\r\\n\\t\\t\\t\\t\\t</td>\r\\n\r\\n\\t\\t          \\t\r\\n\\t          \\t\\t<td>Departure Scan\r\\n\\t\\t          \\t\\t\\t \r\\n     \r\\n     \r\\n          \r\\n       \r\\n      \r\\n       \r\\n      \r\\n      \r\\n   \r\\n   \r\\n    \r\\n    \r\\n    \r\\n\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t \r\\n\\t          \\t\\t</td>\r\\n\\t        \\t</tr>\r\\n\\t        \\t\r\\n\\t           \\t\r\\n\r\\n\\t\\t       \\t\r\\n\\t\\t       \\t<tr>\r\\n\\t\\t          \\t<td class=\"nowrap\">\r\\n\\t\\t          \\t\r\\n\\t\\t            \\t\r\\n\r\\n\\t\\t\\t            \r\\n\r\\n\\t\\t\\t            \r\\n\\t\\t          \\t\r\\n\\t\\t          \\t</td>\r\\n\r\\n\r\\n\\t          \\t\\t\r\\n\\t\\t\\t\\t\\t<td class=\"nowrap\">\r\\n\\t\\t\\t\\t        \r\\n\\t\\t\\t\\t        02/01/2017\r\\n\\t\\t\\t\\t        \r\\n\\t\\t\\t        </td>\r\\n\r\\n\\t          \\t\\t\r\\n\\t\\t          \\t<td class=\"nowrap\">\r\\n\\t          \\t\\t\r\\n\\t            \\t\\t2:22 A.M.\r\\n\\t          \\t\\t\r\\n\\t\\t\\t\\t\\t</td>\r\\n\r\\n\\t\\t          \\t\r\\n\\t          \\t\\t<td>Arrival Scan\r\\n\\t\\t          \\t\\t\\t \r\\n     \r\\n    \r\\n    \r\\n    \r\\n\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t \r\\n\\t          \\t\\t</td>\r\\n\\t        \\t</tr>\r\\n\\t        \\t\r\\n\\t           \\t\r\\n\r\\n\\t\\t       \\t\r\\n\\t\\t       \\t<tr class=\"odd\">\r\\n\\t\\t          \\t<td class=\"nowrap\">\r\\n\\t\\t          \\t\r\\n\\t\\t            \\t\r\\n\\t\\t              \\t\\tMemphis,\r\\n\\t\\t\\t\\t\\t\\t\r\\n\r\\n\\t\\t\\t            \r\\n\\t\\t\\t            \\tTN,\r\\n\\t\\t\\t            \r\\n\r\\n\\t\\t\\t            \r\\n\\t\\t\\t            \\tUnited States\r\\n\\t\\t\\t            \r\\n\\t\\t          \\t\r\\n\\t\\t          \\t</td>\r\\n\r\\n\r\\n\\t          \\t\\t\r\\n\\t\\t\\t\\t\\t<td class=\"nowrap\">\r\\n\\t\\t\\t\\t        \r\\n\\t\\t\\t\\t        01/31/2017\r\\n\\t\\t\\t\\t        \r\\n\\t\\t\\t        </td>\r\\n\r\\n\\t          \\t\\t\r\\n\\t\\t          \\t<td class=\"nowrap\">\r\\n\\t          \\t\\t\r\\n\\t            \\t\\t10:47 P.M.\r\\n\\t          \\t\\t\r\\n\\t\\t\\t\\t\\t</td>\r\\n\r\\n\\t\\t          \\t\r\\n\\t          \\t\\t<td>Departure Scan\r\\n\\t\\t          \\t\\t\\t \r\\n     \r\\n    \r\\n    \r\\n    \r\\n\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t \r\\n\\t          \\t\\t</td>\r\\n\\t        \\t</tr>\r\\n\\t        \\t\r\\n\\t           \\t\r\\n\r\\n\\t\\t       \\t\r\\n\\t\\t       \\t<tr>\r\\n\\t\\t          \\t<td class=\"nowrap\">\r\\n\\t\\t          \\t\r\\n\\t\\t            \\t\r\\n\r\\n\\t\\t\\t            \r\\n\r\\n\\t\\t\\t            \r\\n\\t\\t          \\t\r\\n\\t\\t          \\t</td>\r\\n\r\\n\r\\n\\t          \\t\\t\r\\n\\t\\t\\t\\t\\t<td class=\"nowrap\">\r\\n\\t\\t\\t\\t        \r\\n\\t\\t\\t\\t        01/31/2017\r\\n\\t\\t\\t\\t        \r\\n\\t\\t\\t        </td>\r\\n\r\\n\\t          \\t\\t\r\\n\\t\\t          \\t<td class=\"nowrap\">\r\\n\\t          \\t\\t\r\\n\\t            \\t\\t6:16 P.M.\r\\n\\t          \\t\\t\r\\n\\t\\t\\t\\t\\t</td>\r\\n\r\\n\\t\\t          \\t\r\\n\\t          \\t\\t<td>Origin Scan\r\\n\\t\\t          \\t\\t\\t \r\\n     \r\\n    \r\\n    \r\\n    \r\\n\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t \r\\n\\t          \\t\\t</td>\r\\n\\t        \\t</tr>\r\\n\\t        \\t\r\\n\\t           \\t\r\\n\r\\n\\t\\t       \\t\r\\n\\t\\t       \\t<tr class=\"odd\">\r\\n\\t\\t          \\t<td class=\"nowrap\">\r\\n\\t\\t          \\t\r\\n\\t\\t            \\t\r\\n\r\\n\\t\\t\\t            \r\\n\r\\n\\t\\t\\t            \r\\n\\t\\t\\t            \\tUnited States\r\\n\\t\\t\\t            \r\\n\\t\\t          \\t\r\\n\\t\\t          \\t</td>\r\\n\r\\n\r\\n\\t          \\t\\t\r\\n\\t\\t\\t\\t\\t<td class=\"nowrap\">\r\\n\\t\\t\\t\\t        \r\\n\\t\\t\\t\\t        01/31/2017\r\\n\\t\\t\\t\\t        \r\\n\\t\\t\\t        </td>\r\\n\r\\n\\t          \\t\\t\r\\n\\t\\t          \\t<td class=\"nowrap\">\r\\n\\t          \\t\\t\r\\n\\t            \\t\\t10:30 P.M.\r\\n\\t          \\t\\t\r\\n\\t\\t\\t\\t\\t</td>\r\\n\r\\n\\t\\t          \\t\r\\n\\t          \\t\\t<td>Order Processed: Ready for UPS\r\\n\\t\\t          \\t\\t\\t \r\\n     \r\\n    \r\\n    \r\\n    \r\\n\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t \r\\n\\t          \\t\\t</td>\r\\n\\t        \\t</tr>\r\\n\\t        \\t\r\\n\\t\\t\\t</table>\r\\n\\t\\t</div>\r\\n\\t\\t\r\\n\\t\\t</fieldset>\r\\n\\t</div>\r\\n\\t\r\\n\r\\n\r\\n\\t\\t\r\\n\r\\n\r\\n\r\\n<script language=\"javascript\" type=\"text/JavaScript\">\r\\n\r\\n\\t$(document).ready(function() {\r\\n\r\\n\r\\n\\t\r\\n\r\\n\r\\n\\t   $('#collapse3 h4').click(function(){\r\\n\\t     \r\\n\\t     $('.module3 div.secBody').toggle();\r\\n\\t     \\t  \r\\n\\t     $('.module4 div.secBody').toggle();\r\\n\\t     $('.module4 div.secBody').toggle();\r\\n\r\\n\\t\\t\\t $('#collapse3 h4').toggleClass('collapseIcon').toggleClass('expandIcon');\r\\n\\t\\t\\t $('#collapse3').toggleClass('collapsed').toggleClass('');\r\\n\\t\\t  \r\\n\\t\\t\\t \r\\n\\t   });\r\\n\r\\n\r\\n\r\\n });\r\\n\r\\n</script>\r\\n\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t\r\\n\r\\n\r\\n\r\\n\r\\n\r\\n\r\\n\r\\n\r\\n\r\\n\r\\n\r\\n\r\\n\r\\n\r\\n\r\\n\r\\n\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<div class=\"secLvl gradient gradientGroup7 module1\">\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<fieldset>\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<div id=\"collapse1\" class=\"secHead collapsible clearfix\">\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<h4 class=\"btnlnkL collapseIcon\">Additional Information</h4>\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t</div>\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\r\\n\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<div class=\"secBody\">\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t<dl class=\"outHozFixed1 clearfix\">\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t    \r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t        \r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t \\t\\t             \r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t             \r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t           \\t\\t<dt><label for=\"\">Shipment Category: </label></dt>\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t             \r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t            <dd>Package</dd>\r\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t\\t",
  "url": "https://wwwapps.ups.com/WebTracking/track?track=yes&trackNums="
} `

**Comment by cantino** [comment]
Wow, I have no idea. @dsander might have a guess; I haven't really done much filtering with Liquid.

**Comment by dsander** [comment]
@bobbysteel  The `strip_newlines` filter does not remove the linebreaks?

Maybe this xpath expression works: `translate(normalize-space(.), ' ', '')`

**Comment by bobbysteel** [comment]
@dsander it's the tabs not the line breaks I'm concerned with. The rest are
fine. Using translate though has no effect on the tabs.

**Comment by dsander** [comment]
`regex_replace` seems to work:
```
{
  "expected_update_period_in_days": "2",
  "url": "https://wwwapps.ups.com/WebTracking/track?track=yes&trackNums=",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": "dl:nth-child(2) label",
      "value": "."
    }
  },
  "template": {
    "test": "{{url | strip_newlines | regex_replace: '\\t', '' }}"
  }
}
```

**Comment by bobbysteel** [comment]
That works because that extraction doesn't capture the full HTML. I need to extract multiple optional HTML tags which I can only see by returning the value as `./node()` which adds in the tabs. Regexp replace doesn't work via that method.

**Comment by dsander** [comment]
I don't understand, liquid filter operate on text, it should not matter how much of the HTML is returned. When I extract with `./node()` the tabs are removed as well. Can you share the options of your `WebsiteAgent`?

**Comment by bobbysteel** [comment]
This also has the same issue - see with test tracking number:
```
{
  "expected_update_period_in_days": "2",
  "url": "https://wwwapps.ups.com/WebTracking/track?track=yes&trackNums=1ZW0594W9093170735",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": "fieldset:nth-child(1)",
      "value": "."
    }
  },
  "template": {
    "test": "{{url | strip_newlines | regex_replace: '\\t', '' }}"
  }
}
```

**Comment by dsander** [comment]
Seems to be working for me, you need to use the `test` key of the event:
```
{
  "url": "<fieldset>\n\t\t\t<div class=\"secBody\">\n\t\t\t\t<div class=\"secLvl marginBegin clearfix \">\n\t\t\t\t<fieldset>\n\t\t\t\t\t<div class=\"secHead clearfix\">\n\t\t\t\t\t\t<h4>\t\t\t\t\n\t\t\t\t\t\t<\/h4>\t\n\t\t\t\t\t<\/div>\n\t\t\t\t\t<div class=\"secBody\">\n\t\t\t    \t\n\t\t\t    \t\n\t\t\t\t\t\t<h5>Other UPS Sites:<\/h5>\n\t\t\t\t\t     \t\t\n\t\t\t\t\t     \t\n\t\t\t\t\t     \t\t\n\t\t\t\t\t     \t\n\t\t\t\t\t     \t\t\n\t\t\t\t\t     \t\n\t\t\t\t\t     \t\t\n\t\t\t\t\t     \t\n\t\t\t\t\t<select name=\"dropdownList\" id=\"footer_dd_form_0\" class=\"maxwidthFix\" size=\"1\" onchange=\"javascript:footerDropdownLinksHandler('footer_dd_form_0')\">\n\t\t\t\t\t\t\t\t<option value=\"\">Select One<\/option>\n<option value=\"http://compass.ups.com\">UPS Compass (English only)<\/option>\n\t\t\t\t\t\t\t     \t\t\n\t\t\t\t\t\t\t     \t\n<option value=\"https://www.ups.com/golf\">UPS Golf Sponsorships<\/option>\n\t\t\t\t\t\t\t     \t\t\n\t\t\t\t\t\t\t     \t\n<option value=\"http://www.investors.ups.com\">Investors (English only)<\/option>\n\t\t\t\t\t\t\t     \t\t\n\t\t\t\t\t\t\t     \t\n<option value=\"http://www.upsjobs.com/\">UPS Jobs<\/option>\n\t\t\t\t\t\t\t     \t\t\n\t\t\t\t\t\t\t     \t\n\t\t\t\t\t<\/select>\n\t\t\t\t\t<script language=\"JavaScript1.2\" type=\"text/javascript\">\t\t\t\t\t\t\n\t\t\t\t\t function footerDropdownLinksHandler(formName){\t\t\t\t\t\n\t\t\t\t\t var dropdwnObj = document.getElementById(formName);\t\t\t\t\n\t\t\t\t\t    if ( dropdwnObj.options[dropdwnObj.selectedIndex].value != \"\" ){\n\t\t\t\t\t        window.open(dropdwnObj.options[dropdwnObj.selectedIndex].value,'_blank');\n\t\t\t\t\t   }\n\t\t\t\t\t }\n\t\t\t\t\t<\/script>\n\t\t\t\t\t\t<dt><label><br><\/label><\/dt>\n\t\t\t  \n\t\t  \n\t\t<img src=\"/img/en/gb/solvers.png\" width=\"230\" height=\"15\" alt=\"United Problem Solvers\" border=\"0\">\n\t\t\t\t\t<\/div>\n\t\t        <\/fieldset>\n\t\t\t\t<\/div>\t\t\n\t\t\t<\/div>\n\t\t<\/fieldset>",
  "test": "<fieldset><div class=\"secBody\"><div class=\"secLvl marginBegin clearfix \"><fieldset><div class=\"secHead clearfix\"><h4><\/h4><\/div><div class=\"secBody\">        <h5>Other UPS Sites:<\/h5>                                        <select name=\"dropdownList\" id=\"footer_dd_form_0\" class=\"maxwidthFix\" size=\"1\" onchange=\"javascript:footerDropdownLinksHandler('footer_dd_form_0')\"><option value=\"\">Select One<\/option><option value=\"http://compass.ups.com\">UPS Compass (English only)<\/option>          <option value=\"https://www.ups.com/golf\">UPS Golf Sponsorships<\/option>          <option value=\"http://www.investors.ups.com\">Investors (English only)<\/option>          <option value=\"http://www.upsjobs.com/\">UPS Jobs<\/option>          <\/select><script language=\"JavaScript1.2\" type=\"text/javascript\"> function footerDropdownLinksHandler(formName){ var dropdwnObj = document.getElementById(formName);    if ( dropdwnObj.options[dropdwnObj.selectedIndex].value != \"\" ){        window.open(dropdwnObj.options[dropdwnObj.selectedIndex].value,'_blank');   } }<\/script><dt><label><br><\/label><\/dt>    <img src=\"/img/en/gb/solvers.png\" width=\"230\" height=\"15\" alt=\"United Problem Solvers\" border=\"0\"><\/div>        <\/fieldset><\/div><\/div><\/fieldset>"
}
```

**Comment by bobbysteel** [comment]
ah i see, that does work, i missed the scroll down earlier looking at the url key. so this solves it. thanks!

**Comment by dsander** [comment]
Nice! I also had to look at the generated events and missed it in the dry-run response :)
