### ISSUE TITLE
Cannot send mails 

### ISSUE THREAD

**Issue by 3PO** [cantino/huginn#1894]
Hi, 

i seems, that Mailing is not working in huginn?

i've created a "Testuser" and to check if mailing is working, i clicked on,

> Forgot your password?

after input the username i got this issue:

> We're sorry, but something went wrong.

This is the mailing part in ".env"

    SMTP_DOMAIN=gmx.de
    SMTP_USER_NAME=foobar@gmx.de
    SMTP_PASSWORD=321abc
    SMTP_SERVER=mail.gmx.net
    SMTP_PORT=465
    SMTP_AUTHENTICATION=login
    SMTP_ENABLE_STARTTLS_AUTO=true

And this is the issue form the Log:

    I, [2017-02-01T14:15:00.585337 #2650]  INFO -- : [6f7ee794-7fe7-4f6c-af61-e3540919afde] Started GET "/users/password/new" for 192.168.177.45 at 2017-02-01 14:15:00 +0100
    I, [2017-02-01T14:15:00.586472 #2650]  INFO -- : [6f7ee794-7fe7-4f6c-af61-e3540919afde] Processing by Devise::PasswordsController#new as HTML
    I, [2017-02-01T14:15:00.588533 #2650]  INFO -- : [6f7ee794-7fe7-4f6c-af61-e3540919afde]   Rendering devise/passwords/new.html.erb within layouts/application
    I, [2017-02-01T14:15:00.591856 #2650]  INFO -- : [6f7ee794-7fe7-4f6c-af61-e3540919afde]   Rendered devise/shared/_links.html.erb (0.7ms)
    I, [2017-02-01T14:15:00.591993 #2650]  INFO -- : [6f7ee794-7fe7-4f6c-af61-e3540919afde]   Rendered devise/passwords/new.html.erb within layouts/application (3.3ms)
    I, [2017-02-01T14:15:00.593708 #2650]  INFO -- : [6f7ee794-7fe7-4f6c-af61-e3540919afde]   Rendered layouts/_navigation.html.erb (0.8ms)
    I, [2017-02-01T14:15:00.594071 #2650]  INFO -- : [6f7ee794-7fe7-4f6c-af61-e3540919afde]   Rendered layouts/_messages.html.erb (0.1ms)
    I, [2017-02-01T14:15:00.594472 #2650]  INFO -- : [6f7ee794-7fe7-4f6c-af61-e3540919afde] Completed 200 OK in 8ms (Views: 6.4ms | ActiveRecord: 0.0ms)
    I, [2017-02-01T14:15:06.750571 #2650]  INFO -- : [2bfa901d-12c0-4437-815b-ee243b93bad5] Started POST "/users/password" for 192.168.177.45 at 2017-02-01 14:15:06 +0100
    I, [2017-02-01T14:15:06.751708 #2650]  INFO -- : [2bfa901d-12c0-4437-815b-ee243b93bad5] Processing by Devise::PasswordsController#create as HTML
    I, [2017-02-01T14:15:06.751804 #2650]  INFO -- : [2bfa901d-12c0-4437-815b-ee243b93bad5]   Parameters: {"utf8"=>"?", "authenticity_token"=>"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=", "user"=>{"login"=>"Testuser"}, "commit"=>"Send me reset password instructions"}
    I, [2017-02-01T14:15:06.771307 #2650]  INFO -- : [2bfa901d-12c0-4437-815b-ee243b93bad5]   Rendering devise/mailer/reset_password_instructions.html.erb
    I, [2017-02-01T14:15:06.771877 #2650]  INFO -- : [2bfa901d-12c0-4437-815b-ee243b93bad5]   Rendered devise/mailer/reset_password_instructions.html.erb (0.4ms)
    I, [2017-02-01T14:15:16.860350 #2650]  INFO -- : [2bfa901d-12c0-4437-815b-ee243b93bad5] Sent mail to foobar@gmx.de (10087.6ms)
    I, [2017-02-01T14:15:16.860718 #2650]  INFO -- : [2bfa901d-12c0-4437-815b-ee243b93bad5] Completed 500 Internal Server Error in 10109ms (ActiveRecord: 0.0ms)
    F, [2017-02-01T14:15:16.862000 #2650] FATAL -- : [2bfa901d-12c0-4437-815b-ee243b93bad5]   
    F, [2017-02-01T14:15:16.862066 #2650] FATAL -- : [2bfa901d-12c0-4437-815b-ee243b93bad5] EOFError (end of file reached):
    F, [2017-02-01T14:15:16.862119 #2650] FATAL -- : [2bfa901d-12c0-4437-815b-ee243b93bad5]   
    F, [2017-02-01T14:15:16.862165 #2650] FATAL -- : [2bfa901d-12c0-4437-815b-ee243b93bad5] config/initializers/silence_worker_status_logger.rb:3:in `call'

Where is my fault?

**Comment by dsander** [comment]
This seems to be an issue specific to GMX: http://stackoverflow.com/questions/21768973/gmx-ruby-mail-smtp-end-of-file-reached
Years ago they had something called "POP/IMAPE before SMTP", which means that the same user/ip has to fetch mails before being able to use SMTP.
Maybe this article helps: https://karussell.wordpress.com/2008/10/07/very-small-hints-for-actionmailer/

**Comment by 3PO** [comment]
> [...] Maybe this article helps ...

Not really. :(
I dont speak ruby.

**Comment by dsander** [comment]
Did you try setting the port to `25` like suggested in the blog post? That seems to be the only real difference to your settings.

**Comment by 3PO** [comment]
The blog is from 2008, gmx doesnt support unencrypted mail anymore.

--> https://hilfe.gmx.net/pop-imap/pop3/serverdaten.html

**Comment by 3PO** [comment]
With the followig Settings it it working with "https://www.gmx.net/".

    SMTP_DOMAIN=gmx.de
    SMTP_USER_NAME=foobar@gmx.de
    SMTP_PASSWORD=321abc
    SMTP_SERVER=mail.gmx.net
    SMTP_PORT=587
    SMTP_AUTHENTICATION=login
    SMTP_ENABLE_STARTTLS_AUTO=true


The "SMTP_PORT" was wrong.

Thanks for the hint and sorry for the noise.

**Comment by dsander** [comment]
Nice! 😄

**Comment by mightymt** [comment]
@3PO Thanks a lot, this actually helped me today.

One thing I'd like to add is, that I also had to set `EMAIL_FROM_ADDRESS` to the same value as `SMTP_USER_NAME`. Otherwise I always got the following error:

`550-Requested action not taken: mailbox unavailable`
