### ISSUE TITLE
Email confirmation fails

### ISSUE THREAD

**Issue by Mirclus** [cantino/huginn#1895]
I just updated my instance (from 410ece8 to 0fccdc8) and enabled `REQUIRE_CONFIRMED_EMAIL=true`. My user didn't have his email confirmed before, so on login I get an error:

> You have to confirm your email address before continuing.

So I follow the `Didn't receive confirmation instructions?` and enter my email address. But instead of sending an confirmation mail, I just get an error in the form:

> 1 error prohibited this user from being saved:
>
>    Login can't be blank

**Comment by dsander** [comment]
Hi @Mirclus,

thank you for reporting the issue. #1897 should fix the problem.
