### ISSUE TITLE
Cannot login in successfully

### ISSUE THREAD

**Issue by Voleking** [cantino/huginn#1896]
I built it on my VPS and It can be visited at https://huginn.voleking.me now.
However I cannot login in successfully with USERNAME `admin` and PASSWORD `password` ( I  haven't changed it before).

**Comment by cantino** [comment]
`bundle exec rake db:seed`?

**Comment by cantino** [comment]
Oh, it looks like the site is down. Is the Huginn process running on the server?

**Comment by Voleking** [comment]
@cantino Yes, please wait a minute. I'm trying to fit it by myself and now it may takes some time to reproduce this issue

**Comment by Voleking** [comment]
@cantino My site is up now! Thx.

**Comment by Voleking** [comment]
This information may help. When I reboot my VPS, I got this issue #1618: Huginn failed to restart.
`/etc/runit/2 &` don't work now and I reinstall runit to fix it.

**Comment by Voleking** [comment]
There are many issues install from source. I would like to use docker.
@cantino Thx

**Comment by cantino** [comment]
Sorry it was complicated. I agree Docker is a better solution than installing from source these days.

**Comment by Voleking** [comment]
Yes, install with docker is much more easier and I can explore Huginn now! BTW, Thanks a lot.
