### ISSUE TITLE
Newbie Question - HTML encoded within XML

### ISSUE THREAD

**Issue by mc0e** [cantino/huginn#1898]
I want to pull some data out of HTML in the description fields of items in an RSS feed.

I can pull out the description OK, as per the example.  How do I then remove the ampersand encoding, and parse the result as HTML?  Where do I look for answers to such things?

**Comment by cantino** [comment]
You can use the `unescape` [liquid filter](https://github.com/cantino/huginn/wiki/Formatting-Events-using-Liquid#filters-added-by-huginn) and then send it to a WebsiteAgent for parsing.

**Comment by dsander** [comment]
I am closing this issue. Please feel free to reopen if you need further assistance!
