### ISSUE TITLE
502 bad gateway Nginx

### ISSUE THREAD

**Issue by BasharAG** [cantino/huginn#1900]
Hello!

I launched an entirely new instance just for huginn, and all the installation steps went by very smoothly; however, when I tried accessing it via my browser, I got a Nginx error 502 'bad gateway'. Any suggestions? 

Please note im very new to programming. 

Here is what I found in my Nginx error log:
2017/02/04 19:04:56 [error] 8962#8962: *1 connect() to unix:/home/huginn/huginn$
2017/02/04 19:04:56 [error] 8962#8962: *1 connect() to unix:/home/huginn/huginn$

**Comment by Voleking** [comment]
What's your serve memory?
In my case, It cannot work perfectly both nginx and huginn on a 512M VPS without any optimization.
I got 502 bad gateway.

**Comment by bobbysteel** [comment]
did you edit your Procfile as in the instructions to choose one pair of settings there?

**Comment by dsander** [comment]
Please post the contents of all logs listed in the [troubleshooting section](https://github.com/cantino/huginn/blob/master/doc/manual/installation.md#troubleshooting). `502` errors usually mean either the unicorn server is not running or not configured properly.

**Comment by dsander** [comment]
I am closing this issue. Please feel free to reopen if you need further assistance!
