### ISSUE TITLE
Feathub for requests?

### ISSUE THREAD

**Issue by alias1** [cantino/huginn#1903]
In the past we've used the issue tracker for feature/agent requests, ideas, suggestion, etc. And while in some places it's good (those that get actively discussed/worked on), in a lot of other ways it tends to clutter up the issues with things that might not have much interest, or that just end up falling to the wayside.

I was thinking it would be cool to make use of a 'proper' feature tracker, one that lets users vote, etc.

Just stumbled upon http://feathub.com/ through another project, and thinking maybe it could be used for this.

Interested to hear everones thoughts. (ping @cantino, @knu, @dsander, etc)

**Comment by cantino** [comment]
I'd be open to it.

**Comment by dsander** [comment]
That looks interesting, does an issue need to have a specific tag or are all listed in feathub?

The only problem I see is our agent suggestion issue, we would need to split that up again which would kind of bloat the issue list.

**Comment by alias1** [comment]
It seems that GH issues are independent of FH requests.

Quick example, created a test issue, and a test feature independently. Neither appear in the other:
* http://feathub.com/alias1/chrome-NewWindowWithTabsToRight
* https://github.com/alias1/chrome-NewWindowWithTabsToRight/issues

**Comment by knu** [comment]
I didn't know of FeatHub, but GitHub's issue tracker currently has a `sort by most reactions` feature that we could use to see a popularity rating of existing issues at a glance.

**Comment by dsander** [comment]
I am not sure how I feel about the features being completely separated from GitHub issues. It would allow us to clean up the issue list (I'd guess at least half of the open issues are feature requests of some sort). On the other hand we would need to manually copy and paste dozens of issues to features and kind of loose the nice references we have on GitHub.

An other option could be the "new" projects feature of GitHub.

**Comment by alias1** [comment]
@knu I only came across it recently via a different project and thought it looked kind of cool.

@dsander If we were to go forward with this, i'd probably be happy to do a lot of the migration work. As part of that, if they have a current issue, I would link to that from feathub, as well as the initial description. Then if any of the features were going to be worked on that had an original issue, we could reopen it/reference it from the PR. Which other references would you see being lost?

I haven't looked into the projects feature, but definitely open to exploring other ideas. My main motivation is that every time I come back to this project, the issue list always seems pretty daunting, especially since a lot of them are suggestions that may or may not ever actually get worked on.

**Comment by cantino** [comment]
What do you see as the main benefits over keeping stuff in GitHub as-is?

**Comment by alias1** [comment]
I suppose my initial feeling was around clearing up the issues so there are less open ones, and having a 'better' voting system for them. Though on further thought, and with the ideas raised here, i'm starting to wonder if you can't get that same effect 'good enough' through GH directly.

**Comment by cantino** [comment]
Yea, I do think there would be benefit to keeping everything in one place (GitHub). The issues have gotten a bit overloaded recently, but we can work to reduce them.

**Comment by alias1** [comment]
That's fair.

Get Outlook for iOS




On Thu, Feb 9, 2017 at 4:45 AM +1100, "Andrew Cantino" <notifications@github.com> wrote:












Yea, I do think there would be benefit to keeping everything in one place (GitHub). The issues have gotten a bit overloaded recently, but we can work to reduce them.
