### ISSUE TITLE
Worker gets completely stuck daily at the same time

### ISSUE THREAD

**Issue by Mirclus** [cantino/huginn#1904]
This may be related to #1567.

I updated my Huginn instance from a version of 2016-12-05 to the current one end of January (around 2017-01-25, unfortunately I don't have an exact time or commit hash).

After the update, my huginn instance stopped working. It took me some days to recognize and I didn't think much about it. I just updated again (at 2017-02-02 11:00 UTC) and restarted the server.

This time I actually monitored closer and it failed again. I set up a monitoring service which Huginn pushes an event to every hour. As the fail occurred at the same time in multiple consecutive days I investigated further.

I also updated multiple times to see if there were any fixes. The current running version is 97db476 with #1892.

The interesting part is that the service fails daily at the same time: 00:05 UTC+1. The job overview in the web interface shows *Event propagation* every time. The log isn't that helpful either:

> Error while reserving job: could not obtain a connection from the pool within 5.000 seconds

I took a thread dump some days ago, I hope it helps you. Also, I piped the stderr of the worker process, which shows that the first error yesterday actually occurred at 2017-02-05 20:08:55 +0100.
I also see error 420 from Twitter (which means I get rate limited).

You can find the log files at https://gist.github.com/Mirclus/d7495673353180537748e06c69ea0b0b.

If you need more information, just tell me.

Regarding the running agents:
- Twitter Stream agent (every 5 hours) with 9 searches (one 10k, three 1k, two 100, two 10, one 1 event(s) per 5 hours)
- 1 Twitter User agent (every 10 mins, between 0 and 20 tweets per day)

**Comment by dsander** [comment]
Hi @Mirclus,

thank you for the detailed logs! Your problem might have a simple solution. 
What is your current `DATABASE_POOL` setting in the `.env` file? Our current default of 20 might be too low. I am using `30` with a few TwitterStreamAgents. Remember to run `sudo bundle exec rake production:export` after making changes to the `.env` file

**Comment by Mirclus** [comment]
Thank you. That seems to fix it.

**Comment by dsander** [comment]
Great! What was your previous setting? I am wondering if we need to increase the default further.

**Comment by Mirclus** [comment]
I missed 6fb8fe22 during an update, so it was still 10.

**Comment by dsander** [comment]
Oke, thanks!

**Comment by virtadpt** [comment]
It may not be a useful data point, but I ran into this two days ago.  A full reboot and restart cleared things out.  It may have been two Website Agents getting hung up, I haven't had time to dig into it, but I'll keep watch for a recurrence just in case the data is helpful somehow.
