### ISSUE TITLE
Huginn agent to filter data based on non empty value

### ISSUE THREAD

**Issue by neethkrish** [cantino/huginn#1905]
Hi,

Is there a way to track those data and forward them to another service depending on , whether  a certain field within the data has non empty value..

For example consider a case where i have the following event body generated from one of the agents,

    {
        url": "",
	"category": "",
	"twitterid": "",
	"author": "",
	"sharedBy": "",
	"created_at": "Sat Feb 08 04:28:22 +0000 2016",
	"id": 804905091597598720,
	"id_str": "804905091597598720",
	"text": "tweet one",
	"source": "\u003ca href=\"http://twitter.com\" rel=\"nofollow\"\u003eTwitter Web    Client\u003c/a\u003e",
	"truncated": false,
	"in_reply_to_status_id": null,
	"in_reply_to_status_id_str": null,
	"in_reply_to_user_id": null,
	"in_reply_to_user_id_str": null,
	"in_reply_to_screen_name": null
    }

I need to forward this message to another service if and only if , say the field 'text' is non empty (example is given only to illustrate the scenario ) .  I am aware of event triggering agents , but could not find a way to put them to use in this scenario. What would be value to be compared with..if am using trigger agents. Please suggest a way.. 

Thanks in advance.

**Comment by irfancharania** [comment]
What about a trigger agent with a rule like this to not match empty values?

```json
"type": "!regex",
"value": "^$",
"path": "text"
```

**Comment by neethkrish** [comment]
yes that works fine...thanks
