### ISSUE TITLE
New agent class not defined, not being run

### ISSUE THREAD

**Issue by sentience** [cantino/huginn#1906]
In [agent.rb, line 421](https://github.com/cantino/huginn/blob/master/app/models/agent.rb#L421):

```ruby
        next unless const_defined?(type)
```

This line causes Huginn to skip running checks for any agents whose classes have not yet been loaded by the background jobs process (or which do not exist).

I’ve created a new agent class (`Agents::TwitterListAgent`, implemented in app/models/agents/twitter_list_agent.rb), but because of the above line, checks for it are not being scheduled at all.

Is there something else I am supposed to do when creating a new agent class to guarantee it is loaded by the background jobs process?

**Comment by sentience** [comment]
I’m currently working around this by manually running my agent with **Actions → Run** the first time. This is enough to force the background jobs process to load my agent class, and from then on it schedules its checks correctly.

**Comment by cantino** [comment]
Hey @sentience, that's odd, I've never had issues with that line. I assume you've restarted the background jobs process after adding the code for your new Agent?

**Comment by sentience** [comment]
Yep I have. Every time I restart the server, I need to run the agent manually once before it will be scheduled automatically.

**Comment by cantino** [comment]
That's very strange. Could I see the source of your Agent to see if anything might be going on there?

**Comment by sentience** [comment]
Here’s the agent as it currently stands (I still need to write a spec for it): https://github.com/sentience/huginn/blob/2293ad252113e9d7b12201ffedba8474cda9d964/app/models/agents/twitter_list_agent.rb

**Comment by sentience** [comment]
Actually, I’m pretty sure it’s nothing to do with my new agent. I’m seeing the same behaviour using an existing agent. If I set up a `TwitterUserAgent` to send events to a `PushoverAgent`, the `TwitterUserAgent` doesn’t start running on its assigned schedule until I run it manually once first.

**Comment by sentience** [comment]
I doubt it’s relevant, but I upgraded the `eventmachine` gem to 1.0.9.1 (currently 1.0.7 in Gemfile.lock) in order to get Huginn to bundle on macOS (see https://github.com/eventmachine/eventmachine/issues/643). That’s the only thing I can think I would be doing differently from anyone else.

**Comment by dsander** [comment]
You probably can work around this by setting [`eager_load`](https://github.com/cantino/huginn/blob/master/config/environments/development.rb#L17) to `true` in development. I think we either need to set that in the threaded initializer or force the auto loading of every agent class.

**Comment by sentience** [comment]
@dsander Good to know, thanks!

**Comment by cantino** [comment]
Ah, so in production it should be okay since I think eager_load would be on.
