### ISSUE TITLE
erase memory of agent with an option or via commander agent?

### ISSUE THREAD

**Issue by githubkoma** [cantino/huginn#1908]
In Addition to "ability to erase memory #802":
Is it possible to erase memory of agent with an option or via commander agent?

I have an RSS Agent where option "mode": "all" is not possible. But i want it to create events every time, when it grabs entries. Despite the Agent already had those entries already in memory..

**Comment by dsander** [comment]
Hi @githubkoma,

I don't think we have a way to manipulate the memory of an other Agent at the moment. Do you have a way to work around the fact that the `RSSAgent` does not have a `all` mode?

**Comment by githubkoma** [comment]
Okay thanks, and thanks for this great project here.
I am now using the Website Agent in XML Mode to accomplish this. It has the ```all``` mode.
See there: https://github.com/cantino/huginn/wiki/Agent-configuration-examples#itunes-trailers
