### ISSUE TITLE
is it possible to make RSS/Website Agent/... receive events, to pass Parameters?

### ISSUE THREAD

**Issue by githubkoma** [cantino/huginn#1909]
Is it possible to make RSS/Website Agent/... receive events, to pass Parameters?
E.g.: I would like to have a incoming webhook send some data to an Website/RSS/... Agent. It should include some data coming from the hook agent. That data (like a username) should then be merged into every event that the Website/RSS/... Agent produces.

That way i can give that events back to an email agent for example, which that way directly knows where to send the email with the output to..

**Comment by dsander** [comment]
Unfortunately there is no easy way to do this, it might be possible by using a CommanderAgent. Send the Event from your `WebsiteAgent` to the `RSSAgent` and a `Commander`, then use the `Commander` to configure the Agent that will receive the data from the `RSSAgent` and set the username based on the `WebsiteAgent` event.

**Comment by githubkoma** [comment]
Thanks, i now pursued that solution, despite i earlier found it a bit too complicated and a bit error-prone.
Error-prone because of the timing in which multiple users asking the webhook, which then could get confused. Depending on the timing it could confuse whom to send which answer.

But for now its okay i think.. Using Huginn for a bot-like interaction ;)

But its now like:
  * incoming webhook (including a parameter and recipient for the answer)
  * Commander agent to change the recipient on the email-agent
  * Commander agent to set the Trigger-Filter according to the first parameter
  * RSS-Agent that gets the data
  * Trigger-Filter that filters the results
  * Email-Agent that sends the answer back to the user/recipient
