### ISSUE TITLE
The single-table inheritance mechanism failed to locate the subclass: 'Agents::BeeperAgent'

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#1910]
Some of my agent networks that use the Beeper Agent as their output started to throw errors after I upgraded to commit 3dda1ffb632c6c820aa5b468269559c0bd19f89a during routine maintenance a few days ago.  The outputs appear to be blocked and the jobs are showing up as failed and are piling up in the Jobs list; I can delete the failed jobs normally.  I'm not entirely sure what's going on with Beeper Agent though I have noticed anomalous behavior (many fewer alerts than before, probably owing to this bug, some events are emitted five or six times in a row without change).

Thinking about it a little, I shouldn't be getting these at all because I'm using Pushover these days (through Website Agent, because I forgot about the Pushover Agent).

Here's the stack trace from one of the dead agents: http://pastebin.com/VKaTXr0U

Could something be triggering these agents by accident?

**Comment by dsander** [comment]
We removed the `BeeperAgent` from Huginn some time ago. When you open your Agent list you should get a warning that the code for the Agent is missing and remove those Agent. After removing them the error messages should go away.

**Comment by virtadpt** [comment]
I did as you said, got the warning window (which seems to have deleted all of the remaining Beeper Agents), and then deleted the Manual test agents I'd set up for debugging.  I think everything should be good now.  If, after a week, nothing explodes, I'll close this ticket.

**Comment by alias1** [comment]
@virtadpt I'll close this for now, but if there's an issue we can reopen it :)

**Comment by virtadpt** [comment]
Yup, close it.  Everything seems fine.

**Comment by cantino** [comment]
Great!
