### ISSUE TITLE
Switching to a deactivated account

### ISSUE THREAD

**Issue by camilstaps** [cantino/huginn#1914]
When a user account is deactivated, it is not possible to switch to it (as an administrator). However, when you then login to your own (admin) account again, there is an option 'Switch Back to Admin User' in the account menu.

I would suggest to do one of the following:

- Make it possible to switch to deactivated accounts
- Remove the option from the menu

Depending on that choice, this is either a bug or an enhancement.

This has in no way a high priority, I would say, but I still wanted to report it.

**Comment by dsander** [comment]
Tahsnk for reporting the issue @camilstaps.

I think removing the become user link would be easier, as it does not require messing with Devise which probably prevents the login as a deactivated user.

**Comment by cantino** [comment]
This should be fixed now thanks to @aeter.
