### ISSUE TITLE
input agent for website agent and RSS data output agent [help-wanted]

### ISSUE THREAD

**Issue by ronajon** [cantino/huginn#1915]
i'm using the website agent (that extracts values with xpath) and RSS data output agent to create a RSS feed on a dutch sort of craigslist site. 
if i want to search for more items on the site, i'll clone the website agent, change the querystring part of the url and connect that new agent tot the existing data output agent. So i have now multiple cloned website agents where only the url is different.  

is it possible to put another agent (with schedule) before the website agent? That agent should then send only the url to one single website agent for parsing the URL and sending the data forward to the data output agent?

**Comment by cantino** [comment]
The WebsiteAgent can fetch based on an event, yes. To fetch the url in the Event’s url key, for example, set `url_from_event` to `{{ url }}`.

**Comment by ronajon** [comment]
found the url_from_event option, but i don't know how to pass multiple urls 
i read somewhere that i can be done in an array, or is there another event that can be the source for my event ?

**Comment by cantino** [comment]
Nice! 👍 

Please re-open if you have further questions.
