### ISSUE TITLE
Help with Post Agent and Discord WebHook

### ISSUE THREAD

**Issue by frumpymoons** [cantino/huginn#1918]
I managed to create an website agent that gets new posts from a reddit subreddit and a Trigger Agent for a specific keyword. They both work and are creating events.
Here is the Trigger Agent:
```
{
  "expected_receive_period_in_days": "2",
  "keep_event": "true",
  "rules": [
    {
      "type": "regex",
      "value": "...",
      "path": "title"
    },
    {
      "type": "regex",
      "value": "...",
      "path": "author"
    }
  ],
  "message": "link"
}
```

I have problems with the Post Agent. Since I have no experience with this I am a bit lost here.
This is pretty much the default config. The response says "cannot send empty message".
```
{
  "post_url": "https://discordapp.com/api/webhooks/...",
  "expected_receive_period_in_days": "1",
  "content_type": "json",
  "method": "post",
  "payload": {
    "url": "{{link}}"
  },
  "emit_events": "true",
  "no_merge": "true"
}
```
Can someone help me out here, or point me in the right direction?

**Comment by dsander** [comment]
Hi @frumpymoons,

the `PostAgent` in your current configuration will make a `json` encoded request to the URL with the body being `{"url": "contents of the link key in the received event"}`. 
I looked at te discord webhook documentation (https://discordapp.com/developers/docs/resources/webhook#execute-webhook), i think the payload should look something like this:
```

  "payload": {
    "content": "{{title}}",
    "username": "{{author}}"
  },
```

**Comment by frumpymoons** [comment]
Thanks, that already did the trick 👍
