### ISSUE TITLE
how to use "url_from_event"?

### ISSUE THREAD

**Issue by megaxox** [cantino/huginn#1927]
I have tried the following ways, but don't work.
"url": "{{url}}",
"url_from_event": "{{ url }}",

```

{
  "expected_update_period_in_days": "2",
  "url_from_event": "{{ url }}",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "fulltext": {
      "css": ".content_font.fontsize.immmge",
      "value": "."
    }
  }
}
```

result:
[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Dry Run finished

**Comment by dsander** [comment]
Hi @megaxox,

what is the event you are using to dry run the Agent? With `{"url": "http://www.google.com" }` it should make request to google.com.

**Comment by megaxox** [comment]
@dsander 
The events come from a RSS agent and another website agent.
It works well with a specific url.

**Comment by dsander** [comment]
How is the format of those events? You can check that either in the dry run modal of your `WebsiteAgent` or in the event tab of the two source Agents.

**Comment by megaxox** [comment]
@dsander 
`{
  "id": "http://www.businesscat.happyjar.com/?post_type=comic&p=3680/",
  "url": "http://www.businesscat.happyjar.com/comic/ornament/",
  "urls": [
    "http://www.businesscat.happyjar.com/comic/ornament/"
  ],
  "links": [
    {
      "href": "http://www.businesscat.happyjar.com/comic/ornament/"
    }
  ],
  "title": "Ornament",
  "description": "<p><a href=\"http://www.businesscat.happyjar.com/comic/ornament/\" rel=\"bookmark\" title=\"Ornament\"><img width=\"170\" height=\"170\" src=\"http://www.businesscat.happyjar.com/wp-content/uploads/2017/03/2017-03-10-Ornament-170x170.png\" class=\"attachment-thumbnail size-thumbnail wp-post-image\" alt=\"\" data-wp-pid=\"3681\" /><\/a>\n<\/p>Don&#8217;t worry. It&#8217;s only value is sentimental. &#8211; This comic brought to you courtesy of my amazing patrons. Special thanks to: Karen Carpenter, Gary Cooper, Dan Cunningham, Colin Dellow, &#8216;Giz&#8217;, Reece Hall, Erica Holcombe, Yuliya Levina, Jonna Märijärvi, Coté Nicholas, &#8216;Scott&#8217;",
  "content": "<p><a href=\"http://www.businesscat.happyjar.com/comic/ornament/\" rel=\"bookmark\" title=\"Ornament\"><img width=\"170\" height=\"170\" src=\"http://www.businesscat.happyjar.com/wp-content/uploads/2017/03/2017-03-10-Ornament-170x170.png\" class=\"attachment-thumbnail size-thumbnail wp-post-image\" alt=\"\" data-wp-pid=\"3681\" /><\/a>\n<\/p><p>Don&#8217;t worry. It&#8217;s only value is sentimental.<br />\n&#8211;<br />\n<em style=\"font-size:12px;\"><b>This comic brought to you courtesy of my amazing <a href=\"http://www.patreon.com/tomfonder\" target=\"_blank\">patrons<\/a>. Special thanks to:<\/b><br />\nKaren Carpenter, Gary Cooper, Dan Cunningham, Colin Dellow, &#8216;Giz&#8217;, Reece Hall, Erica Holcombe, Yuliya Levina, Jonna Märijärvi, Coté Nicholas, &#8216;Scott&#8217;<\/em><\/p>\n",
  "image": null,
  "enclosure": null,
  "authors": [
    "<Fonder>"
  ],
  "categories": [
    "angel",
    "boss",
    "break",
    "business cat",
    "cats",
    "ceo",
    "fragile",
    "glass",
    "office",
    "ornament",
    "smash",
    "suit",
    "tie",
    "wings",
    "work"
  ],
  "date_published": "2017-03-10T00:01:33+00:00",
  "last_updated": "2017-03-10T00:01:33+00:00"
}`

**Comment by dsander** [comment]
Great!
