### ISSUE TITLE
Is there a way to set ActionMailer SMTP Authentication type to `nil`? 

### ISSUE THREAD

**Issue by ashleysommer** [cantino/huginn#1937]
Im using an SMTP server that is configured to have no authentication.
Assigning no SMTP authentication type in huginn (leaving it empty), it appears that huginn sets `plain` authentication type on Action mailer.
I get an error with this trace from the mailer worker:
```
                       503 #5.3.3 AUTH not available

/usr/lib/ruby/2.3.0/net/smtp.rb:977:in `check_auth_response'
/usr/lib/ruby/2.3.0/net/smtp.rb:741:in `auth_plain'
/usr/lib/ruby/2.3.0/net/smtp.rb:733:in `authenticate'
/usr/lib/ruby/2.3.0/net/smtp.rb:568:in `do_start'
/usr/lib/ruby/2.3.0/net/smtp.rb:521:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/network/delivery_methods/smtp.rb:113:in `deliver!'
/app/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/message.rb:2149:in `do_delivery'
```

I get that same message if I set `SMTP_AUTHENTICATION` to "plain", "login" or "cram_md5", any other value like "none" returns an "invalid authentication type" error from ActionMailer.
If I set `SMTP_AUTHENTICATION` to empty string or `null`, this line https://github.com/cantino/huginn/blob/5868c7b4b23516bce7f7a9867b2310d6ef85980b/config/initializers/action_mailer.rb#L5 causes the value assigned to ActionMailer to be "plain".

Looking at the ActionMailer source files in the rails repository, here: https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/actionmailer/lib/action_mailer/delivery_methods.rb#L31 it seems that the `authentication` field of the smtp delivery method type can be `nil` and should be `nil` if no Auth is to be attempted.

So my question is, how do I set force that value to `nil` using a huginn configuration, without it reverting to "plain"?

**Comment by dsander** [comment]
Hi @ashleysommer,

I think you are right and we need a special string value which will converted to nil. Can you try to change the line in the initializer to ` authentication: (ENV['SMTP_AUTHENTICATION'] == 'nil' ? nil : ENV['SMTP_AUTHENTICATION'] || "plain"),`?

**Comment by knu** [comment]
"none", maybe?

**Comment by ashleysommer** [comment]
Thanks for the suggestion.

I didn't mention, I am using the docker container of huginn, pulled from Docker Hub. Env variables are passed I from my compose file.

I can't really make that quick change to see if it works. I will need to clone the repo, make the change and rebuild the container locally to test it. I probably won't have time to do that for a few days.

**Comment by ashleysommer** [comment]
Ok, I got it working.
I created a derived Dockerfile and copied in a modified config/initializers/action_mailer.rb file over existing one.
Adding the suggested line:
`authentication: ENV['SMTP_AUTHENTICATION'] == 'none' ? nil : ENV['SMTP_AUTHENTICATION'] || "plain"`
Successfully set the auth type to `nil` in action_mailer, however the ruby/net/smtp code was still calling auth_plain to try to authenticate and I was getting the same error.

I found the culprit here:
https://github.com/ruby/ruby/blob/ruby_2_3/lib/net/smtp.rb#L568

What I found in that line of code, _if there is a username set_ the smtp system will still try to authenticate and will fall back to `DEFAULT_AUTH_TYPE` if no auth type is provided.

I assumed that setting `SMTP_USER_NAME:` _(empty)_ in the environment file would be enough because the initializer uses `ENV['SMTP_USER_NAME'].presence` to set `nil` if the env variable is not present. However I think it is present and set to an empty string.

The only way I was able to get it to work was to add a similar line as above:
`user_name: ENV['SMTP_USER_NAME'] == 'none' ? nil : ENV['SMTP_USER_NAME'].presence`
to set user_name to `nil` if "none"
I tried lots of varients of setting `SMTP_USER_NAME` to an empty string, or unsetting it, but in each of those cases `SMTP_USER_NAME` was replaced with "you@gmail.com" as per the .env.example file.

Then finally, after setting `SMTP_USER_NAME` to "none" to force it to `nil`, I was getting an error along the lines of "SMTP-AUTH requested by no Username provided". But authentication was set to `nil`.

Again, looking at the ruby smtp code, it seems that if there is a password provided but username is `nil`, it queries the SMTP endpoint to see what Auth types are available, chooses an auth type, then raises an exception because there is no Username set.

As with the username above, I tried with `SMTP_PASSWORD` set to empty string and unset, but in each case it defaults to "yourpassword" as per the .env.example file.
I replaced the password line in the initializer with this:
`password: ENV['SMTP_USER_NAME'] == 'none' ? nil : ENV['SMTP_PASSWORD'].presence`

The first ENV key is correct, it checks SMTP_USER_NAME and sets password to `nil` if SMTP_USER_NAME is "none".

Here is the final action_mailer.rb that works for me:
```
ActionMailer::Base.smtp_settings = {
  address: ENV['SMTP_SERVER'] || "smtp.gmail.com",
  port: ENV['SMTP_PORT'] || 587,
  domain: ENV['SMTP_DOMAIN'],
  authentication: ENV['SMTP_AUTHENTICATION'] == 'none' ? nil : ENV['SMTP_AUTHENTICATION'] || "plain",
  enable_starttls_auto: ENV['SMTP_ENABLE_STARTTLS_AUTO'] == 'true',
  user_name: ENV['SMTP_USER_NAME'] == 'none' ? nil : ENV['SMTP_USER_NAME'].presence,
  password: ENV['SMTP_USER_NAME'] == 'none' ? nil : ENV['SMTP_PASSWORD'].presence,
  openssl_verify_mode: ENV['SMTP_OPENSSL_VERIFY_MODE'].presence,
  ca_path: ENV['SMTP_OPENSSL_CA_PATH'].presence,
  ca_file: ENV['SMTP_OPENSSL_CA_FILE'].presence
}
```
and what my environment.yml in the docker-compose script looks like:
```
version: '2'
services:
  huginn_base:
    environment:
      DATABASE_ADAPTER: mysql2
      DATABASE_NAME: huginn
      DATABASE_USERNAME: huginn
      DATABASE_PASSWORD: myhuginnpassword
      APP_SECRET_TOKEN: mysecrettoken
      SMTP_DOMAIN: mydomain.com.au
      SMTP_USER_NAME: none
      SMTP_PASSWORD:
      SMTP_SERVER: smtp.mydomain.com.au
      SMTP_PORT: 25
      SMTP_AUTHENTICATION: none
      SMTP_ENABLE_STARTTLS_AUTO: "false"
      EMAIL_FROM_ADDRESS: noreply@mydomain.com.au
      SEND_EMAIL_IN_DEVELOPMENT: "true"
```

**Comment by dsander** [comment]
@knu True, that is a better name 😄 

@ashleysommer Awesome research, glad you figured it out! Would you be willing to make a pull request with those changes? We have a bot which automatically builds docker images for ever PR which allows you to verify the changes still work.

**Comment by ashleysommer** [comment]
PR created: https://github.com/cantino/huginn/pull/1942
