### ISSUE TITLE
Dropbox Watch Agent fails on folder names with spaces

### ISSUE THREAD

**Issue by dnszero** [cantino/huginn#1946]
I am able to watch a directory with no spaces (`/ThisWorksFine`), but unable to use the `Dropbox Watch Agent` to monitor a directory which contains an embedded space in the name. Each of the following attempts fails:

`"dir_to_watch": "/\"Camera Uploads\""`
`"dir_to_watch": "/Camera\\ Uploads"`
`"dir_to_watch": "/Camera%20Uploads"`
`"dir_to_watch": "/Camera Uploads"`

Either no results are returned or the job fails with a "Last Error" of "404 - Not found". I've attached the [ErrorBacktrace.txt](https://github.com/cantino/huginn/files/868687/ErrorBacktrace.txt) from the last attempt.

**Comment by dsander** [comment]
That is odd the last version you tried works fine for me:
```
{
  "dir_to_watch": "/Camera Uploads",
  "expected_update_period_in_days": 1
}
```
The agent memory:
```
{
  "contents": [
    {
      "path": "/Camera Uploads/2012-07-25 15.27.37.jpg",
      "rev": "d410615354b",
....
```

The Dropbox error does not contain more information then the `404 - Not found`?

**Comment by dnszero** [comment]
I deleted and recreated the agent... and now it works fine using a plain space. Maybe something was hung up from my previous attempts at escaping the space?

Anyway, thanks for checking!
