### ISSUE TITLE
Replace therubyracer with execjs (if possible)

### ISSUE THREAD

**Issue by alias1** [cantino/huginn#1959]
So thinking about therubyracer/mini_racer stuff in #1919 lead me to finding out about https://github.com/rails/execjs

Essentially, it seems to be a wrapper around all the possible ruby JS implementations.

Theoretically, that means that we should be able to rip out the current direct binding to therubyracer, and replace it with execjs, and have everything just work.

Creating this separate issue so it doesn't get stuck in my dockerfile rewrite stuff.

Is this something anyone else would like to tackle? Shouldn't be overly difficult, but i'm well aware of my time pressures at the moment, and so not sure I will get to it in any sort of reasonable timeframe at the moment.

**Comment by dsander** [comment]
I don't think that will work. `execjs` only allows to execute javascript code, but we are also adding [functions](https://github.com/cantino/huginn/blob/master/app/models/agents/java_script_agent.rb#L113-L129) which will always be specific to the javascript runtime. I will have a look at `mini_racer`, it sounds like it would both speed up asset precompilation as well as the `JavascriptAgent`.

**Comment by alias1** [comment]
I'm going to close this for now, in light of #1961 Can reopen again later if required.
