### ISSUE TITLE
Specify path (base url) for reverse proxy

### ISSUE THREAD

**Issue by dansherman** [cantino/huginn#1966]
I'm running Huginn from a docker container in FreeNAS 10. It works great when I access it via the IP address, or if I reverse proxy with nginx using "huginn.domain.tld".

I tried proxying it to "domain.tld/huginn", but when I do I see the following:
![image](https://cloud.githubusercontent.com/assets/1310290/24956021/6c40332c-1f4b-11e7-8c04-6306e6faffe4.png)

Some apps support changing the url base to allow them to be accessed by a path instead of a bare (sub)domain. Is that possible with Huginn?

**Comment by JamiePhonic** [comment]
This isn't something supported by Huginn just now as far as i know.

The reason the solution you tried doesn't work is because nginx appends the location to the proxied location,
so `domain.tld/huginn` is being proxied to `huginn.domain.tld/huginn` which obviously doesn't exist.

**Comment by dansherman** [comment]
That's what I thought, thanks. I'll just use a subdomain.
