### ISSUE TITLE
Data Output Agent - option to change content type returned?

### ISSUE THREAD

**Issue by kimptoc** [cantino/huginn#1968]
Hi,

I am trying to use a feed produced by huginn with the Alexa skills kit for a flash briefing. It takes an rss or json feed. However, its saying my feed is invalid, even though the exact same xml works if supplied from a static page under apache.

I am guessing the issue is with the Content-Type returned.  Huginn returns 'text/xml' - seems to be fixed in the agent - https://github.com/cantino/huginn/blob/master/app/models/agents/data_output_agent.rb

Whereas my apache page, returns Content-Type of 'application/rss+xml' .

I could supply a patch to make the content type setting something that can be configured in the template - is that a valid route to take?  Presumably it needs to be 'text/xml' for some usages?

My app is proxied via nginx - so I can perhaps 'fix' it there.

Thanks in advance,
Chris

**Comment by dsander** [comment]
Hi Chris,

adding an option to configure the Content-Type would be reasonable. I wonder if we can change the default to `application/rss+xml` as it seems to be the [suggested value](http://www.rssboard.org/rss-mime-type-application.txt) for RSS feeds.

@knu probably know more about it :)

**Comment by knu** [comment]
I don't think there was a particular reason for adopting the current value instead of the industry default, so I've created a PR above.

**Comment by knu** [comment]
Please upgrade your Huginn instance and check out the `rss_content_type` option.

**Comment by kimptoc** [comment]
Great - many thanks for that.  

I am using the docker image, which looks to have been rebuilt.  I have removed/pulled/restarted my compose service, but still not picking up the change.

**Comment by cantino** [comment]
I believe it gets rebuilt on every merge to master. @dsander may has further suggestions.

**Comment by dsander** [comment]
@kimptoc Which image are you using? `cantino/huginn` and `cantino/huginn-single-process` are rebuild for every new commit on the master branch.

**Comment by kimptoc** [comment]
```
  image: cantino/huginn
```
I see it was rebuilt yesterday and after I "rm"'ed my compose container, it seemed to pull down the new image.

Must at the layers of my image :( 

Thanks.

**Comment by dsander** [comment]
That's odd, I never noticed an issue like this. You are using `docker-compose pull` and `docker-compuse up -d` as well to upgrade? I'll keep an eye out for similar oddities.

**Comment by kimptoc** [comment]
Have deleted all my containers and images (docker ps -a and docker images both return nothing) and then downloaded latest and still getting text/xml as content (via wget --save-headers)

**Comment by knu** [comment]
The migration script explicitly sets rss_content_type to the previous default value (text/xml) for existing agents.  This is for compatibility.  Edit your agents to go for the new value (application/rss+xml).

**Comment by kimptoc** [comment]
doh - apologies, that works just great.

Thanks  again!
