### ISSUE TITLE
Disabling the scheduler

### ISSUE THREAD

**Issue by Faberman** [cantino/huginn#1971]
Hello.
Is it possible to turn off the scheduler for specific agents? I have a few scenarios, where all the agents are dependent on each other. When the first agent receives an event, it sends all the necessary data to other agents. And this data is valid for 10-15 minutes. So when all the agents, except the first one, run as a scheduled jobs, they return errors (and 'not working' status), because there's no any data for them.

Or maybe it's possible to add a really long interval to a scheduler?

**Comment by cantino** [comment]
Can you set their schedules to `never`, or am I misunderstanding?

**Comment by Faberman** [comment]
Now I feel myself really stupid. I've been using Huginn for a few years and never seen this option. Thank you for the tip!

**Comment by cantino** [comment]
Haha, no problem!
