### ISSUE TITLE
How to do a calculation between two values in event then setup a trigger based on the result

### ISSUE THREAD

**Issue by educatedwarrior** [cantino/huginn#1975]
Anyone know how to take two values from an event, do a calculation between them, then setup a trigger agent based on the results of the calculation?

**Comment by dsander** [comment]
Calculations can be done using [liquid math filters](https://help.shopify.com/themes/liquid/filters/math-filters). I think you need to use a `EventFormattingAgent` for the calculations because the `TriggerAgent` only supports `JSONPaths`.

**Comment by educatedwarrior** [comment]
Thanks @dsander  .   I'm now trying to figure out how I can convert a percent value (stored as text) into a numeric value.  Got any suggestions.   My event looks like this.

{
  "no": "2",
  "ticker": "XOM",
  "ATR": "0.89",
  "52wk_high": "-13.29%",
  "52wk_low": "0.49%",
  "price": "80.69",
  "change": "-0.40%"
}

**Comment by educatedwarrior** [comment]
Think I figured it out.

{{52wk_high| replace:'%','' | multiply:1}}

**Comment by educatedwarrior** [comment]
Now I'm having issues with floating point calculation using liquid.  

For my event above I'm trying to do the following calculaton

{{ 1.00 | plus: 52wek_high_pct | times: price}}

I appears when I add the decimal to 1 , it yields 1 integer.

**Comment by educatedwarrior** [comment]
Opened #1981  to deal with shopify math filter issues.

**Comment by dsander** [comment]
Nice! Thanks for opening a new issue.
