### ISSUE TITLE
How to parse Finviz for stock price monitoring

### ISSUE THREAD

**Issue by educatedwarrior** [cantino/huginn#1976]
Would like to set up stock monitoring events using Finviz.   Anyway to parse the table on the screener page.  Here is a link.   I took a look at the source and couldn't figure it out.
 
http://www.finviz.com/screener.ashx

**Comment by dsander** [comment]
Hi @educatedwarrior,

the Chrome dev tools are very helpful when looking for the right selector. Right click on inspect and then use `Copy -> Copy selector`. When dealing with tables you need to remove `tbody` because it's inserted by chrome and on most sites not present in the actual HTML. These options should work for the table:
```
{
  "expected_update_period_in_days": "2",
  "url": "http://www.finviz.com/screener.ashx?v=111",
  "type": "html",
  "mode": "all",
  "extract": {
    "no": {
      "css": "#screener-content > table > tr:nth-child(4) > td > table > tr:nth-child(2) > td:nth-child(1)",
      "value": "string(.)"
    },
    "ticker": {
      "css": "#screener-content > table > tr:nth-child(4) > td > table > tr:nth-child(2) > td:nth-child(2)",
      "value": "string(.)"
    }
  }
}
```

**Comment by educatedwarrior** [comment]
Thank you!!!! I'll give it a try.

**Comment by educatedwarrior** [comment]
@dsander    , nubbie question for you.   What is the "#screen-content for?"  How did you no to use that tag.

**Comment by educatedwarrior** [comment]
...never mind, I think I found it in the div tag as the id property.

**Comment by educatedwarrior** [comment]
@dsander , I got a problem.   It's only pulling back the first row. Any suggestions?

**Comment by dsander** [comment]
Sorry my first example had a `nth-child` selector on the`tr` this returns all rows:
```
{
  "expected_update_period_in_days": "2",
  "url": "http://www.finviz.com/screener.ashx?v=111",
  "type": "html",
  "mode": "all",
  "extract": {
    "no": {
      "css": "#screener-content > table > tr:nth-child(4) > td > table > tr > td:nth-child(1)",
      "value": "string(.)"
    },
    "ticker": {
      "css": "#screener-content > table > tr:nth-child(4) > td > table > tr > td:nth-child(2)",
      "value": "string(.)"
    }
  }
}
```

**Comment by educatedwarrior** [comment]
@dsander ,  I think we are almost there.   Now how do you skip the 1st row which has the row headers?  Got to filter that out of the results because when trying to cast a value into a number which text, I get an error.

**Comment by educatedwarrior** [comment]
So.. basically, I need to select the 2nd to n child, skipping the first child for the last tr .

**Comment by educatedwarrior** [comment]
I tried this but it didn't work.

{
  "expected_update_period_in_days": "2",
  "url": "http://finviz.com/screener.ashx?v=171&f=geo_usa,ta_highlow52w_a0to10h&ft=4&t=AMT,ADM,BMI,CAT,KO,CL,LLY,XOM,JNJ,MCD,POT,PPG,PG,SWK",
  "type": "html",
  "mode": "all",
  "extract": {
    "no": {
      "css": "#screener-content > table > tr:nth-child(4) > td > table > tr:not(nth-child(1)) > td:nth-child(1)",
      "value": "string(.)"
    },
    "ticker": {
      "css": "#screener-content > table > tr:nth-child(4) > td > table > tr:not(nth-child(1)) > td:nth-child(2)",
      "value": "string(.)"
    }
  }
}

**Comment by educatedwarrior** [comment]
I'm thinking maybe, I'm not getting the syntax right.  I've also tried.

{
  "expected_update_period_in_days": "2",
  "url": "http://www.finviz.com/screener.ashx?v=111",
  "type": "html",
  "mode": "all",
  "extract": {
    "no": {
      "css": "#screener-content > table > tr:nth-child(4) > td > table > :not(tr:nth-child(1)) > td:nth-child(1)",
      "value": "string(.)"
    },
    "ticker": {
      "css": "#screener-content > table > tr:nth-child(4) > td > table > :not(nth-child(1)) > td:nth-child(2)",
      "value": "string(.)"
    },
    "ATR": {
      "css": "#screener-content > table > tr:nth-child(4) > td > table > :not(tr:nth-child(1)) > td:nth-child(4)",
      "value": "number(.)"
    },
    "52wk_high": {
      "css": "#screener-content > table > tr:nth-child(4) > td > table > :not(tr:nth-child(1)) > td:nth-child(8)",
      "value": "string(.)"
    },
    "52wk_low": {
      "css": "#screener-content > table > tr:nth-child(4) > td > table > :not(tr:nth-child(1)) > td:nth-child(9)",
      "value": "string(.)"
    },
    "price": {
      "css": "#screener-content > table > tr:nth-child(4) > td > table > :not(tr:nth-child(1)) > td:nth-child(11)",
      "value": "number(.)"
    }
  }
}

**Comment by educatedwarrior** [comment]
Error - 
[00:00:01] ERROR -- : Error when fetching url: unexpected 'nth-child(' after ':not('

**Comment by educatedwarrior** [comment]
Figured it out.   I changed tr to tr:nth-child(n+2) and that did the trick.

**Comment by dsander** [comment]
Nice!
