### ISSUE TITLE
abs and round Shopify Liquid Math filters not working currectly in  EventFormattingAgent

### ISSUE THREAD

**Issue by educatedwarrior** [cantino/huginn#1981]
The shopify liquid reference gives examples on how math filters should work, but when the exact examples are used in huginn, the results do not match the reference.

For example

{{ "-19.86" | abs }} should yield 19.86 , but yields -19.86 in Huginn

{{ "-183.357" | round: 3 }} should yield -183.357 but yields -183.0 in Huginn.  (Doesn't work when quotes are around the number)

Do we need to convert a string number into a number with decimals... How do you do that.   Can't get multiply:1  to work

**Comment by cantino** [comment]
Hey @educatedwarrior, thanks for reporting this. I agree. When I run `Liquid::Template.parse('{{ "-19.86" | abs }}').render!`, I also get `"-19.86"` in the current version of Huginn. If I upgrade Liquid to 4.0, I get the correct `"19.86"`. It'd be nice for us to upgrade Liquid, but a number of tests break when I do. I may need @knu's help to investigate, as it looks like the [innards of Liquid::Block have changed a bit](https://github.com/Shopify/liquid/pull/458). @knu, I pushed a failing branch to [upgrade-liquid](https://github.com/cantino/huginn/tree/upgrade-liquid) with the bump and a fix for https://github.com/Shopify/liquid/pull/661.

The only remaining failures are 4 specs similar to:
```
  1) LiquidInterpolatable::Filters regex_replace_first block should replace the first occurrence of a string using regex
     Failure/Error: subject = render_all(@in_block, context)

     NoMethodError:
       undefined method `render_all' for #<LiquidInterpolatable::Blocks::RegexReplace:0x007fc35a2f9ca0>
       Did you mean?  render
     # ./app/concerns/liquid_interpolatable.rb:413:in `render'
     # /Users/andrew/.rvm/gems/ruby-2.3.1@huginn/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
     # /Users/andrew/.rvm/gems/ruby-2.3.1@huginn/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
     # /Users/andrew/.rvm/gems/ruby-2.3.1@huginn/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
     # /Users/andrew/.rvm/gems/ruby-2.3.1@huginn/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
```

(They've also added https://github.com/Shopify/liquid/pull/645, which looks useful, and some [other stuff](https://github.com/Shopify/liquid/blob/master/History.md#400--2016-12-14--branch-4-0-stable).)

**Comment by educatedwarrior** [comment]
Thanks for the follow-up @cantino .  Good news for the abs function that a fix is in the works.  Any advice on the round issue?   The negative number parsed from HTML either needs to be converted to a number before using round (I haven't had any luck in figuring this out) , or the round function needs to be updated to accept a number in string format.

**Comment by dsander** [comment]
@cantino I fixed the specs in your branch.

@educatedwarrior The issue with negative floats has also been fixed in liquid `4.0.0`: https://github.com/Shopify/liquid/commit/1597f8859f08b7d594e6b47b9b5b9662cca145d3

**Comment by knu** [comment]
Actually this is a documentation problem rather than a software bug, as the "abs" filter is not present in Liquid 3.0 while the online documentation is based on Liquid 4.0 which has it.  So we could "fix" it by adding the function, but I'd agree it'd be much more beneficial to upgrade Liquid to 4, so let's move on to #1982.

**Comment by cantino** [comment]
This should be fixed now @educatedwarrior, thanks for reporting it!
