### ISSUE TITLE
EmailDigestAgent emailing entire event payload when message is in payload

### ISSUE THREAD

**Issue by educatedwarrior** [cantino/huginn#1992]
I updated my Rain notifier scenario so I could specify different recipients for different locations.

To the EventFormatting Agent I am using a liquid tag case statement to create recipient list based on location.  In order to propagate the recipient payload all the way down to the EmailDigestAgent, I had to set keep_event=true in the "Rain Notifier" TriggerAgent.      

Eventhough a message is created in the TriggerAgent, when the event is received by the EmailDigestAgent, it emails the entire payload instead of just the message.   This conflicts with the how the EmailDigestAgent should work as described in help.

I would only like to email the message, not the entire payload.

**Comment by cantino** [comment]
Could you give an example of the event payload and the agent configuration?

**Comment by educatedwarrior** [comment]
Event Payload from "Rain Tomorrow Notifier"

{
  "date": {
    "epoch": "1493679600",
    "pretty": "7:00 PM EDT on May 01, 2017",
    "day": 1,
    "month": 5,
    "year": 2017,
    "yday": 120,
    "hour": 19,
    "min": "00",
    "sec": 0,
    "isdst": "1",
    "monthname": "May",
    "monthname_short": "May",
    "weekday_short": "Mon",
    "weekday": "Monday",
    "ampm": "PM",
    "tz_short": "EDT",
    "tz_long": "America/New_York"
  },
  "period": 2,
  "high": {
    "fahrenheit": "76",
    "celsius": "24"
  },
  "low": {
    "fahrenheit": "55",
    "celsius": "13"
  },
  "conditions": "Thunderstorm",
  "icon": "tstorms",
  "icon_url": "http://icons.wxug.com/i/c/k/tstorms.gif",
  "skyicon": "",
  "pop": "90",
  "qpf_allday": {
    "in": 0.41,
    "mm": 10
  },
  "qpf_day": {
    "in": 0.4,
    "mm": 10
  },
  "qpf_night": {
    "in": 0.0,
    "mm": 0
  },
  "snow_allday": {
    "in": 0.0,
    "cm": 0.0
  },
  "snow_day": {
    "in": 0.0,
    "cm": 0.0
  },
  "snow_night": {
    "in": 0.0,
    "cm": 0.0
  },
  "maxwind": {
    "mph": 25,
    "kph": 40,
    "dir": "SSW",
    "degrees": 195
  },
  "avewind": {
    "mph": 18,
    "kph": 29,
    "dir": "SSW",
    "degrees": 195
  },
  "avehumidity": 79,
  "maxhumidity": 0,
  "minhumidity": 0,
  "title": "Monday",
  "fcttext": "Thunderstorms. A few storms may be severe. High 76F. Winds SSW at 15 to 25 mph. Chance of rain 90%.",
  "fcttext_metric": "Thunderstorms. A few storms may be severe. High near 25C. Winds SSW at 25 to 40 km/h. Chance of rain 90%.",
  "location": "US/NC/Charlotte",
  "agent": "WeatherAgent",
  "owner": "",
  "current_time": "2017-04-30 12:08:19",
  "txn_date_s": "",
  "current_time_s": "1493568499",
  "recipients": "['tjb5@email.com','mlb214@email.com']",
  "message": "Just so you know, it looks like 'Thunderstorm' tomorrow in US/NC/Charlotte"
}

**Comment by educatedwarrior** [comment]
Afternoon Digest (Email Digest Agent) config

{
  "subject": "Your Afternoon Digest",
  "expected_receive_period_in_days": "7"
}

**Comment by dsander** [comment]
@educatedwarrior I think you are right and the description of the `DigestAgent` is wrong. You can use an `EventFormattingAgent` to only send the `message` to the `DigestAgent`

**Comment by educatedwarrior** [comment]
@dsander ... makes sense.    I do have one concern, will I be able to pass a recipients list into the DigestAgent from the EventFormattingAgent without the recipient list being displayed in the digest output?

**Comment by educatedwarrior** [comment]
Thanks for your help @dsander and @cantino ...   I figured out another way to do it.  Had to create multiple DigestAgents with different recipient lists.
