### ISSUE TITLE
Interface with The Thing System

### ISSUE THREAD

**Issue by KenYN** [cantino/huginn#201]
I've just come across [The Thing System](http://thethingsystem.com/) ([Github](https://github.com/TheThingSystem)), and it would be nice if we could link the two together; can Huginn be the [magic](http://thethingsystem.com/dev/Magic.html) they talk about?

http://thethingsystem.com/dev/supported-things.html

@TheThingSystem

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further!
