### ISSUE TITLE
Language-agnostic agents

### ISSUE THREAD

**Issue by peterkeen** [cantino/huginn#215]
Right now agents pretty much have to be written in either Ruby or Javascript. It would be neat if agents could be written in other languages as well, like [Heroku buildpacks](https://devcenter.heroku.com/articles/buildpack-api).

Agents would simply be a `bin` directory containing an executable named `process`. This executable would take a JSON event (or an array of events) on STDIN and output an array of events on STDOUT. Logs would go to STDERR and get picked up like `AgentLogs`. Agent-level metadata would be in a file called `agent_metadata.json` at the top level, and configuration information could be passed as a JSON filename as the first argument, and the "memory" could be a cache directory passed in as a second argument or via the config JSON.

**Comment by cantino** [comment]
I don't think Huginn is going to become polyglot in the near future.  We have the ShellCommandAgent and the JavaScriptAgent which get us part of the way there.  Feel free to open a new issue to discuss further!
