### ISSUE TITLE
Event Tracking and Visualization

### ISSUE THREAD

**Issue by engineerkhushal** [cantino/huginn#226]
This is a suggestion, Events tracking should be implemented for instance I want to search for soccer and someone is posting a link on twitter, which then leads to few more interesting links, so if such connected events can be tracked, it will be worth something and can lead to a lot more possible enhancements. If its possible I would love to contribute for this part.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further!
