### ISSUE TITLE
Graph Editing GUI

### ISSUE THREAD

**Issue by ClashTheBunny** [cantino/huginn#241]
NoFlo has been doing a great job at getting a good visual graph editor going and it would be great to see it integrated into huginn.  Setting huginn up visually would probably be quite a stunning visual and would give access to people who are maybe slightly less technical, or at least people who are more spacial reasoning oriented vs analytic.

There are two levels of components, the full noflo graph editor:
https://github.com/noflo/noflo-ui
which could maybe be cajoled into editing the graphs you need with some new specific components added.  The resulting graph would probably need to be imported in (but it's in JSON, so it should be pretty easy).  There is an example graph in the next repo:
https://github.com/the-grid/the-graph/blob/master/the-graph-editor/clock.json.js

The other option is to grab the web widget that they created and be able to define your own output formats and not have to deal with all the "nodejs"-ness:
https://github.com/the-grid/the-graph
I know nothing about it, other than that it's full of eye candy and touch friendly.

"The Graph" replaced this other old web based visual graph editor:
https://github.com/meemoo/dataflow

Since I don't know much about the architecture of any of this, my gut feeling is all I have to go off of, which says "The Graph" is probably the way to go to avoid the nodejs part and it is actively developed.

Thanks so much for creating such a great project.  I look forward to seeing where it goes and using it in my various nordic-god-like duties.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further!
