### ISSUE TITLE
Allow "OR" on rules in TriggerAgent

### ISSUE THREAD

**Issue by snicker** [cantino/huginn#266]
It would be useful to have a configuration setting to allow the TriggerAgent to fire if *any* rule in the rule array is matched rather than *all* rules.

Example:
You're monitoring a feed of news articles and you want to trigger an event if a phrase is found in either the `title` or `description` field in a news article. 

Current Workarounds:

* Two TriggerAgents, kinda inelegant?
* Using a EventFormattingAgent to merge any relevant fields into one and comparing that

**Comment by cantino** [comment]
We support this now!
