### ISSUE TITLE
'Global' Event Listener

### ISSUE THREAD

**Issue by alias1** [cantino/huginn#291]
Splitting this from the original thread in #262 for clarity.

> Me: Along another similar line (sorry for hijacking the thread!), is there currently any concept of a 'global' event listener (that doesn't need to be manually wired up), and if not, does the event propagation architecture support this sort of thing easily/at all?

> @cantino: It should be possible to make an Agent listen to everything, although it might not be very performant.

I know that it would be possible to achieve by manually 'wiring' it up to every agent, but that feels like a hacky way to go about it.

I'm not sure I have a 'real world' use case for it at the moment (more of an academic pondering based on stuff i've read about event systems in general) I guess one off the top of my head could be writing a line to a log file (contrived example I know).

I guess my thinking is it would allow for more.. organic (eg. less predefined) handling of things. Eg. Without having to manually wire it up, look for any event that look sort of like X and then do Y with them. Again, not sure I have a non-contrived real-world case for this, but I put it out there for your ideas/comments on it, would be interested to see what others have to say about it.

Could anyone give me a quick 2min rundown on how the event handling system works currently (at a technical level)? If not I could dig into the code and have a look when I find the time.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further!
