### ISSUE TITLE
Agent 'Cards' and a 'Wall'

### ISSUE THREAD

**Issue by samw3** [cantino/huginn#317]
Email digests are sooo last decade ;)  I like using email to be alerted, but for low-priority items, I'd like to view them in a timeline.

This would be something like the Events page, but easier for human consumption.

@alias1 was suggesting that each agent could have something like a Twitter 'Card'.  A simple html templating engine would probably be enough.  Something that would let you select payload vars and lay them out in a nice way.  

Having a nice standardized frame with color coding or priority levels would be nice too (i.e. panic, critical, warning, notice).  This could be done pretty easily in CSS.

Also, I would be happy to work on this, but I'm hesitant to start since it might change some core structures.  Maybe @cantino could give direction.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further or try building this!
