### ISSUE TITLE
Agent  Not working

### ISSUE THREAD

**Issue by suhas6ue** [cantino/huginn#332]
Hi,
          I am new to Huginn. I have cliked on run but working does not change from "no" to "yes" as i have seen in many screen shot. Thanks in advance.

**Comment by betacanis** [comment]
Hi, I just deployed the latest Huginn on google cloud, I still see all the Agents in Working NO state

I started the server as 
```javascript
foreman start
```
Any help would be appreciated, thanks!

**Comment by cantino** [comment]
Try `bundle exec foreman start` and see if that helps.  Which Agents are not working?

**Comment by betacanis** [comment]
Hi @cantino thanks for the quick response.. I did manage to run a TwitterUserAgent after starting my server with ```javascript bundle exec foreman start ```
However TwitterStreamAgent is still not getting executes, I get the following exception
```javascript
12:17:44 jobs.1 | Exception A copy of TwitterStream has been removed from the module tree but is still active!:
12:17:44 jobs.1 | /opt/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:465:in `load_missing_constant'
12:17:44 jobs.1 | /opt/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:180:in `const_missing'
12:17:44 jobs.1 | /opt/projects/huginn/lib/twitter_stream.rb:102:in `run'
12:17:44 jobs.1 | bin/threaded.rb:29:in `block (2 levels) in <top (required)>'
```

**Comment by cantino** [comment]
Wow, that's a new error for me.  What version of Ruby is this?

**Comment by betacanis** [comment]
Finally got it working.. I had installed incorrect version of nokogiri.. thanks!

**Comment by cantino** [comment]
Glad you figuring it out @betacanis!

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you need further help!
