### ISSUE TITLE
TrelloWebhookAgent (Initialization and Shutdown entry points)

### ISSUE THREAD

**Issue by Toilal** [cantino/huginn#346]
Some agents may send events without beeing scheduled. 

[Trello.com](https://trello.com) provides a [webhook API](https://trello.com/docs/gettingstarted/webhooks.html). When the webhook is registered, Trello can notify specific model changes to the huginn agent, through ```def receive_web_request(params, method, format)```.

I'm new on huginn and ruby, but i didn't find any entry point in agent class to perform registration of the webhook at init time, when a new Agent is created. 

I need to register the webhook at creation time, and unregister it at delete time. 

Those entry points should also be called when starting and shutting down Huginn.

**Comment by naiyt** [comment]
Has anyone here made any progress on a Trello agent? If so, let me know if I can help out. If not, I'd like to try putting one together.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further or try building this!
