### ISSUE TITLE
Hide memory by default. Toggle with button.

### ISSUE THREAD

**Issue by alias1** [cantino/huginn#350]
From #136 

> @Alex-Ikanow In a similar vein (protecting sensitive information), the "memory" field in the "show" page for Agents should by default not show the memory, you should have to press a button.

> @cantino  It would be simple to hide the memory by default-- someone could submit a patch for that.

**Comment by Jngai** [comment]
I will work on this ui change.

**Comment by Jngai** [comment]
@cantino I think you can close this.

**Comment by cantino** [comment]
Yup, thanks!
