### ISSUE TITLE
(KenYN's) Time Gateway Agent

### ISSUE THREAD

**Issue by alias1** [cantino/huginn#351]
From @KenYN in #67 
> I'm perhaps a bit late with this, but here's a related agent I've just developed. It will only let an event pass through between one of the given time periods.

https://gist.github.com/KenYN/23a33ba61e91279ba9c4

If @KenYN wants to send a PR for this we can do it, otherwise I (or someone else) can setup a PR with this.

Also ping @crawfordcomeaux

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further.
