### ISSUE TITLE
Unable to delete agent, thrown to ActiveRecord::RecordNotFound screen.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#399]
I'm reworking part of my agent network and I'm trying to delete an agent because I can't change what type it is.  When I try to do so with the Delete (or Disable, for that matter) function, I'm thrown to an "ActiveRecord::RecordNotFound" screen.  Details from this screen:

Couldn't find Agent with 'id'=39 [WHERE `agents`.`user_id` = ?]

In the app/controllers/agents_controller.rb subwindow (starting at row 120):

```ruby
      end
    end
  end
  def update
    @agent = current_user.agents.find(params[:id])
    respond_to do |format|
      if @agent.update_attributes(params[:agent])
        format.html { redirect_back "'#{@agent.name}' was successfully updated." }
        format.json { render json: @agent, status: :ok, location: agent_path(@agent) }
```

Line 125 (`@agent = current_user.agents.find(params[:id])`) is highlighted.

I can get more information if you need it, just tell me what would be helpful.

**Comment by virtadpt** [comment]
As of commit 26a8e495817bdd5362dbd09b317a5c05f7335a9f, I no longer see this happen.  Things are now working as expected when deleting agents.  \0/

**Comment by cantino** [comment]
Yay!
