### ISSUE TITLE
Twitter Stream agent only follows first filter on first agent

### ISSUE THREAD

**Issue by kazazes** [cantino/huginn#406]
I can't seem to get multiple twitter stream agents to run. So far, I can only get it to generate events for the FIRST filter of the FIRST agent. I'm not sure what is meant by "If you provide an array instead of a filter, the first entry will be considered primary and any additional values will be treated as aliases." What is meant by aliases? Are they not primary filters?

If I set the first one to "testphrase101" and the second to "testphrase102", I only generate events on the first time. I can't get a second agent to generate events at all.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further!
