### ISSUE TITLE
User Locations

### ISSUE THREAD

**Issue by haxwithaxe** [cantino/huginn#411]
a key value pair like Credentials that stores various user location definitions.
the utility of htis would be to have a "home", "work", "current" type of reference for user location that can be referenced by things like the weather agent to provide info based on one's current location (magically updated by some as yet considered method).
it should allow an arbitrary number of locations to allow a user to specify arbitrary locations to agents.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further or try building this!
