### ISSUE TITLE
More robust scenarios

### ISSUE THREAD

**Issue by andrewcurioso** [cantino/huginn#434]
As a user I'd like to see more robust scenarios. Specifically:

- A archive file format that allows files to be packaged with the scenario (such as logos, or shell scripts)
- Logos for scenarios
- Manifests (author, license, requirements, homepage, source code location... similar to the current export)
- Parametrization (so that a user can configure a scenario without having to go into individual agents)
- Signing scenarios using public/private keys to prove authorship (especially during upgrade)

I think if Huginn scenarios had these capabilities it would pave way for a robust community of package authors. I'd be happy to draft up a spec for the community to discuss if anyone is interested.

**Comment by cantino** [comment]
Closing in favor of #813.
