### ISSUE TITLE
can specify the varible in url of web site agent?

### ISSUE THREAD

**Issue by nikeyol** [cantino/huginn#447]
Hi there,

I tried to utilize website agent to get url value from event fromat agent, it means it will pass the varible to website agent. Just like below:

{
  "expected_update_period_in_days": "2",
   "url": "{{uri}}",
  "type": "json",
  "mode": "all",
  "extract": {
    "originatingURI": {
      "path": "d.results.[*].originatingURI"
    },
    "sourceID": {
      "path": "d.results.[*].sourceID"
    },
    "tenantID": {
      "path": "d.results.[*].tenantID"
    },
    "status": {
      "path": "d.results.[*].status"
    },
    "creationUserID": {
      "path": "d.results.[*].creationUserID"
    },
    "lastModTimeStamp": {
      "path": "d.results.[*].lastModTimeStamp"
    },
    "creationTimeStamp": {
      "path": "d.results.[*].creationTimeStamp"
    },
    "id": {
      "path": "d.results.[*].id"
    },
    "isActive": {
      "path": "d.results.[*].isActive"
    },
    "description": {
      "path": "d.results.[*].description"
    },
    "lastModUserID": {
      "path": "d.results.[*].lastModUserID"
    },
    "__metadata": {
      "path": "d.results.[*].__metadata"
    }
  }
}

**Comment by cantino** [comment]
I believe this is possible now.
