### ISSUE TITLE
give a variable to post_url in post agent

### ISSUE THREAD

**Issue by nikeyol** [cantino/huginn#451]
Hi there,

currently, I utilized post agent to post data, and the post url is like： http://x.x.x.x:port/ca-nim/odata/default/v1/Request('id'), where id is a varible, and we can get it from event format agent, but how to make the post agent to accept it, and can the parameter post_url in post agent to concatenate some basic string from the source like event format agent?

**Comment by cantino** [comment]
I believe this is possible now.
