### ISSUE TITLE
Docker - Automated Builds

### ISSUE THREAD

**Issue by alias1** [cantino/huginn#458]
http://docs.docker.com/userguide/dockerrepos/#automated-builds

> Automated Builds automate the building and updating of images from GitHub or BitBucket, directly on Docker Hub. It works by adding a commit hook to your selected GitHub or BitBucket repository, triggering a build and update when you push a commit.

Reading through the docker doco (*smirk*) and came across this. Not sure if it's something we currently do/have thought about/etc?

**Comment by ianblenke** [comment]
Automated docker builds have been in place a while now... is there anything left in this issue to follow up on?
