### ISSUE TITLE
uninitialized constant RAILS

### ISSUE THREAD

**Issue by princeankasa** [cantino/huginn#471]
i seem to have found ma self in a problem
can someone help me
this is the error and the trace

C:\fedena>rake db:create
rake aborted!
uninitialized constant RAILS
(See full trace by running task with --trace)
C:\fedena>rake db:create --trace
rake aborted!
uninitialized constant RAILS
C:/Ruby193/lib/ruby/1.9.1/rake/ext/module.rb:36:in `const_missing'
C:/fedena/config/boot.rb:108:in `<top (required)>'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/fedena/Rakefile:4:in `<top (required)>'
C:/Ruby193/lib/ruby/1.9.1/rake/rake_module.rb:25:in `load'
C:/Ruby193/lib/ruby/1.9.1/rake/rake_module.rb:25:in `load_rakefile'
C:/Ruby193/lib/ruby/1.9.1/rake/application.rb:501:in `raw_load_rakefile'
C:/Ruby193/lib/ruby/1.9.1/rake/application.rb:82:in `block in load_rakefile'
C:/Ruby193/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handlin
g'
C:/Ruby193/lib/ruby/1.9.1/rake/application.rb:81:in `load_rakefile'
C:/Ruby193/lib/ruby/1.9.1/rake/application.rb:65:in `block in run'
C:/Ruby193/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handlin
g'
C:/Ruby193/lib/ruby/1.9.1/rake/application.rb:63:in `run'
C:/Ruby193/bin/rake:32:in `<main>'

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further.
