### ISSUE TITLE
Agent output format should be specifiable

### ISSUE THREAD

**Issue by pjz** [cantino/huginn#483]
It Would Be Nice if it was possible to specify the *output* format of agents as well as their input format.  For instance, if I want to read an RSS feed and add a sentiment value to it, that should be simple, right?  But it's not, because the sentimentAgent outputs _only_ the three values it computes, and basically drops all the rest of the input on the floor.  Instead of what it currently does, it could do one of:

  *  have an 'Output' Liquid template, with the results of the Agent as variables for substitution.  Then it would be possible to, if desired, duplicate the entire input format and just add fields for the new data.

  * have each output value associated with one (or more?) javascript 'path' statements that would describe how to mutate the incoming event with each piece of new data. So something like: ```good-bad: $.good_bad``` would mean, approximately ```$incoming['good-bad'] = <good-bad value>```/

Or perhaps I'm missing some common way people are doing multi-step transformations?  All the examples I've seen have been simple in-filter-sink.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further or try building this!
