### ISSUE TITLE
Capture fatal exceptions in a more permanent manner to facilitate reproduction and debugging.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#485]
After running into another problem with a tweet incorporating Unicode crashing Huginn, it would be nice to have an error handling system that did something like the following:
* Receive an exception
* Determine that the exception is fatal, i.e., Huginn is crashing
* Capture the exception, stack trace, et al as a crash dump
* Write the crash dump to a separate file, such as huginn/log/crashdump-<datestamp>-<timestamp>.txt
* Commence dying.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further or try building this!
