### ISSUE TITLE
Adding Windows support to the `bin/setup_heroku` script

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#489]

**Comment by liquiddandruff** [comment]
Installed the heroku + ruby environment and most of the bundles until I checked out the setup script... oh the woes of using windoze

**Comment by cantino** [comment]
Were you able to get it working @liquiddandruff?

**Comment by liquiddandruff** [comment]
Like @knu mentioned the setup script would be straight forward to get working (using where.exe instead of which for one), but I gave up and got it going on my linux machine instead since I still needed to build the mysql bundle from source.

**Comment by hakarune** [comment]
Can't get it to install on windows either. Halted on bundle step. no way to execute bundle script on windows

**Comment by cantino** [comment]
My general suggestion on Windows is to use VirtualBox.  Have you tried that
by any chance?

**Comment by irfancharania** [comment]
@hakarune: I grabbed a linux VM from [osboxes](http://www.osboxes.org/) and got it going that way.

**Comment by ylhaven** [comment]
I also meet that problem. I'll try it.
