### ISSUE TITLE
Huginn setup fails while installing better_errors 

### ISSUE THREAD

**Issue by shahamit** [cantino/huginn#500]
After facing issues with setting up huginn on cent os 7, I started setting up it on Ubuntu 14.0.4 in parallel.  I installed ubuntu-14.0.4.1-desktop-amd64.iso image on my virtualbox machine and followed the steps mentioned in Novice set up guide to install huginn. 
At the bundle step, the installation failed with an error that better_errors (2.0.0) cannot be installed. When I tried installing it with 'gem install better_errors -v 2.0.0', this failed stating that ruby version needs to be > 2.0 (while the novice guide mentioned 1.9.3). 
Unfortunately by not being a linux expert I wasn't able to upgrade ruby to 2.0 on my ubuntu vm (I tried a couple of steps though).

Any thoughts on how to proceed?

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further.
