### ISSUE TITLE
Docker Image has an issue at seeding process

### ISSUE THREAD

**Issue by paimpozhil** [cantino/huginn#505]
Hi ,

I was able to created mysql container/ run the initial database creations fine. 

I changed the SECRET_TOKEN and then when i run seed, i get this issue.

root@cloud-server-01:~/huginn# docker run --rm --link huginn-mysql:db \
>   -e "SEED_USERNAME=admin" \
>   -e "SEED_PASSWORD=password" \
>   andrewcurioso/huginn rake db:seed
rake aborted!
Devise.secret_key was not set. Please add the following to your Devise initializer:

  config.secret_key = '06bcd26e007bf5c4f58130493fb78312c2c3b97139a97c95835bc9c58267705ab978ab45403b9ad00bb521771435bc16b415b9db63bc681b09589b48201aac88'

Please ensure you restarted your application after installing Devise or setting the key.
/usr/local/src/huginn/config/routes.rb:58:in `block in <top (required)>'
/usr/local/src/huginn/config/routes.rb:1:in `<top (required)>'
/usr/local/src/huginn/config/environment.rb:8:in `<top (required)>'
Tasks: TOP => db:abort_if_pending_migrations => environment
(See full trace by running task with --trace)

root@cloud-server-01:~/huginn# docker version
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.1
Git commit (client): d84a070
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2.1
Git commit (server): d84a070

**Comment by ianblenke** [comment]
Is this still a docker problem?

**Comment by cantino** [comment]
@dsander is this still an issue?

**Comment by dsander** [comment]
I think this should work now, please re-open if it is still an issue.
