### ISSUE TITLE
Using Huginn with MySQL on Heroku

### ISSUE THREAD

**Issue by bolus** [cantino/huginn#522]
Hi,

I'd like to use Huginn with a MySQL database (I can use MySQL for free).

Is there an easy way to update an "Deploy to Heroku"-button installation to use MySQL instead of Postgres?

If not: How do I deploy a Huginn instance that uses MySQL myself to Heroku?

I've tried to deploy Huginn myself by creating the .env file with the appropriate information an pushing the code to Heroku but I get the following error:

Gem::LoadError: Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).

I'm not a Ruby programmer so a simple solution would be great.

Best regards,
Daniel

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further.
