### ISSUE TITLE
Deleting an agent from the agent's `show` action will redirect to non-existent agent

### ISSUE THREAD

**Issue by amoeba** [cantino/huginn#531]
As in the subject, deleting an agent from the agent's `show` action will attempt to redirect the user back to the agent's `show` action which will result in an error. Is this intended behavior?

A quick scan (I'm new to Huginn) shows that you can only find a link to `destroy` and agent in two locations: (1) the agents list and the agent's `show` action itself. In both cases, the user probably wants to be redirected to the agents list.

The current method in https://github.com/cantino/huginn/blob/master/app/controllers/agents_controller.rb:
 ```
def destroy
    @agent = current_user.agents.find(params[:id])
    @agent.destroy

    respond_to do |format|
      format.html { redirect_back "'#{@agent.name}' deleted" }
      format.json { head :no_content }
    end
  end
```

If you agree, I could PR this.

**Comment by virtadpt** [comment]
It would appear that this bug has reappeared.  I've been able to reproduce it reliably after upgrading to commit a76c68bffbcbd3ec4bea937a87dab9ec7e0cc590.

**Comment by cantino** [comment]
Is this fixed for you @virtadpt?

**Comment by amoeba** [comment]
Just an FYI, I'm not reproducing this with a Huginn instance I refreshed from source two weeks ago.

**Comment by cantino** [comment]
Going to go ahead and close because I believe this is fixed.  Please re-open if not!

**Comment by virtadpt** [comment]
This issue's been dead as disco for many months (the last time it popped up was a regression).  I think it's well and truly done now.
