### ISSUE TITLE
Twitter stream duplicates tweets and case insensitivity

### ISSUE THREAD

**Issue by isaacdd** [cantino/huginn#542]
The agent been sending me the same tweets twice because I have two identical keywords but one is lower case and the other is title case.

To Replicate: create an twitter stream agent that looks for Football and football, you will receive each tweet twice. 

I guess two questions:

1. Is the twitter stream agent case insensitive?
2. Should not duplicate tweets be removed either way? 

Also, if a keyword is a substring of another one, would a duplicate get created?  I have not tested this case myself.

**Comment by cantino** [comment]
I'm going to close this issue since I haven't heard back.
