### ISSUE TITLE
Emoji not accepted in event payloads, error logs

### ISSUE THREAD

**Issue by deanputney** [cantino/huginn#563]
Working on the TumblrBlogAgent today, and one post in my test collection contains some emoji characters. Apparently events.payload, agent_logs.message and delayed_jobs.last_error are unable to handle these types of characters. It may be that just these columns/tables need updating, but it could be the whole database.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further.
