### ISSUE TITLE
A couple of issues with Chef deployment

### ISSUE THREAD

**Issue by hjhart** [cantino/huginn#568]
Hi there,

Just deployed huginn using the chef-setup document here: https://github.com/cantino/huginn/wiki/Deploying-huginn-on-any-server-or-virtualbox-using-chef-solo-and-or-vagrant

I ran into a couple of problems. One was a cookbook not found, and the other was a recipe not existing.

More specifically:

Issue 1)
```
ERROR: Cookbook ark not found. If you're loading ark from another cookbook, make sure you configure the dependency in your metadata
```

Issue 2)
```
Chef::Exceptions::RecipeNotFound
--------------------------------
could not find recipe install_from_binary for cookbook nodejs

```

Temporary solution for issue 1 was adding the `ark` cookbook to the Cheffile and re-running librarian-chef install.

My solution for issue 2 was changing the `huginn_production.rb` role to run the `nodejs_from_binary` recipe instead of the `install_from_binary`, as that no longer exists in the nodejs cookbook. 

I'm bringing these issues to the forum to discuss what should be done. I think solution number 2 feels like I could write a pull request easily, but issue number 1 may need more discussion.

**Comment by cantino** [comment]
We've moved away from Chef to Docker and an official guide.
