### ISSUE TITLE
Document how to use the Manual Event Agent.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#573]
It's trivial to instantiate an instance of the Manual Event Agent but it's not clear how to use it.  Editing the agent and manually entering event parameters into the Options editor isn't the way to do it.  Here is how to use it:
* Instantiate an instance of the Manual Event Agent.
* Wire the Manual Event Agent into the agent under testing.
* Click on the Manual Event Agent in the Agents list.
* Click on Summary.
* Enter a JSON document which describes the event.
* Click the Submit button.
The manually created event will then propagate to the next agent in the chain.

**Comment by virtadpt** [comment]
Just wrote the wiki page using the Github page editor.

https://github.com/cantino/huginn/wiki/Using-the-ManualEventAgent

**Comment by cantino** [comment]
Awesome!  I made a link from the [wiki frontpage](https://github.com/cantino/huginn/wiki).

**Comment by virtadpt** [comment]
Excellent.

**Comment by cantino** [comment]
This should work better now.  Thanks!
