### ISSUE TITLE
Trigger Agent with Values out of Events from another Agent

### ISSUE THREAD

**Issue by Saboti** [cantino/huginn#591]
I have a Question about the Trigger Agent.

First my Scenario:
I have a RSS Agent that grabs RSS Entries in Events. For this Example from a Trailer Page.
In addition I have a Website Agent wich get Filmtitles I have on a Watchlist in Trakt.tv as Entries.

Now I want to set up a Trigger Agent with the Source of the RSS Agent.
But I want to have checked against my Grabbed Website Agent Events as values.
So it Triggers a Event whenever a certain Title is found in the Trailer Page.
Is this possible?

I hope my Problem it's understandable.

Regards Saboti

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further.
