### ISSUE TITLE
Confirmation Agent

### ISSUE THREAD

**Issue by chriseidhof** [cantino/huginn#603]
I am thinking of writing a "confirmation agent". This would receive events, and for every received events, it sends me an email. When I confirm that email, the event gets propagated, when I don't, it gets deleted from the queue.

One possible use-case would be automatically sending out emails to other people, for example, reminders, but I would want to confirm before sending it.

Before I start, I would love to get some feedback. Does anybody think this is a good idea? Anything I should consider?

**Comment by cantino** [comment]
Do you still want this @chriseidhof?

**Comment by chriseidhof** [comment]
I'm not actively using huginn so much anymore, so feel free to close it!

**Comment by cantino** [comment]
Would be curious to find out why you left.

**Comment by chriseidhof** [comment]
Well, I wasn't really using it too much... I get quite excited by new technology, and set up some agents, but all they did was monitor twitter. The weather agent with push notifications turned out to be a bit annoying and I started ignoring it.

Please don't take it as a critique, I think huginn is awesome and I will use it again if I find a good use-case. But right now, I don't have a good use-case for it =)

**Comment by cantino** [comment]
Totally understand. Thanks for the answer!

**Comment by owyongsk** [comment]
I am thinking of implementing an agent like this, but seems like it might involve working with multiple agents. Eg, watch incoming events or see a queue of pending confirmations, send an email (email agent), watch for a confirmation click (webhook agent).

**Comment by mbbrown85** [comment]
+1.

A Confirmation Agent (or something like what is described) is something I have actively wanted.
