### ISSUE TITLE
IMAP Agent causing strange UTF errors

### ISSUE THREAD

**Issue by snicker** [cantino/huginn#613]
Noticed for the second time that my agents were not running for a day or two, logged in to 10k+ jobs queued. Checking logs I find this:
```
Agent#48: Emitting an event for mail: 1414342851139.6367485.12636139.1074898546@backend.cp20.com
Agent#48: Connection closed
Agent#48: Exception during check: "\x99" from ASCII-8BIT to UTF-8 -- ["/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/core_ext/object/json.rb:34:in `encode'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/core_ext/object/json.rb:34:in `to_json'", "/
usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/json-1.8.1/lib/json/common.rb:223:in `generate'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/json-1.8.1/lib/json/common.rb:223:
in `generate'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/json-1.8.1/lib/json/common.rb:394:in `dump'", "/usr/local/huginn/lib/json_with_indifferent_access.rb:7:in `dump'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/attribute_methods/serialization.rb:105:in `serialize'", "/usr/loc
al/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/attribute_methods/serialization.rb:95:in `serialized_value'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/attribute_methods/serialization.rb:181:in `typecasted_attribute_value'", "/usr/local/rvm/gems/ruby-2.0.0-p
353/gems/activerecord-4.1.5/lib/active_record/attribute_methods.rb:433:in `block in arel_attributes_with_values'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/attribute_methods.rb:432:in `each'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/attribu
te_methods.rb:432:in `arel_attributes_with_values'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/attribute_methods.rb:412:in `arel_attributes_with_values_for_create'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/persistence.rb:500:in `_create_reco
rd'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/attribute_methods/dirty.rb:87:in `_create_record'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/callbacks.rb:306:in `block in _create_record'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesuppo
rt-4.1.5/lib/active_support/callbacks.rb:113:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:113:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'", "/usr/local/
rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:215:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/
callbacks.rb:215:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:215:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gem
s/activesupport-4.1.5/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:215:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:215:in `block i
n halting_and_conditional'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:86:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:86:in `run_callbacks'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/
lib/active_record/callbacks.rb:306:in `_create_record'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/timestamp.rb:57:in `_create_record'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/persistence.rb:482:in `create_or_update'", "/usr/local/rvm/gems/
ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/callbacks.rb:302:in `block in create_or_update'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:113:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:113:i
n `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:166:in `block in halting'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:166:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_s
upport/callbacks.rb:166:in `block in halting'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:166:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:166:in `block in halting'", "/usr/local/rvm/gems/ruby-2.0.0-p353/
gems/activesupport-4.1.5/lib/active_support/callbacks.rb:86:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:86:in `run_callbacks'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/callbacks.rb:302:in `create_or_update'", "/usr/l
ocal/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/persistence.rb:125:in `save!'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/validations.rb:57:in `save!'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/attribute_methods/dirty.
rb:29:in `save!'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/transactions.rb:273:in `block in save!'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'", "/usr/local/rvm/gems/ruby-2.
0.0-p353/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/transactions.rb:208:in `transaction'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_r
ecord/transactions.rb:326:in `with_transaction_returning_status'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/transactions.rb:273:in `save!'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/associations/has_many_association.rb:38:in `insert_record'"
, "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:44:in `block (2 levels) in create_record'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/associations/collection_association.rb:389:in `add_to_target'",
"/usr/local/rvm/gems/ruby-2.0.0-p353/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:42:in `block in create_record'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/associations/collection_association.rb:168:in `block in transaction'", "/usr/
local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transactio
n'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.5/lib/active_record/transactions.rb:208:in `transaction'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gem
s/activerecord-4.1.5/lib/active_record/associations/collection_association.rb:167:in `transaction'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:41:in `create_record'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/protected_attributes-1
.0.8/lib/active_record/mass_assignment_security/associations.rb:30:in `create!'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:64:in `create!'", "/usr/local/huginn/app/models/agent.rb:103:in `create_event'", "/usr/local/huginn/app/mod
els/agents/imap_folder_agent.rb:296:in `block in check'", "/usr/local/huginn/app/models/agents/imap_folder_agent.rb:384:in `block (3 levels) in each_unread_mail'", "/usr/local/huginn/app/models/agents/imap_folder_agent.rb:383:in `each'", "/usr/local/huginn/app/models/agents/imap_folder_agent.rb:383:in `block (2 leve
ls) in each_unread_mail'", "/usr/local/huginn/app/models/agents/imap_folder_agent.rb:336:in `each'", "/usr/local/huginn/app/models/agents/imap_folder_agent.rb:336:in `block in each_unread_mail'", "/usr/local/huginn/app/models/agents/imap_folder_agent.rb:442:in `open'", "/usr/local/huginn/app/models/agents/imap_folde
r_agent.rb:325:in `each_unread_mail'", "/usr/local/huginn/app/models/agents/imap_folder_agent.rb:232:in `check'", "/usr/local/huginn/app/models/agent.rb:421:in `async_check'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/performable_method.rb:26:in `perform'", "/usr/local/rvm/gems/ruby-2.0
.0-p353/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:105:in `block in invoke_job'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'", "/usr/local/
rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'", "/usr/local/rvm/g
ems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:102:in `invoke_job'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block (2 levels) in run'", "/usr/local/rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/timeout.rb:66:in `timeout'", "/usr/local/rvm/gems/rub
y-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block in run'", "/usr/local/rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/worker.rb:206:in `run'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_j
ob-4.0.2/lib/delayed/worker.rb:274:in `block in reserve_and_run_one_job'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'", "/usr/local/rvm/gems/ruby-2
.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'", "/usr/local/rvm/gems/ruby-2.0.0-
p353/gems/delayed_job-4.0.2/lib/delayed/worker.rb:274:in `reserve_and_run_one_job'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/worker.rb:190:in `block in work_off'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/worker.rb:189:in `times'", "/usr/local/rvm/gems/r
uby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/worker.rb:189:in `work_off'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/worker.rb:154:in `block (4 levels) in start'", "/usr/local/rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'", "/usr/local/rvm/gems/ruby-2.0.0
-p353/gems/delayed_job-4.0.2/lib/delayed/worker.rb:153:in `block (3 levels) in start'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'", "/usr/local/rv
m/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'", "/usr/local/rvm/gem
s/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/worker.rb:152:in `block (2 levels) in start'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/worker.rb:151:in `loop'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/worker.rb:151:in `block in start'", "/usr/local
/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/plugins/clear_locks.rb:7:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/life
cycle.rb:78:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `block (2 levels) in add'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/li
fecycle.rb:60:in `block in initialize'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `block in add'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/dela
yed/lifecycle.rb:65:in `call'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'", "/usr/local/rvm/gems/ruby-2.0.0-p353/gems/delayed_job-4.0.2/lib/delayed/w
orker.rb:150:in `start'", "bin/threaded.rb:46:in `block (2 levels) in <top (required)>'", "bin/threaded.rb:16:in `safely'", "bin/threaded.rb:43:in `block in <top (required)>'"]
```

happening every 2-3 seconds. Agent #48 is an IMAP agent with the following configuration:
```
{
  "expected_update_period_in_days": "1",
  "host": "imap.gmail.com",
  "ssl": true,
  "port": 993,
  "username": "<omitted>",
  "password": "<omitted>",
  "folders": [
    "INBOX"
  ],
  "conditions": {
  }
}
```

Removing the offending email from my inbox cleared the issue and allowed all queued up jobs to begin processing.

Running Huginn on master from commit 66615897433c383ba928694203c8b0039d2e6f27 which is a bit old (9/27)

This is the second time I have experienced an issue with malformed characters in the IMAP agent causing my entire installation to stop working and queue up pending jobs forever. I will make the suggestion that seems logical: we should treat incoming emails just as any other input; it is untrusted and could be Bad. Verifying/sanitizing/converting text to valid UTF before attempting to send it to a DB or function expecting valid UTF may be the solution

**Comment by cclements** [comment]
I'm getting this error with a heroku build from 2015-03-06.  Was this fix merged into the main branch or do I need to apply it manually?

**Comment by cantino** [comment]
It should have been merged.  Are you erroring in the same spot?

**Comment by cclements** [comment]
Yep, pretty sure.  Agent errors out with:


Exception during check. "\xB7" from ASCII-8BIT to UTF-8: /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/core_ext/object/json.rb:34:in `encode'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/core_ext/object/json.rb:34:in `to_json'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
/app/vendor/bundle/ruby/2.0.0/gems/json-1.8.2/lib/json/common.rb:223:in `generate'
/app/vendor/bundle/ruby/2.0.0/gems/json-1.8.2/lib/json/common.rb:223:in `generate'
/app/vendor/bundle/ruby/2.0.0/gems/json-1.8.2/lib/json/common.rb:394:in `dump'
/app/lib/json_with_indifferent_access.rb:7:in `dump'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods/serialization.rb:110:in `serialize'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods/serialization.rb:100:in `serialized_value'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods/serialization.rb:186:in `typecasted_attribute_value'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods.rb:438:in `block in arel_attributes_with_values'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods.rb:437:in `each'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods.rb:437:in `arel_attributes_with_values'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods.rb:417:in `arel_attributes_with_values_for_create'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/persistence.rb:501:in `_create_record'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:87:in `_create_record'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:306:in `block in _create_record'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:306:in `_create_record'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/timestamp.rb:57:in `_create_record'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/persistence.rb:483:in `create_or_update'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `block in create_or_update'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `create_or_update'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/persistence.rb:125:in `save!'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/validations.rb:57:in `save!'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:273:in `block in save!'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:273:in `save!'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/associations/has_many_association.rb:38:in `insert_record'
/app/vendor/bundle/ruby/2.0.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:44:in `block (2 levels) in create_record'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:389:in `add_to_target'
/app/vendor/bundle/ruby/2.0.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:42:in `block in create_record'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:168:in `block in transaction'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
/app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:167:in `transaction'
/app/vendor/bundle/ruby/2.0.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:41:in `create_record'
/app/vendor/bundle/ruby/2.0.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:30:in `create!'
/app/vendor/bundle/ruby/2.0.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:64:in `create!'
/app/app/models/agent.rb:107:in `create_event'
/app/app/models/agents/imap_folder_agent.rb:296:in `block in check'
/app/app/models/agents/imap_folder_agent.rb:384:in `block (3 levels) in each_unread_mail'
/app/app/models/agents/imap_folder_agent.rb:383:in `each'
/app/app/models/agents/imap_folder_agent.rb:383:in `block (2 levels) in each_unread_mail'
/app/app/models/agents/imap_folder_agent.rb:336:in `each'
/app/app/models/agents/imap_folder_agent.rb:336:in `block in each_unread_mail'
/app/app/models/agents/imap_folder_agent.rb:442:in `open'
/app/app/models/agents/imap_folder_agent.rb:325:in `each_unread_mail'
/app/app/models/agents/imap_folder_agent.rb:232:in `check'
/app/app/models/agent.rb:425:in `async_check'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.2/lib/delayed/performable_method.rb:26:in `perform'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:105:in `block in invoke_job'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:102:in `invoke_job'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block (2 levels) in run'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block in run'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:206:in `run'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:274:in `block in reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60

**Comment by cantino** [comment]
It looks like this is happening on `models/agent.rb:107` in `create_event` when it tries to make a new Event.

You could try editing the `imap_folder_agent.rb` and changing line 296 to something like:

```ruby
          create_event :payload => {
            'folder' => mail.folder,
            'subject' => mail.subject.encode('utf-8', invalid: :replace, undef: :replace, replace: '??'),
            'from' => mail.from_addrs.first,
            'to' => mail.to_addrs,
            'cc' => mail.cc_addrs,
            'date' => (mail.date.iso8601 rescue nil),
            'mime_type' => mime_type,
            'body' => body.encode('utf-8', invalid: :replace, undef: :replace, replace: '??'),
            'matches' => matches,
            'has_attachment' => mail.has_attachment?,
          }
```

Perhaps those `.encode('utf-8', invalid: :replace, undef: :replace, replace: '??')` will help.

**Comment by cclements** [comment]
That fixed it.  Thanks!

**Comment by virtadpt** [comment]
Any word on making this an official patch?  I'm seeing the same error a couple of times an hour.

**Comment by cantino** [comment]
@virtadpt, so this is still happening for you?  I was hoping that @knu's fix in https://github.com/cantino/huginn/commit/49eb43459db750b7a62319e1c0ea29ff404680ca would have fixed it.

**Comment by virtadpt** [comment]
Yup, still happening.

**Comment by cantino** [comment]
@virtadpt Did the amove code fix this for you?

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if this is still happening.
