### ISSUE TITLE
In DataOutputAgent  some information like title and link details got escaped in xml and json file,how to tackle this problem? 

### ISSUE THREAD

**Issue by rselvi** [cantino/huginn#625]
I have created one RSS  agent.In that RSS agent i have given one url rss feed.Rss agent is perfectly working.So,i used that RSS agent as source for DataOutputAgent.My DataOutputAgent shows working.It list xml and json content.But  the feed description,title, and link details of the article got escaped in the xml and json file.In option field i have given only title and description,because i have used RSS agent as source in source tab.
Below output only i am getting as in .json content.
http://localhost:3000/users/1/web_requests/23/a-secret-key.json
{"title":"","description":"Secret hovertext: ","link":"","guid":2437,"pubDate":"Fri, 07 Nov 2014 00:45:57 -0800"}

**Comment by cantino** [comment]
I'm going to close this issue because I haven't heard back.
