### ISSUE TITLE
Build an API

### ISSUE THREAD

**Issue by chriseidhof** [cantino/huginn#626]
Hey everyone,

As discussed in #604 , I want to build an iOS app, and for that, we need an API. Is there a JSON-based way to log in? In principle, I thought this would work:

    curl -H "Content-Type: application/json" -H "Accept: application/json" -d "{'user': { 'email': '$HUGINN_EMAIL', 'password': '$HUGINN_PASSWORD' } }" -X POST $MY_HUGINN_URL/users/sign_in

But this throws an error here:

    ActionDispatch::ParamsParser::ParseError (795: unexpected token at '{'user': { 'email': '', 'password': '' } }'):

I'm not sure what I'm doing wrong. I guess it could have to do with failing CSRF tokens, but it also looks like JSON is not accepted by devise? Any ideas on how I could get this to work? (Once I can do it with curl, it should be easy to do it in Swift).

**Comment by rishabhjain** [comment]
@chriseidhof @dsander `_rails_session` cookie is changing every request(why?), maybe because of that.

**Comment by cantino** [comment]
Are you sending back the cookie when you make a request?  If you don't,
it'll issue a new one.

**Comment by rishabhjain** [comment]
Yeah, I'm sending the cookie back and still getting new different cookie. Weird.

**Comment by cantino** [comment]
Can you show how you're sending it?

**Comment by rishabhjain** [comment]
Here: http://cl.ly/aW7z/Screen%20Recording%202015-04-04%20at%2009%3A34.gif

**Comment by cantino** [comment]
Maybe Rails 4 updates the session cookie on every request to avoid replay attacks?  I seem to remember that.  Is it causing you a problem to have to resend the updated cookie each time?

Clearly this isn't a long term solution for an API.  Better would be a token based API, or oauth.  I owe @dsander some attention to his doorkeeper efforts.

**Comment by cantino** [comment]
@chriseidhof, do you still want this?

**Comment by chriseidhof** [comment]
I think it'd be nice, but feel free to close it for now. If it'll become an issue (pun intended) I'll either ask to reopen or file a new issue!

**Comment by cantino** [comment]
Hopefully #628 or similar will provide this soonish.  Closing for now, but feel free to re-open if/when you need it.
