### ISSUE TITLE
Name "Workflows" ?

### ISSUE THREAD

**Issue by chriseidhof** [cantino/huginn#631]
Hey,

I currently have two pages of agents, so I never use the '/agents' view anymore, but rather use the agent diagram. In that diagram, it seems to me like we could think of a nice name for a group of connected agents. Maybe a group could be called *workflow*? And maybe we could make it so that they can be named?

This'll help keeping an overview, and once we do a mobile app, it might help, too (as a different way to get to your agents).

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further or try building this!

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further or try building this!
