### ISSUE TITLE
How about a general purpose "Just emit an event that looks like this" agent?

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#632]
For a project at work, I'm trying to build an agent network that looks like this:
* Scheduler Agent: Run an agent FOO at 1700 hours local time Monday through Friday
* agent FOO: Emit an event consisting of "message": "Text that only gets printed at 1700 hours Monday through Friday."
* Slack Agent: Take the event "message" from agent FOO and send it to the configured channel.
It's the agent FOO part that's holding me up.  I've tried the ManualEventAgent, but SchedulerAgent won't touch it.  Neither will CommanderAgent.  I've also tried the EventFormattingAgent and JavaScriptAgent classes to do this, and those didn't work with SchedulerAgent or CommanderAgent, either.  I'm not sure if I'm doing something wrong, or if there isn't an Agent type yet that only emits certain events when they're told to.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further or try building this!
