### ISSUE TITLE
What about a way of inverting change detection?

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#633]
ChangeDetectorAgent is great, I use it a lot - something changes, it notices and emits an event.  Great.  But, what about a mode that inverts it, i.e., it emits an event if it's data feed doesn't change in a certain amount of time?  What I'm trying to implement is a monitor for an app to detect when its upstream data source stops feeding it information, meaning that the time_t in the JSON it emits stops updating.  If that time_t doesn't change in ten minutes' time, I'd like to send myself an e-mail to log in and reboot the box it's running on.
Is there sufficient demand to implement this, or would it make better sense to implement it another way?

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further or try building this!
