### ISSUE TITLE
Add JSONpaths support to EventFormattingAgent.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#642]
I'm having some problems extracting data from JSON lists emitted by the DropboxWatchAgent using the EventFormattingAgent.  Here's an example of the JSON I'm fighting with:
```
{
  "added": [ {
    "path": "/path/to/added/file",
    "rev": "1526952fd5",
    "modified": "Fri, 10 Oct 2014 19:00:43 +0000"
  },
  {
    "path": "/path/to/another/added/file",
    "rev": "1526952fd5",
    "modified": "Fri, 14 Oct 2014 19:00:43 +0000"
  }
 ]
}
```
I've lost track of the number of ways I've tried to shoehorn JSONpaths parsing into this agent and I'm a little frustrated; I'm in some pain right now, so I'll admit it could be problems concentrating, but hopefully this ticket will help someone else.  Here are a few of the things I've tried:
* {{ added.path }}
* {% $.added[*].path %}
* {{ $.added[*].path }}
* < $.added[*].path >

Every time, the text my output agent sends is a blank message - nothing coming through even though, looking at events emitted in the agent chain I can see some data percolating through the chain.  This works, but it's not formatted (or formattable) so it's not really useful to me:
* {{added}}

How difficult would it be to add JSONpaths support to the EventFormattingAgent?  Failing that, is there another agent I could splice in between the two to sort this out?  I've investigted the possibility of using DataOutputAgent (not what I need), PeakDetector (which is basically "more events than zero" in this case - I could do it, but it doesn't seem elegant, and peak_spacing could be problematic), TriggerAgent (but then I need to figure out how to get JSON array lengths in JSONpaths, and my research seems to indicate that going opinion is "wrong way to do it").

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further or try building this!
