### ISSUE TITLE
How to resolve the  exception in Adioso Agent?

### ISSUE THREAD

**Issue by rselvi** [cantino/huginn#645]
I have created a Adioso agent.I have defined username and password.While running it throws following exception in the log tab
     Exception during check:  undefined method `gsub' for nil:NilClass

**Comment by Ishfal** [comment]
Just wanted to add a +1 on this... I've reconfirmed log-in information is correct but I get the same result as rselvi above. Also, I attempted to find any information on the Adioso API on their website to no avail, and when trying to directly HTTP GET the Adioso API, my correct log-in info is rejected. Is the AdiosoAgent working for others? Does their API work for others?

**Comment by Ishfal** [comment]
Circling back on this... I've reached out to Adioso to see if the API is still open / available. Doing a little more tracing makes me doubly suspicious that the AdiosoAgent itself is working fine and that the end-point (Adioso) is the issue.

**Comment by cantino** [comment]
Thanks for digging in @Ishfal.  I don't use Adioso, so have no way to test it.

**Comment by rubella** [comment]
I'm getting the same error with the Adioso Agent. Login credentials are confirmed and I've tested the search on the Adioso website without issue.

'undefined method `gsub' for nil:NilClass'

**Comment by cantino** [comment]
It seems like they've turned off their API.  See also https://github.com/cantino/huginn/issues/1088

**Comment by dsander** [comment]
Closing since we removed the Agent 😄
