### ISSUE TITLE
Can't access site with invalid SSL

### ISSUE THREAD

**Issue by vitorbaptista** [cantino/huginn#648]
I've deployed Huginn on Heroku, so I can't add the sites' SSL CA. The way I found to bypass this issue was to change app/concerns/web_request_concern.rb as:

```diff
diff --git a/app/concerns/web_request_concern.rb b/app/concerns/web_request_concern.rb
index 6c6f74c..8372b7b 100644
--- a/app/concerns/web_request_concern.rb
+++ b/app/concerns/web_request_concern.rb
@@ -21,7 +21,7 @@ module WebRequestConcern
   end
 
   def faraday
-    @faraday ||= Faraday.new { |builder|
+    @faraday ||= Faraday.new(ssl: { verify: false }) { |builder|
       builder.headers = headers if headers.length > 0
 
       builder.headers[:user_agent] = user_agent
```

This way Faraday doesn't verify the SSL certificates and everything works.

For a long-term solution, it would be good to add some option to disable SSL verification per-agent. but it would require changes to both the `web_request_concern.rb` and any agents that use it.

Do you think this is a useful feature? Any other ideas on how it could be implemented?

**Comment by cantino** [comment]
@vitorbaptista, do you still need this?

**Comment by vitorbaptista** [comment]
Oh, sorry. I've never came back here to close this issue. This was solved by https://github.com/cantino/huginn/pull/656. Thanks!

**Comment by cantino** [comment]
Great!
