### ISSUE TITLE
Unable to run bundle successfully

### ISSUE THREAD

**Issue by Immortalin** [cantino/huginn#658]
![image](https://cloud.githubusercontent.com/assets/7126128/5331341/484dfb66-7e62-11e4-88f4-e995b586e280.png)

**Comment by jodiecunningham** [comment]
@Immortalin : Change the Gemfile.lock to make eventmachine 1.0.4 instead of 1.0.3.

**Comment by cantino** [comment]
Thanks @jodiecunningham!

If that fixes it @jodiecunningham & @Immortalin, please add `gem 'eventmachine', '1.0.4'` to the Gemfile and run `bundle update eventmachine`.  If that still fixes it, would you mind sending a pull request so everyone can have the fix?

**Comment by breandan** [comment]
`bundle` failed when installing libv8 3.16.14.7 on Windows: 

![image](https://cloud.githubusercontent.com/assets/175716/8764251/b4c2a14c-2d9a-11e5-9023-6fffc43d5ef7.png)

**Comment by cantino** [comment]
We don't support running Huginn directly on Windows.  I recommend using VirtualBox to run Huginn inside of a Linux guest.  Ubuntu is probably easiest.

**Comment by breandan** [comment]
Thanks. If anyone else gets this error, I fixed it by running:

```
gem install libv8 -v '3.16.14.7' -- --with-system-v8
```

[As described here](http://stackoverflow.com/questions/19673714/rails-gem-install-error-error-installing-libv8-error-failed-to-build-gem-nati).

**Comment by breandan** [comment]
+1 @cantino On further inspection, getting this to work on Windows is definitely non-trivial. Would also recommend [the Docker route](https://github.com/cantino/huginn/wiki/Using-huginn-on-predeployed-docker-container).

**Comment by cantino** [comment]
@breandan If you run into any Docker problems, please post new Issues.
