### ISSUE TITLE
Installation project on debian box | RFP

### ISSUE THREAD

**Issue by mawasolutions** [cantino/huginn#665]
All,

looking for someone who is setting up (installing / Configuring) huginn for us ( http://www.mawa-solutions.com ) on a debian Linux box. Yes, we want to pay for this job!

**What we provide:**
* Linux turnkey box with LAMP installed
* ssh root access 
* Database full access
* Local postfix install
* full internet Access

**What need to be accomplished?**
* Install Huginn with all related tools
* Configure E-Mail on local box with postfix

Since we are newbies please let us know if we forgot something.

Please contact us for Offers related to this task.

*Thank you in advance!*
Heiko

**Comment by Zorbash** [comment]
Hey @mawasolutions have you found anyone for this task?

**Comment by cantino** [comment]
Closing since we haven't heard back.
