### ISSUE TITLE
I want to change port from 3000 to 80

### ISSUE THREAD

**Issue by KimJungHun** [cantino/huginn#675]
Hello.

The firewall of our company block 3000 port.

So we have to change it from 3000 to 80 port.

But I can't find how to change it.

Normally, Rails use "rails s -p 80".

But when we start huginn, we use "foreman start". right?

So I can't use "-p 80" option. :(

Please help me. :)

Happy~ New Year~!!

**Comment by cantino** [comment]
Welcome! You can either edit the Procfile, or set the appropriate
environment variable in the .env file.  To launch on port 80 you may
also need to run with sudo, depending on the type of system that you're on.

**Comment by KimJungHun** [comment]
Thank you~ Cantino~! :)
I resolved it. I changed "Procfile".
I added "-p 80" into end of "web: bundle exec rails server".
"web: bundle exec rails server -p 80".
Now, It is working by using 80 port.

**Comment by cantino** [comment]
Glad to hear it @KimJungHun!

**Comment by cantino** [comment]
Please let us know if you have any other questions :smile:
