### ISSUE TITLE
I can't send email by using EmailAgent.

### ISSUE THREAD

**Issue by KimJungHun** [cantino/huginn#676]
Hello. I faced another issue.

I set huginn in AWS.

I changed two file for it.

.env 
SMTP_DOMAIN=gmail.com
SMTP_USER_NAME=clabopen@gmail.com
SMTP_PASSWORD=
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true

config/environments/development.rb
config.action_mailer.perform_deliveries = true # Enable when testing!

So  I faced this error :(

How to resolve this issue? 
Have a nice day~ :)

535-5.7.8 Username and Password not accepted. Learn more at 

/usr/lib/ruby/1.9.1/net/smtp.rb:960:in `check_auth_response'
/usr/lib/ruby/1.9.1/net/smtp.rb:737:in `auth_plain'
/usr/lib/ruby/1.9.1/net/smtp.rb:729:in `authenticate'
/usr/lib/ruby/1.9.1/net/smtp.rb:564:in `do_start'
/usr/lib/ruby/1.9.1/net/smtp.rb:519:in `start'
/var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
/var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
/var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/message.rb:236:in `block in deliver'
/var/lib/gems/1.9.1/gems/actionmailer-4.1.8/lib/action_mailer/base.rb:527:in `block in deliver_mail'
/var/lib/gems/1.9.1/gems/activesupport-4.1.8/lib/active_support/notifications.rb:159:in `block in instrument'
/var/lib/gems/1.9.1/gems/activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/1.9.1/gems/activesupport-4.1.8/lib/active_support/notifications.rb:159:in `instrument'
/var/lib/gems/1.9.1/gems/actionmailer-4.1.8/lib/action_mailer/base.rb:525:in `deliver_mail'
/var/lib/gems/1.9.1/gems/mail-2.6.3/lib/mail/message.rb:236:in `deliver'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/performable_mailer.rb:6:in `perform'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:105:in `block in invoke_job'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:102:in `invoke_job'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block (2 levels) in run'
/usr/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block in run'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:206:in `run'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:274:in `block in reserve_and_run_one_job'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:274:in `reserve_and_run_one_job'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:190:in `block in work_off'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:189:in `times'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:189:in `work_off'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:154:in `block (4 levels) in start'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:153:in `block (3 levels) in start'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:152:in `block (2 levels) in start'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:151:in `loop'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:151:in `block in start'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/plugins/clear_locks.rb:7:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `block (2 levels) in add'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `block in add'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/lib/gems/1.9.1/gems/delayed_job-4.0.2/lib/delayed/worker.rb:150:in `start'
bin/threaded.rb:46:in `block (2 levels) in <top (required)>'
bin/threaded.rb:16:in `safely'
bin/threaded.rb:43:in `block in <top (required)>'

**Comment by cantino** [comment]
Hey @KimJungHun.

A few ideas:

1) Did you also change `config.action_mailer.perform_deliveries` in `config/environments/development.rb`?
2) Is your firewall blocking port 587?
3) Is the password correct? (And you should change the password now since you posted it here...)

**Comment by KimJungHun** [comment]
I wrote wrong data of development.rb file.
I already changed "config.action_mailer.perform_deliveries = true". :(
And I opened all port of AWS.
And I used correct password.
Once, I will try again. :)

**Comment by cantino** [comment]
It's possible the username is just `clabopen`?

**Comment by KimJungHun** [comment]
I tried a variety of ways.
But It is not working. :(

**Comment by cantino** [comment]
I'm sorry, I'm not sure. Logging in the web browser with that exact email
and password definitely works?

**Comment by KimJungHun** [comment]
I resolved issue. :)
I changed two things.
SMTP_PORT=587 -> 465
SMTP_AUTHENTICATION=plain -> login
Thank you for your help :)

**Comment by cantino** [comment]
Very glad that you figured it out! Do you know why you had to change the
port?

**Comment by KimJungHun** [comment]
When I use 587 port, There is no response from the smtp server of gmail. :(

**Comment by cantino** [comment]
Thanks for letting me know, I'll add a note to the docs.

**Comment by Monkey1GIt** [comment]
I have a problem.If I use docker to install huginn, how can I find the .env file and edit it?

**Comment by dsander** [comment]
@Monkey1GIt You can either pass `--env-file .env` or use `-e` to specify indivudual environment variables when starting the docker container.
