### ISSUE TITLE
Docker: Jobs not running with vanilla Docker image

### ISSUE THREAD

**Issue by TFenby** [cantino/huginn#680]
As the title says, doing a `docker run -it -p 5000:5000 cantino/huginn` gets a Huginn image up and running, but background jobs will not run. They just sit in the list.

**Comment by cantino** [comment]
Hey @TFenby, thanks for reporting this. There isn't really anyone working on the Docker deployment right now.  Do you know it well enough to debug?  Also, @ianblenke might have ideas.

**Comment by ianblenke** [comment]
Sounds like we need to spin up some background workers. For that, we'll need a process manager like supervisord. Let me take a quick stab at it.

**Comment by ianblenke** [comment]
It looks like `[ -z DO_NOT_RUN_JOBS ]` is the culprit. Changing that to "-n" fixes it.

I'm refactoring the init script a bit here to exec supervisord and have it spawn children processes to ensure proper signal delivery. Will generate a PR shortly.

**Comment by cantino** [comment]
Awesome @ianblenke, thanks!

**Comment by cantino** [comment]
@TFenby Did #681 fix this for you?

**Comment by TFenby** [comment]
https://github.com/cantino/huginn/pull/681#issuecomment-69746193
:)

**Comment by cantino** [comment]
Ah!  Awesome :smile:
