### ISSUE TITLE
change spring temp path

### ISSUE THREAD

**Issue by fnkr** [cantino/huginn#682]
How to change the `spring` temp path? I do not have write access to `/tmp/spring` because its already used by another user.
I already tried setting `SPRING_TMP_PATH` but it did not work :(
```
./vendor/bundle/ruby/2.1.0/gems/spring-1.1.3/lib/spring/server.rb:22:in `initialize': Permission denied @ rb_sysopen - /tmp/spring/6b84a35523e9b30b31d71464cf104252.pid (Errno::EACCES)
```

**Comment by cantino** [comment]
Good question.  I don't personally use spring -- you could uninstall it and things should work fine.

Perhaps this would work?

https://github.com/rails/spring/issues/127#issuecomment-18048959

**Comment by fnkr** [comment]
Why [is it in the gem file](https://github.com/cantino/huginn/blob/master/Gemfile#L106) if you dont use it?

No, setting `SPRING_TMP_PATH` to a writable path does not work.

**Comment by cantino** [comment]
I don't *personally* use it.  I know some other users do, such as @knu.

**Comment by knu** [comment]
As found in the thread, `SPRING_TMP_PATH` is no longer supported.  `chmod 1777 /tmp/spring` should be the way to go.

I think spring is mainly for (local or personal) development and they do not expect it to be used by many users on a single host.

**Comment by knu** [comment]
If you are on production, you should specify `--without development test` when running `bundle install --deployment` so spring is not installed and used.

**Comment by fnkr** [comment]
I dont have access to `/tmp/spring` since this folder is already owned by another user. But installing bundles with `--without development test` worked for me, thanks!
