### ISSUE TITLE
I have been getting a broken pipe error

### ISSUE THREAD

**Issue by adim86** [cantino/huginn#684]
Everytime I click the run button on an agent i get this error:
Broken pipe - /dev/null /home/deploy/www/cerberus/app/models/agent.rb:198:in `write'

This is the dump from the error. I am stumped to what might cause this. This is occurring immediately after setup, this has never worked. my production environment is Unix, nginx and passenger any help will be greatly appreciated

Broken pipe - /dev/null
/home/deploy/www/cerberus/app/models/agent.rb:198:in `write'
/home/deploy/www/cerberus/app/models/agent.rb:198:in `puts'
/home/deploy/www/cerberus/app/models/agent.rb:198:in `puts'
/home/deploy/www/cerberus/app/models/agent.rb:198:in `log'
/home/deploy/www/cerberus/app/models/agent.rb:203:in `error'
/home/deploy/www/cerberus/app/models/agent.rb:429:in `rescue in async_check'
/home/deploy/www/cerberus/app/models/agent.rb:423:in `async_check'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/performable_method.rb:26:in `perform'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:105:in `block in invoke_job'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:102:in `invoke_job'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block (2 levels) in run'
/usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block in run'
/usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/worker.rb:206:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/worker.rb:274:in `block in reserve_and_run_one_job'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/worker.rb:274:in `reserve_and_run_one_job'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/worker.rb:190:in `block in work_off'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/worker.rb:189:in `times'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/worker.rb:189:in `work_off'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/worker.rb:154:in `block (4 levels) in start'
/usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/worker.rb:153:in `block (3 levels) in start'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/worker.rb:152:in `block (2 levels) in start'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/worker.rb:151:in `loop'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/worker.rb:151:in `block in start'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/plugins/clear_locks.rb:7:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `block (2 levels) in add'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `block in add'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/delayed_job-4.0.2/lib/delayed/worker.rb:150:in `start'
bin/threaded.rb:46:in `block (2 levels) in <top (required)>'
bin/threaded.rb:16:in `safely'
bin/threaded.rb:43:in `block in <top (required)>'

**Comment by cantino** [comment]
Is it possible that it doesn't have write access to STDOUT / STDERR?

**Comment by adim86** [comment]
Sorry I am new at this, how can I check and change this? But I do not see
how this could be possible, the application is running as root.

**Comment by cantino** [comment]
It looks the it's trying to redirect STDOUT to /dev/null and having issues?  How do you have this setup?  Does it work fine for you locally?

**Comment by adim86** [comment]
Yes it works perfect for me locally.

I am using nginx and passenger. I am not sure if that matters I remember the very first time I ran "Foreman start" it said that is could not log into mysql, but then it seemed to work fine after that, I killed the forman process and started it again and it seemed to work fine. I dont know if that has anything to do with it. If I run an agent just as i hit foreman start, it seems to work correctly the first time but then after that, i just keep getting errors

**Comment by cantino** [comment]
So you're just running `foreman start`?  Nothing else?  Is anything being output in the log directory?

**Comment by adim86** [comment]
yes just foreman start, should i be running anything else, in the production log yes, nothing out of the ordinary, just all the logs when a page loads up like:

I, [2015-01-21T06:18:59.521362 #11928]  INFO -- : [b080c222-0609-4757-aa92-5f8fd2a6ba28] Started GET "/jobs" for 197.242.123.195 at 2015-01-21 06:18:59 +0000
I, [2015-01-21T06:18:59.522537 #11928]  INFO -- : [b080c222-0609-4757-aa92-5f8fd2a6ba28] Processing by JobsController#index as */*
I, [2015-01-21T06:18:59.528725 #11928]  INFO -- : [b080c222-0609-4757-aa92-5f8fd2a6ba28]   Rendered jobs/index.html.erb (3.7ms)
I, [2015-01-21T06:18:59.529009 #11928]  INFO -- : [b080c222-0609-4757-aa92-5f8fd2a6ba28] Completed 200 OK in 6ms (Views: 3.6ms | ActiveRecord: 0.7ms)

**Comment by cantino** [comment]
When you click `run`, it's probably triggering a delayed_job. So maybe something with how delayed_job is logging is causing problems... but I'm not sure what.

**Comment by cantino** [comment]
Any luck on this?

**Comment by adim86** [comment]
Nope no luck, i decided to delete the app on my ubuntu server and start
again. One thing I am getting stuck on is this error (whenever i run
foreman
start): /usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/webrick/utils.rb:85:in
`initialize': Address already in use - bind(2) (Errno::EADDRINUSE)
apparently the I have a process running already but i dont know how to kill
that process, any ideas?

**Comment by cantino** [comment]
Perhaps try `top` or `htop` and see if it's somehow running more than once?

**Comment by ayukawa** [comment]
darn ... i have the exact same error here on my localhost (Mac).  Running in development mode.

**Comment by cantino** [comment]
Are you getting the "Address already in use" error?

**Comment by ayukawa** [comment]
I see the exact same as this git issue with the "broken pipe to /dev/null" (but i didn't do a diff).
BTW, my permissions on /dev/null are 666, so I think OK.
Maybe some funkiness with Mac OSX. 
It was complaining about my old ruby gem so I just did a 
gem update --system 
sudo gem pristine --all
It failed with a libxml2 missing error.
Did a brew install libxml2 ... warned about Mac OS having a system copy.
still failing gem pristine --all 
May need to try with special build flags ... maybe time to boot up vagrant.

**Comment by cantino** [comment]
Are you using rvm or rbenv?

**Comment by ayukawa** [comment]
To be honest, I don’t think I’m using either.  I’m very new to Ruby.  More familiar with Django/Python.

**Comment by cantino** [comment]
I'd suggest giving `rvm` a try.

**Comment by ayukawa** [comment]
OK.  Installed rvm.  Did a clean of my system.  Updated everything.  Had a problem with eventmachines that I was only able to fix by going from 1.0.3 to 1.0.4.  I ended up updating the Gemfile.lock.  Finally bundle and rake now complete without errors.
** This I would suggest is something that might be good to validate and then push to the master **
I reference this:
https://github.com/eventmachine/eventmachine/issues/495
But I still have the same problem.  Points to the same line 198 in agent.rb.
I'm now thinking that it may be an artifact of some badly formed agents.

**Comment by ayukawa** [comment]
Progress ... sort of.  Narrowed it down to the RSSAgent.  The feed is good xml.  Or at least the validator here says so (http://validator.w3.org/feed/ ).
If the turn clean = true ... the error goes away.  
There are other limitations of the RSSAgent.  It really shouldn't need one to hack at the agent.rb to accommodate other than the default items.  I've not yet learned enough to know how to update it to parse through all the fields and add them to events.

**Comment by cantino** [comment]
@ayukawa Thanks for your determination!  Would you like to submit a pull request that bumps eventmachine to 1.0.4?  (Otherwise, I will.)

I agree that you shouldn't have to change the source in order to parse RSS.  We'll work on it until that's the case.

**Comment by cantino** [comment]
Hey @ayukawa, looking more closely, I think you should be using a
WebsiteAgent for this, since this isn't a standard RSS feed.  I just
updated the RSSAgent description to clarify this.  If you have any trouble
making it work with the WebsiteAgent, please let me know!

**Comment by ayukawa** [comment]
Try this pull request please.
https://github.com/ayukawa/huginn-cp/pull/1

**Comment by ayukawa** [comment]
There is something still funky with my installation.  I get the same broken pipe error even with the example iTunes website agent.  I was thinking it might be a mysql problem but the database is there, the daemon is running.  Passwords are OK (I updated the database.yml).  
Any ideas on where to look for the problem?

**Comment by space-pope** [comment]
This issue seems to contain a few different topics, but it's not closed yet, so I figured I'd comment here (on the original topic) instead of making a duplicate. I've also been getting a sporadic "Broken pipe" error (on OSX, running `rails server` in the development env):

```
                        Broken pipe @ io_write - <STDOUT>
/<...>/huginn/app/models/agent_log.rb:18:in `write'
```

...complete with that odd spacing in the first line. I've tried on both MySQL and Postgres, having read about an old issue with the ruby MySQL gem; Postgres seemed to fix the issue at first, but then it popped up again. The strange thing is how non-deterministic it seems—most of the time, a job that fails with this error will run when it retries, but occasionally a job will get stuck in the 'broken pipe' state and never complete, no matter whether I re-run it manually or even restart the server entirely.

**Comment by cantino** [comment]
Any chance you're running out of ram or disk space?

**Comment by space-pope** [comment]
Definitely not disk space; RAM...I suppose there's a chance, but swap
should in theory kick in at that point, no? Seems like I also wouldn't be
able to delete the job, kick off a new one, and have that one succeed if it
were a resource issue.

**Comment by cantino** [comment]
Yea, I agree.  That's odd.  This is a broken pipe between Huginn and the DB.  You might try increasing your `DATABASE_POOL` from `5` to `10`.

**Comment by space-pope** [comment]
Thanks for the tip; I'll give that a shot. I haven't noticed any connection timeouts, though; wouldn't I be getting those if the pool were being exhausted?

Along the same lines, I'm wondering what could be causing the starvation...I do have a scenario with 5 or 6 agents chained one after the other and set to propagate immediately; is there a chance that, combined with the scheduler, that scenario could be monopolizing the available connections? If so, I'm wondering if there's something we could do to hand off a connection between agents in a scenario, or agents with a source/target relationship with events set to propagate immediately. After a bit of digging around, though, that doesn't seem terribly straightforward to do...

**Comment by cantino** [comment]
Good question.  Even with immediate propagation, we still call `Agent.async_receive` which makes a new delayed_job, so I wouldn't think so.  Did changing the pool size help at all?

**Comment by space-pope** [comment]
To be honest, I've been down a different rabbit hole the past few days and hadn't really tested out that fix until this morning. It seems to be working just fine in my limited testing so far, but it does give me a bit of pause scalability-wise if I have to make sure my d/b connection pool stays larger than the number of agents that could potentially be running at any given time. I guess that makes sense as a limitation since each agent is an AR instance; maybe I need to revisit the number of agents I want to run concurrently or try to come up with a new kind of forking or chaining agent to get around this.

**Comment by cantino** [comment]
It should just have to be larger than the number of threads + delayed_job workers.

**Comment by space-pope** [comment]
Well, based on the use of `async_receive`, `# of delayed_job workers = (# of receiving agents + # of timed schedules currently firing)`, right?

**Comment by cantino** [comment]
Delayed_job runs a fixed number of workers that process events from the
queue, independent of the length of the queue.  If increasing the pool size
has fixed it, hopefully we were just slightly too low.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further.
