### ISSUE TITLE
Odd git error

### ISSUE THREAD

**Issue by cantino** [cantino/huginn#687]
When deploying to Heroku for the first time using bin/setup_heroku, I received this error:

```
remote: Verifying deploy... done.        
fatal: protocol error: bad line length character: warn
error: error in sideband demultiplexer
To https://git.heroku.com/testing-huginn-2.git
 + 2724bc9...2e9d1c0 master -> master (forced update)
Running database migrations...
Running `rake db:migrate` attached to terminal... up, run.8552
Restarting...
Restarting dynos... done
Done!
```

Anyone seen `fatal: protocol error: bad line length character: warn` before?

**Comment by dsander** [comment]
Never seen one of these before, everything I found about it suggests that the server is mis-configured. To which region did you try to deploy to? I just tested it with 'europe' and had no problems.

**Comment by cantino** [comment]
Very odd.  I just clicked the Heroku button to test it from scratch.  I'll assume it's a one-time Heroku issue.  Thanks for testing!
