### ISSUE TITLE
EmailAgent :message

### ISSUE THREAD

**Issue by lexoyo** [cantino/huginn#688]
Hello

First of all thx for this great project! Very useful! I use it with https://github.com/lexoyo/Monitoshi to monitor and be notified...

In the ```EmailAgent``` config page, it is written

> If the Events’ payloads contain a :message, that will be highlighted, otherwise everything in their payloads will be shown.

When I send an event with this payload, it still sends an email with the whole JSON in the body 

```json
{
  "title": "** PROBLEM Alert - test file is DOWN **",
  "message": "test file Alert: http://preprod.silex.me/test.txt has status Error: HTTPERROR on Tue Jan 27 2015 00:29:03 GMT+0100 (CET)"
}
```

:8ball: why is this? Do I do something wrong?

**Comment by cantino** [comment]
Thanks @lexoyo!

Based on `EmailConcern`, I think that it prioritizes the `message` field as the subject / title, but still sends all additional fields.  It would be pretty easy for you to change / improve-on that behavior if you'd like to give it a try.  I'd be happy to help talk through it.

**Comment by lexoyo** [comment]
Ok, I have tried but I have hard times with ruby :8ball:

**Comment by cantino** [comment]
Sure, I can take a crack at it.  So you'd like an option to specify exactly which fields to send?

**Comment by lexoyo** [comment]
Thank you for your reply
I have this json sent with my request to the web hook
```json
{
  "title": "** RECOVERY Alert - Silex Dropbox auth is UP **",
  "details": "<strong>Alert name<\/strong>: Silex Dropbox auth<br/><strong>Status<\/strong>: 200<br/><strong>URL<\/strong>: http://editor.silex.me/api/v1.0/dropbox/connect<br/><strong>Date<\/strong>: Thu Jan 29 2015 23:34:05 GMT+0000 (UTC)<br/><strong>Type<\/strong>: ping",
  "details_no_html": "Silex Dropbox auth Alert: http://editor.silex.me/api/v1.0/dropbox/connect has status 200 on Thu Jan 29 2015 23:34:05 GMT+0000 (UTC)"
}
```
And ideally, I would send an email with "title" as title, and "details" as email body

**Comment by cantino** [comment]
Hey @lexoyo, would you mind testing #692?  You should be able to set your `subject` key to `{{title}}` and your `body` to `{{details}}`.

**Comment by lexoyo** [comment]
Yeah, that work perfectly !! Thank you @cantino !!
And if you need to monitor website uptime with https://github.com/lexoyo/Monitoshi you will be able to send alerts to twitter or mail with Huginn :green_heart:

**Comment by cantino** [comment]
Great!
