### ISSUE TITLE
How to use "form_configurable"?

### ISSUE THREAD

**Issue by KimJungHun** [cantino/huginn#689]
Hello. I am implementing dropbox_new_file_agent.rb.

So I am using form_configurable.

But I faced issue for "completable" of "form_configurable".

![new_file](https://cloud.githubusercontent.com/assets/10268864/5917354/2ae5388a-a65f-11e4-8da1-64b4482cf3df.JPG)

So I checked it in hipchat agent.
But it is showed same problem.

![room_name](https://cloud.githubusercontent.com/assets/10268864/5917334/eeb9397e-a65e-11e4-85ff-c5e9a0a9a454.jpg)

------------------------------------------------------------------------------------------------
    def complete_directory
      dropbox.ls('/').map { |entry|
        if entry['is_dir']
          {id: entry['path'], text: entry['path']}
        end
      }
    end
------------------------------------------------------------------------------------------------

So I need help for it. :(

**Comment by cantino** [comment]
Hey @KimJungHun!

@dsander, would you mind looking at this?

**Comment by dsander** [comment]
Hi @KimJungHun, it looks like the method is somehow throwing an exception, do you see anything in the `development.log`?

Try adding a `compact` call on the `map` result so the returned array does not contain any `nil` entries.

```
def complete_directory
  dropbox.ls('/').map do |entry|
    if entry['is_dir']
      {id: entry['path'], text: entry['path']}
    end
  end.compact
end
```

**Comment by KimJungHun** [comment]
@dsander Awesome~! :)

Now, It is working. Thank you for your help~!!
