### ISSUE TITLE
Multiple Jobs

### ISSUE THREAD

**Issue by K1773R** [cantino/huginn#691]
Currently it seems only 1 job can run at a time. It would be nice, if multiple jobs can run the same time.
Is this something we can change somewhere or has this to be implemented first?

**Comment by dsander** [comment]
It depends, if you server has enough memory available you can use the [old background job configuration](https://github.com/cantino/huginn/blob/master/Procfile#L9-L13) and change the delayed job command to `bundle exec script/delayed_job -nX run` with `X` being the amount of workers.

I think you need about 200-300MB of memory for every additional woker.

**Comment by K1773R** [comment]
nope, unfortunately still only 1 job is run at a time :S

**Comment by dsander** [comment]
Sorry, you are right, the `-n` argument seems not to work with the `run` command. An option would be to add multiple `scipt/delayed_job run` calls to your Procfile:
```
...
dj: bundle exec script/delayed_job run
dj2: bundle exec script/delayed_job run
...
```
Another solution would be to start delayed_job via `bundle exec script/delayed_job -nX start`, but since that command will daemonize `foreman` can not manage those processes.

**Comment by K1773R** [comment]
this unfortunately also dosnt work, the second instance prints this:
```ERROR: there is already one or more instance(s) of the program running```

**Comment by dsander** [comment]
I am not sure if that will work with foreman, but on my production server i am able to spwan additional workers with `bundle exec rake jobs:work`

**Comment by K1773R** [comment]
seems this is not such a good idea:
```Error while reserving job: Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction: UPDATE `delayed_jobs` SET `delayed_jobs`.`locked_at` = '2015-01-30 **:37:37', `delayed_jobs`.`locked_by` = 'host:huginn pid:9459' WHERE ((run_at <= '2015-01-30 **:37:37' AND (locked_at IS NULL OR locked_at < '2015-01-30 **:17:37') OR locked_by = 'host:huginn pid:9459') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1```

**Comment by dsander** [comment]
That's odd it works on my production instance. I am using postgresql, so it might be a problem with mysql event though the delayed_job docs to not mention any issues with spawning additional works via the `jobs:work` rake command.

Did you try to remove the `dj` command from the Procfile and manually start the workers via `bundle exec script/delayed_job -nX start`?

**Comment by K1773R** [comment]
it also works for me, this just happend once. just a bit worried due to that "deadlock".
will try without dj in Procfile and manually running the workers (rake jobs:work). If i see it again, il report back.

**Comment by K1773R** [comment]
so far, this didnt happen again :)

**Comment by dsander** [comment]
Great, let's hope it was just a hiccup

**Comment by K1773R** [comment]
I think this should be documented before closed, in case others are interested in this too.

**Comment by cantino** [comment]
@K1773R Would you be willing to document it on the wiki?

**Comment by K1773R** [comment]
https://github.com/cantino/huginn/wiki/Concurrent-Jobs---Workers---Agents

My grammar is bad as i'm not a native English speaker. Could you take a look at it and edit it if necessary?

**Comment by cantino** [comment]
I made some edits.  Thanks!

https://github.com/cantino/huginn/wiki/Concurrent-Jobs---Workers---Agents

**Comment by cantino** [comment]
Linked now at https://github.com/cantino/huginn/wiki/Running-Many-Job-Workers

**Comment by cantino** [comment]
Thanks!

**Comment by K1773R** [comment]
Great :)
