### ISSUE TITLE
Bundler fails on mysql2 gem (OS X)

### ISSUE THREAD

**Issue by panicsteve** [cantino/huginn#695]
Steps:

1. Deployed to Heroku using "Deploy to Heroku" button on GitHub project page

(then, on local OS X machine:)

2. heroku git:clone --app my-app-name
3. cd my-app-name
4. bundle

Fetching source index from https://rubygems.org/
Using rake 10.4.2
Using ace-rails-ap 2.0.1
Using i18n 0.7.0
Using json 1.8.1
Using minitest 5.5.0
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.1.8
Using builder 3.2.2
Using erubis 2.7.0
Using actionview 4.1.8
Using rack 1.5.2
Using rack-test 0.6.2
Using actionpack 4.1.8
Using mime-types 1.25.1
Using mail 2.6.3
Using actionmailer 4.1.8
Using activemodel 4.1.8
Using arel 5.0.1.20140414130214
Using activerecord 4.1.8
Using addressable 2.3.6
Using extlib 0.9.16
Using multi_json 1.10.1
Using autoparse 0.3.3
Using bcrypt 3.1.7
Using coderay 1.1.0
Using better_errors 1.1.0
Using debug_inspector 0.0.2
Using binding_of_caller 0.7.2
Using kaminari 0.16.1
Using bundler 1.7.4
Using thor 0.19.1
Using railties 4.1.8
Using hike 1.2.3
Using tilt 1.4.1
Using sprockets 2.11.0
Using sprockets-rails 2.2.2
Using rails 4.1.8
Using bootstrap-kaminari-views 0.0.3
Using buftok 0.2.0
Using eventmachine 1.0.3
Using http_parser.rb 0.6.0
Using simple_oauth 0.2.0
Using cantino-twitter-stream 0.1.15 from git://github.com/cantino/twitter-stream.git (at master)
Using timers 1.1.0
Using celluloid 0.15.2
Using chronic 0.10.2
Using coffee-script-source 1.7.1
Using execjs 2.2.1
Using coffee-script 2.3.0
Using coffee-rails 4.0.1
Using cookiejar 0.3.2
Using rdoc 4.1.1
Using rest-client 1.6.8
Using docile 1.1.5
Using simplecov-html 0.8.0
Using simplecov 0.9.0
Using tins 1.3.2
Using term-ansicolor 1.3.0
Using coveralls 0.7.1
Using safe_yaml 1.0.3
Using crack 0.4.2
Using daemons 1.1.9
Using delayed_job 4.0.2
Using delayed_job_active_record 4.0.2
Using delorean 2.1.0
Using orm_adapter 0.5.0
Using responders 1.1.1
Using warden 1.2.3
Using devise 3.4.0
Using diff-lcs 1.2.5
Using dotenv-deployment 0.0.2
Using dotenv 0.11.1
Using dotenv-rails 0.11.1
Using hashie 2.0.5
Using oauth 0.4.7
Using dropbox-api 0.4.2
Using em-socksify 0.3.0
Using em-http-request 1.1.2
Using em-websocket 0.5.1
Using equalizer 0.0.9
Using polyglot 0.3.5
Using treetop 1.5.3
Using erector 0.10.0
Using ffi 1.9.5
Using ethon 0.7.1
Using multipart-post 2.0.0
Using faraday 0.9.0
Using faraday_middleware 0.9.1
Using hpricot 0.8.6
Using simple-rss 1.3.1
Using feed-normalizer 1.5.2
Using sass 3.2.19
Using font-awesome-sass 4.2.0
Using forecast_io 2.0.0
Using foreman 0.63.0
Using formatador 0.2.5
Using geokit 1.8.5
Using geokit-rails 2.0.1
Using jwt 1.0.0
Using launchy 2.4.2
Using retriable 1.4.1
Using signet 0.5.1
Using uuidtools 2.1.5
Using google-api-client 0.7.1
Using rb-fsevent 0.9.4
Using rb-inotify 0.9.5
Using listen 2.7.9
Using lumberjack 1.0.9
Using method_source 0.8.2
Using slop 3.6.0
Using pry 0.10.1
Using guard 2.6.1
Using guard-livereload 2.2.0
Using rspec-support 3.0.4
Using rspec-core 3.0.4
Using rspec-expectations 3.0.4
Using rspec-mocks 3.0.4
Using rspec 3.0.0
Using guard-rspec 4.3.1
Using multi_xml 0.5.5
Using httparty 0.13.1
Using hipchat 1.2.0
Using httmultiparty 0.3.10
Using http 0.5.1
Using hypdf 1.0.7
Using jquery-rails 3.1.1
Using jsonpath 0.5.6
Using kramdown 1.3.3
Using libv8 3.16.14.7
Using liquid 2.6.1
Using systemu 2.6.4
Using macaddr 1.7.1
Using memoizable 0.4.2
Using mini_portile 0.6.1
Using mqtt 0.3.1

Your user account isn't allowed to install to the system Rubygems.
You can cancel this installation and run:

    bundle install --path vendor/bundle

to install the gems into ./vendor/bundle/, or you can enter your password
and install the bundled gems to Rubygems using sudo.

Password: 

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb 
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lm... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lz... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lsocket... no
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lnsl... no
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lmygcc... no
checking for mysql_query() in -lmysqlclient... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
	--with-mysql-dir
	--without-mysql-dir
	--with-mysql-include
	--without-mysql-include=${mysql-dir}/include
	--with-mysql-lib
	--without-mysql-lib=${mysql-dir}/
	--with-mysql-config
	--without-mysql-config
	--with-mysql-dir
	--without-mysql-dir
	--with-mysql-include
	--without-mysql-include=${mysql-dir}/include
	--with-mysql-lib
	--without-mysql-lib=${mysql-dir}/
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-mlib
	--without-mlib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-zlib
	--without-zlib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-socketlib
	--without-socketlib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-nsllib
	--without-nsllib
	--with-mysqlclientlib
	--without-mysqlclientlib
	--with-mygcclib
	--without-mygcclib
	--with-mysqlclientlib
	--without-mysqlclientlib

Gem files will remain installed in /var/folders/m6/yygnpz9d2yj4wx9x5bt194qr0000gn/T/bundler20150203-28986-1k7131t/mysql2-0.3.16/gems/mysql2-0.3.16 for inspection.
Results logged to /var/folders/m6/yygnpz9d2yj4wx9x5bt194qr0000gn/T/bundler20150203-28986-1k7131t/mysql2-0.3.16/gems/mysql2-0.3.16/ext/mysql2/gem_make.out
An error occurred while installing mysql2 (0.3.16), and Bundler cannot continue.
Make sure that `gem install mysql2 -v '0.3.16'` succeeds before bundling.

**Comment by cantino** [comment]
Hey @panicsteve.  Are you using `rvm` or `rbenv`?

**Comment by panicsteve** [comment]
Hm, I used to have rbenv installed but I think I switched machines since then, and might not have it on the new Mac.

All I really want to do is create an account on my Heroku deployment.  The instructions seemed to indicate I needed a local Huginn dev setup to make this happen.  Possibly I misunderstood?

**Comment by cantino** [comment]
Yea, the local Huginn is used to run `bin/setup_heroku` which provisions the account for you.  Unfortunately Heroku's one-click deploy doesn't support advanced provisioning yet.

You might try install rbenv or rvm.

**Comment by panicsteve** [comment]
Ah, I missed this page about the mysql2 gem error: https://github.com/cantino/huginn/wiki/Novice-setup-guide

For anyone else stopping by, I did approximately the following:

Install rbenv with Homebrew:

$ brew install rbenv ruby-build rbenv-gem-rehash rbenv-default-gems
$ echo 'eval "$(rbenv init -)"' >> ~/.bashrc

Wasn't sure which Ruby version to use, so arbitrarily picked 2.1.0:

$ rbenv install 2.1.0
$ rbenv global 2.1.0

Install mysql with Homebrew:

$ brew install mysql

Install Xcode command line tools:

$ xcode-select --install

Then I could build the mysql2 gem:

$ gem install mysql2 -v '0.3.16'

And re-ran bundler successfully.

$ bundle

**Comment by cantino** [comment]
Glad it worked @panicsteve!

Was there anything else missing from the guide that we should add to that page?

**Comment by panicsteve** [comment]
If you want, I guess you could point people to Homebrew http://brew.sh/ as the easiest way for OS X users to get MySQL installed so the client libraries are available for the mysql2 gem to build successfully.  Other than that, it was pretty straightforward!

**Comment by cantino** [comment]
Will do, thanks!

**Comment by rocking42** [comment]
I know this has been a while but that was the only solution to work for me after searching everything. Thanks heaps mate.

**Comment by mperez-bluechip** [comment]
I second rocking42, I spent 2 days on this b4 your solution worked. Awesome!
