### ISSUE TITLE
Email without body. In GMail

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#699]
Since I updated huginn from the last commit I have been getting emails with out body text. Subject line is ok but once I open the email is blank. I'm using hugin in open shift. 

Is this just me or anyone else having same issue.

**Comment by signallhill** [comment]
I use gmail SMTP like the instruction

**Comment by cantino** [comment]
Hey @signallhill, thanks for letting us know!  I think I broke something.  Could you show me your email agent configuration?

**Comment by signallhill** [comment]
Here it is. I followed the instructions to do this but it has worked until I updated. I have 2 instances of huginn one running the latest update and the other that I have not updated. The old one works fine but the new updated on does not show anything in the body of the email. How can i find out the commit number for the instance so I can reverse? 

{
  "subject": "{{header}}",
  "headline": "{{header}}",
  "expected_receive_period_in_days": "5",
  "recipients": "someone@gmail.com",
  "body": [
    "{{message}}",
    "\" \"",
    "\" \"",
    "{{link}}"
  ]
}

**Comment by signallhill** [comment]
The email agent receives payload from Event Formatting Agent (EFA). When I look at the EFA events I can see that the payload is properly formatted and populated with data when it leaves EFA and into Email Agent. But when the email goes to my inbox, the body of the email is blank.

**Comment by cantino** [comment]
I'm surprised that body formatting worked before? Or was it being ignored?
Please see the help text for the agent now: the body should be a single
string, or you can skip it entirely to have it act how I think it was
acting for you.

**Comment by signallhill** [comment]
It was working before. I removed body and I'm getting the full email now. Thank you.  

Huginn is truly amazing.

**Comment by cantino** [comment]
Sorry about that!  I added the ability for `body` to be a formatted message, and happened to collide with your settings.  `body` wasn't something that already existed, was it?

So glad you like Huginn!
