### ISSUE TITLE
Wiki page on debugging agents

### ISSUE THREAD

**Issue by bennlich** [cantino/huginn#702]
Would it be worth creating a wiki page on debugging techniques? E.g. here are some things @virtadpt mentioned to me on gitter:

* Watch huginn/logs/development.log
* Run the agent manually (Actions -> Run)
* The Logs tab of each agent shows you what's happening in an agent, though only if it outputs anything specifically (like ImapFolderAgent does) or if there's a problem (read: stack trace)
* Usually, only when things go wrong will anything show up in the Logs.
* The Events tab shows you what events an agent has emitted.
* For some agents, I find it useful to plug a ManualEvent agent into its input, craft an event by hand, and use that to force an agent network to run so I can watch it.

Might also be good to know if there are good ways to insert debug log statements into agent behaviors when testing (that are particularly visible in the console output, say).

**Comment by cantino** [comment]
Hey @bennlich, I do think that'd be a good idea.  Would you be interested in starting it?

**Comment by bennlich** [comment]
Sure! Here's a draft: https://github.com/cantino/huginn/wiki/Debugging-an-agent. I bolded information I have questions about. What do you think?

**Comment by bennlich** [comment]
Btw, when I look at `huginn/logs/development.log`, I see something like this:

![log screenshot](http://cl.ly/image/3g33362u4503/Screen%20Shot%202015-02-10%20at%206.41.11%20PM.png)

Any idea what's up with all the ESCs? Is there an editor or viewer I can use to make it easier to read?

**Comment by virtadpt** [comment]
The ESC's are escape sequences that are used to color bits of the text.  The value of your TERM environment variable may not allow colored text so you see the escape codes themselves.  For example, mine displays alternating colored lines (without needing to reconfigure my shell): One that starts with purple text and default colored rest of the line, the other teal text and the rest of the line is bright white instead of default grey.

**Comment by virtadpt** [comment]
`echo $TERM`
What do you get?

**Comment by cantino** [comment]
Thanks @bennlich!  `development.log` can be hard to interpret, but the individual Agents' logs from their show pages are useful.  Those are created by `log` and `error` in the Agents.

The suggestion to use a ManualEventAgent is a very good one.

**Comment by bennlich** [comment]
@virtadpt Ah, I see, thanks. The output in my terminal looks fine (colored). It's just when I open the log for debugging in vim or sublime that I see the escape sequences.

`echo $TERM` gives "xterm-color"

**Comment by bennlich** [comment]
It'd be great if anyone wants to weigh in on the questions I've bolded in https://github.com/cantino/huginn/wiki/Debugging-an-agent. @cantino , I'll mention something about `log` and `error` in there.

**Comment by virtadpt** [comment]
Text editors are notorious for not obeying color codes, because the theory behind them is that it should be possible to edit those codes as well if you wish.  Kind of counter-intuitive, and there's probably a way to reconfigure vim to obey them, but there it is.

**Comment by cantino** [comment]
*[where for output?]* => Generally in the Agent's logs tab.  The Rails console has some info, but it moves fast and is hard to use.

**Comment by bennlich** [comment]
K! Going to close this for now. Could still use a sentence about the difference between log() and errors.add().

**Comment by cantino** [comment]
Sorry, missed that. `log` is used for outputing information to the Agent's log tab.  `errors.log` adds a validation error to the Agent before saving, causing the create / update form to show an error message. (This is a standard Rails pattern.)

**Comment by bennlich** [comment]
Ah, k, cool. Sorry I'm not familiar with rails =P

**Comment by cantino** [comment]
No worries.  It's worth explaining, since many people haven't used Rails!

**Comment by bennlich** [comment]
Speaking of, is it worth adding a line to the Quick Start section of the readme.md (or to a new Develop section) about how to test specs? (And is `bundle exec rspec` the way to go?)

**Comment by cantino** [comment]
Yes please!
