### ISSUE TITLE
SMTP server without auth?

### ISSUE THREAD

**Issue by sapg** [cantino/huginn#703]
Hi,

My SMTP server doesn't require authentication (it is internal only), I've tried leaving the username and password blank in .env but that didn't seem to work, I get a message in my email agent's log telling me that auth failed.

How should I handle this?

Thanks,
Sap

**Comment by cantino** [comment]
Interesting.  Would you mind trying to edit your local copy of [config/smtp.yml](https://github.com/cantino/huginn/blob/master/config/smtp.yml) and deleting the username, password, and authentication lines and see if that helps?

**Comment by virtadpt** [comment]
In my huginn/.env file I have the following:
```
SMTP_DOMAIN=my.huginn.server.example.com
SMTP_USER_NAME=
SMTP_PASSWORD=
SMTP_SERVER=localhost
SMTP_PORT=25
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=false
EMAIL_FROM_ADDRESS=huginn@my.huginn.server.example.com
```
In config/environments/development.rb I've set the config.action_mailer.perform_deliveries directive to 'true'.

**Comment by sapg** [comment]
I tried what virtapt did first but I still got this message - 

"504 5.7.4 Unrecognized authentication type "

Our mail server is in MS Exchange 2010 by the way.

I also tried removing those lines from smtp.yml but I get the same result.  I tried hitting port 25 but I see that 587 is open too so I'll try that.

**Comment by sapg** [comment]
OK, our Exchange admin reckons that it won't support plain auth, MS have removed the functionality.
We set up an "SMTP connector" specifically for this and enforced "basic auth" so I can use the same user account that I use to access the mailbox over plain IMAP (port 143).

So now I've got this (and I've put the lines back in smtp.yml) -

SMTP_DOMAIN=ourcompany.com
SMTP_USER_NAME=msexchangeuser
SMTP_PASSWORD=msexchangepassword
SMTP_SERVER=exchangeserver.internal
SMTP_PORT=25
SMTP_AUTHENTICATION=login
SMTP_ENABLE_STARTTLS_AUTO=true

Still no luck though, I get the error mentioned above in the job status page in Huginn.

**Comment by sapg** [comment]
OK, I found the problem.  I tried to start huginn with `./bin/rails s` at some point in the past so there were some huginn spring processes hanging around, I've killed those and mail is working.

**Comment by cantino** [comment]
Awesome, glad to hear it's working for you now!

**Comment by mhow2** [comment]
I'm having the same problem and I'm not sure to understand how to configure .env file, and if I have to restart huginn after modifications. @cantino what's the official procedure to make huginn to send mails through the local MTA (localhost, *no auth* on port 25) ? Thanks.

**Comment by virtadpt** [comment]
@mhow2, this is how I do just that: https://github.com/cantino/huginn/issues/703#issuecomment-73782770

**Comment by cantino** [comment]
Thanks @virtadpt!

@mhow2, yes, you do need to restart foreman after editing the .env file.

**Comment by mhow2** [comment]
Hi and thanks to both of you. However as I have deployed huginn with Chef Solo there is nothing about foreman. Should I use 'sudo stop/start huginn' ? ('stop' doesn't stop spring, is it normal ?) In addition I see that some SMTP variables are sitting in /etc/init/huginn-jobs-1.conf which means that editing /home/huginn would not be sufficient here (and the documentation at https://github.com/cantino/huginn/wiki/Deploying-huginn-on-any-server-or-virtualbox-using-chef-solo-and-or-vagrant doesn't say how to alter .env within such deployment.

**Comment by cantino** [comment]
Hey @mhow2, you should take a look at https://github.com/cantino/huginn/pull/872.  @elijah is in the process of extracting the Chef Solo system into a separate repo, since it's not super-well supported right now, and @dsander is working on an official guide for installing Huginn (without Chef).
