### ISSUE TITLE
Integration with codename generators for naming agents or populating fields.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#710]
For agent networks which involve lots of data feeds that are substantially identical save for one detail (such as an account name or IP address) it is useful to name each agent that inputs data and emits events uniquely.  The workflow for doing this many dozens or even hundreds of times in a row is somewhat cumbersome.

Would it be possible to somehow integrate http://nsanamegenerator.com/ into the build-an-agent part of Huginn's workflow?

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further or try building this!
