### ISSUE TITLE
Logging ruby hashes as strings

### ISSUE THREAD

**Issue by bennlich** [cantino/huginn#712]
I've been trying to do `log someEvent` or `log someEvent.payload`, and I just discovered that what I really needed was `log JSON.dump(someEvent.payload)`.

The error I was getting when trying to log `someEvent` had to do with `someEvent` having no `scrub!` method.

Is JSON.dump a common way to get a string representation of a hash, or are there other simpler ways of doing this?

**Comment by dsander** [comment]
You could also use `someEvent.payload.inspect`, which converts the hash into a string which looks like the way you would write ruby hash. I would say `inspect` is the more common way if you do not want to pass the JSON to something else.

**Comment by bennlich** [comment]
Ah, awesome! I guess I'm wondering, wouldn't such an inspect function get called automatically when trying to log something?

**Comment by cantino** [comment]
That's a good suggestion @bennlich, I'll try to add that.

**Comment by cantino** [comment]
Would you mind testing on the object_logging branch?

**Comment by bennlich** [comment]
Works!

**Comment by cantino** [comment]
Great!
