### ISSUE TITLE
Not getting emails

### ISSUE THREAD

**Issue by Dyldog** [cantino/huginn#717]
I've just set up Huginn, and I'm not receiving any emails from one of the default digest actions. I've added smpt settings to .env and put a recipient in the options for safety, no dice.

This is the only log I've been able to get out of the digest events:
`Sending digest mail to ***@***.com with events [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]`
I can't see anything related to smtp or email in the shell output.

Is there a log somewhere hiding my error or something?

Any help would be much appreciated.

**Comment by cantino** [comment]
Hey @Dyldog, are you running in development or production mode.  If it's local (in development), you'll need to set config.action_mailer.perform_deliveries in config/environments/development.rb.  Perhaps that's the issue?

**Comment by Dyldog** [comment]
Hey @cantino, 
That definitely got the emails job going. Cheers!
Now where do I put my smtp creds, as I'm getting "534-5.7.9 Application-specific password required. Learn more at **SNIPPED**"
I tried the obvious config/smtp.yml, but that hasn't worked.

**Comment by virtadpt** [comment]
It goes in huginn/.env, in the variables SMTP_USER_NAME and SMTP_USER_NAME and SMTP_PASSWORD.  You'll want to tailor SMTP_AUTHENTICATION and SMTP_ENABLE_STARTTLS_AUTO, too.

**Comment by Dyldog** [comment]
That was it! All working now. Thanks for your help, man.

This probably wasn't the proper channel to get this kind of help, I'd also like to ask you about the kinds of agents you've come up with, so is there a better way for me to contact you? Standard email, perhaps?

Thanks again.

**Comment by cantino** [comment]
Glad to year it!  Let us know if we can help with anything else :smile:
