### ISSUE TITLE
Nothing running

### ISSUE THREAD

**Issue by blacklabelpaul** [cantino/huginn#719]
I'm a complete noob here and eagerly have been trying to get this powerful tool to work.

I run huginn using foreman start

I can login and create agents.

Once the agent has been told to run, it never completes.

Right now I'm showing 7 jobs pending and there isn't anything go on.  For now, I'm using the Twitter agent.  I've given the twitter app read and write privs and have keyed in my API keys into my env file.

I'm a bit unsure which log I should pull up, showing as the development log file is not showing any failures.  I can't clear these jobs either despite deleting the agent they spwaned from.

Would anyone be able to help?  

Thanks!

**Comment by cantino** [comment]
Welcome! It sounds like delayed_job isn't getting started by foreman.  Are
you getting any errors in the console log where you ran foreman?

**Comment by blacklabelpaul** [comment]
First - thank you so much for such a quick response.  I was not expecting that.

Secondly...a slightly new development.

I learned that I had mistakenly created a different account to begin with rather than login as the admin.  After doing that, I could then manage the jobs.

I did a test with the RSS Agent and it worked out of the box.

I then tried using my twitter agent but it still fails.  Verified I have the right API keys in the .env file as well.

Oddly enough, when I start foreman - it says no jobs are found.  Shouldn't it see the default 7 jobs?


13:00:39 web.1  | started with pid 21923
13:00:39 jobs.1 | started with pid 21925
13:00:41 jobs.1 | /usr/local/rvm/gems/ruby-2.2.0/bundler/gems/twitter-stream-1c60a1007c50/lib/twitter/json_stream.rb:27: warning: duplicated key at line 30 ignored: :path
13:00:42 jobs.1 | No agents found.  Will look again in a minute.

**Comment by blacklabelpaul** [comment]
Okay - I deleted my first post because things seem to be moving in the right direction now.

It appears to only be failing on anything calling the Twitter API

When I run a Twitter related agent, a bunch of diag messages spit to the screen.  One of the lines is:

"Agent#14: Exception during check. Could not authenticate you.: /usr/local/rvm/gems/ruby-2.2.0/gems/twitter-5.8.0/lib/twitter/rest/response/raise_error.rb:17:i"

However my API and API secret values match whats on the twitter app page along with my .env file.

Is there a step I seem to be overlooking?

Thank you so much!  I had no expectation of getting such a fast response.

**Comment by cantino** [comment]
You're welcome!

Were you able to make a Service for Twitter in the services menu?

**Comment by blacklabelpaul** [comment]
I was able to make the service - however anything that runs fails with "Could not authenticate you."

So there it's down to authentication but I still unsure why.  

I wound up deleting and trying again multiple times, now I can't make another app until the rate limit allows me to.

Any suggestions as to what to check?  I am using the Consumer and Secret keys, even tried the application tokens, but still failed.

**Comment by cantino** [comment]
Can you show us an obfuscated copy of the .env?

**Comment by blacklabelpaul** [comment]
Other than clearing out my keys...this is pretty much it.  It's all out of the box, but I may be overlooking something.

Thank you so much - you're too kind!

-------


# ==== Required configuration settings for Huginn ====

# Replace the following with the output from "rake secret"
APP_SECRET_TOKEN=df0ddd64b3c4bc545edf39c343309e8d339a4024690de391ff1714adc6fb7a4c0a4cf14ba6ad2fe78a1912cfe1c41827341aefa184300bae0cfcff4b5c1e677e


# This is the domain where your Huginn instance will be running. The default should work
# for development, but it needs to be changed to your Huginn domain when you deploy to a
# production environment (e.g., yourdomain.com, possibly including a port).
DOMAIN=localhost:3000

# Optionally set an asset host
# ASSET_HOST=http://assets.example.com

############################
#      Database Setup      #
############################

DATABASE_ADAPTER=mysql2
DATABASE_ENCODING=utf8
DATABASE_RECONNECT=true
DATABASE_NAME=huginn_development
DATABASE_POOL=5
DATABASE_USERNAME=root
DATABASE_PASSWORD="MyPassWord"
#DATABASE_HOST=your-domain-here.com
#DATABASE_PORT=3306
#DATABASE_SOCKET=/tmp/mysql.sock

# MySQL only: If you are running a MySQL server >=5.5.3, you should
# set DATABASE_ENCODING to utf8mb4 instead of utf8 so that the
# database can hold 4-byte UTF-8 characters like emoji.
#DATABASE_ENCODING=utf8mb4

# ==== Additional required production settings ====

# Configure Rails environment.  This should only be needed in production and may cause errors in development.
# RAILS_ENV=production

# Should Rails force all requests to use SSL?
FORCE_SSL=false

############################
#     Allowing Signups     #
############################

# This invitation code will be required for users to signup with your Huginn installation.
# You can see its use in user.rb.  PLEASE CHANGE THIS!
INVITATION_CODE=automationpaul

#############################
#    Email Configuration    #
#############################

# Outgoing email settings.  To use Gmail or Google Apps, put your Google Apps domain or gmail.com
# as the SMTP_DOMAIN and your Gmail username and password as the SMTP_USER_NAME and SMTP_PASSWORD.
#
# PLEASE NOTE: In order to enable emails locally (e.g., when not in the production Rails environment),
# you must also change config.action_mailer.perform_deliveries in config/environments/development.rb.
# 
# If you have trouble with port 587 on Gmail, you can also try setting
# SMTP_AUTHENTICATION to login and the SMTP_PORT to 465.

SMTP_DOMAIN=your-domain-here.com
SMTP_USER_NAME=you@gmail.com
SMTP_PASSWORD=somepassword
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true

# The address from which system emails will appear to be sent.
EMAIL_FROM_ADDRESS=from_address@gmail.com

###########################
#      Agent Logging      #
###########################

# Number of lines of log messages to keep per Agent
AGENT_LOG_LENGTH=200

########################################################################################################
#    OAuth Configuration                                                                               #
#  More information at the wiki: https://github.com/cantino/huginn/wiki/Configuring-OAuth-applications #
########################################################################################################

TWITTER_OAUTH_KEY=MyConsumerKeyWentHere
TWITTER_OAUTH_SECRET=MyConsumerSecretKeyWentHere

THIRTY_SEVEN_SIGNALS_OAUTH_KEY=
THIRTY_SEVEN_SIGNALS_OAUTH_SECRET=

GITHUB_OAUTH_KEY=
GITHUB_OAUTH_SECRET=

TUMBLR_OAUTH_KEY=
TUMBLR_OAUTH_SECRET=

DROPBOX_OAUTH_KEY=
DROPBOX_OAUTH_SECRET=

#############################
#  AWS and Mechanical Turk  #
#############################

# AWS Credentials for MTurk
AWS_ACCESS_KEY_ID="your aws access key id"
AWS_ACCESS_KEY="your aws access key"

# Set AWS_SANDBOX to true if you're developing Huginn code.
AWS_SANDBOX=false

########################
#   Various Settings   #
########################

# Specify the HTTP backend library for Faraday, commonly used by
# WebsiteAgent, RssAgent and PostAgent.  You can change this depending
# on the performance and stability you need for your service.  Any
# choice other than "typhoeus", "net_http", or "em_http" should
# require you to bundle a corresponding gem via Gemfile.
FARADAY_HTTP_BACKEND=typhoeus

# Specify the default User-Agent header value for HTTP requests made
# by Agents that allow overriding the User-Agent header value.
DEFAULT_HTTP_USER_AGENT="Huginn - https://github.com/cantino/huginn"

# Allow JSONPath eval expresions. i.e., $..price[?(@ < 20)]
# You should not allow this on a shared Huginn box because it is not secure.
ALLOW_JSONPATH_EVAL=false

# Enable this setting to allow insecure Agents like the ShellCommandAgent.  Only do this
# when you trust everyone using your Huginn installation.
ENABLE_INSECURE_AGENTS=true

# Enable this setting to allow second precision schedule in
# SchedulerAgent.  By default, the use of the "second" field is
# restricted so that any value other than a single zero (which means
# "on the minute") is disallowed to prevent abuse of service.
ENABLE_SECOND_PRECISION_SCHEDULE=false

# Specify the scheduler frequency in seconds (default: 0.3).
# Increasing this value will help reduce the use of system resources
# at the expense of time accuracy.
#SCHEDULER_FREQUENCY=0.3

# Use Graphviz for generating diagrams instead of using Google Chart
# Tools.  Specify a dot(1) command path built with SVG support
# enabled.
#USE_GRAPHVIZ_DOT=dot

# Timezone. Use `rake time:zones:local` or `rake time:zones:all` to get your zone name
TIMEZONE="Pacific Time (US & Canada)"

# Number of failed jobs to keep in the database
FAILED_JOBS_TO_KEEP=100

**Comment by cantino** [comment]
Hmm... if you have quotes around `MyConsumerKeyWentHere`, try removing those.  Other than that, I'm not sure what it could be.  You're totally sure you copied the "API Key" and "API Secret" correctly?

(Also, to be super paranoid, you should change your `APP_SECRET_TOKEN` now that it's been posted here with `rake secret`.)

**Comment by blacklabelpaul** [comment]
Thanks - I overlooked the token.  It's since been updated.

I went through and created another twitter account.  Same process as before but different error message.

The change I made was putting my Twitter API keys in quotes.  But now it seems to have beef with my search.  When I add the stream it now says "Exception wrong number of arguments (2 for 0..1)"  

I only have 1 search term added.  I'm so sorry I keep asking questions, I just find this project absolutely incredible with lots of potential so I'm eager to get down to using it.  

Here is the agent, I picked a term I knew that would generate hits and still fails.

{
  "filters": [
    "isis"
  ],
  "expected_update_period_in_days": "2",
  "generate": "events"
}

**Comment by cantino** [comment]
The keys should not be in quotes.

I'm trying to think what else it could be.  You're using the API keys, not
the consumer key, right?

**Comment by blacklabelpaul** [comment]
Thats what I thought, I've since taken those out.

On the app settings page, I'm using the keys that are listed as

Consumer Key (API Key)
Consumer Secret (API Secret)

Perhaps I'm using the wrong keys?  Should I be using the access tokens?

**Comment by cantino** [comment]
No, definitely not the access token.

When you registered for the account did it ask you any other questions
about the site URL or things like that that might be required?

**Comment by blacklabelpaul** [comment]
Yes - it asked me for the URL and Callback.

I filled in the callback URL as mentioned in the file, and I'm able to add the credential OK (after keying in my password it returns to my huginn server)  - so odd.

**Comment by cantino** [comment]
So odd.  @dsander, any ideas?

**Comment by blacklabelpaul** [comment]
What would be the best way to purge everything and start over?  

I've done it a couple of times by using db:purge

Then rvm implode

Then reinstalling everything, but now my agents don't feel like running anymore lol  

Thanks again for all your help, although I haven't been able to get it working, it's been helpful to me to spruce up my rustiness with ssh and ruby.

**Comment by blacklabelpaul** [comment]
Sorry to keep this trailing on so long.

I've done multiple reinstalls. One thing I've noticed is that it tries to install eventmachine 1.0.3, which may not be compatible with Ruby 2.2.

I have to run

bundle update

To get jobs running again.  However, the Twitter stream still fails and I think it's tied to that.  Again, total newb here, but thats where I believe my hiccup is coming from.

Here is the output I'll see when attempting to run my Twitter agent:

15:18:00 jobs.1 | Exception wrong number of arguments (2 for 0..1):
15:18:00 jobs.1 | /usr/local/rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/em/buftok.rb:15:in `initialize'
15:18:00 jobs.1 | /usr/local/rvm/gems/ruby-2.2.0/bundler/gems/twitter-stream-1c60a1007c50/lib/twitter/json_stream.rb:206:in `new'
15:18:00 jobs.1 | /usr/local/rvm/gems/ruby-2.2.0/bundler/gems/twitter-stream-1c60a1007c50/lib/twitter/json_stream.rb:206:in `reset_state'
15:18:00 jobs.1 | /usr/local/rvm/gems/ruby-2.2.0/bundler/gems/twitter-stream-1c60a1007c50/lib/twitter/json_stream.rb:140:in `post_init'
15:18:00 jobs.1 | /usr/local/rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/em/connection.rb:58:in `block in new'
15:18:00 jobs.1 | /usr/local/rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/em/connection.rb:49:in `instance_eval'
15:18:00 jobs.1 | /usr/local/rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/em/connection.rb:49:in `new'
15:18:00 jobs.1 | /usr/local/rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:679:in `bind_connect'
15:18:00 jobs.1 | /usr/local/rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:649:in `connect'
15:18:00 jobs.1 | /usr/local/rvm/gems/ruby-2.2.0/bundler/gems/twitter-stream-1c60a1007c50/lib/twitter/json_stream.rb:65:in `connect'
15:18:00 jobs.1 | /var/www/automation/huginn/lib/twitter_stream.rb:18:in `stream!'
15:18:00 jobs.1 | /var/www/automation/huginn/lib/twitter_stream.rb:65:in `block in load_and_run'
15:18:00 jobs.1 | /var/www/automation/huginn/lib/twitter_stream.rb:54:in `each'
15:18:00 jobs.1 | /var/www/automation/huginn/lib/twitter_stream.rb:54:in `load_and_run'
15:18:00 jobs.1 | /var/www/automation/huginn/lib/twitter_stream.rb:121:in `block in run'
15:18:00 jobs.1 | /usr/local/rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `call'
15:18:00 jobs.1 | /usr/local/rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
15:18:00 jobs.1 | /usr/local/rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
15:18:00 jobs.1 | /var/www/automation/huginn/lib/twitter_stream.rb:104:in `run'
15:18:00 jobs.1 | bin/threaded.rb:29:in `block (2 levels) in <top (required)>'
15:18:00 jobs.1 | bin/threaded.rb:16:in `safely'
15:18:00 jobs.1 | bin/threaded.rb:27:in `block in <top (required)>'
15:18:00 jobs.1 |
15:18:00 jobs.1 | Waiting for a couple of minutes...
15:18:01 jobs.1 | /var/www/automation/huginn/app/concerns/liquid_droppable.rb:24: warning: already initialized constant Kernel::AgentDrop
15:18:01 jobs.1 | /var/www/automation/huginn/app/concerns/liquid_droppable.rb:24: warning: previous definition of AgentDrop was here

**Comment by cantino** [comment]
Have you been running 'bundle update'?  That is, does your Gemfile.lock have a bunch of changes in it?  Perhaps you're on a newer version of something and so you're getting errors.  I can test updating on my system shortly.

**Comment by blacklabelpaul** [comment]
Yes I have been running 'bundle update' 

Here is what it looks like when I run bundle:
.....
Using sprockets-rails 2.2.2
Using rails 4.1.8
Using bootstrap-kaminari-views 0.0.3
Using buftok 0.2.0

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/local/rvm/rubies/ruby-2.2.0/bin/ruby -r ./siteconf20150227-25494-jpcvoo.rb extconf.rb --with-cflags='-O2 -pipe -march=native -w'
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for inotify_init() in sys/inotify.h... yes
checking for writev() in sys/uio.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... no
checking for epoll_create() in sys/epoll.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling rubymain.cpp
compiling pipe.cpp
compiling kb.cpp
compiling cmain.cpp
compiling em.cpp
em.cpp: In member function 'void EventMachine_t::_RunEpollOnce()':
em.cpp:574:37: error: 'rb_thread_select' was not declared in this scope
em.cpp: In member function 'int SelectData_t::_Select()':
em.cpp:827:67: error: 'rb_thread_select' was not declared in this scope
em.cpp: In member function 'void EventMachine_t::_RunSelectOnce()':
em.cpp:946:40: error: 'rb_thread_select' was not declared in this scope
make: *** [em.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.3 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.2.0/extensions/x86_64-linux/2.2.0/eventmachine-1.0.3/gem_make.out
An error occurred while installing eventmachine (1.0.3), and Bundler cannot
continue.
Make sure that `gem install eventmachine -v '1.0.3'` succeeds before bundling.


When I run bundle update, it installs a bunch of other gems..notably:

"Installing eventmachine 1.0.7 (was 1.0.3)"

Here is the full dump of 'bundle update':

# bundle update
Updating git://github.com/cantino/twitter-stream.git
Fetching gem metadata from https://rubygems.org/........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies.......
Using rake 10.4.2
Using ace-rails-ap 2.0.1
Using i18n 0.7.0
Installing json 1.8.2 (was 1.8.1)
Installing minitest 5.5.1 (was 5.5.0)
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.1.8
Using builder 3.2.2
Using erubis 2.7.0
Using actionview 4.1.8
Using rack 1.5.2
Using rack-test 0.6.3 (was 0.6.2)
Using actionpack 4.1.8
Using mime-types 1.25.1
Using mail 2.6.3
Using actionmailer 4.1.8
Using activemodel 4.1.8
Using arel 5.0.1.20140414130214
Using activerecord 4.1.8
Installing addressable 2.3.7 (was 2.3.6)
Using extlib 0.9.16
Installing multi_json 1.7.9 (was 1.10.1)
Using autoparse 0.3.3
Installing bcrypt 3.1.10 (was 3.1.7)
Using coderay 1.1.0
Using better_errors 1.1.0
Using debug_inspector 0.0.2
Using binding_of_caller 0.7.2
Installing kaminari 0.16.3 (was 0.16.1)
Using bundler 1.7.9
Using thor 0.19.1
Using railties 4.1.8
Using hike 1.2.3
Using tilt 1.4.1
Using sprockets 2.12.3 (was 2.11.0)
Using sprockets-rails 2.2.4 (was 2.2.2)
Using rails 4.1.8
Installing bootstrap-kaminari-views 0.0.5 (was 0.0.3)
Using buftok 0.2.0
Installing eventmachine 1.0.7 (was 1.0.3)
Installing http_parser.rb 0.6.0
Installing simple_oauth 0.2.0
Using cantino-twitter-stream 0.1.15 from git://github.com/cantino/twitter-stream.git (at master)
Installing hitimes 1.2.2
Installing timers 4.0.1 (was 1.1.0)
Installing celluloid 0.16.0 (was 0.15.2)
Installing chronic 0.10.2
Installing coffee-script-source 1.9.1 (was 1.7.1)
Installing execjs 2.3.0 (was 2.2.1)
Installing coffee-script 2.3.0
Installing coffee-rails 4.0.1
Installing cookiejar 0.3.2
Using rdoc 4.2.0 (was 4.1.1)
Installing rest-client 1.6.8
Installing docile 1.1.5
Installing simplecov-html 0.9.0 (was 0.8.0)
Installing simplecov 0.9.2 (was 0.9.0)
Installing tins 1.3.4 (was 1.3.2)
Installing term-ansicolor 1.3.0
Installing coveralls 0.7.1
Installing safe_yaml 1.0.4 (was 1.0.3)
Installing crack 0.4.2
Installing daemons 1.1.9
Installing delayed_job 4.0.6 (was 4.0.2)
Installing delayed_job_active_record 4.0.3 (was 4.0.2)
Installing delorean 2.1.0
Installing orm_adapter 0.5.0
Installing responders 1.1.2 (was 1.1.1)
Installing warden 1.2.3
Installing devise 3.4.1 (was 3.4.0)
Installing diff-lcs 1.2.5
Installing dotenv 1.0.2 (was 0.11.1)
Installing dotenv-deployment 0.2.0 (was 0.0.2)
Installing dotenv-rails 1.0.2 (was 0.11.1)
Installing hashie 2.0.5
Installing oauth 0.4.7
Installing dropbox-api 0.4.6 (was 0.4.2)
Installing em-socksify 0.3.0
Installing em-http-request 1.1.2
Installing em-websocket 0.5.1
Installing equalizer 0.0.9
Installing polyglot 0.3.5
Installing treetop 1.5.3
Installing erector 0.10.0
Installing ffi 1.9.6 (was 1.9.5)
Installing ethon 0.7.3 (was 0.7.1)
Installing multipart-post 2.0.0
Installing faraday 0.9.1 (was 0.9.0)
Installing faraday_middleware 0.9.1
Installing hpricot 0.8.6
Installing simple-rss 1.3.1
Installing feed-normalizer 1.5.2
Installing sass 3.2.19
Installing font-awesome-sass 4.3.1 (was 4.2.0)
Installing forecast_io 2.0.0
Installing foreman 0.63.0
Installing formatador 0.2.5
Installing geokit 1.8.5
Installing geokit-rails 2.0.1
Installing jwt 1.3.0 (was 1.0.0)
Installing launchy 2.4.3 (was 2.4.2)
Installing retriable 2.0.2 (was 1.4.1)
Installing signet 0.5.1
Installing uuidtools 2.1.5
Installing google-api-client 0.7.1
Installing rb-fsevent 0.9.4
Installing rb-inotify 0.9.5
Installing listen 2.8.5 (was 2.7.9)
Installing lumberjack 1.0.9
Installing nenv 0.2.0
Installing shellany 0.0.1
Installing notiffany 0.0.6
Installing method_source 0.8.2
Installing slop 3.6.0
Installing pry 0.10.1
Installing guard 2.12.4 (was 2.6.1)
Installing guard-compat 1.2.1
Installing guard-livereload 1.4.0 (was 2.2.0)
Installing rspec-support 3.0.4
Installing rspec-core 3.0.4
Installing rspec-expectations 3.0.4
Installing rspec-mocks 3.0.4
Installing rspec 3.0.0
Installing guard-rspec 4.5.0 (was 4.3.1)
Installing haversine 0.3.0
Installing multi_xml 0.5.5
Installing httparty 0.13.3 (was 0.13.1)
Installing hipchat 1.2.0
Installing httmultiparty 0.3.10
Installing http 0.5.1
Installing hypdf 1.0.7
Installing jquery-rails 3.1.2 (was 3.1.1)
Installing jsonpath 0.5.6
Installing kramdown 1.3.3
Installing libv8 3.16.14.7
Installing liquid 2.6.2 (was 2.6.1)
Installing systemu 2.6.4
Installing macaddr 1.7.1
Installing memoizable 0.4.2
Using mini_portile 0.6.2 (was 0.6.1)
Installing mqtt 0.3.1
Installing mysql2 0.3.18 (was 0.3.16)
Installing naught 1.0.0
Installing net-ftp-list 3.2.8
Using nokogiri 1.6.6.2 (was 1.6.4)
Installing oauth2 0.9.4
Installing omniauth 1.2.2
Installing omniauth-oauth2 1.1.2
Installing omniauth-37signals 1.0.5
Installing omniauth-oauth 1.0.1
Installing omniauth-dropbox 0.2.0
Installing omniauth-tumblr 1.1
Installing omniauth-twitter 1.1.0 (was 1.0.1)
Installing protected_attributes 1.0.8
Installing quiet_assets 1.1.0 (was 1.0.3)
Installing ref 1.0.5
Installing rr 1.1.2
Installing rspec-collection_matchers 1.0.0
Installing rspec-html-matchers 0.6.1
Installing rspec-rails 3.0.2
Installing rturk 2.12.1
Installing uuid 2.3.7
Installing ruby-growl 4.1
Installing rufus-scheduler 3.0.9 (was 3.0.8)
Installing sass-rails 4.0.5 (was 4.0.3)
Installing select2-rails 3.5.9.3 (was 3.5.9.1)
Installing shoulda-matchers 2.8.0 (was 2.7.0)
Installing slack-notifier 1.0.0
Installing spectrum-rails 1.3.4
Installing spring 1.3.3 (was 1.3.2)
Installing spring-commands-rspec 1.0.4 (was 1.0.2)
Installing string-scrub 0.0.5
Installing therubyracer 0.12.1
Installing tumblr_client 0.8.5 (was 0.8.4)
Installing twilio-ruby 3.11.6
Installing twitter 5.8.0
Installing typhoeus 0.6.9
Installing uglifier 2.7.1 (was 2.5.3)
Installing vcr 2.9.3 (was 2.9.2)
Installing webmock 1.17.4
Installing weibo_2 0.1.6
Installing wunderground 1.2.0
Installing xmpp4r 0.5.6
Your bundle is updated!

**Comment by dsander** [comment]
@blacklabelpaul I see that you are using ruby 2.2, we are not testing huginn with that version yet. There also seem to [have been](https://github.com/eventmachine/eventmachine/issues/509) some issues with `eventmachine` and ruby 2.2. If you are able to i would advice to revert your changes to the `Gemfile.lock` and downgrade to ruby 2.1.5.

**Comment by blacklabelpaul** [comment]
Thank you - I will give that a shot.  I had a feeling I was against an
incompatability issue somewhere.

I'll learn how to perform the downgrade tonight :)

**Comment by cantino** [comment]
Agreed.  Also, try reverting your Gemfile.lock changes and just running `bundle`, not `bundle update`.

**Comment by blacklabelpaul** [comment]
Woohoo - The magic was just by running

rvm ruby 2.1.5

My gosh, thank ya'll so much for taking the time to help me out here.  I got it running like a firehose now.

Now my next quest will be learning how to keep this thing running constantly.  Seems like I can only run foreman when SSH'd into the console.

**Comment by cantino** [comment]
Use "screen" or look at the wiki for info on upstart and other tools.
Congrats!

**Comment by virtadpt** [comment]
@blacklabelpaul I run mine inside of a GNU Screen session with `foreman start`.

**Comment by cantino** [comment]
Glad it's working!  Let us know if we can help with anything else.
