### ISSUE TITLE
weibo_2 depends on rest-client (~> 1.6.7), which is insecure.

### ISSUE THREAD

**Issue by cantino** [cantino/huginn#721]
@albertsun @knu Could either of you update the weibo_2 gem to a version that supports the newest `rest-client` so we can bump it in Huginn?

http://www.osvdb.org/show/osvdb/117461

**Comment by albertsun** [comment]
I can take a look at this.

**Comment by cantino** [comment]
Thanks @albertsun!

**Comment by albertsun** [comment]
I opened a pull request on weibo_2 to update their version of rest-client https://github.com/simsicon/weibo_2/pull/21

**Comment by cantino** [comment]
Awesome!
