### ISSUE TITLE
ShellCommandAgent: Broken Pipe

### ISSUE THREAD

**Issue by Dyldog** [cantino/huginn#727]
Basically, when the command a ShellCommandAgents runs takes even a little while, it will fail with one of two broken pipe errors:
Broken pipe - /dev/null or Broken pipe - <STDOUT>

I can get it to happen repeatably with "sleep 10 && echo done" as the command, and "echo done" on it's own works. 

Any ideas?

**Comment by cantino** [comment]
Interesting.  I'd expect it to give you at least 5 minutes before delayed_job times out.  Where are you running this?

**Comment by Dyldog** [comment]
By where, do you mean what path is the command running from? If so, that's /usr/bin, but the same thing happens at the root dir too.

**Comment by cantino** [comment]
No, I mean, is this on a shared system or anywhere that something external might be killing the process?  You're saying it dies in under 10 seconds?

**Comment by Dyldog** [comment]
My mistake man, everything seems to be working now.

The only thing I did different today was run it inside its own subshell. It seems weird that that would make a difference. 

Sorry for wasting your time. I'll poke around a bit and see if I can work out why it was happening before.

**Comment by cantino** [comment]
No problem!  I'd love to hear what you're using it for, and accept any pull requests if you improve the Agent. :)

**Comment by Dyldog** [comment]
ATM, I'm using it to ping a server and make sure it's up. What about you? I'm interested to know what the creator of this beautiful beast has come up with :D

**Comment by cantino** [comment]
I mostly use Huginn to monitor the web for events.  It watches twitter for words I care about, scrapes a few sites into an update email, etc.
