### ISSUE TITLE
UI Agent Consumers

### ISSUE THREAD

**Issue by K1773R** [cantino/huginn#729]
When editing/creating an Agent, you can select the Source already.
It would be cool if its possible to also specify the consumers.

If i create/edit Agents, i lose alot of time editing all the consumers adding the source of my added/edited Agent.

**Comment by cantino** [comment]
I suppose that would be possible.  Usually I think about making a parent Agent before I make any consumers, but I agree for something like an EmailDigestAgent, you could select it when making an Event Source.  Would you want to try adding this?

**Comment by K1773R** [comment]
Yes, i often had this problem with Email{,Digest}Agent, JabberAgent, TriggerAgent or anything that usually has alot of sources.
Im new to ruby, so this aint such a good idea. Tough i want to take a look at it, but dont expect any results.

**Comment by cantino** [comment]
Any Rails tutorial should put you in the right direction.  I'm also happy to work with you to figure out a good approach.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further or try building this!
