### ISSUE TITLE
RSS Agent error

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#731]
There are several errors when my huginn runs RSS agents. But I dont know which agent the error is coming from or what the error means. Please help

"\xE2" from ASCII-8BIT to UTF-8
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/core_ext/object/json.rb:34:in `encode'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/core_ext/object/json.rb:34:in `to_json'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/json-1.8.2/lib/json/common.rb:223:in `generate'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/json-1.8.2/lib/json/common.rb:223:in `generate'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/json-1.8.2/lib/json/common.rb:394:in `dump'
/var/lib/openshift/54/app-root/runtime/repo/lib/json_with_indifferent_access.rb:7:in `dump'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/attribute_methods/serialization.rb:110:in `serialize'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/attribute_methods/serialization.rb:100:in `serialized_value'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/attribute_methods/serialization.rb:186:in `typecasted_attribute_value'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/attribute_methods.rb:438:in `block in arel_attributes_with_values'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/attribute_methods.rb:437:in `each'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/attribute_methods.rb:437:in `arel_attributes_with_values'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/attribute_methods.rb:417:in `arel_attributes_with_values_for_create'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/persistence.rb:501:in `_create_record'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:87:in `_create_record'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:306:in `block in _create_record'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:306:in `_create_record'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/timestamp.rb:57:in `_create_record'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/persistence.rb:483:in `create_or_update'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `block in create_or_update'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `create_or_update'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/persistence.rb:125:in `save!'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/validations.rb:57:in `save!'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/transactions.rb:273:in `block in save!'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/transactions.rb:273:in `save!'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/associations/has_many_association.rb:38:in `insert_record'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:44:in `block (2 levels) in create_record'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:389:in `add_to_target'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:42:in `block in create_record'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:168:in `block in transaction'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:167:in `transaction'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:41:in `create_record'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:30:in `create!'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:64:in `create!'
/var/lib/openshift/54/app-root/runtime/repo/app/models/agent.rb:107:in `create_event'
/var/lib/openshift/54/app-root/runtime/repo/app/models/agents/rss_agent.rb:82:in `block in check'
/var/lib/openshift/54/app-root/runtime/repo/app/models/agents/rss_agent.rb:78:in `each'
/var/lib/openshift/54/app-root/runtime/repo/app/models/agents/rss_agent.rb:78:in `check'
/var/lib/openshift/54/app-root/runtime/repo/app/models/agent.rb:425:in `async_check'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/performable_method.rb:26:in `perform'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:105:in `block in invoke_job'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:102:in `invoke_job'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block (2 levels) in run'
/opt/rh/ruby200/root/usr/share/ruby/timeout.rb:66:in `timeout'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block in run'
/opt/rh/ruby200/root/usr/share/ruby/benchmark.rb:296:in `realtime'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/worker.rb:206:in `run'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/worker.rb:274:in `block in reserve_and_run_one_job'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/worker.rb:274:in `reserve_and_run_one_job'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/worker.rb:190:in `block in work_off'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/worker.rb:189:in `times'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/worker.rb:189:in `work_off'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/worker.rb:154:in `block (4 levels) in start'
/opt/rh/ruby200/root/usr/share/ruby/benchmark.rb:296:in `realtime'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/worker.rb:153:in `block (3 levels) in start'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/worker.rb:152:in `block (2 levels) in start'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/worker.rb:151:in `loop'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/worker.rb:151:in `block in start'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/plugins/clear_locks.rb:7:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `block (2 levels) in add'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `block in add'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/var/lib/openshift/54/app-root/runtime/repo/vendor/bundle/ruby/gems/delayed_job-4.0.2/lib/delayed/worker.rb:150:in `start'
bin/threaded.rb:46:in `block (2 levels) in <top (required)>'
bin/threaded.rb:16:in `safely'
bin/threaded.rb:43:in `block in <top (required)>'

**Comment by virtadpt** [comment]
I see this in some of my agents, also.  It's coming from RSSagent - it's expecting ASCII characters but the RSS or ATOM feed it's getting is comprised of UTF-8 characters.  Interestingly (at least for the feeds I'm pulling) this doesn't seem to be a fatal error, but it does represent a cry for help.

**Comment by signallhill** [comment]
Is there a way to know which of the RSS Agent is giving this error? Is there an agent ID or something that would tell me from the error?

**Comment by virtadpt** [comment]
In my experience, it's on the logging tab of the agent in question.

**Comment by signallhill** [comment]
Yes, after going through all the logs of the agents I see which one is giving the error. Thank you very much for your help.
