### ISSUE TITLE
OpenShift deployment failed with "Could not find thread_safe-0.3.4 in any of the sources (Bundler::GemNotFound)"

### ISSUE THREAD

**Issue by bolus** [cantino/huginn#732]
Hi,

I tried to deploy Huginn to OpenShift by following the steps outlined on [this](https://github.com/cantino/huginn/wiki/Run-Huginn-for-free-on-OpenShift) wiki page.

Everything seemed to work but at the end when creating the admin user I got the following error:

```
Could not find thread_safe-0.3.4 in any of the sources (Bundler::GemNotFound)
```

When I open the Huginn app in my browser I get a "503 Service Unavailable" message.

The full error message is below.

Does anyone know what the problem is and how to fix it?

Best regards,
Daniel

```

I can make an admin user on your new Huginn instance and setup some example Agents.
Should I create a new admin user and some example Agents? (Y/n) 
Okay, what is your email address? foo@bar.com
And what username would you like to login as? foo
Finally, what password would you like to use? 
Just a moment...
/var/lib/openshift/54ff2b495973cae8b6000094/.gem/gems/bundler-1.8.4/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find thread_safe-0.3.4 in any of the sources (Bundler::GemNotFound)
	from /var/lib/openshift/54ff2b495973cae8b6000094/.gem/gems/bundler-1.8.4/lib/bundler/spec_set.rb:85:in `map!'
	from /var/lib/openshift/54ff2b495973cae8b6000094/.gem/gems/bundler-1.8.4/lib/bundler/spec_set.rb:85:in `materialize'
	from /var/lib/openshift/54ff2b495973cae8b6000094/.gem/gems/bundler-1.8.4/lib/bundler/definition.rb:132:in `specs'
	from /var/lib/openshift/54ff2b495973cae8b6000094/.gem/gems/bundler-1.8.4/lib/bundler/definition.rb:177:in `specs_for'
	from /var/lib/openshift/54ff2b495973cae8b6000094/.gem/gems/bundler-1.8.4/lib/bundler/definition.rb:166:in `requested_specs'
	from /var/lib/openshift/54ff2b495973cae8b6000094/.gem/gems/bundler-1.8.4/lib/bundler/environment.rb:18:in `requested_specs'
	from /var/lib/openshift/54ff2b495973cae8b6000094/.gem/gems/bundler-1.8.4/lib/bundler/runtime.rb:13:in `setup'
	from /var/lib/openshift/54ff2b495973cae8b6000094/.gem/gems/bundler-1.8.4/lib/bundler.rb:122:in `setup'
	from /var/lib/openshift/54ff2b495973cae8b6000094/.gem/gems/bundler-1.8.4/lib/bundler/setup.rb:18:in `<top (required)>'
	from /opt/rh/ruby200/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:53:in `require'
	from /opt/rh/ruby200/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:53:in `require'


Okay, you should be all set!  Visit http://foo-bar.rhcloud.com and login as 'foo' with your password.

If you'd like to make more users, you can visit http://foo-bar.rhcloud.com/users/sign_up and use the invitation code:

	foo

We recommend that you read https://github.com/cantino/huginn/wiki/Run-Huginn-for-free-on-OpenShift and setup Pingdom to keep your app awake!

Done!
```

**Comment by cantino** [comment]
Thanks for reporting this, @bolus.  I'll take a look.

**Comment by cantino** [comment]
(I'm on vacation this week, so it may be a week before I look at this.  In the meantime, you should be able to run Huginn locally, or on Heroku, or you could try to figure out what is causing this issue.)

**Comment by cantino** [comment]
So I just checked out the app and ran `bin/setup_openshift` based on [these instructions](https://github.com/cantino/huginn/wiki/Run-Huginn-for-free-on-OpenShift) and it worked without issue.  That's very odd.  Would you mind running it again?

**Comment by bolus** [comment]
Did you use the same source code that someone gets with git clone git@github.com:cantino/huginn.git ?

Because yesterday I tried to deploy Huginn to Heroku with [this](https://github.com/cantino/huginn/wiki/Run-Huginn-for-free-on-Heroku) tutorial and after that with the Heroku button and both versions aren't usable.

The application loads in both cases but I get the error message "We're sorry, but something went wrong." when I click on "Login" or "Signup".

There isn't anything that I can do wrong with the Heroku button, right?

No worries. Enjoy your vacation and then look into it.

Best regards,
Daniel

**Comment by cantino** [comment]
I did use the same code, yes.  I also just went to https://github.com/cantino/huginn and pressed the Heroku button and it launched fine: https://foo.herokuapp.com/users/sign_up

Then I did 

```
heroku git:clone --app foo
cd foo
bundle
bin/setup_heroku
```

and hit return through the prompts (except I said `n` for sendgrid) and it worked.

Can you show me screenshots / logs of where it's failing for you?

**Comment by bolus** [comment]
I tried the Heroku button again and this time it worked.

The setup took quite a bit of time and after the automatic setup finished
and I saw the manual setup instructions I realised what the problem the
last time was.

Basically, I opened the app before the automatic setup was finished because
I thought the progress indicator/interface hanged.

The app was available but there were no manual setup instructions (just the
home page).

Would it make sense if I retry the OpenShift setup?

If it worked for you then the problem was probably on my side.

And I need only one Huginn instance.

Btw., at the end of the manual setup it's recommended to setup Pingdom so
the app stays active.

Wouldn't it be possible to create a WebsiteAgent that requests the app URL
every 30 minutes?

This way one account less is required.

Thanks for your help!

Best regards,
Daniel

2015-03-15 2:17 GMT+01:00 Andrew Cantino <notifications@github.com>:

**Comment by cantino** [comment]
You could definitely try OpenShift again if you want.  We could play with a self-pinging WebsiteAgent, but Heroku sometimes prevents those from counting.

**Comment by bolus** [comment]
I tried the OpenShift deployment again and this time there was no error message.

Very odd.

Maybe the first time there was some kind of network error or I did something wrong like I did with the Heroku button.

Anyway, thanks again for your help.

**Comment by cantino** [comment]
No problem, let us know how you use Huginn!
