### ISSUE TITLE
Issue with IMAP, hugginn on heroku "\xB7" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by aforester** [cantino/huginn#733]
I am currently running into an issue with the IMAP Folder agent on my heroku build. 

                        "\xB7" from ASCII-8BIT to UTF-8
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/core_ext/object/json.rb:34:in `encode'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/core_ext/object/json.rb:34:in `to_json'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
/app/vendor/bundle/ruby/2.2.0/gems/json-1.8.2/lib/json/common.rb:223:in `generate'
/app/vendor/bundle/ruby/2.2.0/gems/json-1.8.2/lib/json/common.rb:223:in `generate'
/app/vendor/bundle/ruby/2.2.0/gems/json-1.8.2/lib/json/common.rb:394:in `dump'
/app/lib/json_with_indifferent_access.rb:7:in `dump'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods/serialization.rb:110:in `serialize'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods/serialization.rb:100:in `serialized_value'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods/serialization.rb:186:in `typecasted_attribute_value'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods.rb:438:in `block in arel_attributes_with_values'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods.rb:437:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods.rb:437:in `arel_attributes_with_values'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods.rb:417:in `arel_attributes_with_values_for_create'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/persistence.rb:501:in `_create_record'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:87:in `_create_record'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:306:in `block in _create_record'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:306:in `_create_record'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/timestamp.rb:57:in `_create_record'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/persistence.rb:483:in `create_or_update'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `block in create_or_update'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `create_or_update'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/persistence.rb:125:in `save!'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/validations.rb:57:in `save!'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:273:in `block in save!'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:273:in `save!'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/associations/has_many_association.rb:38:in `insert_record'
/app/vendor/bundle/ruby/2.2.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:44:in `block (2 levels) in create_record'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:389:in `add_to_target'
/app/vendor/bundle/ruby/2.2.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:42:in `block in create_record'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:168:in `block in transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.8/lib/active_record/associations/collection_association.rb:167:in `transaction'
/app/vendor/bundle/ruby/2.2.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:41:in `create_record'
/app/vendor/bundle/ruby/2.2.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:30:in `create!'
/app/vendor/bundle/ruby/2.2.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:64:in `create!'
/app/app/models/agent.rb:107:in `create_event'
/app/app/models/agents/imap_folder_agent.rb:296:in `block in check'
/app/app/models/agents/imap_folder_agent.rb:384:in `block (3 levels) in each_unread_mail'
/app/app/models/agents/imap_folder_agent.rb:383:in `each'
/app/app/models/agents/imap_folder_agent.rb:383:in `block (2 levels) in each_unread_mail'
/app/app/models/agents/imap_folder_agent.rb:336:in `each'
/app/app/models/agents/imap_folder_agent.rb:336:in `block in each_unread_mail'
/app/app/models/agents/imap_folder_agent.rb:442:in `open'
/app/app/models/agents/imap_folder_agent.rb:325:in `each_unread_mail'
/app/app/models/agents/imap_folder_agent.rb:232:in `check'
/app/app/models/agent.rb:425:in `async_check'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/performable_method.rb:26:in `perform'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:105:in `block in invoke_job'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/backend/base.rb:102:in `invoke_job'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block (2 levels) in run'
/app/vendor/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
/app/vendor/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `call'
/app/vendor/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:207:in `block in run'
/app/vendor/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:206:in `run'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:274:in `block in reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:274:in `reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:190:in `block in work_off'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:189:in `times'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:189:in `work_off'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:154:in `block (4 levels) in start'
/app/vendor/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:153:in `block (3 levels) in start'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:152:in `block (2 levels) in start'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:151:in `loop'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:151:in `block in start'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/plugins/clear_locks.rb:7:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `block (2 levels) in add'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:60:in `block in initialize'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:78:in `block in add'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:65:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/lifecycle.rb:38:in `run_callbacks'
/app/vendor/bundle/ruby/2.2.0/gems/delayed_job-4.0.2/lib/delayed/worker.rb:150:in `start'
bin/threaded.rb:46:in `block (2 levels) in <top (required)>'
bin/threaded.rb:16:in `safely'
bin/threaded.rb:43:in `block in <top (required)>'
                      

	
queued 	7m ago 	<1m ago 	4 	"\xB7" from ASCII-8BIT to UTF-8 	
queued 	<1m ago 	in <1m 	1 	"\xB7" from ASCII-8BIT to UTF-8 	
queued 	2m ago 	in <1m 	3 	"\xB7" from ASCII-8BIT to UTF-8 	
queued 	6m ago 	in 1m 	4 	"\xB7" from ASCII-8BIT to UTF-8 	
queued 	5m ago 	in 2m 	4 	"\xB7" from ASCII-8BIT to UTF-8 	
queued 	4m ago 	in 3m 	4 	"\xB7" from ASCII-8BIT to UTF-8 	
queued 	3m ago 	in 4m 	4 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	37m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	36m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	35m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	32m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	30m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	29m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	28m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	27m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	26m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	25m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	24m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	23m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	22m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	21m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	20m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	19m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	
failed 	18m ago 		5 	"\xB7" from ASCII-8BIT to UTF-8 	

    1
    2
    Next ›
    Last »

**Comment by virtadpt** [comment]
Is it emitting events to downstream agents at the same time?

**Comment by aforester** [comment]
It should be sending to an email agent and a twilio agent but it is not

**Comment by cantino** [comment]
@knu, do you have any ideas on this?

**Comment by virtadpt** [comment]
Is there anything else in the Logs tab?

**Comment by aforester** [comment]
I was able to resolve by editing the imap_folder_agent.rb and changing line 296 to something like:

          create_event :payload => {
            'folder' => mail.folder,
            'subject' => mail.subject.encode('utf-8', invalid: :replace, undef: :replace, replace: '??'),
            'from' => mail.from_addrs.first,
            'to' => mail.to_addrs,
            'cc' => mail.cc_addrs,
            'date' => (mail.date.iso8601 rescue nil),
            'mime_type' => mime_type,
            'body' => body.encode('utf-8', invalid: :replace, undef: :replace, replace: '??'),
            'matches' => matches,
            'has_attachment' => mail.has_attachment?,
          }

**Comment by iecompattest** [comment]
hello

**Comment by knu** [comment]
That would fix the observed problem but broken bytes in a subject or body will cause an error in pattern matching if you have regexp patterns set for subject/body in `conditions`.
I'll look to fixing it by patching the Message class.

**Comment by knu** [comment]
@aforester Could you test the above patch? ([link](https://github.com/cantino/huginn/commit/ede443e89beb899d234bb58a1eb619fb1e7e4a9f.patch))

**Comment by virtadpt** [comment]
+1 - please patch, I'm running in to it, too, with the RSSagent.

**Comment by cantino** [comment]
Thanks @knu!
