### ISSUE TITLE
How to parse RSS content

### ISSUE THREAD

**Issue by wootwoot1234** [cantino/huginn#743]
Hey Guys,

I'm new here and I'm stuck trying to parse some data.  I have an RSS feed that delivers html in the "description" field.  I can't figure out how to parse out (preferably using regex) an image url from the html.

I'm using the RSS agent to get the infomation into huginn but I don't know how to edit the data from there.  I'm sure this is easy to do I just can't figure out how.

Thanks.

**Comment by cantino** [comment]
So you're using an RSSAgent to pull the RSS feed.  Then you want to extract just a portion of the `description`?

**Comment by wootwoot1234** [comment]
Yes, exactly.  I just want to get the image url from the description.  The
description is some (html encoded) html.

**Comment by cantino** [comment]
I think you want RSSAgent -> EventFormattingAgent.

**Comment by wootwoot1234** [comment]
That worked great, thanks!

On a related note, is it possible to do more advanced processing of data?
Is it possible to have code that's run on each event do more complicated
computations with persistent storage.  For example, could it keep a running
tally and fire another event when a number is reached?  I love huginn so
far and I'm interested to see how far I can take it without writing my own
agents.  :)

Thanks again.

**Comment by cantino** [comment]
Great!
