### ISSUE TITLE
Rack 1.5.2 on OpenShift

### ISSUE THREAD

**Issue by mattbarron** [cantino/huginn#744]
I deployed on OpenShift and I am getting a 500 error when I try to open the app. In my ruby.log I am seeing: "You have already activated rack 1.5.2, but your Gemfile requires rack 1.6.0." I did some Googling and found this: https://bugzilla.redhat.com/show_bug.cgi?id=1184179. Looks like rack 1.6.0 is not available for OpenShift.

Does anyone know how to get around this?

**Comment by cantino** [comment]
Odd.  Maybe this got messed up in our Rails upgrade (cc @dsander).  You should be able to edit your Gemfile to use an older version and then run `bundle` before redeploying to OpenShift.

**Comment by dsander** [comment]
Rails 4.2 depends on [rack ~> 1.6](https://github.com/rails/rails/blob/4-2-stable/actionpack/actionpack.gemspec#L24), so I guess we either have to wait for openshift to support rails 4.2 or revert the rails upgrade.

**Comment by cantino** [comment]
We could tag the previous release and use that for OpenShift I guess, or make a branch with the reversion.  That's pretty annoying.

**Comment by dsander** [comment]
Yeah, a separate branch sounds like a plan. The last comment of the OpenShift issue @mattbarron linked does not sound like there is a trivial fix. Pretty strange for a PaaS to not have separate internal and external version dependencies.

**Comment by mattbarron** [comment]
Thanks for the updates!

**Comment by cantino** [comment]
@mattbarron, I reverted the Rails 4.2 upgrade on the openshift branch.  Would you mind trying that branch?

**Comment by mattbarron** [comment]
Works perfect. I am up and running. Thank you!!

**Comment by cantino** [comment]
Glad to hear it!  Hopefully OpenShift fixes this soon.  Maintaining a second branch is a pain.
