### ISSUE TITLE
Make the "perform (e-mail) deliveries" feature an option in .env rather than a code edit.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#747]
From time to time, editing the config/environments/development.rb to set "config.action_mailer.perform_deliveries" to true causes hangups in the process of updating Huginn to the latest version.  It would be helpful if it were an environment variable in the .env file so that editing the code would not be necessary.

**Comment by cantino** [comment]
@virtadpt You can pull from master, add the new option to your `.env` file, and you should be all set.

**Comment by virtadpt** [comment]
Yup.  Working like a charm. :)

**Comment by cantino** [comment]
Awesome!
