### ISSUE TITLE
Make the menu bar at the top dynamic so that parts don't get pushed down.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#748]
The menu bar at the top of Huginn's interface sometimes gets into a state where everything to the left of the search bar is where it's supposed to be, but the search bar and everything to the right get pushed down and obscure parts of the agent documentation and name/title.  I don't know if the HTML that implements this uses static positioning or if it's a CSS glitch or what, but it would be worth looking into.

Resizing my browser doesn't seem to fix the issue.

It seems to happen when the number of queued jobs is in the double digits, the number of jobs in the retry queue is displayed, the number of failed jobs is in the double digits, and an "x new events" bubble is displayed.

**Comment by virtadpt** [comment]
![menu_glitch](https://cloud.githubusercontent.com/assets/639730/6771904/5a7a86c4-d0ab-11e4-9f54-e3b75c5365d3.png)

**Comment by cantino** [comment]
Hopefully f886bdf fixed this.  Mind pulling from master?

**Comment by dsander** [comment]
@virtadpt Do you override the font in your browser or is it the default on of you Linux distribution? 

I am pretty sure I checked the width with 3+ digits in every indicator in d10f21bb79

**Comment by virtadpt** [comment]
No and yes (in that order).  I've even tried it after ^0 to reset the displayed page to defaults.

**Comment by virtadpt** [comment]
I've merged from master/ and that does seem to have fixed it.  I'm looking at 2, 1, 1, and 2 digits up there (respectively) and there doesn't seem to be any menu bar funniness going on.

**Comment by cantino** [comment]
Something odd with the browser on Linux, I think.  We might need you to open the developer tools and play with the CSS in your browser until it fits, then submit a patch.

**Comment by virtadpt** [comment]
Just saw a screen with 3, 1, 2, and 1 in the bubbles, and it looks good.  I think it's fixed.

**Comment by dsander** [comment]
@virtadpt can you check which font, with which size is used in your browser using the developer tools? I am wondering why non of our sans-serif fonts are used. 

Maybe we should supply some google web sans-serif font?

**Comment by virtadpt** [comment]
The dev-tools say "Bookman URW Light" and "Bookman URW Light Italic" for the menu bar.

**Comment by virtadpt** [comment]
I haven't seen this happen in a couple of weeks, this might be a done deal.  Anybody else?

**Comment by cantino** [comment]
I never saw it happen.  I suspect it was a Linux issue?

**Comment by virtadpt** [comment]
Probably.  There were at least three pull-and-merges in between when that was happening and when I stopped seeing it.

**Comment by cantino** [comment]
Glad to hear it!
