### ISSUE TITLE
Delayed Job process, liquid_droppable.rb exception causes a warning.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#749]
The Delayed Job process occasionally throws an exception about having an already initialized constant:
```
19:11:47 dj2.1      | /home/drwho/huginn/app/concerns/liquid_droppable.rb:24: warning: already initialized constant Kernel::AgentDrop
19:11:47 dj2.1      | /home/drwho/huginn/app/concerns/liquid_droppable.rb:24: warning: previous definition of AgentDrop was here
19:11:47 dj.1       | /home/drwho/huginn/app/concerns/liquid_droppable.rb:24: warning: already initialized constant Kernel::AgentDrop
19:11:47 dj.1       | /home/drwho/huginn/app/concerns/liquid_droppable.rb:24: warning: previous definition of AgentDrop was here
19:11:47 dj2.1      | /home/drwho/huginn/app/concerns/liquid_droppable.rb:24: warning: already initialized constant Kernel::EventDrop
19:11:47 dj2.1      | /home/drwho/huginn/app/concerns/liquid_droppable.rb:24: warning: previous definition of EventDrop was here
19:11:47 dj.1       | /home/drwho/huginn/app/concerns/liquid_droppable.rb:24: warning: already initialized constant Kernel::EventDrop
19:11:47 dj.1       | /home/drwho/huginn/app/concerns/liquid_droppable.rb:24: warning: previous definition of EventDrop was here
```
I've configured Huginn to run multiple Delayed Job processes so this may have something to do with it but I'm not sure.  Is there something I can do to get better debugging information?

**Comment by dsander** [comment]
Thos are just warnings, nothing to worry about. I will try to get rid of them.

**Comment by dsander** [comment]
I remember seeing those warning locally before, but now I can't reproduce them.

**Comment by virtadpt** [comment]
What commit are you running right now, @dsander?

**Comment by dsander** [comment]
I think that was f886bdf00d2cfb0b60ac63016679e3dacb16d9ad

**Comment by dsander** [comment]
Interestingly enough, if had the same issue again today :smile: 

@virtadpt  It looks like you are running your workers in the development environment. It might help the memory usage and overall performance to run them in production via `export RAILS_ENV=production; bundle exec script/delayed_job run`

**Comment by virtadpt** [comment]
Hmmm... are there official instructions for kicking into production mode?  I tried a few weeks ago (after doing some research) and hosed my instanance pretty badly.

**Comment by dsander** [comment]
I think there is none for 'manual' deployment. All that needs to be done is to copy your development settings in the `database.yml` to the production section and then starting delayed_job with the command above.

**Comment by cantino** [comment]
Don't you need to bundle assets too?

**Comment by dsander** [comment]
@cantino Not if you just run delayed job in production

**Comment by cantino** [comment]
Oh, interesting.  Do you think we should somehow make that a default?

**Comment by dsander** [comment]
Unsure, it might be nice to have the verbose development log by default.
