### ISSUE TITLE
Twitter Service Authentication says something went wrong

### ISSUE THREAD

**Issue by Nateliason** [cantino/huginn#753]
Tried authenticating with Twitter per the O-Auth instructions. Plugged in my Key and Secret, but when I go to services and click the "authenticate with Twitter" button it just says "We're Sorry, but Something Went Wrong"

Any idea what might be causing this?

**Comment by cantino** [comment]
Did you set the callback url as well to something like `https://localhost:3000/auth/twitter/callback`?

**Comment by Nateliason** [comment]
I'm using Heroku, would I still set that as the callback URL?

**Comment by cantino** [comment]
You'd set the one for your Heroku application, then.  you.herokuapp.com, or whatever

**Comment by Nateliason** [comment]
kk I'll try that

**Comment by Nateliason** [comment]
That did it, thanks!!

**Comment by cantino** [comment]
Great!  Is there somewhere we should make the more clear in the documentation to help the next user?

**Comment by Nateliason** [comment]
Maybe mention it here: https://github.com/cantino/huginn/wiki/Configuring-OAuth-applications that they need to set the callback as well.
