### ISSUE TITLE
API key management

### ISSUE THREAD

**Issue by crawfordcomeaux** [cantino/huginn#76]
It seems like it'd be worth discussing ways to allow for easy API key management. One thing to keep in mind is the distinction between app keys & user keys: correct me if I'm wrong, but I think a single Huginn deployment can be configured with a single Twitter consumer key & consumer secret, but oauth creds for each user. 

My thoughts:

Quick & dirty:  App keys go in .env, user keys get their own fields on the Account screen.

Better: Same as above, but separate API keys view and menu item to the Account dropdown.

Betterer: Same as above, but user keys can be accessed/modified from agent creation page and get cached for future instances of that agent. If the user is the admin, keys for the app will be available there, too.

**Comment by cantino** [comment]
Closing.  We have Credentials and are fairly 12-factor.  We could add a Liquid tag to access the ENV if needed.
