### ISSUE TITLE
Agents not running on heroku.

### ISSUE THREAD

**Issue by wootwoot1234** [cantino/huginn#760]
I have huginn running on heroku but my agents aren't running automatically.  I setup a cron job from another server to load/ping huginn every minute but that doesn't seem to have worked.  Is there a specific url I should be pinging and is every minute enough or too much?

Thanks.

**Comment by cantino** [comment]
Every minute should be more than enough. I'm surprised that's not working.
Is there anything in your "heroku logs"?

**Comment by wootwoot1234** [comment]
Thanks for writing back.

There isn't anything in the logs that suggest there are any errors and nothing during the time when it's scheduled to run.  Is there a specific url I should be pinging or is the root url (main page) fine?  It's only a few days old but maybe I should update it?

**Comment by cantino** [comment]
You could try hitting `/users/sign_in`instead, but I do find that strange.  Does it correctly run scheduled Agents when you're actively using it?

**Comment by wootwoot1234** [comment]
I have my agents set to run every 5 hours.  It ran correctly last time but
I was actively using huginn.  I'm going to leave it alone for 5 or 10 hours
and see if it runs on it's own.  I'll also check on the cron job and make
sure it's running correctly.

**Comment by wootwoot1234** [comment]
Looks like that fixed it.  Thanks!

**Comment by cantino** [comment]
Great!
