### ISSUE TITLE
Only listening on localhost

### ISSUE THREAD

**Issue by McGriddle** [cantino/huginn#761]
Since updating to the latest commit (currently 1832a9acfec89a315579fdde0fad6afa81ca0331), it looks like the domain setting in my .env is no longer being used.
`netstat --listen` shows that the machine is listening on localhost:3000. I can confirm that huginn is running as I can access it if via ssh port forwarding on localhost:3000.

To update I did the following
```
git pull
RAILS_ENV="production" bundle exec rake db:migrate
```

I've tried setting the domain to 0.0.0.0, the actual IP, and the hostname to no avail. Am I missing a new setting?

**Comment by cantino** [comment]
The `DOMAIN` in `.env` doesn't affect listening interface or port, only URLs in the app.  That shouldn't have changed.  Rails normally only listens locally when running in development mode.  Had you changed that somehow?

**Comment by dskzz** [comment]
I am having same problem.  This is my first attempt with (maddening!) ruby; I think I've done everything right. Not 100% if I've set this up as production.  here from my netstat:
tcp        0      0 127.0.0.1:3000          0.0.0.0:*               LISTEN      8361/ruby

I can access it from my localhost, but that's just a server and I don't want to run huginn through lynx or set up a proxy or something like that.  I was ready to assume I was the problem but this post made be think maybe not. 

Thanks really looking forward to digging in with this program.  Props on the nordic thing

**Comment by cantino** [comment]
Are you running in development or production mode?

**Comment by dskzz** [comment]
Honestly, being new to Ruby, I am not sure. I uncommented
the RAILS_ENV=production line in .env

On Mon, Mar 30, 2015 at 2:31 AM, Andrew Cantino <notifications@github.com>
wrote:

> Are you running in development or production mode?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cantino/huginn/issues/761#issuecomment-87569896>.
>



-- 
DM
www.gall-holl.com
201-394-7641

Confidentiality Warning: This e-mail contains information intended only for
the use of the individual or entity named above. If the reader of this
e-mail is not the intended recipient or the employee or agent responsible
for delivering it to the intended recipient, or the intended recipient has
not been authorized to disseminate or reproduce this email, then any
dissemination, publication or copying of this e-mail is strictly
prohibited. The sender does not accept any responsibility for any loss,
disruption or damage to your data or computer system that may occur while
using data contained in, or transmitted with, this e-mail. If you have
received this e-mail in error, please immediately notify us by return
e-mail. Thank you.-

**Comment by cantino** [comment]
If you're deploying, you should run in `production`, but then you'll need to bundle assets.  If you're running in `development`, it should serve on port 3000 on localhost, which one could proxy-pass to from nginx.  But you don't really want to run Rails in development and open to the world, as it exposes security issues.  Please see https://github.com/cantino/huginn/wiki#deploying-huginn

**Comment by dskzz** [comment]
Appreciate the help.  Is there a way, a line of code or something I can
change to make it run on 0.0.0.0 without going production mode?  I'm not
worried about security, I can ipfilter the traffic.

On Tue, Mar 31, 2015 at 5:34 PM, Andrew Cantino <notifications@github.com>
wrote:

> If you're deploying, you should run in production, but then you'll need
> to bundle assets. If you're running in development, it should serve on
> port 3000 on localhost, which one could proxy-pass to from nginx. But you
> don't really want to run Rails in development and open to the world, as it
> exposes security issues. Please see
> https://github.com/cantino/huginn/wiki#deploying-huginn
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cantino/huginn/issues/761#issuecomment-88256987>.
>



-- 
DM
www.gall-holl.com
201-394-7641

Confidentiality Warning: This e-mail contains information intended only for
the use of the individual or entity named above. If the reader of this
e-mail is not the intended recipient or the employee or agent responsible
for delivering it to the intended recipient, or the intended recipient has
not been authorized to disseminate or reproduce this email, then any
dissemination, publication or copying of this e-mail is strictly
prohibited. The sender does not accept any responsibility for any loss,
disruption or damage to your data or computer system that may occur while
using data contained in, or transmitted with, this e-mail. If you have
received this e-mail in error, please immediately notify us by return
e-mail. Thank you.-

**Comment by cantino** [comment]
Try editing `Procfile` and changing the `web:` line to `web: bundle exec rails server --binding=0.0.0.0 --port=80`

**Comment by cantino** [comment]
Did you solve this issue?

**Comment by nosybore** [comment]
Had the same issue - I found this helpful. Thanks.

**Comment by HiddenKn** [comment]
Thanks! I have been looking for this all day.

**Comment by cantino** [comment]
@dsander I don't think I really understand local Rails port binding.  Do you know if we should change a default around this?

**Comment by dsander** [comment]
@cantino Do you mean port or interface binding? I think we could change the default web command to bind on `0.0.0.0`

**Comment by cantino** [comment]
Interface, I guess.  Is the issue that Rails, by default, binds to localhost instead of 0.0.0.0, and that causes problems?

**Comment by Puneeth-n** [comment]
I was also looking for this and was chaining the env file to listen to all ports.

**Comment by cantino** [comment]
I guess we should change this then.  I don't fully understand when it's needed and when it's not.

**Comment by dsander** [comment]
I agree we should change the default.

@cantino Maybe you are used to using `unicorn` in development? unicorn binds to 0.0.0.0 per default whereas `thin` just binds to localhost

**Comment by cantino** [comment]
@dsander I always just run `foreman start`
