### ISSUE TITLE
JSONPath help

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#764]
Hi I have a webhook agent receiving post but the payload is blank. I think it has to do with the payload_path not being correct. Below is the raw data that is being posted, can someone help me with the path I need to put to get the payload. I am trying to get the title, description, location and date. 

{"name":"Hill","count":69,"frequency":"Daily","version":12,"newdata":true,"lastrunstatus":"partial","lastsuccess":"Sun Mar 29 2015 19:10:48 GMT+0000 (UTC)","thisversionstatus":"partial","nextrun":"Mon Mar 30 2015 19:10:48 GMT+0000 (UTC)","thisversionrun":"Sun Mar 29 2015 19:10:48 GMT+0000 (UTC)","results":{"collection1":[{"title":{"text"some title"","href"http:// link""},"description":"1 2 3 4 5 6 7 8 9","location":"1 2 3 4 5 6 7 8 9","date":{"text":"1 2 3 4 5 6 7 8 9","href":"javascript:__doPostBack('DataGrid1$_ctl1$_ctl1','')"},"url":"http://ng.com"},{"title":{"text"some title 2015"","href"http://2.com""},"description"descriptionsome"Job Type","location":"Location","date":{"text":"Post Date*","href":"javascript:__doPostBack('DataGrid1$_ctl2$_ctl0','')"},"url":"http://nn.com"},{"title":{"text":"APB","href":"http://n.com"},"description":"Temporary","location":"IN - Indiana","date":{"text":"03/27/2015","href":""},"url":"http://jcom"}

**Comment by cantino** [comment]
Which part are you interested in?

**Comment by signallhill** [comment]
The data I want is starting from collection1. So each payload should have title,description, location, date. 

If that's not possible then title is what I want.

{"collection1":[{"title":{"text"some title"","href"http:// link""},"description":"1 2 3 4 5 6 7 8 9","location":"1 2 3 4 5 6 7 8 9","date":{"text":"1 2 3 4 5 6 7 8 9","href":"javascript:__doPostBack('DataGrid1$_ctl1$_ctl1','')"},"url":"http://ng.com"}

I have webhook posting to huginn and http://requestb.in/. Huginn gets post but payload is empty while the other website gets what I posted above. I'm sorry I'm confusing you.

**Comment by cantino** [comment]
So you want it to loop over the results, not just return the first one with something like `collection1[0].title`?

**Comment by signallhill** [comment]
Yes I think.

**Comment by signallhill** [comment]
I read some examples online and came up with this.

$..collection1[*]

The problem is Huginn is only showing the first payload and ignoring the rest. However, when I goto http://jsonpath.curiousconcept.com/ the same query on same raw data shows each payload with Title, description, date location etc. 

Is there something wrong with the above Jsonpath?

Here is the raw data

{
  "name": "Raw Data",
  "count": 58,
  "frequency": "1 day",
  "version": 1665,
  "newdata": true,
  "lastrunstatus": "success",
  "lastsuccess": "Fri Apr 03 2015 17:09:54 GMT+0000 (UTC)",
  "thisversionstatus": "success",
  "nextrun": "Fri Apr 04 2015 17:24:54 GMT+0000 (UTC)",
  "thisversionrun": "Fri Apr 03 2015 17:09:54 GMT+0000 (UTC)",
  "results": {
    "collection1": [
      {
        "title": {
          "text": "Title Text 1",
          "href": "http://URL1.com"
        },
        "date": "April 2, 2015",
        "description": "Description 1",
        "url": "http://URL1.com"
      },
      {
        "title": {
          "text": "Title Text 2",
          "href": "http://URL2.com"
        },
        "date": "April 2, 2015",
        "description": "Description 2",
        "url": "http://URL2.com"
      },
      {
        "title": {
          "text": "Title Text 3",
          "href": "http://url3.com"
        },
        "date": "April 2, 2015",
        "description": "Description 3",
        "url": "http://url3.com"
      },
      ]
    },
    "endpoint": "/api/addfd"
  }
}

**Comment by cantino** [comment]
I need to look and see if this type of Agent can loop and produce more than one event from a payload.  If not, we'd need to add that feature.

**Comment by cantino** [comment]
Perhaps you could modify the WebhookAgent and change the `create_event(:payload => payload_for(params))` line to something like this (untested):

```ruby
if boolify(options['multiple_payloads'])
  Array(payload_for(params)).each do |payload|
    create_event(payload: payload)
  end
else
  create_event(payload: payload_for(params))
end
```

Then set the `multiple_payloads` option to `true` and set the `payload_path` to the root array that you're trying to emit events for.  If that works, you could add a spec and send a PR! :)

**Comment by signallhill** [comment]
Wow thank you for this opportunity. I have forked, changed the agent code and created my PR. I will create a new huginn instance from my PR and test it. I will update you.

Thank you again for allowing me to help.

**Comment by signallhill** [comment]
Couple of questions

"Then set the multiple_payloads option to true"

Do I do that in the agent like below or is that done in if boolify(options['multiple_payloads']).

{
  "secret": "secret",
  "expected_receive_period_in_days": "6",
  "multiple_payloads": "true",
  "payload_path": "$..collection1[*]"
} 

"you could add a spec"

What does spec mean and how do I add that?

**Comment by cantino** [comment]
Maybe Rails 4 updates the session cookie on every request to avoid replay attacks?  I seem to remember that.  Is it causing you a problem to have to resend the updated cookie each time?

**Comment by cantino** [comment]
(Sorry, that previous comment was for a different thread.)

**Comment by cantino** [comment]
I think the `payload_path` would be `$..collection1` and the `multiple_payloads` you have is correct, once the new code is added.  We'd also update the file in spec/models/agents/webhook_agent_spec.rb.  Would you like me to do it?

**Comment by signallhill** [comment]
I will do it. This is my first time doing this that's why I'm asking. I want to learn. 

I will update and test again.

**Comment by cantino** [comment]
Great!  Glad to get your help :)

**Comment by signallhill** [comment]
Ok the updated webhook agent is working I can confirm. but

I have to apologize. I have never written a code before on any language, and dont work in IT either. From reading helpful websites and youtube vids I see spec is used to test ruby code. I also installed rspec gem. but I am on windows and I think it does not work well with it.  

I think I see where I need to update the spec file below but I don't know what the code i should put. 

describe 'receive_web_request' do
    it 'should create event if secret matches' do
      out = nil
      expect {
        out = agent.receive_web_request({ 'secret' => 'foobar', 'payload' => payload }, "post", "text/html")
      }.to change { Event.count }.by(1)
      expect(out).to eq(['Event Created', 201])
      expect(Event.last.payload).to eq(payload)
    end

I am sorry.

**Comment by cantino** [comment]
No need to apologize @signallhill!  I'm glad it's working for you, I'll make a pull request that you can try out and we'll merge it if it works.

**Comment by cantino** [comment]
Mind trying out https://github.com/cantino/huginn/pull/773 @signallhill?

**Comment by signallhill** [comment]
@cantino Yes it is working confirmed. Thank you very much. 

I have followed this project for almost a year now. This is absolutely amazing.

**Comment by nachiarg** [comment]
Hi, I'm having trouble with a web hook agent and the payload_path. Could you give me a hand. I have this Json from a Kerberos installation but I can buil just one event for it. 

{
  "regionCoordinates": [
    388,
    308,
    535,
    599
  ],
  "numberOfChanges": 4442,
  "incoming": 1,
  "outgoing": 0,
  "timestamp": "1476391523",
  "microseconds": "6-438745",
  "token": 736,
  "pathToImage": "1476391523_6-438745_frontdoor_388-308-535-599_4442_736.jpg",
  "instanceName": "frontdoor",
  "web_request": {
    "regionCoordinates": [
      388,
      308,
      535,
      599
    ],
    "numberOfChanges": 4442,
    "incoming": 1,
    "outgoing": 0,
    "timestamp": "1476391523",
    "microseconds": "6-438745",
    "token": 736,
    "pathToImage": "1476391523_6-438745_frontdoor_388-308-535-599_4442_736.jpg",
    "instanceName": "frontdoor"
  }
}

**Comment by cantino** [comment]
If you have a question @nachiarg, please post on a new issue.
