### ISSUE TITLE
Option not to keep events

### ISSUE THREAD

**Issue by stvnrlly** [cantino/huginn#765]
I'm using a WebsiteAgent to watch a JSON file that's updated minutely, producing 20 events every minute. All I care about is the small output of the DeDuplicationAgent that it's passed to, but I still end up with tens of thousands of WebsiteAgent events per day.  This could be a problem for using the free Postgres database on Heroku, for instance.

The extreme version of this could be self-destructing events that delete themselves after being passed on. A lighter version could be an option to keep the events for only 10 minutes or so.

**Comment by cantino** [comment]
You can set a max age to keep on created events when setting up an Agent.  Does that work for you?

![screen shot 2015-04-03 at 1 17 49 pm](https://cloud.githubusercontent.com/assets/83835/6988211/de16d698-da03-11e4-8f30-25e0e1a5ae05.png)

**Comment by stvnrlly** [comment]
It does work, but 1 day at this rate is still 28,800 events, which pushes the Heroku database above the 10,000 row limit for the free level. I only need these events for a few seconds to propagate down the line, so it would be nice to have some even-shorter age options or to have an option to delete after propagation.

If adding more age options would make the list too long, perhaps it would be possible to have the max age option be a number field and a minutes/days/years dropdown.

**Comment by cantino** [comment]
Oh, I see!  You could add another option to the list for an hour or something?

**Comment by stvnrlly** [comment]
Okay, so I was able to figure this out, but it requires setting the event cleanup to run more than once per day. For my purposes, I wanted to keep the events for 2-3 minutes, so I added that as an option and set cleanup to run every 3 minutes.

I don't know if that will cause problems for people running larger-scale Huginn instances, so I thought I'd check to see about that before submitting a pull request.

**Comment by cantino** [comment]
You could make it a variable in the .env file?

**Comment by stvnrlly** [comment]
Nice, that sounds like it should work.

**Comment by signallhill** [comment]
Hi Is this now implemented in public master?

**Comment by stvnrlly** [comment]
Not fully. I was going to make the option a little milder and more configurable, as we discussed on the pull requests: https://github.com/cantino/huginn/pull/808. I should be able to get to that this week.

What's in the pull request now does work, though, if you'd like to merge that and have me submit an new pull request with the revision.

**Comment by stvnrlly** [comment]
@signallhill Not yet. There's still one more change to be made to make the option more configurable: https://github.com/cantino/huginn/pull/808.

**Comment by signallhill** [comment]
Thanks. This is very useful update. I will follow #808.
