### ISSUE TITLE
Simply awesome!

### ISSUE THREAD

**Issue by bruskiza** [cantino/huginn#769]
No issue, just happiness.

Andrew, I've been watching your project for a while now and have finally found a business use for it.

Excellent product!

Well done!

**Comment by cantino** [comment]
Thanks, and glad to hear it!

What are you using it for?

**Comment by bruskiza** [comment]
HelloPeter.com and Twitter watching mainly for now. Huginn posts into Slack notifying us when the events occur and gives us a better view on what's going on.

Early days, but I'm liking very much.

Running on Heroku is a dream too, no hassles and good documentation.

**Comment by MartinDelille** [comment]
Totally ok with @bruskiza !!! IFTTT concept was cool but having an opensource alternative is awesome!
Is there a list of compatible API?

**Comment by cantino** [comment]
Thanks for the info @bruskiza!  Are you paying for the Heroku hosting, or using the free plan?  I heard that sometimes the free plan goes to sleep and stops receiving events.  Has that happened to you?

@MartinDelille, you can look at the list of Agents in app/models/agents, or see the wiki.

**Comment by flechaig** [comment]
@cantino : I use Heroku free plan since a few days and haven't noticed any sleep or shutdown.

**Comment by cantino** [comment]
Good to hear!
