### ISSUE TITLE
Importing credentials.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#780]
It's possible to download the set of one's credentials from Huginn (Credentials -> Download Credentials) but it's not possible to re-import them the same way.

**Comment by Jngai** [comment]
@cantino This may be an easy patch too. Let me take a look.

**Comment by Jngai** [comment]
#1394

**Comment by Jngai** [comment]
@cantino You forgot to close this.

**Comment by cantino** [comment]
Thanks @Jngai for implementing it!
