### ISSUE TITLE
Credential text editor is inaccurate.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#781]
When typing in credentials (Credentials -> New Credential) the position of the cursor is often several spaces off by the very end of the text.  This makes it difficult to determine if the information entered is accurate, vis a vis whether or not there are a bunch of spaces at the end, which would invalidate API keys and suchlike.

**Comment by cantino** [comment]
Screenshot please?  Does this happen in both Chrome and FF?

**Comment by virtadpt** [comment]
![editor_fail](https://cloud.githubusercontent.com/assets/639730/7109667/0302082e-e157-11e4-9842-0c86ced3b6bc.jpg)
I haven't tried Chrome yet.

**Comment by virtadpt** [comment]
It doesn't seem to happen in Chromium.
![editor_fail-chromium](https://cloud.githubusercontent.com/assets/639730/7446191/8687c7f4-f185-11e4-8a0e-af67ac718be8.jpg)

**Comment by cantino** [comment]
Someone could try upgrading ace.

**Comment by virtadpt** [comment]
I haven't seen this problem in a couple of weeks.  Did Ace get updated?

**Comment by cantino** [comment]
Don't think so, but I did use the ace editor for the JavaScriptAgent--
maybe thst fixed something for some reason?

**Comment by virtadpt** [comment]
Do they reference the same editor library?

**Comment by virtadpt** [comment]
I just went prowling throug the code to see what they had in common, and I'm not seeing anything overt.

**Comment by cantino** [comment]
Maybe your browser updated?

**Comment by virtadpt** [comment]
I did update to Firefox v37.0.2 eight days later...

**Comment by cantino** [comment]
Seems likely.  Glad it's fixed now :)
