### ISSUE TITLE
Scheduler Agents do not re-import correctly.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#784]
When importing Scenarios which have one or more SchedulerAgents in them, they are disconnected from the rest of the agent networks and have to be reconnected manually by editing them.  Looking at the exported scenarios, the SchedulerAgents do not have fields which logically connect them to the agents they're supposed to control:
```
    {
      "type": "Agents::SchedulerAgent",
      "name": "Ping the morning BART delay detector until I get to work",
      "disabled": false,
      "guid": "eb86a0892621a545007ef09104390705",
      "options": {
        "action": "run",
        "schedule": "0/5 8-9 * * 1-5"
      }
```

**Comment by cantino** [comment]
Yes, I don't think that those ever got added into Scenarios.

**Comment by cantino** [comment]
Hey @virtadpt, I got around to fixing this.  Would you mind seeing if #925 fixes exports for you?

**Comment by virtadpt** [comment]
Let me give it a look-see.

**Comment by virtadpt** [comment]
Reading over the pull request it looks like it'll mostly do the job.  I don't see anything specific to instances of SchedulerAgent in the diff, though.  That might be inaccurate because WeatherAgent and TriggerAgent might need to be handled as edge cases instead of core cases.  Does that seem accurate as a sightread assessment?

**Comment by cantino** [comment]
You're correct that it's a bit inaccurate to be testing on non-SchedularAgents, but nothing actually limits only those agents to be able to use control links, so I think it's okay.
