### ISSUE TITLE
Heroku Precompile Error

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#790]
I was deploying a new heroku app by clicking the Deploy heroku button and got this error several times. Not sure if this is just me or for everyone. 

       Cheers.

       ***

       

       Bundle completed (186.47s)

       Cleaning up the bundler cache.

-----> Preparing app for Rails asset pipeline

       Running: rake assets:precompile

       rake aborted!

       PG::ConnectionBad: could not connect to server: Connection refused

       Is the server running on host "127.0.0.1" and accepting

       TCP/IP connections on port 5432?

       /tmp/build_6e3d9dc8081cc473bde2dcd21b0de848/cantino-huginn-da1b467/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'

**Comment by signallhill** [comment]
Found something in heroku that may be helpful

https://devcenter.heroku.com/articles/rails-asset-pipeline

**Comment by devilankur18** [comment]
+1

**Comment by cantino** [comment]
Maybe our Rails upgrade broke the one-click.  If someone wants to take a look, it'd be appreciated, otherwise I'll get to it soonish.

**Comment by dsander** [comment]
I am getting ` !     Push rejected, failed to compile Multipack app`  which seems to be a known issue ddollar/heroku-buildpack-multi#49

**Comment by cantino** [comment]
I have a fix for this, deploying shortly.

**Comment by cantino** [comment]
Okay @signallhill  and @devilankur18, this should be fixed now.  I'd appreciate if someone could test it.  It looks like Heroku stopped auto-provisioning their postgres addon, so I added

```json
"addons": ["heroku-postgresql"]
```

to the app.json config and

```ruby
unless $config['DATABASE_URL']
  puts "Setting up the postgres addon"
  puts capture("heroku addons:add heroku-postgresql")
  puts
end
```

to `bin/setup_heroku`.

**Comment by dsander** [comment]
New deployment worked like a charm :+1:

**Comment by cantino** [comment]
Thanks!
