### ISSUE TITLE
Is OpenShift Deployment working?

### ISSUE THREAD

**Issue by orymeyer** [cantino/huginn#791]
I tried to deploy on Openshift but unfortunately got the following error(truncated):

`remote: Mysql2::Error: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
remote: /var/lib/openshift/5530c507e0b8cd2e54000174/app-root/runtime/repo/vendor/bundle/ruby/gems/mysql2-0.3.16/lib/mysql2/client.rb:70:in connect`

Full logs here:  http://pastebin.com/PwbhZm48

I followed the  Install on openshift instructions on the wiki.

**Comment by cantino** [comment]
Thanks for letting us know! I haven't tried it recently, so perhaps
something has changed.  I'll try to run it soon and see if I can debug.  If
you figure anything out, any fixes or info are appreciated!

**Comment by signallhill** [comment]
@cantino I was also running huginn in OS could not update so tried heroku and that is also not working.
Not sure if this has anything to do with OpenShift rack1.6 because thats the error I got when upgrading or doing new install. Hope it helps.

https://bugzilla.redhat.com/show_bug.cgi?id=1180420

**Comment by cantino** [comment]
@dsander I thought we held this back?

**Comment by dsander** [comment]
@cantino If I remember correctly you created a openshift branch which still runs on rails 4.1, maybe we need to updated the documentation? I never deployed to openshift myself.

**Comment by cantino** [comment]
Right!  @orymeyer, could you try the https://github.com/cantino/huginn/tree/openshift branch?

**Comment by orymeyer** [comment]
@cantino  Tried the openshift branch.Works perfectly now.Thanks!

You guys might as well update the documentation.And BTW, some amazing work you all are doing here.

**Comment by cantino** [comment]
I've added a comment on https://github.com/cantino/huginn/wiki/Run-Huginn-for-free-on-OpenShift

**Comment by cantino** [comment]
So, unfortunately, I'm having trouble getting OpenShift to work now with `bin/setup_openshift`.  They seem to have changed something and it won't connect to mysql.  I'm wondering if we should drop support for OpenShift since we have Heroku and Docker?

**Comment by dsander** [comment]
I never personally used it, we could mark the OpenShift deployment as broken until someone has the time and motivation to fix it out, or OpenShift supports rails 4.2

**Comment by signallhill** [comment]
I am actually switched to heroku. It is far more easier to use for novice like me too.

**Comment by cantino** [comment]
Agreed.  What do you think is the best way to mark it, @dsander?

**Comment by dsander** [comment]
Adding a note on the [wiki](https://github.com/cantino/huginn/wiki/Run-Huginn-for-free-on-OpenShift) linking to the openshift [issue](https://bugzilla.redhat.com/show_bug.cgi?id=1180420) stating they do not support rack 1.6 should be enough for now?

**Comment by cantino** [comment]
Good call.  Done!
