### ISSUE TITLE
Request for how to update huginn in README

### ISSUE THREAD

**Issue by eliotsykes** [cantino/huginn#794]
I'm very sorry if the update instructions exist and I missed them! 

I'm interested in running huginn though if there's one thing holding me back it's knowing how much overhead is involved in keeping my install up-to-date. I can take a guess but it'd be great if how to stay on top of huginn updates (e.g. when huginn's Rails version is updated) was documented in the README.

**Comment by virtadpt** [comment]
If you're following the workflow described in README.md (section Getting Started -> Quick Start) it's documented in there:
```
Periodically run git fetch upstream and then git checkout master &&
git merge upstream/master to merge in the newest version of Huginn.
```
However, I've found that it's a little more involved than that.  Here's my workflow for updating (again, following the Github workflow of forking the repo into my own account):
• rm log/development.log
• git fetch upstream
• git checkout master
• git merge upstream/master
• bundle
• rake db:migrate
• foreman start

**Comment by eliotsykes** [comment]
Thanks for the details @virtadpt. The update process sounds reasonable and scriptable, so that's good news, thank you! :+1:

**Comment by cantino** [comment]
@dsander Does / will your guide have a section about this?

**Comment by dsander** [comment]
@cantino Yes, but the [update docs](https://github.com/dsander/huginn/blob/deployment-guide/doc/update/README.md) are pretty specific to the installation and will probably not work when running in development.
