### ISSUE TITLE
Ability to kill multiple queued background jobs at a time.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#796]
It would be extremely useful to be able to kill multiple pending backgrounded jobs at a time to prevent storms of requests against other people's online assets.  For example, at this moment I have 2,349 pending tasks and I'd like to kill 2,000 of them without having to hand-hack the database or terminate them one at a time.

**Comment by virtadpt** [comment]
For the record, here's what I did to keep from getting banned from every service I have Huginn watching:
```
DELETE FROM delayed_jobs WHERE ID LIKE '187%';
```

**Comment by cantino** [comment]
Like, a "kill all queued jobs" button?

**Comment by virtadpt** [comment]
Yes.

**Comment by virtadpt** [comment]
Or checkboxes that could be used to select jobs (including a "select everything on this page" checkbox) that could be used to select subsets of queued jobs to kill them.  Or both.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further or try building this!
