### ISSUE TITLE
Ability to run all queued background jobs simultaneously.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#798]
Sometimes if you've only got two or three pages of stuck jobs in the queue (sometimes with lots of retries racked up) it would be nice to be able to hit a button (or select a subset of them) and force them to execute simultaneously to get them out of the queue without having to delete them.

**Comment by Jngai** [comment]
I can submit a patch for this.

**Comment by Jngai** [comment]
#1389

**Comment by Jngai** [comment]
#1423 new pr

**Comment by cantino** [comment]
Merged @Jngai's improvement!
