### ISSUE TITLE
There is a version mismatch between the spring client and the server.

### ISSUE THREAD

**Issue by joshuataylor** [cantino/huginn#811]
`21:40:33 web.1  | started with pid 29056

21:40:33 jobs.1 | started with pid 29057

21:40:33 jobs.1 | There is a version mismatch between the spring client and the server.

21:40:33 jobs.1 | You should restart the server and make sure to use the same version.

21:40:33 jobs.1 | 

21:40:33 jobs.1 | CLIENT: 1.3.4, SERVER: 1.3.2

21:40:33 jobs.1 | exited with code 1

21:40:33 system | sending SIGTERM to all processes

21:40:33 web.1  | terminated by SIGTERM
`

**Comment by dsander** [comment]
`bundle exec spring stop` should do the trick

**Comment by joshuataylor** [comment]
:+1:

Thanks @dsander !
