### ISSUE TITLE
Protecting Huginn with HTTP auth breaks Twilio integration.

### ISSUE THREAD

**Issue by virtadpt** [cantino/huginn#815]
When using the Twilio agent to interact with the outside world, putting Huginn behind a web server which implements HTTP Basic Auth breaks inbound interaction from Twilio's API server.  For example, sending a text message to an agent network results in the following error at Twilio:
```
Error              11200 HTTP retrieval failure 
Description    An attempt to retrieve content from https://exocortex.virtadpt.net/ returned the HTTP status code 401.
```
Is there a way to work around this such that Twilio's API server can send incoming events while still preventing untrusted users from monkeying with Huginn?

**Comment by dsander** [comment]
Doesn't the invitation code offer enough 'protection'?

You could try `https://username:password@exocortex.virtadpt.net/`.

**Comment by virtadpt** [comment]
I don't know.  I set it up at the advice of @cantino.

Hmmm...  I'll try that.

**Comment by cantino** [comment]
@dsander Since he was running in development mode, I encouraged him to put the site behind basic auth in nginx.  Rails in development is fairly insecure (interactive debug consoles, error logs, etc.).

**Comment by virtadpt** [comment]
I could try.  I haven't had time to mess with Huginn for a few weeks now.

**Comment by cantino** [comment]
That'd be my recommendation.

**Comment by virtadpt** [comment]
I've created a separate basic auth user for webhooks and I'm trying that URL spec - I forgot that you could do that.

It works like a charm!

**Comment by cantino** [comment]
Great!
