### ISSUE TITLE
The new heroku free dyno

### ISSUE THREAD

**Issue by ZucchiniZe** [cantino/huginn#818]
The new heroku free dyno (https://blog.heroku.com/archives/2015/5/7/heroku-free-dynos) allows you to have 1 web and 1 worker process, but the web dyno can only stay awake for 18 hours of that day. Currently there is now way to force the new free dyno in the app.json.

Are we going to stick with the traditional free dyno or suggest users switch to the new free dyno?

**Comment by cantino** [comment]
That's a great question.  Do you know if the `app.json` is still using the old one at the moment?

I'm also going to get in touch with Heroku and discuss options.

**Comment by ZucchiniZe** [comment]
Just checked and the `app.json` still uses the traditional dyno.

**Comment by cantino** [comment]
Discussion is in 893 now.
