### ISSUE TITLE
WebsiteAgent Suggestion

### ISSUE THREAD

**Issue by signallhill** [cantino/huginn#823]
The website agent is great, but I see when there is unequal number of extracted data then it does not work.

Wanted to suggest if it could be updated to allow empty as part of the result if it does not find equal number of result. Just have "Empty" or "No result" to fill the gaps.

**Comment by cantino** [comment]
I understand why you would want that. The challenge is that it's hard to do
unless you have a container element that is always present. We could add a
container selector that must always be present, and then a list of optional
sub selectors that are optional.

Can you provide a good example of a problem that you're trying to solve, to
see if this would work?

**Comment by virtadpt** [comment]
Do the contents of ticket #807 match what you're seeing, @signallhill?

**Comment by signallhill** [comment]
Yes, I will follow 807
