### ISSUE TITLE
Agent with DropboxConcern doesn't seems to receive events

### ISSUE THREAD

**Issue by kokotchY** [cantino/huginn#828]
I'm trying to setup Dropbox agents, but it doesn't seems to work.

None of the 2 provided agents (dropbox_file_url_agent and dropbox_watch_agent) doesn't seems to receive events. I've tried to develop my own agent to upload some file, but it didn't receive any event neither.

I have created a simple agent, and it's working, the log messages are displayed:
```ruby
module Agents
  class LoggingEventAgent < Agent
    cannot_be_scheduled!

    description <<-MD
        Display the incoming events
    MD

    event_description <<-MD
        Any event will work
    MD

    def working?
        true
    end

    def receive(incoming_events)
      log "Incoming event!"
      incoming_events.each do |event|
        log event
      end
    end

  end                                                                                                    
end
```
```
13:38:45 jobs.1 | Agent#22: Incoming event!
13:38:45 jobs.1 | Agent#22: #<Event:0x00000009b2a3f0>
```

After a bit of investigation, I've found out that it was because of the include DropboxConcern in the two dropbox agents. Indeed, when I remove the include, the log messages are displayed.

The following agent isn't working:
```ruby
module Agents
  class LoggingEventFaillingAgent < Agent
    include DropboxConcern
    cannot_be_scheduled!                                                                                 

    description <<-MD
        Display the incoming events
    MD

    event_description <<-MD
        Any event will work
    MD

    def working?
        true
    end

    def receive(incoming_events)
    | log "Incoming event!"
    | incoming_events.each do |event|
        log event
    | end
    end

  end
end
```

I don't see any errors in the logs when loading the server. 

I think that my Dropbox service is well configured because I was able to connect with oauth and my dropbox account is displayed in the configuration of the LoggingEventFaillingAgent.

How can I investigate more?

**Comment by cantino** [comment]
Hey @kokotchY, welcome to the project!  Sorry this isn't working.

Including the `DropboxConcern` primarily adds a dependency on having a Dropbox service configured.  Have you setup Dropbox credentials in your .env file and added a Service for it?

@gtramontina may have other suggestions as well.

**Comment by kokotchY** [comment]
Hello @cantino , 
My dropbox service is configured in .env. I can see it in the services tab (and my name is associated to it, so the communication between huginn and dropbox was working at start).

I might then be the dropbox dependencies not available, but it seems that they are installed:
```
% gem20 list --local | grep dropbox                                                                                                                                            ~
dropbox-api (0.4.2)
omniauth-dropbox (0.2.0)
```

**Comment by cantino** [comment]
It's odd that you're not seeing any error logs in the console or in the agent logs on the /agents/NUM page for each agent.  (You're looking at both, right?)

Are you using `bundle exec foreman start`?

Try temporarily editing your DropboxConcern and changing the gem_dependency_check to

```ruby
    gem_dependency_check do
      puts "LOOK HERE!"
      p defined?(Dropbox), Devise.omniauth_providers.include?(:dropbox)
      defined?(Dropbox) && Devise.omniauth_providers.include?(:dropbox)
   end
```

and look for that in the logs.  Both `true`?

You could also run `bundle exec rails c` and `Agent.find(NUM)` for your new Agent and ask it if it's `valid?`.

**Comment by kokotchY** [comment]
I've checked the logs for both agents and the output is more or less the same when viewing the page.

I'm using ```bundle exec foreman start``` to start the application. 

After adding the debug inside DropboxConcern, I'm receving the expected output:
```
12:50:53 web.1  | LOOK HERE!
12:50:53 web.1  | constant
12:50:53 web.1  | true
```

Next, I've tried to remove the dropbox service and re-add it... but it was more difficult than expected.
It seems that I need to be disconnect from my dropbox account to let the oauth process finish... but still a bit inconsistent.

After re-adding the service, I had to set it up again in all dropbox agents and at that point it's working.

I can't understand what was going on before. I'm thinking about an invalid token in some way that the dropbox-api couldn't handle and fail silently. 

Should we consider the issue closed or more investigation is needed? I've the feeling that it can occur to other people as well.

**Comment by virtadpt** [comment]
You're not the only person it happens to - I've never gotten the Dropbox agents to work, so I use an RSSagent to monitor my Dropbox share for changes.  I don't think I've seen anything in the logs, either, but arranging some tests to see what happens won't be difficult.

**Comment by cantino** [comment]
I'm glad you were able to get it working @kokotchY.  I think we've definitely learned from this that the Dropbox integration is brittle.

I wish I know how best to output error logs for this.  Maybe there's a way to tell `Dropbox::API::Client` to output more verbose logs.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further.
