### ISSUE TITLE
Should validation of agent config go thru JSON Schema?

### ISSUE THREAD

**Issue by spdustin** [cantino/huginn#832]
I've been giving some thought to how Huginn currently checks that an agent's config is valid, and it seems like it's too fragile, and would require over-work to validate common scenarios (since there's no agreed-upon validation methodology). JSON Schema seems like a good fit to validate agent configuration, and may enable a GUI-based config for agents that supply a JSON Schema for their config options.

Thoughts?

**Comment by cantino** [comment]
That's an interesting idea @spdustin.  I haven't used JSON Schema.  Have you played with it?

**Comment by spdustin** [comment]
I have, recently, as I was pondering how to standardize the various options JSON objects that agents use. There's a [json-schema gem](https://github.com/ruby-json-schema/json-schema) that works pretty well for validation, and I found an [excellent reference](http://spacetelescope.github.io/understanding-json-schema/) to understand JSON Schema. The schema itself could be used to generate a configuration UI. I've done similar things with parsing XSLT to generate a forms-based UI to provide values to a generated XML file, so this wouldn't be that different.

Heck, there's even a [JSON Schema Generator](http://jsonschema.net/#/) that can generate a schema given sample data. For example, the Webhook Agent's JSON Schema might look like this:

```JSON
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://github.com/cantino/huginn/blob/master/app/models/agents/webhook_agent.rb",
  "type": "object",
  "additionalProperties": true,
  "properties": {
    "secret": {
      "id": "https://github.com/cantino/huginn/blob/master/app/models/agents/webhook_agent.rb/secret",
      "type": "string",
      "minLength": 1,
      "description": "A token that the host will provide for authentication.",
      "default": "supersecretstring"
    },
    "expected_receive_period_in_days": {
      "id": "https://github.com/cantino/huginn/blob/master/app/models/agents/webhook_agent.rb/expected_receive_period_in_days",
      "type": "integer",
      "default": "1",
      "description": "How often you expect to receive events this way. Used to determine if the agent is working.",
      "minimum": 1
    },
    "payload_path": {
      "id": "https://github.com/cantino/huginn/blob/master/app/models/agents/webhook_agent.rb/payload_path",
      "type": "string",
      "minLength": 1,
      "description": "JSONPath of the attribute in the POST body to be used as the Event payload. If payload_path points to an array, Events will be created for each element.",
      "default": "$"
    }
  },
  "required": [
    "secret",
    "expected_receive_period_in_days",
    "payload_path"
  ],
  "description": "Schema for validating Webhook Agent options",
  "name": "Webhook Agent Schema"
}
```

**Comment by cantino** [comment]
Sorry I took a while to consider this.

So, would we define a schema, then use some UI that interprets the Schema to make a UI builder?  What are the benefits over what we have now?

**Comment by spdustin** [comment]
The big benefit would be that you'd have a single source of truth for generating UI, validating options ... Heck, even a rake task to pre-build a skeleton for your agent given the schema.

**Comment by spdustin** [comment]
So here's an example - If JSON Schema were used to define the options for agents, we'd get the benefit of a standard approach for agent options schemas, and a slick editor that is "context aware" (note, for this context, I did not complete the schema for the Web Site Agent)

[Check out this auto-generated Agent Options form for the Web Site Agent](http://jeremydorn.com/json-editor/?schema=N4IgJAzgxgFgpgWwIYgFwhgF0wB1QenwCsIB7AOwFpp5kA6UgJwHN8ATRpAM00oAYALPhqIkAYhAAaEGzhcAluXmZ5FCGlBwAHpk5QVFAPpQKC5hpCYAnjjhoQpAEZE4+qSByNStxirjrUUCgIANBZaEZ5HANyewAVeAACAGEAZVTE1LgAG1dMJkSAVwg4NkTHK0TMGHkIRIBBZjhyTCrSRPlZFvkuSuq4RJwkRmbW0i4qpJMW0bbygaHGErY6d077YPVpciQEO3RN9xVMXPs0jKzc/SYjm32QCF1Fc2lZLiRC7Mx7R1I2SroUGySBCiTE6wAvtIAG5IbKFfZhfxQSLRVSxdAAJRySBU0IG+UmA3OmRyeQKSF++MkRMGuJgc36iWmmFmhO0uiQ+joiQAYgVtLscLkaQABCCMKA0gp0QisnQACgAlGs2PZYfC7NtdvcNQijspTugAGpwhGJET0W62eyPSLkF4yOQfL72WX4eWYZUgCG+qFOiJRGL2erkRLaYVIHYxRKU0iFVpMnCFRg4UglRLjSa1DrkR5RqADcIo+SOUrlPo1OqWpCraSebxwXzyfwWCN5UqGQo4Ni4uCGHyqNiGRSGXtWUIBktoijxJLILTyBCFBCxhDxlqZiYqPaTXGJKzxgDkZXb+jmQ1BZcwAHc4M1EgBRfEtOpl57MkZ9soVbN1RqjDyiQJDmOYUNklTFOWhIlImSQADogDeTAANbPIhFqYLixR1iA6zoGerLDt2vasgOTZDiO5BjkgE7uDsez2IRnYkX25GRH8VE0XR0jHEaICPlotj6OWACqPZ9okAAKFF/IkCqKIk44QEquHWDa6CKKyTSMD60gcno3yBFOqLBugAASTZwDSh6FBawk9JUN4wPutmJDeUZwQMAGbuyOiGYkXBeKuTJ3o4dJNLh+EgAZXLfNqjEEf5cXWvcTguG49ZeD4fgBOQnzZPWuKsow5BSdlTa5RYAB6CoANpIJQABe9SUAAWpQhgALpKgA1GAFhgCMXD2GI7ByIoyjohA+Cxfo6LGKY8jmL60iFEoACOCIAJKsggAS6AivGGvcyRLcwKa4uigUFGdMyboJnLzbO/rqYiJlBuic4EncW7MhQrK+VWDRNJuN7yNk2R0kscBRWq6BvfROr2Ijx0nKdAOzIsEAfqjlh3LaTwOu4zQrmgdUYJgCDZO4WjU+4JCzrxHIgF1/rrrIFjFqZX3oAA6vAYbg5Df4g7MKJwJJ5BwDeT4vpgEAAPyJAA8mGcD4owlSMOt0qMJm5AQe5ygMrAUZNGUpFIIrqr2BzWogAx9z2wa6P2M+swu7xBPoHazwk/lCDkyAcI09IRhmw6dhs2tjA08Z3OfbO6AJAMJgIMKcCsokomYgAMjS4PVIMXj5CYUNRmUW1NhORPMNDOolRANLVDmPmtMLUMjE8Guw7b6ApmHjvIwPceu/xud5xewwlO4FBwCrI2oHVoCI77dfuInM4YiAqf/RnuTZ5PhcmyXpBl6QFfkFXCJa37DoN3sTct8D7fGyL3eRL3cP2IPSOJSAP+aMJ752njDPSq8fYh0YJwKw7gECKF2ogAIABGaQyhkEWDXg8De/p1ryGrkg/aaBDrWQ+tvb6+9M5H3zifYuDYL5XxvjXe+9dFiNybM3UWb9O6JE/i2fEP9R5Dydr/MewD7iTzAbPCEbN/QjC2vIEY8MKbMWIhJMig5OKjmUu4IB+MbTSC9jFZKbguoSPsOZQozBFBhj5nARwqQMFi03CrbeWwDFpWcHkH0QAAA==&value=N4IgpgHgDmDGAuYAmB9ArlJBDRKYCcBLAe1UIDsVsBPAZxAC4AmAGnAnnywUdDXwA2vELFr0GIAMSxiAW0KwABIVkBzEGwBuWAWjCMQAAVr5YIAL5t4heAP0NQo8VJnylK9Vp16Dh67f1LEAAjUmoURA5hJwMkQk0AOlksCg0QbV17EASAehzI+AAKAEoLIPhqGAMAC3hZITZZUiziSlhqrHJVfTZ+IQla+CgGPMgsWSg7BNd86rAoLG6E2vqLIA&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&show_errors=interaction)

**Comment by cantino** [comment]
Thoughts @dsander?

**Comment by virtadpt** [comment]
That's pretty cool.

**Comment by dsander** [comment]
That's definitely interesting, but I don't see the benefits over `FormConfigurable` and `validate_options` right now. Am I missing something @spdustin?

Once we are at the point to support agent written in different languages this could come in very handy (given there is good library support in multiple languages).

**Comment by spdustin** [comment]
Validating user submitted options is easier - just one method to call. And the options UI becomes idiot-proofed. Writing test harnesses would be easier too since you can generate random options for tested agents based on the schema.

**Comment by dsander** [comment]
Hmm still don't completely get it, you either need to get the validations right in ruby or in the JSON schema. I am wondering does the editor support nested hashes like the ones we need in the `WebsiteAgent`? That would be awesome because adding support for that to `FormConfigurable` is a lot of work.

**Comment by spdustin** [comment]
You mean the array of hashes determining what to extract? The example I showed supports that now. Next to **Configuration for Content Extraction**, select **Properties**. Then, type the name of the new extraction and select **+ Add**. You'll see the new extraction config appear at the bottom of the array of extraction hashes.

Here's an updated form with a more complete JSON Schema for the `WebsiteAgent`: [JSONSchema Form](http://jeremydorn.com/json-editor/?schema=N4IgJAzgxgFgpgWwIYgFwhgF0wB1QenwCsIB7AOwFpp5kA6UgJwHN8ATRpAM00oAYALPhqIkAYhAAaEGzhcAluXmZ5FCGlBwAHpk5QVFAPpQKC5hpCYAnjjhoQpAEZE4+qQ/JwA8lzQBtUDBGOXsxdjlFZVVyCHxtXSR9aONTeWZDLAQAGxAAX0lA4N90MNkFJQMYuJ09SpTyM0MSCjyC8CLQ8PKotWqEpKMTBrTDTHi8gF18kGDmbRwLWWhGeRxK+wAVeAACACU4ZgBXLKRGbYBRLRxgiAho7cxSbeRMWG2kZiRFCEwHnaGxuRfo9to44NscKcIHA2HR3PI2PZZvN3CpMFk7Oh9kcTmdLtc4LdoqibJiQD8VuRzNIykhjph7AA9AAUdAA1AB+ACUqG2rLZXLArRAilkWkWhKgKzWxPQW3Bou021IXD+4KgSDWh0pzG2zEYpEOOAeT0O0O2XCYf3kEGeSFeMDo2wAqua+CbtvFau8slk7Q7FLqAXAgXDpAj7IrxdI0Rj7ABhTWYbWB7YAcQNRu2AElyGKSbZ/CKgQc4Ix3BTAyAptIvYk6kNGpkcqhQNZC+gnC43NJrqRbIwVISLFBbhLlqt1nKdvGAMqz7azuAY/RWs0w0FWa22gCCcyBHoRIZUXC3mB2kOCB5Vau2wYPILBEKhMLDIsR6FH6mk5CQCDJX6osocboHOC5LiujzljGpL2JWVLuLS9L2I4pBsFudBQCctzbGIEbTAAbkgWSHJioBLFKk6yiA+wnCoBHgiC57gmBi7Lq4UHvKhDGSLekLnh6zF3hQgLAk8db6E6ABiVraH+OAYrxAACECMFAvFWnQhBjDozJcvCH4gERJF2D+f5ksZpFAeiZIAGrEaR2wiPQBZkvB1IyHIdJZAy6BafgOmYHpeTTMEACOhzyMEH5+CAgHSJZdgTNISBsGwPS/lkAAKBoDkO6ioFwxHQtMEkNqk6TNOQFjtmSXYce4fZ5fIw6tiA/EwOOlEyi007ggAUrOXgAHJZfaMBsZBa7Qmwm7btse7HoeshAvIp63soiAek+l4zW+EboB17i/v+9hHTGwFkoNI1jQJEEcUwrlwboVY0l5yHoDc9IQHQbD2kgfgAFQTHQsZ2LkoVwBFUUwkWR3JSAqXpZUxE5f2Zb5WgRVZCVtY1PWySNiMgU1bBnbOA1va5RjLUFaAyJXBYQQhCUXSRJUsQMws0xRkzHSs2U7PRLEvMQ9I4WRdFRZc/CebaNWKVpRlqPU4OtNY8VcBi55E49dV6A7uQnpXCcv6VFxhrAhe2o4KQ5o3ueNrbN8mBIOQUDghRKxgrNjhnjATvOUgb5NTTrWaFcHEwoYRp/WMhgDqobCGIohh/VYdM691U4gPKdpaPICCHAg7wIIa16qio/5/Pa2xWIaADks3zBxHqQjhYKYAA7nAIYXAxQK2mCqZSnA9obn782LaG2zbFsTtOxQWRbuus0gtCVvggAOiAXdMAA1oGO9Oa7yY/QZ9gt/o0ex+PCdlknKfkGnSAZ8d5mX5H1/J7f8eJ2hT8X5vwujZew+Io6zWdDgOO4IsoPzQnyRQ2x04QC5G+WqkYSxzHLNMDBbUvZUV6rnHYtVlSqnvFbJ209fhd3kL6Z8jBoT7UMhgsyp10CsMsJdBMIklq7VTJwvB5IXoIVrOQYuRZmzuC0NkdwVVUTjBrCAMusgurShzgAdXgEbWh9DHa7n3L8Ue49tieC7v3Y8EAOTbC8EbOADFGBbkYIccgGkzhLy3LQgSsA3ZzFmnHJAHIL7oBUaZEAJ0yShOsiBEA5wB6/CiTBDswidTuBDBI1AsViI5GkIMGAvikrTG1C2cikp1HUTziYBACk4BjBdLsAAMrxLxE0+yPBMH6N2s0IplgziI3Ul5zJjEYbxfRC1DHbF0X6YIL17FwGYfYYp792EgCWSAmJzpGltxfO4Cg3higBEsGTFJr0s7lKIZU0g1SMR1M2U0yZyhWkGnaaQTpeZtg9Mce5BhQyywQFGQHAxS0pnbBmSsOZCz0BrPCR/KFjAclcNAegO52zGFhMtIwF4iyVitDbMc04nArDuAQIobMYwEAFQAIzhnJZnIR7lhQuPkD0sliACq6FIm9XWOdLnXNqeCO5zTHkQmeaQDp7x3mfL6TqH5/5hn/KnhMkFYKWoMUhas+FyyyTQrBvYFFIJdroqYFiuF8hJilXxm4fBZTCH6xAAACTLHAXi9dDhOVsFANanj8m/FdZMt2m9xlLRBGVC0BoS5CR7o4Z8cwnRZQxEgc05BSB1PPLXIS0JIIbjKvcIuPxQTgk1ApeQGpHAYkEv8XhB5+FUgeKSbYWQbRjFmkgbi8zgkgDKlqz+/QGRJLqhTHs7VVaY1QOI30vZ7TDPIGjZq4cQAsj8EgSgAAvHclAABalBDATC5GyIUbVmbFBAKUCIFRhZ9FqITCqIVpBMpZbStAHLnWIpifGCq2p7T3Axdsd9JYDyXF7cSaYjhE0lsMHSc8ajbX2GzKqTwMIYS8UFp4Wa9qNgbCytsAAQmBqAC1DgCXXIwCJErZrtwgHvRgs14DBF4o2/e4JiMRNQBRqjiJwyGVA3cKAEHCOdTYWSbj4HIMCdfWSdDmGcN4YI946Kx55DFSeugBlb0iofXHVkXJetiJPucVrO9SgemeFuIYLIpBSD70MKBqA+9oN63sA0wuyhbziIQGCdxqo5mDzvPAWzG4f33tIiZoeW5jwP1rUgUxxcPPbFo/M7YAARd6PlbQggAEx8D4OqoLIZCQQDMxZqzNm7OCcWUZ4L+XCuWes4kUr4m9UVbyzhczlnKAleU8WMY2DEIpd8plvg2mUYtmfdrCWMMYqdq/s2mO0C77/2TqnFB7gdWwWkIkqbvaFYNfQPaw4zBFBGw0XARws5NpBoPF4PW34jnJPqm4XIQAAA=&value=N4IgpgHgDmDGAuYAmB9ArlJBDRKYCcBLAe1UIDsVsBPAZxAC4AGAGhHmpkZAAt4BbADYg2/UmG5ZBwtmnzCGIEeAjx8WBI2ABfNgCMstQrBRY08Ht2VpyhAI5ow5MLVopBxYgGsUB2F8YAJiYmbSAA==&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&show_errors=interaction). Note that you can select **Properties** at the top level to remove optional properties (such as `basic_auth`), but not required ones.

**Comment by cantino** [comment]
That is a pretty cool idea.  I don't know if it'd be worth it yet for us to integrate-- it might be a lot of work-- but the idea of JSONSchema as a way to convey valid structure is interesting.

**Comment by spdustin** [comment]
I've started a new branch locally (haven't pushed it) that will do all this. When it's ready for testing, you can let me know if you still don't think it's worth it. ;) JSONSchema is definitely growing as a standard, and I think it'd go well with the modularization of agents-as-gems to include a JSONSchema and a rake task to generate tests for an agent that includes a JSONSchema automatically. I've also played around with nicer-looking forms using that other project as a baseline. It's a big patch I'd be contributing, for sure, but I think there are big payoffs to doing it. :) I won't be upset if it doesn't get merged, I'm certainly going to use it here!

I'll close this issue for now, and will open a PR when I have something to test out.
