### ISSUE TITLE
In DataOutputAgent, enclosed media cannot be output

### ISSUE THREAD

**Issue by flechaig** [cantino/huginn#834]
I have a source RSS feed that I want to filter before importing it in my favorite Podcast Player on Android. The issue is that I can't add attributes to entries in the xml output of an item. This is the output I want to be able to achieve :

```
<rss version="2.0">
<channel>
<ttl>360</ttl>
<link>http://example.com</link>
<title>A title</title>
<description>A description</description>
<item>
<title>Item title</title>
<link>http://example.com</link>
<enclosure url="http://something.com/1.mp3" length="9502596" type="audio/mpeg"/>
</item>
```

Look at the "enclosure" line : it has 3 mandatory attributes to link to the content.
How to achieve that ?
Thanks

**Comment by cantino** [comment]
This seems like a straightforward improvement.  I guess you'd add sub-object to `options['template']['item']` that looked something like `"enclosure": { "tag_type": "enclosure", "self_closing": true, "attributes": { "url": "{{url}}", "length": "??", "type": "audio/mpeg" } }`

Would something like that work?

**Comment by flechaig** [comment]
Sorry, I'm new to Ruby and Huginn, I don't understand your suggestion.
Should I only include this in my  DataOutputAgent ? If so, this is the output :
```<item>
  <title>My title</title>
  <description>My description</description>
  <link>http://example.com/1.mp3</link>
  <enclosure>
   <tag-type>enclosure</tag-type>
   <self-closing>true</self-closing>
   <attributes>
    <url>http://example.com/1.mp3</url>
    <length>9502596</length>
    <type>audio/mpeg</type>
   </attributes>
  </enclosure>
  <guid>15488</guid>
  <pubDate>Thu, 04 Jun 2015 18:04:58 +0200</pubDate>
 </item>
```
This is not what I want.
Or are changes needed in huggin code ? In data_output_agent.rb ? data_output_agent_spec.rb ?
Thank you for your help.

**Comment by cantino** [comment]
Sorry @flechaig, I was unclear.  We do need to modify the Huginn code to allow this.  I'll try to take a look at solving this for you soon.

**Comment by cantino** [comment]
Hey @flechaig, I have a prototype working: https://github.com/cantino/huginn/pull/843

Would you mind testing it?  Try the following:

```
"enclosure": {
  "_attributes": {
    "type" => "audio/mpeg",
    "url" => "{{media_url}}"
  }
}
```

**Comment by flechaig** [comment]
Hi, thank you !
I'll test it, but let me a few days please, I need to setup a dedicated environnement for this. I'll let you know as soon as I test it.
Thanks again

**Comment by cantino** [comment]
You're welcome :) And no rush.

**Comment by flechaig** [comment]
Yes, it works :)

I think it would be event better with an example in true JSON like :
```
"enclosure": {
  "_attributes": {
    "url": "{{media_url}}",
    "length": "1234456789",
    "type": "audio/mpeg"
  }
},
"another_tag": {
  "_attributes": {
    "key": "value",
    "another_key": "another_value"
  },
  "_contents": "tag contents (can be an object for nesting)"
}
```
Thank you

**Comment by cantino** [comment]
Awesome! I'll switch it to JSON, thanks!

**Comment by cantino** [comment]
Merged @flechaig!

**Comment by flechaig** [comment]
Thank you very much.
