### ISSUE TITLE
icon.rake width:nil under huginn_development chef role, works fine under huginn_production

### ISSUE THREAD

**Issue by elijah** [cantino/huginn#837]
So I got this explosion when running vagrant up with the huginn_development role set - meaning that i got the huginn_development chef cookbook from site-cookbooks:

{code}
SyntaxError: /home/huginn/huginn/lib/tasks/icon.rake:72: syntax error, unexpected tLABEL
def convert_image(source, target, width: nil, round: false)
                                        ^
/home/huginn/huginn/lib/tasks/icon.rake:72: Can't assign to nil
def convert_image(source, target, width: nil, round: false)
                                             ^{code}

The same thing works fine when using the huginn_production role.  

I haven't quite figured out what's going on here -- it looks like the ruby convert_image function found in the rakefile expects 'real values' instead of width:nil -- which, for iOS and android, seem to be set already.

I haven't quite figured out what's different in the environment yet - looking at the two cookbooks, what's in the default recipe for starting up the production version seems to be a bit more fleshed out than what's in the "development" cookbook's recipe.

Before I start digging in and thinking about rewriting the 'development' recipe to look a lot more like production - can someone confirm that this is just small breakage, and that the icon.rake stuff actually currently works as intended in someone else's "real" deployment?

**Comment by knu** [comment]
b737a77 may have fixed this, assuming you are using Ruby 1.9.  Could you run git pull and see if it fixes the problem?

**Comment by cantino** [comment]
I think that our vagrant setup may be very out of date. I wonder if we
should remove it?

**Comment by cantino** [comment]
Closing since we haven't heard back.  Hope it's working for you!
