### ISSUE TITLE
Fetch page from event

### ISSUE THREAD

**Issue by alexiri** [cantino/huginn#838]
I'm trying to replicate Yahoo Pipe's "fetch page" source in order to fetch (part of) the content of each link in an RSS feed. How can I do this with Huginn?

**Comment by virtadpt** [comment]
Use an instance of RSSAgent to pull the feed.  RSSAgent emits one event per entry in the RSS or ATOM feed it sees.  Run its output through an instance of DeDuplicationAgent (in case the feed has lots of duplicate entries) followed by something like TriggerAgent to detect what you're really looking for.  Use MessageFormattingAgent to built the output events.

**Comment by cantino** [comment]
Hey @alexiri, welcome!  I think you could potentially use the WebsiteAgent for this.

```
The WebsiteAgent can also scrape based on incoming events. It will scrape the url contained in the url key of the incoming event payload. If you specify merge as the mode, it will retain the old payload and update it with the new values.
```

**Comment by alexiri** [comment]
Hi @cantino, thanks, that's exactly what I wanted! Sorry I missed it in the docs.
