### ISSUE TITLE
Webhook JSONPath Failure

### ISSUE THREAD

**Issue by sean-horn** [cantino/huginn#845]
Huginn Version: master 8dc5387f0b14940af6c728fe4f5c570d325c32ff

In a WebHookAgent, I think I should be able to declare a JSONPath to only capture the value of a leaf node. Currently, it seems that I can only follow the path down to the second to last key and value, i.e `$.foo.bar`, to generate an event of `{"bing": "hmmm"}`

If I try the complete JSONPath `$.foo.bar.bing`, I get an error as shown below, even though I think that is valid JSONPath.

If I do the same at http://ashphy.com/JSONPathOnlineEvaluator/, I get `{"Hmmm"}`

If I try `foo.bar.*` with the WebHookAgent, I get the event `{"bing": "Hmmm"}`

Of course, I can grab the whole JSON with WebHookAgent, then pare down with the EventFormatter, because EventFormatter _does_ allow specifying JSONPath like `$.foo.bar.bing`. This is sub-optimal though, because it preserves more JSON than is strictly necessary in the WebHookAgent Events, if one keeps historical events there.

Is this accurate behavior for the WebHookAgent?

myjson-foo.json
----------------------
```
{
 "foo": {
    "bar": {
      "bing": "hmmm"
    }
  }
}
```
Send Command Line Post
-----------------------------------
Enter a post with the JSON body found in myjson-foo.json and get a failure, if I have specified `$.foo.bar.bing` as the JSONpath in my WebHookAgent

![screen shot 2015-06-07 at 4 46 18 pm](https://cloud.githubusercontent.com/assets/1459992/8026356/215c73a8-0d40-11e5-95a5-b7a85d37f616.png)

WebhookAgent Setup
-----------------------------
I have specified `$.foo.bar.bing` as the JSONpath in my WebHookAgent. The generated event should be `{"hmmm"}`

![screen shot 2015-06-07 at 4 45 42 pm](https://cloud.githubusercontent.com/assets/1459992/8026354/1e621b8a-0d40-11e5-8361-9773956f5c96.png)

**Comment by cantino** [comment]
Hey @sean-horn, welcome and thanks for the detailed report!

The problem is that the output needs to be a valid JSON Object, and `{"hmmm"}` isn't valid JSON.  I'd suggest using `$.foo.bar`.  We could also modify the agent so that JSONPaths to single values return something like `{ "value": "hmm" }`.  Would this be better?

**Comment by sean-horn** [comment]
@cantino Thanks, happy to try to help! Oh yes, I see that.  I think it's ok. I wouldn't make a special case of the final element unless other people have seen a need for this too. Please close at your convenience.

**Comment by cantino** [comment]
Glad you like it!  Let me know if we can help out.
