### ISSUE TITLE
Twitter timelines

### ISSUE THREAD

**Issue by sillygwailo** [cantino/huginn#846]
Is there a way to get a Twitter home timeline flowing into to Huginn via the streaming API? And public lists? Private lists? Not just a single user's timeline, or a filtered stream, but the flow of tweets in what I see when I login to Twitter.com, for example.

**Comment by cantino** [comment]
Hey @sillygwailo.  That isn't possible right now, but it seems like it'd be straightforward to add a TwitterTimelineAgent which could either be streaming (like the TwitterStreamAgent) or intermittent polling (like the TwitterUserAgent).

**Comment by brianpetro** [comment]
@sillygwailo Checkout the Twitter streaming API "with" attribute https://dev.twitter.com/streaming/overview/request-parameters#with

I believe the Twitter Streaming Agent would still need an update to use it, though.

**Comment by Jngai** [comment]
@cantino I think a TwitterTimelineAgent (like twitter user agent) will solve this problem and #1249 as well. Using "with" attribute to streaming agent won't solve #1249 because he doesn't want search terms.

**Comment by Jngai** [comment]
@sillygwailo I modified the twitter user agent to display home timeline/tweets for an authenticated twitter user and their followers here #1249 . The ticket is closed and the pr merged in. I think this solved your problem. @cantino this issue is similar to #1249 you may be able to close this issue as well.

**Comment by cantino** [comment]
Thanks @Jngai!  Please re-open @sillygwailo if this didn't fix the issue.

**Comment by sillygwailo** [comment]
This is very cool. Thanks for the awesome addition, @Jngai!

**Comment by Jngai** [comment]
@sillygwailo no problem!
