### ISSUE TITLE
Filtering agents

### ISSUE THREAD

**Issue by sillygwailo** [cantino/huginn#847]
Is there something like the Filter module that Yahoo! Pipes has, where you can filter on many criteria, and it returns or blocks events based on all or any of the filters? So far I've been doing that with a JavaScript agent, but if there was something that was more of a configurable form, I'd use that.

**Comment by virtadpt** [comment]
You can do it with a TriggerAgent.  I use a few instances of this agent with between 10 and 30 filtering rules each to parse and sort events coming from data feeds.

**Comment by sillygwailo** [comment]
TriggerAgent. Perfect. That opens up a world of possibilities. Thanks!

**Comment by sillygwailo** [comment]
Maybe I need a tutorial on how to create a flow where the following happens:

1. Take in an RSS feed and, for each item emit an event that has a 'url' property. (No problem, that's easy.)
2. A TriggerAgent that says: If the contains any of the specified domains in an array, do not emit the event down the chain. If it doesn't contain any of the domains in the array, emit the event down the chain. How would I work it so that it doesn't pass example1.com and example2.com URLs, but allows anything else?
3. Post to a Slack channel. (No problems there.)

With step 2 I have the double-negative problem: I don't know if 'regex' or '!regex' is the one to use, and 'keep_event' is under-documented. Do I set that to true or false? How do I setup the TriggerAgent in the case outlined above?

**Comment by irfancharania** [comment]
I've been playing around with the RSS and TriggerAgents after seeing the hint from virtadpt. 

My guess would be:

1. 'keep_event' set to true will keep the RSS item for you to pull 'url' from
2. use something like the following (not tested)

```json
    "type": "!regex",
    "value": "google\\.com|bing\\.com",
    "path": "url"
```

My use case has been RSS -> TriggerAgent to filter out items -> RSS

**Comment by cantino** [comment]
Do we need to add a `{ "type": "inclusion", "in": ["foo", "bar"] }` mode to the TriggerAgent?  That would be an easy change.

**Comment by sillygwailo** [comment]
I guess that was my understanding of this: "The value can be a single value or an array of values. In the case of an array, if one or more values match then the rule matches." I get the sense that it doesn't work with arrays of regexes. 

@cantino The syntax you suggest would make that more clear. Would it be able to do regex? I want to filter out domains inside URLs.

**Comment by cantino** [comment]
An array of regexes should work.  Did it not work for you?

This is the current code, which should handle an array of regexes.

```ruby
match_found = rule_values.any? do |rule_value|
  case rule['type']
    when "regex"
      value_at_path.to_s =~ Regexp.new(rule_value, Regexp::IGNORECASE)
    when "!regex"
      value_at_path.to_s !~ Regexp.new(rule_value, Regexp::IGNORECASE)
    ...

```

**Comment by cantino** [comment]
@sillygwailo, as it is right now, you could so something like this right?

```json
"rules": [
  {
    "type": "!regex",
    "value": "ignored-domain-one\\.com",
    "path": "url"
  },
  {
    "type": "!regex",
    "value": "ignored-domain-two\\.com",
    "path": "url"
  }
]
```

**Comment by sillygwailo** [comment]
Array of rules, not an array of values, gotcha. I have this running and have a good feeling about it. I'll post back later after more events go through (and, in some cases, hopefully not).

**Comment by jloons42** [comment]
I have a set of RSS feeds bundled together and I'm working on fine tuning the filtering. Right now I have a trigger agent that is doing a great job of only giving me football articles from my feeds. However, I'd also like to only see high school articles so I am trying to also filter out the already filtered feed. Here is what I have that is only doing half the job. The values I have in the second rule are ones I have seen come through in events today so I know they should filter them out if I run it again.

{
  "expected_receive_period_in_days": "10",
  "keep_event": "true",
  "rules": [
    {
      "type": "regex",
      "value": "football|boys football|Football",
      "path": "title"
    },
    {
      "type": "!regex",
      "value": "COLLEGE|UND|standings|SMSU|Pepin/Alma|Cochrane-Fountain|JV",
      "path": "title"
    }

My question is if I should do a second TriggerAgent to filter out what I don't want, or if it is possible to do both within one TriggerAgent.

**Comment by cantino** [comment]
That looks right to me because I believe that any separate rule is
anded together. I take it that you're seeing things that the not-regex
should be excluding?

**Comment by jloons42** [comment]
I think it is working now. May have jumped the gun a little too soon on thinking it wasn't working. Thanks anyways. I am loving this thing!

**Comment by cantino** [comment]
Glad it's working!  Can we close this ticket?

**Comment by jloons42** [comment]
Sorry I missed your response. Yeah this ticket can be closed.

**Comment by hughwi** [comment]
@cantino sorry to ressurect this - but I have a very similar setup to jloons42 that had been working fine up until recently, when i added a few extra values. - now the filtering agent is returning 0 valid events to pass onto the next agent in the chain.

i understand that .'s have to be escaped, but what about spacing? the new values to match on have spaces, I believe this used to work? - i have added \ (which is being interpreted as \\) but no luck.

Example:

`{   "expected_receive_period_in_days": "1",   "keep_event": "true",   "rules": [     {       "type": "regex",       "value": "(trawler\\ skipper|Head\\ of\\ Aquaculture|Responsible Fishing Scheme Manager|Assistant Fisheries Biologist|Fish\\ Farm\\ Operative|Responsible\\ Fishing\\ Scheme Standards\\ Manager|Fishermen's\\ Training\\ Manager|Fisheries\\ Scientist|Marine\\ Biology|Fish\\ Processing|Fish\\ Farm\\ Manager|Marine\\ Science\\ Support\\ Specialists|Fisheries\\ Assessment\\ Manager|Fisheries|fish\\ farming|fish\\ farm|offshore\\ mariculture|mariculture|fish|seafood|aquaculture|seine|trawl|longline)",       "path": "description"     },     {       "type": "!regex",       "value": "(Teacher|Handyman|Account|Paralegal|Solicitor|Lawyer|Note\\ Takers|Receptionist|Welder|Warehouse|Fundraising|Software|Accountant|Accounting|Finance|Tax|Clinical|Medical|Nurse|Nursery|Linux|Mac|ERP|Help\\ Desk|Desktop|\\.Net|cook|chef)",       "path": "description"     }   ] }`
Thanks

Hugh

**Comment by cantino** [comment]
Hey @hughwi, you shouldn't need to escape spaces. I think adding the `\\` is causing it to look for a literal `\`, which won't be present.
