### ISSUE TITLE
Fulltext fetch for feed item

### ISSUE THREAD

**Issue by irfancharania** [cantino/huginn#848]
I'm trying to fetch full text for a feed item, and I'm unsure how to go about it.
[issue 598](https://github.com/cantino/huginn/issues/598) suggests it's possible but I can't find any other hints.

Here's what I've got:
__Agent 1: Type: Rss Agent__
```json
{
  "expected_update_period_in_days": "5",
  "clean": "false",
  "url": "http://feeds.feedburner.com/oatmealfeed"
}
```
It generates the events as expected.

Next I'm failing at trying to use the urls from the events in a Website Agent

__Agent 2: Type: Website Agent__
Event sources: Agent 1
```json
{
  "expected_update_period_in_days": "5",
  "url": "{{url}}",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "body_text": {
      "css": ".post_body",
      "value": ".//text()"
    },
    "title": {
      "css": "title",
      "value": ".//text()"
    }
  }
}
```

Any ideas?
Thanks!

**Comment by cantino** [comment]
Hey @irfancharania, welcome!

What happens if you change `mode` to `merge`?

**Comment by irfancharania** [comment]
Thanks! That gave me what I was looking for.

Though my initial confusion turned out to be something else: I had to re-emit event from the first agent in order to see it propagate through. Then everything worked.

I think I found a bug in tinkering around with things. In the url field for the second agent, you cannot add a suffix or prefix to the {{url}}.

__Agent 1__
Type: Manual Event Agent
Event receivers: Agent 2
``` json
{
  "url": "https://www.google.ca/search?q="
}
```

__Agent 2__
Type: Website Agent
Event sources: Agent 1
``` json
{
  "expected_update_period_in_days": "2",
  "url": "{{url}}testing",
  "type": "html",
  "mode": "all",
  "extract": {
    "url": {
      "css": "body",
      "value": "normalize-space(.)"
    }
  }
}
```

Looking at the log, Agent 2 only ever tries "Fetching https://www.google.ca/search?q="

Is this intentional?
Could it be changed to allow prefix/suffix?

**Comment by cantino** [comment]
The `url` key is not currently used when a `url` is received from an incoming Event, so you'd need to use an EventFormattingAgent to add the prefix / suffix.

I actually like your approach of always using the options.url in the Agent, and allowing Liquid formatting in it to include an Event's url, but given the current behavior, I'm not sure how best to change it without breaking people's setups.

**Comment by irfancharania** [comment]
Yeah, I realized something was off when I tried to pass it a differently named key and it wouldn't take. EventFormattingAgent it is then.

As far as backwards compatilbility: 
1. The form won't let you leave the url field as blank
2. It won't accept anything other than `url` if incoming
3. If not incoming, you are filling it with non-liquid style text

It doesn't sound like anything would break by allowing for liquid formatting only on incoming

**Comment by reticentsmile** [comment]
I've been playing around with huginn for a week to setup security feeds. I worked around a way to add prefix/suffix to by using concat(string1,string2) function in the value field. For your scenario,try:
 "url": {
      "css": "body",
      "value": "concat('@attr',testing)"
    }
The attr is to replaced with the attribute containing url (which for most cases was @href). Hope this helps. Have fun!

**Comment by irfancharania** [comment]
knu just added easy liquid url formatting with pull #866
check it out!
