### ISSUE TITLE
RssAgent: Missing tags

### ISSUE THREAD

**Issue by irfancharania** [cantino/huginn#851]
RssAgent ignores a number of tags, mainly **guid** and **enclosure**.

Is the fix as simple as adding these in [rss_agent.rb L93](https://github.com/cantino/huginn/blob/285407caeaab8b489c3f0f67f692ee58d2d9bc02/app/models/agents/rss_agent.rb#L93)?
Any reason not to?

**Comment by cantino** [comment]
It may be straightforward.  Do you have an example feed I can test on that has these?

**Comment by irfancharania** [comment]
[This](http://www.mediamonkey.com/wiki/index.php/Podcast_Sample_Feed) seems to be a standard for podcasts

here's [an example feed](http://feed.cnet.com/feed/podcast/googlicious/hd.xml)

**Comment by cantino** [comment]
`guid` should be available in the `id` attribute.  I tried getting enclosure to work, but the RSS parser we're using didn't make it easy.  For now, I'd suggest using the XML parsing capabilities of the WebsiteAgent.

**Comment by irfancharania** [comment]
Okay. I'll give it a shot tomorrow and see how it goes.

**Comment by irfancharania** [comment]
XML parsing with WebsiteAgent works. Thanks Andrew!

Leaving this open as a future "to revisit"

**Comment by Jogan** [comment]
@irfancharania could you share the config you used for your website agent that parses podcast rss feeds?

**Comment by irfancharania** [comment]
I don't bother with podcasts anymore, but here's an example based on the
feed mentioned above:
(haven't tested in a feed reader, but works in the dry run)


{
  "expected_update_period_in_days": "2",
  "url": "http://feed.cnet.com/feed/podcast/googlicious/hd.xml",
  "type": "xml",
  "mode": "on_change",
  "extract": {
    "title": {
      "css": "//item/title",
      "value": "normalize-space(.)"
    },
    "url": {
      "css": "//item/link",
      "value": "normalize-space(.)"
    }
  }
}


What were you specifically having an issue with?

**Comment by thiagotalma** [comment]
+1

**Comment by cantino** [comment]
Does https://github.com/cantino/huginn/pull/957 work any better?

**Comment by cantino** [comment]
Closing this since it's 2 years old :)
