### ISSUE TITLE
Expanding short URLs

### ISSUE THREAD

**Issue by sillygwailo** [cantino/huginn#853]
What's the best way to expand a short URL (say, an ow.ly URL)? I tried a WebsiteAgent that ran it through LongURL.org but that's overthinking it? Also the WebsiteAgent scrapes the value 'url' key of an incoming event anyway, and I don't want it to do that. I want to pass the expanded URL on as an event to another agent.

**Comment by cantino** [comment]
Might potentially be a new UrlExpanderAgent?

**Comment by sillygwailo** [comment]
That would be cool. The easy way to do it would be to just redirect a URL until it doesn't redirect, I assume.

**Comment by K1773R** [comment]
ie, follow each HTTP 301/302 until you get an 200?
there should be a max depth and also auto detection of loops

**Comment by cantino** [comment]
That's right K1773R.  Might be able to use HEAD requests for speed.

**Comment by virtadpt** [comment]
It should also be possible to use the URL shorteners' APIs to expand what they're given (like this one: https://v.gd/apilookupreference.php).

**Comment by knu** [comment]
I think we could add a Liquid function that expands a shortened URL.

**Comment by cantino** [comment]
I like that.

**Comment by knu** [comment]
@sillygwailo Is this working for you?

**Comment by sillygwailo** [comment]
When I try to save an agent with `{{ url | uri_expand }}`, I get the following error in the logs:

    :at=info method=POST path="/agents/12" host=ancient-bastion-3321.herokuapp.com request_id=756d7a5a-1aa3-4620-912b-c71c26a79ee1 fwd="76.10.186.237" dyno=web.1 connect=2ms service=67ms status=500 bytes=951
    [756d7a5a-1aa3-4620-912b-c71c26a79ee1] Started PUT "/agents/12" for 76.10.186.237 at 2015-07-07 16:16:51 +0000
    [756d7a5a-1aa3-4620-912b-c71c26a79ee1]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[[TOKEN REDACTED]]", "agent"=>{"name"=>"Slack: Ingress Channel", "schedule"=>"every_1m", "control_target_ids"=>[""], "keep_events_for"=>"0", "source_ids"=>["", "11"], "propagate_immediately"=>"1", "options"=>"{\r\n  \"webhook_url\": \"https://hooks.slack.com/services/[[TOKEN REDACTED]]\",\r\n  \"channel\": \"#ingress\",\r\n  \"username\": \"Talkwalker: Ingress\",\r\n  \"message\": \"{{url | uri_expand}}\",\r\n  \"icon\": \"\",\r\n  \"unfurl_links\": true\r\n}"}, "commit"=>"Save", "id"=>"12"}
    [756d7a5a-1aa3-4620-912b-c71c26a79ee1] 
    ArgumentError (bad argument (expected URI object or URI string)):
      app/concerns/liquid_interpolatable.rb:142:in `uri_expand'
      app/concerns/liquid_interpolatable.rb:91:in `block in interpolate_string'
      app/concerns/liquid_interpolatable.rb:53:in `interpolate_with'
      app/concerns/liquid_interpolatable.rb:90:in `interpolate_string'
      app/concerns/liquid_interpolatable.rb:69:in `block in interpolate_options'
      app/concerns/liquid_interpolatable.rb:53:in `interpolate_with'
      app/concerns/liquid_interpolatable.rb:66:in `interpolate_options'
      app/concerns/liquid_interpolatable.rb:72:in `block (2 levels) in interpolate_options'
      app/concerns/liquid_interpolatable.rb:71:in `each'
      app/concerns/liquid_interpolatable.rb:71:in `each_with_object'
      app/concerns/liquid_interpolatable.rb:71:in `block in interpolate_options'
      app/concerns/liquid_interpolatable.rb:53:in `interpolate_with'
      app/concerns/liquid_interpolatable.rb:66:in `interpolate_options'
      app/concerns/liquid_interpolatable.rb:85:in `block in interpolated'
      app/concerns/liquid_interpolatable.rb:53:in `interpolate_with'
      app/concerns/liquid_interpolatable.rb:83:in `interpolated'
      app/concerns/liquid_interpolatable.rb:15:in `validate_interpolation'
      app/concerns/liquid_interpolatable.rb:9:in `valid?'
      app/controllers/agents_controller.rb:177:in `block in update'
      app/controllers/agents_controller.rb:176:in `update'
    config/initializers/silence_worker_status_logger.rb:5:in `call_with_silence_worker_status'

**Comment by sillygwailo** [comment]
I've made it `{{ url | to_uri | uri_expand }}` and it saves. I'll let you know how it goes once events roll in.

**Comment by knu** [comment]
Thanks for the report!
c4459308 should rescue any error raised in validate_interpolation, and 01219153 I just committed an improvement on uri_expand so it does not fail when a non-string/non-URI object is given.
Please upgrade your huginn!

**Comment by sillygwailo** [comment]
I upgraded, and it looks that way. Thanks!

**Comment by knu** [comment]
Great!  I'm closing this, then.

**Comment by cantino** [comment]
Thank you both!
