### ISSUE TITLE
Wrong url_encode

### ISSUE THREAD

**Issue by K1773R** [cantino/huginn#854]
I have an RSS Feed i'd like to scrape
```
https://foo.bar/bla/blub.aspx?GetRss?CategoryNr=12345
```

unfortunately, huginn replaces this to
```
https://foo.bar/bla/blub.aspx?GetRss%3FCategoryNr=12345
```
and the server returns an error...

**Comment by cantino** [comment]
The URL has two `?` in it?  That's not valid.

**Comment by K1773R** [comment]
all other browsers handle it w/o problem. i checked with fake ssl certs + tcpdump that only huginn does that.

**Comment by dsander** [comment]
Interesting, thats the first time I have seen a URL formatted like this too. The [RFC 3986](http://tools.ietf.org/html/rfc3986#section-3.4) really seem to allow it. I don't know how much we can do about this since I think we are just passing the URL to `faraday` to fetch it.

**Comment by K1773R** [comment]
@dsander its not only with the RSSAgent. its also with the WebsiteAgent...

**Comment by dsander** [comment]
@K1773R would you mind testing https://github.com/dsander/huginn/tree/disable-faraday-url-encoding ? This is still a bit rough, but you should be able to disable the url encoding by setting `disable_url_encoding` to `true` in your RSS or WebsiteAgent.

**Comment by K1773R** [comment]
@dsander it works half. urlencoding is disabled as it should, but unfortunately it adds a = add the end of the query string...

Here is my agent configuration (just a example RSS, there are tons of them...) so you can test yourself.
```
{
  "expected_update_period_in_days": "5",
  "clean": "false",
  "url": "http://www.ricardo.ch/dataservice/xmlproxy.aspx?GetRss?CategoryNr=39207",
  "disable_url_encoding": "true"
}
```

**Comment by dsander** [comment]
Sorry my bad, I updated the branch and the problem should be fixed. Your example worked fine on my installation.
