### ISSUE TITLE
Limit RSS feed items

### ISSUE THREAD

**Issue by irfancharania** [cantino/huginn#858]
Is there a way to limit the number of RSS items fetched similar to the [Truncate Module in Yahoo Pipes](http://pipes.yahoo.com/pipes/docs?doc=operators#Truncate)?

Scenario: Feed has a large number of items, and I only want the most recent 10.

**Comment by cantino** [comment]
Not at the moment, but that would be an easy addition to the RSSAgent.
I'll try to add it for you.

**Comment by cantino** [comment]
@irfancharania, are you interested in learning a bit of Ruby and getting your hands into the Huginn code?  If so, that feature would be straightforward to work on and is definitely something I could help you through.

**Comment by irfancharania** [comment]
Sure!
I'll have time closer to the end of the week, and ask for guidance then. Work for you?

**Comment by cantino** [comment]
Sounds great!  Glad to have you involved :)
