### ISSUE TITLE
Event Formatting Agent: Replacers?

### ISSUE THREAD

**Issue by irfancharania** [cantino/huginn#859]
In the Event Formatting Agent, what do you think about having a "Replacers" setting?

It would be handy to be able to match and substitute text that you can't really easily do with matchers. Scenario: `I have / some / long text / from / some source ` and I just want to easily remove all instances of `/` by replacing them with empty space. 

To keep things simple, order would be insignificant: matchers always match on original text.

**Comment by knu** [comment]
If you just need simple (literal) string substitution, try the `replace` filter: `{{ string | replace:' / ',' ' }}`
https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#standard-filters

If you want regex, we'd consider adding a custom filter.

**Comment by irfancharania** [comment]
That worked. Regex might have been cleaner, but you can pipe multiple filters, so no need. 
Thanks!

**Comment by cantino** [comment]
Would one of you mind adding that trick to the Liquid page on the wiki?
Very cool!

**Comment by irfancharania** [comment]
It's already there:
https://github.com/cantino/huginn/wiki/Formatting-Events-using-Liquid#basic-usage-of-liquid-in-huginn

It just didn't occur to me right away as an option...

**Comment by irfancharania** [comment]
I updated the existing example slightly.

**Comment by cantino** [comment]
Thanks :)

**Comment by HyShai** [comment]
I would love to have Regex replace functionality (without using the JS agent). As a newcomer from Yahoo Pipes - this was a huge part of my scraping pipes. E.g. to replace part of a badly formatted url.
I know that shopify doesn't [officially support regex replace](https://github.com/Shopify/liquid/issues/202)  but it would seriously be awesome.

**Comment by cantino** [comment]
@HyShai Would this be a new Agent type that replaces text of events that come through it?

**Comment by HyShai** [comment]
@cantino I was thinking of functionality added to the Event Formatting agent similar to `matchers`. (Or alternatively a custom Liquid filter.)
I think the semantics of usage for the Event Formatter Agent would probably be a better place for Regex Replace (i.e. formatting...).

**Comment by cantino** [comment]
That's an interesting idea.  Would you be interested in trying to add this functionality?

**Comment by HyShai** [comment]
@cantino My Rails skills aren't put to par, but I will definitely try to add this. The EventFormatting Agent seems like one of the more complex ones so I'll probably need some assistance getting up to speed.

**Comment by knu** [comment]
Why not add a Liquid filter so it can be used anywhere other than EventFormattingAgent?
