### ISSUE TITLE
cannot match precise term in TwitterStreamAgent

### ISSUE THREAD

**Issue by j0narch3r** [cantino/huginn#860]
I am having trouble getting the TwitterStreamAgent to return tweets matching a precise term.

e.g.

filter: [
match this term <= this matches if all words appear in any order
"match this term" <= this does not match because it looks for the term to include quotes
]

Evidently, when I put quotes around the term in the filter, the output escapes them, turning them into actual quotes to be searched for, which it won't find, and therefore won't match.

How can I get the TwitterStreamAgent to match a precise term?

**Comment by cantino** [comment]
Hey @j0narch3r, I'd think that if you did `'"something in quotes"'`, we'd send that through to Twitter literally.  I assume https://twitter.com/search-home does what you'd want?

**Comment by j0narch3r** [comment]
I would have assumed so, too. Under Details in the Agent, the term gets sent as "\"something in quotes\"", but for some reason tweets weren't appearing. (I sent a series of test tweets with the term from another account, and no emails were triggered until I removed the quotes.)

For total clarity, here are screencaps of my setup, with one term in quotes for demonstration purposes:

![image](https://cloud.githubusercontent.com/assets/1578205/8200861/9d3a9bda-147f-11e5-8e1c-5d8a92289b6b.png)

![image](https://cloud.githubusercontent.com/assets/1578205/8200873/c9aa9bde-147f-11e5-80c4-0b273bb73897.png)

**Comment by dsander** [comment]
I don't think exact matches are possible, the API [docs](https://dev.twitter.com/streaming/overview/request-parameters#track) do not mention it. Have you tried using "music makes a city" (without the quotes)?

**Comment by j0narch3r** [comment]
@dsander Thanks, I had suspected that might be the case. Yes, without the quotes everything works just fine—it just throws a fair number of false positives since it's unique in that order, but fairly non-unique if they can appear in any order. At the volume I'm dealing with, not really a big deal.
