### ISSUE TITLE
DOMAIN in .env file has no effect

### ISSUE THREAD

**Issue by Puneeth-n** [cantino/huginn#861]
The DOMAIN parameter in the .env file which contains the default address to bind the huggin server doesn't seem to work and always binds to 127.0.0.1:3000

**Comment by cantino** [comment]
Are other params from the .env being picked up? Are you running Rails in
development or production mode?

**Comment by Puneeth-n** [comment]
I am trying to bring up the vagrant box using the vagrant file provided. I will update here soon.

**Comment by Puneeth-n** [comment]
Works with docker. May be some problem with chef version/ cookbook

**Comment by virtadpt** [comment]
Is the address you have set in the DOMAIN option a hostname or an IP?  If it's a hostname, is it resolvable by DNS or is it in /etc/hosts?  If it's an IP, make sure it's on one of the network interfaces on the system.

**Comment by Puneeth-n** [comment]
I provide the ip address in the env file and definetely it is on my ethernet network interface. I moved to docker as it worked seamlessly.

**Comment by cantino** [comment]
Closing since we haven't heard back.  Hope it's working for you!
