### ISSUE TITLE
Email not being sent

### ISSUE THREAD

**Issue by Edu115** [cantino/huginn#867]
Hi,

Yet another issue configuring huginn :disappointed: 

When running a job from an EmailDigestAgent I get the error

```
                 550 5.1.1 <[MY EMAIL HERE]>: Recipient address rejected: User unknown in local recipient table

/usr/lib/ruby/2.2.0/net/smtp.rb:964:in `check_response'
/usr/lib/ruby/2.2.0/net/smtp.rb:933:in `getok'
/usr/lib/ruby/2.2.0/net/smtp.rb:869:in `rcptto'
/usr/lib/ruby/2.2.0/net/smtp.rb:850:in `block in rcptto_list'
/usr/lib/ruby/2.2.0/net/smtp.rb:848:in `each'
/usr/lib/ruby/2.2.0/net/smtp.rb:848:in `rcptto_list'
/usr/lib/ruby/2.2.0/net/smtp.rb:663:in `send_message'
/var/lib/gems/2.2.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:113:in `block in deliver!'
/usr/lib/ruby/2.2.0/net/smtp.rb:521:in `start'
/var/lib/gems/2.2.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
/var/lib/gems/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
/var/lib/gems/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `block in deliver'
/var/lib/gems/2.2.0/gems/actionmailer-4.2.1/lib/action_mailer/base.rb:543:in `block in deliver_mail'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
/var/lib/gems/2.2.0/gems/actionmailer-4.2.1/lib/action_mailer/base.rb:541:in `deliver_mail'
/var/lib/gems/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:236:in `deliver'
/var/lib/gems/2.2.0/gems/actionmailer-4.2.1/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
/var/lib/gems/2.2.0/gems/actionmailer-4.2.1/lib/action_mailer/delivery_job.rb:10:in `perform'
/var/lib/gems/2.2.0/gems/activejob-4.2.1/lib/active_job/execution.rb:32:in `block in perform_now'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:343:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/var/lib/gems/2.2.0/gems/activejob-4.2.1/lib/active_job/logging.rb:23:in `call'
/var/lib/gems/2.2.0/gems/activejob-4.2.1/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
/var/lib/gems/2.2.0/gems/activejob-4.2.1/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/var/lib/gems/2.2.0/gems/activejob-4.2.1/lib/active_job/logging.rb:43:in `block in tag_logger'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
/var/lib/gems/2.2.0/gems/activejob-4.2.1/lib/active_job/logging.rb:43:in `tag_logger'
/var/lib/gems/2.2.0/gems/activejob-4.2.1/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:441:in `instance_exec'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:342:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:342:in `block in simple'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:497:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:497:in `block in around'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_perform_callbacks'
/var/lib/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/2.2.0/gems/activejob-4.2.1/lib/active_job/execution.rb:31:in `perform_now'
/var/lib/gems/2.2.0/gems/activejob-4.2.1/lib/active_job/execution.rb:21:in `execute'
/var/lib/gems/2.2.0/gems/activejob-4.2.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:34:in `perform'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
/usr/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
/usr/lib/ruby/2.2.0/timeout.rb:99:in `call'
/usr/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
/usr/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
/usr/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:124:in `run'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:112:in `block in run_process'
/var/lib/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
/var/lib/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
/var/lib/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:264:in `call'
/var/lib/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:264:in `start_proc'
/var/lib/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
/var/lib/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/controller.rb:73:in `run'
/var/lib/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
/var/lib/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/var/lib/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/var/lib/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:110:in `run_process'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:91:in `block in daemonize'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `times'
/var/lib/gems/2.2.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `daemonize'
script/delayed_job:5:in `<main>'
```

Why would it try to use my local postfix instance and not the configured Google Apps SMTPD server?
Bear in mind that this is running in development mode (as I can't seem to configure nginx to run this in production), but SEND_EMAIL_IN_DEVELOPMENT is set to true.

**Comment by cantino** [comment]
You're using `foreman` and it's definitely loading your `.env`?

**Comment by Edu115** [comment]
@cantino yes, and I think so, as all other agents work fine.

**Comment by cantino** [comment]
Can you share a de-sensitized copy of your .env?

**Comment by virtadpt** [comment]
In particular, we need to look at the values for the SMTP_* variables in your .env file.

**Comment by Edu115** [comment]
'''
# ==== Required configuration settings for Huginn ====

# Replace the following with the output from "rake secret"
APP_SECRET_TOKEN=[REDACTED]

# This is the domain where your Huginn instance will be running. The default should work
# for development, but it needs to be changed to your Huginn domain when you deploy to a
# production environment (e.g., yourdomain.com, possibly including a port).
DOMAIN=[REDACTED]

# Optionally set an asset host
# ASSET_HOST=http://assets.example.com

############################
#      Database Setup      #
############################

DATABASE_ADAPTER=mysql2
#DATABASE_ENCODING=utf8
DATABASE_RECONNECT=true
DATABASE_NAME=huginn_development
DATABASE_POOL=10
DATABASE_USERNAME=root
DATABASE_PASSWORD=[REDACTED]
#DATABASE_HOST=your-domain-here.com
#DATABASE_PORT=3306
#DATABASE_SOCKET=/tmp/mysql.sock

# MySQL only: If you are running a MySQL server >=5.5.3, you should
# set DATABASE_ENCODING to utf8mb4 instead of utf8 so that the
# database can hold 4-byte UTF-8 characters like emoji.
DATABASE_ENCODING=utf8mb4

# ==== Additional required production settings ====

# Configure Rails environment.  This should only be needed in production and may cause errors in development.
# RAILS_ENV=production

# Should Rails force all requests to use SSL?
FORCE_SSL=false

############################
#     Allowing Signups     #
############################

# This invitation code will be required for users to signup with your Huginn installation.
# You can see its use in user.rb.  PLEASE CHANGE THIS!
INVITATION_CODE=[REDACTED]

#############################
#    Email Configuration    #
#############################

# Outgoing email settings.  To use Gmail or Google Apps, put your Google Apps domain or gmail.com
# as the SMTP_DOMAIN and your Gmail username and password as the SMTP_USER_NAME and SMTP_PASSWORD.
#
# PLEASE NOTE: In order to enable emails locally (e.g., when not in the production Rails environment),
# you must also set SEND_EMAIL_IN_DEVELOPMENT to true below.
#
# If you have trouble with port 587 on Gmail, you can also try setting
# SMTP_AUTHENTICATION to login and the SMTP_PORT to 465.

SMTP_DOMAIN=eduardoneves.net
SMTP_USER_NAME=huginn@eduardoneves.net
SMTP_PASSWORD=[REDACTED]
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true

# Send emails when running in the development Rails environment.
SEND_EMAIL_IN_DEVELOPMENT=true

# The address from which system emails will appear to be sent.
EMAIL_FROM_ADDRESS=[REDACTED]

###########################
#      Agent Logging      #
###########################

# Number of lines of log messages to keep per Agent
AGENT_LOG_LENGTH=200

########################################################################################################
#    OAuth Configuration                                                                               #
#  More information at the wiki: https://github.com/cantino/huginn/wiki/Configuring-OAuth-applications #
########################################################################################################

TWITTER_OAUTH_KEY=
TWITTER_OAUTH_SECRET=

THIRTY_SEVEN_SIGNALS_OAUTH_KEY=
THIRTY_SEVEN_SIGNALS_OAUTH_SECRET=

GITHUB_OAUTH_KEY=
GITHUB_OAUTH_SECRET=

TUMBLR_OAUTH_KEY=
TUMBLR_OAUTH_SECRET=

DROPBOX_OAUTH_KEY=
DROPBOX_OAUTH_SECRET=

WUNDERLIST_OAUTH_KEY=
WUNDERLIST_OAUTH_SECRET=

#############################
#  AWS and Mechanical Turk  #
#############################

# AWS Credentials for MTurk
AWS_ACCESS_KEY_ID="your aws access key id"
AWS_ACCESS_KEY="your aws access key"

# Set AWS_SANDBOX to true if you're developing Huginn code.
AWS_SANDBOX=false

########################
#   Various Settings   #
########################

# Specify the HTTP backend library for Faraday, commonly used by
# WebsiteAgent, RssAgent and PostAgent.  You can change this depending
# on the performance and stability you need for your service.  Any
# choice other than "typhoeus", "net_http", or "em_http" should
# require you to bundle a corresponding gem via Gemfile.
FARADAY_HTTP_BACKEND=typhoeus

# Specify the default User-Agent header value for HTTP requests made
# by Agents that allow overriding the User-Agent header value.
DEFAULT_HTTP_USER_AGENT="Huginn - https://github.com/cantino/huginn"

# Allow JSONPath eval expresions. i.e., $..price[?(@ < 20)]
# You should not allow this on a shared Huginn box because it is not secure.
ALLOW_JSONPATH_EVAL=false

# Enable this setting to allow insecure Agents like the ShellCommandAgent.  Only do this
# when you trust everyone using your Huginn installation.
ENABLE_INSECURE_AGENTS=false

# Enable this setting to allow second precision schedule in
# SchedulerAgent.  By default, the use of the "second" field is
# restricted so that any value other than a single zero (which means
# "on the minute") is disallowed to prevent abuse of service.
ENABLE_SECOND_PRECISION_SCHEDULE=false

# Specify the scheduler frequency in seconds (default: 0.3).
# Increasing this value will help reduce the use of system resources
# at the expense of time accuracy.
SCHEDULER_FREQUENCY=0.3

# Use Graphviz for generating diagrams instead of using Google Chart
# Tools.  Specify a dot(1) command path built with SVG support
# enabled.
#USE_GRAPHVIZ_DOT=dot

# Timezone. Use `rake time:zones:local` or `rake time:zones:all` to get your zone name
TIMEZONE="Amsterdam"

# Number of failed jobs to keep in the database
FAILED_JOBS_TO_KEEP=100

# Maximum runtime of background jobs in minutes
DELAYED_JOB_MAX_RUNTIME=20

# Amount of seconds for delayed_job to sleep before checking for new jobs
DELAYED_JOB_SLEEP_DELAY=10
'''

**Comment by cantino** [comment]
Well, it looks fine to me.  @virtadpt, do you notice anything odd?

To be super sure that the .env is being read, you could change `DATABASE_NAME` to gibberish and make sure the server won't start.

**Comment by virtadpt** [comment]
SMTP_USER_NAME=huginn@eduardoneves.net jumped out at me.
@Edu115, if you log into the Google Apps Admin page, is there a user 'huginn' set up in the Users panel?  If that e-mail address doesn't exist, it can't be used to send mail.

**Comment by Edu115** [comment]
![screen shot 2015-06-24 at 21 12 24](https://cloud.githubusercontent.com/assets/665222/8339149/bf37c960-1ab5-11e5-899e-e0a95906c8de.png)

**Comment by virtadpt** [comment]
Okay, that rules that out.
Try setting the value of EMAIL_FROM_ADDRESS= to huginn@eduardoneves.net, restart Huginn, and try again.  Maybe the GMail server doesn't like it when you log in as one user but have a From: header of someone else.

**Comment by cantino** [comment]
Closing since we haven't heard back.  Hope it's working for you!
