### ISSUE TITLE
Heroku auto-deploy failed

### ISSUE THREAD

**Issue by danielpcox** [cantino/huginn#869]
...
-----> Compiling Ruby/Rails
 !
 !     An error occurred while installing Ruby ruby-2.0.0
 !     For supported Ruby versions see https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
 !     Note: Only the most recent version of Ruby 2.1 is supported on Cedar-14
 !     Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar-14/ruby-2.0.0.tgz -s -o - | tar zxf - ' failed unexpectedly:
 !     
 !     gzip: stdin: invalid compressed data--format violated
 !     tar: Unexpected EOF in archive
 !     tar: Unexpected EOF in archive
 !     tar: Error is not recoverable: exiting now
 !
 !     Push rejected, failed to compile Multipack app

**Comment by cantino** [comment]
Hey @danielpcox, thanks for letting us know!  I just clicked the Heroku button in our README and it built successfully.  Did you do anything different?  Mind trying again and seeing if it was a brief glitch on their end?

**Comment by danielpcox** [comment]
All I did was name it and click Deploy for Free. I just did it again and it worked, though, so I guess you're right: it was a temporary problem on their end. Looking forward to trying out huginn!

**Comment by cantino** [comment]
Thanks for trying again.  Welcome aboard :)
