### ISSUE TITLE
Deployment on a VPS 

### ISSUE THREAD

**Issue by robbielj** [cantino/huginn#870]
Hello @cantino 

Yesterday I deployed huginn instance on a Digitalocean vps (ubuntu 14.04, x64) in production mode. The guide in the wiki section (Deployment with Capistrano, Unicorn, nginx, Foreman, and Upstart) seems to be based on ruby1.9.1. `rvm` can offer ruby2+.  Also i suspect `Capistrano` is not really needed if one just want to clone app to vps, configure it and host it via nginx for personal use.

I referred the `deployment/site-cookbooks/huginn_production/recipes/default.rb` for the steps. Maybe it is a good idea to make a separate guide. If you think so, i can contribute a bit. You can also check whether i have made any mistake then :)

**Comment by virtadpt** [comment]
Please do make a wiki page for this.  I've tried to deploy in production mode several times, and bollixed it up each time.

**Comment by dsander** [comment]
I have started working on a guide, will try to finish it over the weekend.

**Comment by robbielj** [comment]
@dsander okay then ;)

**Comment by cantino** [comment]
Thanks @dsander.  @robbielj, maybe you can proof / refine it when he's done?

**Comment by robbielj** [comment]
@cantino yep.
