### ISSUE TITLE
Question about RSS and Extraction matching with website agent

### ISSUE THREAD

**Issue by nris** [cantino/huginn#874]
I'm trying to pull out a full rss, from the url i wish to extract two div.
In the Website Agent:
{
  "expected_update_period_in_days": "14",
  "url": "{{url}}",
  "type": "html",
  "mode": "merge",
  "extract": {
    "body_text": {
      "css": ".filelist, .download",
      "value": "./node()"
    }
  }
}

and 

DataOutputEvent:

{
  "secrets": [
    "examplerss"
  ],
  "expected_receive_period_in_days": "14",
  "template": {
    "title": "test full rss",
    "description": "desc test",
    "item": {
      "title": "{{title}}",
      "description": "{{body_text}}",
      "pubDate": "{{pubDate}}"
    }
  }
}

The rss result i get are two different item entry with same title,pubdate but the description is one from css .filelist and the other one from css .download .
I wish to get one rss item with both .filelist and .download content in the description,

is that possible?

**Comment by irfancharania** [comment]
What happens if, in the Website Agent, you extract the two separately as {{filelist}} and {{download}} instead of in one {{body_text}}, and then in DataOutput you join the two results together in description?

**Comment by nris** [comment]
irfancharania: i tried to do something like that but dont know what to use as alternate body_text in websiteagent and how to merge the results in the output.

(im totally newbie and honestly i found out about huginn after yahoo pipes died :)

**Comment by irfancharania** [comment]
You don't need `body_text`; you can extract whatever you want...
You could try something like this and see if it does the trick:

__WebsiteAgent__
```json
"extract": {
    "filelist": {
      "css": ".filelist",
      "value": "./node()"
    },
    "download": {
      "css": ".download",
      "value": "./node()"
    }
  }
```

__DataOutput__
```json
"template": {
    "item": {
      "description": "{{filelist}} - {{download}}",
    }
```

**Comment by nris** [comment]
irfancharania:
it works!
ThankYou!

**Comment by cantino** [comment]
I'm glad that worked for you @nris.  Thanks @irfancharania!
