### ISSUE TITLE
Accessing locally hosted huginn through intranet

### ISSUE THREAD

**Issue by reticentsmile** [cantino/huginn#875]
I've been playing around with huginn and am currently done with configuring and setting up agents. Now, is it possible to allow locally hosted huginn to be accessed by anyone through intranet?
I've tried setting up alias which points to the localhost and then trying to access it through the domain alias but something seems to be missing.. Any advice?

**Comment by dsander** [comment]
Hi @reticentsmile, 

if you are running huginn in development [this](https://github.com/cantino/huginn/issues/761#issuecomment-88311126) might solve your problem. However when you not planning to do huginn development on that installation it is recommended to run huginn in the production environment.

I am working new installation instructions, the guides are not complete yet but the installation [part](https://github.com/dsander/huginn/blob/deployment-guide/doc/install/installation.md) has been working fine for me.

**Comment by nris** [comment]
hello,
add "GatewayPorts yes" to /etc/ssh/sshd_config
run command "screen"
run ssh -R 9000:127.0.0.1:3000 user@IPHUGINNISRUNNINGON

this way im accessing from internet to huginn on a vps

**Comment by dsander** [comment]
That does not sound like a production installation, have you looked at the guide I linked? If you follow it huginn will be available at the http port 80, proxied by nginx, which is the suggested way to run huginn in production.

**Comment by reticentsmile** [comment]
@dsander  thanks a lot for the suggestion. I've followed the one with running huginn in development and it works. Hope configuring iptables on top of it would solve the security problems. I will also try the guide for deploying it in production mode on Gentoo linux and let you know if that works! 

@nris Never used screen before! But I've tried as you said and it doesn't solve my issue. Thanks!
