### ISSUE TITLE
Generatin Pastebin RSS from Website

### ISSUE THREAD

**Issue by nris** [cantino/huginn#876]
Hello,
I'm trying to make a rss from an user pastebin page,

first agent i use (WebsiteAgent):
```json
{
  "expected_update_period_in_days": "2",
  "url": "http://pastebin.com/u/NWPlayer123",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "body_text": {
      "xpath": "//*[(@id = \"content_left\")] | //tr/td/a",
      "value": "@href"
    }
  }
}
```

second is TriggerAgent, which from WebsiteAgent it gets

```json
{
  "body_text": "/archive/text"
}
```
and
```json
{
  "body_text": "/FaSCTsjp"
}
```
and so on

i need first to get rid of "/archive/text"  and then replace "/FaSCTsjp" with "http://pastebin.com/FaSCTsjp"

is it possible?

**Comment by irfancharania** [comment]
You can use the EventFormattingAgent to format it however you like:

```json
{
  "instructions": {
    "url": "http://pastebin.com{{body_text}}"
  },
  "mode": "merge"
}
```

**Comment by nris** [comment]
there are the agents i setup to get pastebin user content to rss:

WebsiteAgent:
{
  "expected_update_period_in_days": "2",
  "url": "http://pastebin.com/u/NWPlayer123",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "body_text": {
      "xpath": "//*[(@id = \"content_left\")] | //tr/td/a",
      "value": "@href"
    }
  }
}

EventFormattingAgent:
{
  "instructions": {
    "url": "http://pastebin.com{{body_text}}"
  },
  "mode": "merge"
}

TriggerAgent:
{
  "expected_receive_period_in_days": "2",
  "keep_event": "true",
  "rules": [
    {
      "type": "!regex",
      "value": ".*\\/archive\\/.*",
      "path": "url"
    },
    {
      "type": "!regex",
      "value": "^http\\:\\/\\/pastebin\\.com$",
      "path": "url"
    }
  ]
}

WebsiteAgent:
{
  "expected_update_period_in_days": "2",
  "url": "{{url}}",
  "type": "html",
  "mode": "merge",
  "extract": {
    "title": {
      "css": "h1",
      "value": ".//text()"
    },
    "text": {
      "css": "#selectable > div > ol",
      "value": "./node()"
    }
  }
}

DataOutputAgent:
{
  "secrets": [
    "a-secret-key"
  ],
  "expected_receive_period_in_days": 2,
  "template": {
    "title": "pastebin rss",
    "description": "This is a feed of recent pastebin user, generated by Huginn",
    "item": {
      "title": "{{title}}",
      "description": "{{text}}",
      "link": "{{url}}"
    }
  }
}

is there a better way to do it?

Thanks again irfancharania!

**Comment by virtadpt** [comment]
This might make what you want to do a little easier: http://pastebin.com/api#9

**Comment by nris** [comment]
is there a way to reverse the item display order? at the moment above agents give oldest on top and newest on bottom of the rss results

**Comment by nris** [comment]
@virtadpt thanks, at the moment I'm trying to understand how to make rss from website page, pastebin is just a test

**Comment by virtadpt** [comment]
Okay.  Just a suggestion.

**Comment by cantino** [comment]
I don't think we have a way to reverse items right now.  That's a good suggestion.

**Comment by knu** [comment]
I have a plan to introduce the concept of "sort key" to WebsiteAgent.  I'll open an issue later.

**Comment by mdazmir** [comment]
@knu Is the "sort key" function that you mentioned already available in the current version? I'm having a similar problem with @nris where my Website Agent RSS output the oldest result on top and newest at the bottom. Any idea on how to reverse the output?

**Comment by cantino** [comment]
Is it okay to close this issue @nris and @knu?
