### ISSUE TITLE
Error while using de_duplication

### ISSUE THREAD

**Issue by HiddenKn** [cantino/huginn#877]
Error: https://gist.github.com/HiddenKn/5b4e2f91f167fbc3e3c8

Event info (WebHookAgent)
  Event from YoutubePythonScript 
  Expires in: never
  
  Payload:
  
  {
    "body": "New video: Mass Effect Andromeda News! ~ Way to Andromeda Discovered?",
    "url": "http://youtu.be/eavFOjFtICI"
  }

**Comment by dsander** [comment]
Hi @HiddenKn,

is it possible that you deleted the memory of your DeDuplicationAgent? If that is the case I think it is a bug in the Agent. Sadly the only way to resolve it would be to clone your current agent and delete the old one.

**Comment by HiddenKn** [comment]
Yup, that was the issue. Thank you!

**Comment by cantino** [comment]
To clarify-- did you click the button that cleared the Agent's memory?  If so, I agree that we have a bug; Agents should know how to clear their own memory in a safe way.

**Comment by HiddenKn** [comment]
Yes, I did.

**Comment by roxaloxa** [comment]
I'm still experiencing this bug (currently on a Heroku deploy). I clear the DeDuplication Agent's memory and it stops working until I clone it and put the new one in the chain.

**Comment by cantino** [comment]
Thanks, please let us know!

**Comment by roxaloxa** [comment]
@cantino: I had misread when the deploy happened and it looks like it was indeed before this fix. Dumping the memory of the agent works just fine now that we've updated. Sorry for the premature scare.

**Comment by cantino** [comment]
No problem!
