### ISSUE TITLE
nginx socket connection refused

### ISSUE THREAD

**Issue by reticentsmile** [cantino/huginn#879]
Followed the guide posted by @dsander on this link:
https://github.com/dsander/huginn/blob/deployment-guide/doc/install/installation.md
to host my own server.
Pretty much everything worked and the test also completed. But, when I try to access huginn through a browser, it doesn't work. On looking through logs on /var/log/nginx/huginn-errors.log, I get an error saying: connect to ........socket ... connection refused. 
I've tried replacing sockets with 127.0.0.1:80 on listen (unicorn) & server (nginx)  too, it doesn't work.
My doubt is on the huginn process, is there a way to check if unicorn is running huginn correctly? or Is it an issue related to permissions? Any help would be really appreciated.

**Comment by dsander** [comment]
Hm I never had that issue during my tests.

I suppose you started huginn with `sudo start huginn`?

Can you paste the output of `/home/huginn/huginn/log/unicorn.log`? It should say something like: `INFO -- : listening on addr=/home/huginn/huginn/tmp/sockets/unicorn.socket fd=8`

If that file does not exist, check your `Procfile`, it is important that you use one of the example configuration from the "Procution" [section](https://github.com/dsander/huginn/blob/deployment-guide/Procfile#L15-L27)

**Comment by reticentsmile** [comment]
It's weird. I don't see unicorn.log file inside log folder. After which I was trying to solve it for like the whole day. 
Luckily, when I was retrying it again from my PC it worked, and the only difference between both is that my laptop has ubuntu 15.04 while my pc has v14.04 LTS. Still can't find in what way it affects huginn.
Also, I remembered getting an error in 15.04 initially saying "start: unable to connect to upstart" while starting huginn after which I changed the upstart package and modified initctl to return true. But I never had to to this while configuring in 14.04 version. Think this might the prime suspect.
PS: I request you to add a line or two in the guide to update secret key within .env file, so that any newcomers don't leave it out!

**Comment by dsander** [comment]
That really sounds like like unicorn is not enabled in the `Procfile`, can you check the contents on your `14.04` installation? Both the missing log file and socket would be explained by this.

Good to know the guide also works on `15.04`, the problem with upstart was that ubuntu changed the default init system to systemd with the 15.04 release.

**Comment by reticentsmile** [comment]
Sorry for the confusion, what I meant was:
14.04 - It works with your guide.
15.04: 
           - I get the upstart unable to connect error. 
           - After modifying initctl to return true (or forcing upstart to be the default), it doesn't throw any error when i run huginn but I don't get the message saying huginn start/running. Finally, checked open files and processes (including logs and procfile) to confirm that huginn didn't even start. So as you said, it might be the problem with 15.04 release and it acts weird even after changing default init system. Thanks!

**Comment by dsander** [comment]
I see. Great the installation worked on 14.04, I think we will not support 15.04 since its not a LTS release which gives us some time to either pick a different init system then upstart or ensure upstart is properly installed on 16.04.

**Comment by virtadpt** [comment]
When last I heard, Upstart was being replaced with systemd.

**Comment by dsander** [comment]
@virtadpt Thats correct, really not sure yet how we should be dealing with the switch, but that's something to decide in a different issue after I got my PR merged :smile:

**Comment by reticentsmile** [comment]
Yep, that's right! 
Btw is the process of switching from upstart to systemd possible if I put in few hours?
I'll be interested in working on that if it's feasible... inputs will be appreciated!

**Comment by reticentsmile** [comment]
my bad, got it working with systemd by using foreman with export systemd! that was simple! :) 
Now, I'm almost successful porting it to gentoo!
Will move forward & close the issue!
