### ISSUE TITLE
Liquid "split" filter causes 500 error

### ISSUE THREAD

**Issue by HyShai** [cantino/huginn#881]
When saving (or Dry Run) a WebsiteAgent that uses an interpolated `url_from_event` and the Liquid `split` filter as well, I get a 500 error - "We're sorry, but something went wrong."

Example 1 (`link` is the interpolated property):
```
{
  "expected_update_period_in_days": "2",
  "url_from_event": "{% assign foo = link | split: '  ' %}{{ foo[0] }}",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": "body",
      "value": ".//text()"
    }
  }
}
```

Example 2 (`link` is the interpolated property):

```
{
  "expected_update_period_in_days": "2",
  "url_from_event": "{{link | split: ' ' | first}}",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": "#comic img",
      "value": "@src"
    }
  }
}
```

(I know that in this contrived case I can use the `replace` filter)

**Comment by HyShai** [comment]
@knu why is this an interpolation error?

**Comment by HyShai** [comment]
@knu also, after updating I still get a 500 error when trying to save.

Maybe this should be reopened.

This only happens when using the split filter - this works:
```
{
  "expected_update_period_in_days": "2",
  "url_from_event": "{% assign foo = link %}{{foo[0]}}",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": "body",
      "value": ".//text()"
    }
  }
}
```

**Comment by knu** [comment]
Because you didn't provide the error backtrace, I tried it myself and observed this:
```
NoMethodError - undefined method `split' for nil:NilClass:
  liquid (2.6.2) lib/liquid/standardfilters.rb:64:in `split'
  liquid (2.6.2) lib/liquid/strainer.rb:43:in `invoke'
  liquid (2.6.2) lib/liquid/context.rb:82:in `invoke'
  liquid (2.6.2) lib/liquid/variable.rb:50:in `block in render'
  liquid (2.6.2) lib/liquid/variable.rb:38:in `render'
  liquid (2.6.2) lib/liquid/block.rb:109:in `block in render_all'
  liquid (2.6.2) lib/liquid/block.rb:96:in `render_all'
  liquid (2.6.2) lib/liquid/block.rb:82:in `render'
  liquid (2.6.2) lib/liquid/template.rb:128:in `render'
  liquid (2.6.2) lib/liquid/template.rb:138:in `render!'
  app/concerns/liquid_interpolatable.rb:93:in `block in interpolate_string'
  app/concerns/liquid_interpolatable.rb:55:in `interpolate_with'
  app/concerns/liquid_interpolatable.rb:92:in `interpolate_string'
  app/concerns/liquid_interpolatable.rb:71:in `block in interpolate_options'
  app/concerns/liquid_interpolatable.rb:55:in `interpolate_with'
  app/concerns/liquid_interpolatable.rb:68:in `interpolate_options'
  app/concerns/liquid_interpolatable.rb:74:in `block (2 levels) in interpolate_options'
  app/concerns/liquid_interpolatable.rb:73:in `block in interpolate_options'
  app/concerns/liquid_interpolatable.rb:55:in `interpolate_with'
  app/concerns/liquid_interpolatable.rb:68:in `interpolate_options'
  app/concerns/liquid_interpolatable.rb:87:in `block in interpolated'
  app/concerns/liquid_interpolatable.rb:55:in `interpolate_with'
  app/concerns/liquid_interpolatable.rb:85:in `interpolated'
  app/models/agents/website_agent.rb:386:in `extraction_type'
  app/models/agents/website_agent.rb:177:in `validate_extract_options!'
  app/models/agents/website_agent.rb:140:in `validate_options'
...
```
If this is not what is happening on your site, please paste the log.

**Comment by knu** [comment]
Seems `interpolated` is also called via `#working?` and a problematic template affects the /agents page, which needs a fix.

**Comment by HyShai** [comment]
That's really weird - it's a valid filter according to the Liquid docs https://docs.shopify.com/themes/liquid-documentation/filters/string-filters#split
and it works when using a hardcoded string.
```
{
  "expected_update_period_in_days": "2",
  "url_from_event": "{% assign foo = 'bar' | split: ' ' %}{{foo[0]}}",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": "body",
      "value": ".//text()"
    }
  }
}
```

**Comment by HyShai** [comment]
(sorry about the logs - I'm running on heroku and I'm not sure how to access the logs....)

**Comment by knu** [comment]
Evaluating a valid Liquid template still can raise an error.  `"{% assign foo = link %}{{foo[0]}}"` is valid but will raise NoMethodError when `link` is evaluated to null.
In this case, Huginn tried to validate the options in which process the above template was interpolated without an incoming event, so it failed.

**Comment by cantino** [comment]
@HyShai do you get logs in the Agent logs section of the Agent?  Also, `heroku logs -n 200` should show you the last 200 lines of logs.

**Comment by HyShai** [comment]
Ah gotcha thanks so much! Seems to be fixed now!

**Comment by HyShai** [comment]
Actually - like @knu said - I can't access the /agents page that has that agent.

**Comment by HyShai** [comment]
Wow!! You guys work fast! I gotta get involved. Brush up on my Rails first...,

**Comment by knu** [comment]
@HyShai Just pushed a fix for that.  Please give it a try.

**Comment by HyShai** [comment]
@cantino in this case there were no logs in the Logs section of the agent. Possibly because this issue happened when I was saving the agent, not when running it?

**Comment by knu** [comment]
@cantino It is a problem that an exception (not <= Liquid::Error) Liquid's `render!()` may raise kills the whole recursive interpolation process in `interpolated()`.  It should probably offer a "safe mode" that leaves any failed template as it is, for use from validation, etc.  What do you think?

**Comment by HyShai** [comment]
@knu everything seems good now. Thanks so much!

**Comment by cantino** [comment]
@HyShai We'd love to have you involved!

**Comment by knu** [comment]
Glad to hear that!
