### ISSUE TITLE
Specs make actual network connections

### ISSUE THREAD

**Issue by cantino** [cantino/huginn#883]
@knu, I just noticed that when I run `describe "POST dry_run"` in `agents_controller_spec.rb`, I see real outbound network connections to xkcd.  WebMock doesn't seem to be able to prevent these.  I tried adding `FARADAY_HTTP_BACKEND=net_http` to `spec/env.test`, which is definitely being picked up, but didn't help.  Any ideas?  This may explain some of our slow test runs.

I noticed these connections by running `sudo tcpdump -i en0 -n -s 0 -w - | grep -a -o -E "Host\: .*|GET \/.*"` in another window.

**Comment by dsander** [comment]
@cantino You can debug this by disabling VCR. I had issues like this when writing specs for other agents. When VCR is enabled webmock does not seem to work properly. When VCR is disabled you should see the webmock exceptions and can stub out the requests.

**Comment by cantino** [comment]
Thanks @dsander.  Do you know if there is any way to isolate VCR to just the specs that want it?

**Comment by dsander** [comment]
I did a few quick google searches back then, but did not find anything, then I just disabled VCR, wrote my specs and enabled VCR again.
