### ISSUE TITLE
Enhancing the WebsiteAgent: Browser Emulation

### ISSUE THREAD

**Issue by irfancharania** [cantino/huginn#888]
(or a new agent) that will render the page to make for easier DOM parsing.

There are a number of sites like https://www.google.com that have ugly source, but a nicer looking DOM. We could look at using something like phantom.js to pull out the rendered document.

Could be implemented as an option in the existing WebsiteAgent.

**Comment by cantino** [comment]
Since we already have `therubyracer` for the JavaScriptAgent, maybe something like https://github.com/tmpvar/jsdom would be a good solution?

**Comment by knu** [comment]
The title of this issue is not very specific. You should at least include the word JavaScript in it.

**Comment by knu** [comment]
Or maybe "browser emulation".

I don't know much about jsdom, but capybara+capybara-webkit might also be a good option.

**Comment by knu** [comment]
There will be so much amount of work needed, but it could be worthwhile?

- Running a given piece of JavaScript code onload/document ready
- Providing JavaScript API to emit an event from within the code
- Storing and extracting cookies/localStrorage in Agent's memory
- Memory management (maybe the headless browser should be a separate process)

**Comment by irfancharania** [comment]
I know there's debate about future use of Heroku, but from quick googling, it looks like capybara-webkit won't run on Heroku whereas Phantomjs does. Something to consider...

Currently, I'm running a separate instance of PhantomJS on Heroku which returns a rendered page to the calling Huginn agent.

**Comment by cantino** [comment]
I wonder if there are any web services available that allow you to run a script of your choice in the context of a website of your choice, and get the output as an API result.

**Comment by knu** [comment]
[PhantomJs Cloud](https://phantomjscloud.com/) looks interesting.  It has a free plan that should be enough for personal use.

**Comment by cantino** [comment]
If someone gets this working well with Huginn it'd absolutely be worth documenting in the wiki.

**Comment by irfancharania** [comment]
I added an [entry in the wiki](https://github.com/cantino/huginn/wiki/Browser-Emulation-Using-PhantomJS-Cloud) for using PhantomJs Cloud with Website Agent.

Alternative to building an agent for it.

**Comment by dsander** [comment]
@irfancharania very cool, thanks you!

**Comment by irfancharania** [comment]
@dsander: The workflow actually works quite well. 

It would be nice to have the ability to set API key and request options in a dedicated agent, but I wasn't sure how a separate agent + interactions with other agents would work with all the options PhantomJs Cloud has: GET/POST, output Html/Json/PDF/Image, etc

**Comment by dsander** [comment]
@irfancharania You should be able to use credentials and the credential liquid tag to extract the API key from the agent options like this: `"https://PhantomJsCloud.com/api/browser/v2/{% credential credential-name %}/?request={{url}}"` A separate agent sounds interesting, if the PhantomJs Cloud are not dynamic using [FormConfigurable](https://github.com/cantino/huginn/blob/master/app/models/agents/hipchat_agent.rb#L43-L49) would be a nice option to configure the Agent.

**Comment by irfancharania** [comment]
@dsander  I forgot about credentials. Thanks for pointing that out. I'll update the wiki entry

**Comment by irfancharania** [comment]
@dsander I decided to try creating a [PhantomJs Cloud Agent with FormConfigurable](https://github.com/irfancharania/huginn/commit/31f6b95fb541e39d90961cfc96afff38f8fe4b1b). My knowledge of ruby/rails is very limited, so I need some help.

So far I've got it creating an event with the correct url.

What I can't figure out is:
1. How to present a list of credentials for user to select their API key from
2. Why [receive(incoming_events)](https://github.com/irfancharania/huginn/commit/31f6b95fb541e39d90961cfc96afff38f8fe4b1b#diff-aeab952d51cb488a1720ef9cd03a8e5eR68) doesn't seem to fire

**Comment by strugee** [comment]
FYI I just published a daemon written in Node that makes this dead-simple: https://github.com/strugee/fulldom-server

You can run fulldom on any old box and point WebsiteAgent at a fulldom URL instead of the actual URL, and fulldom will load up the page, run JS and then serve you the result. See the README for details.

**Comment by cantino** [comment]
Nice!

**Comment by cantino** [comment]
Mind putting a usage example on the wiki?

**Comment by strugee** [comment]
Sure. Though the README has it covered quite well.

**Comment by strugee** [comment]
@cantino just wrote this up on the wiki: https://github.com/cantino/huginn/wiki/Browser-Emulation-using-fulldom-server

It doesn't work yet due to #1735, though. Soon!

**Comment by irfancharania** [comment]
The [PhantomJs Cloud Agent](https://github.com/cantino/huginn/pull/1503) has been working well for me for quite some time. 
Think we could merge that in?

**Comment by cantino** [comment]
Yes! Sorry I lost track of this.

**Comment by cantino** [comment]
It got merged!
