### ISSUE TITLE
unfurl_links has no effect

### ISSUE THREAD

**Issue by sillygwailo** [cantino/huginn#892]
Any ideas on how I can pass just a straight URL string to the SlackAgent with the `unfurl_links` flag? It's described in https://api.slack.com/docs/unfurling but doesn't seem to unfurl links in Slack. I looked at the `slack-notifier` gem and thought maybe an `options` object with an `unfurl_links` property set to `true` might do the trick, but that doesn't work.

**Comment by sillygwailo** [comment]
I heard from the developer of `slack-notifier`: https://github.com/stevenosloan/slack-notifier/issues/32 (Possible, but apparently inconsistent.) I'll see what I can come up with in an agent's JSON.

**Comment by cantino** [comment]
Still want this @sillygwailo?

**Comment by sillygwailo** [comment]
Looks like this is merged already and it seems to be working. Closing this.
