### ISSUE TITLE
 EventFormattingAgent: Replace CR/LF

### ISSUE THREAD

**Issue by K1773R** [cantino/huginn#898]
I tried replacing \r\n in two ways.

```{{foo | replace '\r\n', ''}}```
```{{foo | replace '\\r\\n', ''}}```

unfortunately, none of those remove the CR nor the LF.

**Comment by knu** [comment]
While I'm not sure if Liquid supports escape characters in a string literal, there's an exact function that does what you want.  Try `{{foo | strip_newlines}}`.

**Comment by K1773R** [comment]
Works, thanks.

**Comment by cantino** [comment]
Thanks, I just added this to the wiki: https://github.com/cantino/huginn/wiki/Formatting-Events-using-Liquid
