### ISSUE TITLE
Novice questions

### ISSUE THREAD

**Issue by mightymt** [cantino/huginn#899]
I have recently set up Huginn on Heroku in an effort to find a replacement for Yahoo Pipes. So far I'm getting along quite well but there are a few things I can't figure out and I also couldn't find documented anywhere in the wiki.

## Credentials

On the *Credentials* page I can - as I understand it - assign/save custom variables of sorts. But how and where can I access them in my agents? Is there some Liquid code I can use?

## WebsiteAgent url_from_event
Can someone please explain to me how the `url_from_event` feature in the WebsiteAgent works. 

Here's what I'm trying to do:

1. Extract all the URLs from an OPML file (see below)
1. Parse each of those URLs (RSS feeds)
1. Create a new RSS feed containing the items of all the RSS feeds from the OPML file

The solution I came up with is to use two WebsiteAgents and one DataOutputAgent. So how can I access the URLs in the second WebsiteAgent? Thank you.

```json
{
  "expected_update_period_in_days": "2",
  "url": "http://www.flickr.com/recent_opml.gne?nsid=xxxxxxxxxxxx",
  "type": "xml",
  "mode": "on_change",
  "extract": {
    "url": {
      "xpath": "/opml/body/outline",
      "value": "@xmlUrl"
    },
    "title": {
      "css": "/opml/body/outline",
      "value": "@title"
    }
  }
}
```

**Comment by cantino** [comment]
Welcome @mightymt!

You can make `url_from_event` be a Liquid expression that will be evaluated in the context of the incoming Event before being used to fetch the resulting URL.  (Right @knu?)

Credentials can be accessed in Liquid with something like `{% credential USER_CREDENTIAL_NAME %}`.  See https://github.com/cantino/huginn/wiki/Formatting-Events-using-Liquid

**Comment by mightymt** [comment]
Hello Andrew,

Thanks for your help. 

So credentials are working now. I think I had seen that wiki page about the Liquid templating before but obviously hadn't read it properly.

Also *url_from_event* is working but apparently not in "Dry Run" which is why I was thinking that it didn't work at all. I just put `"url_from_event": "{{url}}"`, which isn't even really necessary if the incoming events have the `url` property.

Oh yes, one more thing. After also reading the discussions on some of the other issues, I have to say that I like the positive and helpful tone here. That really means a lot.

**Comment by cantino** [comment]
Glad it's working for you @mightymt, and thanks for the kind words :)
