### ISSUE TITLE
revise chef deployment docs to use new repositories for vagrantfile and chef-cookbook

### ISSUE THREAD

**Issue by elijah** [cantino/huginn#900]
The old instructions are here; 

https://github.com/cantino/huginn/wiki/Deploying-huginn-on-any-server-or-virtualbox-using-chef-solo-and-or-vagrant

In the NEW-CHEFFY-WORLD I am trying to build, folks ought to be able to just clone the vagrant project and type 'vagrant up' with minimal other effort.   

Once that's done, the stuff in the deployment/ directory can all go away.

**Comment by cantino** [comment]
Awesome!

**Comment by cantino** [comment]
How's it going @elijah?

**Comment by elijah** [comment]
So... sometime in the summer I had a chance to refactor and re-arrange the
chef bits that were in the huginn repo into two separate repositories -
cookbook-huginn and vagrant-huginn - so that I could deploy huginn 'my way'
- using Chef for all of the relevant bits.  I got it working, but then time
got precious (several big projects steamrollered me at once), and I haven't
been able to revisit huginn lately.

I am super pumped to see all the ticket shepherding that @cantino has done
in the last few days.  Awesome work!

I would at some point like to revisit the huginn bits I was working on and
make the testing and such a lot better - I may even be able to convince
someone to let me donate some of my (security focused) time in that
direction.  ;-)

For my own purposes - I'm hacking around a bit with openhab, and have the
notion that I'd like to have openhab, huginn, and several other things in
our home (both within and on the edges of my homelab...) communicating
better.  Just not there yet.  :)   I'm semi-waiting on my PINE64 boards to
arrive - that's where I'm intending to do my next deploy.

I imagine that the bits I was noodling on in the summer still probably work
- they were intended to get things rolling in a direction that was more
maintainable overall, and that I thought would be extensible.  I learned a
few things in the process of assembling them, for sure.  Maybe I'll go
'vagrant up' in a bit and see what happens.  :)

I have not ever gotten around to solidly clarifying documentation about how
to tangle with the bits I was working on - I think they're relatively
straightforward to clone and edit - people really just need the
vagrant-huginn cookbook and a few plugins installed - that should probably
get done.  :)

best,

--e

**Comment by cantino** [comment]
Sounds good. Let us know if we can help. :smile:

**Comment by cantino** [comment]
Is it okay if we close this issue? I think most people are using Docker or Capistrano now.

**Comment by dsander** [comment]
I am closing this for now, feel free to reopen if you plan to work on this further.

**Comment by elijah** [comment]
Sounds like a plan.

These days *I* might even choose to use docker for this... as my knowledge
of docker has grown, I've come to prefer managing fewer stateful instances
and even drive Docker containers with Chef, sometimes.  ;-)

--e

**Comment by alias1** [comment]
I know I abandoned my chef efforts back on the day, and these days docker has definitely filled that void for me ;3

Get Outlook for iOS




On Sat, Mar 11, 2017 at 2:59 AM +1100, "Elijah Wright" <notifications@github.com> wrote:










Sounds like a plan.



These days *I* might even choose to use docker for this... as my knowledge

of docker has grown, I've come to prefer managing fewer stateful instances

and even drive Docker containers with Chef, sometimes.  ;-)



--e





On Fri, Mar 10, 2017 at 9:53 AM, Dominik Sander <notifications@github.com>

wrote:

**Comment by dsander** [comment]
> These days *I* might even choose to use docker for this... as my knowledge of docker has grown, I've come to prefer managing fewer stateful instances and even drive Docker containers with Chef, sometimes. ;-)

If I need to I am using ansible, but I should really look into managing docker containers with it. Using chef/ansible for that sounds like a neat replacement for `cap deploy`. Currently I am sshing to the system and run `docker-compose pull && docker-compose up -d` 😄

**Comment by cantino** [comment]
I assume Kube is overkill for personal use, right

**Comment by alias1** [comment]
May well not be needed with docker swarm stuff these days too

Get Outlook for iOS




On Sat, Mar 11, 2017 at 11:03 AM +1100, "Andrew Cantino" <notifications@github.com> wrote:












I assume Kube is overkill for personal use, right
