### ISSUE TITLE
PostAgent propagate event?

### ISSUE THREAD

**Issue by chrisrickard** [cantino/huginn#902]
Is it possible for a PostAgent to propagate/continue an event?

In my example I want to make a POST request, but then propagate the result JSON as a new event 
Any ideas?

Cheers.

**Comment by cantino** [comment]
Hey @chrisrickard!

The PostAgent doesn't currently have an option to emit the results from the Post as a new Event.  Is that what you're suggesting?  If so, I think it's a good idea, and would be happy to help guide you through the process of adding it to Huginn.

**Comment by chrisrickard** [comment]
Hi @cantino , correct - I think it would be handy to emit the result, so as to chain the events.
Great - I can take a look myself, but what would your general suggestions be?

**Comment by cantino** [comment]
Great, I think it'd be a good improvement.

One thought, though: should this just be part of the WebsiteAgent?  That Agent can already receive a `url` (or `url_from_event`) and make a request, then merge the results back into the incoming Event.  Maybe the WebsiteAgent should be able to take a `method`, so that it can do non-GET requests?  What do you think @dsander & @knu?

If we were to add it to the PostAgent, which is also reasonable, and possibly simpler, I think you could just use the `Faraday::Response` that the `faraday.run_response` line in post_agent.rb should return to create a new Event.

**Comment by chrisrickard** [comment]
That seems like a good idea, depending on @dsander & @knu's thoughts I am happy to give that a shot

**Comment by flechaig** [comment]
This is something needed, to use Readability API for instance.

**Comment by dsander** [comment]
@cantino Not sure to be honest, wouldn't the WebsiteAgent also need to accept the POST parameters in a different from then the URL string?

My first feeling is that this feature should go into the PostAgent, but if the returned data needs to be transformed in some way the WebsiteAgent already had support for XPath and JSONPath.

**Comment by cantino** [comment]
That's true, and I see no harm in having it in the PostAgent.  @chrisrickard, you could go ahead and try to use the `Faraday::Response` that the `faraday.run_response` line in post_agent.rb should return to create a new Event.

**Comment by Ishfal** [comment]
Another use case for this is for interacting with the Google Flights QPX API.

https://developers.google.com/qpx-express/

**Comment by cantino** [comment]
@chrisrickard or @Ishfal, would either of you like to make this change?

**Comment by Ishfal** [comment]
Yes, I am happy to give it a shot. Unfortunately, I don't really know Ruby, so it may take me a while to produce something meriting a commit. But, I will give it a try, and if someone else beats me to the punch then we're all that much better off.

**Comment by cantino** [comment]
@Ishfal I'm happy to provide feedback, code review, and to answer any questions!

**Comment by Ishfal** [comment]
Here's my first whack at it... still lots to do, but I think it's moving in the right direction. Also, apologies in advance for sloppy code, etc. -- I'm an amateur!

https://github.com/cantino/huginn/pull/997

**Comment by cantino** [comment]
This should be working now.
