### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by gsportelli** [cantino/huginn#906]
I'm trying to install Huginn on my Raspberry Pi 2. I followed the [Novice setup guide](https://github.com/cantino/huginn/wiki/Novice-setup-guide), then the [Quick start](https://github.com/cantino/huginn#quick-start).

I had to solve a few minor issues, e.g., I had to install ruby-dev and libmysqlclient-dev, to pass the first "bundle" run.

But now I can't get through the step where I run "bundle exec rake db:migrate". The error I get is

    == 20140813110107 SetCharsetForMysql: migrating ===============================
    rake aborted!
    StandardError: An error has occurred, all later migrations canceled:

    undefined local variable or method `acts_as_mappable' for #<Class:0x391c4a0>/var/lib/gems/1.9.1/gems/activerecord-4.2.2/lib/active_record/dynamic_matchers.rb:26:in `method_missing'

Any suggestion on how to solve the error?

**Comment by dsander** [comment]
Hi @gsportelli, if your raspberry linux distribution is based on debian 6 or 7 would you mind trying the [new manual installation guide](https://github.com/dsander/huginn/blob/deployment-guide/doc/manual/installation.md)? The pull request is still in the works, but the installtion worked well for me on stock debian jessie and wheezy installations.

**Comment by cantino** [comment]
Closing since we haven't heard back.  Hope it's working for you!
