### ISSUE TITLE
Sorting RSS feed by something other than PubDate

### ISSUE THREAD

**Issue by christianmhunt** [cantino/huginn#907]
Hey,

I'm setting up Huginn to scrape an RSS feed coming out of Pinboard using Website Agent, reformat it using various Event Format Agents, and output another reformatted RSS feed using Data Output Agent. 

I'd like the output feed to sort RSS items according to an 'order' property that's derived from how they are tagged in pinboard, rather than sorting them by PubDate. 

The order property is a number 1-12, and Huginn is creating events that have **order:(some number)**.

Is there a way to sort the outgoing RSS feed by **order**? 

This is something I was doing with Yahoo Pipes, which had a 'sort' operator. Apologies if I've missed an obvious answer to this, or somewhere that this has been discussed before - this is my first time with Huginn, Git and anything more complex than Pipes, so the learning curve is quite steep...

Appreciate any guidance!

**Comment by cantino** [comment]
Hi @christianmhunt!

We don't really have any sorting agent right now.  Since every Agent tends to iteratively create events, it's hard to "retroactively" sort the feed.  Probably the best place would be inside of the Data Output Agent itself, which could take the last N events by creation order, then sort them by some alternative metric.  Do you know how to program, and if so, would you be interested in attempting this improvement?

**Comment by christianmhunt** [comment]
That makes sense as a solution. Unfortunately I don't program so it's
beyond me. Guess that'll have to change at some point in the future...

Thanks for getting back.

On Mon, Jul 13, 2015 at 5:35 PM, Andrew Cantino <notifications@github.com>
wrote:

> Hi @christianmhunt <https://github.com/christianmhunt>!
>
> We don't really have any sorting agent right now. Since every Agent tends
> to iteratively create events, it's hard to "retroactively" sort the feed.
> Probably the best place would be inside of the Data Output Agent itself,
> which could take the last N events by creation order, then sort them by
> some alternative metric. Do you know how to program, and if so, would you
> be interested in attempting this improvement?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cantino/huginn/issues/907#issuecomment-121080910>.
>



-- 
Christian Hunt

US: +1 (612) 466 0051
skype: + 44 (0) 20 8638 0727
skype: chr1stianhunt
UK mobile: +44 (0) 7754 196 894

**Comment by cantino** [comment]
Hey @christianmhunt, I gave this a go.  Mind trying out #918?

**Comment by christianmhunt** [comment]
Hey @cantino, this appears to work fine and meets the functionality. Thanks very much for implementing - you've inspired me to give learning ruby a go!

**Comment by cantino** [comment]
Glad to hear it!  Good to have you involved :)

We'll merge #918 when @knu and I have settled on a format.

**Comment by knu** [comment]
@christianmhunt While the `events_order` option has been added to RssAgent, the "order" property might not be used as sort key if RssAgent did not output it as part of each event.  In that case, please file an issue to demand an enhancement to RssAgent.

**Comment by knu** [comment]
Another option is to use WebsiteAgent and scrape the feed as XML document.

**Comment by marycanady** [comment]
Hi--what is the best option to get the RSS feed items sorted by the publish date on the website, not the date they were published by Huginn?

**Comment by cantino** [comment]
@marycanady, `events_order` has been added to the RssAgent, so I think you could set it to something like `[["{{date}}", "time"]]`.  Do you see the documentation for `events_order` in your sidebar?

**Comment by marycanady** [comment]
@cantino thanks, I do see the comments on the right and I've tried a few options. I get confused regarding which field is the date the article was published, and which field is the date that Huginn published the event, and which of these fields are passed between the agents. Also, I'm unsure whether sorting at the RSS Agent level is sufficient. 
For example, if an RSS feed has its last post in 2014, and I sort with RSS Agent, then aggregate this with a feed that has 2015 items, the feed sorting will be out of order, so I'd rather do it at the Final Data Output level. This is how I do it in Yahoo Pipes and it works well.
You have one of my scenarios which has my current sorting in the Final Data Output level, this is one that's not working (I used PubDate to sort), if you could look at it and let me know how I should change it, that would be great, thanks!

**Comment by cantino** [comment]
On the scenario you sent me, `"events_order": [["{{date_published}}", "time", true]]` seems to sort correctly.  I had to add `date_published` to the output to convince myself, but it looks right.
