### ISSUE TITLE
Debug twitter 401 Authorization Required

### ISSUE THREAD

**Issue by jonaslejon** [cantino/huginn#908]
I'm seeing: 

OAuth::Unauthorized at /auth/twitter
401 Authorization Required

When clicking authenticate with Twitter from the Services menu. Yes, i've set the TWITTER OAUTH in .env:

TWITTER_OAUTH_KEY=a7na6kx4t71SOMETHING
TWITTER_OAUTH_SECRET=aYErpdpGcznFYcbiQD0MDtNrkyASOMETHING
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=

Is it possible to do some more debugging?

**Comment by dsander** [comment]
Hi @jonaslejon,

did you configure a callback URL in the [Twitter application settings](https://apps.twitter.com)? When you are running huginn locally on port 3000 it should look like this: ` http://127.0.0.1:3000/auth/twitter/callback`

**Comment by jonaslejon** [comment]
@dsander I'm running Huginn on a public URL with Nginx as a proxy_pass in front. And the callback URL has been configured at Twitter.

When visiting the callback URL directly with my browser i'm getting the following error:

RuntimeError at /auth/twitter/callback
Could not find a valid mapping for path "/auth/twitter/callback"

**Comment by dsander** [comment]
The message you are getting is normal, because the callback URL expects some data from twitter.

Can you try to remove `TWITTER_CONSUMER_KEY` and `TWITTER_CONSUMER_SECRET` from your `.env` file and double check the key and secret do not contain trailing spaces?

**Comment by jonaslejon** [comment]
Thanks for your input. I've solved it by regenerating the Consumer Key and Secret and then typed them again into .env
