### ISSUE TITLE
External MYSQL Db

### ISSUE THREAD

**Issue by nothing-fr** [cantino/huginn#912]
Is it possible to use an external mysql database ?

I've set in DOCKER env :

`HUGGIN_DATABASE_PORT=3306`
`HUGINN_DATABASE_ADAPTER=mysql2`
`HUGINN_DATABASE_HOST=10.0.1.61`
`HUGINN_DATABASE_PASSWORD=mypassword`
`HUGINN_DATABASE_USER=huggin`
`HUGINN_DATABASE_NAME=huggin`

and it's not working : 

```
foreman stderr | Mysql2::Error: Access denied for user 'root'@'172.17.0.6' (using password: YES)
stdout
```

**Comment by dsander** [comment]
@ianblenke is working on a pull request to improve the docker linking documentation, maybe #905 can help you with your issue.

**Comment by ianblenke** [comment]
The problem is that the README is wrong, it should be:

    HUGINN_DATABASE_USERNAME=huginn

Nothing uses `HUGINN_DATABASE_USER`, so that is why you are seeing the default `DATABASE_USER=root`

**Comment by ianblenke** [comment]
And, yes, #905 fixes that README documentation.
