### ISSUE TITLE
Daemonising on debian?

### ISSUE THREAD

**Issue by dugite-code** [cantino/huginn#914]
I'm new to ruby (huginn is my first reason to even have it installed on my system) and am unfamiliar with how to run huginn in the background.

Unfortunately the only mention I found in the wiki involved upstart, and that seamed like an unnecessarily complicated way to get huginn running in the background.

**Comment by cantino** [comment]
Hey @dugite-code, welcome!

Are you going to run this on a remote computer (like a VPS), or locally?

**Comment by dugite-code** [comment]
Locally, on my home server currently installed in a virtual Debian environment witch I setup and control with [webvirtmgr](https://github.com/retspen/webvirtmgr).

**Comment by cantino** [comment]
`foreman` can [export](http://ddollar.github.io/foreman/#EXPORT-FORMATS) for inittab and systemd too.  Also, @dsander has a guide underway: https://github.com/cantino/huginn/pull/872

**Comment by dugite-code** [comment]
Thank you for the help

**Comment by dugite-code** [comment]
Unfortunately the export to systemd in foreman doesn't appear to work straight off the bat and I haven't found a way to make it work or any guides that don't focus on upstart.

I looked at the installation guide linked but installing upstart stopped my system booting up altogether so I had to reload from a snapshot.

**Comment by cantino** [comment]
If it's easy, you might consider using Docker.  There's also #872.

**Comment by dugite-code** [comment]
hummm... I'm still not seeing anything other than using upstart in #872 and for some reason that frags my system.

In any case I guess I'll have to try to get docker working again

**Comment by dsander** [comment]
@dugite-code I also tried to use systemd on debian for #872 with no luck, the export worked but the services did not start. Which debian version are you using? I tested the upstart installation with debian 6 and 7 images on vagrant and digital ocean and had no problems.

**Comment by dugite-code** [comment]
I'm using 7 wheezy. It's an install with a whole bunch of tinkering done so I'm not surprised something broke badly. Defiantly looks like docker is the best way to go for me
