### ISSUE TITLE
Extracting Media:thumbnail tag from feed label:help-wanted 

### ISSUE THREAD

**Issue by whatBlackshirt** [cantino/huginn#916]
How would I go about extracting the information from the media:thumbnail tag on a feed?

**Comment by cantino** [comment]
Hey @whatBlackshirt!

For now, the WebsiteAgent is probably your best bet.  It can parse XML.

**Comment by whatBlackshirt** [comment]
Okay, thanks for the answer! 
I'm very new to this so how would an example look to do just that? I have tried my self with not much success

**Comment by cantino** [comment]
See https://github.com/cantino/huginn/wiki/Agent-configuration-examples

Could you provide an example of the XML you're trying to parse?

Something like this might work..., but I haven't tested it since I don't have an example.

```
{
  "url": "url",
  "mode": "on_change",
  "type": "xml",
  "expected_update_period_in_days": "10",
  "extract": {
    "url": {
      "xpath": "//item/media:thumbnail",
      "value": "@url"
    }
  }
}
```

**Comment by whatBlackshirt** [comment]
I tried it my self with http://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular+in%3Adigitalart%2Fdrawings+frogs
but it just gives me an error - Error when fetching url: Undefined namespace prefix: //item/media:thumbnail

**Comment by cantino** [comment]
This seems to work for me once I include `use_namespaces`:

```json
{
  "expected_update_period_in_days": "2",
  "url": "http://backend.deviantart.com/rss.xml?type=deviation&q=boost%3Apopular+in%3Adigitalart%2Fdrawings+frogs",
  "type": "xml",
  "use_namespaces": "true",
  "mode": "on_change",
  "extract": {
    "url": {
      "xpath": "//item/media:thumbnail",
      "value": "@url"
    }
  }
}
```

**Comment by AviOmicron** [comment]
Hi there, I am using DataOutputAgent and have the "same" issue. Not sure if I need to make a new thread.

```
 "item": {
      "title": "{{title}}",
      "description": "{{description}}",
      "link": "{{url}}",
      "media:content": {
        "_attributes": {
          "url": "www.google.com"
        }
```

returns an error. If I replace media:content by media it works.

**Comment by cantino** [comment]
Hi @AviOmicron, I think this is a different issue.  We may need to add a `_namespace` option for the data output agent.  What error do you get?  A new thread would be appropriate for this.

**Comment by cantino** [comment]
@whatBlackshirt, did my solution work for you?

**Comment by AviOmicron** [comment]
This page contains the following errors:

error on line 16 at column 21: Namespace prefix media on content is not defined
Below is a rendering of the page up to the first error.

**Comment by cantino** [comment]
What system displayed this error to you?  Your browser?  A screenshot would be helpful, and ideally in a new GitHub issue.

**Comment by AviOmicron** [comment]
Done, created new issue here: https://github.com/cantino/huginn/issues/960

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further!
