### ISSUE TITLE
Precise sheduling options

### ISSUE THREAD

**Issue by K1773R** [cantino/huginn#922]
I have an agent which i'd like to run Monday - Friday 07:00. Now with crontab that would be simple. Unfortunately the shedule options for huginn don't allow for such scenarios.

**Comment by knu** [comment]
Try SchedulerAgent.

**Comment by K1773R** [comment]
i dont have this agent, gonna pull later and reopen if its still an issue.

**Comment by K1773R** [comment]
I still dont have this agent after pulling, hence i'll reopen it.

**Comment by K1773R** [comment]
The SchedulingAgent is precisely what i want. cron with seconds is awesome too (tough, dont need it now). Thanks.

**Comment by cantino** [comment]
Great! :)
