### ISSUE TITLE
E-Mail dosnt work anymore

### ISSUE THREAD

**Issue by K1773R** [cantino/huginn#924]
Ater updating to current git, huginn fails to send emails. I always get connection refused. If i connect with nc to the specified port/ip in .env, it works.
Unfortunately, the backtrace dosnt show any values, how to tackle this?

**Comment by K1773R** [comment]
I've dumped the network traffic. It tries to connect to ::1, then 127.0.0.1 port 25. In my config i have another ip and port 587 (ie, .env).

**Comment by K1773R** [comment]
after ``` bundle update``` it worked again.

**Comment by cantino** [comment]
Good!
