### ISSUE TITLE
Production with FreeBSD

### ISSUE THREAD

**Issue by Free16t** [cantino/huginn#926]
Hi, 

I'm trying to launch Huginn in production mode, however, I'm using FreeBSD and Upstart isn't existing in this OS. 
Is there an other way to launch it as production or running without the shell?

Thanks

**Comment by cantino** [comment]
Welcome @Free16t!  Yes, `foreman` can [export](http://ddollar.github.io/foreman/#EXPORT-FORMATS) to many different process management systems beyond upstart.

**Comment by knu** [comment]
I'm running Huginn on my FreeBSD box using daemontools.  There seems to be an exporter plugin for Foreman to export a "service" directory, but I just wrote hand-crafted scripts as follows:

[/var/service/huginn-worker]
```sh
#!/bin/sh

set -e

export PATH=/path/to/ruby/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

export RAILS_ENV=production
export DISABLE_SPRING=1

cd /path/to/huginn

ulimit -n 1024

exec 2>&1
exec setuidgid user_for_huginn \
    bundle exec script/delayed_job run
```

[/var/service/huginn-scheduler/run]
Replace the last line of the above script with: `bundle exec rails runner bin/schedule.rb`

[/var/service/huginn-twitter_stream/run]
Replace the last line of the above script with: `bundle exec runner bin/twitter_stream.rb`

You can manage the daemon processes using svc(1).  `svc -t /var/service/huginn-*` to restart all of them, for example.

**Comment by cantino** [comment]
Worth adding to the wiki?

**Comment by Free16t** [comment]
Thanks, I will try (currently, I'm using screen ... it's not the best we can do)

**Comment by virtadpt** [comment]
Screen's not so bad, @Free16t, I use it for Huginn, too (but I run a bunch of stuff in parallel with Huginn through it, too).

**Comment by Free16t** [comment]
Ok thanks for your feedback @virtadpt
