### ISSUE TITLE
Problem in installation

### ISSUE THREAD

**Issue by Scinawa** [cantino/huginn#929]
I run (as root) the following "bundle exec foreman start", and I get this.

07:50:43 web.1  | started with pid 9878
07:50:43 jobs.1 | started with pid 9880
07:50:49 jobs.1 | Warning: You're using Rubygems 1.8.23 with Spring. Upgrade to at least Rubygems 2.1.0 and run `gem pristine --all` for better startup performance.
07:50:49 web.1  | Warning: You're using Rubygems 1.8.23 with Spring. Upgrade to at least Rubygems 2.1.0 and run `gem pristine --all` for better startup performance.
07:51:53 jobs.1 | ## Set TWITTER_OAUTH_KEY and TWITTER_OAUTH_SECRET in your environment to use Twitter Agents.
07:51:53 jobs.1 | Twitter stream stopped ...
07:52:02 web.1  | [2015-07-21 07:52:02] INFO  WEBrick 1.3.1
07:52:02 web.1  | [2015-07-21 07:52:02] INFO  ruby 1.9.3 (2013-11-22) [x86_64-linux]
07:52:02 web.1  | [2015-07-21 07:52:02] INFO  WEBrick::HTTPServer#start: pid=9882 port=3000
07:52:53 jobs.1 | Queuing event propagation
07:52:53 jobs.1 | Queuing schedule for every_1m
07:53:13 jobs.1 | exited with code 0
07:53:13 system | sending SIGTERM to all processes
07:53:13 web.1  | terminated by SIGTERM

I do not press ctrl+c or anything else. It just close on it's own. DOMAIN on .env it's an IP on one of my interfaces. the port it's 3001 but it seems to be ignored. 
Any hints? Tnx

**Comment by dsander** [comment]
Hi @Scinawa,

rubygems 1.8.23 looks quite old, which ruby version are you running? We only test huginn on ruby 2+, you can use [rbenv](https://github.com/sstephenson/rbenv) or [rvm](http://rvm.io) to install a current ruby version.

If you just want to try out huginn [the docker image](https://registry.hub.docker.com/u/cantino/huginn/) is a great option.

**Comment by cantino** [comment]
Closing since we haven't heard back.  Hope it's working for you!
