### ISSUE TITLE
liquid date filter validate error 

### ISSUE THREAD

**Issue by HyShai** [cantino/huginn#933]
If I try to save an agent (DataOutputAgent) with the `date` filter that comes after some string manipulation I get a validation error.

If I do this:
```
{
  "expected_receive_period_in_days": 2,
  "template": {
    "title": "hello",
    "item": {
      "title": "{{title | remove: 'foo' |  date: '%D' }}",
      "link": "{{url}}"
    }
  },
  "secrets": [
    "secret"
  ]
}
```

I get an error `Options has an error with Liquid templating: Liquid error: no time information in ""`

but when I do this:
```
{
  "expected_receive_period_in_days": 2,
  "template": {
    "title": "hello",
    "item": {
      "title": "{{title |  date: '%D' }}",
      "link": "{{url}}"
    }
  },
  "secrets": [
    "secret"
  ]
}
```
it saves without error.

Seems like `date` is receiving an empty string only when it goes through a string manipulation filter first. Which is weird because when saving an agent that receives events the interpolation validation would naturally fail.

**Comment by knu** [comment]
This looks like a bug in Liquid.  It'll submit a PR.

**Comment by HyShai** [comment]
Thanks! 
(Was this fixed already in pull request Shopify/liquid#555 ?)

**Comment by HyShai** [comment]
I wonder if this was a bug introduced in Liquid v3 - it had been working as of ~2-3 weeks ago....

**Comment by HyShai** [comment]
Thanks so much!!
