### ISSUE TITLE
PostAgent and Liquid Templating

### ISSUE THREAD

**Issue by unnikked** [cantino/huginn#934]
I tried to search but I was unfortunate. 

I'm trying to `POST` a payload request to this [project](https://github.com/Reportr/dashboard). 

In order to use the _Time Chart_ visualization I need to post the actual value as an integer, but using the __PostAgent__ I cannot make a value retrieved via liquid templating into integer. 

```json
{
  "post_url": "https://reportr.mydomain.com/api/events",
  "expected_receive_period_in_days": "1",
  "content_type": "json",
  "method": "post",
  "payload": {
    "type": "reddit.username.comment_karma",
    "properties": {
      "value": "{{ comment_karma }}"
    }
  },
  "headers": {
    "Content-Type": "application/json"
  },
  "basic_auth": "username:password",
  "disable_ssl_verification": "true"
}
```

The `POST` call is done correctly but the `value` field is a _string_ and i need it as _int_.

If I try to delete manually `"..."`

```json
...
"payload": {
    "type": "reddit.username.comment_karma",
    "properties": {
      "value": {{ comment_karma }}
    }
  },
...
```

The editor will automatically put it again. It's intended or I'm missing something? I tried everything to my knowledge but I don't know what to do. 

Sorry for the silly question.

**Comment by cantino** [comment]
Hi @unnikked.  I just want to make sure I'm understanding you.  Is it correct that the POST needs to have `value` as a JSON integer, not as a JSON string?

**Comment by unnikked** [comment]
Yes, I'm sure. I've made some tests using Postman and everything worked when I sent the value as a JSON Integer.

**Comment by cantino** [comment]
That makes sense @unnikked.  If you edit the raw JSON by clicking "toggle view" and make it a literal integer instead of an integer as a string, does that help?

**Comment by unnikked** [comment]
As I wrote in the original submission @cantino doing that does not help

The editor quote `{{ comment_karma }}` automatically, making it a string

**Comment by cantino** [comment]
I'm sorry @unnikked, of course it wouldn't because you're using a Liquid tag.  @knu, is there any way for a Liquid filter to output a number instead of a string?

**Comment by cantino** [comment]
I was hoping that `{{ price | plus: 15 }}` would give a number, but it appears to still be a string in the JSON result, so I'm not sure if we have a way to do this right now.

**Comment by cantino** [comment]
Maybe a liquid filter that tags the output for conversion, then we coerce it from string to integer? @knu or @dsander, have you seen anything like this?

**Comment by cantino** [comment]
Can I close this @unnikked?

**Comment by unnikked** [comment]
Deeply sorry to reply late. I'm not able to reproduce again this issue at the moment. I guess you can close for now.

**Comment by cantino** [comment]
Thanks!

**Comment by cantino** [comment]
Please re-open if you'd like to discuss further.
