### ISSUE TITLE
WebhookAgent question... GET/POST?

### ISSUE THREAD

**Issue by darrencauthon** [cantino/huginn#935]
![postonly](https://cloud.githubusercontent.com/assets/148768/8881806/34fd91de-3208-11e5-8dfa-f925dfa0c993.png)

Just curious... is there a reason why GET requests to the WebhookAgent endpoints are not allowed?

If there's not a strong opinion against them, what if they were opened up via configuration?

**Comment by cantino** [comment]
Hey @darrencauthon, that may be out-of-date.  We should be routing all verbs to the WebRequestsController which should then be calling `trigger_web_request` on the specified Agent with the params, verb, and format.

Where did you see that?

**Comment by darrencauthon** [comment]
I saw it here:  https://github.com/cantino/huginn/blob/285407caeaab8b489c3f0f67f692ee58d2d9bc02/app/models/agents/webhook_agent.rb#L42

**Comment by cantino** [comment]
Oh, I see.  We limit in the webhook agent itself.  I agree with you, there's probably no reason to have that limit.  Maybe it should be an option, so the user can list allowed verbs?

**Comment by darrencauthon** [comment]
That sounds fine. Just wanted to check before I pop a PR. 



—

**Comment by cantino** [comment]
Go for it!

**Comment by darrencauthon** [comment]
:+1:

**Comment by darrencauthon** [comment]
My question was answered, so there's no need to hold this open until I get a PR released.
