### ISSUE TITLE
How to change {{url}} before fetching url using WebsiteAgent?

### ISSUE THREAD

**Issue by waldens** [cantino/huginn#936]
If the orginal url is `http://www.ftchinese.com/story/001063181`, here we need to fetch url `http://www.ftchinese.com/story/001063181?full=y`, but using EventFormattingAgent is not working. Really need help, thanks!

Type: Rss Agent 
```
{
  "expected_update_period_in_days": "14",
  "clean": "false",
  "url": "http://www.ftchinese.com/rss/hotstoryby7day"
}
```

Type: Event Formatting Agent 
```
{
  "instructions": {
    "url_full": "{{url}}?full=y"
  },
  "mode": "merge"
}
```

Type: Website Agent 
```
{
  "expected_update_period_in_days": "14",
  "url": "{{url_full}}",
  "type": "html",
  "mode": "merge",
  "extract": {
    "description": {
      "css": "#bodytext",
      "value": "."
    }
  }
}
```

log said, `Ignoring a non-HTTP url: "\\?full=y"`

**Comment by irfancharania** [comment]
use `url_from_event` in the website agent instead of `url`, and you can do the templating

"url_from_event": "{{url}}?full=y"
