### ISSUE TITLE
Unique entry in the dataoutput

### ISSUE THREAD

**Issue by pierrehegr** [cantino/huginn#940]
Hello,
I'm using Huginn currently with rssagent and triggers. For some triggers I have multiples sources. Would it be possible to filter the output in order to have just unique entry (for instance it's just 1 article with the same title or 1 article with an URL) ? 

Thanks a lot

**Comment by mikalauskas** [comment]
use DeDuplicationAgent for this.
example: rssagent -> triggeragent -> deduplicationagent -> dataoutputagent

**Comment by pierrehegr** [comment]
Yes, now it's seem obvious to me, sorry for the question! And thanks for the answer
