### ISSUE TITLE
huge log file

### ISSUE THREAD

**Issue by pierrehegr** [cantino/huginn#941]
hello, 

On my current huginn installation, the log file (development.log) is very huge (5,6G) is there a way to control is weight? 

Thanks a lot

**Comment by K1773R** [comment]
If you dont want it, just symlink it to /dev/null
Otherwise, setup logrotate for it

**Comment by cantino** [comment]
Hey @pierrehegr, @K1773R is right.  Both logrotate and a symlink should work.  Maybe it'd be worth mentioning this on the wiki or including in @dsander's guide?

**Comment by pierrehegr** [comment]
Ok, I wasn't sure if it was normal or not. So I will send it to /dev/null 

Thanks

**Comment by dsander** [comment]
@pierrehegr It's already in the [guide](https://github.com/dsander/huginn/blob/deployment-guide/doc/manual/installation.md#setup-logrotate), you might need to change paths in the [logrotate config](https://github.com/dsander/huginn/blob/deployment-guide/lib/support/logrotate/huginn)

**Comment by cantino** [comment]
Awesome @dsander!
