### ISSUE TITLE
Dropping support for Ruby 1.9

### ISSUE THREAD

**Issue by knu** [cantino/huginn#944]
Ruby 1.9 is [EOL](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/) and we haven't been testing Huginn with Ruby 1.9 on Travis-CI for a long time.
There are many good reasons to require Ruby 2.0+, namely keyword arguments and Module#prepend, for both of which we are relying on ugly emulation, parsing options hash by hand and using lib/prepend.rb.

Is there any reason not to?  Do we have any supported setup still fixed at Ruby 1.9?

/cc @cantino @dsander

**Comment by cantino** [comment]
I'd be supportive of require 2+.  Do you think we should add a deprecation
warning or just do it?

**Comment by dsander** [comment]
To be honest I thought we dropped support when we stopped testing 1.9 :smile: 

The [chef receipe](https://github.com/cantino/huginn/blob/master/deployment/site-cookbooks/huginn_production/recipes/default.rb) still uses ruby 1.9, maybe we should remove it and point to @elijah respository?

**Comment by virtadpt** [comment]
+1 to dropping support for Ruby v1.9.

**Comment by cantino** [comment]
Go for it @knu :)

**Comment by knu** [comment]
OK, thanks for your feedback, guys!

@ianblenke I've found our Docker setup script still has ruby 1.9 in it.  Is it possible you could upgrade it any time soon?
