### ISSUE TITLE
Issue with the feed normalizer

### ISSUE THREAD

**Issue by pierrehegr** [cantino/huginn#946]
Hello,

When I launch Huginn, I have this error message: `gems/ruby-2.1.6/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:153: warning: regexp match /.../n against to UTF-8 string` and I have some issue with agents, do you know why?

Thanks

**Comment by cantino** [comment]
Hi @pierrehegr.  How are you running Huginn?  What Agent configuration is giving you the error?

**Comment by pierrehegr** [comment]
For this try, I launch it by running the cmd `bundle exec foreman start` (on ubuntu 14.04, huginn and bundle up to date, `ruby -v`: `ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]` ). It's the rssagent that gave me this error.

**Comment by cantino** [comment]
Was this error during startup, or after a particular RSSAgent ran?

In either case, it's a warning, not an error, so it may be fine.

**Comment by pierrehegr** [comment]
In all the feed. 
Yes, however, I don't know why, Huginn try but jobs failed as the number of attempts is higher than 5. At the end, the agent stop.

**Comment by cantino** [comment]
Would you mind updating to the newest version of Huginn and seeing if you still have this issue?

Are other Agents working for you?

**Comment by pierrehegr** [comment]
I just update using `git remote update` then `git merge origin/master` and the bundle (using `bundle update`) 
however I still have this error. 
Others than RSS yes, they work

**Comment by cantino** [comment]
Perhaps it's an issue with the particular feed you're trying to access.  What is the URL?

**Comment by pierrehegr** [comment]
It's almost all the URL that I put on the agent (around hundred URL)

**Comment by cantino** [comment]
Could I see an example?

**Comment by pierrehegr** [comment]
Sure, 
here is my agent:
>{
  "expected_update_period_in_days": "5",
  "clean": "true",
  "url": [
    "http://feeds.arstechnica.com/arstechnica/index/",
    "http://feeds.boingboing.net/boingboing/iBag",
    "http://www.scoop.it/t/influence-operations/rss.xml",
    "http://feeds.feedburner.com/Infoguerre?format=xml",
    "http://news.webplanete.net/rss.php?fid=0",
    "http://www.scoop.it/t/startupfr/rss.xml",
    "http://www.techmeme.com/feed.xml",
    "http://feeds2.feedburner.com/secrets-2-moteurs",
    "http://feeds.gawker.com/lifehacker/full",
    "http://www.linformaticien.com/DesktopModules/DnnForge%20-%20NewsArticles/Rss.aspx?TabID=58&ModuleID=2214&MaxCount=25&sortBy=StartDate&sortDirection=DESC",
    "http://www.israelvalley.com/feed/rss",
    "http://feeds2.feedburner.com/LeJournalduGeek",
    "http://feeds.wired.com/wired/index",
    "http://maddyness.com/feed/",
    "http://feeds.feedburner.com/TechCrunch",
    "http://startupweekend.org/feed/"
  ]
}

and the log file: 
>Failed to fetch http://startupweekend.org/feed/ with message 'undefined method `clean!' for nil:NilClass': ["/opt/huginn/app/models/agents/rss_agent.rb:101:in `check_url'", "/opt/huginn/app/models/... 	<1m ago 	
Failed to fetch http://feeds.feedburner.com/TechCrunch with message 'undefined method `clean!' for nil:NilClass': ["/opt/huginn/app/models/agents/rss_agent.rb:101:in `check_url'", "/opt/huginn/app/... 	<1m ago 	
Failed to fetch http://maddyness.com/feed/ with message 'undefined method `clean!' for nil:NilClass': ["/opt/huginn/app/models/agents/rss_agent.rb:101:in `check_url'", "/opt/huginn/app/models/agent... 	<1m ago 	
Failed to fetch http://feeds.wired.com/wired/index with message 'undefined method `clean!' for nil:NilClass': ["/opt/huginn/app/models/agents/rss_agent.rb:101:in `check_url'", "/opt/huginn/app/mode... 	<1m ago 	
Failed to fetch http://feeds2.feedburner.com/LeJournalduGeek with message 'undefined method `clean!' for nil:NilClass': ["/opt/huginn/app/models/agents/rss_agent.rb:101:in `check_url'", "/opt/hugin... 	<1m ago 	
Failed to fetch http://www.israelvalley.com/feed/rss with message 'undefined method `clean!' for nil:NilClass': ["/opt/huginn/app/models/agents/rss_agent.rb:101:in `check_url'", "/opt/huginn/app/mo... 	<1m ago 	
Failed to fetch http://www.linformaticien.com/DesktopModules/DnnForge%20-%20NewsArticles/Rss.aspx?TabID=58&ModuleID=2214&MaxCount=25&sortBy=StartDate&sortDirection=DESC with message 'undefined meth... 	<1m ago 	
Failed to fetch http://feeds.gawker.com/lifehacker/full with message 'undefined method `clean!' for nil:NilClass': ["/opt/huginn/app/models/agents/rss_agent.rb:101:in `check_url'", "/opt/huginn/app... 	<1m ago 	
Failed to fetch http://feeds2.feedburner.com/secrets-2-moteurs with message 'undefined method `clean!' for nil:NilClass': ["/opt/huginn/app/models/agents/rss_agent.rb:101:in `check_url'", "/opt/hug... 	<1m ago 	
Failed to fetch http://www.techmeme.com/feed.xml with message 'undefined method `clean!' for nil:NilClass': ["/opt/huginn/app/models/agents/rss_agent.rb:101:in `check_url'", "/opt/huginn/app/models... 	<1m ago 	
Failed to fetch http://www.scoop.it/t/startupfr/rss.xml with message 'undefined method `clean!' for nil:NilClass': ["/opt/huginn/app/models/agents/rss_agent.rb:101:in `check_url'", "/opt/huginn/app... 	<1m ago 	
Failed to fetch http://news.webplanete.net/rss.php?fid=0 with message 'undefined method `clean!' for nil:NilClass': ["/opt/huginn/app/models/agents/rss_agent.rb:101:in `check_url'", "/opt/huginn/ap... 	<1m ago 	
Failed to fetch http://feeds.feedburner.com/Infoguerre?format=xml with message 'undefined method `clean!' for nil:NilClass': ["/opt/huginn/app/models/agents/rss_agent.rb:101:in `check_url'", "/opt/... 	<1m ago 	
Failed to fetch http://www.scoop.it/t/influence-operations/rss.xml with message 'undefined method `clean!' for nil:NilClass': ["/opt/huginn/app/models/agents/rss_agent.rb:101:in `check_url'", "/opt... 	<1m ago 	
Failed to fetch http://feeds.boingboing.net/boingboing/iBag with message 'undefined method `clean!' for nil:NilClass': ["/opt/huginn/app/models/agents/rss_agent.rb:101:in `check_url'", "/opt/huginn... 	<1m ago 	
Failed to fetch http://feeds.arstechnica.com/arstechnica/index/ with message 'undefined method `clean!' for nil:NilClass': ["/opt/huginn/app/models/agents/rss_agent.rb:101:in `check_url'", "/opt/hu... 	<1m ago

**Comment by cantino** [comment]
So, I just ran your RssAgent locally and it worked for me.  Are you sure you're on the master version of Huginn?  Any change `spring` is running?  (If so, stop it with `spring stop`.)

**Comment by pierrehegr** [comment]
stopping `spring` helps to improve. yes, I'm using the master of Huginn. Some feeds are ok however because of the failed one, agents are still stopping themselves.

**Comment by cantino** [comment]
You're saying that when one fails, they all fail?

**Comment by pierrehegr** [comment]
Well when one feed fails, the Agent failed (because the agent try again and the number of attempts reach the max)

**Comment by cantino** [comment]
If you're on the newest Huginn, those log messages shouldn't actually cause DJ to retry anything.  When you look at the delayed_job interface and see attempts reaching the max, what errors do they have there?

**Comment by pierrehegr** [comment]
Well, I find the answer ... I'm really sorry for disturbing you because in fact my current installation is behind a proxy and the proxy didn't allow huginn to go on the internet all the time ... that's why I had this error (which seem obvious to me now)

**Comment by cantino** [comment]
Glad it's working for you!
