### ISSUE TITLE
issue during installation in ubuntu 12.04

### ISSUE THREAD

**Issue by kingqiu** [cantino/huginn#949]
Hi, guys. I'm trying to install the latest version of huginn in ubuntu 12.04 by following the quick start guide and Novice setup guide. Now I've done all the setup of environment including the mysql installation, but got following error during running "bundle exec rake db:migrate":

rake aborted!
Devise.secret_key was not set. Please add the following to your Devise initializer:

  config.secret_key = 'a21eaf4f768c8e17796923fbb16642079d41747256dc234634550c9be89675f7d9035d713fec42ec8ed04fa3835dbd1171d7a8582fc2d126c4a41768c44c2545'

Please ensure you restarted your application after installing Devise or setting the key.
/usr/local/rvm/gems/ruby-2.2.1/gems/devise-3.4.1/lib/devise/rails/routes.rb:480:in `raise_no_secret_key'
/usr/local/rvm/gems/ruby-2.2.1/gems/devise-3.4.1/lib/devise/rails/routes.rb:209:in `devise_for'
/bazhua/huginn/config/routes.rb:74:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.2/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
/usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.2/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
/usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.2/lib/action_dispatch/routing/route_set.rb:410:in `draw'
/bazhua/huginn/config/routes.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/application/routes_reloader.rb:40:in `each'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/application/routes_reloader.rb:16:in `reload!'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/file_update_checker.rb:75:in `call'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/file_update_checker.rb:75:in `execute'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/application/routes_reloader.rb:27:in `updater'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/application.rb:352:in `initialize!'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/railtie.rb:194:in `public_send'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/railtie.rb:194:in `method_missing'
/bazhua/huginn/config/environment.rb:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.2/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

===========================================
Did I miss any configurations? Thanks.

**Comment by cantino** [comment]
Hey @kingqiu, is this our `capistrano` based guide, or @dsander's one (https://github.com/cantino/huginn/pull/872)?

In either case, it looks to me like the `.env` file isn't being loaded correctly.  Is it present in the working directory and configured for production?

**Comment by kingqiu** [comment]
Hi @cantino, I just followed the quick start guide, not using capistrano. Yes, it's in the working directory that I couldn't find .env.example file indeed. 
After I submitted the issue, I found a manual installation guide here: https://github.com/dsander/huginn/blob/deployment-guide/doc/manual/README.md . Should I follow this one? Thanks.

**Comment by cantino** [comment]
Did you rename .env.example to .env and edit it? Sorry I couldn't tell from
your answer. Yes, you could definitely try following that installation
guide.

**Comment by kingqiu** [comment]
hi @cantino , I've re-installed huginn by following that installation guide. The process running well until the last step. I've got the prompts of '502 bad gateway' when trying to access my huginn as "http://121.201.63.37:3000".
<img width="804" alt="screen shot 2015-08-01 at 5 07 26 pm" src="https://cloud.githubusercontent.com/assets/5411939/9021342/19d9258a-3870-11e5-8796-8e3d1efa0a14.png">

Because I don't have domain setting for huginn setting, I have to set the IP address instead of domain name in nginx file(/etc/nginx/sites-available/huginn) as follow. So I'm not quite sure whether that's the cause of the issue. Any suggestions? Thanks.

###################################
##         configuration         ##
###################################
##
## See installation.md#using-https for additional HTTPS configuration details.

upstream huginn {
  server unix:/home/huginn/huginn/tmp/sockets/unicorn.socket fail_timeout=0;
}

## Normal HTTP host
server {
  listen 0.0.0.0:3000 default_server;
  listen [::]:3000 ipv6only=on default_server;
  server_name 121.201.63.37 ## Replace this with something like huginn.example.com
  server_tokens off; ## Don't show the nginx version number, a security best practice
  root /home/huginn/huginn/public;

**Comment by dsander** [comment]
Hi @kingqiu,

a few things to check:

* did you modify the `Procfile` to use one of the examples for production?
* after you started huginn, does the unicorn socket file (`/home/huginn/huginn/tmp/sockets/unicorn.socket`) exist? 
* what are the contents of `/home/huginn/huginn/log/production.log`, `/home/huginn/huginn/log/unicorn.log` and `/var/log/nginx/huginn_error.log`?

**Comment by kingqiu** [comment]
hi @dsander,

- did you modify the Procfile to use one of the examples for production?
I didn't change any settings in Procfile cause I saw the development part are uncommented. Should I uncomment one section of the production part?
###############################
#         DEVELOPMENT         #
###############################

# Procfile for development using the new threaded worker (scheduler, twitter str
eam and delayed job)
web: bundle exec rails server
jobs: bundle exec rails runner bin/threaded.rb

# Old version with separate processes (use this if you have issues with the thre
aded version)
# web: bundle exec rails server
# schedule: bundle exec rails runner bin/schedule.rb
# twitter: bundle exec rails runner bin/twitter_stream.rb
# dj: bundle exec script/delayed_job run

###############################
#         PRODUCTION          #
###############################

# Using the threaded worker (consumes less RAM but can run slower)
# web: bundle exec unicorn -c config/unicorn.rb
# jobs: bundle exec rails runner bin/threaded.rb

- after you started huginn, does the unicorn socket file (/home/huginn/huginn/tmp/sockets/unicorn.socket) exist?
No, the unicorn.socket file doesn't exist.

- what are the contents of /home/huginn/huginn/log/production.log
The contents in production.log are all Info related, like:
I, [2015-08-01T16:40:50.103487 #7884]  INFO -- : Migrating to DeviseCreateUsers (20120728210244)
I, [2015-08-01T16:40:50.164721 #7884]  INFO -- : Migrating to AddAdminToUsers (20120728215449)
I, [2015-08-01T16:40:50.180945 #7884]  INFO -- : Migrating to EnableLockableStrategyForDevise (20120919061122)
I, [2015-08-01T16:40:50.244328 #7884]  INFO -- : Migrating to AddUsernameToUsers (20120919063304)
I, [2015-08-01T16:40:50.294251 #7884]  INFO -- : Migrating to CreateEvents (20121216025930)

- /home/huginn/huginn/log/unicorn.log 
The unicorn.log doesn't exist.

- and /var/log/nginx/huginn_error.log?
The contents in huginn_error.log are:

2015/08/01 17:01:36 [crit] 9188#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "121.201.63.37:3000"
2015/08/01 17:01:36 [crit] 9188#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "121.201.63.37:3000"
2015/08/01 17:01:52 [crit] 9188#0: *4 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "121.201.63.37:3000"
2015/08/01 17:01:52 [crit] 9188#0: *4 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "121.201.63.37:3000"
2015/08/01 17:01:59 [crit] 9188#0: *4 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "121.201.63.37:3000"
2015/08/01 17:01:59 [crit] 9188#0: *4 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "121.201.63.37:3000"
2015/08/01 17:02:01 [crit] 9188#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "121.201.63.37:3000"
2015/08/01 17:02:01 [crit] 9188#0: *1 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "121.201.63.37:3000"
2015/08/01 17:03:32 [crit] 9188#0: *11 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "121.201.63.37:3000"
2015/08/01 17:03:32 [crit] 9188#0: *11 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "121.201.63.37:3000"
2015/08/01 17:03:35 [crit] 9188#0: *14 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET /index.html HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/index.html", host: "121.201.63.37:3000"
2015/08/01 17:03:35 [crit] 9188#0: *14 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET /index.html HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "121.201.63.37:3000"
2015/08/01 17:03:53 [crit] 9188#0: *11 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET /index.html HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/index.html", host: "121.201.63.37:3000"
2015/08/01 17:03:53 [crit] 9188#0: *11 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET /index.html HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "121.201.63.37:3000"
2015/08/01 17:03:54 [crit] 9188#0: *11 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "121.201.63.37:3000"
2015/08/01 17:03:54 [crit] 9188#0: *11 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "121.201.63.37:3000"
2015/08/01 17:03:55 [crit] 9188#0: *14 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET /public HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/public", host: "121.201.63.37:3000"
2015/08/01 17:03:55 [crit] 9188#0: *14 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET /public HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "121.201.63.37:3000"
2015/08/01 17:05:56 [crit] 9188#0: *23 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET /public HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/public", host: "121.201.63.37:3000"
2015/08/01 17:05:56 [crit] 9188#0: *23 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET /public HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "121.201.63.37:3000"
2015/08/01 17:05:57 [crit] 9188#0: *23 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "121.201.63.37:3000"
2015/08/01 17:05:57 [crit] 9188#0: *23 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "121.201.63.37:3000"
2015/08/01 17:05:58 [crit] 9188#0: *23 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET /index.html HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/index.html", host: "121.201.63.37:3000"
2015/08/01 17:05:58 [crit] 9188#0: *23 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET /index.html HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "121.201.63.37:3000"
2015/08/01 17:05:59 [crit] 9188#0: *30 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET /index HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/index", host: "121.201.63.37:3000"
2015/08/01 17:05:59 [crit] 9188#0: *30 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET /index HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "121.201.63.37:3000"
2015/08/01 17:11:00 [crit] 9188#0: *33 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET /index HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/index", host: "121.201.63.37:3000"
2015/08/01 17:11:00 [crit] 9188#0: *33 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET /index HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "121.201.63.37:3000"
2015/08/01 17:11:01 [crit] 9188#0: *33 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/", host: "121.201.63.37:3000"
2015/08/01 17:11:01 [crit] 9188#0: *33 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "121.201.63.37:3000"

**Comment by dsander** [comment]
> Edit the Procfile and choose one of the suggested versions for production

@kingqiu Yes, in production you need to run unicorn. After you changed the Procfile you need to re-export the init script:
```
sudo rm /etc/init/huginn*
sudo foreman export upstart -a huginn /etc/init
sudo restart huginn
```

**Comment by kingqiu** [comment]
I've uncommented the production section as:

# Procfile for development using the new threaded worker (scheduler, twitter str
eam and delayed job)
#web: bundle exec rails server
#jobs: bundle exec rails runner bin/threaded.rb

# Old version with separate processes (use this if you have issues with the thre
aded version)
# web: bundle exec rails server
# schedule: bundle exec rails runner bin/schedule.rb
# twitter: bundle exec rails runner bin/twitter_stream.rb
# dj: bundle exec script/delayed_job run

###############################
#         PRODUCTION          #
###############################

# Using the threaded worker (consumes less RAM but can run slower)
web: bundle exec unicorn -c config/unicorn.rb
jobs: bundle exec rails runner bin/threaded.rb

# Old version with separate processes (use this if you have issues with the threaded ver
sion)
# web: bundle exec unicorn -c config/unicorn.rb
# schedule: bundle exec rails runner bin/schedule.rb
# twitter: bundle exec rails runner bin/twitter_stream.rb

Then I re-export the init script as root user:
rm /etc/init/huginn*
foreman export upstart -a huginn /etc/init
restart huginn

In case it doesn't work, I reboot the nginx server as well. But the unicorn.log still not exists. The error info in huginn_error.log still the same:
2015/08/01 22:44:56 [crit] 22472#0: *4 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (2: No such file or directory) while connecting to upstream, client: 112.95.202.9, server: 121.201.63.37, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "121.201.63.37:3000"

Is there any place I can check why unicorn doesn't work?

**Comment by dsander** [comment]
Did you make any changes to the unicorn config file `config/unicorn.rb`? Except for the `worker_processes` everything should stay the same as `config/unicorn.rb.example`

**Comment by kingqiu** [comment]
No, I didn't make any changes on that file.

wd = "/home/huginn/huginn"

app_path = wd

worker_processes 2
preload_app true
timeout 180
listen "#{wd}/tmp/sockets/unicorn.socket"

working_directory app_path

rails_env = ENV['RAILS_ENV'] || 'production'

# Log everything to one file
stderr_path "log/unicorn.log"
stdout_path "log/unicorn.log"

# Set master PID location
pid "#{wd}/tmp/pids/unicorn.pid"

before_fork do |server, worker|
  ActiveRecord::Base.connection.disconnect!
  old_pid = "#{server.config[:pid]}.oldbin"
  if File.exist?(old_pid) && server.pid != old_pid
    begin
      Process.kill("QUIT", File.read(old_pid).to_i)
    rescue Errno::ENOENT, Errno::ESRCH
      # someone else did our job for us
    end
  end
end

after_fork do |server, worker|
  ActiveRecord::Base.establish_connection
end

**Comment by dsander** [comment]
Thats odd, do you have a `/var/log/upstart/huginn-web-1.log` logfile?

**Comment by kingqiu** [comment]
No, there is no such logfile in /var/log/upstart/.

-rw-r----- 1 root root  120 Jul 31 20:23 console-setup.log.1.gz
-rw-r----- 1 root root  150 Jul 31 20:23 container-detect.log.1.gz
-rw-r----- 1 root root   87 Jul 31 20:23 dbus.log.1.gz
-rw-r----- 1 root root  386 Jun 23  2013 guestfsd.log.1.gz
-rw-r----- 1 root root 2609 Jul 31 20:23 modemmanager.log.1.gz
-rw-r----- 1 root root   69 Jul 31 20:23 module-init-tools.log.1.gz
-rw-r----- 1 root root  409 Jul 31 21:42 mysql.log.1.gz
-rw-r----- 1 root root   73 Mar 24  2013 network-interface-eth0.log.1.gz
-rw-r----- 1 root root   62 Mar 24  2013 network-interface-lo.log.1.gz
-rw-r----- 1 root root  112 Mar 24  2013 network-interface-security-networking.log.1.gz
-rw-r----- 1 root root  130 Jul 31 20:23 network-interface-security-network-interface_eth0.log.1.gz
-rw-r----- 1 root root  119 Mar 24  2013 network-interface-security-network-interface_lo.log.1.gz
-rw-r----- 1 root root  173 Jul 31 03:21 procps.log.1.gz
-rw-r----- 1 root root  221 Jul 31 20:23 procps-static-network-up.log.1.gz
-rw-r----- 1 root root  221 Jul 31 20:23 procps-virtual-filesystems.log.1.gz
-rw-r----- 1 root root   84 Mar 24  2013 rsyslog.log.1.gz
-rw-r----- 1 root root 1439 Jul 31 20:23 ureadahead.log.1.gz

**Comment by dsander** [comment]
I am assuming you used the guide which still uses [upstart](https://github.com/dsander/huginn/blob/1f80e3d113e3c05e2bef2a58569c97cccd622705/doc/manual/installation.md) and not the update I pushed [yesterday](https://github.com/dsander/huginn/blob/deployment-guide/doc/manual/installation.md)?

When the export worked you should have a `/etc/init/huginn.conf`file and a few other ones like `huginn-web-1.conf`, `huginn-jobs-1.conf`

Do did run `sudo start huginn`?

**Comment by kingqiu** [comment]
Yes, I've already run "sudo start huginn" . And the files you mentioned in /etc/init are all there including:

-rw-r--r-- 1 root root   50 Aug  1 22:59 huginn.conf
-rw-r--r-- 1 root root 1789 Aug  1 22:59 huginn-jobs-1.conf
-rw-r--r-- 1 root root   49 Aug  1 22:59 huginn-jobs.conf
-rw-r--r-- 1 root root 1787 Aug  1 22:59 huginn-web-1.conf
-rw-r--r-- 1 root root   49 Aug  1 22:59 huginn-web.conf

**Comment by kingqiu** [comment]
I'm not quite sure if it's cased by my rake setting. Cause I've got error messages when running "rake production:status"

root@i-zjt7fn3m:~# sudo rake prodction:status
sudo: rake: command not found
root@i-zjt7fn3m:~# rake production:status
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

**Comment by dsander** [comment]
Oh, i see, that looks a bit mixed up. The novice setup is intended for development setups, my new guide is for production installations on a remote server, and does not work with rbenv or rvm setup because then can cause strange problems like the one you are having now.

On top of that you seem to have started with the new guide when it was still using upstart and then pulled the changes which caused more confusion, sorry about that.

I don't know what kind of server you are using and if you just want to install huginn, if you can start from scratch it would probably the way to reinstall the server and use the [current version of the new guide](https://github.com/dsander/huginn/blob/6ead920ae0ba9ce80faf539ed7a86dfdad092b68/doc/manual/installation.md)

When thats not an option the following steps will probably fix the issue:

* disable or uninstall rvm
* [install ruby from source](https://github.com/dsander/huginn/blob/6ead920ae0ba9ce80faf539ed7a86dfdad092b68/doc/manual/installation.md#2-ruby)
*  [install the gems](https://github.com/dsander/huginn/blob/6ead920ae0ba9ce80faf539ed7a86dfdad092b68/doc/manual/installation.md#install-gems)
* run `sudo production:check` until no don't get any failures
* export the init script `sudo production:export`

**Comment by kingqiu** [comment]
OK, I'll try to re-install from the scratch and let you know the result. Thanks.

**Comment by kingqiu** [comment]
hello @dsander, it works now after the re-installation. Thanks a lot.
May I know the major differences between the 'development' and 'production' version? If I want to switch back to development status from current version, can I do that?

**Comment by dsander** [comment]
Well the main difference is the rails environment, the development environment has no caching, code reloading (which does not work for the background workers, you need to restart them after you did changes) and on the fly asset generation, if you are developing an agent or want to do other changes to huginn you can comment out `RAILS_ENV=production` in `.env`, reexport and remove the `public/assets` directory.
