### ISSUE TITLE
Email setting

### ISSUE THREAD

**Issue by kingqiu** [cantino/huginn#956]
Can someone share me your workable email setting in .env file in huginn's production mode? I've configured but the job runs with error "Net::ReadTimeout /usr/local/lib/ruby/2.2.0/net/protocol.rb:158:in `rescue in rbuf_fill'".

Here is mine:
> SMTP_DOMAIN=mail.ismtown.com
> SMTP_USER_NAME=jim@ismtown.com
> SMTP_PASSWORD=xxxxxxxx
> SMTP_SERVER=smtp.ym.163.com
> SMTP_PORT=994
> SMTP_AUTHENTICATION=plain
> SMTP_ENABLE_STARTTLS_AUTO=true

> # Send emails when running in the development Rails environment.
> SEND_EMAIL_IN_DEVELOPMENT=false

> # The address from which system emails will appear to be sent.
> EMAIL_FROM_ADDRESS=jim@ismtown.com

**Comment by cantino** [comment]
This is what I use:

```
SMTP_DOMAIN=mydomain.com
SMTP_USER_NAME=huginn@mydomain.com
SMTP_PASSWORD=myrealemailpassword
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true

# The address from which system emails will appear to be sent.
EMAIL_FROM_ADDRESS=huginn@mydomain.com
```

**Comment by kingqiu** [comment]
It's OK now. The issue is my setting of SMTP_DOMAIN was wrong. The correct format should be like @cantino 's. Thanks.
