### ISSUE TITLE
Help with match and replace

### ISSUE THREAD

**Issue by johnnyzen** [cantino/huginn#962]
Hi all

I am trying to match and replace various events from different sources using just one formatting agent - which I use the url to determine the source.

```json
{
  "instructions": {
    "source": "{{formatted_source}}"
  },
  "matchers": [
    {
      "path": "{{link}}",
      "regexp": "regex_replace: 'W*((?i)bbc(?-i))W*', 'BBC News'",
      "to": "formatted_source"
    },
    {
      "path": "{{link}}",
      "regexp": "regex_replace: 'W*((?i)telegraph(?-i))W*', 'Telegraph News'",
      "to": "formatted_source"
    }
  ],
  "mode": "merge",
  "skip_agent": true,
  "skip_created_at": true
}
```

I am not sure if I can use regex_replace within the regexp?

Not getting any results, and wondered if someone could assist me

Many thanks

**Comment by schulzpin** [comment]
I'm also interested in some kind of tutorial about using regex_replace function. In what agent should I use it? Is there a way to cut a piece of text/code from the incoming feed?
It would be great if someone could make detailed wiki page with few examples.

**Comment by cantino** [comment]
`regex_replace` is a Liquid filter and I don't think it can currently be used inside of the regex key in an EventFormattingAgent.

I don't think the matchers groups of an EventFormattingAgent can currently do replacement.

As an aside, @knu, is `path` here confusingly named?  It looks like it's the actual data to match, not the JSONPath to that data.

**Comment by johnnyzen** [comment]
Would I be able to pay someone to get this done or is there another way ?

Where can regex_replace be used ? maybe I can do in the website agent?

**Comment by johnnyzen** [comment]
Decided to handle this regex client side, as cant find a solution at the moment.

Thanks all for help and loving huginn. Thanks for the great software :)

**Comment by cantino** [comment]
What do you think a regex replace should look like?  We could add it as a new feature of the EventFormattingAgent.

**Comment by cantino** [comment]
Closing since we haven't heard back.  Hope it's working for you!
