### ISSUE TITLE
Help with production deployment

### ISSUE THREAD

**Issue by johnnyzen** [cantino/huginn#964]
Hi all

Looking for someone to help set up production.

Would need someone to move from terminal to another provider and setting up a robust service.

Any takers?

Best

Johnny

**Comment by cantino** [comment]
Hey @johnnyzen, welcome to the project!

You may be able to find someone here who would set this up for you, or you could try following these instructions: https://github.com/cantino/huginn/pull/872

**Comment by cantino** [comment]
Do you still need help @johnnyzen?
