### ISSUE TITLE
development: gem version too low (guard-livereload)

### ISSUE THREAD

**Issue by K1773R** [cantino/huginn#969]
I updated to ruby 2+ (was using 1.9.3) and had the problem that bundle always used guard-livereload 1.4 instead of 2.4. Obviously running in development this crashed everything...

after editing the Gemfile
```
  gem 'guard-livereload', '~> 2.4'
```
and a bundle update, it worked again.

**Comment by cantino** [comment]
Would you mind making a PR that puts this as `>= 2.4` in the Gemfile?

**Comment by cantino** [comment]
Actually, our Gemfile.lock is on 2.2.0, so I don't know how you were using 1.4.

**Comment by cantino** [comment]
I assume you bundled and everything?

**Comment by K1773R** [comment]
Yes i did, but it always took 1.4. Maybe it got cached? I have no idea about the inner workings of bundle...

**Comment by cantino** [comment]
Odd.  Would you mind making a PR for `>= 2.2`?

**Comment by K1773R** [comment]
i made a PR for >= 2.2

**Comment by cantino** [comment]
Thanks!
