### ISSUE TITLE
TwitterUserAgent shows no Summary of Tweets like TwitterStreamAgent

### ISSUE THREAD

**Issue by mustang2015** [cantino/huginn#986]
Finally got Huginn working on my rpi2. Everything seems okay.
But the TwitterUserAgent shows no Summary of Recent Tweets like TwitterStreamAgent. It just stays grey.

**Comment by dsander** [comment]
Hi @mustang2015, 

the `TwitterUserAgent` does not have a summary page, you should see the events created by this agent when you click on the `Events` link in the agent detail view.

**Comment by mustang2015** [comment]
Hi dsander

okay but are there any plans to make a summary page? i know i can read the tweet in text at event. but its more convinient in the summary page.

**Comment by dsander** [comment]
None that I know of. Huginn is more about processing events and taking actions based on them. You could use a `JavascriptAgent` that  logs the received tweets, the log output would then be accessible via the `Logs` tabs of the JavascriptAgent.

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further!
