### ISSUE TITLE
TwitterUserAgent creates same events over and over again

### ISSUE THREAD

**Issue by mustang2015** [cantino/huginn#987]
I get multiple events of two old tweets. It does not pull any newer tweets

**Comment by dsander** [comment]
That is strange, the `TwitterUserAgent` makes sure it just creates events for new tweets. Are the twitter `id` attributes of the event payload also identical?

**Comment by mustang2015** [comment]
I did a fresh install with DietPi. Seems to be working fine now.

**Comment by cantino** [comment]
Glad to hear it!

**Comment by mustang2015** [comment]
Okay it somehow still does that. IDs are all identical. 
Also the TwitterUserAgent gets Stuck in the queue.

**Comment by mustang2015** [comment]
A reboot sometimes does wonders. Should have thought of it in the first place. Seems to be working fine - for now.
