### ISSUE TITLE
Exception Mysql2 links to delayed_jobs

### ISSUE THREAD

**Issue by Free16t** [cantino/huginn#991]
Hi, 
I update Huginn today and I have now the `delayed_job_active_record`. Now, Huginn is shutting down itself with this error:

>Exception Mysql2::Error: Incorrect string value: '\xF0\x9F\x98\x89</...' for column 'last_error' at row 1: UPDATE `delayed_jobs` SET `last_error` = 'Mysql2::Error: Incorrect string value: \'\\xF0\\x9F\\x98\\x89</...\' for column \'message\' at row 1: INSERT INTO `agent_logs` (`level`, `message`, `agent_id`, `created_at`, `updated_at`) VALUES (4, \'Exception during check. Mysql2::Error: Incorrect string value: \\\'\\\\xF0\\\\x9F\\\\x98\\\\x89</...\\\' for column \\\'message\\\' at row 1: INSERT INTO `agent_logs` (`level`, `message`, `agent_id`, `created_at`, `updated_at`) VALUES (4, \\\'Failed to fetch http://www.planet-libre.org/feed.php?type=rss with message \\\\\\\'Mysql2::Error: Incorrect string value: \\\\\\\'\\\\\\\\xF0\\\\\\\\x9F\\\\\\\\x98\\\\\\\\x89</...\\\\\\\' for column \\\\\\\'payload\\\\\\\' at row 1: INSERT INTO `events` (`payload`, `agent_id`, `user_id`, `expires_at`, `created_at`, `updated_at`) VALUES 
> /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `execute'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/mysql2_adapter.rb:252:in `exec_delete'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:114:in `update'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `update'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/relation.rb:88:in `_update_record'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/persistence.rb:513:in `_update_record'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/locking/optimistic.rb:79:in `_update_record'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/attribute_methods/dirty.rb:127:in `_update_record'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/callbacks.rb:310:in `block in _update_record'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:88:in `call'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:88:in `_run_callbacks'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:776:in `_run_update_callbacks'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/callbacks.rb:310:in `_update_record'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/timestamp.rb:70:in `_update_record'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/persistence.rb:502:in `create_or_update'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/callbacks.rb:302:in `block in create_or_update'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:117:in `call'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:117:in `call'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:505:in `call'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:505:in `call'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:92:in `_run_callbacks'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:776:in `_run_save_callbacks'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/callbacks.rb:302:in `create_or_update'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/persistence.rb:142:in `save!'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/validations.rb:43:in `save!'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/transactions.rb:291:in `block in save!'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/transactions.rb:220:in `transaction'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/activerecord-4.2.2/lib/active_record/transactions.rb:291:in `save!'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:224:in `reschedule'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:273:in `handle_failed_job'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:213:in `block in run'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:213:in `rescue in run'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:202:in `run'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
10:24:02 jobs.1 | /usr/local/lib/ruby/2.1/benchmark.rb:294:in `realtime'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
10:24:02 jobs.1 | /usr/local/lib/ruby/gems/2.1/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
10:24:02 jobs.1 | bin/threaded.rb:49:in `block (2 levels) in <top (required)>'
10:24:02 jobs.1 | bin/threaded.rb:19:in `safely'
10:24:02 jobs.1 | bin/threaded.rb:46:in `block in <top (required)>'

>10:24:02 jobs.1 |
10:24:02 jobs.1 | Terminating myself ...
10:24:02 jobs.1 | Exiting...
10:24:02 jobs.1 | Scheduler stopped ...
10:24:02 jobs.1 | Twitter stream stopped ...
10:24:02 jobs.1 | exited with code 0
10:24:02 system | sending SIGTERM to all processes

>10:24:02 web.1  | [2015-08-25 10:24:02] FATAL SignalException: SIGTERM
10:24:02 web.1  |       /usr/local/lib/ruby/2.1/webrick/server.rb:170:in `select'
10:24:02 web.1  |       /usr/local/lib/ruby/2.1/webrick/server.rb:170:in `block in start'
10:24:02 web.1  |       /usr/local/lib/ruby/2.1/webrick/server.rb:32:in `start'
10:24:02 web.1  |       /usr/local/lib/ruby/2.1/webrick/server.rb:160:in `start'
10:24:02 web.1  |       /usr/local/lib/ruby/gems/2.1/gems/rack-1.6.4/lib/rack/handler/webrick.rb:34:in `run'
10:24:02 web.1  |       /usr/local/lib/ruby/gems/2.1/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
10:24:02 web.1  |       /usr/local/lib/ruby/gems/2.1/gems/railties-4.2.2/lib/rails/commands/server.rb:80:in `start'
10:24:02 web.1  |       /usr/local/lib/ruby/gems/2.1/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:80:in `block in server'
10:24:02 web.1  |       /usr/local/lib/ruby/gems/2.1/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:75:in `tap'
10:24:02 web.1  |       /usr/local/lib/ruby/gems/2.1/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:75:in `server'
10:24:02 web.1  |       /usr/local/lib/ruby/gems/2.1/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
10:24:02 web.1  |       /usr/local/lib/ruby/gems/2.1/gems/railties-4.2.2/lib/rails/commands.rb:17:in `<top (required)>'
10:24:02 web.1  |       bin/rails:4:in `require'
10:24:02 web.1  |       bin/rails:4:in `<main>'
10:24:02 web.1  | [2015-08-25 10:24:02] INFO  going to shutdown ...
10:24:02 web.1  | [2015-08-25 10:24:02] INFO  WEBrick::HTTPServer#start done.
10:24:02 web.1  | Exiting
10:24:02 web.1  | terminated by SIGTERM

Have you already saw this error?
Thank

**Comment by cantino** [comment]
Is the collation `utf8mb4_bin` for the DJ columns in your DB?  I'm surprised that this update would have caused this.  [Another thing you could try](http://stackoverflow.com/questions/21420122/how-to-turn-off-mysql-strict-mode-in-rails) is setting `strict: false` in your database.yml file.

I hope this doesn't indicate a deeper error in our updated gem.

/cc @knu, @dsander

**Comment by Free16t** [comment]
The tric works great :+1: I have no longer this error 
Thank a lot

**Comment by cantino** [comment]
Great!  Which change did you end up making?
