### ISSUE TITLE
Basic scenario

### ISSUE THREAD

**Issue by Yachtsman** [cantino/huginn#992]
So. I have two agents configured:
WebHook Agent 
and 
Slack Agent which has WHA as the Sources. 
I have to send to Slack the message with the source details. 
How can I extract them and format the Slack message?

**Comment by cantino** [comment]
Welcome @Yachtsman!  Take a look at the EventFormattingAgent.

**Comment by Yachtsman** [comment]
Not sure how it can help me. How I can access the incoming from the WebHooksAgent data in SlackAgent?

**Comment by cantino** [comment]
You make an EventFormattingAgent, a WebhookAgent, and a SlackAgent.  Have the EventFormattingAgent subscribe to the WebhookAgent and the SlackAgent subscribe to the EventFormattingAgent.

**Comment by Yachtsman** [comment]
OK. That's already clear for me. But how could I access the data from the previous agent in the current one.

**Comment by cantino** [comment]
Oh, ok.  Could you give a larger example of what data you're trying to access?

**Comment by Yachtsman** [comment]
So.
I'm receiving something like https://developer.pagerduty.com/documentation/rest/webhooks

![screenshot from 2015-08-30 10 30 59](https://cloud.githubusercontent.com/assets/897428/9566170/3e67d268-4f02-11e5-8655-2e88b0b36d63.png)

And have to post it to Slack. How can I access the source data to put it to the "message" field of the SlackAgent?

**Comment by cantino** [comment]
If you look at one of the Events created by this WebhookAgent, you should see that it's contents is the JSON data that was located at `messages` in the webhook.  Is it?  If so, you'd reference any key of that data in a receiving Agent.  I'm sorry, I'm not confident that I'm understanding your question.

**Comment by cantino** [comment]
Did you figure this out?

**Comment by Yachtsman** [comment]
Yes. Thank you. It just post nothing if the JSON key is empty. Not sure if it's a bug.
