### ISSUE TITLE
R14 Memory Quota exceeded on Heroku

### ISSUE THREAD

**Issue by jbaylin** [cantino/huginn#993]
Upon deployment to Heroku with a PostgreSQL DB and NOT on a free Heroku Tier, I'm getting a high number of R14 memory issues.  I believe this is from the number of filters in certain agents being quite high, but not sure.

For reference, I have 3 agents all working on many filters/terms.  2 Twitter Stream (Events and Count) and 1 Peak Detector Agent.

Terms/Filters
https://www.dropbox.com/s/o0p4s6el2uuauqh/Screenshot%202015-08-28%2016.36.00.png?dl=0

Single Error
https://www.dropbox.com/s/iou7hjwr40aws35/Screenshot%202015-08-28%2016.37.50.png?dl=0

Many Errors
https://www.dropbox.com/s/x6f1nao1flpkbcp/Screenshot%202015-08-28%2016.38.36.png?dl=0

**Comment by mikalauskas** [comment]
I think 512M RAM pretty low for normal work, especially for Twitter stream, check out these requirements https://github.com/cantino/huginn/blob/master/doc/manual/requirements.md 

I'm using digitalocean 20$ node (2core, 2G ram,ssd) 74 agents doing well ;)

**Comment by jbaylin** [comment]
Yep - switching over to DigitalOcean.  Even upgrading to paid on Heroku doesn't necessarily mean you're getting >2gb :) Heroku good to start.

Any Ansible Playbooks or other config recommendations for getting DO setup the right way?

Obviously you can do the Ruby on Rails/Postgresql/Nginx etc. configuration.

**Comment by virtadpt** [comment]
@jbaylin I'm running Huginn on DO.  I used RVM to install Ruby into a blank VM, and the Huginn manual installation instructions.

**Comment by cantino** [comment]
Be sure to check out the new installation guide in doc/ by @dsander!

**Comment by jbaylin** [comment]
@virtadpt @cantino thanks on both accounts.  one question on huginn on DO w/ postgres 9.4.4 specifically (largely because of the jsonb support added recently).  14.04 doesn't support 9.4.4 (14.10) does.  DO doesn't have a droplet that is 14.10 . tried 15.04 -- ran into some problem around nginx install

any thoughts?

**Comment by dsander** [comment]
@jbaylin I think huginn will not benefit from JSONB since we just serialize data to json use normal sql queries otherwise we could not support mysql. I did only test the installation on the LTS versions of ubuntu, you could try to install postgres 9.4 on 14.04 via a ppa.

**Comment by jbaylin** [comment]
@dsander I've made some other minor changes on a fork so that the JSONB field is "queryable" - i'll give ppa a shot, but hmmm :+1: thanks

**Comment by jbaylin** [comment]
Boom :)

https://askubuntu.com/questions/633919/how-install-postgresql-9-4/633923#633923?newreg=579fada3545e469885d7067576916c53

http://www.rogerpence.com/2015/01/02/install-postgres-9-4-on-ubuntu/

**Comment by virtadpt** [comment]
@jbaylin I'm running 14.04 LTS with MySQL because it has support for utf8mb4, while Postgres doesn't.

**Comment by dsander** [comment]
@virtadpt Postgres does not need a special uftmb4 encoding, it just handles utf8 properly per default. The utf8 encoding limitation is something mysql invented for itself :smile: 

@jbaylin Interesting, can other postgres users benefit from the changes you made?
