### ISSUE TITLE
how to scrape the new reply to a post in the forum?

### ISSUE THREAD

**Issue by TracyHill** [cantino/huginn#994]
I want to make each new reply to a post as the rss new entry.
Like this post: http://forums.thefashionspot.com/f52/sophia-ahrens-218027-17.html
But I found two questions:
1.Each new reply has a differnt ID , the id always changing and no class element alike found 
how can i locate and scrape the new reply?
2. When reply up to 15, the page will turn to next one. 
But I only want to create one agent. How to fix this?

**Comment by cantino** [comment]
Try http://selectorgadget.com.  It looks like `.padding-left` would work.

The pagination is harder, and I don't really have a good solution for it without extending the WebsiteAgent somehow to be able to follow links.

**Comment by virtadpt** [comment]
You could click on "Thread Tools" and pick "Show Printable Version".  It might be easier to scrap that way.

You may also want to see if this RSS feed has the content you want: http://forums.thefashionspot.com/external.php?type=RSS2&forumids=52

**Comment by TracyHill** [comment]
@cantino  Selectorgadget really helps, I can easily scarp the post. However, the number of entry seems to have a little problems. I will try to fix that myself, Thank you so much.

**Comment by TracyHill** [comment]
@virtadpt  The  "Show Printable Version" makes it easier to scape the post and it can show 30 posts in one page which helps in case that  pagination is hard to realize.

**Comment by cantino** [comment]
Glad it's working!  Is it okay if we close this issue?

**Comment by TracyHill** [comment]
@cantino of course. Thanks for help.
