### ISSUE TITLE
Add postgres database

### ISSUE THREAD

**Issue by MOZGIII** [cantino/huginn#995]
MySQL is good, but PostgreSQL is also good.
How about adding a way to use PostgreSQL with custom deployment?

This would require some changes to `Gemfile` - probaby add a `mysql` and `postgres` groups.
Everything else should be fine since it seems to already work on Heroku.

**Comment by cantino** [comment]
Huginn works quite well with Postgresql, actually.  You can make those changes, or, as a hack, set ON_HEROKU=true in the environment.

**Comment by MOZGIII** [comment]
I figured that out already. However, my deployment is nothing to do with Heroku.

Also, when you do that, bundler complains about double gem inclusion, so that dows not work cleanly.
You also haveto remove `gem 'pg'` from `on_heroku` block (or just fix the block). After that use `bundle install` without deployment to recalculate `Gemfile.lock`, and then with deployment. After that it works.
Overall I feels like `on_heroku` is a very durty hack, not worth it.

**Comment by cantino** [comment]
Agreed.  Would you be interested in adding better Postgresql support?

**Comment by MOZGIII** [comment]
Probably, if I'll have some free time.

**Comment by cantino** [comment]
We definitely appreciate any contributions you can make!

**Comment by MOZGIII** [comment]
I'd just add separate bundler groups for mysql and postgres, it's pretty simple.
The hard part though is to fix all places in the docs and automation scripts to use bundler's `without` correctly:

```
bundle install --without development test mysql
```

```
bundle install --without development test postgres
```

**Comment by MOZGIII** [comment]
I can implement actual code fixes today, but I don't know about fixing the docs.

**Comment by MOZGIII** [comment]
Btw, with https://github.com/rails/rails/blob/4-2-stable/railties/lib/rails/generators/rails/app/templates/config/environments/production.rb.tt#L25
Rails and heroky play well together.

**Comment by cantino** [comment]
Thanks!

Yea, Huginn runs pretty well on Heroku, although not on their free plan now that they've changed it.

/cc @dsander, who I think uses Postgresql.

**Comment by dsander** [comment]
Yes, everything works well on postgres. Changing the documentation everywhere would be some work, maybe the optional bundler groups @knu was working on in #822 would be an option?

**Comment by cantino** [comment]
I'm going to close this issue.  Please reopen if you want to discuss further!

**Comment by dsander** [comment]
Postgres is supported since some time, after configuring the database in the `.env` running `bundle` will install the `pg` gem and huginn will work with postgres perfectly.
